pylint-dev/pylint

pylint/interfaces.py, pylint/reporters/base_reporter.py, pylint/reporters/collecting_reporter.py, pylint/reporters/json_reporter.py, pylint/reporters/multi_reporter.py, pylint/reporters/text.py, pylint/testutils/reporter_for_tests.py, tests/extensions/test_broad_try_clause.py, tests/extensions/test_comparetozero.py, tests/test_self.py, tests/unittest_reporting.py
Another instalment of breaking up #4954.
Although the number of changed lines is quite high, it is basically adding typing to the same methods in a bunch of different (sub)classes.
=> Add typing for ``json_reporter`` and sub-classes

pylint/reporters/reports_handler_mix_in.py
No better way than to start the Friday morning with a small typing PR.
Small changes to break up #4954.
I moved `ReportsDict` as I felt it fitted much better there. The update to the docstring is because it incorrectly describes what is returned. There is no sorting and there is also no list of reports.
=> Fix typing of `ReportsHandlerMixIn`

ChangeLog, pylint/checkers/stdlib.py, tests/functional/u/unspecified_encoding_py38.py, tests/functional/u/unspecified_encoding_py38.txt
Closes #5029
/CC @Pierre-Sassoulas
=> Fix ``unspecified-encoding`` for ``Path.read_text()``

pylint/reporters/base_reporter.py, tests/test_self.py
| ✓   | 😨 Refactor         |
Small changes which are needed for further typing of `pylint/reporters`.
I ran the test suite and printed out all types of `BaseReporter.out`. It was only ever `io.TextIO` which also seems fair given what it is doing. However, perhaps somebody with more knowledge of the code base wants to take a look at this.
=> Add typing to `BaseReporter.out`

ChangeLog, pylint/checkers/refactoring/recommendation_checker.py, tests/functional/p/py_version/py_version_35.py, tests/functional/p/py_version/py_version_35.rc
Don't emit `consider-using-f-string` if `py-version` is set to `< 3.6`.
Closes #5019
=> Require Python 3.6 for consider f-string check

pylint/testutils/__init__.py, pylint/testutils/output_line.py, pylint/testutils/unittest_linter.py, tests/checkers/unittest_base.py, tests/checkers/unittest_classes.py, tests/checkers/unittest_deprecated.py, tests/checkers/unittest_exceptions.py, tests/checkers/unittest_format.py, tests/checkers/unittest_imports.py, tests/checkers/unittest_logging.py, tests/checkers/unittest_misc.py, tests/checkers/unittest_spelling.py, tests/checkers/unittest_stdlib.py, tests/checkers/unittest_strings.py, tests/checkers/unittest_typecheck.py, tests/checkers/unittest_variables.py, tests/extensions/test_check_docs.py, tests/extensions/test_check_raise_docs.py, tests/extensions/test_check_return_docs.py, tests/extensions/test_check_yields_docs.py, tests/extensions/test_confusing_elif.py, tests/extensions/test_while_used.py
We had two different `Message` classes. This renames one of them to become `OutputMessage` as I was running into conflicts with typing and imports.
=> Rename `pylint.testutil.Message` to `pylint.testutil.TestMessage`

pylint/utils/__init__.py, pylint/utils/utils.py
While working on the typing of `pylint/utils/utils.py` I noticed these two functions never get called. Therefore they seem like candidates for removal from the codebase.
=> Remove `safe_decode()` and `deprecated_option()` from utils

pylint/testutils/__init__.py, pylint/testutils/output_line.py, pylint/testutils/unittest_linter.py, tests/checkers/unittest_base.py, tests/checkers/unittest_classes.py, tests/checkers/unittest_deprecated.py, tests/checkers/unittest_exceptions.py, tests/checkers/unittest_format.py, tests/checkers/unittest_imports.py, tests/checkers/unittest_logging.py, tests/checkers/unittest_misc.py, tests/checkers/unittest_spelling.py, tests/checkers/unittest_stdlib.py, tests/checkers/unittest_strings.py, tests/checkers/unittest_typecheck.py, tests/checkers/unittest_variables.py, tests/extensions/test_check_docs.py, tests/extensions/test_check_raise_docs.py, tests/extensions/test_check_return_docs.py, tests/extensions/test_check_yields_docs.py, tests/extensions/test_confusing_elif.py, tests/extensions/test_while_used.py
The change introduced in #5043 creates numerous `pytest` warnings because the class name begins with `Test`. This causes it to throw this error:
```bash
PytestCollectionWarning: cannot collect test class 'TestingMessage' because it has a __new__ constructor (from: tests/checkers/unittest_deprecated.py)
class TestingMessage(
```
I don't really like the name `MessageTest` but couldn't come up with anything that doesn't start with `Test`.
=> Rename `TestMessage` to `MessageTest`

pylint/reporters/base_reporter.py, pylint/reporters/text.py
=> Add typing to text reporter

ChangeLog, pylint/checkers/variables.py, tests/functional/a/assign/assignment_expression.py
Fix false-positive `undefined-variable` for `y`.
```py
l = lambda x: y if (y := x) else None
```
=> Fix false-positive undefined-variable with Lambda, IfExp, and :=

pylint/checkers/base_checker.py, pylint/message/message.py, pylint/message/message_handler_mix_in.py, pylint/testutils/unittest_linter.py, pylint/typing.py, tests/message/unittest_message.py, tests/testutils/test_output_line.py
This adds typing to `add_message` and adds a new `NamedTuple` to `typing.py`. I add a deprecation warning for `Message`, but I'm not sure if it is even necessary. Is `Message` part of the public API? If not I can remove it.
The `type: ignore` in `tests/testutils/test_output_line.py` will be fixed in a follow-up PR. `OutputLine` needs a little refactor to only accept `int` for `column` and `line`. This will bring it in line with all other code that references `column` or `line`, where those are also `int`.
=> Type `add_message` and add `MessageLocationTuple`

pylint/message/message_handler_mix_in.py, pylint/utils/file_state.py
I can understand why the parameters were originally kept similar to `add_message()` but with the added method in  #5063 I think removing them leaves us with a cleaner method and way to call that method.
However, while writing this PR I wonder whether we should deprecate this rather than removing the parameters outright. Opinions?
=> Refactor of ``FileState.handle_ignored_message()``

ChangeLog, pylint/checkers/imports.py, pylint/message/message_handler_mix_in.py, tests/functional/u/useless/useless_suppression.py
This also adds a new method to ``MessagesHandlerMixIn`` which adds messages to the list of the ignored messages without doing anything else. 
This will be useful for some other ``useless-suppression`` false positives.
This closes #2366
=> Fix ``useless-suppression`` for ``wrong-import-order``

CONTRIBUTORS.txt, ChangeLog, pylint/config/find_default_config_files.py, setup.cfg
Fix the minimum version of the `toml` dependency as described in #5066.
Closes #5066
=> Update toml dependency to >=0.9.2

pylint/testutils/output_line.py, tests/testutils/test_output_line.py
This brings `OutputLine` in line with the classes dealing with `Message` by making the `line` and `column` attributes `int`. This has increased the size of the diff but I felt that making `line` and `column` `int` throughout the codebase would eventually be worthwhile. `OutputLine` in `csv` form still only consists of `str` (in fact we now make sure this is the case) but whenever we deal with it "internally" we can now assume `line` and `column` are `int`.
The tests have also been changed to accommodate for this.
=> Refactor and typing of OutputLine

pylint/checkers/design_analysis.py, tests/regrtest_data/hang/pkg4972/flask/__init__.py, tests/regrtest_data/hang/pkg4972/string/__init__.py, tests/test_regr.py
If a class could be inferred as an ancestor of itself then
the implementation of _get_parents could get caught in an infinite loop,
forever adding itself to to_explore. This could be possible by
monkeypatching an ancestor after class definition like in the following
simplified example:
```python
class Fake(module.Cls):
pass
module.Cls = Fake
```
Reproducing this is pretty tricky, but this integration test shows the behaviour on current `main`:
```sh
#!/bin/sh
HERE=$(readlink -f .)
VENV=$HERE/venv-repro
PIP=$VENV/bin/pip
python -m venv "$VENV"
PYLINT=$VENV/bin/pylint
$PIP install -e .
$PIP install flask
mkdir -p repro/flask/
touch repro/__init__.py
cat > repro/flask/__init__.py <<'EOF'
import …
```
=> Fix loop in too-many-ancestors when an inheritance cycle is inferred

pylint/reporters/base_reporter.py, pylint/testutils/tokenize_str.py, pylint/utils/pragma_parser.py
Similar to #4950 but now for `./pylint`, going directory for directory.
For this PR I would like to do 3 directories:
=> Typing for ``./pylint``, batch 1

pylint/checkers/refactoring/recommendation_checker.py, pylint/config/option.py, pylint/extensions/code_style.py, pylint/utils/utils.py
Followup to review comments here: https://github.com/PyCQA/pylint/pull/5024#discussion_r710739423
Partially addresses #5038
/CC: @Pierre-Sassoulas @scop
* Add `py-version` requirement to checker documentation
* Improve default value documentation for `py-version` (see image below)
* Improve option parser error message for `py-version`
--
https://pylint--5069.org.readthedocs.build/en/5069/technical_reference/features.html
=> Small py-version improvements

pylint/checkers/imports.py, pylint/checkers/stdlib.py, pylint/checkers/utils.py, pylint/graph.py, pylint/message/message_definition.py, pylint/message/message_handler_mix_in.py, setup.cfg, tests/test_self.py
After the recent typing and refactoring work I think it will be good to add some additional flags to `mypy` to prevent future typing issues.
This is one of those which can be turned on already without much changes to the code.
=> Add ``no-implicit-optional`` flag to ``mypy``

tests/test_regr.py
Tests introduced in #5062 actually raise `pytest` warnings. They had two marks which were not specified.
I did not know about this, but looking at [documentation](https://docs.pytest.org/en/stable/mark.html), marks can be used to group or drop certain types of tests.
We don't really use those and have not specified the `slow` or `serial` mark. Furthermore, the `slow` mark is incorrect as this test is not inherently slow but only should fail if it is slow. Thus, if we want to keep the mark I think we should change this.
I suggest removing them as they don't seem to serve a particular goal.
/CC @nelfin, @Pierre-Sassoulas 
Errors:
```bash
tests/test_regr.py:158 …
```
=> Remove ``pytest`` marks in test_regr

ChangeLog, pylint/checkers/utils.py, tests/functional/i/invalid/invalid_name.py, tests/functional/i/invalid/invalid_name.txt
`overrides_a_method()` was a little too strict for the `invalid-name` checker as it filtered out overwritten methods of the base `object` class. Therefore, `__init__` would never be checked.
This `utils` function is only used twice, the other instance being here:
https://github.com/PyCQA/pylint/blob/5e24aaa4dde2e3f06027cd0e18fabd96e408f519/pylint/checkers/classes.py#L1409-L1434
Based on the fact that the tests pass and the message that is being checked there I think it is safe to say that excluding overwriting `object` methods is also fine there.
Closes #3614
=> Fix ``invalid-name`` for overwritten base ``object`` methods

ChangeLog, pylint/checkers/format.py, pylint/message/message_handler_mix_in.py, tests/functional/u/useless/useless_suppression.py
Also changes ``add_ignored_message()`` to make ``nodes`` parameter optional.
Closes #4212
=> Fix false-positive ``useless-suppression`` for ``line-too-long``

pylint/testutils/decorator.py, pylintrc, tests/extensions/test_check_docs.py
While working on #5084 I noticed our current unittests don't actually fully test the `set_option` behaviour and we are therefore not able to correctly test some settings.
We need to call `set_option` to make the settings pass the validators and actually set them like they would have been in normal circumstances.
After adding this I found that we are actually missing a lot of options in the `options` attributes of some of the checkers. `docparams` which is needed for #5084 is missing `no_docstring_rgx` for example. We would need to add those for this to fully work, but I think they shouldn't be missing anyway.
I would like to know if this assertion is correct as I can then start work on …
=> Make test decorator use ``checker.set_option()``

pylint/config/option.py, pylint/utils/utils.py, tests/extensions/test_check_docs.py
Whenever a regex option is `None` we do not correctly convert those to patterns.
This also add additional typing and fixes a related issue with one of the tests.
Let me know if you would rather have this be 3 separate commits. It is a bit of a weird collection of `regex option` related stuff.
=> Fix empty regex options not converting to regex

pylint/lint/parallel.py, pylint/utils/__init__.py, pylint/utils/checkerstats.py
In anticipation of #5074 this moves the `merge_stats` function into the `checkerstats` namespace.
=> Move ``merge_stats`` to ``checkerstats.py``

pylint/pyreverse/dot_printer.py, pylint/pyreverse/printer.py, pylint/pyreverse/printer_factory.py
Ref #2079 (comment)
This allows ticking of `pylint/pyreverse/dot_printer.py`, `pylint/pyreverse/printer.py` and `pylint/pyreverse/printer_factory.py` from the list.
=> Add basic typing to ``pylint/pyreverse``

pylint/message/message_definition.py, pylint/message/message_definition_store.py, pylint/message/message_id_store.py
Ref https://github.com/PyCQA/pylint/issues/2079#issuecomment-928907726
This allows ticking of `pylint/message/message_definition.py`, `pylint/message/message_definition_store.py` and `pylint/message/message_id_store.py` from the list.
=> Add basic typing to ``pylint/message``

ChangeLog, doc/whatsnew/2.12.rst, pylint/checkers/variables.py, tests/functional/u/unused/unused_name_from_wilcard_import.py, tests/functional/u/unused/unused_name_from_wilcard_import.txt
Instead of reporting all unused imports, the checker now emits one single message for all unused imports with a stylized string containing all imports.
This closes #3859
=> Improve and flatten ``unused-wildcard-import`` message

ChangeLog, pylint/checkers/variables.py, tests/functional/u/undefined/undefined_variable.py
```py
if TYPE_CHECKING:
pass
else:
from types import GenericAlias
object().__class_getitem__ = classmethod(GenericAlias)
```
Closes #5111
=> Fix crash with AssignAttr in TYPE_CHECKING blocks

ChangeLog, pylint/checkers/base.py, tests/functional/i/invalid/invalid_name.py, tests/functional/i/invalid/invalid_name.txt, tests/functional/n/name/name_styles.txt
At the moment `invalid-name` for a function argument is emitted on the `function` node. That does work, however it limits where `pylint: disable` can be set. Consider the following example:
```py
class SomeClass:
def func(
self,
var,
invalidName,
):
pass
```
Only `invalidName` is wrong. With this change it's now possible to add `pylint: disable` directly behind it instead of after `def func`.
This appears to be fully backwards compatible. I.e. both with disable `invalid-name`:
```py
class SomeClass:
def func(  # pylint: disable=invalid-name
self,
var,
invalidName,
):
pass
class SomeClass:
def func(
self,
var,
invalidName,  # pylint: disable=invalid-name
):
pass
```
=> Improve node info for invalid-name

.github/workflows/ci.yaml
Replace `3.10-dev` with `3.10` in Github actions.
Astroid PR: https://github.com/PyCQA/astroid/pull/1198
=> Use 3.10 for Github actions

CONTRIBUTORS.txt, ChangeLog, pylint/checkers/refactoring/recommendation_checker.py, tests/functional/c/consider/consider_using_f_string.py
If the `str.format` function was being referenced (not called) in the keyword argument to a function, the `consider-using-f-string` checker was crashing due to attempting to obtain the `.args` from something that wasn't a call object. Referencing format without calling it in this way might be a mistake, but that should probably be another checker.
Closes #5058
=> Fix a crash if ``str.format`` is referenced without being called

ChangeLog, doc/whatsnew/2.12.rst, pylint/checkers/refactoring/refactoring_checker.py, tests/functional/t/ternary.py, tests/functional/t/ternary.txt
=> Fix incorrect ``consider-using-ternary`` when condition is inferable as False

CONTRIBUTORS.txt, doc/how_tos/custom_checkers.rst, doc/tutorial.rst, pylint/checkers/base.py, pylint/checkers/format.py, pylint/checkers/imports.py, pylint/checkers/spelling.py, pylint/checkers/strings.py, pylint/checkers/typecheck.py, pylint/checkers/variables.py, pylint/extensions/typing.py, pylint/lint/pylinter.py, pylint/pyreverse/main.py
Okay, this was bugging me for a while that the metavars for yes/no options were inconsistent across pylint. This simply re-labels all of them.
I looked across the codebase and found that the most common convention was to have spaces in your metavars, instead of dashes or underscores, so I went witht that.
=> Unify all `<y or n>` metavars

ChangeLog, doc/whatsnew/2.12.rst, pylint/extensions/_check_docs_utils.py, tests/extensions/test_check_docs.py
Based on:
https://numpydoc.readthedocs.io/en/latest/format.html#parameters
Closes #5222
=> Allow no type in Numpy param docstrings for ``mising-param-doc``

CONTRIBUTORS.txt, ChangeLog, doc/whatsnew/2.12.rst, pylint/lint/run.py
Simply tests the import `from multiprocessing import synchronize` to see if the host OS supports shared semaphores. The other part of the code already handles the jobs being set back to 1.
Closes #5216
=> Use single worker if importing `multiprocessing.synchronize` fails

CONTRIBUTORS.txt, ChangeLog, doc/whatsnew/2.12.rst, pylint/checkers/threading_checker.py, tests/functional/u/useless/useless_with_lock.py, tests/functional/u/useless/useless_with_lock.txt
Using `with threading.Lock():` directly has no effect.
Correct usage is:
```
lock = threading.Lock()
with lock:
...
```
This applies for:
* threading.Lock
* threading.RLock
* threading.Condition
* threading.Semaphore
* threading.BoundedSemaphore
Fixes: #5208
Signed-off-by: Martin Basti <mbasti@redhat.com>
Thank you for submitting a PR to pylint!
To ease the process of reviewing your PR, do make sure to complete the following boxes.
Closes #5208
=> Inspection for `with threading.Lock():`

pylint/checkers/similar.py, pylint/utils/pragma_parser.py, tests/functional/p/protocol_classes.py
Sometime (in old version) black added a space when there was already a non breaking whitespace, so there is no two spaces at the start of a comment.
=> Remove unwanted non-breaking whitespaces in comment

.github/ISSUE_TEMPLATE/BUG-REPORT.yml
This is non intuitive and I always need to change my issues to make them text again.
=> Remove ``render: python`` from bug description

ChangeLog, doc/whatsnew/2.12.rst, pylint/checkers/variables.py, tests/functional/s/self/self_cls_assignment.py, tests/functional/s/self/self_cls_assignment.txt
Continuation of #5254 
Basically we only checked single assignments and will now also check tuple assignments.
Furthermore, I have removed some redundant code.
=> Make ``self-cls-assignment`` check tuple assignment

pylint/lint/pylinter.py, pylint/utils/linterstats.py
This permit to reduce the coupling between Pylinter and linterstats.
Refactor prior to #4720
=> Create and use a function for module stats initialization

tests/config/file_to_lint.py, tests/config/test_config.py
See initial intent in https://github.com/PyCQA/pylint/issues/3839
This permit to not use the OptionManagerMixin directly, which is
problematic when it needs the function defined in Pylinter or
other classes.
Required for #4720
=> Simplify ``test_can_read_toml_env_variable`` to work like other tests

pylint/config/option_manager_mixin.py, pylint/config/option_parser.py, pylint/testutils/configuration_test.py, tests/config/conftest.py, tests/config/functional/ini/pylintrc_with_message_control.ini, tests/config/functional/ini/pylintrc_with_message_control.result.json, tests/config/functional/setup_cfg/setup_cfg_with_message_control.cfg, tests/config/functional/setup_cfg/setup_cfg_with_message_control.result.json, tests/config/functional/toml/issue_4746/loaded_plugin_does_not_exists.out, tests/config/functional/toml/issue_4746/loaded_plugin_does_not_exists.result.json, tests/config/functional/toml/issue_4746/loaded_plugin_does_not_exists.toml, tests/config/functional/toml/rich_types.result.json, tests/config/functional/toml/rich_types.toml, tests/config/functional/toml/toml_with_enable.result.json, tests/config/functional/toml/toml_with_enable.toml, tests/config/functional/toml/toml_with_message_control.result.json, tests/config/functional/toml/toml_with_message_control.toml, tests/config/test_config.py, tests/config/test_functional_config_loading.py, tests/lint/test_pylinter.py, tests/lint/unittest_lint.py, tests/message/unittest_message_definition_store.py
This create a framework for configuration testing.  Also migrate three standard unittest to the new framework for testing. Done to help with #4720.
=> Create a framework of functional tests for configuration files

ChangeLog, doc/whatsnew/2.12.rst, pylint/extensions/docparams.py, tests/extensions/test_check_docs.py, tests/extensions/test_check_return_docs.py, tests/extensions/test_check_yields_docs.py
As discussed in the issue it seems that our tests have solidified a bug where we do not break immediately when either of these settings are set to `yes`/`True`. This fixes this and turns off the setting for those tests that relied on the incorrect previous behaviour.
Closes #5223
Edit: I guess I shouldn't be coding this late 😅 Third try is a charm..
=> Fix ``accept-no-yields/return-doc`` for partially correct docstrings

CONTRIBUTORS.txt, ChangeLog, doc/whatsnew/2.12.rst, pylint/config/option_manager_mixin.py, pylint/lint/pylinter.py, tests/config/functional/toml/issue_4580/correct_basic_name_group.toml, tests/config/functional/toml/issue_4580/correct_import_preferred_module.toml, tests/config/functional/toml/issue_4580/empty_list.out, tests/config/functional/toml/issue_4580/empty_list.toml, tests/config/functional/toml/issue_4580/invalid_data_for_basic.out, tests/config/functional/toml/issue_4580/invalid_data_for_basic.toml, tests/config/functional/toml/issue_4580/invalid_data_for_import.result.json, tests/config/functional/toml/issue_4580/invalid_data_for_import.toml, tests/config/functional/toml/issue_4580/rich_types.result.json, tests/config/functional/toml/issue_4580/rich_types.toml, tests/config/functional/toml/issue_4580/top_level_disable.out, tests/config/functional/toml/issue_4580/top_level_disable.toml, tests/config/test_config.py
This is a fix for handling bad or invalid toml configuration in pyproject.toml
Closes #4580
=> Pylint fix for invalid TOML config

CONTRIBUTORS.txt, doc/user_guide/run.rst
This makes the call in the documentation non-trivial, so that [idiots like me](https://stackoverflow.com/questions/69851634/how-to-run-pylint-from-inside-python/69851635#69851635) don't get stuck.
If someone could show how to get the output of the command (as asked [here](https://stackoverflow.com/questions/56081299/how-to-get-report-score-from-pylint-when-run-python-code)), that would also be very helpful to add.
=> Clarify syntax in pylint.lint example

doc/whatsnew/2.12.rst
=> Add a whatsnew entry for python <3.6.2 incompatibility

pylint/checkers/classes.py
Small fix to remove redundant bracket pair in `if` statement.
=> Remove redundant brackets

pylint/testutils/configuration_test.py, tests/config/test_functional_config_loading.py
Detected in https://github.com/PyCQA/pylint/pull/5287#issuecomment-968093640
Tox use its own directory for test so we need to define the user specific path inside tests.
=> Fix user specific path in functional conf tests for tox

ChangeLog, doc/whatsnew/2.12.rst, pylint/checkers/base.py, pylint/extensions/comparison_placement.py, pylintrc, tests/checkers/unittest_base.py, tests/extensions/data/compare_to_zero.py, tests/functional/a/assert_on_tuple.py, tests/functional/c/comparison_with_callable.py, tests/functional/c/consider/consider_using_in.py, tests/functional/e/excess_escapes.py, tests/functional/m/misplaced_bare_raise.py, tests/functional/m/misplaced_bare_raise.txt, tests/functional/m/misplaced_comparison_constant.py, tests/functional/m/misplaced_comparison_constant.rc, tests/functional/n/nan_comparison_check.py, tests/functional/s/singleton_comparison.py, tests/functional/u/use/use_implicit_booleaness_not_len.py, tests/functional/u/use/using_constant_test.py
Closes #1064
Consensus was reached that this check should be an extension. I thought about putting it in `code_style`, but since that only has `Recommendation` and this is a `Convention` I thought I might as well create a new extension.
Since the extensions loaded in our `pylintrc` are not automatically loaded in the functional tests this required to update some tests and their results.
=> Move ``misplaced-comparison-constant`` to optional extension

ChangeLog, doc/whatsnew/2.12.rst, pylint/config/option_manager_mixin.py, pylint/lint/run.py, tests/test_self.py
@Pierre-Sassoulas 👀 
Might as well put it in `2.12`.
Partial of #5306.
=> Add ``enable-all-extensions`` option

tests/test_regr.py
This is necessary to allow typing of `PyLinter.reporter`. Without this change `mypy` will complain that `finalize` does not exist on any of the other reporter classes.
=> Add casts to ``linter.reporter`` in tests

setup.cfg
isort has a special black profile, this prevents that isorts changes a line and black changes it back.
See https://pycqa.github.io/isort/docs/configuration/black_compatibility.html
=> use isorts black profile

pylint/testutils/output_line.py, tests/test_functional.py
@Pierre-Sassoulas 
The problem was we're using the `csv` module which tries to escape delimiters and quote characters. See https://docs.python.org/3/library/csv.html
This is problematic for use as we're using `'` and `"` interchangeably in the messages we put out (something to be fixed soon™.
For now I think this also works. I tested with some of the files in the other PR and the results seemed satisfactory. You can use this fix and update `tests/functional/a/async_functions.txt` to see if it works. That output has both `'` and `"`.
=> Update functional test updater to print actual string

pylint/testutils/output_line.py, tests/test_functional.py
Reverts PyCQA/pylint#5351
See:
https://github.com/PyCQA/pylint/pull/5351#issuecomment-974827473
=> Revert "Update functional test updater to print actual string"

.github/workflows/ci.yaml, setup.cfg, tbump.toml, tests/primer/test_primer_stdlib.py
First step before primer that will be done in #5173. We need to separate both test because they take a long time see https://github.com/PyCQA/pylint/pull/5173#issuecomment-974828609
=> Add accetpance tests in CI for python 3.8+ instead of launching manually at release

doc/development_guide/contribute.rst, doc/development_guide/index.rst, doc/development_guide/testing.rst
Thought I shouldn't ask for better documentation while not doing some of it myself. Nobody likes writing docs 😄 
Based on my comment in #5365
=> Update documentation on writing tests for ``pylint``

pylint/lint/parallel.py
No longer trigger our own `DeprecationWarning` for `Message` requiring `MessageLocationTuple`.
=> Make parallel checker use ``MessageLocationTuple`` for ``Message``

ChangeLog, pylint/checkers/classes.py, pylint/extensions/check_elif.py, tests/functional/ext/check_elif/check_elif.py, tests/functional/ext/check_elif/check_elif.txt
https://github.com/psycopg/psycopg/blob/master/psycopg/psycopg/_queries.py#L281
Exception on node <If l.281 at 0x7f2f9141a550> 
pylint crashed with a ``IndexError`` and with the following stacktrace:
```
File "/home/pierre/pylint/pylint/lint/pylinter.py", line 1035, in _check_files
self._check_file(get_ast, check_astroid_module, file)
File "/home/pierre/pylint/pylint/lint/pylinter.py", line 1070, in _check_file
check_astroid_module(ast_node)
File "/home/pierre/pylint/pylint/lint/pylinter.py", line 1204, in check_astroid_module
retval = self._check_astroid_module(
File "/home/pierre/pylint/pylint/lint/pylinter.py", line 1251, …
```
=> Fix a crash on psycopg2 for elif used 

.github/workflows/ci.yaml, .gitignore, ChangeLog, doc/whatsnew/2.12.rst, pylint/constants.py, pylint/testutils/primer.py, requirements_test_min.txt, setup.cfg, tests/primer/packages_to_lint.json, tests/primer/test_primer_external.py, tests/primer/test_primer_stdlib.py, tests/testutils/test_package_to_lint.py
This is a draft for adding primer tests, and discuss about it.
Closes #4413
=> Primer tests "à la mypy"

ChangeLog, doc/development_guide/testing.rst, doc/whatsnew/2.12.rst, pylint/testutils/functional_test_file.py, pylint/testutils/lint_module_test.py, pylint/testutils/output_line.py, tests/testutils/test_output_line.py
Ref https://github.com/PyCQA/pylint/pull/5349#discussion_r755315222.
=> Add ``min_pyver_end_position`` option

.github/workflows/ci.yaml, doc/development_guide/testing.rst, setup.cfg, tests/conftest.py
Based on https://docs.pytest.org/en/latest/example/simple.html#control-skipping-of-tests-according-to-command-line-option
Because we can remove the standard ``addopts`` IDEs like VS Code will now actually find all tests in our test suite, but will just skip them when running normally. Makes it easier (at least for those on VS Code) to explore all tests.
Ticks of two points from #5306
=> Add documentation for primer and convert to command line option

.pre-commit-config.yaml, ChangeLog, pylint/checkers/base.py, pylint/checkers/classes.py, pylint/checkers/format.py, pylint/checkers/imports.py, pylint/checkers/refactoring/implicit_booleaness_checker.py, pylint/checkers/refactoring/recommendation_checker.py, pylint/checkers/refactoring/refactoring_checker.py, pylint/checkers/similar.py, pylint/checkers/stdlib.py, pylint/checkers/strings.py, pylint/checkers/typecheck.py, pylint/checkers/utils.py, pylint/checkers/variables.py, pylint/config/option.py, pylint/config/options_provider_mixin.py, pylint/extensions/typing.py, pylint/graph.py, pylint/lint/pylinter.py, pylint/utils/pragma_parser.py, pylintrc, requirements_test_pre_commit.txt, setup.cfg
This permit to check that the typing is valid for all python version. Relates to https://github.com/PyCQA/pylint/pull/5068
It seems we have some trouble with python 3.6.0 right now:
```
pylint/testutils/output_line.py:71:5: TYP004 NamedTuple does not support methods in 3.6.0
pylint/testutils/output_line.py:85:5: TYP004 NamedTuple does not support methods in 3.6.0
pylint/testutils/output_line.py:91:5: TYP004 NamedTuple does not support methods in 3.6.0
pylint/testutils/output_line.py:99:5: TYP004 NamedTuple does not support methods in 3.6.0
pylint/pyreverse/printer.py:43:5: TYP005 NamedTuple does not support defaults in 3.6.0
pylint/pyreverse/printer.py:44:5: TYP005 NamedTuple does not …
```
=> Add ``flake8-typing-import`` to the pre-commit configuration

ChangeLog, pylint/__pkginfo__.py, pylint/checkers/strings.py, pylint/reporters/text.py, tbump.toml
=> Release branch 2.12.1

pylint/checkers/variables.py, tests/functional/u/unused/unused_import.py
See https://github.com/PyCQA/astroid/pull/1235#discussion_r749691526
=> Make ``unused-import`` check all ancestors for typing guards

ChangeLog, pylint/checkers/variables.py
https://github.com/PyCQA/pylint/pull/5316#discussion_r757791192 and adds a changelog for that PR.
=> Refactor ``_is_type_checking_import`` of ``unused-import``

tests/checkers/unittest_variables.py, tests/functional/g/globals.py, tests/functional/g/globals.txt, tests/functional/n/no/no_name_in_module.py, tests/functional/n/no/no_name_in_module.rc, tests/functional/r/redefined_builtin.py, tests/functional/r/redefined_builtin.rc, tests/functional/r/redefined_builtin.txt, tests/functional/u/undefined/undefined_variable_classes.py, tests/functional/u/undefined/undefined_variable_decorators.py, tests/functional/u/undefined/undefined_variable_typing.py, tests/functional/u/undefined/undefined_variable_typing.rc, tests/functional/u/unused/unused_module.py
I left one tests as it seems to test specific `pylint` functionality that is not easily represented in a functional test.
=> Move ``TestVariablesChecker`` to functional tests

ChangeLog, examples/pylintrc
=> Update description of ``ignore-paths``

ChangeLog, pylint/config/option.py, tests/test_self.py
Closes #5437
I have not done anything to the error. The error is actually based on a pattern we have made, but should never be encountered by users. Since this is also related to `optparse` I don't think it is worth the effort to improve the error code and handling of it for now.
=> Fix ``_regexp_paths_csv_validator`` for already validated values

ChangeLog, pylint/checkers/variables.py, tests/functional/u/use/used_before_assignment.py, tests/functional/u/use/used_before_assignment.txt, tests/functional/u/use/used_before_assignment_typing.py, tests/functional/u/use/used_before_assignment_typing.txt
/CC: @cdce8p Finally fixed that false positive. Turned out it was a minor fix after all.
Closes #5342
=> Fix false positive for ``used-before-assignment`` for vars in methods

tests/checkers/unittest_typecheck.py, tests/functional/n/no/no_member_imports.py, tests/functional/n/no/no_member_imports.rc, tests/functional/n/no/no_member_imports.txt
=> Move ``no-member`` tests from ``TestTypeChecker``

tests/extensions/test_check_docs.py, tests/functional/ext/docparams/parameter/missing_param_doc_required_Sphinx.py, tests/functional/ext/docparams/parameter/missing_param_doc_required_Sphinx.rc, tests/functional/ext/docparams/parameter/missing_param_doc_required_Sphinx.txt, tests/functional/ext/docparams/raise/missing_raises_doc_Sphinx.py, tests/functional/ext/docparams/raise/missing_raises_doc_Sphinx.txt, tests/functional/ext/docparams/return/missing_return_doc_Sphinx.py, tests/functional/ext/docparams/return/missing_return_doc_Sphinx.txt, tests/functional/ext/docparams/return/missing_return_doc_required_Sphinx.py, tests/functional/ext/docparams/return/missing_return_doc_required_Sphinx.txt
@Pierre-Sassoulas I'm so sorry my git history was totally messed up and I couldn't retrieve the individual commits. If you don't think this is reviewable let me know and I'll redo this.
=> Move Sphinx docstrings out of ``TestParamDocChecker``

.copyrite_aliases, ChangeLog, doc/whatsnew/2.12.rst, doc/whatsnew/2.13.rst, pylint/__pkginfo__.py, pylint/checkers/classes.py, pylint/checkers/design_analysis.py, pylint/checkers/imports.py, pylint/checkers/typecheck.py, pylint/checkers/utils.py, pylint/extensions/_check_docs_utils.py, pylint/reporters/json_reporter.py, pylint/reporters/text.py, tbump.toml, tests/checkers/unittest_utils.py, tests/unittest_reporters_json.py, tests/unittest_reporting.py
Release branche for 2.12.2 and add missing doc for https://github.com/PyCQA/pylint/pull/5316
=> Bump pylint to 2.12.2, update changelog

.pre-commit-config.yaml, ChangeLog, doc/additional_commands/index.rst, doc/whatsnew/2.13.rst, pylint/pyreverse/main.py, pylint/pyreverse/mermaidjs_printer.py, pylint/pyreverse/printer_factory.py, tests/pyreverse/conftest.py, tests/pyreverse/data/classes_No_Name.html, tests/pyreverse/data/classes_No_Name.mmd, tests/pyreverse/data/packages_No_Name.html, tests/pyreverse/data/packages_No_Name.mmd, tests/pyreverse/test_writer.py
This pull request add the [mermaidjs](https://mermaid-js.github.io/mermaid/#/classDiagram) output format (as text like plantuml)
For the packages graph the classDiagram type of diagram is used for mermaidjs, because is the nearest type of graph to the package diagram for this tool.
=> Add mermaidjs as format output for pyreverse

ChangeLog, pylint/testutils/__init__.py, pylint/testutils/constants.py, pylint/testutils/functional/__init__.py, pylint/testutils/functional/find_functional_tests.py, pylint/testutils/functional/lint_module_output_update.py, pylint/testutils/functional/test_file.py, pylint/testutils/functional_test_file.py, pylint/testutils/lint_module_test.py, tests/functional/f/fixme.rc, tests/functional/r/regression/regression_issue_4631.rc, tests/functional/t/too/too_few_public_methods_excluded.rc, tests/functional/t/too/too_many_ancestors_ignored_parents.rc, tests/functional/t/too/too_many_statements.rc, tests/test_functional.py, tests/testutils/test_lint_module_output_update.py
The functional tests grow all the time and organizing them properly will become a problem soon. See possible follow up here: https://github.com/PyCQA/pylint/pull/5396#issuecomment-981055863
=> Refactor functional testutil in order to normalize later

ChangeLog, pylint/checkers/classes.py, pylint/checkers/mapreduce_checker.py, tests/functional/a/arguments_differ.py, tests/functional/a/arguments_differ.txt, tests/functional/a/arguments_differ_issue5371.py, tests/test_check_parallel.py
**Before**
Static methods lacking a `@staticmethod` decorator, such as `Enum._generate_next_value()` in the stdlib would have their first argument stripped when counting their arguments, even though it wasn't `self` or `cls`. This caused comparison issues in `arguments-differ`, including both false negatives and positives.
**Now**
Check if the method is bound before stripping the first argument.
Closes #5371
=> Fix #5371: Correctly count arguments to static methods missing @staticmethod decorator

pylint/checkers/refactoring/refactoring_checker.py
Noticed while working on #5409 that `CALLS_RETURNING_CONTEXT_MANAGERS` lacks `tempfile.TemporaryFile`.
No functional impact. (I believe that is because the stdlib defines `TemporaryFile` in if/else blocks depending on the system, and pylint doesn't have control-flow inference to do anything with it right now. But adding this here should make a future refactor safer?)
=> Add tempfile.TemporaryFile to CALLS_RETURNING_CONTEXT_MANAGERS

tests/pyreverse/test_writer.py
This pr fix the annoying behavior introduced in pr #5272.
After this pr when pyreverse tests are executed some tests files aren't removed after execution.
=> fix deleting files for pyreverse tests

tests/extensions/test_check_docs.py, tests/functional/ext/docparams/parameter/missing_param_doc_required_Numpy.py, tests/functional/ext/docparams/parameter/missing_param_doc_required_Numpy.rc, tests/functional/ext/docparams/parameter/missing_param_doc_required_Numpy.txt, tests/functional/ext/docparams/return/missing_return_doc_Numpy.py, tests/functional/ext/docparams/return/missing_return_doc_Numpy.txt
This does not cover all numpy tests as there are some issues with those that check `raise` documentation (it seems as if tests are incorrectly passing currently).
Just to make the other PR easier to review, let's merge this first!
=> Move some of the Numpy tests out of ``TestParamDocChecker``

ChangeLog, doc/whatsnew/2.13.rst, pylint/checkers/refactoring/refactoring_checker.py, tests/functional/u/unnecessary/unnecessary_dict_index_lookup.py
Fixes crash if the dict view returned by `.items()` is partially unpacked to a 1-tuple, e.g. `for k, in d.items()` instead of `for k, _ in d.items()`
Closes #5504
=> Fix #5504: Fix crash if the output of items() is assigned to a 1-tuple

ChangeLog, doc/whatsnew/2.13.rst, pylint/extensions/_check_docs_utils.py, pylint/extensions/docparams.py, tests/extensions/test_check_docs.py, tests/functional/ext/docparams/raise/missing_raises_doc_Numpy.py, tests/functional/ext/docparams/raise/missing_raises_doc_Numpy.txt
See short discussion in https://github.com/PyCQA/pylint/pull/5492#issuecomment-990986957
The test that has been moved to the functional tests wouldn't pass without this change. Because of the property description in the docstring this gets considered to be a `Google` style and then the `Raises` section is not correctly recognised.
The use of `is_valid` is pretty naive and I think this fix (although also pretty naive) is an improvement: it selects the style for which most sections get recognised.
I wonder if this is a breaking change: removing `is_valid` and requiring `matching_sections` on `DocString` might be troublesome …
=> Fix incorrect classification of property docstrings in Numpy-style

tests/extensions/test_check_docs.py, tests/functional/ext/docparams/raise/missing_raises_doc_Numpy.py, tests/functional/ext/docparams/raise/missing_raises_doc_Numpy.txt, tests/functional/ext/docparams/return/missing_return_doc_required_Numpy.py, tests/functional/ext/docparams/return/missing_return_doc_required_Numpy.txt
=> Move ``Numpy`` test from ``TestParamDocChecker`` to functional tests

ChangeLog, doc/whatsnew/2.13.rst, pylint/checkers/variables.py, tests/functional/u/use/used_before_assignment_issue2615.py, tests/functional/u/use/used_before_assignment_issue2615.txt, tests/functional/u/use/used_before_assignment_issue85.py, tests/functional/u/use/used_before_assignment_issue85.txt
**Previously**
Pylint assumed assignments in the Try block of a Try/Finally or Try/Except pair would succeed. In cases of failure, though, attempting to use such names in a final or except block would raise `UnboundLocalError`.
**Now**
Pylint emits `used-before-assignment` to account for the fact that the statement might have been interrupted by an exception.
Closes #85, Closes #2615
=> Fix #85, #2615: Emit `used-before-assignment` in final or except blocks where try statements could have failed

pylint/testutils/decorator.py, tests/testutils/test_decorator.py
See https://github.com/PyCQA/pylint/pull/5509#issuecomment-992346711
=> Add a DeprecationWarning to set_config_directly

pylint/testutils/functional/test_file.py, pylint/testutils/lint_module_test.py
Follow up to #5418 which improves the validation of functional test option files and makes it in line with the other validators.
=> Unify validation of functional test option files

ChangeLog, doc/whatsnew/2.13.rst, pylint/testutils/checker_test_case.py, pylint/testutils/output_line.py, pylint/testutils/unittest_linter.py, tests/checkers/unittest_base.py, tests/checkers/unittest_deprecated.py, tests/checkers/unittest_imports.py, tests/checkers/unittest_typecheck.py, tests/checkers/unittest_variables.py
List of unittests which "can't" be moved and are updated to now include location attributes:
- `TestMultiNamingStyle`
=> Check `node` location attributes in unittests

pylint/interfaces.py
Pycharm raises a warning when we import something that is not in ``__all__``. We also need a new confidence level clearer than ``HIGH``.
=> Modify the description of HIGH confidence in pylint.interfaces

ChangeLog, pylint/checkers/utils.py, tests/functional/c/consider/consider_using_with.py, tests/functional/c/consider/consider_using_with.txt, tests/functional/t/too/too_many_function_args.py
**Before**
`safe_infer` might confuse two function definitions having different numbers of arguments.
**Now**
It won't. <s>But there is an inference problem with `TemporaryFile` being inferred as `NamedTemporaryFile`, which has an extra argument (`delete`), so I special-cased it. Is that an Astroid issue?</s> Update: the way `tempfile` defines the name `TemporaryFile` conditionally based on platform means Astroid finds ambiguity.
Closes #3675
=> Fix #3675: `safe_infer()` finds ambiguity among function definitions when number of arguments differ

ChangeLog, doc/faq.rst, doc/whatsnew/2.13.rst, examples/pylintrc, pylint/lint/pylinter.py, pylint/lint/run.py, pylintrc, tests/test_self.py
**Before**
Modules without statements (such as typo'd paths) don't generate scores. When a linter is run over both valid and invalid paths, this can lead to a perfect score. Scores meeting the ``--fail-under`` threshold exit with a 0 code (passing), which is counterintuitive for the case just described.
**Now**
<s>As long as ``--fail-under`` is 10.0, this PR fails runs with perfect scores if they had any non-zero exit codes.
Of course, the other approach would be to start emitting non-perfect scores for modules without statements, but this seemed less invasive.</s>
Update: new approach is to simply produce a score of 0 for fatal errors.
Closes #5451
=> Fix #5451: Produce a score of 0 for fatal errors

pylint/lint/pylinter.py, pylint/reporters/base_reporter.py
Small change to these attributes and methods. `_reporter_names` was only used by `_load_reporters` so it makes more sense to just pass that option value to the method instead of creating an additional attribute.
=> Update typing of reporter attributes in ``PyLinter``

tests/functional/u/use/used_before_assignment_except_handler_for_try_with_return.py, tests/functional/u/use/used_before_assignment_except_handler_for_try_with_return.txt
Followup to #5500 and #5506
Add additional tests for `used-before-assignment` cases with `try-except`.
`used-before-assignment` should **not** be emitted for variables after the `try-except` block if
* All ExceptHandlers define it
* OR all ExceptHandlers, that don't `raise` an Exception or `return`, define it.
/CC: @jacobtylerwalls I created these while trying to isolate which case you mentioned https://github.com/PyCQA/pylint/issues/5500#issuecomment-991695275 isn't yet covered.
=> Add additional test cases used-before-assignment with try-except

pylint/checkers/variables.py
Requested by @cdce8p in https://github.com/PyCQA/pylint/pull/5506#pullrequestreview-830508456.
I worked on a series of PRs for `used-before-assignment` false negatives, and I began by trying to make them rhyme with the surrounding list comprehensions. This became a bit absurd after adding another exception case in #5506, so this PR takes the worst offending list comprehension and factors it out. Performance boost from fewer calls to `statement()`.
=> Factor out `_uncertain_nodes_in_except_blocks()`

ChangeLog, doc/whatsnew/2.13.rst, pylint/checkers/typecheck.py, tests/functional/n/not_callable.py, tests/functional/n/not_callable.txt
Closes part of #1730, specifically this comment: https://github.com/PyCQA/pylint/issues/1730#issuecomment-489572303
I tried to destructure the `if` a little bit because I got a `too-many-boolean-expressions` warning and it became really unreadable.. This did lead to some code duplication though..
=> Fix ``not-callable`` for attributes that alias ``NamedTuple``

ChangeLog, doc/whatsnew/2.13.rst, pylint/checkers/utils.py, tests/functional/o/overridden_final_method_regression.py, tests/functional/o/overridden_final_method_regression.txt
Crash identified while working on #5547 
Tagging @mbyrnepr2 since you contributed this checker and I wonder if you have an opinion on this fix.
=> Fix crash on uninferable decorators on Python 3.6 and 3.7

pylint/checkers/variables.py
This removes the last uncovered part of the consumption checker as identified in #5241 
Original commit that added this code is https://github.com/PyCQA/pylint/commit/05b526d58a9b210a54ea2755eaf5104f74039e5b
I tested but I don't think `node.parent` is ever not `nodes.Arguments`. As an extra cautionary action I ran the primer with a debug statement. This can be seen in the following PR: https://github.com/DanielNoord/pylint/pull/59
Searching for `PLEASE SEE ME` would show any code that entered this `if` statement (based on this commit: https://github.com/DanielNoord/pylint/pull/59/commits/362d505d6452042b2dae40acb6fcc30a8c21b378)
This seems to be an unnecessary statement.
=> Remove unnecessary `if` statement in variable consumption checker

ChangeLog, doc/whatsnew/2.13.rst, pylint/checkers/variables.py, tests/functional/u/use/used_before_assignment_typing.py
Closes #5499.
I should have thought of this fix in #5342. This is much better..
=> Fix ``used-before-assignment`` for conditional self-referential typing

pylint/lint/pylinter.py
Missed in #5521 -- when updating the default score evaluation formula in example pylintrc, should have updated the default value when there is no pylintrc. Missed this when performing find and replace due to the line break.
=> Update default evaluation formula to match that in default pylintrc

ChangeLog, doc/whatsnew/2.13.rst, pylint/lint/expand_modules.py, pylint/lint/pylinter.py, pylint/testutils/configuration_test.py, pylint/utils/linterstats.py, tests/functional/e/.#emacs_file_lock.py, tests/functional/e/.#emacs_file_lock_by_conf.py, tests/functional/e/.#emacs_file_lock_by_conf.rc, tests/functional/e/.#emacs_file_lock_redefined_conf.py, tests/functional/e/.#emacs_file_lock_redefined_conf.rc, tests/functional/e/.#emacs_file_lock_redefined_conf.txt
This ignore the file starting like emacs file lock. It's a problem in emacs not in pylint but this kind of file name can almost exclusively come from emacs as it's not a valid module name so we may as well ease the life of our emacs users.
Closes #367
=> Ignore files with name that starts like an emacs lock files

tests/lint/unittest_expand_modules.py
=> Fix unexpected types used in 'get_global_option'

.github/workflows/primer-test.yaml
Seems like one of the new dependencies broke something in the primer.
This makes sure primer is also ran against changes to the dependencies, so we no longer unexpectedly fail on `main`.
=> Add requirement files to list of files to run primer against

requirements_test.txt
Reverts PyCQA/pylint#5561, we need to fix the primer but we can't block all current MR in order to do that.
=> Revert "Update tbump requirement from ~=6.6.0 to ~=6.6.1"

pylintrc
There were many settings documented in `examples/pylintrc` that were not used in our own `pylintrc`. Similarly, there were commands in our `pylintrc` that were not in the example. This brings both documents in line with each other. 
As new users may look at our own configuration I think it is good to have all options in here, even if they are commented out. Please also look at the values of the new settings, as they essentially become default/suggested values.
=> Add missing settings to pylintrc

ChangeLog, doc/whatsnew/2.13.rst, pylint/checkers/base.py, tests/functional/c/comparison_with_callable.py, tests/functional/c/comparison_with_callable_typing_constants.py
Typing constants such as `typing.Any` raise when called, which means they should not emit `comparison-with-callable`.
This PR skips emitting that message when a callable raises in its body (or if it's a typing constant, since some typing constants only raise via their decorator, not via their body).
Closes #5557
=> Fix #5557: Don't emit `comparison-with-callable` if the callable raises

pylint/lint/pylinter.py, pylint/reporters/reports_handler_mix_in.py
Seems like we made an error in https://github.com/PyCQA/pylint/pull/5004 that I didn't catch in my review.
Checkers ``__implements__`` `Ichecker`, but this isn't picked up on by `mypy`. The typing should thus be `BaseChecker`.
=> Add typing to checker and plugin attributes of ``PyLinter``

doc/development_guide/index.rst, doc/development_guide/profiling.rst
Closes #4067
While by no means perfect, this might be a good step towards better documentation on performance analysis. At least it shows users how to generate a useful profiler report.
=> Add documentation about profiling and performance analysis

.github/workflows/ci.yaml
Bump the cache version. Will fix the CI issues seen in #5600 where it could create the venv.
=> Bump CI cache version

pylint/lint/pylinter.py
Closes #5587.
This is the main improvement I found for enabling and disabling messages. The problem was that we synced the `config` object after every message, instead of doing so after all messages have been set.
With this version we first find all messages to set, set them and then sync the `config` object.
For comparison:
Profiler command:
`python -m cProfile -s cumtime pylint/__main__.py test.py --disable=all`
Without change:
```
1    0.000    0.000    0.372    0.372 config_initialization.py:14(_config_initialization)
```
With change:
```
1    0.000    0.000    0.026    0.026 config_initialization.py:14(_config_initialization)
```
About a 10x improvement 😄
=> Refactor message disabling and enabling

pylint/checkers/refactoring/refactoring_checker.py, tests/functional/u/unnecessary/unnecessary_comprehension.py, tests/functional/u/unnecessary/unnecessary_comprehension.txt
The issue location of `unnecessary-comprehension` was being raised at `line:0`, even if the comprehension wasn't present at column 0.
This would give the wrong location, for example:
```python
item = [(k, v) for k, v in a_dict.items()]
```
```text
************* Module mytest
mytest.py:1:0: R1721: Unnecessary use of a comprehension, use list(a_dict.items()) instead. (unnecessary-comprehension)
```
The expected position would be `1:7`, not `1:0`.
Weirdly, the test cases had zero examples of a comprehension that wasn't at column zero, so I tweaked some of those as well.
=> Fix reported node for `unnecessary-comprehension`

pylint/config/config_initialization.py, pylint/testutils/lint_module_test.py, pylint/testutils/testing_pylintrc
Follow up to #5591. Diff should be much smaller after that has been merged (adding blocked in the meantime).
This makes it so that whenever a functional test does not have a `.rc` file we still pass a `pylintrc` file to the configuration initialiser.
This does not fix any current problems but allows me (and others) to assume that `_config_initialization` is always ran, also for functional tests that skip instantiating a `Run` object. That allows me to then work within `_config_initialization` for the implementation of `argparse` and make `argparse` and `optparse` work along side each other while we're still working on it.
=> Make functional tests always go through config initialization

ChangeLog, doc/faq.rst, doc/whatsnew/2.13.rst, examples/pylintrc, pylint/lint/pylinter.py, pylintrc, tests/test_self.py, tests/unittest_reporting.py
Change the default score formula to use a floor of 0. Negative scores are still supported, on an opt-in basis. Users can set `evaluation=` in their pylint rc to get the old behavior. (Or to get the new behavior if they have an old rc file!)
Closes #2399 (*)
(*) Of course, the issue could be kept open for further discussion, but at least the negative part is solved. Better defaults and gamification and nifty scoring formulas could tracked elsewhere (e.g. #3512 or #746).
=> Fix #2399: Avoid negative scores by default

pylint/lint/pylinter.py
We don't need to create message definitions to get their msgids.
The level of indirection may suggest we need to refactor a
little here. Maybe we actually need message definition only
when we want to display the messages.
Follow-up to #5605
=> Get the msgids directly from the MessageIdStore

pylint/lint/pylinter.py, pylint/message/message_definition_store.py, pylint/message/message_id_store.py
This add caching to bottlenecks in the MessageStore. Next step would be to generate the code of an immutable data structure from the checkers instead of creating and checking it at runtime and then using this structure directly, but I think caching is fine for now. (Especially as we can't do everything this way: For plugin there are still unexpected message id and symbol.)
``get_active_msgids`` was calling .lower() / is_digit on every message id we gave it every time caching it save a lot of call.
There's some function we can't cache because of the way PyLinter is designed.
Tested by linting django (03cadb912c78b769d6bf4a943a2a35fc1d952960) with ``python3 -m cProfile -m pylint …
=> Add caching to bottlenecks in the message store

.github/workflows/ci.yaml, .github/workflows/primer-test.yaml
Similar to #5602.
Also updates the primer to run when changes to its workflow file occur.
Should fix CI issues of #5609 (already tested and it works).
=> Update CACHE_VERSION of primer, add comment and update paths

ChangeLog, doc/whatsnew/2.13.rst, pylint/lint/parallel.py, setup.cfg, tests/test_check_parallel.py
For reference see my earlier comment here:
https://github.com/PyCQA/pylint/pull/5584#issuecomment-1002470174
`multiprocessing.Pool` pickles the arguments passed in `initargs`. This was noted in the original commit that added this: https://github.com/PyCQA/pylint/commit/8babeffde54a696e7ba84d69f8fc1f871e432950
One of the effects of this was that it was decided to set `reporter` to `None` as then the reporter doesn't need to be pickled. We're running into a similar issue with the migration to `argparse` since `argparse.ArgumentsParser` isn't pickle-able by `stdlib`.
To overcome this I looked at the solution proposed on …
=> Use ``dill`` to pickle when run in parallel mode

ChangeLog, doc/user_guide/run.rst, doc/whatsnew/2.13.rst, pylint/__init__.py, tests/test_pylint_runners.py
@Pierre-Sassoulas  I'm not sure if this warrants a changelog entry? I haven't added one.
I'll do a follow-up for `epylint`, as it requires some additional changes to its `Run` class.
Closes #5320
=> Allow passing arguments when entry points are used as functions

ChangeLog, doc/user_guide/run.rst, doc/whatsnew/2.13.rst, pylint/__init__.py, pylint/epylint.py, tests/test_pylint_runners.py
Follow up to #5613. No `epylint` works as well 😄
=> Allow passing arguments if ``epylint`` entry point is used as function

pylint/typing.py, tests/functional/r/regression_02/regression_distutil_import_error_73.py, tests/functional/r/regression_02/regression_distutil_import_error_73.txt
Refer to https://github.com/PyCQA/astroid/pull/1321
=> Regression tests for 73 (distutil import error)

ChangeLog, doc/whatsnew/2.13.rst, pylint/checkers/variables.py, tests/functional/r/redefined_except_handler.py, tests/functional/r/redefined_except_handler.txt
Emit `redefined-outer-name` when a nested except handler shadows (overwrites) the name used in an outer except handler.
Implementation borrows from the `redefined-outer-name` implementation for if branches.
Closes #5370, Closes #4434
=> Fix #5370: Emit `redefined-outer-name` when a nested except handler shadows an outer one

setup.cfg
|   | :scroll: Docs          |
Fixes `mypy` issue regarding `colorama` and `--ignore-missing-imports`:
```
Cannot find implementation or library stub for module named "colorama" (https://mypy.readthedocs.io/en/stable/ files)
http://pylint/reporters/text.py:323:%20note:%20See%20https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
```
Closes #5627
=> pre-commit colorama error fix with mypy checker on Windows

pylint/checkers/base.py, pylint/constants.py
I'm going to go through the effort of picking some of the changes for #5311 into separate PRs.
I don't see myself being able to keep my focus for 2000+ lines 😄 
I'm co-authoring @CarliJoy in all of them as they have done all the work here!
=> Move ``HUMAN_READABLE_TYPES`` to ``constants``

.github/workflows/ci.yaml, .github/workflows/primer-test.yaml
Taking inspiration from `pip` as seen here https://github.com/pypa/pip/pull/10720 I really like their clean CI jobs names.
This is probably personal preference, but would we consider changing them? This is my suggestion based on their design.
=> Rename CI job names

tests/functional/e/.#emacs_file_lock_redefined_conf.txt, tests/functional/ext/docparams/raise/missing_raises_doc_required_exc_inheritance.txt
=> Fix escaping of some strings in functional tests

ChangeLog, doc/whatsnew/2.13.rst, pylint/checkers/utils.py, pylint/checkers/variables.py, tests/functional/u/use/used_before_assignment_issue2615.py, tests/functional/u/use/used_before_assignment_issue2615.txt
**Before**
In Pylint 2.13.0 (unreleased) we are starting to be more confident in emitting `used-before-assignment` by making control flow inferences. (See e.g. #5384) We started cautiously, just checking direct parents of statements in try blocks to find out if that was the same `TryExcept` ancestor that was the parent of the node being visited in the except block. This left out possibly failing statements in the try block indented under `if`/`with`, etc.
**Now**
@DanielNoord suggested using `get_node_first_ancestor_of_type()` to be able to leapfrog over `if` and `with` statements to arrive at the relevant try ancestor. With this PR, we can now emit `used-before-assignment` even when the …
=> Don't assume direct parentage when emitting `used-before-assignment`

ChangeLog, doc/whatsnew/2.13.rst, pylint/checkers/utils.py, pylint/checkers/variables.py, tests/functional/g/globals.py, tests/functional/g/globals.txt
Fixed false positive for ``global-variable-not-assigned`` when the `del` statement is used.
If the `del` statement is used on the variable (in the same scope on a later line-number) then the warning is not emitted.
Closes #5333
=> Fixed false positive for ``global-variable-not-assigned``

ChangeLog, doc/whatsnew/2.13.rst, pylint/checkers/variables.py, tests/functional/u/undefined/undefined_variable_py38.py, tests/functional/u/undefined/undefined_variable_py38.txt
Fixes the regression described in #5326 where `undefined-variable` is emitted when a comprehension variable matches a type annotation.
One test result is edited to show that after these changes we will need better detection of walrus operators.
Fixes #5326
=> Fix #5326: Fix false positive for `unused-variable` for a comprehension variable matching a type annotation

ChangeLog, doc/whatsnew/2.13.rst, pylint/checkers/classes/class_checker.py, tests/functional/u/unused/unused_private_member.py, tests/functional/u/unused/unused_private_member.txt
=> Fix #5569: Fix a crash in `unused-private-member` when `type(self)` used in bound methods

pylint/testutils/output_line.py, tests/testutils/test_output_line.py
https://github.com/PyCQA/pylint/blob/2631583577a3b2228af66214a364e4e284ba55dd/tests/testutils/test_output_line.py#L126-L130
This example was not actually handled correctly. For some reason `issubclass(str, Sequence)` equals `True`, so the `isinstance` check didn't make any sense. This meant that the above line had a `len` of `51`. This changes it so that a string will first be separated on the comma's and then parsed.
The diff is quite large as the indentation could then be removed. 
I also hope this removes some `DeprecationWarnings` that were showing up in the test suite on `3.7` and `3.8`.
=> Make sure to split non-separated csv ``OuputLine's``

ChangeLog, doc/whatsnew/2.13.rst, pylint/checkers/variables.py, tests/functional/u/use/used_before_assignment_filtered_comprehension.py
Closes #5586
With a small adjustment, @DanielNoord's suggestion in https://github.com/PyCQA/pylint/issues/5586#issuecomment-1010155471 passes the suite, so I just opened a PR. I'm not certain this is the best way to do this, but I tried an alternative diff in `get_next_to_consume()`, and it turned out to be more questionable.
=> Fix #5586: False positive for `used-before-assignment` with homonyms in filtered comprehensions and except blocks

tests/primer/packages_to_lint_batch_two.json
`pandas-dev` just renamed their main branch from `master` to `main` as seen [here](https://github.com/pandas-dev/pandas/pull/45336). This is one of our primer repositories so we need to update accordingly or else batch two tests fail.
=> Update `pandas-dev` testing primer package branch to `main`

pylint/message/message_id_store.py
Ref #5670.
Instead of using `lru_cache` we can use a basic cache defined on the instance to achieve a similar performance boost.
Tested on `pylint` over `pylint`. 
With new form of cache:
```console
ncalls  tottime  percall  cumtime  percall filename:lineno(function)
54436    0.029    0.000    0.030    0.000 message_id_store.py:107(get_active_msgids)
```
Without new cache:
```console
ncalls  tottime  percall  cumtime  percall filename:lineno(function)
54429    0.099    0.000    0.132    0.000 message_id_store.py:107(get_active_msgids)
```
Problem introduced in https://github.com/PyCQA/pylint/pull/5605
=> Remove ``lru_cache`` from ``get_active_msgids``

ChangeLog, doc/whatsnew/2.13.rst, pylint/checkers/refactoring/implicit_booleaness_checker.py, tests/checkers/unittest_refactoring.py, tests/functional/u/use/use_implicit_booleaness_not_comparison.py, tests/functional/u/use/use_implicit_booleaness_not_comparison.txt
Closes #5646 and supersedes #5647.
The typing on this function was incorrect and never actually received classes. Instead it received `bases.Instance` which was also deductible from the parameter name. I've completely rewritten the function as I felt this was the best way to go.
=> Fix crash on properties & inherited methods in ``implicit-booleaness``

pylint/checkers/variables.py
A downloaded a new extension for VS Code which pointed me to:
https://github.com/PyCQA/pylint/blob/4a6b6bf33053c5887274da14e00dd22a7dcb4284/pylint/checkers/variables.py#L1229
In an attempt to fix this we'll need to do some additional typing to other methods and classes in the `variables` checker. This would be a good start.
@jacobtylerwalls Tagging you as you're clearly the expert here, but I can't request a review from you.
=> Add typing to `ScopeConsumer`

ChangeLog, doc/whatsnew/2.13.rst, pylint/checkers/classes/class_checker.py, pylint/checkers/typecheck.py, tests/functional/a/arguments_renamed.py, tests/functional/a/arguments_renamed.txt, tests/functional/o/overridden_final_method_py38.py, tests/functional/o/overridden_final_method_py38.txt
Fixed the reported crash and other places where the same risky pattern (unprotected `node.parent.name`) appears, one of which was in a different checker.
Closes #5648
=> Fix crashes for accesses to `node.parent.name` on `FunctionDef` nodes

ChangeLog, doc/whatsnew/2.13.rst, pylint/checkers/variables.py, tests/functional/c/consider/consider_using_with_open.py, tests/functional/c/consider/consider_using_with_open.txt, tests/functional/u/use/used_before_assignment_issue85.py, tests/functional/u/use/used_before_assignment_issue85.txt
Fixes false negative for `used-before-assignment` when evaluating statements in a finally block, there is a possibly failing statement in the try block, and an except handler intervenes between.
Found while working on #5582. Unhandled case from #5384 -- I had thought of this case, but didn't know how to solve it: a finally that is not the direct descendant of a try handler because we have try/except/finally. (Since we were just incrementally solving false negatives, that wasn't such a problem at the time.) After #5582, I now know how to handle it!
=> Fix false negative for `used-before-assignment` when an Except intervenes between Try/Finally

pylint/checkers/utils.py
Discussed at https://github.com/PyCQA/pylint/pull/5684#discussion_r785285185
=> Fix typing of `get_node_first_ancestor_of_type()` and related method

setup.cfg
Closes https://github.com/PyCQA/astroid/issues/1341.
See discussion there as well. This allows installing an editable local installation of `astroid` without `pylint` throwing errors about unmatched versions.
=> Allow dev version of next minor ``astroid`` version

ChangeLog, doc/whatsnew/2.13.rst, pylint/checkers/variables.py, tests/functional/u/undefined/undefined_variable.py
The `undefined-variable` checker had a special case for return annotations matching the name of the containing class, but this missed other nested classes like a `namedtuple` used as a class attribute.
Closes #5568
=> Fix #5568: Allow nested classes as return annotations

ChangeLog, doc/whatsnew/2.13.rst, pylint/checkers/utils.py, pylint/checkers/variables.py, tests/functional/g/globals.py, tests/functional/g/globals.txt
Fixed false positive for ``global-variable-undefined`` when ``global`` is used with a class name
Closes #3088
=> Fixed false positive for ``global-variable-undefined``

ChangeLog, doc/whatsnew/2.13.rst, pylint/checkers/variables.py, tests/functional/n/nonlocal_without_binding.py, tests/functional/u/undefined/undefined_variable.py
The `nodes.Tuple` type is currently not considered in the logic to determine if the name is a member of the nonlocal set;
With this merge-request, if the parent of the name which is assigned is of type `nodes.Tuple` (as is the case with tuple-unpacking) then a `return` is reached which prevents emitting the warning message.
Closes #3781
=> ``unused-variable`` when `nonlocal` name in a multiple-assignment

ChangeLog, doc/whatsnew/2.13.rst, pylint/checkers/variables.py, tests/functional/u/undefined/undefined_variable_py38.py, tests/functional/u/undefined/undefined_variable_py38.txt
Closes #5654
Added another exception to the "return early if a name already consumed is encountered again" logic, again having to do with comprehensions. This is getting special-case heavy, so comprehension handling might need to be factored differently going forward, but the challenge was not breaking the `unused-argument` warning raised here: https://github.com/PyCQA/pylint/blob/7611ec443509888b96087d1519be9d73cf3b4c79/tests/functional/u/unused/unused_argument.py#L43-L48
=> Fix #5654: Fix false negative for `undefined-variable` for unused type annotation after the same name appears multiple times in a comprehension

ChangeLog, doc/whatsnew/2.13.rst, pylint/checkers/variables.py, tests/functional/u/undefined/undefined_variable.py, tests/functional/u/undefined/undefined_variable.txt, tests/functional/u/use/used_before_assignment_type_annotations.py, tests/functional/u/use/used_before_assignment_type_annotations.txt
This one is somewhat pedantic, sorry! I simply noticed that we could attempt to raise more targeted messages so that `undefined-variable` corresponds generally with `NameError` and `used-before-assignment` corresponds generally with `UnboundLocalError`. The only use of the message affected by this PR is new in 2.12, so hopefully not breaking too many existing disables. But I suppose that should be balanced against people suppressing `undefined-variable` that would be glad to get `used-before-assignment` coming through now.
See example shell session drawn from existing unit tests adjusted in this PR:
```python
In [1]: G: int
...: 
...: 
...: def a():
...:     global G
...:     print(G)
...: …
```
=> Fix #5713: Emit `used-before-assignment` instead of `undefined-variable` when accessing unused type annotations

tests/functional/u/undefined/undefined_variable_py38.py, tests/functional/u/undefined/undefined_variable_py38.txt
After f85fb8d975d17f411e5f91ed2d5f21ba999e121e, certain unused type annotations raise `used-before-assignment` rather than `undefined-variable`. The subsequent commit 0fb6a120c6f0fbc94e305542fe29e790274be096 was drafted before the prior change was made, and it addressed a related false negative, so this commit just applies the intended change of message type.
Sorry for not pointing this out during review; I was figuring I would have a short interval to fix this when one of them got merged!
=> Fix test conflicts

ChangeLog, doc/whatsnew/2.13.rst, pylint/checkers/variables.py, tests/functional/u/use/used_before_assignment_issue4761.py, tests/functional/u/use/used_before_assignment_issue4761.txt
=> Fix #5683: False positive ``used-before-assignment`` in loop `else` where the only non-break exit is through `except`

ChangeLog, doc/whatsnew/2.13.rst, pylint/checkers/stdlib.py, tests/functional/u/unspecified_encoding_py38.txt
=> Improved `bad-open-mode` message when providing `None` to the `mode` argument of an `open()` call

ChangeLog, doc/user_guide/run.rst, doc/whatsnew/2.13.rst
The argument `arguments` was renamed to `argv` in #5619 without updating the docs.
=> Correct reference to `argv` in documentation for `run_pylint()`

ChangeLog, doc/whatsnew/2.13.rst, pylint/checkers/variables.py, tests/functional/u/undefined/undefined_variable.py, tests/functional/u/undefined/undefined_variable.txt, tests/functional/u/use/used_before_assignment_py37.py, tests/functional/u/use/used_before_assignment_py37.txt, tests/functional/u/use/used_before_assignment_typing.py, tests/functional/u/use/used_before_assignment_typing.txt
There were two _short-circuit-and-consume-names_ paths in the variables checker preventing reporting further errors:
- undefined variable as default function argument
- undefined variable as type annotation
Removing some of these "special early consume" messages has the benefit that going through the regular path raises the correct flavor of `used-before-assignment` versus `undefined-variable`.
Closes #5399
***
Will need a rebase after #5709. (edit: done!)
=> Fix #5399: Fix false negatives for further variable messages for invalid type annotations or default arguments

tests/functional/u/undefined/undefined_variable_py38.py, tests/functional/u/undefined/undefined_variable_py38.txt
Removing a completed TODO.
Changing the message type occurred in 0fb6a120c6f0fbc94e305542fe29e790274be096 and updating this unit test to match took place in fa2b6ceca796311a918e28770d101b53a43f84f3. Didn't notice I could remove this TODO when fixing the conflicts (just wanted to get `main` unblocked!)
=> Remove completed TODO

.github/workflows/ci.yaml, .github/workflows/primer-test.yaml
I recently had a job run for 6h just to fail. Usually they all complete in <10min (CI) / <30min (Primer). So anything that is taking longer than that is probably going to fail anyway.
This PR adds `timeout-minutes` to the individual jobs to abort them after a reasonable amount of time. Usually 2x what they actually need. https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idtimeout-minutes
/CC: @DanielNoord Is 60min enough for Primer jobs? From what I've seen an individual one usually takes 20min.
=> Add timeouts for CI jobs

pylint/checkers/classes/class_checker.py, tests/functional/r/redefined_slots.txt
Change the error message for `redefiend-slots-in-subclass` to output slot names as list instead of string. Originally added in #5640.
Noticed that while fixing one error in Home-Assistant. I did find the comma-separated string slightly confusing to read.
/CC: @mbyrnepr2
=> Improve error message arguments formatting [redefined-slots]

.github/workflows/ci.yaml, .github/workflows/primer-test.yaml
Followup to #5752. After merging the first one, I noticed timeout issues on my personal fork. `PyCQA/pylint` seems to be fine. Maybe it's related to the number of concurrent runners available?
Anyway, I increased the timeouts so that they don't trigger accidentally anymore.
=> Increase timeouts

doc/development_guide/testing.rst, pylint/testutils/lint_module_test.py
|  | :hammer: Refactoring   |
| ✓ | :scroll: Docs          |
When running `tests_functional` and there is no `.rc` file, the 3 default messages disables do not apply [`suppressed-message`, `locally-disabled`, `useless-suppression`].
Problematic code block of `pylint/testutils/lint_module_test.py`:
```
rc_file: Union[Path, str] = PYLINTRC
try:
rc_file = test_file.option_file
self._linter.disable("suppressed-message")
self._linter.disable("locally-disabled")
self._linter.disable("useless-suppression")
except NoFileError:
pass
```
Suggested fix after discussion in [this comment](https://github.com/PyCQA/pylint/pull/5628#discussion_r785347490)
Closes #XXX
=> tests_functional rc file not found overpasses default disables hotfix

ChangeLog, doc/whatsnew/2.13.rst, pylint/checkers/variables.py, tests/functional/u/undefined/undefined_variable_py38.py
Extend an existing special case in the variables checker ("Single statement if, with assignment expression on same line as assignment") to include assignment expressions inside ternary operator tests used in calls (keyword or positional arguments).
Closes #5177 
Closes #5212
=> Fix false positive `used-before-assignment` for named expressions in ternary operators

pylint/checkers/classes/class_checker.py
Follow-up to https://github.com/PyCQA/pylint/pull/5621#discussion_r777069180.
Discussion had not actually resolved, but wanted to create the PR so that we can merge it immediately after we have resolved.
=> Remove unnecessary ``try...except`` from ``frame()`` call

ChangeLog, doc/whatsnew/2.13.rst, pylint/checkers/typecheck.py, tests/functional/a/assign/assignment_from_no_return_2.py, tests/functional/a/assign/assignment_from_no_return_2.txt
Fix `assignment-from-none` false negative case using `list.sort()`
Closes #5722
=> Fix assignment-from-none false negative case using list.sort()

.pre-commit-config.yaml
Upgrade `flake8-typing-import` to `1.12.0`. It was changed in `requirements_test_pre_commit.txt` in #5562 but never updated in in `pre-commit-config.yaml`.
https://github.com/asottile/flake8-typing-imports/compare/v1.10.1...v1.12.0
=> Upgrade flake8-typing-import to 1.12.0 [pre-commit]

pylint/lint/pylinter.py
I was poking around Pylint internals, trying to add new issue categories to the codebase, and stumbled upon this bug.
Since `MessageDefinitionStore._msgs_by_category` is a `defaultdict(list)`, using `.get()` here can break the code on bad input, because it will return `None`, which is not iterable.
=> Avoid using get on a defaultdict

doc/faq.rst
As far as I can tell, Pylint's `wrong-import-position` (C0413) and [pycodestyle's E402](https://www.flake8rules.com/rules/E402.html) are checking for the same thing.
=> wrong-import-position is equivalent to E402

ChangeLog, doc/whatsnew/2.13.rst, pylint/checkers/refactoring/recommendation_checker.py, tests/functional/u/use/use_maxsplit_arg.py, tests/functional/u/use/use_maxsplit_arg.txt
Fix crash in `use-maxsplit-arg` checker if `sep` is provided by keyword to `str.split()`.
Closes #5737
=> Fix crash in `use-maxsplit-arg` checker where `sep` given by keyword

pylint/checkers/utils.py
Came across an error while testing Home Assistant. `safe_infer` here assumes that `value` is a `FunctionDef` to be able to access `value.args.args`. The assumption is never fully checked however. `value` could also be an `<Instance of builtins.function ...>` which would cause an `AttributeError`.
I wasn't able to write a dedicated regression test unfortunately. Home Assistant only managed to break it with some combination of patching a builtin function and custom plugins which import parts of the checked files itself.
The condition was originally added in #5409
=> Fix unsafe `utils.safe_infer`

doc/exts/pylint_messages.py, doc/messages/messages_introduction.rst, doc/messages/messages_list.rst, doc/release.md, tbump.toml
Pretty stupid to have missed this. Should be merged asap to help SEO.
Closes #5740.
=> Fix duplicate names of ``Pylint Messages`` in docs

pylint/lint/pylinter.py
Finally 🎉 
This means that the ``__init__`` and all attributes of `PyLinter` are now fully typed. This will be the last typing PR (from my end) to be proposed for `2.13`. This is just a side-project I have been wanting to finish for a long time!
=> Add parameter typing to ``PyLinter``

ChangeLog, doc/whatsnew/2.13.rst, pylint/checkers/variables.py, tests/functional/u/use/used_before_assignment_except_handler_for_try_with_return.py, tests/functional/u/use/used_before_assignment_except_handler_for_try_with_return.txt, tests/functional/u/use/used_before_assignment_except_handler_for_try_with_return_py38.py, tests/functional/u/use/used_before_assignment_except_handler_for_try_with_return_py38.rc
Fixes #5524.
<s>In discussion I suggested closing #2835 as a duplicate, but if folks like we could "unlink" the two and reopen the older ticket.
The older ticket is just suggesting "always assume try statements fail", and @cdce8p suggested a new message for that (`possibly-unbound`). Probably a 2.14 or later thing. By contrast this PR is just fixing a quick false negative. Sorry for not seeing that we were more likely to tackle these separately!</s> Edit: done!
=> Fix false negative for `used-before-assignment` when some except handlers don't define a name

.pre-commit-config.yaml, pylint/checkers/format.py, pylint/lint/run.py, pylint/pyreverse/diadefslib.py
Due to https://github.com/DanielNoord/pydocstringformatter/pull/52
=> Fix the period added in docstring automatically by mistake

tests/test_check_parallel.py
This fixes the CI issues we were seeing in #5778 and #5805.
The second argument of these tuples is used to determine the number of jobs. However, the Linux runner only has two cores available. I'm not sure why this is different on Linux and Windows, but I think because we were trying to use more processes than available cores the test became either very slow or completely locked up.
You can see that we these changes both #5778 and #5805 pass the tests in expected times on all environments.
=> Don't assume test runners have more than 2 cores available

.github/workflows/ci.yaml
This should help narrow down issues with the CI if they keep popping up.
=> Add some flags showing information to the CI pytest runs

pylint/checkers/__init__.py, pylint/checkers/refactoring/refactoring_checker.py
Refactoring to prevent warnings being issued on these lines from a new
checker.
The new `unnecessary-list-lookup` checker being added in PR #5834 will cause regressions, refactoring to avoid this.
=> Use value directly instead of index in ``enumerate`` contexts

CONTRIBUTORS.txt, ChangeLog, doc/whatsnew/2.13.rst, pylint/checkers/misc.py, tests/checkers/unittest_misc.py
Using `\b` at the end of the patterns for note tags will only match ones that end in an alphanumeric character, immediately followed by a non-alphanumeric character, or the end of the string. This is due to `\b` being defined as a boundary between a word character (`\w`) and a non-word character (`\W`), or the end of the string. This leads to deviations like `???` being ignored when specified.
Swapping `\b` for a positive lookahead that targets a whitespace, a colon, or the end of a string accounts for this.
Closes #5840.
=> Fix matching note tags with a non-word char last

ChangeLog, doc/whatsnew/2.13.rst, pylint/checkers/stdlib.py, tests/functional/d/deprecated/deprecated_module_py33.py, tests/functional/d/deprecated/deprecated_module_py33.txt
Closes #5862, see full write-up there. 
`cElementTree` has been deprecated since Python 3.3, but does not raise `DeprecationWarning` to avoid pestering folks using really old idioms, from before the C-accelerator was on by default.
`pylint` can (and should!) be a bit more aggressive than that, and it was even floated on the python issue that this is a job for a linter.
=> Add stdlib `xml.etree.cElementTree` to deprecated modules

README.rst
(already done in #5869)
Not applicable since the `README` is only shown in GitHub ?
Not applicable since the `README` is only shown in GitHub ?
This commit updates a link formatted using Markdown syntax to use
ReStructuredText syntax, which is what the README file is written in.
This allows a prettier link visualization in GitHub, by not displaying
the full URL between parentheses.
=> Fix Markdown link in ReStructuredText README

.pre-commit-config.yaml, CONTRIBUTORS.txt
Removing the final slash in the `repo` url prevents git from not being
able to clone the repository.
`doc/whatsnew/<current release.rst>`. -> Not applicable since this is an internal implementation detail ?
Running `pre-commit run` on a fresh repository fails during the initalization of the `black-disable-checker` hook, because of a malformed `git` URL. The error log from `~/.cache/pre-commit/pre-commit.log` is given below.
```
pre-commit version: 2.17.0
git --version: git version 2.35.1
sys.version:
3.10.2 (main, Jan 15 2022, 19:56:27) [GCC 11.1.0]
sys.executable: /usr/bin/python
os.name: posix
sys.platform: linux
```
```
An unexpected error has occurred: CalledProcessError: command: …
```
=> Fix pre-commit configuration hook URL

.github/workflows/ci.yaml
See https://github.com/PyCQA/pylint/pull/5849#discussion_r816766177.
=> Also test on PyPy 3.7

pylint/checkers/imports.py
<s>Remove use of deprecated module `distutils` by relying on astroid's determination of the location of site packages. It seems error-prone to have two places for this logic.</s>
EDIT: remove unused functionality for determining the location of site-packages (unused since 9812c5a49ae430945e9ad5dde7ec523904498805).
=> Removed unused detection of site-packages directory

ChangeLog, doc/whatsnew/2.13.rst, pylint/checkers/imports.py, pylint/checkers/stdlib.py, tests/functional/d/deprecated/deprecated_module_py310.py, tests/functional/d/deprecated/deprecated_module_py310.rc, tests/functional/d/deprecated/deprecated_module_py310.txt, tests/functional/r/regression_02/regression_distutil_import_error_73.py
`distutils` was deprecated in Python 3.10. Adding it (and some other tiny methods and decorators that were missed) to the list of deprecations.
=> Add `distutils` to deprecated modules

ChangeLog, pylint/pyreverse/printer.py, tests/data/clientmodule_test.py, tests/pyreverse/data/classes_No_Name.dot, tests/pyreverse/data/classes_No_Name.html, tests/pyreverse/data/classes_No_Name.mmd, tests/pyreverse/data/classes_No_Name.puml, tests/pyreverse/data/classes_No_Name.vcg, tests/pyreverse/data/classes_colorized.dot, tests/pyreverse/data/classes_colorized.puml, tests/pyreverse/test_printer.py
This commit fixes the alignment of arguments and their type annotations
in pyreverse printer output.
Not a feature, is it an important bug fix ?
Until now, the following class
```python
class Example:
def method(self, arg: int):
pass
@classmethod
def class_method(cls, arg: int):
pass
@staticmethod
def static_method(arg: int):
pass
```
would generate the following PlantUML diagram when running `pyreverse -o puml example.py`
```puml
@startuml example
class Example {
class_method(cls: int, arg)
method(arg: int)
static_method(arg)
}
@enduml
```
This output displays wrong type hints because the alignment of arguments and their type annotations is based on the …
=> Fix pyreverse type hinting for class methods

ChangeLog, doc/whatsnew/2.13.rst, pylint/extensions/typing.py, tests/functional/ext/typing/typing_broken_callable.py, tests/functional/ext/typing/typing_broken_callable.rc, tests/functional/ext/typing/typing_broken_callable.txt, tests/functional/ext/typing/typing_broken_callable_deprecated_alias.py, tests/functional/ext/typing/typing_broken_callable_deprecated_alias.rc, tests/functional/ext/typing/typing_broken_callable_future_import.py, tests/functional/ext/typing/typing_broken_callable_future_import.rc, tests/functional/ext/typing/typing_broken_callable_future_import.txt
Similar to the broken NoReturn check - #5304, however this time for `Callable`.
Using `collections.abc.Callable` inside `Optional` and `Union` is broken in Python 3.9.0 and 3.9.1.
This one is a bit more difficult as we currently currently suggest replacing the deprecated `typing.Callable` with `collections.abc.Callable`. Doing that can result in unexpected errors. The PR will change that behavior and **not** emit `deprecated-typing-alias` for `typing.Callable` if `py-version < (3, 9, 2)`. In addition it adds a new check to warn about potential errors.
**Example broken code**
```py
from collections.abc import Callable
from typing import Optional, Union
Alias1 = Optional[Callable[[int], None] …
```
=> Add broken Callable check

CONTRIBUTORS.txt, ChangeLog, setup.cfg
This PR allows python version > 3.7 to use mccabe 0.7.x release, while older release will remain on mccabe 0.6.x.
There's no functional impact to be expected
Closes #5878
=> Mccabe 0.7

ChangeLog, doc/whatsnew/2.13.rst, pylint/checkers/stdlib.py, pylint/constants.py, pylint/utils/file_state.py, tests/functional/d/deprecated/deprecated_method_suppression.py, tests/functional/d/deprecated/deprecated_methods_py39.py, tests/functional/d/deprecated/deprecated_methods_py39.rc, tests/functional/d/deprecated/deprecated_methods_py39.txt, tests/functional/d/deprecated/deprecated_module_py3.rc, tests/functional/d/deprecated/deprecated_module_py3.txt, tests/functional/d/deprecated/deprecated_module_py39.py, tests/functional/d/deprecated/deprecated_module_py39.rc, tests/functional/d/deprecated/deprecated_module_py39.txt, tests/functional/d/deprecated/deprecated_module_py39_earlier_pyversion.py, tests/functional/d/deprecated/deprecated_module_py39_earlier_pyversion.rc, tests/functional/d/deprecated/deprecated_module_py39_earlier_pyversion.txt
**Before**
<s>The deprecated names checker ignored the `py_version` setting, raising warnings (or not) depending on the python interpreter version.</s>
`useless-suppression` is raised on disables of `deprecated-module` and sim. on lower versions where the module is not yet deprecated. This can make it challenging to get a project to pass pylint on multiple versions with a disable for a deprecated module.
**Now**
<s>Deprecated name warnings are emitted according to `py_version` (which falls back to the interpreter version).
Discussed at https://github.com/PyCQA/pylint/pull/5874#issuecomment-1061261766. </s>
`useless-suppression` is treated as incompatible with the stdlib deprecation …
=> Prevent `useless-suppression` on disables for stdlib deprecation checker

ChangeLog, doc/whatsnew/2.13.rst, requirements_test_min.txt, setup.cfg, tests/checkers/unittest_stdlib.py, tests/checkers/unittest_unicode/unittest_bad_chars.py, tests/functional/ext/broad_try_clause/broad_try_clause_extension.txt, tests/functional/i/invalid/invalid_name.py, tests/functional/i/invalid/invalid_name.txt, tests/functional/r/regression/regression_2913.py, tests/functional/r/regression/regression_2913.txt
These are the changes necessary for the tests to allow https://github.com/PyCQA/astroid/pull/1351 to pass the `pylint` test suite.
I'll annotate the changes to explain why something changed and why I think this is not a bad thing.
Obviously, this is all dependent on https://github.com/PyCQA/astroid/pull/1351 actually landing, which will need to be discussed in the `astroid` repository.
_Expect a push to https://github.com/PyCQA/astroid/pull/1351 in a couple of minutes to undraft that PR._
=> Fixes to tests due to (possible) new ``tolineno`` behaviour

ChangeLog, doc/whatsnew/2.13.rst, pylint/checkers/classes/class_checker.py, tests/functional/i/invalid/invalid_class_object.py
Fix a false positive for `invalid-class-object` when the object being assigned is not inferable. (`None` is one of the ambiguous cases returned by `safe_infer()`.)
=> Fix false positive for `invalid-class-object` when inference fails

pylint/testutils/checker_test_case.py, tests/checkers/unittest_base.py
Follow up to #5897. I did not update these tests in that PR as it was not necessary (we only raise a `DeprecationWarning` for unittests with incorrect end positions).
=> Fix end position in unittests

ChangeLog, doc/whatsnew/2.13.rst, pylint/checkers/imports.py, tests/functional/u/ungrouped_imports_suppression.py, tests/functional/u/ungrouped_imports_suppression.txt
Needed for a PR that stops using the deprecated ``cachedproperty`` decorator from `astroid`.
=> Fix disabling of ``ungrouped-imports``

pylint/checkers/classes/class_checker.py, pylint/checkers/design_analysis.py, pylint/checkers/refactoring/refactoring_checker.py, pylint/checkers/typecheck.py, pylint/checkers/variables.py
Last PR to fix all deprecations as a result of `astroid` upgrade 🎉
=> Use ``functools.cached_property`` on 3.8+

ChangeLog, doc/whatsnew/2.13.rst, pylint/checkers/variables.py, tests/functional/u/unused/unused_argument.py, tests/functional/u/unused/unused_argument.txt
Closes #5771 
Refs PyCQA/astroid#1382
Pardon me if this shouldn't go in 2.13! I just noticed no regression test PR for it yet, even though it's already fixed. Feel free to bump the milestone.
=> Add regression test for #5771

doc/faq.rst
Fixes French punctuation (space before punctuation) and a vocabulary mistake in a FAQ entry in the docs.
Nothing spectacular, hence I guess it's okay not to write a CHANGELOG entry for it? 🤔
=> Fix English punctuation and grammar (FAQs)

pylint/checkers/utils.py
While looking at #5901 I noticed that the typing on `safe_infer` is incorrect. `Uninferable` doesn't subclass `NodeNG` and thus the return annotation is incorrect. I also added typing to related functions.
Change was introduced in https://github.com/PyCQA/pylint/pull/2338/. I haven't fully investigated but I think this was just a mistake (or `Uninferable` was added in between these 4 years).
=> Fix typing of ``safe_infer``

pylint/checkers/base.py, pylint/checkers/ellipsis_checker.py, pylint/checkers/spelling.py, pylint/extensions/_check_docs_utils.py, pylint/extensions/docparams.py, pylint/extensions/docstyle.py
=> Remove uses of ``NodeNG.doc`` in favour of ``doc_node``

pylint/checkers/classes/special_methods_checker.py, pylint/checkers/typecheck.py, pylint/checkers/utils.py
Refactoring necessary for https://github.com/PyCQA/astroid/pull/1475 to be "acceptable" for `pylint`.
Note that the change to `names_hint = ", ".join(names)` might be unrelated, but I couldn't get `pre-commit` to pass without it and I wanted to show that if you clone https://github.com/PyCQA/astroid/pull/1475 and these changes then both test suites should pass.
=> Handle ``ComprehensionScope`` and their behaviour better

requirements_test_min.txt, tests/checkers/unittest_refactoring.py, tests/test_regr.py
Use pytest-timeout plugin instead of custom context managers to handle timeouts in tests.  Amend #5925.
=> Use pytest-timeout for tests

CONTRIBUTORS.txt, ChangeLog, doc/whatsnew/2.13.rst, pylint/checkers/utils.py, tests/functional/u/unexpected_special_method_signature.py, tests/functional/u/unexpected_special_method_signature.txt
Noticed this whilst working on #5938.
These magic methods were missing from the `_SPECIAL_METHODS_PARAMS` variable used for several checks so I've added them in:
- [`__subclasses__`](https://docs.python.org/3/library/stdtypes.html?highlight=__subclasses#class.__subclasses__)
- [`__init_subclass__`](https://docs.python.org/3/library/stdtypes.html?highlight=__subclasses#class.__subclasses__)
This variable gets used in these checkers:
- variables.py
- class_checker.py
- special_methods_checker.py
=> Add missing __magic__ methods to `_SPECIAL_METHODS_PARAMS`

ChangeLog, doc/whatsnew/2.13.rst, pylint/checkers/variables.py, tests/functional/u/used/used_before_assignment_class_nested_under_function.py
Fix false `used-before-assignment` for a class definition nested under a function subclassing a class defined outside the function. Because the class is guarded by a function, the parent class should be available at runtime.
Closes #4590
=> Fix `used-before-assignment` false positive for class definition in function scope

.pre-commit-config.yaml, doc/conf.py, doc/data/messages/e/empty-docstring/bad.py, doc/data/messages/e/empty-docstring/good.py, doc/data/messages/y/yield-inside-async-function/bad.py, doc/data/messages/y/yield-inside-async-function/details.rst, doc/data/messages/y/yield-inside-async-function/good.py, doc/data/messages/y/yield-inside-async-function/related.rst, doc/exts/pylint_messages.py
This closes #5527. I'd like to create a separate issue to track the progress of migrating the code examples of `pylint-errors`.
This allows for each message to have a `good.py`, `bad.py`, `related.rst` and `details.rst` section. I have added two examples which can be viewed [here](https://pylint--5934.org.readthedocs.build/en/5934/messages/error/yield-inside-async-function.html) and [here](https://pylint--5934.org.readthedocs.build/en/5934/messages/convention/empty-docstring.html). Based on [this](https://vald-phoenix.github.io/pylint-errors/plerr/errors/async/E1700) and [this](https://vald-phoenix.github.io/pylint-errors/plerr/errors/basic/C0112). Note that …
=> Set up system of code examples and details for message documentation

.github/workflows/ci.yaml, doc/data/messages/e/empty-docstring/bad.py, doc/test_messages_documentation.py
Well, I immediately spotted a mistake...
We could also think about moving the message of `empty-docstring` to the `doc_node` attribute of the definition instead of on the definition line but that's for another PR.
Code is based on the functional test runner but I have removed everything that was redundant. I couldn't inherit the class because there was a lot of stuff to handle the `.rc` and `.txt` files. This seemed like a simpler approach.
I did not put this in the normal test suite as I didn't want to unnecessarily inflate local test runs. This is really something that only should be run before merging so the CI seemed a …
=> Add CI test for message documentation

doc/release.md, doc/test_messages_documentation.py
Follow-up to #5877. This document the new git flow, based on review for https://github.com/PyCQA/astroid/pull/1438
Closes #4701
=> Document a better release process

doc/data/messages/a/access-member-before-definition/bad.py, doc/data/messages/a/access-member-before-definition/good.py, pylint/checkers/classes/class_checker.py
Code examples based on [pylint-errors](https://github.com/vald-phoenix/pylint-errors) and my own work.
Ref. #5953.
=> Add documentation for access-member-before-definition

ChangeLog, doc/user_guide/options.rst, doc/whatsnew/2.13.rst, pylint/checkers/base.py, pylint/constants.py, pylint/utils/linterstats.py, pylintrc, tests/checkers/unittest_base.py, tests/functional/t/typevar_naming_style_default.py, tests/functional/t/typevar_naming_style_default.txt, tests/functional/t/typevar_naming_style_rgx.py, tests/functional/t/typevar_naming_style_rgx.rc, tests/functional/t/typevar_naming_style_rgx.txt
Not sure if we want to do this, but:
After merging https://github.com/PyCQA/pylint/pull/5825, we can merge this. It only adds the necessary boilerplate for `typevar` name checking, but uses the pattern as set for classes.
This makes the diff of https://github.com/PyCQA/pylint/pull/5221 even smaller and should help getting that merged asap after #5825 has been merged.
Closes #3401.
=> Create a ``TypeVar`` style for ``invalid-name``

doc/data/messages/a/abstract-class-instantiated/bad.py, doc/data/messages/a/abstract-class-instantiated/good.py, doc/data/messages/a/abstract-method/bad.py, doc/data/messages/a/abstract-method/good.py
Code examples based on [pylint-errors](https://github.com/vald-phoenix/pylint-errors) and my own work.
Ref. #5953.
=> Pylint errors 1

ChangeLog, doc/whatsnew/2.14.rst, pylint/checkers/typecheck.py, tests/functional/n/no/no_member_assign_same_line.py, tests/functional/n/no/no_member_assign_same_line.txt
Emits `no-member` when attempting to assign an instance attribute to itself before it has been defined, since at the moment of attempted assignment, there is no such member.
Closes #1555
=> Fix #1555: Fix false negatives for `no-member` from self-referencing assignments

ChangeLog, doc/data/messages/u/unnecessary-list-index-lookup/bad.py, doc/data/messages/u/unnecessary-list-index-lookup/good.py, doc/whatsnew/2.14.rst, pylint/checkers/refactoring/refactoring_checker.py, tests/functional/c/consider/consider_using_enumerate.py, tests/functional/u/unnecessary/unnecessary_list_index_lookup.py, tests/functional/u/unnecessary/unnecessary_list_index_lookup.txt, tests/functional/u/unnecessary/unnecessary_list_index_lookup_py38.py, tests/functional/u/unnecessary/unnecessary_list_index_lookup_py38.rc
Added a new checker for catching the case of iterating over a list using `enumerate()`:
for index, value in enumerate(mylist):
print(mylist[index]) # Bad, should use value instead
This will now report
Unnecessary list index lookup, use 'value' instead
Closes #4525
=> New checker `unnecessary-list-index-lookup` (#4525)

ChangeLog, doc/user_guide/options.rst, pylint/checkers/base/name_checker/checker.py, tests/functional/t/typevar_naming_style_default.py, tests/functional/t/typevar_naming_style_default.txt
Allow TypeVar names with multiple uppercase characters like `HVACModeT` and `IPAddress`. Note that if a uppercase suffix is added, it must be `T`. `IPAddressU` is still invalid.
Closes #5981
=> Loosen TypeVar name pattern

ChangeLog, pylint/checkers/utils.py, pylint/checkers/variables.py, pylint/constants.py, pylint/extensions/typing.py, tests/functional/ext/typing/typing_broken_callable.py, tests/functional/ext/typing/typing_broken_callable.txt, tests/functional/ext/typing/typing_broken_noreturn.py, tests/functional/ext/typing/typing_broken_noreturn_future_import.py, tests/functional/ext/typing/typing_broken_noreturn_py372.py
`broken-noreturn` and `broken-collections-callable` errors should not be emitted inside `if TYPE_CHECKING` blocks. At runtime `TYPE_CHECKING` is false and thus the block is never executed and cannot fail.
=> Don't emit broken typing errors inside TYPE_CHECKING blocks

ChangeLog, doc/whatsnew/2.14.rst, pylint/checkers/modified_iterating_checker.py, tests/functional/m/modified_iterating.py
|   | :scroll: Docs          |
Fix program crash for `modified_iterating-list` when the list being iterated through is a function call.
The bug was fixed so that it will not occur with dictionaries and sets as well.
A regression test was added too.
Closes #5969
=> Fix issue #5969 for `modified_iterating-list`

doc/data/messages/b/bad-classmethod-argument/bad.py, doc/data/messages/b/bad-classmethod-argument/good.py
=> Added bad-classmethod-argument example

ChangeLog, pylint/checkers/classes/class_checker.py, tests/functional/p/protected_access.py, tests/functional/p/protected_access.txt
Fixes a false negative regression in #5662.
Closes #5989
=> Fix false negative for `protected-access` on functions

pylint/config/__init__.py, pylint/lint/utils.py
Follow-up to crashes in 2.13.0 there were not reported properly see https://github.com/PyCQA/pylint/issues/5969#issuecomment-1079581083
=> Better error message when we cant write the crash files

doc/data/messages/b/bad-staticmethod-argument/bad.py, doc/data/messages/b/bad-staticmethod-argument/good.py
=> Added example for bad-staticmethod-argument

doc/data/messages/b/bad-except-order/bad.py, doc/data/messages/b/bad-except-order/good.py
=> Added example for bad-except-order

doc/data/messages/a/assignment-from-no-return/bad.py, doc/data/messages/a/assignment-from-no-return/good.py
=> Added assignment-from-no-return message example

doc/data/messages/a/assignment-from-none/bad.py, doc/data/messages/a/assignment-from-none/good.py
=> Added example for assignment-from-none

ChangeLog, doc/whatsnew/2.13.rst, doc/whatsnew/2.14.rst, pylint/checkers/ellipsis_checker.py, tests/functional/u/unnecessary/unnecessary_ellipsis.py
Closes #5973
Fix false positive for ``unnecessary-ellipsis`` when using an ellipsis as a default argument.
=> `unnecessary-ellipsis` false positive: allow ellipsis as default argument

ChangeLog, doc/data/messages/a/await-outside-async/bad.py, doc/data/messages/a/await-outside-async/good.py, doc/data/messages/a/await-outside-async/related.rst, pylint/checkers/typecheck.py
This adds examples and link to the relevant PEP for ``await-outside-async``. 
The new test case for checking the message docs actually found a bug (which cost me more time to find than I'd be willing to admit 😀 ): 
Because the relevant ``visit_await`` method was implemented in the wrong checker class (there are two in the module), it was not possible to disable all messages and then just enable ``await-outside-async`` again.
As both the impact and the fix of this are so minor I decided to directly fix this in this PR and only add a …
=> Add examples for ``await-outside-async`` and fix activation of message

doc/user_guide/run.rst
=> Document means of clearing inference cache

ChangeLog, doc/whatsnew/2.13.rst, doc/whatsnew/2.14.rst, pylint/checkers/base/basic_error_checker.py, tests/functional/n/nonexistent_operator.py
This PR relax requirements for the 'nonexistent-operator' checker to allow repeated unary ops, separated by spaces or with parens.
Closes #5769
=> Change 'nonexistent-operator' to allow repeated unary ops (with space or parens)

doc/data/messages/b/bad-exception-context/bad.py, doc/data/messages/b/bad-exception-context/good.py, doc/data/messages/b/bad-exception-context/related.rst
Examples and related links for ``bad-exception-context``.
Ref: #5953
=> Examples for ``bad-exception-context``

pylint/checkers/base_checker.py, pylint/checkers/logging.py, pylint/config/__init__.py, pylint/config/argument.py, pylint/config/arguments_manager.py, pylint/config/config_initialization.py, pylint/config/exceptions.py, pylint/config/utils.py, pylint/lint/pylinter.py, pylintrc, tests/config/data/logging_format_interpolation_style.py, tests/config/data/logging_format_interpolation_style.rc, tests/config/test_argparse_config.py, tests/test_regr.py
This is my first proposed step towards #5392.
We could build on this in a separate branch, as I intend not to make this interfere too much with any current code. That should keep merge conflicts low.
All of this is based on the documentation of `argparse` found here:
https://docs.python.org/3/library/argparse.html
The idea of this PR is to showcase how we can transform our current `optdicts` into a `Argument` class that we can then at some point start passing to the `ArgumentsManager`. I think that second part would be the next step, to make this in a MVP. After that we can start working on adding new checkers.
I chose the logging module as it is a fairly …
=> Create an `Argument` class and allow convertion of optdict into them

ChangeLog, doc/whatsnew/2.13.rst, setup.cfg
Closes #6028. `testing_pylintrc` wasn't being included in package distributions. 
This should fix running tests via `tox` (this is where I encountered it) and any uses of `pylint.testutils`
=> Include ``testing_pylintrc`` in source and wheel distributions

pylint/config/option_manager_mixin.py, pylint/lint/run.py, tests/test_self.py
I'm trying to clean up `read_config_file` to make it easier to port it to a new system.
This seems like it doesn't fit here. It was added in https://github.com/PyCQA/pylint/commit/3deb961d3583075e48fbdcb23cc2680fecf4329d and never touched (besides some refactoring). I think logilab might have used this internally, but it seems very illogical to define an option at config file parse time. It should be done earlier.
One change that comes from this is that the option has been moved. I tried to keep it in the same place, but I couldn't figure it out without a major refactor of the `optparse` code. That doesn't seem worth it.
```console
Options:
-h, --help            show this help message and …
```
=> Move ``long-help`` to the ``Run`` class

setup.cfg
To avoid "'timeout' not found in  configuration option"
When using --strict-markers with pytest locally.
Follow up to #5932
=> Add an explicit marker for ``pytest-timeout``

ChangeLog, pylint/checkers/ellipsis_checker.py, tests/functional/u/unnecessary/unnecessary_ellipsis.py
Fix crash for ``unneccessary-ellipsis`` checker when an ellipsis is used inside of a list.
Closes #6037
Closes #6048 
Closes #XXX
=> Fix crash for ``unneccessary-ellipsis`` checker 

pylint/checkers/base_checker.py, tests/checkers/unittest_base_checker.py
Closes #6045. Adds a unit test for the `__gt__` method mentioned in the linked issue.
N.B. since we don't currently implement a `__eq__` method (as described in the [docs](https://docs.python.org/3/library/functools.html#functools.total_ordering)) we can't currently assert something like `fake_checker_1 == fake_checker_2` even though they have the same name and args.
Didn't add it in since we're only really doing this for coverage and seems unnecessary, but happy to add in for completeness if desired.
=> Total ordering unit test

ChangeLog, doc/whatsnew/2.13.rst, pylint/checkers/classes/class_checker.py, tests/functional/s/super/super_init_not_called.py, tests/functional/s/super/super_init_not_called.txt
Closes #6027.
Should have never put that comment there...
=> Fix crash in ``super-init-not-called`` checker

pylint/checkers/refactoring/refactoring_checker.py, tests/functional/u/unnecessary/unnecessary_list_index_lookup.py
This fixes a crash in the `unnecessary-list-index-lookup` checker where the value from `enumerate()` is being destructured, and thus no variable name is available. There are conceivably some cases where we could still salvage a useful check here, but the possible benefit seems minor and the original motivation was to catch the simple cases, so I hope we can just ignore this case for now.
Closes #6049
=> Fix crash in ``unnecessary-list-index-lookup`` checker (#6049)

pylint/config/environment_variable.py, pylint/config/find_default_config_files.py, tests/lint/unittest_lint.py
I wonder if this is considered external. It is in the `__all__` but there is no reason for anybody to use this, I think? We don't even use it as the logic for finding the configuration file has moved to `find_default_config_files`.
=> Deprecate ``find_pylintrc``

pylint/config/find_default_config_files.py, tests/config/test_find_default_config_files.py
I added some tests for our config finding functions. I'm wondering if there's not something to do regarding ``find_pylintrc``. It's none if there is no pylintrc but there could be setup.cfg or pyproject.toml with valid configuration.
```python
def find_pylintrc() -> Optional[str]:
"""Search the pylint rc file and return its path if it finds it, else return None."""
for config_file in find_default_config_files():
if config_file.endswith("pylintrc"):
return config_file
return None
```    
Imo it could be nice to have a function : "recover configuration from wherever" and return a configuration object (which is why I made tests for the two important function to …
=> More tests for config file finding, handle malformatted setup.cfg

doc/data/messages/b/bad-format-character/bad.py, doc/data/messages/b/bad-format-character/details.rst, doc/data/messages/b/bad-format-character/good.py, doc/data/messages/b/bad-format-character/related.rst
Add examples for ``bad-format-character``.
I noticed that this currently only works for old-style formatting, so I opened issue #6085 and referenced it in the ``details.rst``.
Ref: #5953
=> Examples for ``bad-format-character``

doc/data/messages/b/bad-str-strip-call/bad.py, doc/data/messages/b/bad-str-strip-call/details.rst, doc/data/messages/b/bad-str-strip-call/good.py, doc/data/messages/b/bad-str-strip-call/related.rst
Add examples and explanation for ``bad-str-strip-call``.
Ref: #5953
=> Add examples for ``bad-str-strip-call``

pylint/lint/parallel.py
Another attempt. Probable culprit of our CI issues would be https://github.com/PyCQA/pylint/pull/5612.
Turns out `.join()` is necessary. I checked locally and with the `join()` statement here there are more calls to internal `join()` methods than when only relying on the termination as the context manager exits. So, although I don't really understand the internals of `multiprocessing` and `threading` the change to the contextmanager has changed behaviour.
The difference in behaviour comes from `terminate()` only joining the `worker_handler` and `join()` also closing the pools.
=> Close and join pools correctly in ``parallel.py``

doc/test_messages_documentation.py, pylint/config/config_initialization.py, pylint/config/option_manager_mixin.py, pylint/config/options_provider_mixin.py, pylint/lint/pylinter.py, pylint/lint/run.py
Sorry for this being a bit all over the place...
These are some basic refactors all related to `read_config_file` to make the parameters that get passed to that function a little more logical. That makes it easier to write a new function that doesn't need to handle some of the non-sensical parameters.
I also removed the configuration file discovery out of `PyLinter` into `Run`. Since the configuration is done in `Run` it makes no sense to do that discovery in `PyLinter`.
=> Some refactors of configuration file discovery

ChangeLog, pylint/checkers/ellipsis_checker.py, tests/functional/u/unnecessary/unnecessary_ellipsis.py, tests/functional/u/unnecessary/unnecessary_ellipsis.txt
Narrow the scope of the ``unnecessary-ellipsis`` checker to functions & classes which contain both a docstring and an ellipsis.
Closes #XXX
=> Narrow the scope of the ``unnecessary-ellipsis`` checker 

pylint/config/find_default_config_files.py, pylint/lint/pylinter.py, pylint/testutils/__init__.py, pylint/testutils/utils.py, tests/config/test_find_default_config_files.py, tests/lint/unittest_lint.py
I have integrated the tests from #6056.
We have a similar issue here: `find_default_config_files` is in `__all__` but it is such an internal function that I think we should be able to change it.
I can also add `str()` calls to all `yields`.
=> Refactor ``find_default_config_files``

pylint/config/__init__.py, pylint/config/arguments_manager.py, pylint/config/config_file_parser.py, pylint/config/config_initialization.py, pylint/config/option_manager_mixin.py
Blocked by #6052.
Last commit introduces a new configuration parser. After some debating with myself I have opted to retain the idea of transforming all rich types into strings. `argparse` can only handle strings. We could inject the rich types into the `Namespace` object but I decided against it. Stuff like that is what makes the current configuration handling so difficult to understand. Let's separate things clearly: a file parser parses a file and an argument parser parses arguments.
The commit also introduces other changes that followed from these changes.
One major change is that we will now allow configuration in `.toml` files without the sections. I have not yet implemented this for …
=> Create ``_ConfigurationFileParser`` class

doc/conf.py, doc/requirements.txt
- change default documentation from `python-docs-theme` to `furo`
- change `conf.py` to use `furo` default config first to look what need to change
- add `furo` and remove `python-docs-theme` dep to `doc/requirement.txt` 
Ref #5953
=> Change documentation theme to use `furo` theme

ChangeLog, doc/whatsnew/2.14.rst, pylint/checkers/typecheck.py, tests/functional/n/not_callable.py
Update E1102 to only be raised when no inferred value is callable.
Resolves #5931
=> Fix E1102 / ``not-callable`` false positive for property that returns a lambda function conditionally

pylint/config/argument.py, pylint/reporters/text.py, pylint/utils/utils.py
=> Add typing to two utility functions

pylint/checkers/classes/class_checker.py, pylint/config/argument.py
=> Use the ``argparse`` config handler in ``class_checker.py``

doc/data/messages/m/missing-format-argument-key/related.rst
fix link to use for `missing-format-argument-key` in `related.rst`
-fix link in related.rst with `* ...`
=> fix link in `missing-format-argument-key`

ChangeLog, pylint/checkers/classes/class_checker.py, tests/functional/r/redefined/redefined_slots.py
=> ``redefined-slots-in-subclass`` crash when slot type is neither a string or constant node

ChangeLog, pylint/checkers/variables.py, tests/functional/u/unused/unused_argument.py, tests/functional/u/unused/unused_argument.txt, tests/functional/u/used/used_before_assignment_comprehension_homonyms.py
Several nodes types didn't meet the allow list for homynym handling b/w except blocks and comprehensions.
Closes #6069
=> Account for more node types in handling of except block homonyms with comprehensions

pylint/config/callback_actions.py, pylint/config/option_manager_mixin.py, pylint/config/options_provider_mixin.py, pylint/lint/run.py
This probably won't work and might need some refactoring. However, setting custom callback actions on `"action"` is how this should be done in `argparse`. This at least allows `optparse` to handle those while I figure out how to pass stuff like `linter` and `Run` to these callback actions.
This is thus necessary boilerplate to make reviewing later on easier.
=> Allow setting a ``CallbackAction`` instead of ``"callback"``

doc/data/messages/c/confusing-consecutive-elif/bad.py, doc/data/messages/c/confusing-consecutive-elif/details.rst, doc/data/messages/c/confusing-consecutive-elif/good.py, doc/data/messages/c/confusing-consecutive-elif/pylintrc, doc/test_messages_documentation.py
To ease the process of reviewing your PR, do make sure to complete the following boxes.
In order to test some messages (e.g. for messages of optional checkers), we need a way to use a custom config.
With this modification it is possible to place a ``pylintrc`` file next to ``good.py`` and ``bad.py``.
To prove it works I added a documentation example for one of the optional checkers.
Ref: https://github.com/PyCQA/pylint/issues/5953#issuecomment-1085587049
=> Enable usage of custom pylintrc file for message documentation tests

pylint/config/argument.py, pylint/config/arguments_manager.py, pylint/config/utils.py, pylint/lint/pylinter.py
**Need to rebase**.
`store_true` arguments can't have a `type`. I thought about subclassing this, but then I would need to change the order of the `__init__` parameters to provide a default value for `type`. I'll probably do that at the end but I want to wait for any other new action types I haven't thought about yet.
=> Add a _StoreTrueArgument class

doc/test_messages_documentation.py
=> Assert number of messages in test_messages_documentation.py

doc/data/messages/c/chained-comparison/bad.py, doc/data/messages/c/chained-comparison/good.py
=> Added chained-comparison message example

doc/data/messages/c/cell-var-from-loop/bad.py, doc/data/messages/c/cell-var-from-loop/good.py, doc/data/messages/c/cell-var-from-loop/related.rst
=> Added cell-var-from-loop message example

doc/test_messages_documentation.py
[``Counter.total``](https://docs.python.org/3/library/collections.html#collections.Counter.total) was only added in Python 3.10, thus the check for the ``sys.version_info`` must be ``> (3, 9)`` instead ``>= (3, 9)``.
=> Fix version constraint in ``test_messages_documentation``

ChangeLog, pylint/checkers/variables.py, tests/functional/u/undefined/undefined_variable_py38.py, tests/functional/u/undefined/undefined_variable_py38.txt, tests/functional/u/unused/unused_variable.py
Closes #6136
Extends the fix from #6073. (There, I had to be careful to not emit `unused-argument`, since that's all the test suite alerted me to, but with diffing primer output locally, I noticed the same deal with `unused-variable`. So I handle that the same way.)
=> Fix handling of "for x in x" homonyms

pylint/checkers/variables.py, tests/functional/u/unused/unused_variable.py, tests/functional/u/unused/unused_variable.txt
Per discussion on #4391, which we closed, I think we can stick to the one-warning-per-variable-per-scope contract, so these TODOs are out of date.
If we want to look into adding warnings, we can do it more broadly in #5838.
=> Remove TODOs in `unused-variable` tests

ChangeLog, doc/whatsnew/2.13.rst, doc/whatsnew/2.14.rst, pylint/checkers/variables.py, tests/functional/u/unused/unused_import_everything_disabled.py
This should fix the false positive reported in #6089 (yes I named my branch wrong 😉).
But as I am not very familar with this part of the code base, I would like to ask @jacobtylerwalls for a review if moving this check can have other side effects than just a small performance loss.
Test suite is passing locally.
Closes #6089
=> Fix false positive for ``unused-import`` when disabling both ``used-before-assignment`` and ``undefined-variable``

doc/data/messages/l/literal-comparison/bad.py, doc/data/messages/l/literal-comparison/good.py, doc/data/messages/l/literal-comparison/related.rst
=> Added literal-comparison message example

doc/data/messages/b/bad-super-call/bad.py, doc/data/messages/b/bad-super-call/details.rst, doc/data/messages/b/bad-super-call/good.py, doc/data/messages/b/bad-super-call/related.rst
Co-authored by: Vladyslav Krylasov <vladyslav.krylasov@gmail.com>
Ref #5953
=> Add example for ``bad-super-call``

doc/data/messages/c/comparison-with-itself/bad.py, doc/data/messages/c/comparison-with-itself/good.py
=> Added comparison-with-itself message example

pylint/checkers/unicode.py, pylint/config/argument.py, pylint/config/arguments_manager.py, pylint/config/callback_actions.py, pylint/config/option.py, pylint/config/options_provider_mixin.py, pylint/config/utils.py, pylint/lint/pylinter.py, pylint/lint/run.py, tests/test_self.py
This is best viewed from the commit view.
Tried to keep it as short as possible, but it's much easier to do this by flipping the switch once. I'll annotate a little bit.
Essentially after this PR all callback options such as ``--generate-rc-file`` are now handled by `argparse`.
=> Work towards turning on ``future_option_parsing`` in ``PyLinter``

pylint/config/argument.py, pylint/config/arguments_manager.py, pylint/config/callback_actions.py, pylint/config/config_initialization.py, pylint/config/help_formatter.py, pylint/config/option_manager_mixin.py, pylint/config/utils.py, pylint/lint/pylinter.py, pylint/lint/run.py
Blocked by #6143 and #6144
The second to last commit is a short refactor. The other is a refactor of how we generate the help message. I have chosen to deprecate the `level` option as it makes everything way more complicated than it needs to be. Some of the options with `level==1` should arguably be displayed always and it is pretty difficult to retrieve their original `help` message after they have been parsed as `SUPRESS` previously.
I think this makes it a lot simpler and doesn't change that much for the end-user.
=> Refactor the help message

ChangeLog, doc/faq.rst, doc/whatsnew/2.14.rst, examples/pylintrc, pylint/checkers/async.py, pylint/checkers/classes/class_checker.py, pylint/checkers/typecheck.py, pylint/config/argument.py, pylint/config/arguments_manager.py, pylint/config/deprecation_actions.py, pylint/config/utils.py, pylint/lint/pylinter.py, pylint/utils/utils.py, pylintrc, tests/config/test_argparse_config.py, tests/functional/m/mixin_class_rgx.rc
Closes #5205.
Finally, the first real new option that comes from this migration. With the use of `new_names` and `old_names` we can now deprecate options and warn about them accordingly.
I have applied it to two options already.
=> Deprecate ignore-mixin-members + add ignored-checks-for-mixins

pylint/config/argument.py, pylint/config/callback_actions.py, pylint/config/config_initialization.py, pylint/lint/pylinter.py, tests/lint/unittest_lint.py, tests/test_regr.py
Blocked by #6173.
Three small commits to fix some stuff that will break as soon as we change `self.config` to `self.namespace` in `PyLinter`.
=> Refactors in preparation of using ``namespace`` in ``PyLinter``

pylint/checkers/base/docstring_checker.py, pylint/checkers/refactoring/refactoring_checker.py, pylint/checkers/spelling.py
=> Use ``argparse`` config handler on three checkers

ChangeLog, doc/whatsnew/2.14.rst, pylint/checkers/strings.py, tests/functional/b/bad_string_format_type.py, tests/functional/b/bad_string_format_type.txt
First and easy part of #6163.
After I started to work on this I realized that making ``bad-string-format-type`` and ``bad-format-character`` work on new-style formatting and f-strings will require a change to ``pylint.checkers.utils.parse_format_method_string``.
As this also leads to small adjustments in the callers of this function, I would rather do this in a separate PR, and then continue working on ``bas-string-format-type`` and ``bad-format-character``.
=> Fix false negative for ``bad-string-format-type`` when using a variable as input

pylint/config/arguments_manager.py, pylint/config/config_initialization.py, pylint/lint/pylinter.py
I think this means that ``_config_initialization`` is done expect for the removal of dead code after `optparse` is removed at some point.
=> Number of small refactors in ``_config_initialization``

pylint/config/argument.py, pylint/config/arguments_manager.py, pylint/config/utils.py, pylint/lint/pylinter.py
This handles the last unsupported key in `optdicts`, a minor milestone 😄  
I'm also going to use `# TODO: Optparse: ...` from now on, because that makes it easier to recognise them.
=> Handle ``group`` in optdicts and ``option_groups``

ChangeLog, doc/whatsnew/2.13.rst, pylint/checkers/variables.py, tests/functional/u/used/used_before_assignment_nonlocal.py, tests/functional/u/used/used_before_assignment_nonlocal.txt
I think it's important to solve the false positive instead of worrying too much about the possibility of false negatives from control-flow (for instance, if the inner function is never called).
Closes #5394
=> Prevent `used-before-assignment` for assignment via nonlocal after type annotation

ChangeLog, doc/whatsnew/2.13.rst, pylint/extensions/_check_docs_utils.py, pylint/extensions/docparams.py, tests/functional/ext/docparams/parameter/missing_param_doc_required_Google.py, tests/functional/ext/docparams/parameter/missing_param_doc_required_Google.txt, tests/functional/ext/docparams/parameter/missing_param_doc_required_Numpy.py, tests/functional/ext/docparams/parameter/missing_param_doc_required_Sphinx.py, tests/functional/ext/docparams/parameter/missing_param_doc_required_Sphinx.txt
Closes #5815, closes #5406.
See the tests for what is allowed now. Asterisks are no longer required and will be parsed correctly in Google style. I have chosen to fix this in the extension itself. Internally we still see the argument names including the asterisk, but when we finally check if we should emit the warning we also check whether the name without asterisks exists. If so, we don't emit.
=> Handle asterisks better in Sphinx and Google style docstrings

pylint/config/arguments_manager.py, pylint/config/option_manager_mixin.py, pylint/lint/pylinter.py, pylint/testutils/unittest_linter.py, tests/lint/unittest_lint.py, tests/test_regr.py
Sorry for the size of this PR. Basically these are all the methods defined on `OptionsManagerMixIn`. Sadly they are all public so they will need to be deprecated.
I thought it would be better to move them on `_ArgumentsManager` and deprecate from there. This would allow us to deprecate instantiating `OptionsManagerMixIn` and completely disregard that file until `3.0` gets released.
=> Copy all of ``OptionsManagerMixIn`` methods into ``_ArgumentsManager``

pylint/config/arguments_manager.py, pylint/config/config_initialization.py, tests/config/test_deprecations.py
=> Deprecate ``load_config_file``, ``load_configuration`` and ``load_configuration_from_config``

doc/data/messages/u/use-maxsplit-arg/bad.py, doc/data/messages/u/use-maxsplit-arg/details.rst, doc/data/messages/u/use-maxsplit-arg/good.py
=> Add example for `use-maxsplit-arg` message documentation

.github/workflows/tests.yaml
This should improve the speed of our CI. Since all tests jobs now depend on `Linux` passing there is really no need to separate these set-ups steps. They just take extra time setting up Python, checking out code and restoring the venv. That can all be done in the same runner: freeing up more runners and decreasing the overall runtime of the CI.
=> Decrease number of runners used in CI

tests/checkers/unittest_refactoring.py
Increased test timeout for unit test `test_issue_5724`, such test failed due to timeout on some slow machines (e.g. qemu when we are porting this package onto RISC-V architecture, it needs 30 seconds but the original timeout was only 25)
There are no known issues regarding this change.
=> increase timeout for test_issue_5724

doc/data/messages/r/return-in-init/bad.py, doc/data/messages/r/return-in-init/good.py, doc/data/messages/r/return-in-init/related.rst
=> Added message example for  return-in-init

tests/functional/u/unused/unused_variable.py
This adds coverage in case this block is removed without a replacement. (Marking as draft for now: I don't understand why it's needed, so I might try to replace it.)
https://github.com/PyCQA/pylint/blob/a93602d92edbf11885645866216d194324578acf/pylint/checkers/variables.py#L2362-L2366
=> Add test coverage for sibling except handlers

doc/data/messages/b/binary-op-exception/bad.py, doc/data/messages/b/binary-op-exception/good.py
=> Added binary-op-exception message example

ChangeLog, doc/whatsnew/2.14.rst, pylint/config/arguments_manager.py
<s>Blocked by #6227 and #6228. </s>
=> Update TODOs and add changelog entry about ``ArgumentsManager``

tests/primer/packages_to_lint_batch_one.json
See https://github.com/PyCQA/pylint/issues/6049#issuecomment-1086108440.
The other package got its last commit in 2015 and hasn't updated its `pylintrc`. This will become problematic and we should probably exclude it. Open to any other suggestions for now packages!
=> Add ``music21`` and remove ``graph-explorer`` from primer

pylint/lint/pylinter.py, pylint/utils/utils.py, tests/config/test_config.py, tests/unittest_reporting.py
This is the last use of `.config` in any of the checkers 🎉
=> Remove last use of ``config`` in ``PyLinter``

ChangeLog, doc/whatsnew/2.14.rst, pylint/config/arguments_manager.py, pylint/config/arguments_provider.py, pylint/lint/pylinter.py, tests/test_func.py, tests/test_functional.py, tests/test_regr.py
This restores access to `linter.config`. After this PR I'll post a status update in #5392.
=> Deprecate ``BaseChecker.config``

pylint/checkers/imports.py, pylint/checkers/typecheck.py, pylint/lint/pylinter.py
These options are used in multiple checkers. This fails our tests because when we only load the checker that "borrows" the option we don't load the actual option. Defining these options on `PyLinter` solves this as we then load them when we initialise `UnittestLinter`.
So it's mainly a change necessary for our unittests but would also allow to only load `PyLinter` and one of the "borrowing" checkers (if we ever support that) without breaking the borrowing checker.
=> Move general options to ``PyLinter`` from individual checkers 

pylint/lint/pylinter.py, pylint/message/message_definition.py, tests/config/functional/ini/pylintrc_with_message_control.result.json, tests/config/functional/setup_cfg/setup_cfg_with_message_control.result.json, tests/config/functional/toml/issue_3181/top_level_list_of_disable.result.json, tests/config/functional/toml/issue_4580/rich_types.result.json, tests/config/functional/toml/issue_4580/top_level_disable.result.json, tests/config/functional/toml/issue_4580/valid_data_for_basic.result.json, tests/config/functional/toml/issue_4580/valid_data_for_import.result.json, tests/config/functional/toml/rich_types.result.json, tests/config/functional/toml/toml_with_enable.result.json, tests/config/functional/toml/toml_with_message_control.result.json, tests/config/functional/toml/unknown_msgid/enable_unknown_msgid.result.json, tests/config/functional/toml/unknown_msgid/enable_unknown_msgid.toml
I tried to find when this was actually introduced and went back 8+ years into the code but couldn't find the specific commit that did this.
I don't think the current attribute is how we want this to be: why would it be 
```python
self.namespace.disable = [["raw-checker-failed"], ["bad-inline-option"], ["locally-disabled"]]
```
instead of
```python
self.namespace.disable = ["raw-checker-failed", "bad-inline-option", "locally-disabled"]
```
Also note, we don't actually use this config attribute 😅 The only time this gets accessed is during `--generate-rcfile` and `--generate-toml-config`. The other times we simply call `self.linter.disable()` or `enable()` and only update this attribute in …
=> Make the enable and disable config attributes an actual list

pylint/lint/pylinter.py, tests/config/functional/toml/unknown_msgid/enable_unknown_msgid.result.json, tests/config/test_deprecations.py, tests/test_import_graph.py
=> Do not use deprecated methods in ``PyLinter``

pylint/testutils/checker_test_case.py, pylint/testutils/configuration_test.py, pylint/testutils/functional/find_functional_tests.py, pylint/testutils/functional/lint_module_output_update.py, pylint/testutils/functional/test_file.py, pylint/testutils/get_test_info.py, pylint/testutils/lint_module_test.py, pylint/testutils/output_line.py, pylint/testutils/primer.py, pylint/testutils/pyreverse.py, pylint/testutils/reporter_for_tests.py, pylint/testutils/tokenize_str.py, pylint/testutils/unittest_linter.py, pylint/testutils/utils.py
=> Use ``python-typing-update`` on ``pylint/testutils`` directory

pylint/message/message_definition.py, pylint/message/message_definition_store.py, pylint/message/message_id_store.py, pylint/utils/docs.py, pylint/utils/file_state.py, pylint/utils/linterstats.py, pylint/utils/pragma_parser.py, pylint/utils/utils.py
=> Use ``python-typing-update`` on ``pylint/utils`` and ``message`` dirs

pylint/reporters/__init__.py, pylint/reporters/base_reporter.py, pylint/reporters/collecting_reporter.py, pylint/reporters/json_reporter.py, pylint/reporters/multi_reporter.py, pylint/reporters/reports_handler_mix_in.py, pylint/reporters/text.py, pylint/reporters/ureports/base_writer.py, pylint/reporters/ureports/nodes.py, pylint/reporters/ureports/text_writer.py
=> Use ``python-typing-update`` on ``pylint/reporters`` directory

pylint/config/argument.py, pylint/config/arguments_manager.py, pylint/config/arguments_provider.py, pylint/config/callback_actions.py, pylint/config/config_file_parser.py, pylint/config/config_initialization.py, pylint/config/deprecation_actions.py, pylint/config/find_default_config_files.py, pylint/config/help_formatter.py, pylint/config/option.py, pylint/config/option_manager_mixin.py, pylint/config/utils.py
=> Use ``python-typing-update`` on ``pylint/config`` directory

pylint/extensions/__init__.py, pylint/extensions/_check_docs_utils.py, pylint/extensions/bad_builtin.py, pylint/extensions/broad_try_clause.py, pylint/extensions/check_elif.py, pylint/extensions/code_style.py, pylint/extensions/comparetozero.py, pylint/extensions/comparison_placement.py, pylint/extensions/confusing_elif.py, pylint/extensions/consider_ternary_expression.py, pylint/extensions/docparams.py, pylint/extensions/docstyle.py, pylint/extensions/empty_comment.py, pylint/extensions/emptystring.py, pylint/extensions/for_any_all.py, pylint/extensions/mccabe.py, pylint/extensions/overlapping_exceptions.py, pylint/extensions/private_import.py, pylint/extensions/redefined_variable_type.py, pylint/extensions/set_membership.py, pylint/extensions/typing.py, pylint/extensions/while_used.py
=> Use ``python-typing-update`` on ``pylint/extensions`` directory

pylint/message/message.py, pylint/pyreverse/diadefslib.py, pylint/pyreverse/dot_printer.py, pylint/pyreverse/mermaidjs_printer.py, pylint/pyreverse/plantuml_printer.py, pylint/pyreverse/printer.py, pylint/pyreverse/printer_factory.py, pylint/pyreverse/utils.py, pylint/pyreverse/vcg_printer.py
Ref #4683.
@Pierre-Sassoulas @cdce8p Perhaps comment if you're going to review as not to duplicate work.
=> Use ``python-typing-update`` on ``pylint/pyreverse`` directory

pylint/checkers/base/__init__.py, pylint/checkers/base/basic_checker.py, pylint/checkers/base/name_checker/checker.py, pylint/checkers/classes/__init__.py, pylint/checkers/classes/class_checker.py, pylint/checkers/refactoring/__init__.py, pylint/checkers/refactoring/implicit_booleaness_checker.py, pylint/checkers/refactoring/recommendation_checker.py, pylint/checkers/refactoring/refactoring_checker.py
=> Use ``python-typing-update`` on ``pylint/checkers/...`` directories

ChangeLog, doc/whatsnew/2.14.rst, pylint/checkers/similar.py, pylint/checkers/variables.py, pylint/config/arguments_manager.py, pylint/config/arguments_provider.py, pylint/config/utils.py, pylint/lint/pylinter.py
Bit of a larger one.
@Pierre-Sassoulas  Let me know what you think of my hack of deprecating unwanted arguments. It's not pretty, but it might work and is more efficient than doing it with `inspect` or something like that.
=> Add ``_ArgumentsManager.set_option`` and deprecate old option setters

pylint/checkers/__init__.py, pylint/checkers/async.py, pylint/checkers/base_checker.py, pylint/checkers/deprecated.py, pylint/checkers/design_analysis.py, pylint/checkers/dunder_methods.py, pylint/checkers/ellipsis_checker.py, pylint/checkers/exceptions.py, pylint/checkers/format.py, pylint/checkers/imports.py, pylint/checkers/logging.py, pylint/checkers/misc.py, pylint/checkers/modified_iterating_checker.py, pylint/checkers/newstyle.py, pylint/checkers/non_ascii_names.py, pylint/checkers/raw_metrics.py, pylint/checkers/similar.py, pylint/checkers/spelling.py, pylint/checkers/stdlib.py, pylint/checkers/strings.py, pylint/checkers/threading_checker.py, pylint/checkers/typecheck.py, pylint/checkers/unicode.py, pylint/checkers/unsupported_version.py, pylint/checkers/utils.py, pylint/checkers/variables.py, pylint/message/message.py
=> Use ``python-typing-update`` on ``pylint/checkers`` directory

pylint/checkers/classes/special_methods_checker.py, pylint/checkers/similar.py, pylint/checkers/utils.py, pylint/config/arguments_manager.py, pylint/config/utils.py, pylint/constants.py, pylint/lint/pylinter.py, pylint/lint/run.py, pylint/reporters/base_reporter.py, pylint/reporters/text.py, pylint/testutils/checker_test_case.py, pylint/testutils/decorator.py, pylint/utils/utils.py
=> Add classifications to TODOs across codebase

doc/data/messages/r/redefined-slots-in-subclass/good.py
I found the "good" example for `redefined-slots-in-subclass` confusing since it added a new slot `"c"` instead of merely removing `"a"` which is the problem with the "bad" example. As per Python docs, subclasses "should only contain names of any _additional_ slots" https://docs.python.org/3/reference/datamodel.html#notes-on-using-slots
=> docs: make it clearer that only additional __slots__ should be specified

tests/pyreverse/conftest.py, tests/pyreverse/test_diadefs.py, tests/pyreverse/test_diagrams.py, tests/pyreverse/test_inspector.py, tests/pyreverse/test_main.py, tests/pyreverse/test_printer.py, tests/pyreverse/test_writer.py, tests/test_check_parallel.py, tests/test_func.py, tests/test_functional.py, tests/test_import_graph.py, tests/test_pylint_runners.py, tests/test_regr.py, tests/test_self.py, tests/test_similar.py, tests/testutils/test_lint_module_output_update.py, tests/testutils/test_output_line.py, tests/unittest_reporters_json.py, tests/unittest_reporting.py, tests/utils/unittest_ast_walker.py
Ref https://github.com/PyCQA/pylint/issues/4683.
=> Use ``python-typing-update`` on half of the ``tests`` directory

tests/checkers/base/unittest_name_preset.py, tests/checkers/unittest_deprecated.py, tests/checkers/unittest_non_ascii_name.py, tests/checkers/unittest_stdlib.py, tests/checkers/unittest_unicode/unittest_bad_chars.py, tests/checkers/unittest_unicode/unittest_functions.py, tests/checkers/unittest_unicode/unittest_invalid_encoding.py, tests/checkers/unittest_utils.py, tests/config/test_config.py, tests/config/test_find_default_config_files.py, tests/config/unittest_config.py, tests/lint/unittest_expand_modules.py, tests/lint/unittest_lint.py, tests/message/conftest.py, tests/message/unittest_message.py, tests/message/unittest_message_id_store.py, tests/primer/test_primer_external.py
=> Use ``python-typing-update`` on second half of the ``tests`` directory

examples/deprecation_checker.py, pylint/checkers/base/name_checker/naming_style.py, pylint/checkers/variables.py, pylint/lint/parallel.py, pylint/lint/pylinter.py, pylint/lint/report_functions.py, pylint/testutils/functional/test_file.py, pylint/testutils/output_line.py, pylint/utils/file_state.py, pylint/utils/pragma_parser.py, pylint/utils/utils.py, script/bump_changelog.py, script/fix_documentation.py, script/get_unused_message_id_category.py
Ref https://github.com/PyCQA/pylint/issues/4683.
=> Add some manual typing changes

ChangeLog, doc/whatsnew/2.14.rst, pylint/config/callback_actions.py, pylint/config/config_initialization.py, pylint/lint/pylinter.py, tests/config/functional/toml/issue_4746/loaded_plugin_does_not_exists.2.out, tests/config/functional/toml/unknown_msgid/enable_unknown_msgid.2.out, tests/config/functional/toml/unknown_msgid/enable_unknown_msgid.result.json, tests/config/functional/toml/unknown_msgid/enable_unknown_msgid.toml, tests/config/test_config.py, tests/functional/b/bad_option_value.txt, tests/functional/u/use/use_symbolic_message_instead.txt
The `try...expect` should have been placed differently. The test was wrong here as well, `"logging-format-interpolation"` should be in `disable` even after the previous message is unknown.
@cdce8p This was caused because in the `homeassistant` config there is a message that has been removed. This caused us to stop parsing the `disable` key when we reached it.
Ref #6293.
Closes #4324.
=> Fix parsing of unknown message IDs

pylint/config/arguments_manager.py, tests/config/test_argparse_config.py, tests/config/test_deprecations.py
For all of these upcoming PRs:
They will get 100% coverage when we switch `pyreverse` and when we finally test on `3.11` (I'm keeping an eye on this, we're waiting on Github..).
Should be able to get ``pylint/config`` to 100%.
=> Increase coverage for ``argparse``

pylint/testutils/utils.py, tests/test_self.py, tests/test_similar.py
Done to avoid duplication when bursting test_self.py during the migration to argparse.
=> Move utility function in testutil

pylint/checkers/classes/class_checker.py, tests/functional/u/useless/useless_super_delegation_py35.py, tests/functional/u/useless/useless_super_delegation_py35.txt
In the `useless-super-delegation` checker, check whether the return type annotation has been specialized in the derived class. If so, then the override is not useless and we should not issue the warning.
Closes #5822
=> Suppress ``useless-super-delegation`` if return type changed (#5822)

ChangeLog, doc/whatsnew/2.14.rst, pylint/config/__init__.py, pylint/config/arguments_provider.py, pylint/config/config_initialization.py, pylint/config/configuration_mixin.py, pylint/config/option.py, pylint/config/option_manager_mixin.py, pylint/config/option_parser.py, pylint/config/options_provider_mixin.py
🎉 
Bit premature because `pyreverse` is still using these, but we might as well deprecate them.
=> Deprecate all old classes from ``optparse``

pylint/checkers/imports.py, pylint/checkers/logging.py, pylint/checkers/strings.py, pylint/checkers/typecheck.py
As discussed in #6060, ``@check_messages`` has no effect in the following cases:
1. Decorating a method that does not start with ``visit_*`` or ``leave_*``: https://github.com/PyCQA/pylint/blob/ebf7bd6793dc484513455d0c47acd6a285a8d1a5/pylint/utils/ast_walker.py#L35-L46)
2. Passing in all messages this checker defines with ``@check_messages(*MSGS)``. This has the same effect as not decorating it at all:
https://github.com/PyCQA/pylint/blob/ebf7bd6793dc484513455d0c47acd6a285a8d1a5/pylint/utils/ast_walker.py#L20-L23
If none of the checker's messages is enabled, we won't load it anyway: …
=> Remove pointless ``check_messages`` decorators

pylint/testutils/lint_module_test.py, tests/testutils/test_functional_testutils.py
`--minimal-messages-config` is an awesome testing tool. But while working on #6362, I found it surprising that crashes were silenced. There were a couple moments where I thought I had a solution that would pass the tests, only to find later that fatal errors were being silenced. (Unbeknownst to me, I was generating a bunch of crash_reports.txt, but pytest was green.)
By design, this tool allows false negatives for unmentioned errors. But I think `astroid-error` and `fatal`, which are the two errors `pylint` emits when any internal failure occurs, should be included with the "minimal" config, because we don't really need to test the isolation of `astroid-error` and `fatal`. It's more …
=> Prevent false negatives for fatal errors with `--minimal-messages-config`

ChangeLog, doc/whatsnew/2.14.rst, pylint/checkers/misc.py, tests/functional/f/fixme.rc
| ✓   | :bug: Bug   |
**Before**: `# pylint: disable=fixme` didn't work on the last line of a module if pylint was invoked with `--enable=fixme`.
Followup to 0281388, identifying and fixing the other functional bug revealed there.
=> Fix a failure to respect inline disables for `fixme`

ChangeLog, doc/data/messages/s/super-without-brackets/bad.py, doc/data/messages/s/super-without-brackets/good.py, doc/whatsnew/2.14.rst, pylint/checkers/classes/class_checker.py, tests/functional/s/super/super_without_brackets.py, tests/functional/s/super/super_without_brackets.txt
=> Add ``super-without-brackets`` checker

ChangeLog, doc/how_tos/custom_checkers.rst, doc/whatsnew/2.14.rst, pylint/checkers/base_checker.py, pylint/checkers/mapreduce_checker.py, pylint/checkers/similar.py, pylint/lint/parallel.py, tests/checkers/unittest_similar.py, tests/test_check_parallel.py, tests/test_deprecation.py
Kinda high priority since `main` is broken due to two `typing` PRs apparently depending on each other but passing on their own.
`main` complains about `checker.get_map_data()` and `checker.reduce_map_data` in `parallel.py`. Instead of adding ignores there I think `mypy` is actually right and warns of a design flaw. There is no need to separate these `MixIns` (ideally we would deprecate the `MixIn` as there is little overhead of making `BaseChecker` a `MapReduceMixin` and just having the methods do nothing.
That's why I propose this solution.
=> Make ``BaseChecker`` a ``MapReduceMixin``

ChangeLog, doc/whatsnew/2.13.rst, pylint/checkers/variables.py, tests/functional/u/undefined/undefined_variable_typing.py, tests/functional/u/undefined/undefined_variable_typing.rc
One of the code paths for `undefined-variable` wasn't checking the ``--additional-builtins`` option.
Closes #6388
=> Prevent false positive `undefined-variable` for user-specified builtins given type annotations

pylint/checkers/base_checker.py, pylint/checkers/strings.py, pylint/lint/pylinter.py
Ref. #2287 
I changed `StringConstantChecker` already to fix coverage and show that we can still have multiple checker types in one checker.
=> Allow subclassing Checker types instead of using ``__implements__``

pylint/lint/pylinter.py
It is not as if this interface is doing much...
https://github.com/PyCQA/pylint/blob/42134810ad1dfd019af8d5102ce5facb59b49ba8/pylint/interfaces.py#L99-L104
The only thing this changes is that ``RawTokenCheckers`` which don't have `IAstroidChecker` in their ``__implements__`` will also get added. However, as long as they don't define any ``visit_`` methods nothing changes. In fact, I think this is likely to prevent bugs as now classes which do have ``visit_`` methods but forget to add the ``__implements__`` line will still get called correctly.
=> No longer care about ``interfaces.IAstroidChecker``

examples/custom_raw.py, pylint/checkers/format.py, pylint/checkers/misc.py, pylint/checkers/raw_metrics.py, pylint/checkers/refactoring/refactoring_checker.py, pylint/checkers/similar.py, pylint/checkers/spelling.py, pylint/checkers/unicode.py, pylint/extensions/check_elif.py, pylint/extensions/empty_comment.py, pylint/lint/pylinter.py, tests/benchmark/test_baseline_benchmarks.py, tests/test_check_parallel.py
=> Subclass ``BaseRawFileChecker`` and ``BaseTokenChecker``

doc/data/messages/m/missing-raises-doc/bad.py, doc/data/messages/m/missing-raises-doc/good.py
=> Added missing-raises-doc message example

doc/data/messages/m/missing-return-doc/bad.py, doc/data/messages/m/missing-return-doc/details.rst, doc/data/messages/m/missing-return-doc/good.py, doc/data/messages/m/missing-return-doc/pylintrc
=> Added missing-return-doc message example

doc/data/messages/m/missing-return-type-doc/bad.py, doc/data/messages/m/missing-return-type-doc/details.rst, doc/data/messages/m/missing-return-type-doc/good.py, doc/data/messages/m/missing-return-type-doc/pylintrc
=> Added missing-return-type-doc message example

ChangeLog, doc/whatsnew/2.14.rst, pylint/checkers/deprecated.py, pylint/checkers/imports.py, tests/functional/d/deprecated/deprecated_module_py3.txt, tests/functional/d/deprecated/deprecated_module_py310.txt, tests/functional/d/deprecated/deprecated_module_py33.txt, tests/functional/d/deprecated/deprecated_module_py36.txt, tests/functional/d/deprecated/deprecated_module_py39.txt, tests/functional/d/deprecated/deprecated_module_py39_earlier_pyversion.txt, tests/functional/d/deprecated/deprecated_module_py4.txt, tests/functional/d/deprecated/deprecated_module_redundant.txt, tests/functional/d/deprecated/deprecated_module_uninstalled.txt, tests/functional/d/deprecated/deprecated_relative_import/dot_relative_import.txt, tests/functional/d/deprecated/deprecated_relative_import/subpackage/dot_dot_relative_import.txt
I left the scrolly thing up there since the Issue has the Documentation tag, hope that's the right thing to do.
So I have improved the wording on W0402; it now says "Deprecated module \<module name\>" for consistency and style.
Closes #6169
=> Improve wording on W0402 message

ChangeLog, doc/release.md, pylint/checkers/variables.py
We cherry picked a fix without testing on all python versions in the CI.
Closes #6408
=> Fix 'object has no attribute additional_builtins'

ChangeLog, doc/whatsnew/2.13.rst, pylint/checkers/stdlib.py, tests/functional/u/unspecified_encoding_py38.py, tests/functional/u/unspecified_encoding_py38.txt
=> Fix crash when open is called with an integer mode

.github/workflows/checks.yaml, .github/workflows/primer-test.yaml, .github/workflows/tests.yaml
* `fetch-depth: 0` was added a while ago to support `setuptools_scm`. We have since moved away from it, thus the default of `1` is enough. It's no longer necessary to fetch the full repo history.
* `python-key` output for windows and pypy. Those became unnecessary when we merged the prepare and test jobs. Only the `python-key` fro `tests-linux` and `prepare-base` are still used in different jobs.
Astroid PR: https://github.com/PyCQA/astroid/pull/1524
=> Remove unused ci settings

pylint/reporters/ureports/nodes.py, pylint/testutils/output_line.py
Followup to #6445
Rename TypeVars to better match the new naming style.
=> Rename remaining TypeVars

pylint/config/utils.py, pylint/pyreverse/main.py
Using `default=[]` in Python 3.7 has the effect that values passed in for this parameter will be stored in the default list object. In subsequent runs (in the same process), the default value is wrongly prepopulated.
Python 3.8 and above handle this situation better, but as we have to support Python 3.7 this fix is necessary.
Ref: https://github.com/PyCQA/pylint/pull/6449#issuecomment-1107831297
This change should be covered e.g. by `tests/pyreverse/test_main.py::test_command_line_arguments_defaults[classes-expected_default1]`.
=> Fix handling of default value for extend action in Python 3.7

pylint/__pkginfo__.py, pylint/testutils/_run.py, tests/benchmark/test_baseline_benchmarks.py, tests/checkers/unittest_refactoring.py, tests/config/test_argparse_config.py, tests/config/test_config.py, tests/conftest.py, tests/lint/test_utils.py, tests/lint/unittest_lint.py, tests/message/unittest_message_id_store.py, tests/primer/test_primer_stdlib.py, tests/profile/test_profile_against_externals.py, tests/test_self.py, tests/test_similar.py
We don't want to use the project's  pylintrc during tests, because it means that a change in our config could break tests.
But we want to see if the changes to the default break tests. Refactor "required" to be able to add spelling checks in the codebase. It broke one (1) test :)
Tests to check that it's done correctly, is adding the following conf in pylintrc:
```ini
[MASTER]
init-hook=raise Exception("implicitly using the project's pylintrc")
```
Refactor prior to #6440
=> Use an explicitly set empty pylintrc inside tests

doc/data/messages/c/consider-using-f-string/bad.py, doc/data/messages/c/consider-using-f-string/details.rst, doc/data/messages/c/consider-using-f-string/good.py
Adds documentation examples for the `consider-using-f-string` checker. There didn't seem to be any examples in the `pylint-errors` repo that I could see, so I wrote a new one.
Ref #5953
=> Add documentation examples of consider-using-f-string

ChangeLog, doc/whatsnew/2.13.rst, pylint/checkers/format.py, tests/functional/s/superfluous_parens.py
The `superfluous-parens` checker was incorrectly reporting that parentheses after an `is not` expression were superfluous. The checker seemed to be assuming that any expression prefixed with `not` was a unary expression and not part of a larger expression that might need parentheses for correctness.
Closes #5930
=> Avoid reporting superfluous-parens after an ``is not`` operator

doc/test_messages_documentation.py
Follow-up to an issue where the documentation being in the wrong directory result in the documentation not displaying the content silently in #6404
=> Add an assertion to check that the documentation structure is correct

.pre-commit-config.yaml, pylint/testutils/pyreverse.py, tests/pyreverse/functional/class_diagrams/attributes/instance_attributes.mmd, tests/pyreverse/functional/class_diagrams/attributes/instance_attributes.py, tests/pyreverse/functional/class_diagrams/colorized_output/colorized.puml, tests/pyreverse/functional/class_diagrams/colorized_output/colorized.py, tests/pyreverse/functional/class_diagrams/colorized_output/colorized.rc, tests/pyreverse/functional/class_diagrams/inheritance/simple_inheritance.mmd, tests/pyreverse/functional/class_diagrams/inheritance/simple_inheritance.py, tests/pyreverse/test_pyreverse_functional.py
I would like to add a more flexible construct for functional tests of ``pyreverse``.
PR #6434 once again showed me that the current test suite is not ideal. 
In general I want to see how the new feature looks like in a final diagram, so I have to ask the contributor to include new, suitable code in `tests/data`. 
This in turn means she/he needs to update **all** generated output files for every possible format, which is cumbersome.
It also does not necessarily makes sense if a PR does not touch the ``Printer`` classes, as it would be enough to check the output with one format, and not for all. …
=> Functional tests for ``pyreverse``

doc/data/messages/a/assert-on-string-literal/details.rst, doc/data/messages/a/assert-on-string-literal/good.py, doc/data/messages/r/redundant-unittest-assert/details.rst, doc/data/messages/r/redundant-unittest-assert/good.py, doc/test_messages_documentation.py, pylint/testutils/lint_module_test.py, tests/testutils/test_functional_testutils.py
We missed the syntax error fixed in [98996bd](https://github.com/PyCQA/pylint/pull/6474/commits/98996bd25aa479e573c0d9dfbfe4283ab5e7373f) because we were disabling fatal errors when checking "good.py" in the message examples.
I also noticed `syntax-error` is slightly different from `astroid-error` so added it to the messages added in #6365
=> Check documentation examples for fatal errors

ChangeLog, doc/whatsnew/2.13.rst, pylint/checkers/variables.py, tests/functional/b/bugfix_local_scope_metaclass_1177.py
=> Fix false positive for ``unused-variable`` when specifying a metaclass via a call

ChangeLog, doc/whatsnew/2.13.rst, pylint/checkers/variables.py, tests/functional/u/undefined/undefined_loop_variable.py
=> Fix false positive for `undefined-loop-variable` when a loop else raises or returns

.pyenchant_pylint_custom_dict.txt, ChangeLog, doc/whatsnew/2.13.rst, pylint/checkers/variables.py, tests/functional/u/undefined/undefined_loop_variable.py
=> Fix false positive for `undefined-loop-variable` for lambda in first of two loops

pylint/checkers/base_checker.py, pylint/checkers/classes/special_methods_checker.py, pylint/checkers/typecheck.py, pylint/checkers/utils.py, pylint/checkers/variables.py, pylint/config/arguments_manager.py, pylint/config/arguments_provider.py, pylint/config/callback_actions.py, pylint/config/configuration_mixin.py, pylint/config/find_default_config_files.py, pylint/config/option.py, pylint/config/option_manager_mixin.py, pylint/config/option_parser.py, pylint/config/options_provider_mixin.py, pylint/constants.py, pylint/interfaces.py, pylint/lint/parallel.py, pylint/lint/pylinter.py, pylint/reporters/base_reporter.py, pylint/reporters/text.py, pylint/testutils/checker_test_case.py, pylint/testutils/unittest_linter.py, pylintrc, tests/pyreverse/test_diadefs.py, tests/test_regr.py, tests/test_self.py
Relates to #3512, following https://github.com/PyCQA/pylint/pull/6479#issuecomment-1114270073
=> Disable fixme for internal uses before we make it optional in #3512

ChangeLog, doc/whatsnew/2.14.rst, requirements_test_min.txt, setup.cfg, tests/functional/i/iterable_context.py
Closes #6372 (depends on https://github.com/PyCQA/astroid/pull/1535)
=> Add regression test for #6372

pylint/checkers/spelling.py, pylint/checkers/variables.py
=> Small refactor in spelling checker

ChangeLog, doc/whatsnew/2.14.rst, pylint/checkers/imports.py, pylint/checkers/spelling.py, pylint/config/argument.py, pylint/pyreverse/main.py
Refactor prior to #6493, permitted by the migration to argparse. It could permit to expanduser in various pylint configuration / options, so it's a feature.
=> Create a path type of argument that automatically expand user/var

pylint/checkers/spelling.py
Follow-up to #6491, before #6137
=> [spelling checker] Use a context manager to access the private dict

.github/workflows/tests.yaml, pylint/testutils/checker_test_case.py, pylint/testutils/lint_module_test.py, setup.cfg, tests/functional/b/bad_open_mode.rc, tests/functional/c/consider/consider_using_with_open.py, tests/functional/c/consider/consider_using_with_open.rc, tests/functional/c/consider/consider_using_with_open.txt, tests/functional/i/import_error.rc, tests/functional/r/regression_02/regression_5479.rc, tests/functional/s/sys_stream_regression_1004.rc, tests/functional/u/undefined/undefined_variable_typing.rc, tests/functional/u/unused/unused_typing_imports.rc
Blocked by https://github.com/PyCQA/astroid/pull/1520.
=> Run PyPy 3.8 and 3.9 in CI

CONTRIBUTORS.txt, ChangeLog, doc/whatsnew/2.14.rst, pylint/checkers/typecheck.py, tests/functional/e/enum_self_defined_member_5138.py, tests/functional/e/enum_self_defined_member_5138.txt
As per title, this PR adds an enhancement to the typechecker to find _simple_ self-defined members
This change **does not** support:
* conditionally defining members (it will assume all members are valid even if the validity is conditional)
* defining members via a function call in `__new__` or `__init__`
Closes #5138
=> Enum: Add support for self-defined members

pylint/checkers/utils.py, pylint/typing.py, tests/checkers/unittest_utils.py, tests/utils/unittest_ast_walker.py
Fix typing for `AstCallbackMethod` used in `check_messages` and `only_required_for_messages`. Generic type aliases need a subscript. Otherwise the TypeVar is interpreted as `Any`. Furthermore, the second parameter type also needs to be a TypeVar. That's because callback parameter are contravariant. I.e. if it's defined as `nodes.NodeNG`, we wouldn't be able to assign `nodes.Dict` to it.
Also renamed `T_Node` to `_NodeT` which better matches the new naming style. _`invalid-name` messages are disabled for pylint, which is why it didn't complain previously._ Will do a followup to rename the remaining TypeVars.
=> Fix `AstCallbackMethod` typing

doc/conf.py
=> Allow not yet published extensions links in ``linkcheck``

pylint/config/config_initialization.py, tests/config/test_config.py
Closes #6418.
We now print:
```console
❯ pylint -Q
usage: pylint [options]
************* Module Command line
Command line:1:0: E0015: Unrecognized option found: Q (unrecognized-option)
```
=> Exit gracefully for unrecognized command line options

tests/config/test_find_default_config_files.py
Disable `duplicate-code` warnings to unblock `main`.
More details: https://github.com/PyCQA/pylint/pull/6448#issuecomment-1118797114
=> Disable duplicate-code warnings

pylint/checkers/classes/class_checker.py, tests/functional/i/invalid/invalid_enum_extension.py
Fix unreleased issue with `invalid-enum-extension` and `IntFlag`.
```py
class CustomFlags(IntFlag):
SUPPORT_OPEN = 1
SUPPORT_CLOSE = 2
```
Unfortunately, that still leaves a corner case which would probably require astroid changes.
It shouldn't be too common though, so we might be fine waiting for a bug report on this one.
```py
from enum import IntFlag, Enum
class C(Enum):
def func(self):
...
a = func
class D(C):  # false-positive: invalid-enum-extension
C = 3
```
Closes #6295
=> Fix invalid-enum-extension with IntFlag

pylint/config/argument.py, tests/config/test_config.py
=> Fix behavior of empty `--confidence` option

tests/checkers/unittest_spelling.py
https://github.com/PyCQA/pylint/pull/1256
This was changed in the above PR. I don't really know why this wasn't picked up. This test will never run with `skipif(True)`...
=> Remove never run test

pylint/extensions/no_self_use.py, tests/functional/ext/no_self_use/no_self_use.txt
Change confidence from `no-self-use` from `HIGH` to `INFERENCE`.
Although we don't use `safe_infer`, we do some (best effort) checks to see if the warning should be emitted, e.g. check for abstract methods. Those aren't perfect though, so I think `INFERENCE` is a better fit than `HIGH`.
=> Change confidence for `no-self-use` to `INFERENCE`

ChangeLog, doc/whatsnew/2.13.rst, doc/whatsnew/2.14.rst, pylint/lint/caching.py, tests/lint/test_caching.py
Closes #6394 and the underlying problem. See for reference also [Fix saving of persistent data files on different drives](https://github.com/PyCQA/pylint/commit/01ffb60ff4094a0876517f826e54a805cfb50279) and https://github.com/DanielNoord/pylint/pull/135.
Basically drive letters are not handled very well when you concatenate two paths with different drives. We now normalise one of the paths to make sure this is handled better.
Tests show behaviour on both *nix and Windows.
=> Fix saving of persistent data files on different drives

doc/user_guide/ide-integration.rst
A link in the user guide claiming to point to VSCode IDE integration documentation was actually pointing to Visual Studio integration documentation. 
This corrects that documentation page.
- [New link to VSCode docs](https://code.visualstudio.com/docs/python/linting).
- [Old link to Visual Studio docs](https://docs.microsoft.com/en-us/visualstudio/python/linting-python-code)
- [Pylink docs page for IDE integrations](https://pylint.pycqa.org/en/latest/user_guide/ide-integration.html)
Closes #6533 
Does the change log need to be updated for a change this small? I did not do so.
=> Correct link to VSCode IDE integration documentation

ChangeLog, doc/whatsnew/2.14.rst, pylint/checkers/utils.py, tests/functional/g/generic_alias/generic_alias_postponed_evaluation_py37.py, tests/functional/g/generic_alias/generic_alias_postponed_evaluation_py37.txt, tests/functional/g/generic_alias/generic_alias_typing.py, tests/functional/g/generic_alias/generic_alias_typing.txt, tests/functional/p/postponed_evaluation_pep585.py, tests/functional/p/postponed_evaluation_pep585.txt
We previously checked if a class is explicitly mentioned in PEP 585 as being subscriptable. That frequently results in errors as some classes are only generic in type stubs. We could continue to update the set of subscriptable names, but that still wouldn't cover custom packages and is impractical.
With this PR, pylint will ignore all string annotations (explicit or via `from __future__ import annotations`). We might miss a few issues, however those aren't runtime errors and a type checker is likely used anyway witch would catch these.
Not emitting false-positives is more important than catching all errors here IMO.
Closes #4369
Closes #6523
=> Don't emit unsubscriptable-object for string annotations

pylint/lint/pylinter.py
Ref. https://github.com/PyCQA/pylint/issues/3312#issuecomment-1120203912
In preparation of moving `PyLinter` to `BaseChecker` instead of `BaseTokenChecker` we need to make the scope of its messages explicit. For `TokenChecker` it is `LINE` by default.
Even if my proposed move to a `_MessageStateHandler` isn't accepted, this PR might be worth considering as it doesn't hurt making this explicit.
=> Make the scope of ``PyLinter`` messages explicit

ChangeLog, doc/whatsnew/2.13.rst, doc/whatsnew/2.14.rst, pylint/checkers/utils.py, tests/functional/r/regression/regression_6531_crash_index_error.py
=> Add an exception for `IndexError` inside `uninferable_final_decorator`

pylint/pyreverse/diagrams.py
Next chunk for typing of `pyreverse`.
This one was a bit trickier. The class hierarchy in this module is not ideal - `PackageDiagram` is a subclass of `ClassDiagram` and reuses some of its methods, so being more specific than `DiagramEntity` was not possible in all cases.
This could probably be solved with a refactoring to have a hierarchy like this:
```mermaid
classDiagram
class Diagram {
<<ABC>>
}
class PackageDiagram 
class ClassDiagram 
Diagram <|-- PackageDiagram
Diagram <|-- ClassDiagram
```
But first I have to figure out which methods need to be provided by the base class and which are specific to the specific diagram class. …
=> Add typing to `pylint.pyreverse.diagrams.py`

pylint/lint/message_state_handler.py, pylint/lint/pylinter.py
Blocked by #6544.
Ref https://github.com/PyCQA/pylint/issues/3312.
=> Move all public methods to ``_MessageStateHandler``

pylint/lint/message_state_handler.py, pylint/lint/pylinter.py
Blocked by #6545.
Ref #3312.
Final refactor PR before moving on to actually fixing the issue.
=> Move ``process_tokens`` to ``_MessageStateHandler``

doc/data/messages/t/try-except-raise/bad.py, doc/data/messages/t/try-except-raise/details.rst, doc/data/messages/t/try-except-raise/good.py
=> Added try-except-raise message example

pylint/lint/parallel.py, pylint/lint/pylinter.py, pylint/utils/file_state.py, tests/lint/unittest_lint.py, tests/test_deprecation.py
Base change required for https://github.com/PyCQA/pylint/pull/6556.
Let's also make `modname` required. It's a bit strange that we create a `FileState` before even encountering a file in the `__init__`, but refactoring that is not part of my plan for now.
=> Pass ``msg_store`` and ``node`` to ``FileState``

ChangeLog, doc/whatsnew/2.13.rst, requirements_test_min.txt, setup.cfg, tests/functional/i/invalid/invalid_name/invalid_name_module_level.py
Closes #6539 (requires PyCQA/astroid#1547)
=> Add regression test for #6539

pylint/utils/file_state.py
Ref. https://github.com/PyCQA/pylint/pull/6556.
Main difference is that we now get the message definitions before calling/doing `_set_message_state_in_block`. It's a little cleaner and separates some functionality. `_collect_block_lines` becomes a bit pointless though.
=> Refactor ``_collect_block_lines``

pylint/utils/utils.py, tests/test_self.py
Ref. https://github.com/PyCQA/pylint/pull/6529
Fixes the issues with `ini`.
=> Make sure that --generate-rcfile generates a valid file

examples/pylintrc, examples/pyproject.toml, tbump.toml
=> Upgrade configuration example and add toml example

pylint/checkers/classes/special_methods_checker.py, pylint/checkers/utils.py, pylint/config/callback_actions.py
Ref. https://github.com/PyCQA/pylint/issues/5513.
=> Update all ``TODO: 2.14``

.pyenchant_pylint_custom_dict.txt, pylint/testutils/functional/test_file.py, pylint/testutils/lint_module_test.py
Fixes the spurious warnings identified in https://github.com/PyCQA/pylint/issues/6570.
Ideally we should deprecate the use of `FunctionalTestFile.options` as we should just parse options like we normally parse the options file. But it is really not a priority and I want to focus attention on any regressions in `2.14` rather than add new ones.
=> Use the standard config parser instead a new one in functional tests

doc/test_messages_documentation.py
Originally included in #6574 but it's going to make the whole test suite be launched for every change.
=> Better assert message for documentation tests

ChangeLog, doc/whatsnew/2.13.rst, pylint/checkers/refactoring/refactoring_checker.py, tests/functional/u/unnecessary/unnecessary_dict_index_lookup.py
=> Fix a crash in `unnecessary-dict-index-lookup` when subscripting an attribute

pylint/checkers/exceptions.py
Text was:
```
--overgeneral-exceptions <comma-separated class names>
Exceptions that will emit a warning when being caught. Defaults to "BaseException, Exception". (default: ('BaseException', 'Exception'))
```
Now:
```
--overgeneral-exceptions <comma-separated class names>
Exceptions that will emit a warning when being caught. (default: ('BaseException', 'Exception'))
```
=> [--long-help] Remove redundant default description in message

pylint/pyreverse/utils.py
This module already had some typing, added typing to the classes and functions that did not have any yet.
Running with `mypy --strict` four issues remain, which I can't wrap my head around why `mypy` complains about them:
```
pylint [typing-pyreverse-p3] % mypy --strict pylint/pyreverse/utils.py           
pylint/pyreverse/utils.py:72: error: Returning Any from function declared to return "bool"  [no-any-return]
pylint/pyreverse/utils.py:77: error: Returning Any from function declared to return "bool"  [no-any-return]
pylint/pyreverse/utils.py:213: error: Returning Any from function declared to return "str"  [no-any-return] …
```
=> Finish typing of `pylint.pyreverse.utils`

doc/data/messages/y/yield-outside-function/bad.py, doc/data/messages/y/yield-outside-function/good.py
Add `yield-outside-function` documentation examples based on the `pyling-errors` project.
Partially addresses https://github.com/PyCQA/pylint/issues/5953
=> Add `yield-outside-function` documentation examples

doc/data/messages/r/raise-missing-from/bad.py, doc/data/messages/r/raise-missing-from/good.py, doc/data/messages/r/raise-missing-from/related.rst, pylint/checkers/exceptions.py, tests/functional/r/raise_missing_from.py, tests/functional/r/raise_missing_from.txt
Co-authored-by: @cool-RR <ram@rachum.com>
Refs #5953 
Closes #3707
=> [raise-missing-from] Clearer message and example in the documentation

doc/development_guide/testing.rst
Update the instructions in /doc/development_guide/testing.rst for telling how to initialize the testing environment. These instructions now (roughly) match the instructions in README.rst.
Closes #6570.
=> Replace `pip install -e` with `pip install -r requirements_test_min.txt`

doc/data/messages/u/using-final-decorator-in-unsupported-version/bad.py, doc/data/messages/u/using-final-decorator-in-unsupported-version/details.rst, doc/data/messages/u/using-final-decorator-in-unsupported-version/good.py, doc/data/messages/u/using-final-decorator-in-unsupported-version/related.rst
=> Add documentation for `using-final-decorator-in-unsupported-version`

ChangeLog, doc/whatsnew/2.14.rst, pylint/utils/ast_walker.py
Write the exception message to stderr, otherwise stdout would produce invalid formatted outputs (e.g. `--output-format=json`).
Closes #6597
=> Write the exception message to stderr in `ASTWalker.walk`

ChangeLog, pylint/checkers/refactoring/refactoring_checker.py, tests/functional/u/use/use_a_generator.py, tests/functional/u/use/use_a_generator.txt
Based on https://peps.python.org/pep-0289/ also `sum()`, `max()`, `min()` should avoid using
lists. Using generator, the memory is not allocated for all items but the items are processed lazily.
=> Raise use_a_generator for `sum()`, `max()`, `min()`

ChangeLog, doc/whatsnew/2.13.rst, pylint/checkers/refactoring/refactoring_checker.py, tests/functional/u/unnecessary/unnecessary_list_index_lookup.py
=> Fix a crash in `unnecessary-list-index-lookup` when incorrectly using `enumerate()`

ChangeLog, doc/whatsnew/2.13.rst, pylint/checkers/variables.py, tests/functional/u/undefined/undefined_loop_variable.py
=> Fix false positive for `undefined-loop-variable` with `enumerate()`

ChangeLog, doc/whatsnew/2.13.rst
Followup to #6603. Remove release note since this was actually an unreleased issue in 2.14.
=> Remove release note for unreleased crash fix

CONTRIBUTORS.txt, ChangeLog, doc/whatsnew/2.13.rst, pylint/__pkginfo__.py, pylint/checkers/refactoring/refactoring_checker.py, pylint/checkers/utils.py, pylint/checkers/variables.py, pylint/lint/expand_modules.py, pylint/lint/pylinter.py, requirements_test_min.txt, setup.cfg, tbump.toml, tests/functional/i/invalid/invalid_name/invalid_name_module_level.py, tests/functional/n/no/no_name_in_module.py, tests/functional/r/regression/regression_6531_crash_index_error.py, tests/functional/u/undefined/undefined_loop_variable.py, tests/functional/u/unnecessary/unnecessary_dict_index_lookup.py, tests/lint/unittest_lint.py, tests/regrtest_data/directory/ignored_subdirectory/failing.py, tests/test_self.py
=> Release branch 2.13.9

ChangeLog, doc/whatsnew/2.14.rst, pylint/checkers/typecheck.py, tests/functional/g/generated_members.py, tests/functional/g/generated_members.txt
Don't emit ``no-member`` inside type annotations with ``from __future__ import annotations``.
With PEP 563, annotations are stored as strings and thus not executed. This can cause false-positives if attributes are used which don't exist in the version used to run pylint.
```py
from __future__ import annotations
import ast
import sys
if sys.version_info >= (3, 10):
def func(node: ast.Match) -> None:  # no-member
...
```
If Python 3.8 is used, pylint would currently emit a `no-member` error for `ast.Match` (which was added in `3.10`).
By excluding type annotations with `from __future__ import annotations`, the behavior will be similar to normal string annotations (which don't emit an error).
```py
def func(node: "ast.Match") -> None:
...
```
Closes #6594
=> Fix `no-member` in type annotations with future import

ChangeLog, doc/whatsnew/2.14.rst, pylint/checkers/utils.py
Update documentation and remove `utils.subscriptable_with_postponed_evaluation_enabled` added in #6536.
The helper function is just one more function call and with that specific name can't really be used anywhere else. Much better to just call the two functions directly. Which is already done elsewhere anyway. The helper has only been included in `2.14.0b1`, so I think it's ok to remove without deprecation.
```py
if is_postponed_evaluation_enabled(node) and is_node_in_type_annotation_context(node):
...
```
=> Remove `utils.subscriptable_with_postponed_evaluation_enabled`

pylint/pyreverse/inspector.py, pylint/pyreverse/writer.py
-->
Add remaining typing to `inspector.py`.
This was the last untyped module.
After this change I can take a look at the refactoring TODOs we found.
Especially the parts of `inspector.py` that deal with interfaces and implementation links can be removed in my opinion, as their behaviour is based on the `__implements__` attribute which is not a standard Python feature and the corresponding PEP 245 is rejected. Plus, `pylint`'s codebase itself does not use it any more.
Those are also the only places in this module where I used `Any`.
=> Add typing to `pylint.pyreverse.inspector`

pylint/constants.py, pylint/lint/base_options.py, pylint/pyreverse/inspector.py, pylint/pyreverse/main.py
Follow up to @DanielNoord's comment:
https://github.com/PyCQA/pylint/pull/6614#discussion_r872992691
The same default value for `ignore` / `black_list` was used in three different places in the code base, so we can extract a constant for it.
=> Create constant for default ignore list

ChangeLog, doc/whatsnew/2.14.rst, pylint/checkers/classes/class_checker.py, tests/functional/u/useless/useless_super_delegation.py, tests/functional/u/useless/useless_super_delegation.txt
If a class overrides `__eq__` then we should allow trivial overrides of `__hash__` without issuing a `useless-super-delegation` warning, because the override can be significant.
As explained in the Python docs:
> A class that overrides `__eq__` and does not define `__hash__` will have its `__hash__()` implicitly set to `None`. When the
> `__hash__` method of a class is None, instances of the class will raise an appropriate `TypeError` when a program attempts to retrieve their hash value, and will also be correctly identified as unhashable when checking `isinstance(obj, collections.abc.Hashable)`.
Closes #3934
=> Suppress useless-super-delegation on __hash__ in classes with __eq__

doc/data/messages/l/logging-not-lazy/bad.py, doc/data/messages/l/logging-not-lazy/details.rst, doc/data/messages/l/logging-not-lazy/good.py, doc/data/messages/l/logging-not-lazy/related.rst
=> Added logging-not-lazy message example

doc/Makefile, doc/development_guide/contribute.rst, doc/exts/pylint_messages.py
I did a lot of doc modification recently for #6589 and the makefile installing dependency each time is taking a lot of time unnecessarily. I'm also thinking about lazy generating message files etc.
=> Faster makefile for doc development offline

doc/conf.py
Realized during #6628. Probably something that will reduce the number of patch version in readthedoc.
=> [doc] Fix the short version in the sphinx configuration

doc/conf.py, doc/data/messages/u/useless-import-alias/related.rst, doc/user_guide/messages/message_control.rst
Apparently the redirect in #6628 is not perfect.
=> [doc] Fix the link to block disable in useless-import-alias related

ChangeLog, doc/whatsnew/2.14.rst, pylint/checkers/utils.py, tests/functional/u/unexpected_special_method_signature.py, tests/functional/u/unexpected_special_method_signature.txt
Fix ``unexpected-special-method-signature`` false positive for ``__init_subclass__`` methods with one or more arguments.
The method can accept arguments.
Closes #6644
=> Fix ``unexpected-special-method-signature`` false positive 

pylint/__init__.py, pylint/config/_pylint_config/__init__.py, pylint/config/_pylint_config/generate_command.py, pylint/config/_pylint_config/help_message.py, pylint/config/_pylint_config/main.py, pylint/config/_pylint_config/setup.py, pylint/config/_pylint_config/utils.py, pylint/config/arguments_manager.py, pylint/lint/run.py, setup.cfg, tests/config/pylint_config/test_pylint_config_generate.py, tests/config/pylint_config/test_pylint_config_help.py, tests/config/pylint_config/test_run_pylint_config.py
Ref https://github.com/PyCQA/pylint/pull/6578 and https://github.com/PyCQA/pylint/issues/971.
This adds a number of new commands:
- `pylint-config`, Shows help message for the new command
- `pylint-config -h/--help`, idem.
- `pylint-config generate`, Shows help message for the subparser
- `pylint-config generate -h/--help`, idem.
- `pylint-config generate --interactive`, Starts interactive process of generating a configuration file
Everything is behind a `UserWarning` that indicates that all of this is experimental to give us some freedom to play around with this.
The way it works is that when `pylint-config` is used on the CLI a …
=> Add ``pylint-config`` command

README.rst, doc/conf.py, doc/development_guide/contribute.rst, doc/development_guide/index.rst, doc/development_guide/tests/index.rst, doc/development_guide/tests/install.rst, doc/development_guide/tests/launching_test.rst, doc/development_guide/tests/writting_test.rst, doc/index.rst, doc/user_guide/badge.rst, doc/user_guide/index.rst
This duplicate only what is strictly necessary in the readme.rst and factorize the remainder and reorganize the testing documentation that was duplicated and contradictory between readme/doc.
=> Remove duplicate of the documentation in the README

pylint/config/_pylint_config/generate_command.py, pylint/config/_pylint_config/utils.py, tests/config/pylint_config/test_pylint_config_generate.py
Blocked by https://github.com/PyCQA/pylint/pull/6661.
Adds a sequence of specifying an output file to the ``generate`` command. Also handles overwriting with a default to not overwrite.
=> Allow specifying an output file when generating a configuration file

doc/conf.py, doc/data/messages/n/no-member/bad.py, doc/data/messages/n/no-member/details.rst, doc/data/messages/n/no-member/good.py, doc/user_guide/index.rst
When the original documentation was created the full list of message did not exists, so this piece of documentation was always a little out of place.
=> [doc] Move the c-extensions documentation to no-member doc

doc/conf.py, doc/data/messages/i/invalid-name/bad.py, doc/data/messages/i/invalid-name/details.rst, doc/data/messages/i/invalid-name/good.py, doc/user_guide/options.rst
Same reasoning than for #6659. This is the most searched message in the documentation too, by far with double the hit of other messages, see https://github.com/PyCQA/pylint/issues/5953#issuecomment-1134172901.
=> [doc] Move the naming-style documentation to invalid-name doc

doc/data/messages/c/consider-using-dict-items/bad.py, doc/data/messages/c/consider-using-dict-items/good.py
=> Add documentation examples for `consider-using-dict-items`.

README.rst, doc/conf.py, doc/whatsnew/2.9.rst
=> [doc] Fix broken links following toc reorganization

doc/data/messages/l/line-too-long/bad.py, doc/data/messages/l/line-too-long/good.py
=> Add documentation examples for `line-too-long`.

ChangeLog, doc/whatsnew/2.14.rst, pylint/checkers/classes/class_checker.py, tests/functional/u/unused/unused_private_member.py, tests/functional/u/unused/unused_private_member.txt
Reproduced the crash in the original checker: 44eab786bb794196b36b16cb8d2b36d5fd098a49
Closes #6709
=> Fix a crash in `unused-private-member` with chained private attributes

.github/workflows/primer_run_main.yaml, .github/workflows/primer_run_pr.yaml, pylint/testutils/primer.py, tests/primer/packages_to_prime.json, tests/primer/primer_tool.py
Ref. https://github.com/PyCQA/pylint/issues/5364.
This is in preparation of a full fledged primer which can warn us about false positives and negatives.
This adds:
1) A workflow triggered on every push to `main` that caches and downloads all packages in `tests/primer/packages_to_prime.json`.
2) A workflow triggered on all relevant PRs that searches for the last successful run on `main` and gets its cache from there.
The cache is managed by what I call the `commitstring`, which is just a concatenation of all commits that the packages to prime are on.
Because this needs to be merged into `main` to work you can see a working example here:
Job on `main`: …
=> Cache and store primer packages via the default branch

ChangeLog, doc/whatsnew/2.14.rst, pylint/pyreverse/utils.py
Ref #6582 
Closes the first bullet point from the list:
`ASTWalker` and `LocalsVisitor` were apparently moved from `astroid.utils` to `pylint.pyreverse.utils` some years ago.
Maybe originally there were also other subclasses of `ASTWalker`, but at least in `pyreverse` that is not the case.
Thus we can remove `ASTWalker` and some of the unused code in there and directly put the remaining stuff in `LocalsVisitor`.
Some remarks, as the diff is a bit hard to read imo:
* `handler` was always `self` -> removed `handler` and replaced references with `self`
* `walk` and `leave` were never called -> …
=> Remove unnecessary base class and dead code in `pylint.pyreverse.utils`

.pre-commit-config.yaml, ChangeLog, doc/whatsnew/2.14.rst, pylint/pyreverse/mermaidjs_printer.py, tests/pyreverse/data/classes_No_Name.html, tests/pyreverse/data/classes_No_Name.mmd, tests/pyreverse/functional/class_diagrams/annotations/method_annotation.mmd, tests/pyreverse/functional/class_diagrams/annotations/method_annotation.py
The ` ->` before the return type annotation is incorrect, and the return type is not shown in the final diagram.
Closes #6467
=> Fix return type annotations in MermaidJS diagrams.

.github/workflows/primer_run_main.yaml, .github/workflows/primer_run_pr.yaml, tests/primer/packages_to_prime.json, tests/primer/primer_tool.py
Ref. https://github.com/PyCQA/pylint/issues/5364.
Next step for the primer.
Test run on local `main`:
https://github.com/DanielNoord/pylint/actions/runs/2396609324
Test run on a PR:
https://github.com/DanielNoord/pylint/actions/runs/2396610764
Basically, the PR run will now result in three files: the PR number, the output of the primer on the PR and the output of the `main` run against which the PR is being compared. 
This can be downloaded by a last and final step which takes all these files. Compares them and then comments on the relevant PR.
=> Run and upload primer over packages

tests/primer/primer_tool.py
`pylint_args` reads `paths_to_lint`, which reads `directories`, so adding `directories` here is both duplicative and error-prone (because it doesn't account for the path to the cloned directory): we were getting fatal errors like "unable to import module src/blackd")
In a follow-up PR I'll probably add `--fail-on=fatal`.
=> Primer tool: remove duplicated directory paths

.github/workflows/primer_run_pr.yaml, tests/primer/primer_tool.py
Ref. https://github.com/PyCQA/pylint/pull/6723#issuecomment-1140323738
=> Small refactors to primer

.github/workflows/primer_run_pr.yaml
Based on tips by original `mypy` primer author over at https://github.com/hauntsaninja/mypy_primer/issues/29.
I considered adding `pre-commit` as a non-triggering actor like they do, but that doesn't work with concurrency. The `pre-commit` commit would trigger the concurrency so then no run would succeed.
=> Add concurrency to primer

doc/data/messages/s/simplifiable-if-expression/bad.py, doc/data/messages/s/simplifiable-if-expression/details.rst, doc/data/messages/s/simplifiable-if-expression/good.py, doc/data/messages/s/simplifiable-if-expression/related.rst, doc/data/messages/s/simplifiable-if-statement/bad.py, doc/data/messages/s/simplifiable-if-statement/details.rst, doc/data/messages/s/simplifiable-if-statement/good.py, pylint/checkers/refactoring/refactoring_checker.py, tests/functional/s/simplifiable/simplifiable_if_expression.py, tests/functional/s/simplifiable/simplifiable_if_expression.txt
I realized during implementation that simplifiable if expression became worst and that I disagree with https://github.com/PyCQA/pylint/issues/1984 basically. If there are two values but one if the opposite of the other we can pretty much simplify the if expression. It look like the example from the issue come directly from [this stackoverflow question](https://stackoverflow.com/questions/49546992/) but the top answer make a compelling point that this is simplifiable.
Refs #5953 
Closes #5882
=> Add a documentation for simplifiable if expression

tests/primer/primer_tool.py
Ref. https://github.com/PyCQA/pylint/issues/5364#issuecomment-1140521653
Example message after this change:
--------
🤖 **Effect of this PR on checked open source code:** 🤖
**Effect on [astroid](https://github.com/PyCQA/astroid):**
The following **fatal messages** are now emitted: 💣💥
<details>
1) fatal:
*Fatal error while checking 'tests/.pylint_primer_tests/PyCQA/astroid/astroid/interpreter/objectmodel.py'. Please open an issue in our bug tracker so we address this. There is a pre-filled template that you can use in '/Users/daniel/Library/Caches/pylint/pylint-crash-2022-05-29-17.txt'.*
**Please check your changes on the following file**: …
=> Put fatal messages at the top in the primer comment

tests/primer/packages_to_lint_batch_one.json, tests/primer/packages_to_lint_batch_two.json, tests/primer/packages_to_prime.json
I'll remove the empty file when we can remove the old primer as removing now requires additional refactors.
=> Move more packages to the new primer

doc/whatsnew/2/2.14/summary.rst, pylint/checkers/imports.py, pylint/checkers/utils.py, pylint/lint/pylinter.py
Not 100% bullet-proof, but we're making an effort not to fail primer jobs if the failures stem from astroid and just warn about them instead. There could be little places all over the codebase that import little helpers, but these are the big ones.
Ref https://github.com/PyCQA/pylint/pull/6746#issuecomment-1141266169
=> Reraise failures in astroid as `AstroidError`

.github/workflows/primer_run_main.yaml, .github/workflows/primer_run_pr.yaml, tests/primer/primer_tool.py, tests/profile/test_profile_against_externals.py
The old primer did one thing very well -- it failed CI jobs when encountering `fatal` errors during the linting of open source packages, whether caused in new pylint or astroid PRs, or when adding new packages to the primer, or when third-party packages pushed new changes.
The new primer needs some analogous functionality -- something beyond the message differ. If some fatal errors "sneak in" (we merge a PR without noticing the change, or we believe it to be related to a different PR, or incompatible PRs are merged, or we add a package, or third-party maintainers publish new commits), we don't want `n` fatal errors on main to silently match `n` fatal errors on a PR and for the comment-bot to …
=> Fail "new primer" runs on fatal errors, like "old primer"

.github/workflows/primer_comment.yaml
Since Comment workflows fail silently expect for PR creators we can easily miss whenever there are issues in that pipeline.
This makes it so that I will be tagged in any failing workflows which is quite handy.
See [this](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#adding-a-job-summary) and [this](https://github.blog/2022-05-09-supercharging-github-actions-with-job-summaries/)
=> Warn users who want to be warned about failing comment workflows

pylint/checkers/base/basic_checker.py
=> Add typing to ``basic_checker``

pylint/checkers/base/basic_checker.py
Follow-up to #6769, probably a small performance increase (?), but I find this easier to understand.
=> [refactor] Use a generator for '_has_variadic_argument'

.github/workflows/primer_run_main.yaml
See https://github.com/PyCQA/pylint/pull/6769#issuecomment-1142052024
=> Run ``Primer / Main`` on all pushes to main

tests/primer/primer_tool.py
Second time I noticed broken URLs with ".git" in them, so better to fix at the source! Ref #6733
=> Fix broken links in primer comments by stripping ".git"

.github/workflows/primer_comment.yaml, .github/workflows/primer_run_main.yaml, .github/workflows/primer_run_pr.yaml
I think it makes most sense to run the primer on the last and least supported versions. Running it on any other doesn't really add much I think.
Besides, running on `3.7` has the additional benefit of testing the old parser (<3.8).
=> Run primer on ``3.7`` and ``3.10``

doc/whatsnew/2/2.14/full.rst, pylint/extensions/_check_docs_utils.py, tests/extensions/test_check_docs_utils.py
Fixes issue discovered by new primer!
=> Fix a crash in the ``docparams`` extension when raising the result of a function

.github/workflows/primer_comment.yaml, tests/primer/primer_tool.py
This is something I always miss in the comments from `coveralls`. Allows you to make sure you're looking at the latest comment and are not still waiting on some workflow to finish.
=> Add commit hash in the primer comment

.github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTORS.txt, doc/development_guide/contributor_guide/contribute.rst, doc/whatsnew/2/2.14/full.rst, doc/whatsnew/2/2.15/index.rst, doc/whatsnew/2/index.rst, examples/pylintrc, examples/pyproject.toml, pylint/__pkginfo__.py, script/.contributors_aliases.json, script/bump_changelog.py, tbump.toml
The time has come to close #5513
=> Bump pylint to 2.14.0, update changelog

tests/functional/r/regression/regression_4680.py, tests/functional/r/regression/regression_4680.txt
On Solaris (both Oracle and OpenIndiana), `import pkg` actually find something because pkg is our OS package manager. This results in pylint warnings in **regression_4680** test being very different. Would it be possible to rename it to something non clashing? It seems that foo package doesn't exist, but if it does, I am happy to change it to anything else ;).
=> Rename clashing import name in one test case

doc/whatsnew/2/2.14/full.rst, pylint/config/utils.py, tests/config/test_find_default_config_files.py
Closes #6810.
This might need to be updated when we add new options, but a new option that clashes with the current length of these preprocessable options will error out anyway. So it's immediately clear that something needs to be updated.
=> Fix the use of abbreviations for preprocessable options on the CLI

pylint/config/utils.py, pylint/constants.py, pylint/exceptions.py, pylint/message/_deleted_message_ids.py, pylint/message/message_id_store.py, script/get_unused_message_id_category.py, tests/config/functional/ini/pylintrc_with_deleted_message.2.out, tests/config/functional/ini/pylintrc_with_deleted_message.ini, tests/config/functional/ini/pylintrc_with_deleted_message.result.json, tests/functional/b/bad_option_value.py, tests/functional/b/bad_option_value.txt, tests/message/test_no_removed_msgid_or_symbol_used.py
Refactor prior to #6824 in order to be able to give a reason for why the message was deleted, and better overall organization as deleted messages are not public and specific to ``pylint.messages``.
=> [deleted messages] Refactor the constant to be able to give a reason

pylint/config/utils.py
=> [spellcheck] Fix the spellcheck hopefully for all environnements

doc/whatsnew/2/2.15/index.rst, pylint/checkers/modified_iterating_checker.py, pylint/checkers/utils.py, pylint/checkers/variables.py, tests/functional/m/modified_iterating.py, tests/functional/m/modified_iterating.txt
Closes #6648
Solves an additional false negative: the check wasn't emitted when iterating literals.
=> Emit `modified-iterating-{list|dict|set}` when iterating literals or using `del`

.pyenchant_pylint_custom_dict.txt, pylint/config/arguments_manager.py, pylint/config/config_initialization.py, pylint/lint/pylinter.py, pylint/lint/utils.py, pylint/typing.py, tests/config/test_per_directory_config.py
This is a first step towards `per-directory-config` as I think they make the most sense:
1) Create a basic `Namespace`
2) Iterate over all `files_or_modules` and see if we can create additional `Namespaces` for subdirectories
3) Look up the correct `Namespace` before checking a file
This is a basic implementation of 3 which allows storing the information that should be gathered in step 2.
=> Store namespaces respective to directories

pylint/lint/message_state_handler.py, pylint/lint/pylinter.py, tests/config/functional/ini/pylintrc_with_deleted_message.2.out, tests/config/functional/ini/pylintrc_with_missing_comma.2.out, tests/config/functional/setup_cfg/do_not_read_other_tools_configuration/setup.2.out, tests/config/functional/toml/issue_3122/toml_with_missing_comma.2.out, tests/config/functional/toml/unknown_msgid/enable_unknown_msgid.2.out, tests/config/test_config.py, tests/functional/b/bad_option_value.py, tests/functional/b/bad_option_value.txt, tests/functional/b/bad_option_value_disable.txt, tests/functional/u/use/use_symbolic_message_instead.txt
All the refactoring and betterment done during #6824 so we only have the new message in the final MR. Follow-up to https://github.com/PyCQA/pylint/pull/6826
=> [bad-option-value] Use the right confidence and refactor message

pylint/config/callback_actions.py, pylint/config/config_initialization.py, pylint/lint/message_state_handler.py, pylint/lint/pylinter.py
=> Refactor bad option value stash in prevision of handling multiple type of messages

doc/whatsnew/2/2.14/full.rst, pylint/checkers/typecheck.py, tests/functional/e/enum_self_defined_member_6805.py, tests/functional/e/enum_self_defined_member_6805.txt
Fixes #6805 by:
- only checking for Enum attributes when metaclass is an Enum metaclass
- coping with a name not being returned in `__new__`
=> typecheck/Enum: fix crash in Enum attributes check

doc/data/messages/c/compare-to-empty-string/bad.py, doc/data/messages/c/compare-to-empty-string/details.rst, doc/data/messages/c/compare-to-empty-string/pylintrc
=> Add `compare-to-empty-string` example

doc/test_messages_documentation.py
Refactor prior to https://github.com/PyCQA/pylint/pull/6824
=> Print the launched command in doc examples tests

pylint/pyreverse/inspector.py
Reduces 26 instances of this `DeprecationWarning` in the suite to 1. (That 1 will need a substantive fix.)
Refs #6713
=> Better target DeprecationWarnings in pyreverse

doc/exts/pylint_extensions.py, doc/exts/pylint_features.py, doc/exts/pylint_options.py, doc/user_guide/checkers/extensions.rst, doc/user_guide/checkers/features.rst, doc/user_guide/configuration/all-options.rst, pylint/checkers/base_checker.py, pylint/utils/docs.py
@Pierre-Sassoulas Potentially do this before https://github.com/PyCQA/pylint/pull/6589. I tried to improve the formatting of the options page a little bit. After this we can do one more PR that removes the `pylint features` page all together I think.
=> Remove redundant options documentation and improve formatting

doc/whatsnew/2/2.14/full.rst, pylint/checkers/utils.py, tests/functional/u/unused/unused_import.py, tests/functional/u/unused/unused_import.txt
The check for `typing.TYPE_CHECKING` was not robust against importing `typing` as `t`. Nor against importing `keyboarding` as `typing`. This could lead to false positives for `unused-import`.
Follow-up: we have the following plethora of utils. Would be good to standardize and deprecate some for 2.15 (not a backport task, though):
- is_typing_guard()
- is_node_in_typing_guarded_import_block()
- in_type_checking_block()  <-- **this one** edited in this PR
Closes #3846
=> Prevent `unused-import` for `if t.TYPE_CHECKING`

tests/primer/primer_tool.py
Refs https://github.com/PyCQA/pylint/actions/runs/2465775611
=> [primer] Truncate comments that are too long for github

tests/primer/primer_tool.py
~Move everything into the new primer and increase the timeout on the `main` job. (3.7 is about 2x as slow as 3.10)
Follow up to #6761 and #6753.~
Never mind, we will have to discuss that separately.
=> [primer] stop overwriting `--rcfile`

pylint/checkers/variables.py
This became useful while trying to make progress on #6677, but even if that PR is abandoned, the performance improvement of avoiding the nested function is probably worthwhile.
=> Factor out `_defines_name_raises_or_returns_recursive`

doc/whatsnew/2/2.14/full.rst, pylint/checkers/variables.py, tests/functional/u/used/used_before_assignment_except_handler_for_try_with_return.py, tests/functional/u/used/used_before_assignment_except_handler_for_try_with_return.txt
Noticed this false positive while working on #6677.
=> Avoid `used-before-assignment` in except handlers employing type annotations

doc/whatsnew/2/2.14/full.rst, pylint/checkers/variables.py, tests/functional/u/undefined/undefined_loop_variable.py, tests/functional/u/undefined/undefined_loop_variable.txt
See https://github.com/PyCQA/pylint/pull/6923#discussion_r895134495 for report.
This call has been here since the initial commit, but nothing fails when I remove it. Let's see what the primer says.
=> Avoid raising `undefined-loop-variable` twice on same line

doc/whatsnew/2/2.15/index.rst, pylint/testutils/output_line.py, tests/testutils/test_output_line.py
Previously if an exception was raised during parsing we re-raised an explanation.
Most of the time I just want to regenerate the output from the current pylint's
output. It's what the exception suggested but it's impossible to do as the error
is also raised when updating, so you had to empty the file.
=> Makes functional tests auto-update works even if the current output is wrong

pylint/config/callback_actions.py, pylint/exceptions.py, pylint/lint/message_state_handler.py, pylint/message/_deleted_message_ids.py, pylint/message/message_id_store.py, tests/functional/b/bad_option_value.py, tests/functional/b/bad_option_value.txt
See https://github.com/PyCQA/pylint/issues/6931#issuecomment-1153226753
**Before**
Command line:1:0: W0012: Unknown option value for '--enable', expected a valid pylint message and got 'no-self-use' (unknown-option-value)
**After**
Command line:1:0: R0022: Useless option value for '--enable', 'no-self-use' was moved to an optional extension, see https://pylint.pycqa.org/en/latest/whatsnew/2/2.14/summary.html#removed-checkers. (useless-option-value)
=> Mark `no-self-use` as moved to extensions

.github/workflows/primer_run_pr.yaml
Fixes run failures such as those seen in https://github.com/PyCQA/pylint/pull/6898.
Because skipped runs are also counted as `completed` we don't get the correct run whenever an initial run on `main` is skipped but the new one hasn't yet finished. See https://docs.github.com/en/rest/actions/workflow-runs#list-workflow-runs
=> Search for successful instead of completed runs on ``main`` for primer

doc/whatsnew/2/2.14/full.rst, pylint/config/config_file_parser.py, pylint/config/config_initialization.py, tests/config/functional/ini/pylintrc_with_missing_comma.4.out, tests/config/functional/ini/pylintrc_with_multi_line_init_hook.ini
Closes #6888.
We could also use an `if` statement to check whether the option is `init-hook` and and then not strip the newlines. But that introduce additional overhead, while this makes pylint faster. The fact that the rest of the test suite passes makes me think that this will be fine. We strip most options of whitespaces in other places anyway.
If this regresses after `2.14.2` we can simply add the `if` statement as desired.
=> Mix incorrect parsing of multi-line options in ``ini`` files

doc/whatsnew/2/2.14/full.rst, doc/whatsnew/2/2.15/index.rst, pylint/lint/base_options.py, pylint/lint/message_state_handler.py, tests/test_self.py
Closes #6811
Now, `--errors-only` is interpreted as a disable of non-error/fatal messages, not a paired disable of non-errors and enable of every error. Prevents canceling out prior disables. (In other words, it was acting as "enable all and only errors", not "disable non-errors").
=> Treat `--errors-only` as a disable, not a paired enable/disable

doc/whatsnew/2/2.14/full.rst, pylint/checkers/classes/class_checker.py, tests/functional/u/useless/useless_super_delegation.py, tests/functional/u/useless/useless_super_delegation.txt
=> Fix false positive for ``useless-super-delegation`` for variadics

doc/whatsnew/2/2.14/full.rst, pylint/checkers/variables.py, tests/functional/u/undefined/undefined_variable.py, tests/functional/u/undefined/undefined_variable.txt
=> Fix ``undefined-variable`` for ``__class__`` in inner methods

doc/whatsnew/2/2.15/index.rst, pylint/checkers/utils.py, pylint/checkers/variables.py, tests/functional/u/undefined/undefined_variable_py38.py, tests/functional/u/undefined/undefined_variable_py38.txt, tests/functional/u/used/used_before_assignment_conditional.py, tests/functional/u/used/used_before_assignment_conditional.txt
Self-referencing assignments under if statements were getting a free pass.
Closes #6643
=> Emit `used-before-assignment` for self-referencing assignments under if conditions

.github/workflows/primer-test.yaml, doc/data/messages/b/bad-super-call/bad.py, doc/data/messages/b/bad-super-call/details.rst, doc/data/messages/b/bad-super-call/good.py, doc/whatsnew/2/2.14/full.rst, pylint/checkers/newstyle.py, tests/functional/s/super/super_checks.py, tests/functional/s/super/super_checks.txt
=> Fix ``bad-super-call`` for non-direct parents

doc/exts/pylint_messages.py, examples/deprecation_checker.py, pylint/checkers/__init__.py, pylint/checkers/base_checker.py, pylint/checkers/deprecated.py, pylint/checkers/imports.py, pylint/checkers/stdlib.py, pylint/message/message_definition.py, pylint/typing.py, tests/message/unittest_message_definition.py, tests/message/unittest_message_id_store.py, tests/pyreverse/functional/class_diagrams/colorized_output/colorized.puml
This PR move message definitions from `msgs` attribute of DeprecatecMixin to separate class attributes. `msgs` attribute cannot be used directly anyway because it mixes two different message classes: `W15XX` and `W04XX`.
Closes #6656
=> Add support of sharing message in multiple checkers. Fix DeprecatedChecker example

doc/whatsnew/2/2.15/index.rst, pylint/checkers/variables.py, tests/functional/u/used/used_before_assignment.py, tests/functional/u/used/used_before_assignment.txt
=> Emit `used-before-assignment` when calling nested functions before assignment

doc/development_guide/contributor_guide/release.md
Add a step for cleaning up readthedoc version list in the release process.
=> [release doc] Add instruction for readthedoc cleanup

.coveragerc, .pyenchant_pylint_custom_dict.txt, pylint/testutils/_primer/primer.py, pylint/testutils/_primer/primer_command.py, pylint/testutils/_primer/primer_compare_command.py, pylint/testutils/_primer/primer_prepare_command.py, pylint/testutils/_primer/primer_run_command.py, tests/testutils/_primer/fixtures/message_changed/expected_truncated.txt, tests/testutils/_primer/test_primer.py
=> Refactor the primer command to be able to make the comment better later on

doc/data/messages/s/stop-iteration-return/bad.py, doc/data/messages/s/stop-iteration-return/details.rst, doc/data/messages/s/stop-iteration-return/good.py, doc/data/messages/s/stop-iteration-return/related.rst
=> [doc] Add some examples for 'stop-iteration-return'

setup.cfg
The "Homepage" link at https://pypi.org/project/pylint/ points to https://www.pylint.org/ which is down:
Instead, link to the docs page at https://pylint.pycqa.org/.
=> Fix homepage link

doc/development_guide/api/pylint.rst, pylint/checkers/utils.py, pylint/config/utils.py, pylint/extensions/typing.py, pylint/lint/pylinter.py, tests/test_deprecation.py, tests/test_self.py
=> Typos and remove always true condition

doc/whatsnew/2/2.14/full.rst, pylint/config/config_initialization.py, tests/config/functional/ini/pylintrc_with_quoted_init_hook.0.out, tests/config/functional/ini/pylintrc_with_quoted_init_hook.ini
=> Fix handling of quoted ``init-hook``

doc/data/messages/i/invalid-unary-operand-type/bad.py, doc/data/messages/i/invalid-unary-operand-type/details.rst, doc/data/messages/i/invalid-unary-operand-type/good.py
Add documentation examples for `invalid-unary-operand-type`
Refs #5953
=> Add documentation examples for `invalid-unary-operand-type`

doc/data/messages/i/invalid-format-index/bad.py, doc/data/messages/i/invalid-format-index/details.rst, doc/data/messages/i/invalid-format-index/good.py
Add documentation examples for `invalid-format-index`
Refs #5953
=> Add documentation examples for `invalid-format-index`

tests/primer/packages_to_lint_batch_one.json, tests/primer/packages_to_prime.json
Tested on my fork. With adding `django`, the 3.7 primer job takes 32m, and the 3.10 job 28m.
=> [primer] Move `django` to new primer

pylint/checkers/method_args.py
Followup to #6780 to avoid deprecation warnings.
=> Avoid deprecated `self.config` access in `missing-timeout`

doc/whatsnew/2/2.14/full.rst, pylint/extensions/private_import.py, tests/functional/ext/private_import/private_import.py
=> Don't report `import-private-name` for relative imports

doc/whatsnew/2/2.14/full.rst, pylint/lint/expand_modules.py, tests/test_self.py
Path should be normalized before checking if it should be ignored. E.g. paths
* ./some/path
* some/path
* some//path
Are the same path. All paths are normalized before checking so creating ignore regex is more straightforward.
See https://docs.python.org/3/library/os.path.html#os.path.normpath for details.
Closes #6964
=> Normalize path before checking if path should be ignored

.flake8, .github/workflows/release.yml, .pre-commit-config.yaml, .pyenchant_pylint_custom_dict.txt, Dockerfile, MANIFEST.in, pyproject.toml, setup.cfg, setup.py
* Use isolated build environments [PEP 517](https://peps.python.org/pep-0517/) with `python -m build` instead of deprecated `python setup.py sdist bdist_wheel`
* Move project metadata from `setup.cfg` to `pyproject.toml` [PEP 621](https://peps.python.org/pep-0621/)
* Cleanup and remove `MANIFEST.in` -> entries haven't been used.
* ~Add `README.rst` to `MANIFEST.in`. Required to be able to build the `wheel` from `sdist` and still include the readme text in the project metadata.~
* Remove `setup.py`. With recent pip versions (`>= 21.0`), no longer required for editable installs. `setup.cfg` is enough.
**Metadata diff**
```diff
-Author: Python Code Quality Authority
-Author-email: code-quality@python.org
+Author-email: Python Code Quality Authority <code-quality@python.org>
...
-Keywords: …
```
=> Improve packaging [PEP 517 + 621]

.pre-commit-config.yaml, setup.py
Followup to https://github.com/PyCQA/pylint/pull/7076#issuecomment-1169308238
Turns out `setup.py` is required for dependabot. At least for now.
=> Add setup.py back to fix dependabot

pylint/testutils/_primer/primer_command.py, pylint/testutils/_primer/primer_run_command.py
=> [primer] Refactor the primer to use 'pylint.message.Message'

doc/whatsnew/2/2.14/full.rst, pylint/config/config_initialization.py, tests/config/test_config.py
Closes https://github.com/PyCQA/pylint/issues/7003.
=> Fix handling of ``--`` as separator of positional arguments and flags

doc/user_guide/configuration/all-options.rst, pylint/lint/base_options.py
This just adds the note from #5415 to docs to explain that `\` is not valid in ignore-paths per https://github.com/PyCQA/pylint/issues/5398#issuecomment-981156554 because it also currently is needed to support Windows path normalization. This will help avoid additional issues being created (like the one I created in #7089 and also someone else in #7094) to reduce the burden on pylint maintainers/developers.
=> Update docs to explain escape character not valid

tests/lint/unittest_lint.py
=> Restore `sys.path` in `test_load_plugin_configuration`

pylint/checkers/refactoring/refactoring_checker.py, tests/functional/c/consider/consider_using_in.txt
Set are more performant for membership tests, we have another checks for this, we may as well suggest the right test from the start. Follow-up to #6635
=> [consider-using-in] Suggest set instead of tuple for membership

doc/whatsnew/2/2.14/full.rst, pylint/checkers/variables.py, tests/functional/u/undefined/undefined_loop_variable.py, tests/functional/u/undefined/undefined_loop_variable.txt
=> Fix crash when using `enumerate` in a ternary expression

doc/user_guide/configuration/all-options.rst, examples/pylintrc, examples/pyproject.toml, pylint/lint/base_options.py, pylintrc
To exceed a threshold here sonds to me as if the score would have to be _above_ the threshold, which is the opposite of what actually happens. Use "maintain" instead of "exceed" to "fix" the description. Another possibility would be to "meet" the threshold, or to rephrase the description altogether.
=> doc(fail-under): improve description

doc/user_guide/checkers/extensions.rst, pylint/extensions/empty_comment.py, tests/message/unittest_message_id_store.py
Seemingly copypaste artifacts from the refactoring checker.
=> [empty_comment] fix checker name in code and docs

pylint/checkers/exceptions.py, pylint/config/callback_actions.py, pylint/testutils/functional/test_file.py
@Pierre-Sassoulas only two TODOs remain. Could you take a look at those:
https://github.com/PyCQA/pylint/blob/7616e83e2541a5f3a66ea2caa751979c0f398d2b/script/bump_changelog.py#L19
https://github.com/PyCQA/pylint/blob/7616e83e2541a5f3a66ea2caa751979c0f398d2b/script/fix_documentation.py#L17
Refs. #6632.
=> Bump or remove some ``TODOs``

doc/data/messages/b/bad-builtin/pylintrc, doc/data/messages/c/consider-using-tuple/pylintrc, doc/data/messages/m/missing-param-doc/pylintrc, doc/data/messages/m/missing-raises-doc/pylintrc, doc/data/messages/m/missing-type-doc/pylintrc, doc/data/messages/o/overlapping-except/pylintrc, doc/data/messages/r/redefined-variable-type/pylintrc, doc/data/messages/u/use-set-for-membership/pylintrc, doc/data/messages/u/using-final-decorator-in-unsupported-version/pylintrc, doc/test_messages_documentation.py
Will unblock https://github.com/PyCQA/pylint/pull/7070 and others as it changes the value for `max-return-values` from our own `11` to the default of `6`.
=> Use the default config in the messages documentation tests

pylintrc
Closes https://github.com/PyCQA/pylint/issues/6284.
We don't support this and it would unnecessarily complicate things. The rationale for this is also flimsy at best:
The original reporter wanted to put all `linter` config in a special subdirectory and then create a `.pylintrc` file which would point to a file in that directory. That's just... Use a symlink or just use one file, this unnecessarily complicates stuff. 
_We're a linter, we should not support such anti-patterns_ 😄
=> Remove unsupported option from our own ``pylintrc``

doc/whatsnew/2/2.14/full.rst, pylint/extensions/_check_docs_utils.py, tests/functional/ext/docparams/parameter/missing_param_doc_required_Numpy.py
Closes https://github.com/PyCQA/pylint/issues/4035.
I really don't want to talk about the number of hours it took me to get this regex right. The fact that I assigned this to myself in October is a small indication...
=> Allow lists of default values in parameter documentation for ``Numpy``

doc/data/messages/c/consider-using-any-or-all/bad.py, doc/data/messages/c/consider-using-any-or-all/details.rst, doc/data/messages/c/consider-using-any-or-all/good.py, doc/data/messages/c/consider-using-any-or-all/pylintrc
`bad.py` examples taken directly from the functional tests.
=> Added documentation examples for `consider-using-any-or-all`.

pylint/lint/pylinter.py
Previously, any crash reports generated in the same hour would get appended into the same file.
When debugging multiple failures (or repeating a single failure while trimming down a large file into a minimal example) it's not ideal to have distinct crash reports all appended into the same file IMO.
=> Prevent appending distinct crash reports together that occur in the same hour

.github/workflows/primer_run_main.yaml
See [last run](https://github.com/PyCQA/pylint/actions/runs/2644912539) on main. The 3.7 job sometimes takes just barely over 45 minutes. The old primer timeout was set to 60m.
Clearly we need to add some concurrency. Rather than parallelizing the primer message comparison infrastructure, my hope is that we can just (later this year or next) solve the underlying issues with `--jobs` (see label `topic: multiprocessing`) and use that.
=> Increase new primer timeout to 60m

pylint/testutils/utils.py, tests/test_self.py, tests/testutils/test_testutils_utils.py
There's still a lot to do there, but I'm going slowly. In particular I would have though that some pytest fixtures would have existed for these use cases, but it seem it's not the case, or is non-trivial.
=> Refactor context manager for sys path and current working directory in tests

doc/user_guide/configuration/index.rst
I've added some documentation on best practices regarding the configuration file. Specifically, it recommends to use a minimal configuration file which only contains configuration overrides rather than a full configuration file where most options use the default values.
Closes #6968
=> Add documentation on using a minimal config file

doc/exts/pylint_messages.py, doc/whatsnew/2/2.15/index.rst
It makes more sense to _first define the problem_, then solve it.
Mentions issue https://github.com/PyCQA/pylint/issues/7143
Signed-off-by: Stavros Ntentos <133706+stdedos@users.noreply.github.com>
Refs #7143
=> In "Messages Overview", show the `bad_code` first

tests/config/pylint_config/test_run_pylint_config.py
This test fails if run through pytest with any args, because
`_run_pylint_config` passes through args from the command line
without checking if the args are actually intended for
pylint-config. We have to pass it some fake args that evaluate
truth-y but don't break anything, to avoid this.
Signed-off-by: Adam Williamson <awilliam@redhat.com>
=> test_run_pylint_config: ignore pytest args

tests/functional/i/import_outside_toplevel.py, tests/functional/i/import_outside_toplevel.txt
Downstream (e.g. in Fedora) tkinter and turtle aren't always
included in the core Python package in order to avoid pulling in
a lot of graphical dependencies on systems that do not need them.
It doesn't really matter what libs are used in this test, so
let's replace it with trace.
=> Use trace not turtle in import_outside_toplevel test

pylint/testutils/utils.py, tests/test_self.py
This is the consensual part of https://github.com/PyCQA/pylint/pull/7173. First step before a MR to fix the pythonpath handling were the pythonpath is not rested correctly.
=> More parametrization in ``test_self.py`` tests

doc/exts/pylint_options.py
The change should also be reflected in rendered docs, like in `doc/user_guide/configuration/all-options.rst`, but I think those are generated from this doc.
=> Fix config section name in doc

pylint/testutils/_primer/primer_run_command.py
This permits to fail early instead of priming all the packages in case of fatal error in the primer. It also adds more and easier to read print. For example if astroid can be primed, but black cannot (it was not downloaded previously). 
```
Running 'pylint tests/.pylint_primer_tests/PyCQA/astroid/astroid, --rcfile=tests/.pylint_primer_tests/PyCQA/astroid/pylintrc, --enable-all-extensions, --enable=all, --disable=duplicate-code,cyclic-import'
Successfully primed astroid.
Running 'pylint tests/.pylint_primer_tests/psf/black/src/black, tests/.pylint_primer_tests/psf/black/src/blackd, tests/.pylint_primer_tests/psf/black/src/blib2to3, --enable-all-extensions, …
```
=> [primer] display results early instead of priming all the packages first

pylint/extensions/docparams.py, pylint/testutils/functional/test_file.py, tests/functional/ext/docparams/docparams.txt, tests/functional/ext/docparams/docparams_py38.txt, tests/functional/ext/docparams/missing_param_doc.txt, tests/functional/ext/docparams/parameter/missing_param_doc_required.txt, tests/functional/ext/docparams/parameter/missing_param_doc_required_Google.txt, tests/functional/ext/docparams/parameter/missing_param_doc_required_Numpy.txt, tests/functional/ext/docparams/parameter/missing_param_doc_required_Sphinx.txt, tests/functional/ext/docparams/parameter/missing_param_doc_required_no_doc_rgx_check_init.txt, tests/functional/ext/docparams/parameter/missing_param_doc_required_no_doc_rgx_test_all.txt, tests/functional/ext/docparams/raise/missing_raises_doc.txt, tests/functional/ext/docparams/raise/missing_raises_doc_Google.txt, tests/functional/ext/docparams/raise/missing_raises_doc_Numpy.txt, tests/functional/ext/docparams/raise/missing_raises_doc_Sphinx.txt, tests/functional/ext/docparams/raise/missing_raises_doc_required.txt, tests/functional/ext/docparams/raise/missing_raises_doc_required_exc_inheritance.txt, tests/functional/ext/docparams/return/missing_return_doc_Google.txt, tests/functional/ext/docparams/return/missing_return_doc_Numpy.txt, tests/functional/ext/docparams/return/missing_return_doc_Sphinx.txt, tests/functional/ext/docparams/return/missing_return_doc_required.txt, tests/functional/ext/docparams/return/missing_return_doc_required_Google.txt, tests/functional/ext/docparams/return/missing_return_doc_required_Numpy.txt, tests/functional/ext/docparams/return/missing_return_doc_required_Sphinx.txt, tests/functional/ext/docparams/useless_type_doc.txt, tests/functional/ext/docparams/yield/missing_yield_doc_required.txt, tests/functional/ext/docparams/yield/missing_yield_doc_required_Google.txt, tests/functional/ext/docparams/yield/missing_yield_doc_required_Numpy.txt, tests/functional/ext/docparams/yield/missing_yield_doc_required_Sphinx.txt
Add the confidence for the doc param checker and some minor refactors prior to #7212
=> Add the proper confidence in doc param checker's messages

pylint/checkers/base/basic_checker.py, tests/functional/ext/docparams/parameter/missing_param_doc_required_Sphinx.txt, tests/functional/ext/docparams/raise/missing_raises_doc.txt, tests/functional/ext/docparams/raise/missing_raises_doc_Google.txt, tests/functional/ext/docparams/raise/missing_raises_doc_Numpy.txt, tests/functional/ext/docparams/raise/missing_raises_doc_Sphinx.txt, tests/functional/ext/docparams/return/missing_return_doc_Google.txt, tests/functional/ext/docparams/return/missing_return_doc_required_Google.txt, tests/functional/ext/docparams/return/missing_return_doc_required_Numpy.txt, tests/functional/ext/docparams/return/missing_return_doc_required_Sphinx.txt, tests/functional/u/unreachable.txt
Add the confidence for unreachable prior to https://github.com/PyCQA/pylint/pull/7212 because the functional test for the doc param checker have a lot of 'unreachable' in them.
=> Add the confidence for 'unreacheable' code

doc/whatsnew/fragments/3860.bugfix, pylint/checkers/imports.py, pylint/lint/pylinter.py, tests/functional/i/import_error.txt, tests/functional/s/syntax/syntax_error.txt, tests/test_self.py
=> [syntax error] Fix a crash when the line and column can't be retrieved

doc/user_guide/configuration/all-options.rst, examples/pylintrc, examples/pyproject.toml, pylint/checkers/variables.py
The default was out of date and we can use the real default value dynamically anyway.
=> Remove hard-coded default in 'ignored-argument-names' description

tests/functional/d/deprecated/deprecated_methods_py36.rc
Maybe astroid 2.12.3 will fix this because of https://github.com/PyCQA/astroid/pull/1714 but this is taking some time to be released.
=> [test] Temporary xfail deprecated methods py36 on pypy

doc/whatsnew/fragments/7246.bugfix, pylint/lint/pylinter.py
Closes #7246
Extracted from #7117
I don't think it's worth adding a context manager just to handle this one fix.
=> Fix sys.path pollution in parallel mode

doc/whatsnew/fragments/7202.bugfix, pylint/config/argument.py, tests/config/test_config.py
=> Fix crash when regex option raises a `re.error` exception.

doc/whatsnew/fragments/3975.false_positive, pylint/checkers/classes/class_checker.py, tests/functional/i/init_not_called.py, tests/functional/i/init_not_called.txt, tests/functional/n/non/non_init_parent_called.py, tests/functional/n/non/non_init_parent_called.txt, tests/functional/s/super/super_init_not_called.py, tests/functional/s/super/super_init_not_called.rc, tests/functional/s/super/super_init_not_called.txt
=> Don't emit ``super-init-not-called`` for abstract ``__init__`` methods

doc/whatsnew/fragments/4444.bugfix, pylint/lint/expand_modules.py, tests/checkers/unittest_imports.py, tests/lint/unittest_lint.py
Fixes #4444: modules contained under an identically named directory weren't linted (failed with `parse-error`).
This PR causes a test failure in `TestImportsChecker.test_relative_beyond_top_level_two`, but that test uses `epylint` to excute pylint (!) which does additional manipulation of `cwd`, so I don't think it's correct.
Notice that linting the package in the test fails using regular pylint, but the failure is now more accurate on this branch:
**main**
```shell
$ pylint tests/regrtest_data/beyond_top_two
************* Module beyond_top_two
tests/regrtest_data/beyond_top_two/__init__.py:1:0: F0010: error while code parsing: Unable to load file …
```
=> Fix the failure to lint modules contained under an identically named directory

README.rst, doc/whatsnew/fragments/7267.internal
See https://openssf.org/
Full disclosure, I'm being paid to make pylint more secure by Tidelift
and this is part of this effort.
=> [open source insight] Add the badge from OpenSSF

doc/whatsnew/fragments/7231.bugfix, pylint/__init__.py, tests/test_self.py
This PR adds code to check if the item being removed from `sys.path` in `modify_sys_path` is in fact current working directory. Adds tests for the change.
Closes #7231
=> Check for `<cwd>` before removing first item from `sys.path` in `modify_sys_path`.

tests/checkers/unittest_imports.py
=> Clean up beyond_top_level tests

doc/whatsnew/fragments/4444.bugfix, pylint/lint/expand_modules.py, tests/checkers/unittest_imports.py, tests/lint/unittest_lint.py
Fixes the failure to lint namespace packages under a directory on `sys.path`. Will need to reopen #4444 and find a new solution for it.
=> Revert "Fix the failure to lint modules contained under an identically named directory"

doc/whatsnew/fragments/7300.false_positive, pylint/checkers/classes/class_checker.py, tests/functional/n/no/no_self_argument.py, tests/functional/n/no/no_self_argument.txt
Fix false positive for `no-self-argument` when a staticmethod is applied to a function but uses a different name.
Closes #7300
=> Fix false positive for `no-self-argument`

pylint/lint/pylinter.py
Refs https://github.com/PyCQA/pylint/issues/7263.
=> Refactors related to separating ast creating and linting

pylint/lint/pylinter.py, tests/lint/test_pylinter.py, tests/test_check_parallel.py
Refs https://github.com/PyCQA/pylint/issues/7263.
Blocked by #7286.
=> Refactor check()

doc/whatsnew/fragments/7311.false_positive, pylint/checkers/variables.py, script/check_newsfragments.py, tests/functional/u/undefined/undefined_loop_variable.py, tests/functional/u/undefined/undefined_loop_variable.txt
Refs #7311 (idk how to fix functions that return `NoReturn`)
=> fix `undefined-loop-variable` with `break` and `continue` statements in `else` blocks

doc/contact.rst
I think the link is permanently down, no idea where this discussion is now and I never used it myself.
=> [doc] Remove dead link to the mail archives prior to 2013

doc/data/messages/i/invalid-name/details.rst, doc/whatsnew/fragments/7322.false-positive, pylint/checkers/base/name_checker/checker.py, tests/functional/a/assigning/assigning_non_slot.py, tests/functional/t/typevar_naming_style_default.py, tests/functional/t/typevar_naming_style_default.txt
Small improvements for the `TypeVar` name regex.
* Simplify `[^\W\da-z_]` to `[A-Z]`
* Add negative lookahead to prevent `T` or `Type` prefix. E.g. `TAnyStr` should be marked as `invalid-name`.
=> Improve TypeVar name regex

doc/whatsnew/fragments/7222.bugfix, pylint/checkers/variables.py, tests/functional/u/undefined/undefined_loop_variable_py38.py, tests/functional/u/undefined/undefined_loop_variable_py38.rc
=> Fix `undefined-loop-variable` from walrus in comprehension test

doc/whatsnew/fragments/7319.bugfix, pylint/checkers/classes/class_checker.py, tests/functional/u/useless/useless_parent_delegation.py
`useless-parent-delegation` tries to be smart enough to detect when there are different default values to an overridden method's arguments and then silence itself--but it was not capturing the case where the source method is uninspectable (e.g. written in C.)
Now, we check for that, but we still catch trivial delegations (e.g. only "self" and no other arguments).
Closes #7319
=> Prevent `useless-parent-delegation` for overriding builtins with new args

tests/lint/unittest_lint.py
=> Add regression test for #3651

doc/whatsnew/fragments/6896.false_positive, pylint/checkers/refactoring/refactoring_checker.py, tests/functional/u/unnecessary/unnecessary_list_index_lookup.py
Closes #6896.
/CC @timmartin This makes the check very conservative but our current test suite still passes and thus the check still offers some benefit. I'd like to merge this and have us improve the checker if somebody wants to: avoiding false positives is more important than false negatives imo.
=> Skip ``unnecessary-list-index-lookup`` if we encounter if statements

doc/whatsnew/fragments/7270.false_positive, pylint/checkers/utils.py, tests/functional/i/import_error.py, tests/functional/i/import_error.txt
=> Check for ``contextlib.suppress`` in ``node_ignores_exception``

doc/whatsnew/fragments/6936.false_positive, pylint/checkers/format.py, tests/functional/t/trailing_whitespaces.py, tests/functional/t/trailing_whitespaces.txt
Closes #6936 and also updates the confidence.
=> Don't emit ``trailing-whitespace`` twice for multi-line docstrings

pylint/reporters/json_reporter.py, script/fix_documentation.py
=> Bump TODOs to the next minor version in preparation of release

.github/workflows/changelog.yml, .github/workflows/checks.yaml, .github/workflows/primer-test.yaml, .github/workflows/primer_comment.yaml, .github/workflows/primer_run_main.yaml, .github/workflows/primer_run_pr.yaml, .github/workflows/tests.yaml, pyproject.toml, requirements_test_min.txt
Required to be done as a standalone before #7355 because the primer can't work when we upgrade astroid.
=> Upgrade astroid version following 2.12.4 release

doc/data/messages/l/literal-comparison/bad.py, doc/user_guide/checkers/features.rst, doc/whatsnew/fragments/5237.other, pylint/checkers/base/comparison_checker.py, tests/functional/c/comparison_of_constants.py, tests/functional/c/comparison_of_constants.txt, tests/functional/l/literal_comparison.py, tests/functional/l/literal_comparison.txt
Also update the confidence
Closes #5237
=> [literal-comparison] Make the message more explicit with the solution

doc/whatsnew/2/2.15/index.rst, doc/whatsnew/fragments/7322.false-positive
Just checked the `2.15` release notes and noticed that my change wasn't included. I guess it's important to use an underscore in the suffix 🤷🏻‍♂️
Refs #7322
=> Fix 2.15 changelog

tests/testutils/test_testutils_utils.py
This PR makes the test suite independent of the outside environment. `PYTHONPATH` could be set or not. Test both.
Closes #7366
=> nest _test_environ_pythonpath independent of outside PYTHONPATH

doc/whatsnew/fragments/7368.false_positive, pylint/checkers/variables.py, tests/functional/u/undefined/undefined_variable.py, tests/functional/u/undefined/undefined_variable.txt
Closes #7368
This PR fixes the following false-positive:
```python
from typing import TYPE_CHECKING
if TYPE_CHECKING:
from typing_extensions import assert_type
else:
def assert_type(val, _):
return val
ANSWER = 42
assert_type(ANSWER, int)  # E0601: Using variable 'assert_type' before assignment (used-before-assignment)
```
The issue comes from definitions in the `else` block of a `if` type-guard.
In 3159b1744caee14068b4d875bb5adaa5ffbebd44 the case was already handled for assignments, I had only added cases for function and class that are defined in the `else` part.
=> Fix `used-before-assignment` for functions/classes defined in type checking guard

tests/config/unittest_config.py
Resolve a deprecation warning seen in python 3.11
=> Replace deprecated `sre_constants.error` with `re.error`

doc/data/messages/b/bad-format-string-key/bad.py, doc/data/messages/b/bad-format-string-key/details.rst, doc/data/messages/b/bad-format-string-key/good.py
Documentation examples for `bad-format-string-key`.
Refs #5953
=> Added documentation examples for `bad-format-string-key`

doc/data/messages/r/redefined-outer-name/bad.py, doc/data/messages/r/redefined-outer-name/details.rst, doc/data/messages/r/redefined-outer-name/good.py
=> Added documentation examples for `redefined-outer-name`

.pyenchant_pylint_custom_dict.txt, doc/whatsnew/fragments/3822.false_positive, pylint/checkers/format.py, tests/functional/t/trailing_whitespaces.py
=> Don't report ``trailing-whitespaces`` within strings

doc/whatsnew/fragments/7380.bugfix, pylint/checkers/modified_iterating_checker.py, tests/functional/m/modified_iterating.py, tests/functional/m/modified_iterating.txt
Closes #7380
@orSolocate I haven't created an issue for this but:
```python
class MyClass:
def __init__(self) -> None:
self.attribute = [1, 2, 3]
def my_other_method(self):
"""This should raise as we are appending."""
for var in self.attribute:
self.attribute.append(var)  # [modified-iterating-list]
```
Currently doesn't raise like it should.
This would require quite a bit of refactoring in the current checker as it isn't really suited for checking class attributes. I'm not sure and there is no obligation, but perhaps you find this interesting and want to look into it?
=> Fix crash while iteraring over a class attribute

doc/whatsnew/fragments/6592.false_positive, pylint/checkers/typecheck.py, tests/functional/a/arguments.py
False positive `too-many-function-args`
Closes #6592
=> False positive for `too-many-function-args`

doc/whatsnew/fragments/3299.false_positive, pylint/checkers/utils.py, pylint/checkers/variables.py, tests/checkers/unittest_utils.py, tests/functional/u/unused/unused_name_in_string_literal_type_annotation.py, tests/functional/u/unused/unused_name_in_string_literal_type_annotation.txt, tests/functional/u/unused/unused_name_in_string_literal_type_annotation_py310.py, tests/functional/u/unused/unused_name_in_string_literal_type_annotation_py310.rc, tests/functional/u/unused/unused_name_in_string_literal_type_annotation_py38.py, tests/functional/u/unused/unused_name_in_string_literal_type_annotation_py38.rc, tests/functional/u/unused/unused_name_in_string_literal_type_annotation_py38.txt, tests/functional/u/unused/unused_name_in_string_literal_type_annotation_py39.py, tests/functional/u/unused/unused_name_in_string_literal_type_annotation_py39.rc
Closes #3299
Changes:
- `VariablesChecker` now checks for possible names in `Const` strings that appear in a typing annotation context. This fixes some false positives for `unused-import` and `unused-variable`.
- string `Const`s used as args to `typing.Literal` aren't treated as names.
- String annotations like `"os.PathLike[str]"` or `"graphlib.TopologicalSorter[T]"` now work
=> Fix #3299 false positives with names in string literal type annotations

doc/whatsnew/fragments/2374.false_negative, pylint/checkers/utils.py, tests/functional/u/used/used_before_assignment_nonlocal.py, tests/functional/u/used/used_before_assignment_nonlocal.txt
=> Emit `used-before-assignment` when function arguments are redefined in inner function

doc/whatsnew/fragments/4743.bugfix, pylint/extensions/docparams.py, tests/functional/ext/docparams/docparams.py, tests/functional/ext/docparams/docparams.rc, tests/functional/ext/docparams/docparams.txt, tests/functional/ext/docparams/return/missing_return_doc_required.py
Closes https://github.com/PyCQA/pylint/issues/4743
Not sure what you were referring to in your [comment](https://github.com/PyCQA/pylint/issues/4743#issuecomment-1200108536) but this seems to be the most logical fix. The code you were referring to is for another message.
=> Make ``missing-return-doc`` respect the ``no-docstring-rgx`` option

doc/whatsnew/fragments/7398.other, pylint/extensions/_check_docs_utils.py, tests/functional/ext/docparams/docparams.py, tests/functional/ext/docparams/missing_param_doc.py, tests/functional/ext/docparams/missing_param_doc.txt, tests/functional/ext/docparams/parameter/missing_param_doc_required_Numpy.py
Some refactors based on the work in https://github.com/PyCQA/pylint/pull/7360
I'd like to see how the primer reacts to separate some of the large changes we were seeing in that PR.
=> Fix and refactors for ``docparams`` extension

doc/whatsnew/fragments/7401.bugfix, pylint/checkers/variables.py, pylint/lint/message_state_handler.py, pylint/utils/file_state.py, tests/functional/d/disable_msg_next_line.py, tests/functional/d/disable_msg_next_line.txt
=> Make ``disable-next`` only consider the succeeding line

doc/whatsnew/fragments/4743.bugfix, pylint/extensions/docparams.py, tests/functional/ext/docparams/raise/missing_raises_doc_required.py, tests/functional/ext/docparams/yield/missing_yield_doc_required.py, tests/functional/ext/docparams/yield/missing_yield_doc_required.txt
=> Make ``missing-yield/raises-doc`` respect ``no-docstring-rgx`` option

doc/whatsnew/fragments/7290.false_positive, tests/functional/d/dataclass_kw_only.py, tests/functional/d/dataclass_kw_only.rc, tests/functional/d/dataclass_kw_only.txt
Closes #7290, closes #6550, closes #5857
=> Add regression test for dataclass kw_only support

doc/whatsnew/fragments/7169.bugfix, pylint/config/find_default_config_files.py, tests/config/test_find_default_config_files.py
=> Suppress ``OSError`` in config file discovery

.pyenchant_pylint_custom_dict.txt, doc/whatsnew/fragments/7264.bugfix, pylint/lint/pylinter.py, tests/lint/unittest_lint.py
As per #7264, this PR will make the changes covered the lines marked with ❗ in the following table. The table is about the relationship between the `load-plugins` and `init-hook` arguments/configuration options.
| # | Passed on CLI | Supplied in pylintrc | Can be imported before init | Can be imported after init | Current Behaviour | Desired Behaviour | Done |
| -- | -- | -- | -- | -- | -- | -- | -- |
| 1 | ✅ | 🚫 | 🚫 | 🚫 | Emit bad-plugin-value | Emit bad-plugin-value | N/A |
| 2 | 🚫 | ✅ | 🚫 | 🚫 | Emit bad-plugin-value | Emit bad-plugin-value | N/A |
| 3 | ✅ | 🚫 | 🚫 | ✅ | Do not register, but do import config, no emit | ❗ **Emit bad-plugin-value** | ✅  |
| 4| 🚫 | ✅ | 🚫 | ✅ | Load as normal, …
=> Add more cases that emit bad-plugin-value

doc/whatsnew/fragments/_template.rst, towncrier.toml
Turn out I was checking the wrong file when generating the release notes.
=> [towncrier] Add whitespaces between fragment in towncrier

pylint/config/arguments_manager.py, pylint/config/arguments_provider.py, pylint/config/option.py, pylint/config/option_manager_mixin.py, pylint/config/utils.py
@Pierre-Sassoulas Since these two modules are deprecated I thought it would be best to just `Any` a lot. We don't really need the typing anyway as most of it is uncovered currently and no longer used.
With this PR I got to `Found 227 errors in 35 files (checked 286 source files)` running in `strict` mode with one check disabled. It seems we're getting there 😄 🎉
=> Finish typing related to the ``config`` directory

pylint/checkers/base/name_checker/checker.py, pylint/checkers/classes/class_checker.py, pylint/checkers/design_analysis.py, pylint/checkers/modified_iterating_checker.py, pylint/checkers/refactoring/refactoring_checker.py, pylint/checkers/similar.py, pylint/checkers/spelling.py, pylint/checkers/typecheck.py, pylint/checkers/utils.py, pylint/checkers/variables.py, pylint/config/configuration_mixin.py, pylint/config/option.py, pylint/extensions/_check_docs_utils.py, pylint/extensions/code_style.py, pylint/extensions/mccabe.py, pylint/extensions/private_import.py, pylint/lint/expand_modules.py, pylint/lint/pylinter.py, pylint/pyreverse/diadefslib.py, pylint/pyreverse/diagrams.py, pylint/pyreverse/utils.py, pylint/pyreverse/writer.py, pylint/testutils/lint_module_test.py, pylint/utils/file_state.py, pylint/utils/utils.py, setup.cfg, tests/lint/test_pylinter.py, tests/reporters/unittest_json_reporter.py, tests/test_pylint_runners.py, tests/test_self.py
=> Turn on ``mypy`` strict mode 🎉 

doc/whatsnew/fragments/3299.bugfix, pylint/checkers/variables.py, tests/functional/u/unused/unused_name_in_string_literal_type_annotation.py, tests/functional/u/unused/unused_name_in_string_literal_type_annotation_py38.py, tests/functional/u/unused/unused_name_in_string_literal_type_annotation_py38.txt
This is a continuation of #7400. This PR fixes some errors in the handling of typing.Literal.
From https://peps.python.org/pep-0586/#literals-enums-and-forward-references:
> One potential ambiguity is between literal strings and forward references to literal enum members. For example, suppose we have the type Literal["Color.RED"]. Does this literal type contain a string literal or a forward reference to some Color.RED enum member?
> In cases like these, we always assume the user meant to construct a literal string. If the user wants a forward reference, they must wrap the entire literal type in a string – e.g. "Literal[Color.RED]".
=> Disambiguate between str and enum member args to typing.Literal

doc/whatsnew/fragments/7453.bugfix, pylint/checkers/utils.py, tests/functional/u/unhashable_member.py
=> Fix `unhashable-member` crash when `lambda` used as a dict key

doc/whatsnew/fragments/7455.other, pylintrc
Description for `typevar-rgx` configuration (introduced by #5894) is mentioning `typevar-naming-style`, which currently does not exist.
https://github.com/PyCQA/pylint/blame/63738bf93f7b20e769923ae5a918b83058a70b78/pylintrc#L323
Refs #7455
=> Fix typevar-rgx description in pylintrc

doc/whatsnew/fragments/7463.other, pylint/checkers/base_checker.py, pylint/checkers/mapreduce_checker.py, pylint/checkers/utils.py, pylint/config/__init__.py, pylint/config/arguments_manager.py, pylint/config/arguments_provider.py, pylint/config/configuration_mixin.py, pylint/config/find_default_config_files.py, pylint/config/option.py, pylint/config/option_manager_mixin.py, pylint/config/option_parser.py, pylint/config/options_provider_mixin.py, pylint/interfaces.py, pylint/lint/pylinter.py, pylint/message/message.py, pylint/reporters/base_reporter.py, pylint/reporters/text.py, pylint/testutils/checker_test_case.py, pylint/testutils/functional_test_file.py, pylint/testutils/output_line.py, pylint/utils/file_state.py, pylint/utils/utils.py
With this change, relevant `DeprecationWarnings` are now raised with `stacklevel=2`, so they have the callsite attached in the message.
I'm not sure this fits anything below?
Closes #7463
=> Use stacklevel=2 in warnings.warn calls to DeprecationWarning where makes sense.
