pylint-dev/pylint

pylint/lint/parallel.py, pylint/message/message.py, pylint/reporters/text.py, pylint/testutils/output_line.py
=> Make ``Message`` a ``dataclass``

pylint/checkers/utils.py, pylint/typing.py, pylint/utils/ast_walker.py, pylint/utils/docs.py, pylint/utils/linterstats.py, tests/utils/unittest_ast_walker.py
=> Add last typing to ``pylint/utils``

pylint/lint/parallel.py
`_get_new_args` didn't really do much for us. We can just access the `messages` attribute.
=> Add typing to ``pylint/lint/parallel.py``

pylint/checkers/base_checker.py, pylint/config/arguments_provider.py, pylint/lint/parallel.py, pylint/lint/pylinter.py, pylint/utils/docs.py
@Pierre-Sassoulas, best viewed in commit view.
=> Refactors related to typing of ``PyLinter``

pylint/config/argument.py, pylint/config/arguments_manager.py, pylint/config/utils.py, pylint/lint/base_options.py, tests/config/test_config.py
Closes #6385.
Didn't add a changelog as it was not yet released.
=> Fix short ``-v`` flag

.github/workflows/tests.yaml
As discussed in #6370 this would be my suggestion for incorporating ``--minimal-messages-config`` in the CI. 
Closes #6370
=> Run functional tests with ``--minimal-messages-config`` in CI

pylint/lint/parallel.py
https://github.com/PyCQA/pylint/pull/6383#discussion_r853023096
=> Add two temporary mypy disables to parallel.py

doc/data/messages/m/missing-param-doc/bad.py, doc/data/messages/m/missing-param-doc/good.py
=> Added missing-param-doc message example

tests/functional/l/logging_format_interpolation_py36.rc
Disable the currently failing functional tests when running with ``--minimal-messages-config``
Ref: https://github.com/PyCQA/pylint/pull/6375#issuecomment-1102643363
=> Fix functional tests with minimal messages config

pylint/checkers/base_checker.py, pylint/checkers/format.py, pylint/checkers/misc.py, pylint/checkers/raw_metrics.py, pylint/checkers/refactoring/refactoring_checker.py, pylint/checkers/spelling.py, pylint/checkers/strings.py, pylint/extensions/check_elif.py, pylint/interfaces.py, pylint/lint/pylinter.py
Add some typing in the checker. Simplify a piece of code that was hard to type otherwise.
=> Add typing to BaseChecker.process_token

.coveragerc, pylint/checkers/__init__.py, pylint/checkers/base_checker.py
=> Add base Checker classes mirroring interfaces

doc/data/messages/m/missing-param-doc/bad.py, doc/data/messages/m/missing-param-doc/good.py
=> Migrated example missing-param-doc to type annotations

doc/data/messages/m/missing-yield-doc/bad.py, doc/data/messages/m/missing-yield-doc/details.rst, doc/data/messages/m/missing-yield-doc/good.py, doc/data/messages/m/missing-yield-doc/pylintrc
=> Added missing-yield-doc message example

doc/data/messages/m/missing-type-doc/bad.py, doc/data/messages/m/missing-type-doc/good.py
=> Added missing-type-doc message example

requirements_test_min.txt, setup.cfg
=> Upgrade astroid to 2.11.3

pylint/reporters/json_reporter.py, pylint/reporters/multi_reporter.py, pylint/reporters/text.py, pylint/testutils/reporter_for_tests.py, tests/unittest_reporting.py
=> Remove ``__implements__ = IReporter``

ChangeLog, doc/whatsnew/2.14.rst, pylint/checkers/base_checker.py, pylint/checkers/refactoring/refactoring_checker.py, pylint/interfaces.py, pylint/lint/pylinter.py
Ref. #2287.
Blocked by https://github.com/PyCQA/pylint/pull/6401.
=> Deprecate interfaces.implements

doc/data/messages/m/missing-yield-type-doc/bad.py, doc/data/messages/m/missing-yield-type-doc/details.rst, doc/data/messages/m/missing-yield-type-doc/good.py, doc/data/messages/m/missing-yield-type-doc/pylintrc
=> Added missing-yield-type-doc message example

ChangeLog, doc/whatsnew/2.14.rst, pylint/checkers/base_checker.py, pylint/interfaces.py, pylint/lint/pylinter.py, pylint/reporters/base_reporter.py, tests/test_deprecation.py
=> Deprecate all interfaces

pylint/lint/pylinter.py
=> Add typing to ``PyLinter.check_astroid_module``

pylint/config/__init__.py, pylint/lint/pylinter.py, pylint/reporters/base_reporter.py, pylint/reporters/multi_reporter.py
=> Add typing to ``pylint/config/__init__.py``

pylint/lint/pylinter.py
=> Add typing to ``_read_stdin``

pylint/checkers/__init__.py, pylint/lint/expand_modules.py, pylint/lint/pylinter.py
=> Add typing to methods of ``PyLinter`` and related functions

pylint/lint/report_functions.py
=> Finish typing of ``pylint/lint/report_functions.py``

pylint/lint/pylinter.py
=> Add ``GetAstProtocol``

pylint/testutils/checker_test_case.py, pylint/testutils/decorator.py, pylint/testutils/global_test_linter.py, pylint/testutils/unittest_linter.py, tests/checkers/unittest_variables.py, tests/test_func.py
=> Finish typing of ``pylint/testutils``

pylint/checkers/base/name_checker/checker.py, pylint/checkers/classes/special_methods_checker.py, pylint/checkers/refactoring/implicit_booleaness_checker.py, pylint/checkers/refactoring/not_checker.py, pylint/checkers/refactoring/recommendation_checker.py, pylint/checkers/refactoring/refactoring_checker.py, pylint/extensions/check_elif.py, pylint/extensions/code_style.py, pylint/extensions/comparetozero.py, pylint/extensions/comparison_placement.py, pylint/extensions/confusing_elif.py, pylint/extensions/docstyle.py, pylint/extensions/emptystring.py, pylint/extensions/eq_without_hash.py, pylint/extensions/for_any_all.py, pylint/extensions/mccabe.py, pylint/extensions/overlapping_exceptions.py, pylint/extensions/private_import.py, pylint/extensions/redefined_variable_type.py, pylint/extensions/set_membership.py, pylint/extensions/typing.py, pylint/extensions/while_used.py
Part 2 following #6417 (cache invalidation fail in my IDE 😓 )
=> Migrate from utils.check_messages to utils.only_required_for_messages

pylint/checkers/classes/special_methods_checker.py, pylint/checkers/stdlib.py, pylint/checkers/utils.py, pylint/extensions/private_import.py
Add some typing detected when working on something else.
=> Small typing fixes

pylint/__init__.py, pylint/checkers/similar.py, pylint/epylint.py, pylint/interfaces.py, pylint/pyreverse/main.py
=> Finish typing of ``./pylint`` directory

pylint/checkers/format.py, tests/primer/test_primer_external.py
Reminder following the closing of #6078
=> Use list comprehension when possible for better performance

pylint/graph.py
=> Finish typing of ``pylint/graph.py``

pylint/checkers/format.py
=> Further simplification and performance fix in the ``FormatChecker``

pylint/checkers/base_checker.py, pylint/checkers/classes/class_checker.py, pylint/checkers/design_analysis.py, pylint/checkers/exceptions.py, pylint/checkers/format.py, pylint/checkers/imports.py, pylint/checkers/logging.py, pylint/checkers/newstyle.py, pylint/checkers/similar.py, pylint/checkers/strings.py, pylint/checkers/typecheck.py, pylint/checkers/variables.py, pylint/lint/pylinter.py, pylint/lint/report_functions.py, pylint/reporters/reports_handler_mix_in.py, pylint/typing.py, tests/config/unittest_config.py, tests/lint/unittest_expand_modules.py
=> Add typing to ``BaseChecker`` ``msgs`` and ``reports``

pylint/checkers/base_checker.py, pylint/typing.py
=> Add further typing to ``BaseChecker``

ChangeLog, README.rst, doc/development_guide/contribute.rst, doc/whatsnew/2.14.rst, requirements_test.txt, requirements_test_min.txt, setup.cfg
Follow-up to https://github.com/PyCQA/pylint/pull/6440#issuecomment-1109437387
=> Fix the installation of pyenchant

doc/data/messages/a/arguments-differ/bad.py, doc/data/messages/a/arguments-differ/good.py, doc/development_guide/contribute.rst, doc/development_guide/profiling.rst, doc/messages/messages_list.rst, pylint/checkers/refactoring/refactoring_checker.py, pylint/checkers/variables.py, tests/message/unittest_message_id_store.py
=> Various typo fixes

ChangeLog, doc/whatsnew/2.14.rst, pylint/checkers/strings.py, tests/functional/i/implicit/implicit_str_concat.py, tests/functional/i/implicit/implicit_str_concat.txt, tests/functional/i/implicit/implicit_str_concat_multiline.py, tests/functional/i/implicit/implicit_str_concat_multiline.txt
=> Raise ``implicit-str-concat`` on call

pylint/checkers/stdlib.py
=> [refactor] Create a generic '_check_open_call' function for the StdlibChecker

pylint/checkers/imports.py, pylint/checkers/stdlib.py, pylintrc, tests/pyreverse/functional/class_diagrams/colorized_output/colorized.puml, tests/test_similar.py
Changes extracted from https://github.com/PyCQA/pylint/pull/6121
Defining messages in two places is asking for trouble. The other changes fixes our tests for the changed values of these settings.
=> Some changes related to duplicate code

.pyenchant_pylint_custom_dict.txt, pylint/typing.py, pylint/utils/ast_walker.py
Followup to https://github.com/PyCQA/pylint/pull/6445#discussion_r856933332
=> Move AstCallback

ChangeLog, doc/whatsnew/2.14.rst, pylint/checkers/similar.py, tests/checkers/unittest_similar.py
See https://github.com/PyCQA/pylint/pull/6121/files#r844920300
=> Change default values of ``ignore-imports`` and ``ignore-signatures``

pylint/constants.py, tests/regrtest_data/duplicate_code/useless_suppression/file_one.py, tests/regrtest_data/duplicate_code/useless_suppression/file_two.py, tests/test_similar.py
Because we handle ``duplicate-code`` a little differently with disables the normal way of figuring out if the disable is useless doesn't work. Let's just not worry about it like we do for other difficult messages.
=> Do not report useless-suppression on duplicate-code

pylint/config/callback_actions.py, pylint/config/option_manager_mixin.py, pylint/graph.py, pylint/pyreverse/mermaidjs_printer.py, pylint/testutils/unittest_linter.py, pylintrc, tests/test_similar.py
This activate the duplicate checkers with a high threshold that we could progressively lower later. I think it detects a false positive with useless suppression / duplicate code when disabling using the scope of the class.
=> Activate the ``duplicate-code`` checker

pylint/config/__init__.py, pylint/utils/linterstats.py
Let's make https://github.com/PyCQA/pylint/pull/6468 reviewable 😄
=> Refactor of ``config.__init__.py``

pylint/checkers/similar.py, pylintrc
`fixme` is now in the disable list, so take it out of the enable list.
=> Remove `fixme` from enable list in our pylintrc

pylint/lint/__init__.py, pylint/lint/pylinter.py, tests/test_deprecation.py
=> Fix pylint.config's caching deprecation

tests/functional/r/regression/regression_4083_sequence_index.py
The commit from #4387 that is passing right now so we can merge it. 
Ref #4083
=> Add regression test of invalid-sequence-index false-positive

doc/data/messages/d/dict-iter-missing-items/bad.py, doc/data/messages/d/dict-iter-missing-items/good.py
=> Added dict-iter-missing-items message example

pylint/lint/message_state_handler.py, pylint/lint/pylinter.py
=> Create ``_MessageStateHandler`` and move all private methods

doc/data/messages/w/while-used/bad.py, doc/data/messages/w/while-used/good.py, doc/data/messages/w/while-used/pylintrc, doc/data/messages/w/while-used/related.rst
=> Added while-used message example

pylint/config/arguments_manager.py, tests/test_self.py
Ref. https://github.com/PyCQA/pylint/pull/6529
Fixes the issues with `toml`. For some reason locally I don't get the `"optional arguments"` section. Let's see what the CI thinks about it.
=> Make sure that --generate-toml-config generates a valid file

doc/data/messages/u/unnecessary-pass/bad.py, doc/data/messages/u/unnecessary-pass/good.py
Add `unnecessary-pass` documentation examples based on work from the `pylint-errors` project.
Partially addresses https://github.com/PyCQA/pylint/issues/5953
=> Add `unnecessary-pass` documentation examples

doc/data/messages/u/using-constant-test/bad.py, doc/data/messages/u/using-constant-test/good.py
=> Added using-constant-test message example

ChangeLog, doc/data/messages/c/consider-using-generator/bad.py, doc/data/messages/c/consider-using-generator/details.rst, doc/data/messages/c/consider-using-generator/good.py, doc/data/messages/c/consider-using-generator/related.rst, doc/whatsnew/2.14.rst, pylint/checkers/refactoring/refactoring_checker.py, tests/functional/c/consider/consider_using_generator.py, tests/functional/c/consider/consider_using_generator.txt, tests/functional/u/use/use_a_generator.py, tests/functional/u/use/use_a_generator.txt
=> Change wording of use a generator message for sum/max/min

.github/workflows/tests.yaml
Closes #4759.
Test issues discussed in that issue appear to be fixed. Still, it would be good to test `macOS` on one python version to catch potential regressions. I consider it overkill to test on all supported versions.
=> Add ``macOS`` to the test environments

requirements_test.txt
Similar to https://github.com/PyCQA/astroid/pull/1564
This fixes a performance issue with Python 3.11
=> Pin coverage to 6.3.3

doc/data/messages/i/invalid-slots-object/bad.py, doc/data/messages/i/invalid-slots-object/good.py, doc/data/messages/i/invalid-slots-object/related.rst
=> Added example for invalid-slots-object message

doc/data/messages/l/logging-too-few-args/bad.py, doc/data/messages/l/logging-too-few-args/good.py
=> Added logging-too-few-args message example

doc/data/messages/l/logging-too-many-args/bad.py, doc/data/messages/l/logging-too-many-args/good.py
=> Added logging-too-many-args message example

doc/data/messages/c/consider-using-enumerate/bad.py, doc/data/messages/c/consider-using-enumerate/details.rst, doc/data/messages/c/consider-using-enumerate/good.py
=> Add documentation examples for `consider-using-enumerate`.

doc/data/messages/c/consider-using-get/bad.py, doc/data/messages/c/consider-using-get/good.py
=> Add documentation examples for `consider-using-get`.

.pyenchant_pylint_custom_dict.txt, pylint/config/arguments_manager.py, pylint/config/callback_actions.py, pylint/config/config_initialization.py, pylint/extensions/comparetozero.py, pylint/lint/run.py
Preparation for https://github.com/PyCQA/pylint/pull/6578.
=> Refactors in preparation of ``pylint-config``

doc/data/messages/c/consider-using-in/bad.py, doc/data/messages/c/consider-using-in/good.py
=> Add documentation examples for `consider-using-in`.

doc/data/messages/c/consider-using-join/bad.py, doc/data/messages/c/consider-using-join/good.py
Addresses https://github.com/PyCQA/pylint/issues/5953
=> Add documentation examples for `consider-using-join`.

doc/Makefile, doc/exts/pylint_messages.py, doc/make.bat
Turns out there is a setting for this!
=> Run ``linkcheck`` in quiet mode

pylint/config/_pylint_config/utils.py, tests/config/pylint_config/test_pylint_config_generate.py, tests/config/pylint_config/test_pylint_config_utils.py
Blocked by https://github.com/PyCQA/pylint/pull/6634.
=> Retry user input if it is not correct

pylint/config/_pylint_config/generate_command.py, pylint/config/_pylint_config/utils.py, pylint/config/arguments_manager.py, pylint/config/callback_actions.py, tests/config/pylint_config/test_pylint_config_utils.py
=> Refactors for ``pylint-config``

.pre-commit-config.yaml, doc/exts/pylint_messages.py, pylint/checkers/__init__.py, pylint/checkers/classes/class_checker.py, pylint/checkers/refactoring/refactoring_checker.py, pylint/checkers/spelling.py, pylint/checkers/utils.py, pylint/epylint.py, pylint/extensions/_check_docs_utils.py, pylint/extensions/broad_try_clause.py, pylint/extensions/no_self_use.py
=> Update ``pydocstringformatter`` to ``0.6.0``

.pre-commit-config.yaml, pylint/checkers/base/name_checker/naming_style.py, pylint/checkers/refactoring/implicit_booleaness_checker.py, pylint/checkers/refactoring/refactoring_checker.py, pylint/checkers/similar.py, pylint/checkers/variables.py, pylint/extensions/for_any_all.py, pylint/extensions/private_import.py, pylint/graph.py
=> Enable line-wrapping from ``pydocstringformatter``

pylint/checkers/async.py, pylint/checkers/deprecated.py
=> Add typing to ``async`` and ``deprecated`` checkers

pylint/checkers/base/name_checker/checker.py, pylint/checkers/base/name_checker/naming_style.py
=> Add typing to ``name_checker``

pylint/checkers/base/comparison_checker.py
=> Add typing to ``comparison_checker``

doc/data/messages/u/unnecessary-comprehension/bad.py, doc/data/messages/u/unnecessary-comprehension/details.rst, doc/data/messages/u/unnecessary-comprehension/good.py
=> Added documentation examples for `unnecessary-comprehension`.

doc/data/messages/u/use-set-for-membership/bad.py, doc/data/messages/u/use-set-for-membership/details.rst, doc/data/messages/u/use-set-for-membership/good.py
=> Added documentation examples for `use-set-for-membership`.

doc/data/messages/c/consider-merging-isinstance/bad.py, doc/data/messages/c/consider-merging-isinstance/details.rst, doc/data/messages/c/consider-merging-isinstance/good.py
=> Added documentation examples for `consider-merging-isinstance`.

doc/data/messages/n/not-an-iterable/bad.py, doc/data/messages/n/not-an-iterable/details.rst, doc/data/messages/n/not-an-iterable/good.py
=> Adding documentation examples for `not-an-iterable`.

doc/data/messages/p/pointless-statement/bad.py, doc/data/messages/p/pointless-statement/details.rst, doc/data/messages/p/pointless-statement/good.py, doc/data/messages/p/pointless-string-statement/bad.py, doc/data/messages/p/pointless-string-statement/details.rst, doc/data/messages/p/pointless-string-statement/good.py
- `pointless-statement`
- `pointless-string-statement`
=> Added documentation examples for pointless statements

doc/data/messages/t/trailing-comma-tuple/bad.py, doc/data/messages/t/trailing-comma-tuple/details.rst, doc/data/messages/t/trailing-comma-tuple/good.py
=> Added documentation examples for `trailing-comma-tuple`.

doc/development_guide/contributor_guide/contribute.rst, doc/development_guide/contributor_guide/index.rst, doc/development_guide/contributor_guide/major_release.rst, doc/development_guide/contributor_guide/minor_release.rst, doc/development_guide/contributor_guide/patch_release.rst, doc/faq.rst, doc/user_guide/installation/index.rst, doc/user_guide/installation/upgrading_pylint.rst
=> Add documentation for the versioning scheme

.github/workflows/primer_run_main.yaml, .github/workflows/primer_run_pr.yaml, .gitignore, pylint/testutils/primer.py, tests/primer/primer_tool.py, tests/primer/test_primer_external.py
=> Move ``pylint_primer_tests`` into ``tests``

.github/workflows/primer_run_main.yaml, .github/workflows/primer_run_pr.yaml
If there are changes in bleeding-edge `astroid` that might affect a pending `pylint` PR, I think it's important to surface the issue during review.
=> Use bleeding-edge `astroid` for primer comparisons

README.rst, doc/exts/pylint_options.py, doc/faq.rst, doc/index.rst, doc/short_text_contribute.rst, doc/short_text_installation.rst, doc/user_guide/configuration/all-options.rst, doc/user_guide/messages/message_control.rst
=> Clean-up the FAQ and remove out of date questions

.github/workflows/primer_run_pr.yaml, tests/primer/packages_to_lint_batch_one.json, tests/primer/packages_to_lint_batch_two.json, tests/primer/packages_to_prime.json
Ref. https://github.com/PyCQA/pylint/pull/6723#issuecomment-1140323738
=> Add ``pytest`` to new primer and exclude some file changes

doc/exts/pylint_messages.py
=> Refactor to be able to document deleted message

.github/workflows/primer-test.yaml, tests/primer/packages_to_prime.json
Closes https://github.com/PyCQA/pylint/issues/6732.
Added the verbose mode cause I'd like to see which packages take longest to lint in the old primer.
=> Refactors related to primer

tests/primer/packages_to_lint_batch_one.json, tests/primer/packages_to_lint_batch_two.json, tests/primer/packages_to_prime.json
=> Add more packages to the new primer

doc/data/messages/n/not-callable/bad.py, doc/data/messages/n/not-callable/details.rst, doc/data/messages/n/not-callable/good.py
=> Added documentation examples for `not-callable`.

doc/data/messages/n/no-name-in-module/bad.py, doc/data/messages/n/no-name-in-module/details.rst, doc/data/messages/n/no-name-in-module/good.py
=> Added documentation examples for `no-name-in-module`.

doc/data/messages/i/invalid-all-format/bad.py, doc/data/messages/i/invalid-all-format/details.rst, doc/data/messages/i/invalid-all-format/good.py
=> Added documentation examples for `invalid-all-format`.

doc/data/messages/n/no-method-argument/bad.py, doc/data/messages/n/no-method-argument/details.rst, doc/data/messages/n/no-method-argument/good.py
=> Added documentation examples for `no-method-argument`.

doc/data/messages/n/not-in-loop/bad.py, doc/data/messages/n/not-in-loop/details.rst, doc/data/messages/n/not-in-loop/good.py
=> Added documentation examples for `not-in-loop`.

.github/workflows/primer_comment.yaml
Ref https://github.com/PyCQA/pylint/pull/6714#issuecomment-1139749640 and similar change in [1afce45](https://github.com/PyCQA/pylint/pull/6714/commits/1afce4559d410e25655b55535f7d638bf2afad8f)
=> Use `node-version` in `setup-node` action

.github/workflows/primer_comment.yaml, .github/workflows/primer_run_main.yaml, .github/workflows/primer_run_pr.yaml, tests/primer/primer_tool.py
This allows running multiple versions like we currently do, but then only commenting based on one version by downloading the correct file.
=> Add python version into the file name of output files of primer

tests/primer/packages_to_prime.json
Let's see if this helps for now?
=> Remove ``home-assistant`` from primer

doc/data/messages/r/redeclared-assigned-name/bad.py, doc/data/messages/r/redeclared-assigned-name/details.rst, doc/data/messages/r/redeclared-assigned-name/good.py
=> Added documentation examples for `redeclared-assigned-name`.

doc/data/messages/c/consider-using-tuple/bad.py, doc/data/messages/c/consider-using-tuple/details.rst, doc/data/messages/c/consider-using-tuple/good.py
=> Added documentation exmaples for `consider-using-tuple`.

doc/data/messages/i/inconsistent-return-statements/bad.py, doc/data/messages/i/inconsistent-return-statements/details.rst, doc/data/messages/i/inconsistent-return-statements/good.py
=> Added documentation examples for `inconsistent-return-statements`.

doc/data/messages/n/no-self-use/bad.py, doc/data/messages/n/no-self-use/details.rst, doc/data/messages/n/no-self-use/good.py, doc/data/messages/n/no-self-use/pylintrc
=> Added documentation examples for `no-self-use`.

pylint/checkers/base/basic_error_checker.py, pylint/checkers/base/docstring_checker.py
=> Add typing to ``basic_error_checker`` and ``docstring_checker``

doc/development_guide/contributor_guide/contribute.rst, doc/development_guide/contributor_guide/tests/index.rst, doc/development_guide/contributor_guide/tests/install.rst, doc/user_guide/checkers/features.rst
We need to merge this prior to https://github.com/PyCQA/pylint/pull/6736 and https://github.com/PyCQA/pylint/pull/6735 because #6736 will be delayed in 2.15.
=> Better documentation for contributor installation

tests/primer/primer_tool.py
We were getting far more notices about `astroid-error` on PR comments than I expected because we were comparing everything in the message, including the crash timestamp.
=> Avoid comparing timestamps in fatal messages

.github/workflows/checks.yaml, .github/workflows/primer-test.yaml, .github/workflows/primer_comment.yaml, .github/workflows/primer_run_main.yaml, .github/workflows/primer_run_pr.yaml, .github/workflows/tests.yaml
Seeing some issues with caches. Let's hope this fixes them.
=> Bump all cache versions

doc/whatsnew/2/2.14/full.rst, pylint/config/find_default_config_files.py, tests/config/test_find_default_config_files.py
Closes https://github.com/PyCQA/pylint/issues/6802.
=> Don't crash if we can't find the user's home directory

.github/CONTRIBUTING.md, README.rst
Updated link to new repository
Refs #XXXX
Closes #6793
=> Updated link in README

.pre-commit-config.yaml, pylint/checkers/base/__init__.py
Fixes the issues found in https://github.com/PyCQA/pylint/pull/6789.
=> Add disable and exclude pylint files in CI

doc/whatsnew/2/2.14/full.rst
I forgot there was a separate section for patch releases when doing #6791. 🤦🏻‍♂️
=> Move changelog to 2.14.1 for #6790 fix

doc/whatsnew/2/2.14/full.rst, pylint/extensions/private_import.py, tests/functional/ext/private_import/private_import.py
=> Fix a crash in the optional `private_import` extension

doc/data/messages/r/redefined-builtin/bad.py, doc/data/messages/r/redefined-builtin/details.rst, doc/data/messages/r/redefined-builtin/good.py
=> Add `redefined-builtin` example

doc/data/messages/u/unused-argument/bad.py, doc/data/messages/u/unused-argument/details.rst, doc/data/messages/u/unused-argument/good.py
=> Add `unused-argument` example

doc/data/messages/u/use-implicit-booleaness-not-len/bad.py, doc/data/messages/u/use-implicit-booleaness-not-len/details.rst, doc/data/messages/u/use-implicit-booleaness-not-len/good.py
Signed-off-by: harupy <hkawamura0130@gmail.com>
As the PR title says
Refs #5953
Closes #XXXX
=> Add `use-implicit-booleaness-not-len` example

doc/data/messages/u/unused-variable/bad.py, doc/data/messages/u/unused-variable/details.rst, doc/data/messages/u/unused-variable/good.py
=> Add `unused-variable` example

.pre-commit-config.yaml, doc/data/messages/t/trailing-whitespace/bad.py, doc/data/messages/t/trailing-whitespace/details.rst, doc/data/messages/t/trailing-whitespace/good.py
=> Add `trailing-whitespace` example

doc/data/messages/u/unexpected-keyword-arg/bad.py, doc/data/messages/u/unexpected-keyword-arg/details.rst, doc/data/messages/u/unexpected-keyword-arg/good.py
=> Add `unexpected-keyword-arg` example

doc/data/messages/s/single-string-used-for-slots/bad.py, doc/data/messages/s/single-string-used-for-slots/details.rst, doc/data/messages/s/single-string-used-for-slots/good.py
=> Add `single-string-used-for-slots` example

doc/data/messages/s/super-init-not-called/bad.py, doc/data/messages/s/super-init-not-called/details.rst, doc/data/messages/s/super-init-not-called/good.py
Signed-off-by: harupy <hkawamura0130@gmail.com>
Refs #5953
Closes #XXXX
=> Add `super-init-not-called` example

doc/data/messages/u/unused-format-string-argument/bad.py, doc/data/messages/u/unused-format-string-argument/details.rst, doc/data/messages/u/unused-format-string-argument/good.py
=> Add `unused-format-string-argument` example

doc/data/messages/u/unnecessary-lambda/bad.py, doc/data/messages/u/unnecessary-lambda/details.rst, doc/data/messages/u/unnecessary-lambda/good.py
Signed-off-by: harupy <hkawamura0130@gmail.com>
Refs #5953
Closes #XXXX
=> Add `unnecessary-lambda` example

doc/data/messages/e/expression-not-assigned/bad.py, doc/data/messages/e/expression-not-assigned/details.rst, doc/data/messages/e/expression-not-assigned/good.py
=> Added documentation examples for `expression-not-assigned`.

doc/data/messages/r/redefined-variable-type/bad.py, doc/data/messages/r/redefined-variable-type/details.rst, doc/data/messages/r/redefined-variable-type/good.py
=> Add `redefined-variable-type` example

doc/data/messages/f/format-needs-mapping/bad.py, doc/data/messages/f/format-needs-mapping/details.rst, doc/data/messages/f/format-needs-mapping/good.py
=> Add `format-needs-mapping` example

.pre-commit-config.yaml, doc/data/messages/t/trailing-newlines/bad.py, doc/data/messages/t/trailing-newlines/details.rst, doc/exts/pylint_messages.py
=> Add `trailing-newlines` example

doc/data/messages/k/keyword-arg-before-vararg/bad.py, doc/data/messages/k/keyword-arg-before-vararg/details.rst, doc/data/messages/k/keyword-arg-before-vararg/good.py
=> Add `keyword-arg-before-vararg` example

doc/data/messages/r/raising-non-exception/bad.py, doc/data/messages/r/raising-non-exception/details.rst, doc/data/messages/r/raising-non-exception/good.py
=> Add `raising-non-exception` example

doc/data/messages/s/subprocess-run-check/bad.py, doc/data/messages/s/subprocess-run-check/details.rst, doc/data/messages/s/subprocess-run-check/good.py
=> Add `subprocess-run-check` example

doc/data/messages/m/missing-format-attribute/bad.py, doc/data/messages/m/missing-format-attribute/details.rst, doc/data/messages/m/missing-format-attribute/good.py
=> Add `missing-format-attribute` example

doc/data/messages/f/f-string-without-interpolation/bad.py, doc/data/messages/f/f-string-without-interpolation/details.rst, doc/data/messages/f/f-string-without-interpolation/good.py
=> Add `f-string-without-interpolation` example

doc/data/messages/o/overlapping-except/bad.py, doc/data/messages/o/overlapping-except/details.rst, doc/data/messages/o/overlapping-except/good.py, doc/data/messages/o/overlapping-except/related.rst
=> Add `overlapping-except` example

doc/data/messages/r/repeated-keyword/bad.py, doc/data/messages/r/repeated-keyword/details.rst, doc/data/messages/r/repeated-keyword/good.py
=> Add `repeated-keyword` example

doc/data/messages/g/global-variable-not-assigned/bad.py, doc/data/messages/g/global-variable-not-assigned/details.rst, doc/data/messages/g/global-variable-not-assigned/good.py
=> Added documentation examples for `global-variable-not-assigned`.

doc/data/messages/g/global-variable-undefined/bad.py, doc/data/messages/g/global-variable-undefined/details.rst, doc/data/messages/g/global-variable-undefined/good.py
=> Added documentation examples for `global-variable-undefined`.

doc/data/messages/u/used-prior-global-declaration/bad.py, doc/data/messages/u/used-prior-global-declaration/details.rst, doc/data/messages/u/used-prior-global-declaration/good.py
=> Added documentation examples for `used-prior-global-declaration`.

.pre-commit-config.yaml, doc/data/messages/m/multiple-imports/bad.py, doc/data/messages/m/multiple-imports/details.rst, doc/data/messages/m/multiple-imports/good.py
=> Add `multiple-imports` example

doc/data/messages/n/no-self-argument/bad.py, doc/data/messages/n/no-self-argument/details.rst, doc/data/messages/n/no-self-argument/good.py
=> Add `no-self-argument` example

doc/data/messages/s/signature-differs/bad.py, doc/data/messages/s/signature-differs/details.rst, doc/data/messages/s/signature-differs/good.py
=> Add `signature-differs` example

doc/exts/pylint_messages.py
=> [doc] Fix the assert for placeholders following #6839

doc/data/messages/i/implicit-str-concat/bad.py, doc/data/messages/i/implicit-str-concat/details.rst, doc/data/messages/i/implicit-str-concat/good.py
=> Add `implicit-str-concat` example

doc/data/messages/d/dangerous-default-value/bad.py, doc/data/messages/d/dangerous-default-value/details.rst, doc/data/messages/d/dangerous-default-value/good.py
The `good.py` example is taken directly from the Python documentation.
`good.py` example taken from https://docs.python.org/3/reference/compound_stmts.html#function-definitions
=> Add documentation examples for `dangerous-default-value`.

doc/whatsnew/1/1.0.rst, doc/whatsnew/1/1.1.rst, doc/whatsnew/1/1.2.rst, doc/whatsnew/2/2.14/summary.rst
Refs https://github.com/PyCQA/pylint/pull/6688
=> [doc] Normalize the changelog for v1.0.0, v1.1.0 and v1.2.0

pylint/extensions/_check_docs_utils.py, pylint/extensions/broad_try_clause.py, pylint/extensions/check_elif.py, pylint/extensions/docparams.py, pylint/extensions/redefined_variable_type.py
=> Add typing to extensions

doc/data/messages/e/empty-comment/bad.py, doc/data/messages/e/empty-comment/details.rst, doc/data/messages/e/empty-comment/good.py, doc/data/messages/e/empty-comment/pylintrc, doc/data/messages/t/trailing-newlines/bad.py, doc/test_messages_documentation.py
=> Add `empty-comment` example

.github/workflows/primer_comment.yaml, .github/workflows/primer_run_main.yaml, .github/workflows/primer_run_pr.yaml, pylint/testutils/_primer/primer.py, tests/primer/__main__.py
=> Move the primer helpers from ``tests/`` to ``pylint.testutil._primer``

doc/data/messages/f/format-string-without-interpolation/bad.py, doc/data/messages/f/format-string-without-interpolation/details.rst, doc/data/messages/f/format-string-without-interpolation/good.py
=> Add `format-string-without-interpolation` example

doc/data/messages/m/mixed-format-string/bad.py, doc/data/messages/m/mixed-format-string/details.rst, doc/data/messages/m/mixed-format-string/good.py
=> Add `mixed-format-string` example

doc/data/messages/t/too-many-branches/bad.py, doc/data/messages/t/too-many-branches/details.rst, doc/data/messages/t/too-many-branches/good.py, doc/data/messages/t/too-many-branches/pylintrc
=> Add `too-many-branches` example

doc/data/messages/m/multiple-constructor-doc/bad.py, doc/data/messages/m/multiple-constructor-doc/details.rst, doc/data/messages/m/multiple-constructor-doc/good.py, doc/data/messages/m/multiple-constructor-doc/pylintrc
=> Add `multiple-constructor-doc` example

pylint/checkers/dunder_methods.py
I found a simple typo on an error about the use of `__reversed__` instead of the builtin method `reversed()`: "funciton" instead of "function".
=> Dunder methods: Fix typo in details about the error.

doc/data/messages/s/shallow-copy-environ/bad.py, doc/data/messages/s/shallow-copy-environ/details.rst, doc/data/messages/s/shallow-copy-environ/good.py
=> Add `shallow-copy-environ` example

doc/data/messages/m/misplaced-bare-raise/bad.py, doc/data/messages/m/misplaced-bare-raise/details.rst, doc/data/messages/m/misplaced-bare-raise/good.py, doc/data/messages/m/misplaced-future/details.rst
Signed-off-by: harupy <hkawamura0130@gmail.com>
Refs #5953
Closes #XXXX
=> Add `misplaced-bare-raise` example

doc/data/messages/u/useless-else-on-loop/bad.py, doc/data/messages/u/useless-else-on-loop/details.rst, doc/data/messages/u/useless-else-on-loop/good.py
=> Add `useless-else-on-loop` example

doc/data/messages/u/undefined-loop-variable/bad.py, doc/data/messages/u/undefined-loop-variable/details.rst, doc/data/messages/u/undefined-loop-variable/good.py
=> Add `undefined-loop-variable` example

doc/data/messages/c/consider-iterating-dictionary/bad.py, doc/data/messages/c/consider-iterating-dictionary/details.rst
=> Added documentation examples for `consider-iterating-dictionary`.

doc/data/messages/i/invalid-slice-index/bad.py, doc/data/messages/i/invalid-slice-index/details.rst, doc/data/messages/i/invalid-slice-index/good.py
=> Added documentation examples for `invalid-slice-index`.

doc/data/messages/b/bad-inline-option/bad.py, doc/data/messages/b/bad-inline-option/details.rst, doc/data/messages/b/bad-inline-option/good.py
=> Add `bad-inline-option` example

doc/data/messages/u/used-before-assignment/bad.py, doc/data/messages/u/used-before-assignment/details.rst, doc/data/messages/u/used-before-assignment/good.py
=> Add `used-before-assignment` example

pylint/checkers/exceptions.py, pylint/checkers/refactoring/refactoring_checker.py, pylint/checkers/spelling.py, pylint/checkers/typecheck.py, pylint/checkers/variables.py, pylint/extensions/broad_try_clause.py, pylint/extensions/docparams.py
Refs https://github.com/PyCQA/pylint/pull/6636#discussion_r891485685
=> [refactor] Make sure we have the expected typing in visitors

doc/data/messages/u/useless-super-delegation/bad.py, doc/data/messages/u/useless-super-delegation/details.rst, doc/data/messages/u/useless-super-delegation/good.py, doc/data/messages/u/useless-super-delegation/related.rst
=> Add doc example for 'useless-super-delegation'

doc/development_guide/how_tos/custom_checkers.rst
Add small code sample to custom checker documentation
=> Add small code sample to custom checker documentation

setup.cfg
After https://github.com/tartley/colorama/issues/341 has been merged we can now "fix" https://github.com/PyCQA/pylint/issues/6012.
We should pin `colorama` to this version now.
=> Pin ``colorama`` to lowest supported version

doc/whatsnew/2/2.14/full.rst, pylint/checkers/variables.py
Follow up to https://github.com/PyCQA/pylint/pull/6925#issuecomment-1153199648.
=> Fix ``undefined-loop-variable`` and ``useless-suppression``

pylint/checkers/format.py
Update docstring of `FormatChecker._check_keyword_parentheses` as it was too specific.
Refs #6226
=> Update docstring of `_check_keyword_parentheses`

doc/data/messages/s/superfluous-parens/bad.py, doc/data/messages/s/superfluous-parens/details.rst, doc/data/messages/s/superfluous-parens/good.py
Copy examples from [pylint-errors - C0325](https://vald-phoenix.github.io/pylint-errors/plerr/errors/format/C0325.html) and extend them with the case raised on #6226.
Refs #5953
Closes #6226
=> Import and extend superfluous parens examples

pylint/extensions/mccabe.py
Based on https://github.com/PyCQA/mccabe/blob/835a5400881b7460998be51d871fd36f836db3c9/mccabe.py.
I removed `node.Print` as it nog longer exists.
=> Clean up and add typing to the ``mccabe`` extension

doc/data/messages/l/logging-not-lazy/bad.py, doc/data/messages/l/logging-not-lazy/good.py, doc/data/messages/l/logging-too-few-args/bad.py, doc/data/messages/l/logging-too-few-args/good.py, doc/data/messages/l/logging-too-many-args/bad.py, doc/data/messages/l/logging-too-many-args/good.py, doc/whatsnew/1/1.8/full.rst, doc/whatsnew/2/2.12/full.rst, doc/whatsnew/2/2.12/summary.rst, doc/whatsnew/2/2.13/full.rst, doc/whatsnew/2/2.13/summary.rst
=> [doc] spelling fixes

doc/data/messages/n/nonlocal-and-global/bad.py, doc/data/messages/n/nonlocal-and-global/details.rst, doc/data/messages/n/nonlocal-and-global/good.py
=> Added documentation examples for `nonlocal-and-global`.

pylint/checkers/classes/class_checker.py, pylint/checkers/refactoring/implicit_booleaness_checker.py
Adjust some string concatenate
=> Add whitespace to some message description

pylint/checkers/base/comparison_checker.py, pylint/checkers/base/docstring_checker.py, pylint/checkers/base_checker.py, pylint/checkers/imports.py, pylint/checkers/stdlib.py
Add whitespace/punctuation to some message descriptions.
Add whitespace/punctuation to some message descriptions.
=> Add whitespace/punctuation to some message descriptions

doc/whatsnew/2/2.15/index.rst, pylint/checkers/variables.py, tests/functional/u/used/used_before_assignment.py, tests/functional/u/used/used_before_assignment.txt
=> Emit `used-before-assignment` when reimporting later in a function

doc/data/messages/b/bad-docstring-quotes/bad.py, doc/data/messages/b/bad-docstring-quotes/details.rst, doc/data/messages/b/bad-docstring-quotes/good.py, doc/data/messages/b/bad-docstring-quotes/pylintrc, doc/data/messages/b/bad-docstring-quotes/related.rst
Add documentation examples for `bad-docstring-quotes`.
Refs #5953
=> Add documentation examples for `bad-docstring-quotes`

doc/data/messages/c/consider-swap-variables/bad.py, doc/data/messages/c/consider-swap-variables/details.rst, doc/data/messages/c/consider-swap-variables/good.py
Add documentation examples for `consider-swap-variables`
Refs #5953
=> Add documentation examples for `consider-swap-variables`

doc/data/messages/i/inherit-non-class/bad.py, doc/data/messages/i/inherit-non-class/details.rst, doc/data/messages/i/inherit-non-class/good.py
Add documentation examples for `inherit-non-class`
Refs #5953
=> Add documentation examples for `inherit-non-class`

doc/data/messages/d/duplicate-except/bad.py, doc/data/messages/d/duplicate-except/details.rst, doc/data/messages/d/duplicate-except/good.py
Add documentation examples for `duplicate-except`
Refs #5953
=> Add documentation examples for `duplicate-except`

doc/data/messages/i/invalid-envvar-default/bad.py, doc/data/messages/i/invalid-envvar-default/details.rst, doc/data/messages/i/invalid-envvar-default/good.py
Add documentation examples for `invalid-envvar-default`
Refs #5953
=> Add documentation examples for `invalid-envvar-default`

doc/data/messages/i/invalid-overridden-method/bad.py, doc/data/messages/i/invalid-overridden-method/details.rst, doc/data/messages/i/invalid-overridden-method/good.py
Add documentation examples for `invalid-overridden-method`
Refs #5953
=> Add documentation examples for `invalid-overridden-method`

doc/data/messages/i/invalid-envvar-value/bad.py, doc/data/messages/i/invalid-envvar-value/details.rst, doc/data/messages/i/invalid-envvar-value/good.py
Add documentation examples for `invalid-envvar-value`
Refs #5953
=> Add documentation examples for `invalid-envvar-value`

doc/data/messages/i/invalid-sequence-index/bad.py, doc/data/messages/i/invalid-sequence-index/details.rst, doc/data/messages/i/invalid-sequence-index/good.py
Add documentation examples for `invalid-sequence-index`
Refs #5953
=> Add documentation examples for `invalid-sequence-index`

doc/data/messages/i/invalid-all-object/bad.py, doc/data/messages/i/invalid-all-object/details.rst, doc/data/messages/i/invalid-all-object/good.py, doc/data/messages/i/invalid-all-object/related.rst
Add documentation examples for `invalid-all-object`
Refs #5953
=> Add documentation examples for `invalid-all-object`

doc/data/messages/u/unhashable-dict-key/bad.py, doc/data/messages/u/unhashable-dict-key/details.rst, doc/data/messages/u/unhashable-dict-key/good.py
=> Added documentation examples for `unhashable-dict-key`.

doc/data/messages/i/invalid-sequence-index/details.rst
Fix spelling in `invalid-sequence-index` `details.rst`
Fix spelling in `invalid-sequence-index` `details.rst`
=> Fix spelling in `invalid-sequence-index` `details.rst`

doc/data/messages/i/invalid-length-returned/bad.py, doc/data/messages/i/invalid-length-returned/details.rst, doc/data/messages/i/invalid-length-returned/good.py
Add documentation examples for `invalid-length-returned`
Refs #5953
=> Add documentation examples for `invalid-length-returned`

doc/data/messages/e/exec-used/bad.py, doc/data/messages/e/exec-used/details.rst, doc/data/messages/e/exec-used/good.py, doc/data/messages/e/exec-used/related.rst, pylint/checkers/base/basic_checker.py
Add documentation examples for `exec-used`
Refs #5953
=> Add documentation examples for `exec-used`

doc/data/messages/l/logging-format-truncated/bad.py, doc/data/messages/l/logging-format-truncated/details.rst, doc/data/messages/l/logging-format-truncated/good.py
Add documentation examples for `logging-format-truncated`
Refs #5953
=> Add documentation examples for `logging-format-truncated`

doc/data/messages/m/misplaced-format-function/bad.py, doc/data/messages/m/misplaced-format-function/details.rst, doc/data/messages/m/misplaced-format-function/good.py
Add documentation examples for `misplaced-format-function`
Refs #5953
=> Add documentation examples for `misplaced-format-function`

doc/data/messages/m/method-hidden/bad.py, doc/data/messages/m/method-hidden/details.rst, doc/data/messages/m/method-hidden/good.py
Add documentation examples for `method-hidden`
Refs #5953
=> Add documentation examples for `method-hidden`

doc/data/messages/n/no-staticmethod-decorator/bad.py, doc/data/messages/n/no-staticmethod-decorator/details.rst, doc/data/messages/n/no-staticmethod-decorator/good.py
Add documentation examples for `no-staticmethod-decorator`
Refs #5953
=> Add documentation examples for `no-staticmethod-decorator`

doc/data/messages/n/no-value-for-parameter/bad.py, doc/data/messages/n/no-value-for-parameter/details.rst, doc/data/messages/n/no-value-for-parameter/good.py
Add documentation examples for `no-value-for-parameter`
Refs #5953
=> Add documentation examples for `no-value-for-parameter`

doc/data/messages/n/non-iterator-returned/bad.py, doc/data/messages/n/non-iterator-returned/details.rst, doc/data/messages/n/non-iterator-returned/good.py
Add documentation examples for `non-iterator-returned`
Refs #5953
=> Add documentation examples for `non-iterator-returned`

doc/data/messages/l/lost-exception/bad.py, doc/data/messages/l/lost-exception/details.rst, doc/data/messages/l/lost-exception/good.py
Add documentation examples for `lost-exception`
Refs #5953
=> Add documentation examples for `lost-exception`

doc/data/messages/n/non-parent-init-called/bad.py, doc/data/messages/n/non-parent-init-called/details.rst, doc/data/messages/n/non-parent-init-called/good.py
Add documentation examples for `non-parent-init-called`
Refs #5953
=> Add documentation examples for `non-parent-init-called`

doc/data/messages/n/not-async-context-manager/bad.py, doc/data/messages/n/not-async-context-manager/details.rst, doc/data/messages/n/not-async-context-manager/good.py
Add documentation examples for `not-async-context-manager`
Refs #5953
=> Add documentation examples for `not-async-context-manager`

doc/data/messages/p/protected-access/bad.py, doc/data/messages/p/protected-access/details.rst, doc/data/messages/p/protected-access/good.py
Add documentation examples for `protected-access`
Refs #5953
=> Add documentation examples for `protected-access`

doc/data/messages/n/notimplemented-raised/bad.py, doc/data/messages/n/notimplemented-raised/details.rst, doc/data/messages/n/notimplemented-raised/good.py
Add documentation examples for `notimplemented-raised`
Refs #5953
=> Add documentation examples for `notimplemented-raised`

doc/data/messages/n/not-context-manager/bad.py, doc/data/messages/n/not-context-manager/details.rst, doc/data/messages/n/not-context-manager/good.py
Add documentation examples for `not-context-manager`
Refs #5953
=> Add documentation examples for `not-context-manager`

doc/data/messages/p/property-with-parameters/bad.py, doc/data/messages/p/property-with-parameters/details.rst, doc/data/messages/p/property-with-parameters/good.py
Add documentation examples for `property-with-parameters`
Refs #5953
=> Add documentation examples for `property-with-parameters`

doc/data/messages/r/redefined-argument-from-local/bad.py, doc/data/messages/r/redefined-argument-from-local/details.rst, doc/data/messages/r/redefined-argument-from-local/good.py
Co-authored-by: Laurent Arnoud <laurent@spkdev.net>
Add documentation examples for `redefined-argument-from-local`
Refs #5953
=> Add documentation examples for `redefined-argument-from-local`

doc/data/messages/r/raising-format-tuple/bad.py, doc/data/messages/r/raising-format-tuple/details.rst, doc/data/messages/r/raising-format-tuple/good.py
Co-authored-by: Laurent Arnoud <laurent@spkdev.net>
Add documentation examples for `raising-format-tuple`
Refs #5953
=> Add documentation examples for `raising-format-tuple`

doc/data/messages/r/raising-bad-type/bad.py, doc/data/messages/r/raising-bad-type/details.rst, doc/data/messages/r/raising-bad-type/good.py, pylint/checkers/exceptions.py
Add documentation examples for `raising-bad-type`
Refs #5953
=> Add documentation examples for `raising-bad-type`

doc/data/messages/r/redundant-keyword-arg/bad.py, doc/data/messages/r/redundant-keyword-arg/details.rst, doc/data/messages/r/redundant-keyword-arg/good.py
Add documentation examples for `redundant-keyword-arg`
Refs #5953
=> Add documentation examples for `redundant-keyword-arg`

doc/data/messages/t/too-few-public-methods/bad.py, doc/data/messages/t/too-few-public-methods/details.rst, doc/data/messages/t/too-few-public-methods/good.py
Add documentation examples for `too-few-public-methods`
Refs #5953
=> Add documentation examples for `too-few-public-methods`

doc/data/messages/s/star-needs-assignment-target/bad.py, doc/data/messages/s/star-needs-assignment-target/details.rst, doc/data/messages/s/star-needs-assignment-target/good.py
Add documentation examples for `star-needs-assignment-target`
Refs #5953
=> Add documentation examples for `star-needs-assignment-target`

doc/data/messages/t/too-many-star-expressions/bad.py, doc/data/messages/t/too-many-star-expressions/details.rst, doc/data/messages/t/too-many-star-expressions/good.py
Add documentation examples for `too-many-star-expressions`
Refs #5953
=> Add documentation examples for `too-many-star-expressions`

doc/data/messages/t/too-many-boolean-expressions/bad.py, doc/data/messages/t/too-many-boolean-expressions/details.rst, doc/data/messages/t/too-many-boolean-expressions/good.py
Add documentation examples for `too-many-boolean-expressions`
Refs #5953
=> Add documentation examples for `too-many-boolean-expressions`

doc/data/messages/t/too-many-star-expressions/good.py
Missing a space in `too-many-star-expressions` example
=> Missing a space in `too-many-star-expressions` example

doc/data/messages/u/unexpected-special-method-signature/bad.py, doc/data/messages/u/unexpected-special-method-signature/details.rst, doc/data/messages/u/unexpected-special-method-signature/good.py
Add documentation examples for `unexpected-special-method-signature`
Refs #5953
=> Add documentation examples for `unexpected-special-method-signature`

doc/data/messages/u/unneeded-not/bad.py, doc/data/messages/u/unneeded-not/details.rst, doc/data/messages/u/unneeded-not/good.py
Add documentation examples for `unneeded-not`
Refs #5953
=> Add documentation examples for `unneeded-not`

tests/functional/n/no/no_member.py
=> [no-member] Add a regression test for a false positive

tests/functional/r/regression_02/regression_3866.py
=> [unused-variable] Add a regression test for a false positive

tests/functional/r/regression_02/regression_4660.py, tests/functional/r/regression_02/regression_4660.rc, tests/functional/r/regression_02/regression_4660.txt
=> [not-callable] Add a regression test for issue #4660

tests/functional/r/regression_02/regression_5801.py
Testing on all interpreter/envs.
Closes #5801
=> [struct.unpack] Add a test for a false positive no-member

.pyenchant_pylint_custom_dict.txt, doc/data/messages/n/nonexistent-operator/bad.py, doc/data/messages/n/nonexistent-operator/details.rst
Add documentation examples for `nonexistent-operator`
Refs #5953
=> Add documentation examples for `nonexistent-operator`

doc/faq.rst
`singleton-comparison` is equivalent to https://www.flake8rules.com/rules/E711.html
=> singleton-comparison is equivalent to E711

doc/data/messages/c/class-variable-slots-conflict/bad.py, doc/data/messages/c/class-variable-slots-conflict/details.rst, doc/data/messages/c/class-variable-slots-conflict/good.py
=> Added documentation examples for `class-variable-slots-conflict`.

.github/workflows/checks.yaml, .github/workflows/release.yml, .github/workflows/tests.yaml, doc/test_messages_documentation.py
=> Bump runners to ``3.10``

README.rst
Signed-off-by: Stavros Ntentos <133706+stdedos@users.noreply.github.com>
README.md: Add Discord invite/badge
=> README.md: Add Discord invite/badge

pylint/testutils/utils.py, tests/test_self.py, tests/testutils/test_testutils_utils.py
The PYTHONPATH was not restored properly.
=> Add tests and fix a bug in ``_test_environ_pythonpath``

doc/development_guide/contributor_guide/contribute.rst, doc/user_guide/configuration/all-options.rst
Links in the documentation to help triaging and labelling the backlog. In order to easily be able to do maintenance task. Closes #7101
=>  Links in the documentation to help triaging and labelling the backlog

pylint/checkers/utils.py, pylint/checkers/variables.py, pylint/pyreverse/utils.py
=> Fix typing of most inference calls

doc/development_guide/contributor_guide/contribute.rst
=> [doc] Separate false postives and bug/crashes in contributor doc

pylint/__init__.py
I think it's an official API of pylint, may as well be consistent in the code.
=> Add run_pylint, run_epylint, run_symilar, run_pyreverse explicitely in the api

pylint/testutils/_primer/primer.py, tests/testutils/_primer/test_primer.py
Something I found when troubleshooting the problem with primers in #6974
=> [primer] Fix a silent fail when no command were given

pylint/checkers/similar.py
=> [typing] Add typing to the similar checker

pylint/checkers/exceptions.py, tests/pyreverse/functional/class_diagrams/colorized_output/colorized.puml
=> Add typing to ``exceptions`` checker

doc/whatsnew/fragments/5776.false_positive, tests/functional/r/regression_02/regression_5776.py
Closes https://github.com/PyCQA/pylint/issues/5776.
Needs https://github.com/PyCQA/astroid/pull/1587.
=> Add regression test for Enum imported as alias

doc/data/messages/f/fixme/bad.py, doc/data/messages/f/fixme/details.rst, doc/data/messages/f/fixme/good.py, doc/user_guide/checkers/features.rst, doc/user_guide/configuration/all-options.rst, doc/whatsnew/2/2.14/full.rst, examples/pylintrc, examples/pyproject.toml, pylint/__pkginfo__.py, pylint/checkers/misc.py, pylint/checkers/variables.py, pylint/config/config_initialization.py, pylint/extensions/_check_docs_utils.py, tbump.toml, tests/config/test_config.py, tests/functional/ext/docparams/parameter/missing_param_doc_required_Numpy.py, tests/functional/f/fixme.py, tests/functional/f/fixme.rc, tests/functional/u/undefined/undefined_loop_variable.py, tests/functional/u/undefined/undefined_loop_variable.txt
Last release not using towncrier. The release documentation was updated.
=> Release branch 2.14.5

.github/workflows/checks.yaml, tox.ini
Closes #7188
Further info: 
https://tox.wiki/en/latest/config.html#conf-isolated_build 
https://tox.wiki/en/latest/example/package.html#packaging
=> Update tox.ini - Add `isolated_build = True`.

pylint/checkers/logging.py
=> Add typing to ``logging.py``

pylint/checkers/spelling.py
=> Add some typing to ``spelling.py``

doc/data/messages/r/raise-missing-from/related.rst
I'm guessing that it was intended to link _PEP 3134 – Exception Chaining and Embedded Tracebacks_ and not _PEP 3132 – Extended Iterable Unpacking_.
=> Fix raise-missing-from related PEP

tests/pyreverse/test_diadefs.py
This has annoyed me slightly for long enough to act.
=> [pyreverse test] Silence a deprecation warning for __implements__

doc/data/messages/c/consider-using-with/bad.py, doc/data/messages/c/consider-using-with/details.rst, doc/data/messages/c/consider-using-with/good.py, doc/data/messages/c/consider-using-with/related.rst
Following a popular question on stackoverflow (added in related).
=> [doc consider-using-with] Add the case where the file isn't even closed

setup.py
=> Remove ``setup.py``

pylint/checkers/format.py
=> Add type annotations to `format.py` module.

script/.contributors_aliases.json
| ✓   | :broom: Cleanup          |
Updating my contributor aliases.
=> bukzor: Updating my contributor aliases.

pylint/checkers/refactoring/refactoring_checker.py
=> Partial typing of ``refactoring_checker``

doc/whatsnew/fragments/7280.other, pylint/checkers/classes/class_checker.py, tests/functional/s/slots_checks.py, tests/functional/s/slots_checks.txt
Fix crash when a type-annotated `__slots__` with no value is declared.
Closes #7280
=> Fix crash when a type-annotated `__slots__` with no value is declared.

pyproject.toml
Re-name to `Homepage`. Similar config to https://github.com/pyproject-toml/pyproject-toml/blob/main/pyproject.toml#L27
Closes #7298
=> Update PyPI `Homepage` url via pyproject.toml configuration.

.github/workflows/primer_comment.yaml, .github/workflows/primer_run_main.yaml, .github/workflows/primer_run_pr.yaml
This should hopefully fix some of the flaky primer comments we have been seeing, such as in https://github.com/PyCQA/pylint/pull/7312.
By allowing the primer command to create its own `venv` we ran the risk of having different `astroid` commits being used in the `main` and `PR` job. This should hopefully fix this.
Tested on my local branch and seems to work.
=> Some primer fixes

tests/functional/r/regression_02/regression_enum_1734.py
Add regression test for crash added in https://github.com/PyCQA/astroid/pull/1734
Which was fixed in https://github.com/PyCQA/astroid/pull/1743
=> Add enum regression test

.github/workflows/primer_comment.yaml, pylint/testutils/_primer/primer_compare_command.py, pylint/testutils/_primer/primer_run_command.py
=> Some fixes to the primer

pylint/testutils/_primer/package_to_lint.py, pylint/testutils/_primer/primer_prepare_command.py
Import directly from the `git.*` modules as `gitpython` uses some import guards that `mypy` doesn't really understand. Functionally this should be the same.
=> Fix ``mypy`` issues in primer

pylint/testutils/_primer/primer_command.py, pylint/testutils/_primer/primer_compare_command.py, pylint/testutils/_primer/primer_run_command.py, tests/testutils/_primer/fixtures/message_changed/expected.txt, tests/testutils/_primer/fixtures/message_changed/expected_truncated.txt, tests/testutils/_primer/fixtures/message_changed/main.json, tests/testutils/_primer/fixtures/message_changed/pr.json, tests/testutils/_primer/fixtures/no_change/main.json, tests/testutils/_primer/fixtures/no_change/pr.json, tests/testutils/_primer/test_primer.py
Suggestion by @cdce8p. Instead of using the branch name that we prime on we use the commit that we prime on. This should make the links permanent following the normal Github scheme.
=> Use permanent links in the primer comment

.github/workflows/changelog.yml, .github/workflows/checks.yaml, .github/workflows/primer-test.yaml, .github/workflows/primer_comment.yaml, .github/workflows/primer_run_main.yaml, .github/workflows/primer_run_pr.yaml, .github/workflows/tests.yaml, pyproject.toml, requirements_test_min.txt
=> Upgrade astroid version following 2.12.3 release

tests/functional/d/deprecated/deprecated_methods_py36.rc, tests/functional/d/deprecated/deprecated_module_redundant.rc
Reverts PyCQA/pylint#7244
Refs #6632
=> Revert "[test] Temporary xfail deprecated methods py36 on pypy"

doc/whatsnew/fragments/5767.false_positive, tests/functional/d/dataclass_parameter.py, tests/functional/d/dataclass_parameter.rc
Closes #5767.
Requires fix in `astroid`: https://github.com/PyCQA/astroid/pull/1746
=> Add tests for #5767

doc/whatsnew/2/2.16/index.rst, doc/whatsnew/2/index.rst, pylint/__pkginfo__.py, tbump.toml, towncrier.toml
Follow-up to #7355, I forgot that I needed to also add the commit to bump to the dev version.
=> Bump pylint to 2.16.0-dev, update changelog

tests/functional/r/regression_02/regression_3976.py
Add a functional regression test. The original issue is no longer reproducible on the latest Pylint (2.15.0).
Refs #3976
=> Add a functional regression test.

.pre-commit-config.yaml, setup.cfg, tests/benchmark/test_baseline_benchmarks.py, tests/config/test_per_directory_config.py, tests/lint/test_pylinter.py, tests/lint/unittest_lint.py, tests/pyreverse/test_pyreverse_functional.py, tests/test_pylint_runners.py, tests/test_regr.py, tests/test_self.py
Pretty large PR, but the changes are relatively simple to review I think.
=> Add typing to some test files

pylint/checkers/classes/class_checker.py, pylint/checkers/typecheck.py, pylint/pyreverse/vcg_printer.py, pylint/typing.py, setup.cfg, tests/checkers/unittest_stdlib.py, tests/pyreverse/conftest.py, tests/pyreverse/test_diadefs.py, tests/pyreverse/test_diagrams.py, tests/pyreverse/test_inspector.py, tests/pyreverse/test_main.py, tests/pyreverse/test_writer.py, tests/test_import_graph.py, tests/test_pylint_runners.py, tests/testutils/test_output_line.py
@Pierre-Sassoulas Sorry for the size of the PR. Got a bit carried away with trying to get the additional flag to pass. This is quite a useful flag to have turned on though 🎉
=> Complete typing of all generic types

pylint/config/option.py, tests/config/unittest_config.py
=> Add typing to ``unittest_config``

.github/CODEOWNERS
This permits to automatically ask for review by the person most knowledgeable about the code. I wanted to document this but in fact there's a codified document proposed by github which is better. Except if the review is required and the contributor is not available of course.
=> Trying out codeowners configuration

tests/functional/i/invalid/invalid_name/invalid_name-module-disable.py
=> Add regression test for #3973

.github/workflows/changelog.yml, .github/workflows/checks.yaml, .github/workflows/primer-test.yaml, .github/workflows/primer_comment.yaml, .github/workflows/primer_run_main.yaml, .github/workflows/primer_run_pr.yaml, .github/workflows/tests.yaml, .pyenchant_pylint_custom_dict.txt, CONTRIBUTORS.txt, doc/whatsnew/2/2.15/index.rst, doc/whatsnew/fragments/7264.bugfix, pylint/__pkginfo__.py, pylint/lint/pylinter.py, pyproject.toml, requirements_test_min.txt, tbump.toml, tests/lint/unittest_lint.py
Too much manual changes to not make mistakes sadly :-(
=> Bump pylint to 2.15.2, update changelog

doc/exts/pylint_extensions.py, pylint/checkers/base_checker.py, pylint/checkers/imports.py, pylint/checkers/spelling.py, pylint/checkers/variables.py, pylint/config/__init__.py, pylint/config/arguments_manager.py, pylint/config/configuration_mixin.py, pylint/config/option.py, pylint/config/option_manager_mixin.py, pylint/config/option_parser.py, pylint/config/options_provider_mixin.py, setup.cfg, tests/lint/unittest_expand_modules.py, tests/pyreverse/test_utils.py, tests/reporters/unittest_reporting.py, tests/test_func.py
Once again sorry...
Without turning on the flag we get a lot of `unused ignore` warnings, but with the flag we need a PR of this size. Chicken and egg..
I think this is best reviewed in commit view, as I have tried to separate all actions.
=> Turn on ``check-untyped-defs`` in ``mypy``

tests/checkers/unittest_non_ascii_name.py, tests/checkers/unittest_unicode/unittest_bad_chars.py, tests/checkers/unittest_unicode/unittest_bidirectional_unicode.py, tests/checkers/unittest_unicode/unittest_invalid_encoding.py, tests/conftest.py, tests/test_func.py, tests/test_pylint_runners.py, tests/testutils/test_functional_testutils.py
=> Add typing to several test files

pylint/checkers/similar.py, pylint/checkers/spelling.py, pylint/config/callback_actions.py, pylint/config/deprecation_actions.py, pylint/config/option.py, pylint/config/option_manager_mixin.py, pylint/pyreverse/vcg_printer.py
=> Finish some unfinished typing signatures

pylint/checkers/base/basic_error_checker.py, pylint/checkers/classes/class_checker.py, pylint/checkers/typecheck.py, pylint/checkers/utils.py, tests/checkers/unittest_unicode/unittest_bad_chars.py, tests/checkers/unittest_unicode/unittest_functions.py, tests/config/test_functional_config_loading.py, tests/extensions/test_private_import.py, tests/lint/test_pylinter.py, tests/pyreverse/test_main.py, tests/pyreverse/test_printer.py, tests/reporters/unittest_reporting.py, tests/test_func.py
=> Finish some incomplete typing signatures

doc/exts/pylint_extensions.py, doc/exts/pylint_features.py, script/create_contributor_list.py, tests/checkers/base/unittest_base.py, tests/checkers/unittest_non_ascii_name.py, tests/checkers/unittest_spelling.py, tests/checkers/unittest_utils.py, tests/config/test_find_default_config_files.py, tests/conftest.py, tests/extensions/test_check_docs_utils.py, tests/lint/unittest_expand_modules.py, tests/message/unittest_message_definition_store.py, tests/primer/test_primer_stdlib.py, tests/profile/test_profile_against_externals.py, tests/pyreverse/test_printer_factory.py, tests/pyreverse/test_utils.py, tests/pyreverse/test_writer.py, tests/reporters/unittest_json_reporter.py, tests/reporters/unittest_reporting.py, tests/test_check_parallel.py, tests/test_func.py, tests/test_numversion.py, tests/test_self.py, tests/test_similar.py, tests/utils/unittest_ast_walker.py
=> Finish unfinished typing in non core directories

pylint/checkers/typecheck.py
=> Finish typing of ``typecheck``

pylint/checkers/variables.py
=> Finish typing of ``variables``

pylint/checkers/classes/class_checker.py, pylint/checkers/imports.py, pylint/checkers/refactoring/recommendation_checker.py, pylint/checkers/refactoring/refactoring_checker.py, pylint/checkers/similar.py, pylint/checkers/spelling.py, pylint/checkers/strings.py, pylint/config/_pylint_config/__init__.py, pylint/extensions/emptystring.py, pylint/lint/pylinter.py, tests/message/unittest_message_definition.py
=> Finish typing across the codebase

.pre-commit-config.yaml, pylint/utils/utils.py, setup.cfg
=> Add ``tomlkit`` and ``isort`` to ``mypy`` dependencies

doc/whatsnew/fragments/7457.bugfix, pylint/checkers/imports.py
=> add deprecated mailcap module

README.rst, doc/data/messages/e/exec-used/details.rst, doc/development_guide/how_tos/plugins.rst, doc/user_guide/configuration/index.rst
Closes https://github.com/PyCQA/pylint/issues/7039, Closes https://github.com/PyCQA/pylint/issues/6900, Refs https://github.com/PyCQA/pylint/issues/7478
=> A collection of documentation updates

pyproject.toml, setup.cfg
Migrate the configs into `pyproject.toml` using [`ini2toml`](https://pypi.org/project/ini2toml) to do the file conversion and running [`validate-pyproject`](https://github.com/abravalheri/validate-pyproject) to validate the results.  Skip any configuration that is not yet PEP 621 compatible (e.g. flake8).
Refs #XXXX
Closes #XXXX
=> Migrate configs for isort, mypy, and pytest into pyproject.toml

tests/functional/u/unused/unused_import.py, tests/functional/u/unused/unused_import.txt
=> Regression test for `unused-import`

doc/data/messages/i/invalid-bool-returned/bad.py, doc/data/messages/i/invalid-bool-returned/details.rst, doc/data/messages/i/invalid-bool-returned/good.py, doc/data/messages/i/invalid-bytes-returned/bad.py, doc/data/messages/i/invalid-bytes-returned/details.rst, doc/data/messages/i/invalid-bytes-returned/good.py, doc/data/messages/i/invalid-hash-returned/bad.py, doc/data/messages/i/invalid-hash-returned/details.rst, doc/data/messages/i/invalid-hash-returned/good.py, doc/data/messages/i/invalid-index-returned/bad.py, doc/data/messages/i/invalid-index-returned/details.rst, doc/data/messages/i/invalid-index-returned/good.py
Add documentation examples for invalid-index-returned, invalid-bytes-returned, invalid-bool-returned, invalid-hash-returned
Refs #5953
=> Add documentation examples for invalid-index-returned, invalid-bytes-returned, invalid-bool-returned, invalid-hash-returned

doc/conf.py, doc/user_guide/messages/messages_overview.rst
Refs #7362 fix based on https://github.com/PyCQA/pylint/issues/7362#issuecomment-1256932866 and checked on the 2.15.4 release branch.
=> Fix duplicate section erorr in sphinx for release notes of patch version

.github/workflows/changelog.yml, .github/workflows/checks.yaml, .github/workflows/primer-test.yaml, .github/workflows/primer_comment.yaml, .github/workflows/primer_run_main.yaml, .github/workflows/primer_run_pr.yaml, .github/workflows/tests.yaml, CONTRIBUTORS.txt, doc/user_guide/checkers/features.rst, doc/whatsnew/2/2.15/index.rst, doc/whatsnew/fragments/3044.bugfix, doc/whatsnew/fragments/3299.bugfix, doc/whatsnew/fragments/7003.bugfix, doc/whatsnew/fragments/7507.bugfix, doc/whatsnew/fragments/7507.other, doc/whatsnew/fragments/7522.bugfix, doc/whatsnew/fragments/7524.bugfix, doc/whatsnew/fragments/7528.bugfix, doc/whatsnew/fragments/7529.false_positive, doc/whatsnew/fragments/_template.rst, pylint/__pkginfo__.py, pylint/checkers/variables.py, pyproject.toml, requirements_test_min.txt, script/.contributors_aliases.json, tbump.toml, tests/functional/u/unused/unused_name_in_string_literal_type_annotation.py, tests/functional/u/unused/unused_name_in_string_literal_type_annotation_py38.py, tests/functional/u/unused/unused_name_in_string_literal_type_annotation_py38.txt, towncrier.toml
Draft, because I had to do some tests for #7589 and have pending code. This could be released once the new astorid version is released and upgraded.
=> Release branch 2.15.4

doc/data/messages/i/invalid-class-object/bad.py, doc/data/messages/i/invalid-class-object/details.rst, doc/data/messages/i/invalid-class-object/good.py, doc/data/messages/i/invalid-format-returned/bad.py, doc/data/messages/i/invalid-format-returned/details.rst, doc/data/messages/i/invalid-format-returned/good.py, doc/data/messages/i/invalid-getnewargs-ex-returned/bad.py, doc/data/messages/i/invalid-getnewargs-ex-returned/details.rst, doc/data/messages/i/invalid-getnewargs-ex-returned/good.py, doc/data/messages/i/invalid-getnewargs-returned/bad.py, doc/data/messages/i/invalid-getnewargs-returned/details.rst, doc/data/messages/i/invalid-getnewargs-returned/good.py, doc/data/messages/i/invalid-length-hint-returned/bad.py, doc/data/messages/i/invalid-length-hint-returned/details.rst, doc/data/messages/i/invalid-length-hint-returned/good.py
Add docs examples for various `invalid-*` messages
Refs #5953
=> Add docs for various `invalid-*` messages

doc/data/messages/i/invalid-metaclass/bad.py, doc/data/messages/i/invalid-metaclass/details.rst, doc/data/messages/i/invalid-metaclass/good.py, doc/data/messages/i/invalid-repr-returned/bad.py, doc/data/messages/i/invalid-repr-returned/details.rst, doc/data/messages/i/invalid-repr-returned/good.py, doc/data/messages/i/invalid-str-returned/bad.py, doc/data/messages/i/invalid-str-returned/details.rst, doc/data/messages/i/invalid-str-returned/good.py, doc/data/messages/i/isinstance-second-argument-not-valid-type/bad.py, doc/data/messages/i/isinstance-second-argument-not-valid-type/details.rst, doc/data/messages/i/isinstance-second-argument-not-valid-type/good.py
=> Add docs examples for invalid-* and isinstance-*

pylint/checkers/imports.py, pylint/checkers/stdlib.py
Add additional stdlib deprecations.
Reference: https://docs.python.org/3.11/whatsnew/3.11.html#deprecated
=> Add additional stdlib deprecations

doc/data/messages/m/misplaced-comparison-constant/bad.py, doc/data/messages/m/misplaced-comparison-constant/details.rst, doc/data/messages/m/misplaced-comparison-constant/good.py, doc/data/messages/m/misplaced-comparison-constant/pylintrc, doc/data/messages/m/modified-iterating-dict/bad.py, doc/data/messages/m/modified-iterating-dict/details.rst, doc/data/messages/m/modified-iterating-dict/good.py, doc/data/messages/m/modified-iterating-list/bad.py, doc/data/messages/m/modified-iterating-list/details.rst, doc/data/messages/m/modified-iterating-list/good.py, doc/data/messages/m/modified-iterating-set/bad.py, doc/data/messages/m/modified-iterating-set/details.rst, doc/data/messages/m/modified-iterating-set/good.py, doc/data/messages/m/multiple-statements/bad.py, doc/data/messages/m/multiple-statements/details.rst
=> Add docs for modified-* messages and a couple others

doc/data/messages/n/nan-comparison/bad.py, doc/data/messages/n/nan-comparison/details.rst, doc/data/messages/n/nan-comparison/good.py, doc/data/messages/n/no-classmethod-decorator/bad.py, doc/data/messages/n/no-classmethod-decorator/details.rst, doc/data/messages/n/non-ascii-module-import/bad.py, doc/data/messages/n/non-ascii-module-import/details.rst, doc/data/messages/n/non-ascii-module-import/good.py, doc/data/messages/n/non-ascii-name/bad.py, doc/data/messages/n/non-ascii-name/details.rst, doc/data/messages/n/non-ascii-name/good.py
=> Add docs for non-* and other messages

doc/data/messages/n/non-str-assignment-to-dunder-name/bad.py, doc/data/messages/n/non-str-assignment-to-dunder-name/details.rst, doc/data/messages/n/non-str-assignment-to-dunder-name/good.py, doc/data/messages/n/nonlocal-without-binding/bad.py, doc/data/messages/n/nonlocal-without-binding/details.rst, doc/data/messages/n/nonlocal-without-binding/good.py, doc/data/messages/n/not-a-mapping/bad.py, doc/data/messages/n/not-a-mapping/details.rst, doc/data/messages/n/not-a-mapping/good.py, doc/data/messages/p/possibly-unused-variable/bad.py, doc/data/messages/p/possibly-unused-variable/details.rst, doc/data/messages/p/possibly-unused-variable/good.py, doc/data/messages/p/preferred-module/bad.py, doc/data/messages/p/preferred-module/details.rst, doc/data/messages/p/preferred-module/good.py, doc/data/messages/p/preferred-module/pylintrc, doc/data/messages/r/redundant-returns-doc/bad.py, doc/data/messages/r/redundant-returns-doc/details.rst, doc/data/messages/r/redundant-returns-doc/pylintrc
=> Add doc example for various messages

README.rst
=> Replace flake8 mirror with upstream repository

script/check_newsfragments.py
Use the way `pydocstringformatter` handles console output in `script/check_newsfragments.py` to avoid `UnicodeEncodeError` on some Windows machines.
Closes #7593
=> `check_newsfragments`: Improve output on Windows machines

doc/data/messages/a/astroid-error/details.rst, doc/data/messages/a/astroid-error/good.py, doc/data/messages/c/config-parse-error/details.rst, doc/data/messages/c/config-parse-error/good.py, doc/data/messages/f/fatal/details.rst, doc/data/messages/f/fatal/good.py, doc/data/messages/m/method-check-failed/details.rst, doc/data/messages/m/method-check-failed/good.py, doc/data/messages/p/parse-error/details.rst, doc/data/messages/s/syntax-error/bad.py, doc/data/messages/s/syntax-error/good.py
Some of the time there is no good or bad example, so we need to document this in a peculiar way.
=> [doc] Document some messages where the code is not the problem

doc/tutorial.rst
There's a lot of contributor in pylint and we generally do not talk about ourselves in the documentation except in release notes.
Also updated the example and checker it worked with the latest version of pylint.
=> [doc] Less personal style for the tutorial

pylint/checkers/base/docstring_checker.py, pylint/config/argument.py
Internal refactor that renames old msg names to the new ones.
Closes #7727
=> use new msg names

doc/data/messages/r/redundant-u-string-prefix/bad.py, doc/data/messages/r/redundant-u-string-prefix/details.rst, doc/data/messages/r/redundant-u-string-prefix/good.py, doc/data/messages/r/redundant-yields-doc/bad.py, doc/data/messages/r/redundant-yields-doc/details.rst, doc/data/messages/r/redundant-yields-doc/good.py, doc/data/messages/r/redundant-yields-doc/pylintrc, doc/data/messages/s/self-cls-assignment/bad.py, doc/data/messages/s/self-cls-assignment/details.rst, doc/data/messages/s/simplifiable-condition/bad.py, doc/data/messages/s/simplifiable-condition/details.rst, doc/data/messages/s/simplifiable-condition/good.py, doc/data/messages/s/simplify-boolean-expression/bad.py, doc/data/messages/s/simplify-boolean-expression/details.rst, doc/data/messages/s/simplify-boolean-expression/good.py
=> Docs for some refactor msgs

doc/data/messages/t/too-many-function-args/bad.py, doc/data/messages/t/too-many-function-args/details.rst, doc/data/messages/t/too-many-function-args/good.py, doc/data/messages/t/too-many-try-statements/bad.py, doc/data/messages/t/too-many-try-statements/details.rst, doc/data/messages/t/too-many-try-statements/pylintrc, doc/data/messages/u/unnecessary-dict-index-lookup/bad.py, doc/data/messages/u/unnecessary-dict-index-lookup/details.rst, doc/data/messages/u/unrecognized-inline-option/bad.py, doc/data/messages/u/unrecognized-inline-option/details.rst, doc/data/messages/u/unrecognized-inline-option/good.py, doc/data/messages/u/unsubscriptable-object/bad.py, doc/data/messages/u/unsubscriptable-object/details.rst, doc/data/messages/u/unsubscriptable-object/good.py
=> Add documentation for some messages

doc/data/messages/u/unsupported-assignment-operation/bad.py, doc/data/messages/u/unsupported-assignment-operation/details.rst, doc/data/messages/u/unsupported-assignment-operation/good.py, doc/data/messages/u/unsupported-delete-operation/bad.py, doc/data/messages/u/unsupported-delete-operation/details.rst, doc/data/messages/u/unsupported-delete-operation/good.py, doc/data/messages/u/unsupported-membership-test/bad.py, doc/data/messages/u/unsupported-membership-test/details.rst, doc/data/messages/u/unsupported-membership-test/good.py, doc/data/messages/u/unused-private-member/bad.py, doc/data/messages/u/unused-private-member/details.rst, doc/data/messages/u/unused-private-member/good.py
=> Add docs for unused / unsupported msgs

doc/user_guide/checkers/extensions.rst, doc/user_guide/checkers/features.rst, tests/functional/ext/typing/typing_broken_noreturn.py
Update documentation after recent changes.
```
tox -e docs
```
=> Update documentation for checkers

doc/user_guide/installation/ide_integration/index.rst
Added link to Sublime Text integration for Pylint.
=> [doc] Add link to Sublime Text integration

tests/checkers/unittest_deprecated.py
Needed to merge https://github.com/PyCQA/pylint/pull/7809
Fixes testing deprecation warning introduced in previous PR.
=> fix end_col_offset deprecation msg

.github/workflows/backport.yml, .github/workflows/changelog.yml, .github/workflows/checks.yaml, .github/workflows/primer-test.yaml, .github/workflows/primer_run_main.yaml, .github/workflows/primer_run_pr.yaml, .github/workflows/tests.yaml
Remove changelog so we don't have to laboriously label everything "skip news" all the time. Cherry-picked to be tested in #7804 where it's going to be reviewed.
=> [github actions] Permit to launch tests when backporting on maintenance branch

tests/primer/test_primer_stdlib.py
Fixes #7832
Follow-up to #7809.
=> Catch UserWarning when linting stdlib

pylint/extensions/bad_builtin.py, pylintrc
=> Enable dict-init-mutate extension

doc/data/messages/t/too-many-nested-blocks/bad.py, doc/data/messages/t/too-many-nested-blocks/details.rst, doc/data/messages/t/too-many-nested-blocks/good.py, doc/data/messages/w/wrong-exception-operation/bad.py, doc/data/messages/w/wrong-exception-operation/details.rst, doc/data/messages/w/wrong-exception-operation/good.py
=> Add docs for a couple messages

doc/data/messages/m/method-cache-max-size-none/bad.py, doc/data/messages/m/method-cache-max-size-none/good.py
See https://github.com/PyCQA/pylint/issues/7857#issuecomment-1328800622
Refs #7857
=> [doc] clearer message for 'method-cache-max-size-none' warning

.github/workflows/checks.yaml, .pre-commit-config.yaml, README.rst
This add pyroma to pre-commit and remove the sphinx only ``ref`` from the Readme. This link is also used in the metadata and the Github's readme. It needs to be pure RST.
=> Add pyroma to pre-commit and fix the packaging's metadata

doc/whatsnew/fragments/7857.false_positive, pylint/checkers/base/name_checker/checker.py, pylint/checkers/design_analysis.py, pylint/checkers/stdlib.py, pylint/checkers/utils.py, tests/functional/m/method_cache_max_size_none.py, tests/functional/m/method_cache_max_size_none.txt
=> Fixes ``method-cache-max-size-none`` false positive 

doc/data/messages/e/eq-without-hash/bad.py, doc/data/messages/e/eq-without-hash/details.rst, doc/data/messages/e/eq-without-hash/good.py, doc/data/messages/e/eq-without-hash/pylintrc, doc/data/messages/u/useless-param-doc/bad.py, doc/data/messages/u/useless-param-doc/details.rst, doc/data/messages/u/useless-param-doc/good.py, doc/data/messages/u/useless-param-doc/pylintrc, doc/data/messages/u/useless-type-doc/bad.py, doc/data/messages/u/useless-type-doc/details.rst, doc/data/messages/u/useless-type-doc/pylintrc, doc/data/messages/u/useless-with-lock/bad.py, doc/data/messages/u/useless-with-lock/details.rst, doc/data/messages/u/useless-with-lock/good.py
=> Add more docs for messages

doc/whatsnew/fragments/7788.false_negative, pylint/checkers/refactoring/refactoring_checker.py, pylint/lint/pylinter.py, tests/functional/n/no/no_else_break.txt, tests/functional/n/no/no_else_continue.txt, tests/functional/n/no/no_else_raise.txt, tests/functional/n/no/no_else_return.py, tests/functional/n/no/no_else_return.txt, tests/functional/r/raise_missing_from.py, tests/functional/r/raise_missing_from.txt
`no else return` and `no else raise` now account for try/except/else pattern.
Closes #7788
=> 7788 no else return False Negative fix

doc/data/messages/n/no-member/details.rst
=> [no-member doc] Add generated-members documentation

doc/user_guide/configuration/all-options.rst
Due to the missing check from #6736
=> [doc] Upgrade the doc following the addition of clear-cache-post-run

pylint/extensions/while_used.py
=> update while-used doc

doc/whatsnew/fragments/5788.false_positive, pylint/checkers/refactoring/recommendation_checker.py, pylint/checkers/utils.py, tests/functional/ext/code_style/cs_consider_using_tuple.py, tests/functional/ext/code_style/cs_consider_using_tuple.txt, tests/functional/u/use/use_sequence_for_iteration.py, tests/functional/u/use/use_sequence_for_iteration.txt
=> Fix `use-sequence-for-iteration` when unpacking a set with `*`

doc/whatsnew/fragments/5636.bugfix, pylint/reporters/text.py, tests/reporters/unittest_reporting.py
=> Manual backport of #7976 following cherry-pick conflict

.github/workflows/tests.yaml, README.rst, codecov.yml, requirements_test.txt
included in the changelog. `<type>` can be one of: breaking, user_action, feature,
new_check, removed_check, extension, false_positive, false_negative, bugfix, other, internal.
If necessary you can write details or offer examples on how the new change is supposed to work.
Closes https://github.com/PyCQA/pylint/issues/6935
=> Use codecov instead of coveralls for coverage reporting

pylint/extensions/docparams.py, tests/functional/ext/code_style/cs_consider_using_namedtuple_or_dataclass.py, tests/functional/ext/code_style/cs_consider_using_namedtuple_or_dataclass.txt, tests/functional/ext/consider_ternary_expression/consider_ternary_expression.py, tests/functional/ext/consider_ternary_expression/consider_ternary_expression.rc, tests/functional/ext/consider_ternary_expression/consider_ternary_expression.txt, tests/functional/ext/docparams/docparams.py, tests/functional/ext/private_import/private_import.py, tests/functional/ext/private_import/private_import.txt
=> Cover more lines

.pre-commit-config.yaml, doc/whatsnew/fragments/6001.false_positive, pylint/checkers/classes/class_checker.py, pylint/checkers/utils.py, tests/functional/a/assigning/assigning_non_slot.py, tests/functional/a/assigning/assigning_non_slot.txt, tests/functional/a/assigning/assigning_non_slot_4509.txt
Manual backport from this PR https://github.com/PyCQA/pylint/pull/7987
=> Backport (#7987)

.github/workflows/tests.yaml
See https://github.com/codecov/codecov-action/issues/557\#issuecomment-1224970469
Astroid MR : https://github.com/PyCQA/astroid/pull/1956
=> [codecov] Use our own token to avoid being rate limited

CONTRIBUTORS.txt, doc/user_guide/checkers/features.rst, doc/user_guide/configuration/all-options.rst, doc/user_guide/messages/messages_overview.rst, doc/whatsnew/2/2.16/index.rst, examples/pylintrc, examples/pyproject.toml, pylint/__pkginfo__.py, script/.contributors_aliases.json, tbump.toml
Time to release the beta branch to get some feedback (without the latest astroid for now) ?
=> Release branch 2.16.0-b0

.github/workflows/primer_comment.yaml, .github/workflows/primer_run_pr.yaml
Fix Primer PR failures due to unauthenticated rest context.
Recent failure: https://github.com/PyCQA/pylint/actions/runs/3960216324/jobs/6784064073#step:8:64
https://github.com/actions/github-script#actionsgithub-script
=> [ci] Use pre-authenticated context for Primer PR

pylint/checkers/base_checker.py, pylint/checkers/classes/special_methods_checker.py, pylint/checkers/typecheck.py, tests/checkers/unittest_base_checker.py, tests/functional/n/non/non_iterator_returned.py
This is PR with small code coverage increase. Each commit is a separate issue handling of either adding a test to increase coverage or remove code that's clearly unused.
=> Add tests to improve coverage

doc/whatsnew/fragments/8120.false_positive, pylint/extensions/redefined_variable_type.py, tests/functional/ext/redefined_variable_type/redefined_variable_type.py
=> Fix a false positive for ``redefined-variable-type`` when ``async`` methods are present.

.github/workflows/changelog.yml, .github/workflows/checks.yaml, .github/workflows/primer-test.yaml, .github/workflows/primer_run_main.yaml, .github/workflows/primer_run_pr.yaml, .github/workflows/tests.yaml, requirements_test_pre_commit.txt
Similar to https://github.com/PyCQA/astroid/pull/1993
* Include `requirements_test_pre_commit.txt` in the cache key whenever `requirements_test.txt` is installed.
* Limit `flake8` and `isort` to  Python `>=3.8`.
=> Fix dev requirements

pylint/lint/utils.py
Print this error to stderr instead of stdout, otherwise it produces invalid formatted outputs.
This is similar to https://github.com/PyCQA/pylint/issues/6597, please let me know if you want me to file a separate issue.
=> Print this error to stderr instead of stdout.

doc/whatsnew/fragments/8119.bugfix, pyproject.toml, requirements_test_min.txt, tests/functional/a/alternative/alternative_union_syntax_error.rc, tests/functional/a/alternative/alternative_union_syntax_regession_8119.py, tests/functional/a/alternative/alternative_union_syntax_regession_8119.rc, tests/functional/w/wrong_exception_operation.rc, tests/functional/w/wrong_exception_operation_py37.py, tests/functional/w/wrong_exception_operation_py37.rc, tests/functional/w/wrong_exception_operation_py37.txt
Add regression tests for new typing Union syntax.
Bump astroid to `2.13.4`.
Requires https://github.com/PyCQA/astroid/pull/1977
Closes #8119
=> Fix issues with new typing Union syntax (Py310)

doc/user_guide/checkers/features.rst, doc/whatsnew/fragments/5073.other, pylint/checkers/variables.py, tests/functional/g/globals.py, tests/functional/g/globals.txt, tests/functional/r/regression/regression___file___global.txt, tests/functional/u/unused/unused_variable.txt
Update explanation for ``global-variable-not-assigned`` and add inference.
Closes #5073
=> Update docs for `global-variable-not-assigned`

doc/user_guide/checkers/features.rst, pylint/checkers/variables.py
Fix grammatical error in explanation of `global-statement (W0603)`.
=> docs: fix grammatical error

doc/data/messages/u/using-f-string-in-unsupported-version/details.rst
Small amendment to https://github.com/PyCQA/pylint/pull/8157 with a slightly different text.
=> Small documentation update for `using-f-string-in-unsupported-version`.

doc/data/messages/f/forgotten-debug-statement/bad.py, doc/data/messages/f/forgotten-debug-statement/details.rst, doc/data/messages/l/locally-disabled/bad.py, doc/data/messages/l/locally-disabled/details.rst, doc/data/messages/t/too-many-statements/bad.py, doc/data/messages/t/too-many-statements/details.rst, doc/data/messages/t/too-many-statements/good.py, doc/data/messages/t/too-many-statements/pylintrc
Follow-up to #8185 that had an unexpected issue I'll fix later.
=> Another batch of doc example

.github/workflows/primer-test.yaml, .github/workflows/primer_comment.yaml, .github/workflows/primer_run_main.yaml, .github/workflows/primer_run_pr.yaml, pylint/testutils/_primer/package_to_lint.py
I think poetry core is not available in the cached image following #8193 .
=> [primer] Fix primer on main after adding poetry-core

.pre-commit-config.yaml, doc/data/messages/m/missing-final-newline/bad.py, doc/data/messages/m/missing-final-newline/details.rst, doc/data/messages/m/missing-final-newline/good.py, doc/data/messages/m/missing-final-newline/related.rst
Add doc for `missing-final-newline / C0304`.
Refs #5953
=> add doc for message missing-final-newline / C0304

.pre-commit-config.yaml, pylint/checkers/logging.py, pylint/checkers/variables.py, pylint/config/argument.py, pylint/config/option_parser.py, pyproject.toml, requirements_test_pre_commit.txt, tests/checkers/unittest_utils.py, tests/lint/unittest_lint.py, tests/test_func.py
I removed only flake8-bugbear because I'm not sure everything in flake8 is implemented yet. But it's going to be nice to get rid of the setup.cfg when it is.
=> [pre-commit] Add ruff to pre commit

doc/data/messages/b/bad-mcs-classmethod-argument/bad.py, doc/data/messages/b/bad-mcs-classmethod-argument/details.rst, doc/data/messages/b/bad-mcs-classmethod-argument/good.py, doc/data/messages/b/bad-mcs-method-argument/bad.py, doc/data/messages/b/bad-mcs-method-argument/details.rst, doc/data/messages/b/bad-mcs-method-argument/good.py, doc/data/messages/d/differing-param-doc/bad.py, doc/data/messages/d/differing-param-doc/details.rst, doc/data/messages/d/differing-param-doc/pylintrc, doc/data/messages/d/differing-type-doc/bad.py, doc/data/messages/d/differing-type-doc/details.rst, doc/data/messages/d/differing-type-doc/good.py, doc/data/messages/d/differing-type-doc/pylintrc, doc/data/messages/d/docstring-first-line-empty/bad.py, doc/data/messages/d/docstring-first-line-empty/details.rst, doc/data/messages/d/docstring-first-line-empty/pylintrc, doc/data/messages/i/inconsistent-mro/bad.py, doc/data/messages/i/inconsistent-mro/details.rst
Supersedes https://github.com/PyCQA/pylint/pull/8182
Let's not let this work go to waste, but also let's not keep reviewing a PR with 140 commits for 6 doc examples.
=> Add documentation examples

.github/CONTRIBUTING.md, README.rst, doc/conf.py, doc/development_guide/how_tos/custom_checkers.rst, doc/whatsnew/2/2.9/summary.rst, pylint/message/_deleted_message_ids.py, pyproject.toml, tests/functional/b/bad_option_value.txt
I also added ruff to pre-commit in #8197 , might as well follow our own dog food's advice. Result can be seen here : https://github.com/Pierre-Sassoulas/pylint/tree/upgrade-readme
=> [readme] Add 'ruff', install at the top, paragraph title to permit skimming

doc/data/messages/u/unused-format-string-key/bad.py, doc/data/messages/u/unused-format-string-key/details.rst, doc/data/messages/u/unused-format-string-key/good.py
Add doc for unused-format-string-key / W1301.
Refs #5953
=> add doc for message unused-format-string-key

doc/data/messages/t/too-many-public-methods/bad.py, doc/data/messages/t/too-many-public-methods/details.rst, doc/data/messages/t/too-many-public-methods/pylintrc, doc/data/messages/t/too-many-public-methods/related.rst
Refs #5953, the design check are not easy to document for beginner in a way that illustrate the rational.
=> [too-many-public-methods] Add an example for the message

doc/development_guide/how_tos/custom_checkers.rst
Add missing import to example test
=> Add missing import to example test

doc/data/messages/u/use-sequence-for-iteration/bad.py, doc/data/messages/u/use-sequence-for-iteration/details.rst, doc/data/messages/u/use-sequence-for-iteration/good.py
Add doc for use-sequence-for-iteration / C0208.
Refs #5953
=> add doc for message use-sequence-for-iteration

doc/data/messages/u/use-symbolic-message-instead/bad.py, doc/data/messages/u/use-symbolic-message-instead/details.rst, doc/data/messages/u/use-symbolic-message-instead/good.py, doc/data/messages/u/useless-suppression/bad.py, doc/data/messages/u/useless-suppression/details.rst, doc/data/messages/u/useless-suppression/good.py
Add doc for use-symbolic-message-instead / I0023 and useless-suppression / I0021
Refs #5953
=> doc for inline message suppression

doc/data/messages/b/boolean-datetime/bad.py, doc/data/messages/b/boolean-datetime/details.rst, doc/data/messages/b/boolean-datetime/good.py, doc/data/messages/b/boolean-datetime/pylintrc, doc/data/messages/b/boolean-datetime/related.rst, doc/data/messages/u/unsupported-binary-operation/bad.py, doc/data/messages/u/unsupported-binary-operation/details.rst, doc/data/messages/u/unsupported-binary-operation/good.py, doc/data/messages/u/unsupported-binary-operation/pylintrc
Add doc for unsupported-binary-operation / E1131 and boolean-datetime / W1502
Refs #5953
=> Doc unsupported-binary-operation, boolean-datetime

doc/exts/pylint_messages.py, doc/test_messages_documentation.py, examples/custom.py, examples/custom_raw.py, pylint/checkers/classes/class_checker.py
Trying to use the latest typing everywhere.
=> [typing] Use __future__ annotations where possible

pyproject.toml, requirements_test_min.txt, tests/functional/r/regression_02/regression_8109.py, tests/functional/r/regression_02/regression_8109.txt
Also add regression test for #8109
=> Upgrade astroid to 2.14.2

doc/data/messages/i/import-self/bad.py, doc/data/messages/i/import-self/details.rst, doc/data/messages/i/import-self/good.py
=> [doc] Do not use real code for 'self-import'

doc/user_guide/usage/run.rst
=> Add documentation for adding Pylint configuration to ``tox.ini``.

doc/data/messages/t/too-many-locals/bad.py, doc/data/messages/t/too-many-locals/details.rst, doc/data/messages/t/too-many-locals/good.py, doc/data/messages/t/too-many-locals/pylintrc, tests/functional/t/too/too_many_locals.py
=> [doc] Add an example for 'too-many-locals'

.github/PULL_REQUEST_TEMPLATE.md, doc/development_guide/contributor_guide/contribute.rst
=> [PR documentation] Add advice to keep the pull requests small

script/.contributors_aliases.json
Updating my entry in CONTRIBUTORS.txt following-on-from #7939.
=> Update self in .contributors_aliases.json

doc/data/messages/i/invalid-name/details.rst, doc/user_guide/checkers/features.rst, doc/whatsnew/fragments/7081.feature, pylint/checkers/bad_chained_comparison.py, pylint/checkers/base/name_checker/checker.py, pylint/checkers/base/name_checker/naming_style.py, pylint/constants.py, pylint/utils/linterstats.py, tests/functional/ext/typing/typing_broken_callable.py, tests/functional/ext/typing/typing_broken_callable_deprecated_alias.py, tests/functional/ext/typing/typing_broken_callable_future_import.py, tests/functional/ext/typing/typing_broken_noreturn.py, tests/functional/ext/typing/typing_broken_noreturn.txt, tests/functional/ext/typing/typing_broken_noreturn_future_import.py, tests/functional/ext/typing/typing_broken_noreturn_future_import.txt, tests/functional/ext/typing/typing_broken_noreturn_py372.py, tests/functional/r/regression_02/regression_3979.py, tests/functional/t/typealias_naming_style_default.py, tests/functional/t/typealias_naming_style_default.rc, tests/functional/t/typealias_naming_style_default.txt, tests/functional/t/typealias_naming_style_rgx.py, tests/functional/t/typealias_naming_style_rgx.rc, tests/functional/t/typealias_naming_style_rgx.txt, tests/lint/test_caching.py
=> Add ``invalid-name`` check for ``TypeAlias`` names

doc/whatsnew/fragments/7343.feature, pylint/checkers/classes/class_checker.py, tests/functional/p/protected_access.py, tests/functional/p/protected_access.rc, tests/functional/p/protected_access.txt
=> Accept values of the form ``<class name>.<attribute name>`` for the `exclude-protected` list

doc/development_guide/contributor_guide/release.md, doc/whatsnew/3/index.rst
The branch is protected, and the branch settings need to be conserved.
=> [release documentation] Upgrade for post release branch deletion

doc/whatsnew/fragments/5488.other, pyproject.toml
Supersedes https://github.com/PyCQA/pylint/pull/7115.
Closes https://github.com/PyCQA/pylint/issues/2079, closes https://github.com/PyCQA/pylint/issues/5488
=> Add and expose ``py.typed``

doc/development_guide/contributor_guide/release.md
=> [release doc] Add a paragraph for label maintenance

pylint/lint/pylinter.py
Forgotten from another deprecation removal ?
=> Remove some useless assertions in pylint 3.0

pylint/checkers/variables.py, pylint/reporters/json_reporter.py, pylint/testutils/functional/test_file.py
Work in progress to discuss #8335 for 3.0.0a6
Closes #8335
=> Upgrade TODO from pylint 2.x to pylint 3.0

pylint/checkers/imports.py
Fixes incompatibility with current `main` of `astroid`.
=> Don't use removed function from ``astroid``

pylint/checkers/base/basic_checker.py, pylint/checkers/nested_min_max.py, pylint/checkers/typecheck.py, pylint/pyreverse/diagrams.py, pyproject.toml, requirements_test_min.txt, tests/pyreverse/test_printer.py
Pin the first pre-release of astroid: `3.0.0a1`.
_This PR should **not** be backported._
=> Bump astroid to 3.0.0a1

doc/whatsnew/2/2.17/index.rst, doc/whatsnew/fragments/8632.bugfix, tests/pyreverse/data/classes_No_Name.vcg, tests/pyreverse/data/packages_No_Name.vcg
=> Merge maintenance 2.17.x in main

tests/primer/packages_to_prime.json
There is an [AssertionError](https://github.com/pylint-dev/pylint/actions/runs/4945892156/jobs/8843239956#step:9:148) in the CI primer workflow because one of the package URLs has `.git` at the end.
```python
[47](https://github.com/pylint-dev/pylint/actions/runs/4945892156/jobs/8843239956#step:9:48)
File "/home/runner/work/pylint/pylint/tests/primer/__main__.py", line 17, in <module>
[48](https://github.com/pylint-dev/pylint/actions/runs/4945892156/jobs/8843239956#step:9:49)
primer.run()
[49](https://github.com/pylint-dev/pylint/actions/runs/4945892156/jobs/88432 …
```
=> Primer - remove `.git` suffix from github URL.

.github/workflows/stale.yml
See https://github.com/pylint-dev/pylint/actions/runs/5151077313/jobs/9275908461#step:2:4298
=> [stale issue CI] Permit to write comment on stale pull requests

pyproject.toml, requirements_test_min.txt
Upgrade astroid following release of 3.0.0a5
=> Upgrade astroid to 3.0.0a5

doc/whatsnew/fragments/8830.false_positive, pylint/checkers/classes/class_checker.py, tests/functional/i/invalid/invalid_enum_extension.py, tests/functional/i/invalid/invalid_enum_extension.txt
=> Exempt parents with only annotations from `invalid-enum-extension`

doc/data/messages/u/unnecessary-pass/bad.py, doc/data/messages/u/unnecessary-pass/good.py, doc/user_guide/checkers/features.rst, pylint/checkers/base/pass_checker.py
Documentation - Update `unnecessary-pass` description and examples to be more specific.
Refs #8874
=> Documentation - Update `unnecessary-pass`

.github/workflows/checks.yaml, .github/workflows/primer-test.yaml, .github/workflows/primer_run_main.yaml, .github/workflows/primer_run_pr.yaml, .github/workflows/tests.yaml, doc/development_guide/contributor_guide/tests/install.rst, pyproject.toml, requirements_test_min.txt, tests/test_check_parallel.py
=> Avoid editable installs on CI

doc/whatsnew/fragments/8558.feature
Intended to be removed when renamed in
570e40d634e97bdd0c70c796b7b11da15bff0e3f.
=> Remove duplicate fragment

doc/whatsnew/fragments/2018.user_action, towncrier.toml
=> Fix news fragment indentation

.github/workflows/tests.yaml
Follow-up to f8c94781f69a82be1d17488f2418af2f16fd53cb.
=> Fix invocation of tests on pypy

doc/requirements.txt, pylint/checkers/stdlib.py, pyproject.toml, requirements_test_min.txt
=> Bump astroid to 3.0.0a9

pylint/checkers/refactoring/refactoring_checker.py, tests/functional/s/simplifiable/simplifiable_condition.py, tests/functional/s/simplifiable/simplifiable_condition.txt, tests/functional/s/simplifiable/simplifiable_if_expression.py, tests/functional/s/simplifiable/simplifiable_if_expression.txt, tests/functional/s/simplifiable/simplifiable_if_statement.py, tests/functional/s/simplifiable/simplifiable_if_statement.txt
Change that was rotting locally because I wanted to use it to test a better diff in the primer.
=> [simplifiable-if-expression] Better formatting for python single quotes

doc/data/messages/a/anomalous-backslash-in-string/details.rst, doc/exts/pylint_options.py, doc/user_guide/configuration/all-options.rst
Required for #6736, depends on #8949
=> [doc] Add the possibility to set dynamic values in doc

.gitattributes, doc/data/messages/m/mixed-line-endings/bad.py, doc/data/messages/m/mixed-line-endings/details.rst, doc/data/messages/m/mixed-line-endings/good.py, doc/data/messages/m/mixed-line-endings/good/full_crlf.py, doc/data/messages/m/mixed-line-endings/good/full_lf.py, doc/data/messages/m/mixed-line-endings/related.rst, doc/data/messages/u/unexpected-line-ending-format/bad.py, doc/data/messages/u/unexpected-line-ending-format/good.py
=> [mixed-line-endings] Create the initial documentation

doc/data/messages/r/relative-beyond-top-level/bad.py, doc/data/messages/r/relative-beyond-top-level/details.rst, doc/data/messages/r/relative-beyond-top-level/good.py, doc/data/messages/r/relative-beyond-top-level/good/absolute_import.py, doc/data/messages/r/relative-beyond-top-level/good/fix_the_relative_import.py, doc/data/messages/r/relative-beyond-top-level/related.rst
Refs #7897, no need to suffer too much, a comment in good.py is good enough imo. Might be blocked by #8991
=> [relative-beyond-top-level] Create the initial documentation

doc/data/messages/d/differing-param-doc/bad.py, doc/data/messages/d/differing-param-doc/good.py, doc/data/messages/d/differing-type-doc/bad.py, doc/data/messages/d/differing-type-doc/good.py, doc/data/messages/f/fixme/bad.py, doc/data/messages/f/fixme/details.rst, doc/data/messages/f/fixme/good.py, doc/data/messages/f/fixme/good/bug_tracker.py, doc/data/messages/f/fixme/good/fixed.py, doc/data/messages/f/fixme/good/no_fix.py, doc/data/messages/f/format-combined-specification/good.py, doc/data/messages/f/format-combined-specification/good/index_formatting.py, doc/data/messages/f/format-combined-specification/good/order_formatting.py, doc/data/messages/t/too-many-lines/bad.py
Follow-up to #9006 
Refs #5953
=> [doc] Use the new multiple file template for ``D <= message-symbol < I``

doc/data/messages/t/too-few-public-methods/good/dataclass_and_function.py, doc/data/messages/t/too-few-public-methods/good/function.py, doc/data/messages/t/too-few-public-methods/good/larger_api.py, doc/data/messages/t/try-except-raise/good/remove_try_except.py, doc/data/messages/t/try-except-raise/good/specialized_exception.py, doc/data/messages/u/unnecessary-lambda/bad/pandas.py, doc/data/messages/u/unnecessary-lambda/bad/print.py, doc/data/messages/u/unnecessary-lambda/good/pandas.py, doc/data/messages/u/unnecessary-lambda/good/print.py, doc/data/messages/u/unnecessary-negation/bad/double_not.py, doc/data/messages/u/unnecessary-negation/bad/equivalent_comparator_exists.py, doc/data/messages/u/unnecessary-negation/good/double_not.py, doc/data/messages/u/unnecessary-negation/good/equivalent_comparator_exists.py, doc/data/messages/u/unused-format-string-argument/good/add_format_target.py, doc/data/messages/u/unused-format-string-argument/good/remove_unused_args.py, doc/data/messages/u/use-sequence-for-iteration/good.py, doc/data/messages/u/use-sequence-for-iteration/good/list.py, doc/data/messages/u/use-sequence-for-iteration/good/tuple.py
=> [doc] Use the new multiple file template for ``T <= message-symbol < Z``

tests/pyreverse/functional/class_diagrams/aggregation/fields.mmd, tests/pyreverse/functional/class_diagrams/aggregation/fields.py
| ✓   | :test_tube: Test        |
Add test for #9045
=> Add test for aggregation issue

doc/whatsnew/fragments/8862.breaking
=> Add release note for `PYLINTRC` removal

README.rst
May as well fix, but no way I'm going to cause hours of linux runner time over it 😄 .
=> [skip ci] Remove typo in README

doc/whatsnew/2/2.17/index.rst
We're going to delete the maintenance/2.17.x branch after that.
=> Merge maintenance 2.17.x into main

pyproject.toml
The “What's New” project link at https://pypi.org/project/pylint/ currently points to v2.  This PR changes that to pointing to v3.
=> Let “What's New” URL point to version 3

.readthedocs.yaml
I merged without checking all the fail in the 3.12 upgrade (#9092) because primers were expected to fail.
=> [readthedoc] Upgrade the ubuntu image, downgrade the python interpreter

doc/exts/pylint_messages.py, doc/exts/pylint_options.py
=> Add a disclaimer for informational message

doc/whatsnew/fragments/9167.false_positive
=> [doc] Add a changelog for #9167

.github/workflows/primer_run_main.yaml
Follow-up to #9324
Refs https://github.com/pylint-dev/pylint/actions/runs/7315247260/job/19928699828
=> Fix uploading of commit string artifact

pylint/testutils/_primer/primer_run_command.py
=> Use short python version (X.Y) in primer output

.github/workflows/primer_comment.yaml
Sorry for drip, drip, drip 💧.
Follow-up to 5af984a.
=> Fix compare output step

doc/data/messages/u/use-dict-literal/related.rst
> tl;dr
> The {} is always faster than dict.
=> [doc] Add an article about performance related to ``use-dict-literal``

pylint/checkers/dunder_methods.py, pylint/extensions/dunder.py
The concept of checker priority [was removed](https://github.com/pylint-dev/pylint/commit/e01fa86c00b2cd879c44570b383115a9407547f1) in [Pylint 2.14.0](https://pylint.readthedocs.io/en/v3.0.3/whatsnew/2/2.14/full.html#what-s-new-in-pylint-2-14-0).
=> Remove leftover checker priority

MANIFEST.in
Closes #9263
Modeled on [Django's example](https://github.com/django/django/blob/main/MANIFEST.in)
**Test**
```py
rm -r dist
rm -r pylint.egg-info
python3 -m build
cd dist
tar -xzf pylint-3.1.0.dev0.tar.gz
cd pylint-3.1.0.dev0 
ls -a
ls -a tests
```
**Before**
```
% ls -a
.                       LICENSE                 README.rst              pyproject.toml
..                      MANIFEST.in             pylint                  setup.cfg
CONTRIBUTORS.txt        PKG-INFO                pylint.egg-info         tests
% ls -a tests
.                               test_functional_directories.py  test_regr.py
..                              test_import_graph.py            test_self.py …
```
=> Include tests, docs with sdist

doc/user_guide/checkers/extensions.rst, pylint/extensions/confusing_elif.py
=> fix a docs typo

MANIFEST.in
=> Include test requirements with sdist

doc/whatsnew/fragments/3501.feature, pylint/checkers/utils.py, tests/checkers/unittest_utils.py
=> checkers.utils.is_sys_guard: understands six.PY2 or six.PY3

doc/conf.py
https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-master_doc
=> replace deprecated m*ster_doc with root_doc

tests/functional/r/regression_02/regression_node_statement.py, tests/functional/r/regression_02/regression_node_statement_two.py
=> fix pandas-dev main branch name

tests/functional/r/regression_02/regression_4126.py, tests/functional/r/regression_02/regression_4126.rc
=> [pypy] Add a regression test for 'import array' false positive

doc/whatsnew/3/3.2/index.rst
See https://github.com/pylint-dev/pylint/actions/runs/9668507699/job/26672818926 and https://github.com/pypa/twine/issues/1125
=> [release] Fix 3.2.4's release date following twine 5.1.0's issues

doc/whatsnew/3/3.0/index.rst
Hello,
This is my first PR so I apologize if there are any issues. This PR normally solves the issue (simply changing the word "checker" to "message"). 
Best reagrds,
Noah
=> Updating minor error in the changelog

pylint/utils/ast_walker.py
The related code was removed in 98c887de0:
https://github.com/pylint-dev/pylint/commit/98c887de000457ea084d799f16dbb564975c8aca#diff-ba25626db7fb419aa5d731ec1abd5d10f2e4236aa04167669429e7c040832713L921-L925
=> Remove obsolete comment from ASTWalker.walk

.github/workflows/tests.yaml
See breaking changes from upload-artifact 4.4.0 described in https://github.com/pylint-dev/pylint/pull/9907#issue-2501019127.
=> Fix coverage uploads

doc/whatsnew/3/3.3/index.rst
Refs https://github.com/pylint-dev/pylint/issues/9791#issuecomment-2375086078
=> Fix release note typo

pyproject.toml, requirements_test_min.txt
=> Bump astroid to 3.3.5

doc/data/messages/b/bare-except/related.rst
Those in favor of PEP760 can always use pylint 😄
=> [bare-except doc] Add PEP760 and discussion around it in related links

doc/additional_tools/pyreverse/configuration.rst, pylint/pyreverse/main.py
Follow up to #10200
Updates documentation for --max-depth option to reflect the new behavior.
=> Update pyreverse documentation

.github/workflows/release.yml, doc/whatsnew/fragments/10256.other, examples/pylintrc, examples/pyproject.toml, pylint/__pkginfo__.py, tbump.toml, towncrier.toml
Permits to test the new trusted publisher release process.
=> Release branch 3.3.5a0

.pre-commit-config.yaml, doc/whatsnew/fragments/10296.other
* https://validate-pyproject.readthedocs.io
* https://github.com/abravalheri/validate-pyproject
=> pre-commit: Add validate-pyproject

pyproject.toml
=> [setuptools] Force the upgrade of setuptools > 77

doc/data/messages/d/docstring-first-line-empty/bad.py
This PR updates the "problematic code" sample for the `docstring-first-line-empty` warning to make it clearer which line is causing the issue. The original sample had two empty lines at the top of the docstring, which led to confusion.
[Current "Problematic code" sample](https://pylint.readthedocs.io/en/latest/user_guide/messages/convention/docstring-first-line-empty.html):
Clarifies the example for a better understanding of the `docstring-first-line-empty` warning, especially for new users or contributors.
Refs #10337
Closes #10337
=> Fix ambiguous docstring example for docstring-first-line-empty warning

doc/whatsnew/fragments/10334.bugfix, pylint/checkers/deprecated.py, pylint/checkers/utils.py, tests/functional/r/regression_02/regression_10334.py, tests/functional/r/regression_02/regression_10334.txt
=> Backport: Manual cherry pick for decorator slice crash fix

.github/workflows/checks.yaml, .github/workflows/primer-test.yaml, .github/workflows/primer_run_main.yaml, .github/workflows/primer_run_pr.yaml, .github/workflows/tests.yaml
=> [ci] Install pylint before every test (#10388)

doc/data/messages/u/unnecessary-dunder-call/related.rst
=> Add a related link for ``unnecessary-dunder-call``

.github/workflows/checks.yaml, .github/workflows/primer-test.yaml, .github/workflows/tests.yaml
The linux job was renamed in https://github.com/pylint-dev/pylint/pull/10299.
=> Fix cache keys [ci]

tests/test_self.py
Fixed unreachable assertions in test_errors_only and test_verbose test methods.
Closes #10450
=> Fix unreachable assertions in test_errors_only and test_verbose test method #10450

pyproject.toml
Reverts pylint-dev/pylint#10342 who itself reverted https://github.com/pylint-dev/pylint/pull/10332
=> Re-apply "Add dependency groups to pyproject.toml file"

pylint/testutils/_primer/package_to_lint.py
=> [primer] Use a dataclasse for PackageToLint

pylint/checkers/base/basic_error_checker.py, pylint/checkers/base/docstring_checker.py, pylint/checkers/classes/class_checker.py, pylint/checkers/refactoring/refactoring_checker.py, pylint/checkers/variables.py
Went through my match changes I had prepared initially. These were the last ones which are a clear improvement at this time. Will do a cleanup pass with all notes from the other match PRs after this one.
=> Use match statement in checkers (7)

pyproject.toml, tox.ini
Add Python 3.14 to Trove classifiers and tox.ini.
Follow on from https://github.com/pylint-dev/pylint/pull/10467.
=> Add support for Python 3.14

doc/whatsnew/3/3.3/index.rst
=> Fix invalid refs in 3.3 whatsnew
