doc/whatsnew/fragments/7461.bugfix
pylint/checkers/modified_iterating_checker.py
tests/functional/m/modified_iterating.py

Closes #7461
As of bcd4ca3052411e8c0823712d38cb970e354713f6 we know that the `iter_obj` is a `Name` or an `Attribute`, so tighten the typing.

Fix a crash in the `modified-iterating-dict` checker involving instance attributes

---

pylint/config/utils.py

Since this is called a few frame levels inside Pylint, providing the context of what optdict= can help with finding where the option originally comes from.
This is a follow-up to #7465
| ✓   | Maintenance          |
This improves the deprecation warnings similar to #7463.

Provide more context in these two DeprecationWarning.

---

doc/whatsnew/fragments/7467.bugfix
pylint/checkers/classes/class_checker.py
tests/functional/i/invalid/invalid_class_object.py
tests/functional/i/invalid/invalid_class_object.txt

[invalid-class-object] Fix crash when ``__class__`` is defined with a tuple

---

doc/whatsnew/fragments/7264.internal
tests/lint/unittest_lint.py

This changes 4 existing tests, due to a misunderstanding of the author (past me) in a couple of the details of those tests. Specifically, we now copy a single python file to use as our plugin, and make sure to correctly check for the name as given in the checker classes. We also make sure not to accidentally load the old copy of the plugin, which apparently sits in a directory that is already on the system path.
There is also a single new test, which covers the cases of loading a plugin with ``init-hook`` magic, both specified in an rc file, but in different orders.
This and #7276 are the only outstanding PRs preventing closure of #7264.
Refs #7264.

Add and fix tests for init-hook based plugin load

---

README.rst

Add the badge for the openssf fondation. Follow-up to #7267 that was already documented in the changelog.

[openssf] Add the badge for the openssf foundation

---

doc/user_guide/usage/output.rst

Fixes the documented shorthand for --reports=y to be `-ry` rather than the incorrect `-rn`.

Fix the documented shorthand for --reports=y

---

doc/data/messages/a/anomalous-unicode-escape-in-string/bad.py
doc/data/messages/a/anomalous-unicode-escape-in-string/good.py
doc/whatsnew/fragments/7482.other

Replaces erroneous usage of `.format()` on the `bytes` object with %-formatting in the message example for W1402 (anomalous-unicode-escape-in-string) so that the good example can actually be run.

Update W1402 message example to be an actually working code

---

doc/whatsnew/fragments/4809.false_positive
pylint/checkers/variables.py
tests/functional/g/globals.py
tests/functional/g/globals.txt
tests/functional/u/unused/unused_variable.py
tests/functional/u/unused/unused_variable.txt

False positive `global-variable-not-assigned`

---

doc/whatsnew/fragments/7471.bugfix
pylint/config/callback_actions.py
tests/test_self.py

Accept a comma-separated list of messages IDs in ``--help-msg``

---

doc/whatsnew/fragments/7311.false_positive
pylint/checkers/variables.py
pylint/constants.py
pylint/extensions/typing.py
tests/functional/u/undefined/undefined_loop_variable.py
tests/functional/u/undefined/undefined_loop_variable.txt
tests/functional/u/undefined/undefined_loop_variable_py311.py
tests/functional/u/undefined/undefined_loop_variable_py311.rc

Continuation of https://github.com/PyCQA/pylint/pull/7419
@DetachHead Sorry not sure what went wrong here. I tried to push my fix to your branch but it closed the PR... Sorry about that!
This should work 😄 
Tested on 3.11 locally as well.
Closes https://github.com/PyCQA/pylint/issues/7311

Fix `undefined-loop-variable` with `NoReturn` and `Never`

---

doc/development_guide/how_tos/custom_checkers.rst
doc/whatsnew/fragments/7264.other

NOTE: This PR replaces #7276 due to an admin error on my part.
This PR just updates the documentation page on writing custom checkers. It adds
information about some restrictions between how `init-hook` changes the loading
path and when you can use that to import your custom module.
Whilst the docs on testing custom checkers do touch on the fact the
module has to be in your load path, there are some restrictions that
were not made clear before.
Specifically, the init-hook configuration item (which is often used
explicitly to change the sys.path) is not automatically sufficient. If
the init hook is in a file, but the load-plugins argument is passed in
the CLI, then the plugins are loaded …

Improve docs clarity on loading custom checkers - FIXED

---

doc/whatsnew/fragments/7390.bugfix
pylint/checkers/classes/class_checker.py
tests/functional/a/arguments_differ.txt
tests/functional/a/arguments_renamed.txt

Closes #7390
Issue brought up that the wording incorrectly said "overridden" when talking about a child, which is an "overriding" object. I updated the two relevant warnings, and also removed the class_type: str as an argument since it's only used within this one function.

Update wording to clarify overriding object.

---

tests/functional/e/enum_subclasses.py

Add a functional test for combinations of ``enum.Flag`` constants with bitwise operators.
Refs #7381

Add a functional test for bitwise combinations of ``enum.Flag`` members

---

doc/whatsnew/fragments/7507.bugfix
doc/whatsnew/fragments/7507.other
pylint/checkers/classes/class_checker.py
tests/functional/m/missing/missing_self_argument.txt
tests/functional/n/no/no_method_argument_py38.py
tests/functional/n/no/no_self_argument.py
tests/functional/n/no/no_self_argument.txt
tests/functional/n/no/no_self_argument_py37.txt
tests/functional/r/regression/regression_4723.txt
tests/functional/u/unexpected_special_method_signature.txt

Report `no-self-argument` rather than `no-method-argument` for methods with variadic arguments.
Per the comment in #7507, I also added method name to the error messages of no-method-argument and no-self-argument
Closes #7507

Replace no-method-argument with no-self-argument when variadic args present

---

doc/whatsnew/fragments/4562.bugfix
pylint/checkers/typecheck.py
pylint/checkers/utils.py
tests/functional/n/no/no_member_augassign.py
tests/functional/n/no/no_member_augassign.txt

Add code to detect `no-member` when an augmented assign is done "manually", that is, when a user does this
`obj.value = 1 + obj.value`
instead of 
`obj.value += 1`
If `no-member` would be raised in the second case, it should also be raised in the first case, which is why this PR is here!
Closes #4562 (altho I can remove this auto-close if we want to keep it open for the `pydantic` false positive case, though I Personally think it should be a separate issue)

Fix false negative ``no-member`` when the code was a `manual` augmented assignments

---

doc/whatsnew/fragments/7530.internal
pylint/config/configuration_mixin.py
pyproject.toml

Fixing `mypy` checker using `pre-commit` on Windows.
See bug description below.
Fix details:
1. `colorama`  module added to `mypy`'s `ignore_missing_imports`.
2. typing was fixed for Python 3.8 and lower, think the error was never discovered before because pre-commit runs on a newer version in CI.
Closes #7530

Hotfix mypy precommit errors for colorama and typing on Windows

---

doc/whatsnew/fragments/7524.bugfix
pylint/checkers/variables.py
tests/functional/r/redefined/redefined_outer_name_type_checking.py

Closes #7524
Similar solution to #6787

Prevent `redefined-outer-name` for `if t.TYPE_CHECKING`

---

.github/workflows/changelog.yml
.github/workflows/checks.yaml
.github/workflows/primer-test.yaml
.github/workflows/primer_comment.yaml
.github/workflows/primer_run_main.yaml
.github/workflows/primer_run_pr.yaml
.github/workflows/release.yml
.github/workflows/tests.yaml
doc/whatsnew/fragments/5920.other
pyproject.toml
tox.ini

Use 3.11 for Github actions

---

Dockerfile
doc/whatsnew/fragments/7544.other

Use `--no-cache-dir` with `pip install` in Dockerfile to prevent cache and minimize the Docker image.

Prevent leaving pip install cache in Docker iamge

---

doc/whatsnew/fragments/7003.bugfix
pylint/config/config_initialization.py
tests/config/test_config.py

Closes https://github.com/PyCQA/pylint/issues/7003.

Fix handling of ``--`` as separator between positional args and flags

---

tests/pyreverse/test_utils.py

Resolves this warning:
```
=============================== warnings summary ===============================
tests/pyreverse/test_utils.py::test_infer_node_1
/home/runner/work/pylint/pylint/venv/lib/python3.11/site-packages/astroid/node_classes.py:94: DeprecationWarning: The 'astroid.node_classes' module is deprecated and will be replaced by 'astroid.nodes' in astroid 3.0.0
warnings.warn(
-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
```

Resolve deprecation warning in pyreverse test

---

tests/pyreverse/test_diadefs.py

@DudeNr33 Are these test passing correctly? Or should they be made to actually fail again?

Remove xfail from passing tests

---

.github/PULL_REQUEST_TEMPLATE.md
doc/development_guide/contributor_guide/contribute.rst
towncrier.toml

See https://github.com/PyCQA/pylint/pull/7581#discussion_r990612131
With `towncrier` V22.8.0 and the array-style definition of fragment types in `towncrier.toml` the order of definition is preserved when generating the changelog file. I updated the comment in `towncrier.toml` so we are not tempted to change that in the future. 😁

Add "breaking change" and "user action" fragment types

---

.github/workflows/primer_comment.yaml
.github/workflows/primer_run_main.yaml
.github/workflows/primer_run_pr.yaml

Primer has been broken since we use `sys.version` to get the correct version for some attributes but that returns something different than the version that GA returns when determining the versions.
I don't really want to start investigating as this is fixed in a month or so. Let's just return to `3.10` while `3.11` is not officially released.

Make primer use ``3.10``

---

.github/workflows/changelog.yml
.github/workflows/checks.yaml
.github/workflows/primer-test.yaml
.github/workflows/primer_run_main.yaml
.github/workflows/primer_run_pr.yaml
.github/workflows/tests.yaml

The Github actions `::set-output` command was deprecated and replaced with environment files.
Refs:
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-output-parameter

Replace deprecated set-output commands [ci]

---

doc/whatsnew/fragments/7626.false_positive
doc/whatsnew/fragments/7626.other
pylint/checkers/refactoring/refactoring_checker.py
pylint/checkers/utils.py
tests/functional/t/ternary.py
tests/functional/t/ternary.txt

If multiple values are possible for a constant, we should silence the refactoring messages that claim to offer simplifications, since the inferred value is not reliable.
Adds a keyword-only `compare_constants` argument to `safe_infer` to accomplish this in a reusable way.
Closes #7626
I'm wondering if @areveny you might wish to have a look, as I saw #5227? No pressure.

Fix a false positive for `simplify-boolean-expression` when multiple values inferred

---

.github/workflows/tests.yaml

Followup to #7618
On windows environment variables should be prefixed with `$env:`.

Fix windows cache key [ci]

---

.github/workflows/tests.yaml
tests/functional/r/regression_02/regression_no_member_7631.py

No changelog entry necessary since regression is only present in main and not released yet.
Requires https://github.com/PyCQA/astroid/pull/1834
Closes #7631

Add regression test for no-member with empty AnnAssign

---

doc/whatsnew/fragments/7635.bugfix
pylint/lint/pylinter.py
script/.contributors_aliases.json
tests/test_check_parallel.py

When the dictionary has served its purpose (making plugin loading pre-and-post init a consistent behaviour), we swap it for bools indicating whether or not a module was loaded.
We don't currently use the bools, but it seemed a sensible choice. The main idea is to make the dictionary fully pickle-able, so that when dill pickles the linter for multiprocessing, it doesn't crash horribly.
Closes #7635

Swap plugin cache to pickle-able values when done

---

script/create_contributor_list.py

On MacOS `Path(__file__).parent.parent` seems to be resolved to an absolute path. This causes the `contibutors-txt` script to insert a duplicate header as the path for `.contributors_aliases.json` doesn't match anymore.
Noticed this while testing the release workflow.
https://github.com/PyCQA/pylint/blob/15dd079792ce8e6b37856450f9e4a928f11b3549/CONTRIBUTORS.txt#L1-L5
Refs: https://github.com/PyCQA/pylint/issues/7362

Use relative paths in `create_contributor_list.py`

---

doc/whatsnew/fragments/7655.other
examples/pylintrc
pylint/config/arguments_manager.py

Sort output of `--generate-rcfile` similar to  the  one from `--generate-toml-config` and  update  example pylintrc.
Noticed this while trying the release workflow.
Note: To make backporting easier, don't squash merge this PR.
https://github.com/PyCQA/pylint/blob/15dd079792ce8e6b37856450f9e4a928f11b3549/pylint/config/arguments_manager.py#L704-L707

Sort `--generate-rcfile` ouput

---

CONTRIBUTORS.txt
doc/whatsnew/2/2.15/index.rst
script/.contributors_aliases.json

Merge maintenance 2.15.x following the 2.15.5 release

---

.github/PULL_REQUEST_TEMPLATE.md
doc/development_guide/contributor_guide/contribute.rst
towncrier.toml

At the moment, there isn't a good category for new features which aren't checks.
The next best option would be `other` but that doesn't seem quite right.
Refs: https://github.com/PyCQA/pylint/issues/7362

Add new `feature` category for changelog entries

---

tests/test_functional.py

The `recwarn` fixture for `test_functional` prevents all `DeprecationWarnings` from showing up which aren't triggered at import. Noticed while working on a DeprecationWarning for https://github.com/PyCQA/astroid/pull/1389.
The previous code was added in https://github.com/PyCQA/pylint/commit/e37bf8c5d64ef5ce6becf631663b7880d8ee5a67.
Refs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html#warns

Fix showing DeprecationWarnings for functional tests

---

tbump.toml

Add an additional `tbump` step to confirm changes before the commit is created.
Found this to be quite helpful when I was doing the patch release.
Refs: https://stackoverflow.com/questions/1885525/how-do-i-prompt-a-user-for-confirmation-in-bash-script

Confirm changes before tbump commit

---

doc/whatsnew/fragments/7661.bugfix
pylint/checkers/unicode.py
tests/regrtest_data/encoding/bad_missing_num.py
tests/regrtest_data/encoding/bad_wrong_num.py
tests/regrtest_data/encoding/good.py
tests/test_self.py

Fix dict operation bug when parsing module to determine module encoding. Also added tests not previously added when handling this issue in https://github.com/PyCQA/pylint/pull/7097
Closes #7661

fix astroid-error for parsing module encoding

---

pylint/testutils/functional/find_functional_tests.py

| ✓   | Tests                  |
The pull request fixes the non deterministic ordering of functional tests depending on the underlying system.
Refs #7464

Make the order of functional tests deterministic

---

doc/exts/pylint_messages.py
doc/whatsnew/fragments/7629.other
pylint/extensions/code_style.py
pylint/lint/pylinter.py
pylint/message/message_definition.py
pylint/typing.py

Add a new `default_enabled` option to make it easier to disable a specific message by default.
This is especially useful for extensions like the `CodeStyle` one. I'm not so sure if we should use it for regular checks though. The expectation I believe is that all of them are enabled by default. I.e. to disable one, we should move it to an extension first.

Add `default_enabled` option to optional message dict

---

requirements_test_min.txt

Fix issue with pytest `v7.2.0` and `pytest-benchmark` discovered in #7671
Ref: https://github.com/ionelmc/pytest-benchmark/issues/226

Pin pytest to resolve issue with pytest-benchmark

---

.github/workflows/changelog.yml
.github/workflows/checks.yaml
.github/workflows/primer-test.yaml
.github/workflows/release.yml
.github/workflows/tests.yaml

Python 3.11 was released yesterday 🎉

Run tests with Python 3.11.0

---

.github/workflows/changelog.yml
.github/workflows/checks.yaml
.github/workflows/codeql-analysis.yml
.github/workflows/primer-test.yaml
.github/workflows/primer_run_main.yaml
.github/workflows/primer_run_pr.yaml
.github/workflows/release.yml
.github/workflows/tests.yaml

This set the least amount of privilege for each github actions when it wasn't already set. 
Full disclosure, I'm being paid to make pylint more secure by Tidelift and this is part of this effort.

[github action] Follow the principle of least privileges

---

requirements_test_min.txt

Followup to #7674
Update pytest to `v.7.2.0`: https://docs.pytest.org/en/7.2.x/changelog.html#pytest-7-2-0-2022-10-23
And pytest-benchmark to `v4.0.0`: https://github.com/ionelmc/pytest-benchmark/blob/master/CHANGELOG.rst#400-2022-10-26

Update pytest and pytest-benchmark following the 7.2.0 release

---

.github/workflows/release.yml

Refs: https://github.com/PyCQA/pylint/pull/7259#issuecomment-1220064159
Add an environment for the `release` workflow. This will allow for additional protection rules and better secrets scoping.
https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment
> **Note**
>   It would make sense to move the `PYPI_API_TOKEN` secret. That way other workflows won't be able to access it.
--
I've also added a wildcard tag protection rule. Thus only users with the admin or maintain permission will be able to create new tags.
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/managing-repository-settings/configuring-tag-protection-rules

Add PyPI deployment environment [ci]

---

doc/whatsnew/fragments/5359.other
tests/primer/packages_to_prime.json

Adding the package to the primer test suite as [discussed](https://github.com/PyCQA/pylint/issues/5359#issuecomment-1291843791).
Refs #5359

Add the `coverage` package to the primer suite.

---

requirements_test_min.txt

The [`py`](https://pypi.org/project/py/) package is used in a number of test files without being an explicit dependency. On linux it is installed with either `pytest-xdist` or `tox`, but that doesn't cover pypy, windows, and macos. If these environments are rebuild from scratch, the tests would fail.
https://github.com/PyCQA/pylint/blob/004fc7483ff6cd99ddd19dd6a572011797b138b0/tests/test_self.py#L30
https://github.com/PyCQA/pylint/blob/004fc7483ff6cd99ddd19dd6a572011797b138b0/tests/test_self.py#L164-L166
https://github.com/PyCQA/pylint/blob/004fc7483ff6cd99ddd19dd6a572011797b138b0/tests/test_pylint_runners.py#L17

Add `py` to requirements

---

doc/whatsnew/fragments/7214.bugfix
pylint/reporters/multi_reporter.py
tests/reporters/unittest_reporting.py

MultiReporter was sending message by reference, which then could be changed by reporter. The colorized reporter was one of them, leading to changing any other reporters. This was broken since 2.14.0 and affected mostly people using colorized with a custom reporter.
Closes #7214

fix: reporters receive copy of message

---

.github/workflows/changelog.yml
.github/workflows/checks.yaml
.github/workflows/primer-test.yaml
.github/workflows/primer_comment.yaml
.github/workflows/primer_run_main.yaml
.github/workflows/primer_run_pr.yaml
.github/workflows/release.yml
.github/workflows/tests.yaml
pyproject.toml
requirements_test_min.txt

Improve multiple issues with our Github actions workflows.
* Remove `restore-keys`. Especially on Windows there are issues with reusing old cache entries and trying to install newer versions. Those are just skipped if the old one still satisfies the requirement. It's easy / fast enough to create a whole new environment if something changes.
* Log astroid and pylint versions to help with debugging if necessary.
* Reset cache versions.
* Add `check-latest: true` for `setup-python` action. This will prevent cache restore issue when runners use different Python patch versions. https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md#check-latest-version
* Add `KEY_PREFIX` env variable to more easily identify the key prefix in each workflow.
* Replace `setup.cfg` with …

Improve Github action workflows

---

.pre-commit-config.yaml
pylint/checkers/format.py
pylint/checkers/strings.py
pylint/checkers/typecheck.py
pylint/checkers/utils.py
pylint/lint/caching.py
pylint/message/message_definition_store.py
requirements_test_pre_commit.txt
tests/test_check_parallel.py

I realized that flake8-bugbear was configured in astroid but not pylint when upgrading pre-commit. Generally it's the other way around. There were some fixes to do, some of them valuable.

Add flake8 bugbear to pre-commit

---

doc/data/messages/i/invalid-characters-in-docstring/details.rst
doc/data/messages/i/invalid-characters-in-docstring/good.py
doc/data/messages/w/wrong-spelling-in-comment/bad.py
doc/data/messages/w/wrong-spelling-in-comment/details.rst
doc/data/messages/w/wrong-spelling-in-comment/good.py
doc/data/messages/w/wrong-spelling-in-comment/pylintrc
doc/data/messages/w/wrong-spelling-in-docstring/bad.py
doc/data/messages/w/wrong-spelling-in-docstring/details.rst
doc/data/messages/w/wrong-spelling-in-docstring/good.py
doc/data/messages/w/wrong-spelling-in-docstring/pylintrc

We can't document ``"invalid-characters-in-docstring"`` in docstring right now because this is raised in case of enchant error and it's hard to trigger. This should be treated like a fatal error for documentation purpose.

[doc] Add examples for wrong-spelling-in-x

---

pylint/checkers/exceptions.py
tests/functional/b/bad_except_order.txt
tests/functional/b/bare_except.txt
tests/functional/b/broad_exception_caught.txt
tests/functional/b/broad_exception_raised.txt
tests/functional/d/duplicate_except.txt
tests/functional/e/exception_is_binary_op.txt
tests/functional/ext/docparams/raise/missing_raises_doc.txt
tests/functional/i/invalid/invalid_exceptions/invalid_exceptions_raised.txt
tests/functional/m/misplaced_bare_raise.txt
tests/functional/r/raising/raising_bad_type.txt
tests/functional/r/raising/raising_format_tuple.txt
tests/functional/r/raising/raising_non_exception.txt

While working on adding the new `broad-exception-raised` checker, I was able to work on adding confidence levels to other checkers in the same file
Don't think this needs changelog but lmk if you disagree.
Closes #7715

add confidence levels to all exception checkers

---

pylint/interfaces.py
pylint/utils/pragma_parser.py

The need to call an exec on a string is worst performance wise, and we also have the benefit of being able to add typing with the new way of doing it.

Use typed NamedTuple for `Confidence` + `PragmaRepresenter`

---

.github/workflows/primer_comment.yaml
.github/workflows/primer_run_main.yaml
.github/workflows/primer_run_pr.yaml
pyproject.toml
requirements_test_min.txt

Followup to https://github.com/PyCQA/pylint/pull/7651#issuecomment-1303397691
To prevent a `Primer / Run` failure if the hash changes, add separate step to create venv in that workflow too. With Github actions cache [scoping](https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#restrictions-for-accessing-a-cache), the cache entry can only be used for the specific PR.
Additionally, remove install of bleeding-edge astroid. That only works as long as the `main` astroid branch doesn't contain any breaking changes.
With the new cache key, it's no longer necessary to update the `CACHE_VERSION` when doing an astroid update.
/CC: @DanielNoord, @Pierre-Sassoulas

Update Primer venv caching [ci]

---

doc/data/messages/u/use-implicit-booleaness-not-comparison/bad.py
doc/data/messages/u/use-implicit-booleaness-not-comparison/details.rst
doc/data/messages/u/use-implicit-booleaness-not-comparison/good.py
pylint/checkers/refactoring/implicit_booleaness_checker.py
tests/functional/u/use/use_implicit_booleaness_not_comparison.txt

Follow-up to #7723 in order to make #6870 more reviewable.

More descriptive message for ``use-implicit-booleaness-not-comparison``

---

pylint/lint/base_options.py

Adding another escape to small doc PR submitted in #7103, looks like the autoupgrade removed the escape.
CC @Pierre-Sassoulas

Ignore path doc: double escape to add escape character in rst

---

pylint/extensions/emptystring.py
tests/functional/ext/emptystring/empty_string_comparison.py
tests/functional/ext/emptystring/empty_string_comparison.txt

Originally done in order to normalize the use-implicit-booleaness check. This make the message more understandable and permit to make https://github.com/PyCQA/pylint/pull/6870 more reviewable. We have to use " as string delimiter because node as string have ' as string delimiter.
Closes #5234 (the changelog will be added in #6870)

[compare-to-empty-string] More actionnable and understandable message

---

pylint/testutils/_primer/package_to_lint.py
pylint/testutils/_primer/primer.py
tests/primer/packages_to_lint_batch_one.json
tests/primer/packages_to_prime.json

Specifying minimum python versions supported by a package should allow us to move the last packages into the new primer. 
Some of them were taking too long on 3.7, and we weren't sure if it was an issue with the package, the primer, or just the action workflow running out of memory diffing massive dictionaries of messages. There's not really a point in priming a package on 3.7 if the development version doesn't support it anymore.

Allow specifying minimum python version for primer packages

---

pylint/lint/pylinter.py
pylint/message/message_definition.py
pylint/message/message_definition_store.py

#7580 added a deprecation warning but didn't silence it in the test suite. Just a cleanup.

Avoid deprecation warning in internal use of `may_be_emitted`

---

.github/workflows/primer_run_main.yaml
.github/workflows/primer_run_pr.yaml
pylint/testutils/_primer/primer_prepare_command.py

Fixes primer failures on PR jobs since Wednesday due to #7717. See discussion at https://github.com/PyCQA/pylint/pull/7717#issuecomment-1312476547 and a [successful primer launch](https://github.com/jacobtylerwalls/pylint/actions/runs/3451179755/jobs/5761509997) on a PR job on my fork where I've already merged the changes to `main`.
Test failures are expected until the workflow is merged to main.

Tag primer commit strings with python version

---

.github/workflows/primer_run_pr.yaml

@mbyrnepr2 Finally this is launching the primer on a PR (this one). Fancy reviewing, and then I can merge?

Preserve file name when copying commit string file in primer job

---

doc/development_guide/contributor_guide/tests/launching_test.rst

Correct documentation about running primer locally

---

pylint/checkers/typecheck.py
tests/functional/i/invalid/invalid_sequence_index.py

The `ExtSlice` node has long been deprecated in astroid and is actually not used anymore since it was merged in `Subscript`. https://github.com/PyCQA/astroid/pull/1026
This PR removes the references to `nodes.ExtSlice` that I seem to have missed in #4568.

Remove unused `ExtSlice` code paths

---

doc/user_guide/configuration/all-options.rst
doc/whatsnew/fragments/7495.bugfix
examples/pylintrc
examples/pyproject.toml
pylint/checkers/exceptions.py
pylintrc
tests/functional/b/bad_exception_cause.txt
tests/functional/b/broad_exception_caught.py
tests/functional/b/broad_exception_caught.rc
tests/functional/b/broad_exception_caught.txt
tests/functional/b/broad_exception_raised.py
tests/functional/b/broad_exception_raised.rc
tests/functional/b/broad_exception_raised.txt

Allow specifying non-builtin exceptions in overgeneral-exception option using exception's qualified name.
Additionally, tries to deprecate specifying built-in exception names without dots. Small problem - I don't know how to tell pylint to warn about deprecation as `warnings.warn(...)` does not seem to be a valid way to do that.
Closes #7495

Use qualified name when checking for overgeneral exceptions

---

doc/data/messages/n/named-expr-without-context/bad.py
doc/data/messages/n/named-expr-without-context/good.py
doc/user_guide/checkers/features.rst
doc/user_guide/messages/messages_overview.rst
doc/whatsnew/fragments/7760.new_check
pylint/checkers/base/basic_checker.py
tests/functional/n/named_expr_without_context_py38.py
tests/functional/n/named_expr_without_context_py38.rc
tests/functional/n/named_expr_without_context_py38.txt
tests/functional/s/superfluous_parens_walrus_py38.py

Instead of emitting `pointless-statement`, this PR adds a new check `named-expr-without-context` for named expressions outside `if`, `for`, ...
```py
(a := 42)  # named-expr-without-context
```
Closes #7760

Add `named-expr-without-context` check

---

doc/whatsnew/fragments/7501.false_positive
pylint/checkers/utils.py
tests/functional/u/unhashable_member.py

Let `nodes.ClassDef` nodes be considered hashable.
Closes #7501

Fix false positive for ``unhashable-member`` when subclassing ``dict``.

---

doc/data/messages/i/invalid-slice-step/bad.py
doc/data/messages/i/invalid-slice-step/good.py
doc/user_guide/checkers/features.rst
doc/user_guide/messages/messages_overview.rst
doc/whatsnew/fragments/7762.false_negative
doc/whatsnew/fragments/7762.new_check
pylint/checkers/typecheck.py
tests/functional/i/invalid/invalid_slice_index.py
tests/functional/i/invalid/invalid_slice_index.txt

Followup to https://github.com/PyCQA/astroid/pull/1844#issuecomment-1312281340 by @nelfin.
This PR
* Improve the `invalid-slice-index` check to detect invalid indices on string and byte sequences.
```py
"Hallo"["a":"z"]  # invalid-slice-index (2x)
```
* Adds a new warning for `invalid-slice-step` when `0` is passed as step value for common builtin sequences.
```py
["a", "b", "c"][::0]  # invalid-slice-step
```

Improve `invalid-slice-index` and add `invalid-slice-step`

---

.github/workflows/checks.yaml

Fix failing `documentation` check.
https://github.com/PyCQA/pylint/actions/runs/3463507407/jobs/5784541243#step:8:1276
Ref https://github.com/PyCQA/pylint/pull/7769#issuecomment-1314214505

Bump timeout for docs check [ci]

---

doc/whatsnew/fragments/7570.bugfix
pylint/checkers/stdlib.py
tests/functional/b/bad_thread_instantiation.py
tests/functional/b/bad_thread_instantiation.txt

kinda both?
`bad-threading-instantiation` relied on the fact that if two args were passed, the user knew the second was the `target` func, but this is naive to assume. Instead, this PR improves this check by making it more strict - users should always identify the target func with the `target=` kwarg.
Closes #7570

Improve bad-threading-instantiation check

---

.github/workflows/backport.yml
doc/development_guide/contributor_guide/release.md

Based on https://github.com/tibdex/backport which seems awfully conveniant.

[release process] Add a github actions to backport fix automatically

---

.github/workflows/backport.yml

We also gave default write permissions for all jobs in the settings.
The permissions were explicitely defined in each job already
See https://github.com/PyCQA/pylint/actions/runs/3483774315 for the result without the right (write) permission.

[github actions] Set write permission for backport workflow

---

doc/whatsnew/fragments/7770.false_negative
pylint/checkers/refactoring/refactoring_checker.py
tests/functional/u/unnecessary/unnecessary_list_index_lookup.py
tests/functional/u/unnecessary/unnecessary_list_index_lookup.txt

`unnecessary-list-index-lookup` code wasn't taking into account the fact that `enumerate` could be called with a kwarg.
Closes #7770

``unnecessary-list-index-lookup`` false negative

---

doc/whatsnew/fragments/7563.false_positive
pylint/checkers/base/basic_checker.py
pylint/checkers/utils.py
pylint/checkers/variables.py
tests/functional/u/used/used_before_assignment_else_return.py
tests/functional/u/used/used_before_assignment_else_return.txt

Closes #7563
If a terminating func such as sys.exit, quit, etc is used in an else statement, `used-before-assignment` should not be flagged.

fix FP For used-before-assignment if terminating func is used

---

pylint/lint/message_state_handler.py
pylintrc

This enables the `broad-try-clause` check and sets the `max-try-statements` config option to not flag anything. I think it would be a good idea to try and lower that number, but that can be done later.

Enable broad-try-clause check

---

pylint/testutils/_primer/package_to_lint.py
tests/testutils/_primer/test_package_to_lint.py

Refs https://github.com/PyCQA/pylint/issues/7738#issuecomment-1320564585

[primer] Fall back to no rcfile rather than pylint's

---

doc/user_guide/configuration/all-options.rst
doc/whatsnew/fragments/7782.bugfix
examples/pylintrc
examples/pyproject.toml
pylint/checkers/classes/class_checker.py
tests/functional/c/class_members_py30.py
tests/functional/c/ctor_arguments.py
tests/functional/f/first_arg.py
tests/functional/f/first_arg.txt
tests/functional/r/regression_02/regression_too_many_arguments_2335.py
tests/functional/u/undefined/undefined_variable_py30.py

|     | Type                  |
| --- | --------------- |
| ✓   | :bug: Bug fix     |
| ✓   | :scroll: Docs      |
This PR fixes the `valid-metaclass-classmethod-first-arg` default config value, which would cause `bad-mcs-classmethod-argument` ([C0204](https://pylint.pycqa.org/en/latest/user_guide/messages/convention/bad-mcs-classmethod-argument.html)) to have a false-positive on metaclass classmethods (using `mcs`), and a false-negative (using `cls`).
Some functional tests failed after introducing this change, due to either using the `classmethod()` decorator or the `__new__` dunder in a metaclass with a `cls` first method argument.
Along with fixing any now-failing tests, I updated documentation to reflect changes.
Closes #7782

Fix `valid-metaclass-classmethod-first-arg` default value

---

.github/workflows/primer_comment.yaml
.github/workflows/primer_run_main.yaml
.github/workflows/primer_run_pr.yaml

Per https://github.com/PyCQA/pylint/pull/6756#issue-1253101349 we run the primer on the oldest and newest supported versions. 3.11 is the newest supported version.

Run primer on 3.11

---

doc/user_guide/checkers/features.rst
doc/user_guide/configuration/all-options.rst
pylint/checkers/variables.py
tests/functional/u/unbalanced_tuple_unpacking.txt
tests/functional/u/unpacking/unpacking_non_sequence.txt

Necessary to be able to do https://github.com/PyCQA/pylint/pull/7750 without thinking about it.

Better error message for unpacking-non-sequence and unbalanced-tuple-unpacking

---

.github/workflows/backport.yml
doc/development_guide/contributor_guide/release.md

The back-porting job needs to be able to create a cherry-pick on a branch and then open a pull request.

[github actions] Fix the permissions in backporting job

---

doc/whatsnew/fragments/5886.false_positive
pylint/checkers/deprecated.py
tests/checkers/unittest_deprecated.py
tests/functional/d/deprecated/deprecated_methods_py38.py

Original PR that added this code https://github.com/PyCQA/pylint/pull/4619/files
it seems that the unit test that was added led the code, which is a good practice, except I believe the unit test itself was incorrect and confused the naming of `deprecated_method`. This wasn't a necessary change at all, and in fact led to a false positive. 
Closes #5886

Fix ``deprecated-method`` false positive

---

tests/config/test_per_directory_config.py
tests/lint/test_pylinter.py
tests/pyreverse/test_pyreverse_functional.py
tests/test_pylint_runners.py
tests/test_self.py

pytest 7.2 no longer depends on py and py is kinda deprecated so it's better to drop it. `tmp_path` fixture is newer and uses `pathlib.Path` from stdlib instead of `LocalPath` from `py._path`.
An alternative for this is to add `py` into test dependencies.

Drop dependency on py module

---

.pyenchant_pylint_custom_dict.txt
doc/whatsnew/fragments/6242.bugfix
doc/whatsnew/fragments/7609.false_positive
pylint/checkers/variables.py
pylint/lint/expand_modules.py
pylint/lint/pylinter.py
tests/functional/u/used/used_before_assignment_typing.py
tests/functional/u/used/used_before_assignment_typing.txt
tests/lint/unittest_expand_modules.py
tests/test_pylint_runners.py

Some backporting did not work automatically as there are more and more conflict when cherry-picking. In particular #7747 was impossible to cherry-pick without downgrading the typing because of massive change in mypy. I tried to keep the mypy enhancement by cherry-picking all the linter change from main but after more than one hour it was clear it's not reasonable. I'm hoping to do all the other backporting with the new action after #7826 is merged.

Manual backporting for 2.15.7 release

---

.github/workflows/backport.yml
.github/workflows/primer-test.yaml
.github/workflows/primer_run_pr.yaml

We need it to push to the backporting branch after cherry-picking. See https://github.com/PyCQA/pylint/pull/7810\#issuecomment-1324742960
Also include change we did on the maintenance branch to not run primers.
Refs #7804, #7815 #7810

Add ``content: write`` rights for backporting job

---

.github/workflows/backport.yml
pyproject.toml
requirements_test_min.txt

Make sure that we use the real version of dill on all interpreter now that dill released version 0.3.6. also explicitly use the latest astroid.

Upgrade the versions of astroid and dill

---

doc/whatsnew/fragments/7828.bugfix
pylint/checkers/refactoring/refactoring_checker.py
tests/functional/s/stop_iteration_inside_generator.py

Pylint should not crash if `next()` is called, even tho that's incorrect python!
Closes #7828

Do not crash if next()` is called

---

doc/whatsnew/fragments/7821.bugfix
pylint/checkers/refactoring/refactoring_checker.py
tests/functional/u/unnecessary/unnecessary_list_index_lookup.py

fixes
```
start_val = node.value
AttributeError: 'Attribute' object has no attribute 'value'
```
Closes #7821

Fix crash when using ``enumerate`` with ``start`` and a class attribute

---

pylint/checkers/variables.py
tests/functional/u/undefined/undefined_variable_py38.py
tests/functional/u/undefined/undefined_variable_py38.txt

Fix an unreleased false positive noticed by Marc in https://github.com/PyCQA/pylint/pull/6677#discussion_r1031664559.

Prevent `used-before-assignment` for variables defined in assignment expressions

---

doc/whatsnew/fragments/4984.false_positive
pylint/checkers/logging.py
tests/functional/l/logging/logging_fstring_interpolation_py37.py
tests/functional/l/logging/logging_fstring_interpolation_py37.txt

``logging-fstring-interpolation`` should not be raised if logging with an f-str that also has %s formatting.
Closes #4984

Fix ``logging-fstring-interpolation`` FP

---

doc/whatsnew/fragments/6543.feature
pylint/pyreverse/diagrams.py
pylint/pyreverse/dot_printer.py
pylint/pyreverse/inspector.py
pylint/pyreverse/mermaidjs_printer.py
pylint/pyreverse/plantuml_printer.py
pylint/pyreverse/printer.py
pylint/pyreverse/vcg_printer.py
pylint/pyreverse/writer.py
tests/pyreverse/data/classes_No_Name.dot
tests/pyreverse/data/classes_No_Name.html
tests/pyreverse/data/classes_No_Name.mmd
tests/pyreverse/data/classes_No_Name.puml
tests/pyreverse/data/classes_colorized.dot
tests/pyreverse/data/classes_colorized.puml
tests/pyreverse/test_diadefs.py

Update pyreverse to differentiate between compositions and aggregations in classes. Only covers the basic cases of composition and aggregation(@DudeNr33 ).
e.g.  having a code like this
```python
""" docstring for file clientmodule.py """
from data.suppliermodule_test import Interface, DoNothing, DoNothing2
class Ancestor:
""" Ancestor method """
__implements__ = (Interface,)
cls_member = DoNothing()
def __init__(self, value):
local_variable = 0
self.attr = 'this method shouldn\'t have a docstring'
self.__value = value
def get_value(self):
""" nice docstring ;-) """
return self.__value
def set_value(self, value):
self.__value = value
return 'this method shouldn\'t have a docstring'
class …
```

Feature: distinct Composition and Aggregation arrows

---

doc/whatsnew/fragments/7818.false_negative
pylint/checkers/base/basic_checker.py
tests/functional/d/dangerous_default_value.py
tests/functional/d/dangerous_default_value.txt

Order of operation matters!! Turns out without the parens we weren't getting the default kwargs.
Closes #7818

Fix ``dangerous-default-value`` false negative when `*` is used.

---

doc/whatsnew/fragments/7821.bugfix
pylint/checkers/refactoring/refactoring_checker.py
tests/functional/u/unnecessary/unnecessary_list_index_lookup.py

This reverts commit 86b8c649061f49c7d121843675ceefe6ff3a8113 which broke the test on the maintenance branch. Do you think this is fixable by cherry-picking something else first @clavedeluna ? Otherwise we can just wait for 2.16 to release the fix.

Revert "Fix crash when using ``enumerate`` with ``start`` and a class attribute (#7824)"

---

CONTRIBUTORS.txt
doc/whatsnew/2/2.15/index.rst
doc/whatsnew/fragments/5886.false_positive
doc/whatsnew/fragments/6242.bugfix
doc/whatsnew/fragments/7609.false_positive
doc/whatsnew/fragments/7828.bugfix
pylint/__pkginfo__.py
tbump.toml

Bump pylint to 2.15.7, update changelog

---

doc/data/messages/s/shadowed-import/bad.py
doc/data/messages/s/shadowed-import/good.py
doc/user_guide/checkers/features.rst
doc/user_guide/messages/messages_overview.rst
doc/whatsnew/fragments/4836.bugfix
pylint/checkers/imports.py
tests/functional/i/import_aliasing.py
tests/functional/r/reimport.txt
tests/functional/r/reimported.py
tests/functional/r/reimported.txt
tests/functional/s/shadowed_import.py
tests/functional/s/shadowed_import.txt
tests/functional/u/unused/unused_import.py
tests/functional/u/unused/unused_import_py30.txt

Closes #4836
Issue brought up the fact that the `reimported` message was confusing and hinted at something else, while also giving us more test cases to improve the check for imports using aliases.

reimported should detect aliased imports

---

doc/development_guide/contributor_guide/tests/writing_test.rst

The `Functional tests` section in the [Writing Test docs page](https://pylint.pycqa.org/en/latest/development_guide/contributor_guide/tests/writing_test.html) is unclear in the example for the `n` lines option:
```
#
```
The second line with `#` can be easily mistaken for being part of the syntax, or meaning some line, where the true meaning is the `empty-comment` error itself..
This PR offers a much better example, which doesn't mix up the syntax of what the example trying the show and the example itself.
see discussion in [the comment here](https://github.com/PyCQA/pylint/pull/7745#discussion_r10 …

Rephrase Functional tests section in writing_test docs page

---

doc/whatsnew/fragments/7209.false_positive
pylint/checkers/classes/class_checker.py
pylint/checkers/utils.py
tests/functional/p/protocol_classes_abstract.py
tests/functional/p/protocol_classes_abstract.rc
tests/functional/p/protocol_classes_abstract.txt

Closes #7209
I'm not sure if I just got lucky in this very short fix or I'm completely wrong here in adding a Protocol check to the is_abstract utility method....

Define Protocol as abstract to prevent abstract-method FP

---

pylint/checkers/classes/class_checker.py
pylint/checkers/typecheck.py
pylint/checkers/utils.py

Looking at the coverage report, I noticed these `except NotImplementedError` blocks weren't being hit. I think it's because they are holdovers from Python 2 days. Oldstyle classes aren't possible anymore, so I don't think it's possible to reach this code. So, delete it.

Cut oldstyle checks

---

doc/whatsnew/fragments/7827.false_positive
pylint/extensions/_check_docs_utils.py
tests/functional/ext/docparams/parameter/missing_param_doc_required_Google.py

As mentioned in linked issue, if this is too a hacky solution, we can reject the PR and attempt to update the `re_param_line` regex.
Closes #7827

Fix ``missing-param-doc`` FP

---

doc/data/messages/r/redundant-typehint-argument/bad.py
doc/data/messages/r/redundant-typehint-argument/good.py
doc/data/messages/r/redundant-typehint-argument/pylintrc
doc/user_guide/checkers/extensions.rst
doc/user_guide/checkers/features.rst
doc/user_guide/messages/messages_overview.rst

[doc] Upgrade generated doc, create example for redundant-typehint-argument

---

doc/whatsnew/fragments/5401.feature
examples/pylintrc
examples/pyproject.toml
pylint/lint/base_options.py
pylint/lint/run.py
pylint/utils/utils.py
pylintrc
tests/config/test_config.py

Use this flag if you expect the linted files to be altered between runs, for instance, if using pylint in a server-like mode. The flag clears astroid's in-memory caches.
Refs https://github.com/microsoft/vscode-pylint/issues/129

Add flag `--clear-cache-post-run` to support server-like usage

---

doc/whatsnew/fragments/5327.false_positive
pylint/checkers/variables.py
tests/functional/u/used/used_before_assignment_py310.py
tests/functional/u/used/used_before_assignment_py310.rc

Prevent `used-before-assignment` in pattern matching with a guard

---

doc/whatsnew/fragments/7873.internal
pylint/checkers/variables.py
tests/functional/u/undefined/undefined_variable_py38.py
tests/functional/u/used/used_before_assignment.py

Fixes false positives relating to cases with `NamedExpr` and `Starred` not handled in https://github.com/PyCQA/pylint/pull/6677.
Thanks to @cdce8p for isolating and reporting.
Unreleased -- should _not_ need a backport.
Closes #7873

Fix unreleased false positives with `used-before-assignment`

---

doc/whatsnew/fragments/3899.bugfix
pylint/lint/parallel.py
pylint/lint/run.py
tests/test_check_parallel.py

Replace `multiprocessing.pool` with [concurrent.futures.ProcessPoolExecutor](https://docs.python.org/3/library/concurrent.futures.html#processpoolexecutor) to avoid deadlocks.
In a `multiprocessing.pool`, if a process terminates in a non-clean fashion (for example, due to OOM or a segmentation fault), the pool will silently replace said process, but the work that the process was supposed to do will never be done, causing pylint to hang indefinitely. The `concurrent.futures.ProcessPoolExecutor` will raise a [BrokenProcessPool exception](https://docs.python.org/3/library/concurrent.futures.html#concurrent.futures.process.BrokenProcessPool) in that case, avoiding the hang.
See …

Avoid hanging forever after a parallel job was killed

---

pyproject.toml
requirements_test_pre_commit.txt

fix: bump dill to >= 0.3.6, prevents tests hanging with python3.11

---

doc/whatsnew/fragments/7938.bugfix
pylint/lint/pylinter.py

Ensure that the import path is fixed up before calling `._astroid_module_checker()` so that the `pylint_django` plugin can successfully import the Django settings module when its checkers are initialized.
Closes #7938

Fix ModuleNotFoundError when using pylint_django

---

doc/whatsnew/fragments/7931.bugfix
pylint/config/arguments_manager.py
pylint/config/config_initialization.py
tests/lint/test_run_pylint.py
tests/lint/unittest_expand_modules.py

We were bitten by this causing us to think that pylint was completing successfully when in fact a typo in a configuration file was causing argparse to exit with exit code 2. This didn't happen in older versions of pylint for whatever reason. The [documentation for pylint](https://pylint.pycqa.org/en/latest/user_guide/usage/run.html#exit-codes) suggests that this means "error message issued" but that pylint executed properly when this is not the case.
It feels a bit clumsy to just add in `try..except`, but on the other hand it's perhaps unexpected that argparse will raise a `SystemExit`. I'm open to any suggestions to improve this.

Fix inconsistent argument exit code when argparse exit with its own error code

---

tests/regrtest_data/importing_plugin/importing_plugin.py
tests/test_self.py

This PR is a follow-up to #7940 to add a regression test for the issue fixed in that PR.  It uses a simple plugin that mimics what happens in the `pylint_django` plugin.  I verified that the test failed before the fix and passes after.  I had to make my best guess as to which test module to use to add the test, so if there is a better place to put it, let me know.  
Refs #7938

Add test for ModuleNotFoundError fix

---

pylint/testutils/lint_module_test.py

In order to help when the target interpreter is not installed locally and you can't update automatically yourself (pypy/old interpreters like python 3.7).
Done for: Refs #7945
Old:
```
Wrong output for 'postponed_evaluation_pep585.txt':
You can update the expected output automatically with: 'python tests/test_functional.py --update-functional-output -k "test_functional[postponed_evaluation_pep585]"'
- Missing lines:
OutputLine(symbol='unsubscriptable-object', lineno=96, column=15, end_lineno=None, end_column=None, object='', msg="Value 'list' is unsubscriptable", confidence='UNDEFINED')
OutputLine(symbol='unsubscriptable-object', lineno=97, column=21, end_lineno=None, end_column=None, …
```

[testutil] More information in output for functional test fail

---

doc/whatsnew/fragments/7979.false_positive
pylint/checkers/variables.py
tests/functional/u/used/used_before_assignment_typing.py
tests/functional/u/used/used_before_assignment_typing.txt

Closes #7979 
See regression test; fixes false positive in `music21`.

Fix `used-before-assignment` if conditional imports guarded again when used

---

doc/whatsnew/fragments/5788.false_positive
pylint/checkers/refactoring/recommendation_checker.py
pylint/checkers/utils.py
tests/functional/ext/code_style/cs_consider_using_tuple.py
tests/functional/ext/code_style/cs_consider_using_tuple.txt
tests/functional/u/use/use_sequence_for_iteration.py
tests/functional/u/use/use_sequence_for_iteration.txt

Manual backport of cf5ea8a32bcdac0bd889f973272c59599b40af95 (#7975) from main.

Fix `use-sequence-for-iteration` when unpacking a set with `*` (#7975)

---

doc/whatsnew/fragments/5636.bugfix
pylint/reporters/text.py
tests/reporters/unittest_reporting.py

Fixes bug when loading user-provided msg-template.

---

tests/functional/ext/dict_init_mutate.py

This covers a missing line from the dict-init-mutate extension test.

Cover missing line in dict-init-mutate test

---

doc/user_guide/checkers/extensions.rst
doc/user_guide/checkers/features.rst
pylint/checkers/refactoring/refactoring_checker.py
tests/functional/c/consider/consider_using_sys_exit.txt

I wanted to copy paste the rational from the doc, but the rational was lacking. Also added confidence in the process and fixed the generated doc.

Add rational for ``consider-using-sys-exit``

---

doc/whatsnew/fragments/6001.false_positive
pylint/checkers/classes/class_checker.py
pylint/checkers/utils.py
tests/functional/a/assigning/assigning_non_slot.py
tests/functional/a/assigning/assigning_non_slot.txt
tests/functional/a/assigning/assigning_non_slot_4509.txt

Pylint was raising  ``assigning-non-slot`` when a class attribute was re-assigned, which I believe is incorrect given that `__slots__` is meant for instance attrs.
Closes #6001

class attrs should not emit assigning-non-slot msg

---

pylint/checkers/typecheck.py
pylint/extensions/docparams.py
pylint/testutils/unittest_linter.py
pylintrc

Refs #8013
Refs https://github.com/PyCQA/pylint/pull/7697#discussion_r1010869312

[style] Use default 'dummy-variable-rgx' and 'ignored-argument-names'

---

pylint/pyreverse/inspector.py
tests/pyreverse/functional/class_diagrams/regression/regression_8031.mmd
tests/pyreverse/functional/class_diagrams/regression/regression_8031.py

If multiple attributes are assigned using tuple unpacking, `pyreverse` crashed with an `AttributeError`.
This only occurs on the current main branch (2.16.0-dev).
Closes #8031

Prevent `pyreverse` crash when processing attributes assigned via tuple unpacking

---

doc/whatsnew/fragments/7779.false_positive
pylint/checkers/utils.py
pylint/checkers/variables.py
tests/functional/u/used/used_before_assignment_ternary.py
tests/functional/u/used/used_before_assignment_ternary.rc
tests/functional/u/used/used_before_assignment_ternary.txt

After investigation, there seems to be two main cases that trigger used-before-assignment false positives:
1. Ternary expression with walrus operator within attribute calls. Eg. `(foo if (foo:='foo') else 'bar').upper()`
2. Ternary expression with walrus operator nested in function calls. Eg. `str(str(foo if (foo:='foo') else 'bar'))`
This fix enforces a stricter check on whether a name may be assigned and used in the same statement.
Closes #7779

Fix `used-before-assignment` false positive

---

doc/whatsnew/fragments/8051.false_positive
pylint/checkers/exceptions.py
tests/functional/t/try_except_raise.py
tests/functional/t/try_except_raise.txt

Fixes false positive for `try-except-raise` with multiple exceptions in one except statement if exceptions are in different namespace.
Closes #8051

Fixes false positive for `try-except-raise` with multiple exceptions in one except statement

---

tests/functional/r/regression_02/regression_2567.py

This is fixed in astroid 2.13.2, it failed with astroid 2.12.14.
Closes #2567, depends on #8030

Regression tests for false positive ``no-member`` in decorated manager

---

CONTRIBUTORS.txt
script/.contributors_aliases.json

The idea is to automate more for easier release in #7362, so first we need to normalize. I made a web search to get the real name of Logilab employee from the email.

[contributors.txt] Fix aliases and name that were actually emails

---

tbump.toml

Otherwise tbump don't want to handle the current beta version.

[tbump] Fix the regex for semver version to accept '1.2.3a4'

---

doc/exts/pylint_messages.py
pylint/checkers/exceptions.py
pylint/checkers/similar.py
pylint/lint/pylinter.py
pylint/pyreverse/inspector.py
pylint/pyreverse/main.py
pylint/pyreverse/plantuml_printer.py
setup.cfg
tests/checkers/unittest_spelling.py
tests/test_func.py
tests/test_self.py

125 is a good start. The check was activated in pylint with value = 100, but flake8 is less lenient than pylint and does not make any exceptions (for docstrings, strings and comments in particular).

[style] Limit line length and complexity using flake8

---

.github/CODEOWNERS

No availability for review right now, so the automated review request is a bit much. It's possible to stay a pylint member without being spammed for it. (@areveny fyi)

[code owner] Remove areveny from her checkers temporarily

---

doc/whatsnew/fragments/8067.bugfix
pylint/checkers/method_args.py
pylint/checkers/refactoring/refactoring_checker.py
tests/functional/r/regression_02/regression_8067.py
tests/functional/r/regression_02/regression_8067.txt

Fixed a crash when inferring a value and using its qname on a slice

---

doc/whatsnew/fragments/8081.bugfix
pylint/checkers/utils.py

Prevent regex timeout issues for methods with unreasonable many leading underscores (> 80T).

Better regex for private attribute check

---

doc/whatsnew/fragments/8086.false_positive
pylint/checkers/utils.py
tests/functional/ext/code_style/cs_consider_using_augmented_assign.py
tests/functional/ext/code_style/cs_consider_using_augmented_assign.txt

Fix `consider-using-augmented-assign` nested attribute access

---

pylint/__pkginfo__.py
pyproject.toml
requirements_test_min.txt
script/bump_changelog.py
tbump.toml

We were not able to release on wednesday and we found a false positive recentely with #8088 so let's release another beta version and wait until the 30th to release 2.16.0 to see if anything else comes up.
Text for release note:
New beta release following a performance fix in the new pointless exception statement checks in https://github.com/PyCQA/pylint/issues/8073 and a false positive fixed in the unreleased ``consider-using-augmented-assign`` check in https://github.com/PyCQA/pylint/pull/8088. We're also using the latest version of astroid (2.13.3).

Bump pylint to 2.16.0-b1, update changelog

---

doc/whatsnew/fragments/7882.false_positive
pylint/checkers/variables.py
tests/functional/u/used/used_before_assignment_typing.py
tests/functional/u/used/used_before_assignment_typing.txt

Fix FP for `used-before-assignment` when reimporting name used in type annotation

---

doc/data/messages/s/subprocess-run-check/good.py
doc/data/messages/s/subprocess-run-check/related.rst
doc/user_guide/checkers/features.rst
pylint/checkers/stdlib.py
tests/functional/s/subprocess_run_check.txt

Fix consistency in ``subprocess-run-check`` and add rational

---

doc/data/messages/b/bare-except/bad.py
doc/data/messages/b/bare-except/details.rst
doc/data/messages/b/bare-except/good.py
doc/data/messages/b/bare-except/related.rst
doc/data/messages/b/broad-exception-caught/bad.py
doc/data/messages/b/broad-exception-caught/details.rst
doc/data/messages/b/broad-exception-caught/good.py
doc/data/messages/b/broad-exception-caught/related.rst
doc/data/messages/b/broad-exception-raised/related.rst
doc/user_guide/checkers/features.rst
pylint/checkers/exceptions.py

All messages do not have a good/bad example yet but the next step is giving the rationale. This one was easy to do. I feel like the rationale are lacking right now we have a lot of "emitted when ..." type message, but **when** it's emitted is / should be shown by the example, what we really need is a rationale for **why** the message exists in pylint. There's a lot of work if we want to change this part of the message other the whole code base.

[doc] Add details and related links for bare/broad-except

---

doc/whatsnew/fragments/8100.false_positive
pylint/checkers/typecheck.py
tests/functional/d/dataclass/dataclass_kw_only.txt
tests/functional/m/missing/missing_kwoa.py
tests/functional/m/missing/missing_kwoa.txt

Fix ``no-kwoa`` false positive for context managers.
Closes #8100

Fix `missing-kwoa` FP with With statements

---

doc/data/messages/p/positional-only-arguments-expected/bad.py
doc/data/messages/p/positional-only-arguments-expected/good.py
doc/data/messages/p/positional-only-arguments-expected/related.rst
doc/user_guide/checkers/features.rst
doc/user_guide/configuration/all-options.rst
doc/user_guide/messages/messages_overview.rst
doc/whatsnew/fragments/6489.new_check
pylint/checkers/method_args.py
tests/functional/p/positional_only_arguments_expected.py
tests/functional/p/positional_only_arguments_expected.rc
tests/functional/p/positional_only_arguments_expected.txt

This PR aims to implement a new checker `positional-only-arguments-expected` as requested.
Closes #6489

feat(6489): implement `positional-only-arguments-expected` checker

---

doc/data/messages/u/useless-import-alias/details.rst
doc/data/messages/u/useless-import-alias/related.rst
doc/user_guide/checkers/features.rst
doc/user_guide/configuration/all-options.rst
doc/whatsnew/fragments/6006.feature
pylint/checkers/imports.py
pylintrc
tests/checkers/unittest_imports.py
tests/functional/i/import_aliasing.txt
tests/regrtest_data/allow_reexport/__init__.py
tests/regrtest_data/allow_reexport/file.py

Add option to reduce amount of false-positives for `useless-import-alias` when choosing to use explicit reexports.
~Test might be a bit difficult as the result depends on the filename (if it's `__init__.py`). Not sure it's worth it.~
Closes #6006

Add `--allow-reexport-from-package` option

---

pylint/checkers/base/basic_checker.py
pylint/checkers/classes/class_checker.py
pylint/checkers/format.py
pylint/checkers/imports.py
pylint/checkers/refactoring/refactoring_checker.py
pylint/checkers/similar.py
pylint/checkers/spelling.py
pylint/checkers/stdlib.py
pylint/checkers/strings.py
pylint/checkers/typecheck.py
pylint/checkers/utils.py
pylint/checkers/variables.py
pylint/lint/expand_modules.py
pylint/lint/run.py
pylint/testutils/output_line.py
pylint/utils/ast_walker.py
pylintrc
tests/checkers/unittest_deprecated.py
tests/checkers/unittest_format.py
tests/lint/unittest_lint.py
tests/test_self.py

This PR tightens a few of the design constraints in the config file. No code is changed, although a few disable comments are added.
The rationale for the numbers is that they should be as low as possible without raising too many warnings. This way only the worst offenders are flagged. For example, there are only a few functions with more than 50 statements, and more with between 40 and 50 statements. So 50 is the cutoff. I'm not wed to any of the numbers in particular, but I think they're about where they should be.
Observe that several functions raise multiple warnings. Such functions are prime candidates for refactoring.

Tighten design constraints

---

.pre-commit-config.yaml
requirements_test_pre_commit.txt

Release notes: https://github.com/PyCQA/isort/releases/tag/5.12.0
Compare view: https://github.com/PyCQA/isort/compare/5.11.4...5.12.0
Necessary to fix isort with pre-commit.
--
Astroid: https://github.com/PyCQA/astroid/pull/1989

Update isort to 5.12.0

---

.pre-commit-config.yaml
doc/data/.flake8
doc/data/messages/b/bad-exception-cause/bad.py
doc/data/messages/c/class-variable-slots-conflict/bad.py
doc/data/messages/c/consider-using-dict-comprehension/bad.py
doc/data/messages/c/consider-using-dict-comprehension/details.rst
doc/data/messages/c/consider-using-f-string/bad.py
doc/data/messages/c/consider-using-set-comprehension/bad.py
doc/data/messages/c/consider-using-set-comprehension/details.rst
doc/data/messages/l/line-too-long/bad.py
doc/data/messages/l/line-too-long/pylintrc
doc/data/messages/n/no-self-use/details.rst
doc/data/messages/n/no-self-use/good.py
doc/data/messages/t/too-many-boolean-expressions/bad.py
doc/data/messages/t/too-many-format-args/bad.py

And upgrade existing unreasonable length. Reading ease is drastically reduced on read the doc after 103 chars (Because of horizontal scrolling)

[doc] Make sure that doc examples are of a reasonable length

---

.github/workflows/primer_comment.yaml

Fix broken primer comment workflow. The cache key needs to match the one for the `Primer / Run` workflow.

Fix primer comment job [ci]

---

tests/test_pragma_parser.py

This PR improves test_pragma_parser by adding the test `test_unknown_keyword_with_missing_messages`.
I believe this case is missing in test_pragma_parser.
In fact, we have some similar ones: `test_unknown_keyword_with_messages` and `test_unknown_keyword_without_messages`, but we do not check the case of unknown_keyword with missing messages:
```
"#pylint: unknown-keyword = missing-docstring" OK: test_unknown_keyword_with_messages
"#pylint: unknown-keyword = " missing test
"#pylint: unknown-keyword" OK: test_unknown_keyword_without_messages
```

improving test_pragma_parser

---

doc/whatsnew/fragments/8161.bugfix
pylint/checkers/imports.py

Closes #8161 @MarcSchmitzer we can add you as co-author if you want (need your commit email) :)

[crash] Fix crashes on python interpreter < 3.9

---

tests/functional/ext/typing/redundant_typehint_argument.py
tests/functional/ext/typing/redundant_typehint_argument.txt
tests/functional/ext/typing/redundant_typehint_argument_py310.py
tests/functional/ext/typing/redundant_typehint_argument_py310.rc
tests/functional/ext/typing/redundant_typehint_argument_py310.txt

| ✓   | :hammer: Testing   |
Adds a few test cases for the `redundant-typehint-argument` check, just to verify existing behavior.

Add some test cases for redundant type check

---

doc/data/messages/b/bad-configuration-section/details.rst
doc/data/messages/b/bad-configuration-section/good.py
doc/data/messages/p/parse-error/good.py
doc/data/messages/u/using-f-string-in-unsupported-version/bad.py
doc/data/messages/u/using-f-string-in-unsupported-version/details.rst
doc/data/messages/u/using-f-string-in-unsupported-version/good.py
doc/data/messages/u/using-f-string-in-unsupported-version/pylintrc
doc/exts/pylint_messages.py

Saw some issue while reading the doc.
Before:
After:

Fix some doc about messages

---

tests/primer/packages_to_prime.json

I think this needs to go into main before the #8153 ?

Add poetry-core as a repository to prime

---

doc/whatsnew/fragments/8207.bugfix
pylint/checkers/refactoring/refactoring_checker.py
tests/functional/r/regression_02/regression_8207.py

Fix crash when an attribute node was used inside an unary op

---

doc/whatsnew/fragments/8148.bugfix
pylint/checkers/variables.py
tests/regrtest_data/pkg_mod_imports/__init__.py
tests/regrtest_data/pkg_mod_imports/base/errors.py
tests/regrtest_data/test_no_name_in_module.py
tests/test_self.py

Closes #8148
I was able to reproduce the original issue FP but also came up with a non-lib specific example that raised this issue.

fix no-name-in-module when variable is same as module name

---

examples/custom.py

The example lint rule references a deprecated attribute, so this changes the example to use the new recommended attribute.

Don't use ``self.config`` since it's deprecated

---

doc/development_guide/how_tos/custom_checkers.rst

Don't use deprecated attribute in example test. Wish I'd caught this in my earlier PR 🤷 . Probably this could use a lint rule or something, but that's beyond my purview for the time being.

Don't use deprecated attribute in example test

---

pylint/checkers/utils.py

Related to #8071. Small refactor to utility function `is_defined`. Nothing functional is changed.
Sorry @Pierre-Sassoulas. Jacob pointed out this inconsistency for the guard clauses in one of his reviews, but I misunderstood it then and did not manage correct it before merge.

Minor refactor to util function

---

doc/user_guide/configuration/all-options.rst
doc/user_guide/usage/run.rst
doc/whatsnew/fragments/8154.feature
examples/pylintrc
pylint/config/argument.py
pylint/config/option.py
pylint/lint/__init__.py
pylint/lint/base_options.py
pylint/lint/expand_modules.py
pylint/lint/parallel.py
pylint/lint/pylinter.py
pylint/lint/utils.py
pylint/pyreverse/main.py
pylint/testutils/pyreverse.py
tests/lint/unittest_expand_modules.py
tests/lint/unittest_lint.py
tests/primer/packages_to_prime.json
tests/pyreverse/conftest.py
tests/pyreverse/functional/class_diagrams/namespaces/pep420/pep420.dot
tests/pyreverse/functional/class_diagrams/namespaces/pep420/pep420.mmd
tests/pyreverse/functional/class_diagrams/namespaces/pep420/pep420.puml
tests/pyreverse/functional/class_diagrams/namespaces/pep420/pep420.py
tests/pyreverse/functional/class_diagrams/namespaces/pep420/pep420.rc
tests/pyreverse/test_main.py
tests/pyreverse/test_pyreverse_functional.py
tests/regrtest_data/pep420/wrapper/project/namespace/package/logging/__init__.py
tests/regrtest_data/pep420/wrapper/project/namespace/package/logging/wrapper/__init__.py
tests/test_check_parallel.py
tests/test_deprecation.py

Fixes #7959 by introducing the concept of source roots.
Closes #8154

Support Implicit Namespace Packages (PEP 420)

---

doc/whatsnew/fragments/8125.bugfix
pylint/checkers/variables.py
tests/functional/u/used/used_before_assignment_ternary.py

Fix false positive when the walrus operator is used with the ternary operator in dictionary key/value initialization.
Closes #8125

Fix `used-before-assignment` false positive for walrus operator in dictionary

---

doc/whatsnew/fragments/7851.feature
pylint/pyreverse/main.py
tests/pyreverse/test_main.py

Add the `--version` option to `pyreverse`.
Note that this does not yet fix the crash mentioned in the referenced issue if somebody passes some other unknown version.
```console
% pyreverse --version
pyreverse is included in pylint:
pylint 2.17.0-dev0
astroid 2.14.1
Python 3.10.4 (main, May 15 2022, 08:21:46) [Clang 12.0.5 (clang-1205.0.22.9)]
```
Refs #7851

Add version option to `pyreverse`

---

doc/whatsnew/fragments/8252.false_positive
pylint/checkers/variables.py
tests/functional/u/undefined/undefined_variable_py38.py
tests/functional/u/undefined/undefined_variable_py38.txt

Fix FP for used-before-assignment with assignment expressions in containers

---

.gitattributes
doc/data/messages/u/unexpected-line-ending-format/bad.py
doc/data/messages/u/unexpected-line-ending-format/details.rst
doc/data/messages/u/unexpected-line-ending-format/good.py
doc/data/messages/u/unexpected-line-ending-format/pylintrc
doc/data/messages/u/unexpected-line-ending-format/related.rst

Add doc for unexpected-line-ending-format / C0328
Refs #5953

doc unexpected-line-ending-format

---

doc/whatsnew/fragments/8205.false_positive
pylint/checkers/typecheck.py
pylint/constants.py
tests/functional/d/dataclass/dataclass_typecheck.txt
tests/functional/ext/typing/redundant_typehint_argument.py
tests/functional/ext/typing/redundant_typehint_argument_py310.py
tests/functional/i/isinstance_second_argument.txt
tests/functional/i/isinstance_second_argument_py310.py
tests/functional/i/isinstance_second_argument_py310.rc
tests/functional/i/isinstance_second_argument_py310.txt

Fixes false positive for `isinstance-second-argument-not-valid-type` with union types.
Closes #8205

Fix invalid type false positive

---

doc/data/messages/d/duplicate-code/bad/apple.py
doc/data/messages/d/duplicate-code/bad/orange.py
doc/data/messages/d/duplicate-code/details.rst
doc/data/messages/d/duplicate-code/good.py
doc/data/messages/d/duplicate-code/good/apple.py
doc/data/messages/d/duplicate-code/good/fruit.py
doc/data/messages/d/duplicate-code/good/orange.py
doc/exts/pylint_messages.py
doc/test_messages_documentation.py
pylint/testutils/reporter_for_tests.py
tests/functional/e/empty_docstring.rc
tests/functional/ext/plugin_does_not_exists.py
tests/functional/ext/plugin_does_not_exists.txt

Refs https://github.com/PyCQA/pylint/issues/7897
Closes #7143

Add support for more complicated documentation examples

---

doc/whatsnew/fragments/8290.feature
pylint/config/argument.py
pylint/config/option.py
pylint/lint/base_options.py
pylint/pyreverse/main.py
tests/lint/unittest_lint.py

Add globbing pattern support for source-roots.
Closes #8290

Support globbing patterns for source-roots

---

doc/exts/pylint_messages.py
pylint/checkers/stdlib.py
tests/functional/s/shallow_copy_environ.txt

In https://github.com/PyCQA/pylint/pull/7162, "we decreed" that the `bad_code` goes first, then the `good_code`.
Fixup current changes, to revert "back to standards".
Additionally, tackle the comment here
https://github.com/PyCQA/pylint/pull/8287#issuecomment-1437983737
"Message emitted" is technically still code (`%-formatting`); let us make it stand out properly.
Refs https://github.com/PyCQA/pylint/pull/8287
Closes https://github.com/PyCQA/pylint/issues/8321

Documentation: Order of messages

---

doc/data/messages/s/suppressed-message/bad.py
doc/data/messages/s/suppressed-message/details.rst
doc/data/messages/s/suppressed-message/good.py
doc/test_messages_documentation.py

The message would not be triggered if implicit-str-concat is not activated too. I initially wanted to activate invalid-name so we follow pep8 in our examples but there's more than 50 violations right now. So 'implicit-str-concat' it is.
Refs #7897 #5953

[doc] Add an example for suppressed-message

---

doc/whatsnew/fragments/8280.false_negative
pylint/checkers/base/basic_error_checker.py
pylint/checkers/refactoring/refactoring_checker.py
tests/functional/i/inconsistent/inconsistent_returns.py
tests/functional/i/inconsistent/inconsistent_returns.txt

Fixes false negative for `inconsistent-returns` by only counting `while` loops as return-ended when they are obviously non-terminating.
Closes #8280

Only count obviously non-terminating while-loops as return-ended

---

doc/development_guide/contributor_guide/governance.rst
doc/development_guide/contributor_guide/index.rst
doc/whatsnew/fragments/8329.other

This is done due to clarify our standing on moderation issues related to the recent PyCQA discussion, and also as part of the work done for the OpenSSF best practices (that Tidelift is paying me to do to make the software supply chain more secure). To be clear having an autocrat behaving like an asshole as the owner of a project is a liability for everyone in the software supply chain. Making sure that this does not happen for pylint is valuable. The way to become a maintainer is also a frequently asked question.

Document the governance model and the path to maintainership

---

doc/data/messages/n/non-ascii-file-name/bad/bàd.py
doc/data/messages/n/non-ascii-file-name/bad/not_bétter.py
doc/data/messages/n/non-ascii-file-name/details.rst
doc/data/messages/n/non-ascii-file-name/good.py
doc/data/messages/n/non-ascii-file-name/related.rst
doc/user_guide/checkers/features.rst
doc/user_guide/configuration/all-options.rst
pylint/checkers/non_ascii_names.py
tests/functional/n/non_ascii_name/non_ascii_name_loł.txt

Move links to related.rst, and upgrade the message shown for python 3.5+
Replace #8324, refs #5953

[doc] Add an example for 'non-ascii-file-name'

---

tests/checkers/unittest_imports.py

[test] Permits to debug more easily 'test_allow_reexport_package'

---

tests/checkers/unittest_imports.py
tests/config/pylint_config/test_pylint_config_generate.py
tests/config/test_per_directory_config.py
tests/test_pylint_runners.py

Closes #8342, and fix test that could create similar bugs with specifics configurations.

[test] Use an empty pylintrc so tests to not depend on system's conf

---

doc/whatsnew/fragments/8307.bugfix
pylint/checkers/base/name_checker/checker.py
tests/functional/g/globals.py
tests/functional/g/globals.txt
tests/functional/n/name/name_styles.py
tests/functional/n/name/name_styles.txt

Prevent emitting ``invalid-name`` for the line on which a ``global`` statement is declared.
The `visit_global` function seems to be redundant because the `visit_assignname` method is already running the [self._check_name("const", node.name, node)](https://github.com/PyCQA/pylint/blob/main/pylint/checkers/base/name_checker/checker.py#L446) method on the node representing the module-level assignment.
Closes #8307

Prevent emitting ``invalid-name``

---

doc/whatsnew/fragments/8307.bugfix
pylint/checkers/base/name_checker/checker.py
tests/functional/g/globals.py
tests/functional/g/globals.txt
tests/functional/n/name/name_styles.py
tests/functional/n/name/name_styles.txt

Manually cherry pick invalid name on global fix

---

pylint/checkers/spelling.py
tests/checkers/unittest_spelling.py

Following a failed attempt to add functional tests for spelling checker in #6137. Branch forgotten for some time but recovered after a global cleanup 😄

[spelling checker] Better help message and code organization

---

.pyenchant_pylint_custom_dict.txt
doc/user_guide/usage/run.rst
doc/whatsnew/fragments/8310.feature
pylint/config/config_initialization.py
tests/lint/unittest_lint.py
tests/test_self.py

Support globbing pattern for input specification

---

examples/deprecation_checker.py
pylint/checkers/base/basic_checker.py
pylint/checkers/utils.py
pylint/config/arguments_provider.py
pylint/config/config_initialization.py
pylint/extensions/confusing_elif.py
pylint/extensions/typing.py
pylint/lint/run.py
pylint/reporters/text.py
pylint/testutils/_primer/primer_compare_command.py
pylint/testutils/lint_module_test.py
setup.cfg
tests/message/unittest_message_definition_store.py

Changing flake8 to have a max-line-length of 115 because there are issues with changing it to 103. This makes the code easier to understand.
Refs #XXXX
Closes #XXXX

Changing flake8 to have max-line-length of 115

---

doc/whatsnew/fragments/8370.false_positive
pylint/checkers/spelling.py
tests/checkers/unittest_spelling.py

enchant does not understand class name well enough so it creates false positives, and mypy type ignore comments with additional text are a syntax error anyway, so raising a spelling mistakes for it is not really important.

[spelling] Ignore spelling in type/mypy type ignore comments

---

.pre-commit-config.yaml
doc/data/ruff.toml
pylint/config/config_initialization.py
pyproject.toml
setup.cfg

ruff is faster and support pyproject.toml and python 3.7. flake8-typing-import is not implemented but it checks for things in python version < 3.7.2 that we do not support. Fix main following #8362 that broke it.

[pre-commit] Transition from flake8/autoflake to ruff

---

doc/data/messages/m/missing-format-string-key/bad.py
doc/data/messages/m/missing-format-string-key/details.rst

[doc] Add an example for 'missing-format-string-key'

---

doc/data/messages/l/line-too-long/details.rst

Closes #4802 with a doc update as described there.

Document ignoring pragmas for calculating line length

---

.github/workflows/codeql-analysis.yml
.github/workflows/tests.yaml

Closes #8285
Extends our [existing](https://github.com/PyCQA/pylint/blob/c356a3c99388a192dd57beea99c4d043e15cff2c/.github/workflows/primer-test.yaml#L19-L21) `concurrency` infrastructure that cancels some in-progress jobs when a PR is updated to cancel also the tests workflow and the codeql-analysis workflow.
Does not affect pushes to main.
[Example cancelled run](https://github.com/jacobtylerwalls/pylint/actions/runs/4336747449)

Cancel previous tests when pushing to PRs

---

doc/whatsnew/fragments/8205.false_positive
pylint/checkers/typecheck.py
pylint/constants.py
tests/functional/d/dataclass/dataclass_typecheck.txt
tests/functional/ext/typing/redundant_typehint_argument.py
tests/functional/i/isinstance_second_argument.txt
tests/functional/i/isinstance_second_argument_py310.py
tests/functional/i/isinstance_second_argument_py310.rc
tests/functional/i/isinstance_second_argument_py310.txt

(cherry picked from commit e64f0437388298c7f8514a6755c3c27a0d9a35f2)

[Backport maintenance/2.16.x] Fix invalid type false positive (#8206)

---

doc/whatsnew/fragments/8387.feature
pylint/checkers/imports.py
pylint/checkers/typecheck.py
pylint/pyreverse/inspector.py
pylint/pyreverse/writer.py
pyproject.toml
requirements_test_min.txt

Upgrade to astroid 2.15.0

---

pylint/checkers/async.py
pylint/checkers/base/basic_checker.py
pylint/checkers/classes/class_checker.py
pylint/checkers/classes/special_methods_checker.py
pylint/checkers/dunder_methods.py
pylint/checkers/exceptions.py
pylint/checkers/refactoring/implicit_booleaness_checker.py
pylint/checkers/refactoring/refactoring_checker.py
pylint/checkers/stdlib.py
pylint/checkers/strings.py
pylint/checkers/typecheck.py
pylint/checkers/utils.py
pylint/checkers/variables.py
pylint/extensions/_check_docs_utils.py
pylint/extensions/overlapping_exceptions.py
pylint/pyreverse/diagrams.py
pylint/pyreverse/inspector.py

Blocked on the new `astroid` release.

Use ``UninferableBase`` instead of ``Uninferable``

---

doc/whatsnew/fragments/5288.false_positive
tests/functional/u/unpacking/unpacking_non_sequence_py310.py
tests/functional/u/unpacking/unpacking_non_sequence_py310.rc

Add regression test for #5288

---

doc/whatsnew/fragments/8401.breaking
pylint/checkers/base_checker.py
tests/checkers/unittest_base_checker.py

[deprecation] Remove ``get_message_definitions`` from ``BaseChecker``

---

doc/whatsnew/fragments/8407.breaking
pylint/checkers/similar.py
pylint/lint/message_state_handler.py
pylint/lint/parallel.py
pylint/lint/pylinter.py
pylint/utils/file_state.py
tests/test_deprecation.py

``modname`` and ``msg_store`` are now required to be given in FileState, ``collect_block_lines`` has also been removed.

[FileState] Deprecation enactment for 3.0.0

---

pylint/pyreverse/diagrams.py
pylint/pyreverse/dot_printer.py
pylint/pyreverse/inspector.py
pylint/pyreverse/mermaidjs_printer.py
pylint/pyreverse/plantuml_printer.py
pylint/pyreverse/printer.py
pylint/pyreverse/utils.py
pylint/pyreverse/vcg_printer.py
pylint/pyreverse/writer.py

After removing the support for `__implements__` with #8404 there are now some parts in the code that can be removed as well.
Refs #8404

`pyreverse`: remove remaining code parts related to `__implements__`

---

.coveragerc

The TODO statement in this file says to remove the file names when the files have been deleted, so I think this is a good time to remove the files from ".coveragerc".
Refs #8405

Removing files from coveragerc since they have been deleted

---

doc/whatsnew/fragments/8412.breaking
pylint/reporters/text.py

I think we could be a lot more liberal with the breaking change for small internal things like that.

[colorize_ansi] Remove the possibility to use anything else than a MessageStyle

---

doc/whatsnew/fragments/8361.bugfix
pylint/checkers/utils.py
pylint/lint/run.py

Closes #8361 
Created a new backport label (should I have?)

Clear LRU caches on pylint utilities

---

.pre-commit-config.yaml
doc/data/ruff.toml
pyproject.toml
requirements_test_pre_commit.txt

Faster, but I'm not sure if ruff handle first party / third parties correctly. It's good enough for the doc example anyway, and the per file configuration is better than a regex...

[pre-commit] Configure ruff to sort import in the doc examples

---

doc/whatsnew/fragments/8434.bugfix
pylint/checkers/utils.py
tests/checkers/unittest_utils.py

Fix a crash when `TYPE_CHECKING` is used without importing it

---

doc/user_guide/configuration/all-options.rst
doc/whatsnew/fragments/8403.false_positive
examples/pylintrc
examples/pyproject.toml
pylint/checkers/classes/class_checker.py
tests/functional/a/attribute_defined_outside_init_py38.py
tests/functional/a/attribute_defined_outside_init_py38.rc

This patch adds `unittest.IsolatedAsyncioTestCase` asynchronous "setUp" coroutine to the list of "defining-attr-methods", in order to silence "attribute-defined-outside-init" (W0201) false positive.
---
Feel free to edit this PR as needed; I'm not sure how we should handle Python 3.8+ constraint here.
Thanks, bye :wave:

Add Python 3.8+ `asyncSetUp` to "defining-attr-methods" list

---

.github/workflows/primer_run_main.yaml

The 3.7 primer job on main regularly takes about an hour and fails most of the time now, especially since we added `poetry-core`. Eventually, a better multiprocessing design will help. For now, bump the limit to the same as the workflow on PRs:
https://github.com/PyCQA/pylint/blob/b968fa062f801626426ef399401c4530e13fcc49/.github/workflows/primer_run_pr.yaml#L38

Increase new primer timeout to 120m

---

pylint/checkers/utils.py
pylint/checkers/variables.py

Seen when adding ruff specific checks, it suddenly appeared following unrelated changes, I don't know why.

[cyclic-import] Break cycle between pylint.checkers.util / variables

---

pylint/checkers/base/basic_checker.py
pylint/checkers/stdlib.py
pylint/checkers/typecheck.py
pylint/checkers/utils.py
pylint/checkers/variables.py
pylint/config/find_default_config_files.py
pylint/lint/expand_modules.py
pylint/lint/parallel.py
pylint/lint/pylinter.py
pylint/reporters/ureports/nodes.py
pyproject.toml
tests/checkers/unittest_format.py
tests/lint/unittest_lint.py
tests/primer/test_primer_external.py
tests/primer/test_primer_stdlib.py
tests/test_func.py
tests/test_self.py
tests/testutils/_primer/test_package_to_lint.py
tests/testutils/_primer/test_primer.py

Depends on #8448, permitted to detect https://github.com/charliermarsh/ruff/issues/3496

[pre-commit] Add ruff specific rules in ruff configuration

---

doc/whatsnew/fragments/8463.internal
pylint/lint/pylinter.py
tests/lint/test_pylinter.py

Enacting planned deprecations.

[deprecation] 'Pylinter.check' now takes sequence of str only

---

doc/whatsnew/fragments/8464.internal
pylint/reporters/text.py

Enacting of planned deprecations.

[deprecation] 'ColorizedTextReporter' only accepts 'ColorMappingDict'

---

doc/whatsnew/fragments/8465.user_action
doc/whatsnew/fragments/8466.internal
pylint/testutils/checker_test_case.py

[deprecation] end_line and end_col_offset required in functional tests

---

tests/test_regr.py

Enacting deprecation, but I'm not sure it's supposed to still be broken.

[test] Remove 'test_pylint_config_attr'

---

tests/test_check_parallel.py

It was fixed previously I don't know when.

[test multiprocessing] Add regression test against removing dill for unpickable plugins

---

doc/whatsnew/fragments/8473.internal
pylint/message/message_definition.py

[deprecation] Make 'py_version' required for 'MessageDefinition.may_be_emitted'

---

doc/whatsnew/fragments/8472.internal
pylint/lint/run.py
pylint/testutils/_run.py

[deprecation] Remove 'do_exit' from the 'Run' constructor

---

doc/whatsnew/fragments/8476.internal
doc/whatsnew/fragments/8477.internal
pylint/message/message.py

[deprecation] Message.location must be a 'MessageLocationTuple'

---

doc/whatsnew/fragments/8453.bugfix
pylint/checkers/imports.py
tests/checkers/unittest_imports.py

This PR updates the preferred-modules functionality to avoid incorrect partial matches from the configuration, as highlighted by @ssbarnea via #8453. Also added is a new test to simulate the example partial match which was provided in the issue (`random` vs `getrandom`).
Closes #8453

Fix incorrect preferred-modules matches

---

doc/whatsnew/fragments/8475.internal
pylint/checkers/utils.py
tests/checkers/unittest_utils.py

Enacting planned deprecations.

[deprecation] Remove all duplicated typing guard check functions

---

doc/whatsnew/fragments/8496.false_positive
pylint/checkers/base/basic_checker.py
tests/functional/u/unnecessary/unnecessary_lambda.py
tests/functional/u/unnecessary/unnecessary_lambda.txt

Fix `unnecessary-lambda` false positive for lambdas using its parameters in their body

---

doc/whatsnew/fragments/8474.internal
pylint/testutils/output_line.py
tests/testutils/test_output_line.py

[deprecation] Make 'OutputLine' require a fixed number of args

---

doc/whatsnew/fragments/8485.false_positive

Follow up to https://github.com/PyCQA/pylint/pull/8488.
I'm making ``pre-commit`` a required check to avoid this in the future.

Fix news fragment after incorrect auto-merge

---

doc/whatsnew/2/2.13/summary.rst

Refs https://github.com/pylint-dev/pylint/pull/8516#discussion_r1153781931

[doc] Fix missing spaces in 2.13's whatsnew

---

doc/whatsnew/fragments/8504.bugfix
pylint/pyreverse/writer.py
tests/pyreverse/test_writer.py

When calling pyreverse with an output filename like that ends with a "/" character like
```
pyreverse -o png -p packagename/ path_to_project/
``` 
the program crashes. 
Added bugfix to strip those characters at the end of the output filename
Closes #8504

[pyreverse] Bugfix: strip "/" at the end of the file 

---

tests/pyreverse/test_writer.py

See https://github.com/pylint-dev/pylint/pull/8517#discussion_r1155303397
Turned out that by using the `monkeypatch` fixture there is no need to touch the existing tests.

refactor `pyreverse` tests to use temporary directory

---

doc/whatsnew/fragments/7506.false_positive
requirements_test.txt
tests/functional/u/unused/unused_import.py
tests/functional/u/unused/unused_import.txt

Closes #7506 
Depends on PyCQA/astroid#2049

Add regression test for #7506

---

pyproject.toml
requirements_test_min.txt

Upgrade astroid to 2.15.2

---

doc/whatsnew/2/2.17/index.rst
doc/whatsnew/fragments/8485.false_positive
doc/whatsnew/fragments/8487.false_positive
doc/whatsnew/fragments/8496.false_positive
doc/whatsnew/fragments/8504.bugfix
pylint/__pkginfo__.py
tbump.toml
towncrier.toml

- ``invalid-name`` now allows for integers in ``typealias`` names:
- now valid: ``Good2Name``, ``GoodName2``.
- still invalid: ``_1BadName``.
Closes #8485 (`#8485 <https://github.com/PyCQA/pylint/issues/8485>`_)
- No longer consider ``Union`` as type annotation as type alias for naming
checks.
Closes #8487 (`#8487 <https://github.com/PyCQA/pylint/issues/8487>`_)
- ``unnecessary-lambda`` no longer warns on lambdas which use its parameters in
their body (other than the final arguments), e.g.
``lambda foo: (bar if foo else baz)(foo)``.
Closes #8496 (`#8496 <https://github.com/PyCQA/pylint/issues/8496>`_)
- Fix a crash in pyreverse when "/" characters are used in the output filename
e.g pyreverse -o png -p name/ …

Release branch 2.17.2

---

doc/whatsnew/fragments/3670.false_positive
pylint/checkers/variables.py
tests/functional/u/unused/unused_argument.py
tests/functional/u/unused/unused_argument.txt

Problem: the special method `__new__` must match the arguments of the `__init__` method even if `__new__` method does not use them. This generate `unused-argument` for the `__new__` method.
Fix: the unused arguments check should not be done on the `__new__` method if the `__init__` method is defined in the same class.
Closes https://github.com/pylint-dev/pylint/issues/3670

Fix check unused arguments false positive bug

---

doc/whatsnew/fragments/8410.false_positive
pylint/checkers/logging.py
tests/functional/l/logging/logging_not_lazy.py
tests/functional/l/logging/logging_not_lazy.txt

Do not emit `logging-not-lazy` for explicitly concatenated strings.

---

doc/whatsnew/fragments/8540.false_positive
pylint/checkers/base/name_checker/checker.py
tests/functional/t/typealias_naming_style_default.py
tests/functional/t/typealias_naming_style_rgx.py

Those variables shouldn't be treated as TypeAlias.
Closes #8540

Fix typelias `invalid-name` false positives for Union variables without assignment.

---

doc/whatsnew/fragments/8424.false_positive
pylint/checkers/typecheck.py
tests/functional/i/isinstance_second_argument_py310.py
tests/functional/i/isinstance_second_argument_py310.txt

Fix false positive for `isinstance-second-argument-not-valid-type` when union type includes `None`, for example:
```py
isinstance(0, int | None)
```
Closes #8424

Fix isinstance-second-argument-not-valid-type for union types with None

---

doc/whatsnew/fragments/8536.false_negative
pylint/checkers/base/name_checker/checker.py
tests/functional/t/typealias_naming_style_default.py
tests/functional/t/typealias_naming_style_default.txt

Also check the typealias naming style for TypeAlias variables defined in functions.

---

doc/whatsnew/fragments/8555.false_positive
pylint/checkers/method_args.py
tests/functional/p/positional_only_arguments_expected.py

Fix false positive for ``positional-only-arguments-expected`` when a
function contains both a positional-only parameter that has a default value, and ``**kwargs``.
Closes #8555

Fix false positive for ``positional-only-arguments-expected``

---

.pre-commit-config.yaml
pylint/checkers/misc.py
pylint/lint/pylinter.py
pylint/lint/run.py
pylint/testutils/testing_pylintrc

This PR refactors code in a way that it removes explicit disable of Info Messages during creation of `Run` class but instead define it in message definition. This fixes issue when Message documentation is not showing Caution Bar that message is disabled by default.

Disable Info linters in definition instead of Run class

---

doc/whatsnew/fragments/8559.false_negative
pylint/checkers/typecheck.py
tests/functional/a/arguments_positional_only.py
tests/functional/a/arguments_positional_only.rc
tests/functional/a/arguments_positional_only.txt

Fix false negative for ``no-value-for-parameter`` when a function, whose signature contains both a positional-only parameter ``name`` and also ``*kwargs``, is called with a keyword-argument for ``name``.
```python
def required_positional_with_var_kwargs(a, /, **_kwargs):
return a
required_positional_with_var_kwargs(a=43)
```
Closes #8559

Fix false negative for `no-value-for-parameter`

---

doc/whatsnew/fragments/8198.bugfix
pylint/checkers/variables.py
tests/functional/u/used/used_before_assignment_scoping.py
tests/functional/u/used/used_before_assignment_scoping.txt

This PR addresses false negative cases for `used-before-assignment`, when imports are made within `TYPE_CHECKING` guard clauses.
The root cause of these false negatives is the consumption of `Import`, `ImportFrom` nodes within `TYPE_CHECKING` clauses. Upon consumption, subsequent usages are not evaluated by the checker.
My approach is to not consume these nodes and keep track of usage scopes, so that errors can be emitted in multiple scopes.
Feel free to discuss alternative solutions! 🙂 
Closes #8198

Fix `used-before-assignment` TYPE_CHECKING false negatives

---

pylint/checkers/nested_min_max.py
tests/checkers/unittest_stdlib.py
tests/pyreverse/test_printer.py

Refs pylint-dev/astroid@c59a4a4bdcc7b3593ea93aba1b72a2b516852bb6
Shows a real-world example of inventing nodes without parents.

Cope with changes to `Starred`, `AssignAttr`, and `Arguments` constructors

---

doc/whatsnew/fragments/8563.bugfix
pylint/checkers/refactoring/refactoring_checker.py
tests/functional/c/consider/consider_using_generator.py
tests/functional/c/consider/consider_using_generator.txt

Improve output of `consider-using-generator` message for `min()` calls with `default` keyword

---

doc/whatsnew/fragments/8167.false_positive
pylint/checkers/variables.py
tests/functional/u/used/used_before_assignment.py
tests/functional/u/used/used_before_assignment.txt

Fix FP `used-before-assignment` for statements guarded under same test

---

pylint/checkers/variables.py

A small change on #8431 to update the container (of [scope nodes](https://pylint.readthedocs.io/projects/astroid/en/latest/api/base_nodes.html#astroid.nodes.NodeNG.scope)) type to `LocalsDictNodeNG` which is more specific compared to the base class `NodeNG`. 
Nothing functional is changed, apologies for any inconvenience caused!

Minor refactor on type annotation

---

pyproject.toml
requirements_test_min.txt
tests/functional/r/regression/regression_4439.py

Upgrade astroid for next patch release.

Upgrade astroid to 2.15.3

---

doc/whatsnew/fragments/1954.performance
pylint/checkers/utils.py
script/check_newsfragments.py
towncrier.toml

For one project in the pylint primer (music21), provides 15% speedup _linting the entire project_. (171.6s -> 145.6s on an M1 mac running python3.11.)
I think we should batch the performance improvements in 3.0 and describe them all with a set of benchmarks at the end, so adding a skip news label.

Cache `class_is_abstract()`

---

pylint/testutils/_primer/primer_run_command.py

This dramatically sped up the 3.7 primer job on my fork. See [run](https://github.com/jacobtylerwalls/pylint/actions/runs/4778850281/jobs/8495537389).

Clear cache between primer package runs

---

pylint/checkers/typecheck.py
pylint/checkers/utils.py
pylint/checkers/variables.py

Fallout from https://github.com/pylint-dev/astroid/pull/2115 - required for the next astroid update.
Fix `isinstance` checks now that `nodes.FunctionDef` doesn't inherit from `nodes.Lambda`.
Changes are compatible with the current astroid version, so don't need to wait to fix these.

Fix `FunctionDef` isinstance checks

---

pylint/checkers/typecheck.py

The `Load`, `Store`, and `Del` constants have been deprecated for quite some time in favor of `astroid.Context`.
Refs https://github.com/pylint-dev/astroid/pull/2141

Use `astroid.Context` enum

---

CONTRIBUTORS.txt
doc/whatsnew/2/2.17/index.rst
doc/whatsnew/fragments/3670.false_positive
doc/whatsnew/fragments/7506.false_positive
doc/whatsnew/fragments/8410.false_positive
doc/whatsnew/fragments/8424.false_positive
doc/whatsnew/fragments/8500.false_positive
doc/whatsnew/fragments/8540.false_positive
doc/whatsnew/fragments/8555.false_positive
doc/whatsnew/fragments/8563.bugfix
doc/whatsnew/fragments/8570.false_positive
pylint/__pkginfo__.py
tbump.toml
towncrier.toml

What's new in Pylint 2.17.3?
----------------------------
Release date: 2023-04-24
- Fix `unused-argument` false positive when `__new__` does not use all the
arguments of `__init__`.
Closes #3670 
- Fix ``unused-import`` false positive for usage of ``six.with_metaclass``.
Closes #7506 
- `logging-not-lazy` is not longer emitted for explicitly concatenated string
arguments.
Closes #8410 
- Fix false positive for isinstance-second-argument-not-valid-type when union
types contains None.
Closes #8424 
- Fixed `unused-import` so that it observes the `dummy-variables-rgx` option.
Closes #8500 
- `Union` typed variables without assignment are no longer treated as
`TypeAlias`.
Closes #8540 
- Fix false positive for ``positional-only-arguments-expected`` …

Bump pylint to 2.17.3, update changelog

---

doc/whatsnew/fragments/8613.false_positive
pylint/constants.py
tests/functional/ext/bad_dunder/bad_dunder_name.py

Fix a false positive for ``bad-dunder-name`` when there is a user-defined ``__index__`` method.
Closes #8613

Fix a false positive for ``bad-dunder-name`` 

---

pyproject.toml
requirements_test_min.txt

Did another release. Maybe a bit early but the less breaking changes we batch, the easier these bump PRs are.
https://github.com/pylint-dev/astroid/milestone/77?closed=1
https://github.com/pylint-dev/astroid/releases/tag/v3.0.0a2

Bump astroid to 3.0.0a2

---

doc/whatsnew/fragments/8632.bugfix
pyproject.toml

Will require a real fix later
Refs #8632

[tomlkit] Limit the maximum version of tomlkit

---

doc/exts/pylint_options.py
doc/user_guide/configuration/all-options.rst
doc/whatsnew/fragments/8632.bugfix
pylint/config/arguments_manager.py
pyproject.toml

Reverts https://github.com/pylint-dev/pylint/pull/8633 
Fixes https://github.com/pylint-dev/pylint/issues/8632

Make sure a ``tool`` table is created in ``toml`` generation

---

pylint/testutils/_primer/primer_prepare_command.py

Follow-up to 87a4d672a8661aa61d5717fd902315d9563e33b6.
The shortening of the commit SHA to 8 chars was done in only 1 of 3 places, making it so the primer would fail the subsequent time after regenerating the list of projects.

[primer] Fix commit string generation

---

.pyenchant_pylint_custom_dict.txt
doc/user_guide/usage/run.rst
doc/whatsnew/fragments/7163.other
pylint/config/find_default_config_files.py
tests/config/test_find_default_config_files.py

Search for pyproject.toml in parent directories.
Closes #3289

Search for pyproject.toml config file in parent dirs

---

doc/data/messages/i/implicit-str-concat/details.rst

Creates `doc/data/messages/i/implicit-str-concat/details.rst`
and provide some guidance on how to configure this rule to be more strict.
For reference, `check-str-concat-over-line-jumps` was introduced in #2716

[Doc] Create implicit-str-concat/details.rst

---

doc/data/messages/i/implicit-str-concat/details.rst
doc/data/messages/i/implicit-str-concat/related.rst

Follow-up of #8648
I think it's worth adding this important warning.
Ping @Pierre-Sassoulas who reviewed & merged the previous PR

[Doc] Improving implicit-str-concat/details.rst

---

doc/whatsnew/3/3.0/index.rst
doc/whatsnew/3/index.rst
tox.ini

Small tox/doc upgrade following a readthedoc debug in #8630

Upgrade 'tox - docs' to match readthedoc online and for performance

---

doc/data/messages/u/use-implicit-booleaness-not-comparison-to-string/details.rst
doc/data/messages/u/use-implicit-booleaness-not-comparison-to-zero/details.rst
doc/data/messages/u/use-implicit-booleaness-not-comparison/details.rst
doc/user_guide/checkers/features.rst
doc/whatsnew/fragments/6871.user_action
pylint/checkers/refactoring/implicit_booleaness_checker.py
tests/functional/u/use/use_implicit_booleaness_not_comparison.txt
tests/functional/u/use/use_implicit_booleaness_not_comparison_to_string.txt
tests/functional/u/use/use_implicit_booleaness_not_comparison_to_zero.txt
tests/functional/u/use/use_implicit_booleaness_not_len.py

Follow-up to #8630 
Closes #6871
Closes #5234

Merging of ``use-implicit-booleaness``-like checkers for consistency and performance

---

doc/development_guide/contributor_guide/tests/launching_test.rst

Without this minor fixup, I get the error already described in #8341:
```
$ pytest pylint -k my_new_func_test_name
...
collected 0 items / 1 error
============================================================== ERRORS ===============================================================
_____________________________________ ERROR collecting pylint/testutils/functional/test_file.py _____________________________________
.../python3.8/site-packages/_pytest/runner.py:341: in from_call
result: Optional[TResult] = func()
.../python3.8/site-packages/_pytest/runner.py:372: in <lambda>
call = CallInfo.from_call(lambda: list(collector.collect()), "collect")
.../python3.8/site-packages/_pytest/python.py:817: …
```

[Doc] Minor fixup in launching_test.rst

---

doc/whatsnew/2/2.17/index.rst
doc/whatsnew/fragments/8603.bugfix
doc/whatsnew/fragments/8613.false_positive
doc/whatsnew/fragments/8632.bugfix
pylint/__pkginfo__.py
tbump.toml
towncrier.toml

- Fix a false positive for ``bad-dunder-name`` when there is a user-defined
``__index__`` method.
Closes #8613 
- ``pyreverse``: added escaping of vertical bar character in annotation labels
produced by DOT printer to ensure it is not treated as field separator of
record-based nodes.
Closes #8603 
- Fixed a crash when generating a configuration file:
``tomlkit.exceptions.TOMLKitError: Can't add a table to a dotted key``
caused by tomlkit ``v0.11.8``.
Closes #8632

Release branch 2.17.4

---

doc/user_guide/usage/run.rst
doc/whatsnew/fragments/4874.bugfix
pylint/lint/parallel.py
pylint/lint/pylinter.py
tests/test_check_parallel.py

Load custom plugins when processing in parallel.
The current implementation of multiprocessing launches a pool, and unpickles a `PyLinter` object that contains all the configuration information. The workers in the pool will not have access to the AstroidManager that had the configuration options (custom plugins, init hooks) applied to it.
The solution here is to just re-register the custom plugins during the initialization of the pool. It's inelegant to do this multiple times, but I'm suggesting not over-optimizing a multiprocessing design that's flawed in other ways. (See #2525.) We can optimize this infelicity out later if it's still even relevant after the overhaul for #2525.
(It's …

Load custom plugins when linting in parallel

---

doc/whatsnew/fragments/8595.false_negative
pylint/checkers/variables.py
tests/functional/u/unused/unused_variable.py
tests/functional/u/unused/unused_variable.txt

This is a fix for a false negative regression caused by #8441. The issue lies in `_defines_name_raises_or_returns()`, which returns false even when an exception variable defines the given name.
Closes #8595

Regression fix for `unused-variable` false negative

---

doc/whatsnew/fragments/8698.bugfix
pylint/checkers/typecheck.py
tests/functional/i/invalid/invalid_metaclass.py
tests/functional/i/invalid/invalid_metaclass.txt

Closes #8698
``mro()`` is documented as raising these two exceptions. Thus, we need to catch them.

Fix crash in `invalid-metaclass` check

---

doc/whatsnew/fragments/7774.bugfix
pylint/checkers/exceptions.py
pylint/config/config_initialization.py

This warning was emitted multiple times when running with ``--jobs``, e.g. thousands of times (not just number of jobs).
It's a configuration sanity check: it belongs in the linter, not in the actual checker.
Closes #7774

Avoid duplicate overgeneral-exceptions warnings with ``--jobs``

---

doc/whatsnew/2/2.14/summary.rst

The optparse module is deprecated, and it's better to use argparse, but there's no current plans to remove it.
https://docs.python.org/3.12/library/optparse.html shows it's still present in 3.12 and says:
> _Deprecated since version 3.2:_ The [optparse](https://docs.python.org/3.12/library/optparse.html#module-optparse) module is deprecated and will not be developed further; development will continue with the [argparse](https://docs.python.org/3.12/library/argparse.html#module-argparse) module.

Docs: optparse not removed in Python 3.12

---

.github/workflows/stale.yml

Some issues can be managed automatically, and free some time for maintainers. See https://github.com/actions/stale for reference.

Manage PR/Issues that are stale automatically

---

doc/data/messages/r/return-in-finally/bad.py
doc/data/messages/r/return-in-finally/good.py
doc/data/messages/r/return-in-finally/related.rst
doc/whatsnew/fragments/8260.new_check
pylint/checkers/base/basic_checker.py
tests/functional/l/lost_exception.py
tests/functional/r/return_in_finally.py
tests/functional/r/return_in_finally.txt

add checker for return in finally

---

.github/workflows/stale.yml

Follow-up to #8706 after the job failed in https://github.com/pylint-dev/pylint/actions/runs/5040967851

[stale action] The expected value is a comma separated string

---

pylint/config/config_file_parser.py

This will permit to parse config file without having to instantiate a linter for tool working on pylint configuration like #5462. another way to do this would be to extract the logic and create another class that we could use in ``_ConfigurationFileParser`` like here: https://github.com/Pierre-Sassoulas/pylint/commit/4ccbee1d1e73900f2d34dd67c00d5eb665cf2a04

[config] Make the linter optional during config parsing

---

.github/workflows/codeql-analysis.yml
.github/workflows/stale.yml

There's no need to run the "close stale issues and pr" or CodeQL cron for forks.
More info: https://dev.to/hugovk/til-how-to-disable-cron-for-github-forks-2d0l

CI: Only run stale cron on upstream

---

tests/functional/c/condition_evals_to_constant.py
tests/functional/c/condition_evals_to_constant.txt

Closes #7933.
The original issue reported pylint as missing bugs in comparisons like:
`if get_text() == "string A" or "string B":`
In reality this is already covered by the message
'condition-evals-to-constant', however test cases with strings were missing, they have been added to self-document other cases this checker applies to and extend coverage.

Extend test cases for 'condition-evals-to-constant'

---

doc/whatsnew/fragments/8740.bugfix
pylint/checkers/variables.py
tests/functional/u/undefined/undefined_all_variable_edge_case.py
tests/functional/u/undefined/undefined_all_variable_edge_case.txt

Fix a crash when `__all__` exists but cannot be inferred

---

doc/whatsnew/fragments/8696.false_positive
pylint/checkers/variables.py
tests/functional/u/unused/unused_global_variable2.py
tests/functional/u/unused/unused_global_variable2.txt

Fix a false positive for ``unused-variable`` when there is an import in a ``if TYPE_CHECKING:`` block and ``allow-global-unused-variables`` is set to ``no`` in the configuration.
Closes #8696

Fix a false positive for ``unused-variable``

---

tests/functional/r/regression_02/regression_5408.rc

Similar skip as in astroid, see pylint-dev/astroid@1f9ba55.
Discussed [here](https://github.com/pylint-dev/pylint/pull/8685#issuecomment-1579447820).

Skip flaky `regression_5408.py` test on PyPy

---

doc/whatsnew/fragments/374.bugfix
pylint/checkers/similar.py
pylint/lint/parallel.py
tests/test_self.py
tests/test_similar.py

All the groundwork for detecting `duplicate-code` with `--jobs` was laid in #4007, but it was only unit tested without actually checking that messages were emitted.
Closes #374 (I moved the remaining cyclic-import issue to #4171)

Support `duplicate-code` message with `--jobs`

---

doc/whatsnew/fragments/8747.false_positive
pylint/checkers/refactoring/refactoring_checker.py
tests/functional/i/inconsistent/inconsistent_returns_noreturn.py
tests/functional/i/inconsistent/inconsistent_returns_noreturn.txt

fix(inconsistent-return-statements): Fix false positive due to pylint not seeing that a method returns `NoReturn`

---

doc/whatsnew/fragments/6287.bugfix
pylint/extensions/_check_docs_utils.py
pylint/extensions/docparams.py
tests/functional/ext/docparams/missing_param_doc.py
tests/functional/ext/docparams/missing_param_doc_py38.py
tests/functional/ext/docparams/missing_param_doc_py38.rc
tests/functional/ext/docparams/parameter/missing_param_doc_required_Google.py
tests/functional/ext/docparams/parameter/missing_param_doc_required_Google.txt
tests/functional/ext/docparams/parameter/missing_param_doc_required_Numpy.py
tests/functional/ext/docparams/parameter/missing_param_doc_required_Numpy.txt
tests/functional/ext/docparams/parameter/missing_param_doc_required_Sphinx.py
tests/functional/ext/docparams/parameter/missing_param_doc_required_Sphinx.txt

The docparams extension won't raise a `missing-type-doc` when type annotations are given. This changes means that it also won't raise a  `missing-type-doc` when type comments are given.
Closes #6287

docparams extension considers type comments as type documentation.

---

doc/whatsnew/fragments/8719.false_positive
pylint/checkers/stdlib.py
pylint/checkers/utils.py
tests/functional/b/bad_open_mode.txt
tests/functional/u/unspecified_encoding_py38.py
tests/functional/u/unspecified_encoding_py38.txt

False positives were being generated when passing arguments as kwargs to open() calls. This has been resolved by using inference inside `get_argument_from_call`.
This is an opt-in function, for inference to be used, `infer=True` must be specified when calling `get_argument_from_call`. This ensures that the rest of the codebase does not suffer a performance hit unnecessarily.
Closes #8719

Fix false positive `unspecified-encoding` when using kwargs

---

CITATION.cff
doc/whatsnew/fragments/8760.other

Add a CITATION.cff containing the necessary metadata to cite Pylint

---

doc/user_guide/installation/ide_integration/index.rst
doc/whatsnew/fragments/8774.bugfix
pylint/checkers/stdlib.py
tests/functional/s/shallow_copy_environ.py
tests/functional/s/shallow_copy_environ.txt

Fix a crash when calling `copy.copy()` without args

---

doc/whatsnew/fragments/8753.bugfix
pylint/checkers/classes/class_checker.py
tests/functional/m/method_hidden.py
tests/functional/m/method_hidden.txt
tests/functional/m/method_hidden_py39.py
tests/functional/m/method_hidden_py39.rc
tests/functional/m/method_hidden_py39.txt

Ignore cached_property in method-hidden check (#8753)

---

pylint/config/argument.py
pylint/config/callback_actions.py
pylint/testutils/checker_test_case.py
pylint/testutils/configuration_test.py
pylint/testutils/functional/lint_module_output_update.py
pylint/testutils/output_line.py
tests/testutils/test_lint_module_output_update.py
tests/testutils/test_output_line.py

Refs #6306, specifically the first item.
Leaves https://github.com/pylint-dev/pylint/issues/6306#issuecomment-1519118923 (test cleanup) still to be done. (Decided to go back one version to do #8792 first.)

Misc cleanup after dropping Python 3.7

---

doc/whatsnew/fragments/8715.performance
pylint/lint/run.py
tests/test_self.py

Closes #8715 (should reduce the number of issues we get about this)
Exit immediately with the help message if all checks are disabled. Exit non-zero.

Exit immediately if all messages are disabled

---

doc/user_guide/usage/run.rst
doc/whatsnew/fragments/4171.bugfix
pylint/checkers/imports.py
tests/test_check_parallel.py

Support `cyclic-import` message with `--jobs`

---

doc/whatsnew/fragments/8714.false_negative
pylint/checkers/typecheck.py
tests/functional/a/assignment/assignment_from_no_return_2.py
tests/functional/a/assignment/assignment_from_no_return_2.txt

Emit assignment-from-none for builtin methods like dict.update()

---

pylint/checkers/typecheck.py

Arguments cannot be parenthesized in python3. codecov showed the `name=None` line was not covered, meaning we are spending useless `isinstance` and `assert` checks.
Similar change as pylint-dev/astroid@3db2bdd6ebfc49db5ed7f379a7c8388849b97262.

Remove Python 2 check in visit_call()

---

doc/whatsnew/fragments/8714.false_negative
pylint/checkers/typecheck.py
tests/functional/a/assignment/assignment_from_no_return_2.py
tests/functional/a/assignment/assignment_from_no_return_2.txt

Follow-up to 32effc5dab2288ca15c4f1638389f60087a1504f.
Since we won't be merging `assignment-from-no-return` with `assignment-from-none`, we should emit the correct message for builtins like `list.sort()` and `dict.update()`. Only `list.sort()` is a behavior change from stable versions.
Closes #8810

Emit assignment-from-no-return for builtin methods like dict.update()

---

pylint/checkers/imports.py
tests/test_check_parallel.py

Follow-up to bf8051b632afdba6792e55c20faec712b0ebebaf. I need to also combine the data collected during the multiprocessing about excluded edges. I wondered about this during development but unfortunately didn't fully test it.
(Sorry for all the PR volume! It won't be like this forever. No rush on the reviews.)

Fix cyclic import edge exclusion with `--jobs`

---

examples/custom.py
pylint/checkers/base/basic_checker.py
pylint/checkers/base/basic_error_checker.py
pylint/checkers/base/docstring_checker.py
pylint/checkers/base/name_checker/checker.py
pylint/checkers/classes/class_checker.py
pylint/checkers/format.py
pylint/checkers/imports.py
pylint/checkers/newstyle.py
pylint/checkers/refactoring/not_checker.py
pylint/checkers/refactoring/refactoring_checker.py
pylint/checkers/typecheck.py
pylint/checkers/utils.py
pylint/checkers/variables.py
pylint/extensions/_check_docs_utils.py
pylint/extensions/bad_builtin.py
pylint/extensions/docparams.py
pylint/extensions/no_self_use.py
pylint/pyreverse/inspector.py
pylint/utils/utils.py
pyproject.toml
requirements_test_min.txt

Prerequisite for adding Python 3.12 compatibility. 3.12 CI jobs will be added later in #8718.
Skipping news because we have several pre-releases to go before announcing the astroid version to be used for 3.0 final.

Upgrade astroid to 3.0.0a6

---

.github/workflows/primer_run_main.yaml

If there's a cache hit on the primer projects, don't clone them again. Saves a few seconds. I don't expect that this is the source of any commit drift between the step that creates the commit string and this one, but it can't hurt to skip this step and be _sure_ there's no source of drift here.
[Example](https://github.com/jacobtylerwalls/pylint/actions/runs/5495063672/jobs/10016521468) of this working.

[primer] Skip regenerate cache step for cache hits

---

pylint/checkers/imports.py
tests/test_check_parallel.py

Follow-up to f815e9f5fcdd5caffc04e335fc4590a65989ef21.
Discussed at https://github.com/pylint-dev/pylint/pull/8820#issuecomment-1627530624.

Optimize parallel runs when `cyclic-import` disabled

---

doc/whatsnew/fragments/3696.breaking
pylint/config/config_initialization.py
tests/config/functional/toml/toml_with_mutually_exclusive_disable_enable_all.toml
tests/config/functional/toml/toml_with_specific_disable_before_enable_all.toml
tests/config/functional/toml/toml_with_specific_enable_before_disable_all.toml
tests/config/test_config.py
tests/config/test_functional_config_loading.py
tests/regrtest_data/fixme.py
tests/test_self.py

Let individual enables/disables take effect even if followed by `--enable=all` or `--disable=all`. Previously, this was order-specific, which is tolerable on the CLI but inconvenient for configuration files.
This means that for:
```
pylint my_module --enable=fixme --disable=all
```
...you'll now get the fixme messages, whereas before, you'd have to reverse the order of the arguments.  (If the new result is not what you want, you can get the prior behavior by removing the superfluous first argument.)
Order-dependence still applies for message categories such as "R", "W", etc. This PR just moves the `=all` arguments to the front.
Providing both `--enable=all` …

Observe specific enables/disables even if followed by "all"

---

doc/whatsnew/fragments/8754.bugfix
pylint/checkers/variables.py
tests/functional/u/used/used_before_assignment.py

(cherry picked from commit e71f63b5ec623b5c128891453baf2bea63fa6eff)
Backport of #8839 to 2.17.x

[Backport maintenance/2.17.x] Fix crash from unexpected assignment (#8839)

---

doc/user_guide/checkers/features.rst
pylint/checkers/refactoring/implicit_booleaness_checker.py

This PR fixes a typo in the description of use-implicit-booleaness-not-len. Relates to #6870.

docs: Fix typo in implicit booleaness checker description.

---

pyproject.toml
requirements_test_min.txt

Allows us to mark the astroid 2.15.6 issues as fixed in the 2.17.x maintenance branch of pylint.

Bump astroid to 2.15.6 on maintenance branch

---

pylint/checkers/refactoring/refactoring_checker.py

`TryExcept` was removed in astroid 3.0.0a7.

Fix type annotation

---

pylint/checkers/stdlib.py
tests/functional/t/try_except_raise_crash.py

Add stdlib [deprecations from Python 3.12](https://docs.python.org/3.12/whatsnew/3.12.html#deprecated). Some missing items are attributes, tracked in #8855.

Add stdlib deprecations from 3.12

---

.github/workflows/checks.yaml
.github/workflows/primer_run_pr.yaml
requirements_test.txt

CI: exclude linting dependencies from the unittest environment.

---

pyproject.toml

[Dill 0.3.7](https://github.com/uqfoundation/dill/releases/tag/dill-0.3.7) for Python 3.12 compat

Bump dill to 0.3.7 on Python 3.12

---

CONTRIBUTORS.txt
doc/user_guide/configuration/all-options.rst
doc/whatsnew/2/2.17/index.rst
doc/whatsnew/fragments/8554.bugfix
doc/whatsnew/fragments/8598.bugfix
doc/whatsnew/fragments/8696.false_positive
doc/whatsnew/fragments/8698.bugfix
doc/whatsnew/fragments/8719.false_positive
doc/whatsnew/fragments/8720.bugfix
doc/whatsnew/fragments/8735.other
doc/whatsnew/fragments/8740.bugfix
doc/whatsnew/fragments/8747.false_positive
doc/whatsnew/fragments/8754.bugfix
doc/whatsnew/fragments/8774.bugfix
doc/whatsnew/fragments/8830.false_positive
pylint/__pkginfo__.py
tbump.toml
towncrier.toml

What's new in Pylint 2.17.5?
----------------------------
Release date: 2023-07-26
- Fix a false positive for ``unused-variable`` when there is an import in a
``if TYPE_CHECKING:`` block and ``allow-global-unused-variables`` is set to
``no`` in the configuration.
Closes #8696 
- Fix false positives generated when supplying arguments as ``**kwargs`` to IO
calls like open().
Closes #8719
- Fix a false positive where pylint was ignoring method calls annotated as
``NoReturn`` during the ``inconsistent-return-statements`` check.
Closes #8747
- Exempt parents with only type annotations from the ``invalid-enum-extension``
message.
Closes #8830
- Fixed crash when a call to ``super()`` was placed after an operator (e.g. …

Release branch for 2.17.5

---

doc/data/messages/i/invalid-name/details.rst
doc/whatsnew/fragments/2018.user_action
pylint/checkers/base/name_checker/naming_style.py
tests/functional/d/disable_msg_next_line.py
tests/functional/d/disable_msg_next_line.txt
tests/functional/i/invalid/invalid_name.py
tests/functional/i/invalid/invalid_name.txt
tests/functional/i/invalid/invalid_name/invalid_name_property.py
tests/functional/i/invalid/invalid_name/invalid_name_property.txt
tests/functional/n/name/name_preset_snake_case.txt
tests/functional/n/namePresetCamelCase.txt
tests/functional/r/regression/regression_4723.py
tests/functional/r/regression/regression_4723.txt

Closes #2018
Many users have expressed surprise that `invalid-name`, which styles itself as a casing checker for snake case, camel case, etc., also checks for a minimum of three characters. We could clarify in the message, we could decouple the two, or we could build a new feature. This PR takes the middle ground: decoupling length from casing and then showing users who still want to check for length some alternatives. The simplest alternative involves adding a single setting.

Stop checking minimum name length by default

---

.github/workflows/tests.yaml
doc/Makefile
doc/conf.py

Follow-up to #8878. Ideally this will restore the codecov calculations.

[coverage] Invoke pytest as `python -m pytest` to restore coverage

---

CONTRIBUTORS.txt
doc/whatsnew/2/2.17/index.rst
doc/whatsnew/3/3.0/index.rst
doc/whatsnew/fragments/8408.internal
doc/whatsnew/fragments/8554.bugfix
doc/whatsnew/fragments/8558.new_check
doc/whatsnew/fragments/8598.bugfix
doc/whatsnew/fragments/8696.false_positive
doc/whatsnew/fragments/8698.bugfix
doc/whatsnew/fragments/8719.false_positive
doc/whatsnew/fragments/8720.bugfix
doc/whatsnew/fragments/8735.other
doc/whatsnew/fragments/8740.bugfix
doc/whatsnew/fragments/8747.false_positive
doc/whatsnew/fragments/8754.bugfix
doc/whatsnew/fragments/8774.bugfix
doc/whatsnew/fragments/8830.false_positive

Refs #8887
- Apply the 2.17.5 changelog updates
- Reclassify one 3.0 new feature as "new check" to put it with other new checks
- Add backticks
- Link to astroid changelog

Fix release notes after 2.17.5 release

---

.github/workflows/tests.yaml
pylint/checkers/typecheck.py
tests/functional/e/enum_self_defined_member_5138.rc

Refs www.github.com/python/cpython/issues/106762

Cope with removal of `EnumType.__getattr__` in 3.12

---

.github/workflows/tests.yaml
pyproject.toml

Follow-up to 2821efbd0a119a53c5ebd88ed9e1fab661208a65.
Too much of pylint's test suite assumes the repo root is on the path. Restore this workaround for now.
cc/ @DanielNoord this will ideally allow you to run a bare `pytest` invocation as before.
Sorry for the churn; I thought we could do without this workaround, but not if every contributor has to manipulate their path or invoke pytest differently.

Restore editable_mode=compat analogue

---

doc/user_guide/checkers/features.rst
tbump.toml

Add a tbump step to automatically normalize line ending

---

doc/data/messages/r/return-arg-in-generator/details.rst
doc/data/messages/r/return-arg-in-generator/related.rst
doc/user_guide/checkers/features.rst
pylint/checkers/base/basic_error_checker.py

Blocked by the inclusion of deleted messages in the doc (#6670) or the inclusion of a new message template #7897 
Refs #5953

[return-arg-in-generator] Add a details.rst only as the message is not raised anymore

---

doc/whatsnew/fragments/8919.false_positive
pylint/checkers/classes/class_checker.py
tests/functional/a/arguments_differ.py

Fix false positive for ``arguments-differ`` when overriding `__init_subclass__`.
Closes #8919

Fix false positive for ``arguments-differ``

---

doc/exts/pylint_options.py
doc/user_guide/configuration/all-options.rst

New feature prior to #6736 and #8950

Add the possible choices in the generated toml doc

---

pylint/checkers/base_checker.py
tests/checkers/unittest_base_checker.py

The comparison was not done properly for extension when the second values given was a builtin and the first one an extension. The tests were not testing this case properly because the alphabetical order made us think that everything went right. Added a test with a low alphabetical value extension checker.
Necessary for #8951

[base checker] Fix the ordering of checkers for extensions

---

.github/workflows/checks.yaml
.pre-commit-config.yaml
doc/development_guide/contributor_guide/tests/install.rst

Refs #5953 
Refs https://github.com/PyCQA/pylint/pull/6735#discussion_r884226339
Require #8949, #8950, #8951, #8956

[doc] Add a CI check for the doc being properly generated

---

doc/whatsnew/fragments/8973.feature
doc/whatsnew/fragments/8973.user_action
pylint/pyreverse/inspector.py
pylint/pyreverse/main.py
pylint/pyreverse/writer.py
tests/pyreverse/conftest.py
tests/pyreverse/test_main.py

Here is what Pyreverse currently prints:
```
$ pyreverse pylint/pyreverse/
parsing pylint/pyreverse/__init__.py...
parsing /home/nick/pylint/pylint/pyreverse/inspector.py...
parsing /home/nick/pylint/pylint/pyreverse/plantuml_printer.py...
parsing /home/nick/pylint/pylint/pyreverse/printer.py...
parsing /home/nick/pylint/pylint/pyreverse/mermaidjs_printer.py...
parsing /home/nick/pylint/pylint/pyreverse/writer.py...
parsing /home/nick/pylint/pylint/pyreverse/__init__.py...
parsing /home/nick/pylint/pylint/pyreverse/dot_printer.py...
parsing /home/nick/pylint/pylint/pyreverse/main.py...
parsing /home/nick/pylint/pylint/pyreverse/printer_factory.py...
parsing …
```

Pyreverse: print package import stats

---

pylint/pyreverse/diagrams.py
tests/pyreverse/functional/class_diagrams/annotations/line_breaks.dot
tests/pyreverse/functional/class_diagrams/annotations/line_breaks.mmd
tests/pyreverse/functional/class_diagrams/annotations/line_breaks.puml
tests/pyreverse/functional/class_diagrams/annotations/line_breaks.py
tests/pyreverse/functional/class_diagrams/annotations/line_breaks.rc
tests/pyreverse/functional/class_diagrams/attributes/duplicates.mmd
tests/pyreverse/functional/class_diagrams/attributes/duplicates.py

Add tests for existing bugs:
- https://github.com/pylint-dev/pylint/issues/8189
- https://github.com/pylint-dev/pylint/issues/8522
- https://github.com/pylint-dev/pylint/issues/8888
Running the last of these tests successfully requires adding a `sort` call, which is an extremely minor change in behavior.

Add tests for existing Pyreverse bugs

---

doc/data/messages/a/access-member-before-definition/bad.py
doc/data/messages/a/access-member-before-definition/good.py
doc/data/messages/c/cell-var-from-loop/bad.py
doc/data/messages/c/cell-var-from-loop/good.py

Foo/bar does not help beginners, it's one more concept to understand before
diving in the problem example.
Inspired by #8960

Remove some foo/bar examples from the doc

---

doc/whatsnew/fragments/8671.bugfix
pylint/pyreverse/dot_printer.py
tests/pyreverse/functional/class_diagrams/annotations/line_breaks.dot
tests/pyreverse/functional/class_diagrams/annotations/line_breaks.mmd
tests/pyreverse/functional/class_diagrams/annotations/line_breaks.puml
tests/pyreverse/functional/class_diagrams/annotations/line_breaks.py

Fix a line break error in Pyreverse dot output
Closes #8671

Fix Pyreverse line break bug

---

doc/data/messages/b/bad-plugin-value/details.rst
doc/data/messages/b/bad-plugin-value/good.py
doc/data/messages/r/raw-checker-failed/details.rst
doc/data/messages/r/raw-checker-failed/good.py
doc/data/messages/u/unrecognized-option/details.rst
doc/data/messages/u/unrecognized-option/good.py

Refs #7897 #5953, separating in multiple PR to merge faster. Temporary solution if we want to create a configuration template but I think it's good enough and could be permanent, frankly.

[doc] Document some internal pylint errors and configuration/option error

---

doc/whatsnew/fragments/9001.bugfix
pylint/checkers/base_checker.py
tests/checkers/unittest_base_checker.py

Inconsistent hashing issue in `BaseChecker` was causing some reports not being exported.
If any of checker's message definition tuples provided extra message option (optional) `BaseChecker.create_message_definition_from_tuple()` method was overriding those options by adding default `scope` parameter to them. This resulted in message instances having incosistent hashes during their lifecycle and could not be found in reports dictionary when `ReportsHandlerMixIn.make_reports()` was called.
Closes #9001

Fixing inconsistent hashing issue in `BaseChecker` 

---

.github/workflows/primer-test.yaml
.github/workflows/primer_comment.yaml
.github/workflows/primer_run_main.yaml
.github/workflows/primer_run_pr.yaml
.github/workflows/tests.yaml
pylint/testutils/_primer/package_to_lint.py
tests/primer/packages_to_prime.json

See https://github.com/nedbat/coveragepy/commit/f2aa871b575aee0b10b2ec8f407b3963ec06c793
Refs #8998

[primer] Fix conf following coverage's changes

---

doc/data/messages/a/arguments-differ/details.rst
doc/data/messages/b/bad-str-strip-call/bad/hello_world.py
doc/data/messages/b/bad-str-strip-call/bad/remove_abc_from_both_side.py
doc/data/messages/b/bad-str-strip-call/good/hello_world.py
doc/data/messages/b/bad-str-strip-call/good/remove_abc_from_both_side.py
doc/data/messages/c/consider-using-any-or-all/bad/all_even.py
doc/data/messages/c/consider-using-any-or-all/bad/any_even.py
doc/data/messages/c/consider-using-any-or-all/good.py
doc/data/messages/c/consider-using-any-or-all/good/all_even.py
doc/data/messages/c/consider-using-any-or-all/good/any_even.py
doc/data/messages/c/consider-using-with/bad/close.py
doc/data/messages/c/consider-using-with/bad/not_even_close.py
doc/data/messages/c/consider-using-with/good.py
doc/data/messages/l/logging-format-interpolation/related.rst
doc/data/messages/l/logging-fstring-interpolation/related.rst
doc/data/messages/l/logging-not-lazy/related.rst

Refs #7897 
There are multiple examples for [consider-using-f-string](https://pylint.readthedocs.io/en/stable/user_guide/messages/convention/consider-using-f-string.html) and [consider-using-generator](https://pylint.readthedocs.io/en/stable/user_guide/messages/refactor/consider-using-generator.html): but I think it's not worth it to separate everything. (Better to keep all the examples together in this case).

[doc] Use the new multiple file template for ``A <= message-symbol < D ``

---

doc/whatsnew/fragments/8189.bugfix
pylint/pyreverse/diagrams.py
tests/pyreverse/functional/class_diagrams/attributes/duplicates.mmd
tests/pyreverse/functional/class_diagrams/attributes/duplicates.py

Fix duplicate fields Pyreverse bug

---

doc/whatsnew/fragments/8888.bugfix
pylint/pyreverse/diagrams.py
tests/pyreverse/functional/class_diagrams/attributes/duplicates.mmd
tests/pyreverse/functional/class_diagrams/attributes/duplicates.py

Fix Pyreverse duplicate annotations

---

doc/whatsnew/fragments/9014.bugfix
pylint/pyreverse/utils.py
tests/pyreverse/functional/class_diagrams/annotations/attributes_annotation.dot
tests/pyreverse/functional/class_diagrams/annotations/attributes_annotation.mmd
tests/pyreverse/functional/class_diagrams/annotations/attributes_annotation.puml
tests/pyreverse/functional/class_diagrams/annotations/attributes_annotation.py

Fix Pyreverse optional annotation bug

---

doc/test_messages_documentation.py

Seen in #8960, previously the error message was:
```
msg = f"""There should be no warning raised for 'good.py' but these messages were raised:
- {messages}
See:
"""
>           with open(self._test_file[1]) as f:
E           IsADirectoryError: [Errno 21] Is a directory: '/home/runner/work/pylint/pylint/doc/data/messages/c/cell-var-from-loop/good'
```
As seen in https://github.com/pylint-dev/pylint/actions/runs/6026790597/job/16350544929?pr=8960. Now with this MR it's:
```
E           AssertionError: There should be no warning raised for 'good.py' but these messages were raised:
E             - cell-var-from-loop (l. 8)
E             
E             See:
E             
E             
E …
```

[doc test helper] Better representation of failure for multiple good files

---

doc/test_messages_documentation.py

This starts to check that there is a warning for each files in a bad directory, except if the message is in the list of expected message that need multiple file to create an example. Result:
```
E           AssertionError: There should be at least one warning raised for each file in '/home/pierre/pylint/doc/data/messages/n/non-ascii-file-name/bad' (3 total)
E             - Missing warning in /home/pierre/pylint/doc/data/messages/n/non-ascii-file-name/bad/__init__.py
E             'non-ascii-file-name' might need to be added in 'known_multiple_file_messages'.
E             
E             
E           assert 2 >= 3
E            +  where 2 = …
```

[doc test helper] Better representation of failure for multiple bad files 

---

.pre-commit-config.yaml
doc/data/messages/s/superfluous-parens/bad/example_1.py
doc/data/messages/s/superfluous-parens/bad/example_2.py
doc/data/messages/s/superfluous-parens/good/example_1.py
doc/data/messages/s/superfluous-parens/good/example_2.py

Fix doc and/or a false negative in ``superfluous-parens``

---

pylint/pyreverse/mermaidjs_printer.py
tests/pyreverse/functional/package_diagrams/type_check_imports/packages.mmd

There is an issue with a mermaid arrow.
Check:
Closes #9030 
The issue was introduced in:
#8824 
it should be:
`mod_c ..> mod_a`
as documented here:
https://mermaid.js.org/syntax/classDiagram.html#defining-relationship
github renders mermaid files, and if we try to open this one we get an error, see:
https://github.com/pylint-dev/pylint/blob/ffe1e714a3cfe83b5a627ade6d723489f2e10621/tests/pyreverse/functional/package_diagrams/type_check_imports/packages.mmd
with this fix now the file renders without issue:
https://github.com/pylint-dev/pylint/blob/83ade2f16272153ae077b03c5c8ffd341b03cf25/tests/pyreverse/functional/package_diagrams/type_check_imports/packages.mmd
_Originally posted by @agusdmb …

fix mermaid dotted arrow

---

doc/whatsnew/fragments/8522.bugfix
pylint/pyreverse/diagrams.py
tests/pyreverse/functional/class_diagrams/attributes/duplicates.mmd
tests/pyreverse/functional/class_diagrams/attributes/duplicates.py

Fix Pyreverse duplicate arrows bug

---

doc/data/messages/i/invalid-character-carriage-return/details.rst
doc/data/messages/i/invalid-character-carriage-return/good.py
doc/data/messages/i/invalid-character-nul/details.rst
doc/data/messages/i/invalid-character-nul/good.py
doc/data/messages/i/invalid-character-nul/related.rst

Refs #5953 
As far as I know it's impossible to raise those two messages unless you construct a theoretical node in a unit test.

[doc] Document invalid characters that exists because of the genericity of the unicode checker

---

doc/whatsnew/fragments/7710.bugfix
pyproject.toml
requirements_test_min.txt
tests/functional/u/unbalanced/unbalanced_tuple_unpacking.py
tests/functional/u/unbalanced/unbalanced_tuple_unpacking.txt

Closes #7710 
Require an upgrade in astroid and https://github.com/pylint-dev/astroid/pull/2244 being merged. Will probably fix other issues in other messages whenever ``sys.argv`` is used in a check but I don't aim to create exhaustive tests.

[unbalanced-tuple-unpacking] Add a regression tests for #7710

---

doc/whatsnew/fragments/9045.bugfix
pylint/pyreverse/writer.py
tests/pyreverse/functional/class_diagrams/aggregation/fields.mmd

Fixes the multiple-association-arrows bug mentioned in #9045

Pyreverse: Don't show multiple class association arrows

---

doc/whatsnew/2/2.17/index.rst
doc/whatsnew/fragments/7229.bugfix
doc/whatsnew/fragments/7710.bugfix
doc/whatsnew/fragments/8189.bugfix
doc/whatsnew/fragments/8522.bugfix
doc/whatsnew/fragments/8888.bugfix
doc/whatsnew/fragments/9014.bugfix
pylint/__pkginfo__.py
tbump.toml
towncrier.toml

Release date: 2023-09-24
- When parsing comma-separated lists of regular expressions in the config,
ignore commas that are inside braces since those indicate quantifiers, not
delineation between expressions.
Closes #7229
- ``sys.argv`` is now always correctly considered as impossible to infer
(instead of using the actual values given to pylint).
Closes #9047 
- Don't show class fields more than once in Pyreverse diagrams.
Closes #8189
- Don't show arrows more than once in Pyreverse diagrams.
Closes #8522
- Don't show duplicate type annotations in Pyreverse diagrams.
Closes #8888 
- Don't add `Optional` to `|` annotations with `None` in Pyreverse diagrams.
Closes #9014

Bump pylint to 2.17.6, update changelog

---

doc/whatsnew/fragments/7402.false_positive
pylint/checkers/base/name_checker/checker.py
pylint/checkers/utils.py
tests/functional/i/invalid/invalid_name/invalid_name_enum.py
tests/functional/i/invalid/invalid_name/invalid_name_enum.txt

Check that a name exists inside an `enum.Enum` class' `__members__` container before doing the ``invalid-name`` check.
Refs #7402

Check that a name exists inside `enum.Enum` class' `__members__`.

---

doc/whatsnew/fragments/9074.bugfix
pylint/checkers/refactoring/refactoring_checker.py
tests/functional/r/regression/regression_9074_refactor_loop_with_unary_variable.py

Fixes:
```
File "python3.10/site-packages/pylint/utils/ast_walker.py", line 91, in walk
callback(astroid)
File "python3.10/site-packages/pylint/checkers/refactoring/refactoring_checker.py", line 700, in visit_for
self._check_unnecessary_list_index_lookup(node)
File "python3.10/site-packages/pylint/checkers/refactoring/refactoring_checker.py", line 2227, in _check_unnecessary_list_index_lookup
has_start_arg, confidence = self._enumerate_with_start(node)
File "python3.10/site-packages/pylint/checkers/refactoring/refactoring_checker.py", line 2352, in _enumerate_with_start
start_val, confidence = self._get_start_value(keyword.value)
File "python3.10/site-packages/pylint/checkers/refactoring/refactoring_checker.py", line 2369, in _get_start_value
return node.operand.value, HIGH …
```

Fix crash in refactoring checker from unaryop with variable

---

pyproject.toml
requirements_test_min.txt
tests/functional/n/no/no_member_typevar.py
tests/functional/u/unsubscriptable_object.py

| ✓   | 🧪 Tests          |
Refs #9069
Refs pylint-dev/astroid#2305

Add regression tests.

---

doc/whatsnew/fragments/9069.false_positive
pyproject.toml
requirements_test_min.txt

Upgrade astroid on 2.17.x branch

---

doc/whatsnew/2/2.17/index.rst
doc/whatsnew/fragments/9069.false_positive
doc/whatsnew/fragments/9074.bugfix
pylint/__pkginfo__.py
tbump.toml
towncrier.toml

- Fix a regression in pylint 2.17.6 / astroid 2.15.7 causing various
messages for code involving ``TypeVar``.
Closes #9069
- Fix crash in refactoring checker when unary operand used with variable in for
loop.
Closes #9074

Bump pylint to 2.17.7, update changelog

---

doc/whatsnew/fragments/9059.bugfix
pylint/lint/pylinter.py
tests/lint/unittest_lint.py
tests/test_check_parallel.py
tests/test_regr.py
tests/test_self.py

Closes #9059
Some messages are emitted before the checkers are opened, so this was clearing stats too soon.

Prevent stats loss

---

.pre-commit-config.yaml
README.rst
doc/data/messages/c/consider-using-dict-comprehension/details.rst
doc/data/messages/c/consider-using-set-comprehension/details.rst
doc/whatsnew/2/2.11/summary.rst
pylint/checkers/base_checker.py
pylint/checkers/refactoring/refactoring_checker.py
pylint/extensions/_check_docs_utils.py
pylint/testutils/constants.py
pyproject.toml

Stumbled upon a nasty bug of pyupgrade that created a syntax error. Making pyupgrade ignore the file is more work than migrating to ruff. Upgraded the doc where applicable too.

Remove pyupgrade use ruff, upgrade doc

---

doc/whatsnew/fragments/9106.false_positive
pylint/checkers/classes/class_checker.py
tests/functional/i/inherit_non_class.py
tests/functional/i/inherit_non_class.txt

Closes https://github.com/pylint-dev/pylint/issues/9106.
Thought I would make a PR, has been a while 😄 
Fixes a false positive which is apparently a regression in `3.x`.

Fix false positive for ``inherit-non-class`` for generic Protocols

---

doc/whatsnew/fragments/9100.other
pylint/checkers/utils.py
tests/functional/i/invalid/invalid_name/invalid_name_enum.py
tests/functional/i/invalid/invalid_name/invalid_name_enum.txt

Fix a crash when an enum class which is also decorated with a ``dataclasses.dataclass`` decorator is defined.
Closes #9100

Fix a crash for Enum class decorated with dataclass

---

doc/exts/pylint_extensions.py
doc/whatsnew/3/3.0/index.rst
doc/whatsnew/fragments/9100.other
doc/whatsnew/fragments/9106.false_positive
pylint/__pkginfo__.py
tbump.toml
towncrier.toml

- Fixed false positive for ``inherit-non-class`` for generic Protocols.
Closes #9106 
Other Changes
-------------
- Fix a crash when an enum class which is also decorated with a ``dataclasses.dataclass`` decorator is defined.
Closes #9100

Bump pylint to 3.0.1, update changelog

---

doc/whatsnew/fragments/8524.bugfix
pylint/checkers/nested_min_max.py
tests/functional/n/nested_min_max.py
tests/functional/n/nested_min_max.txt
tests/functional/n/nested_min_max_py39.py
tests/functional/n/nested_min_max_py39.rc
tests/functional/n/nested_min_max_py39.txt

Fixes suggestion when list or dict comprehensions are used or combined with add/or operators.
Closes #8524

Fix suggestion for min-max with expressions

---

pylint/config/_breaking_changes.py

First step for  #5462 . I suppose considering the timeline early reviews are important 😄

[configuration] Create a data structure to store breaking changes

---

doc/whatsnew/fragments/9110.false_positive
pylint/checkers/variables.py
pyproject.toml
requirements_test_min.txt
tests/functional/u/used/used_before_assignment_py312.py
tests/functional/u/used/used_before_assignment_py312.rc

Fix `used-before-assignment` FP for generic type syntax (Py 3.12)

---

doc/whatsnew/fragments/9113.bugfix
pylint/checkers/strings.py
tests/functional/i/inconsistent/inconsistent_quotes_fstring.py
tests/functional/i/inconsistent/inconsistent_quotes_fstring.rc
tests/functional/i/inconsistent/inconsistent_quotes_fstring_py312.py
tests/functional/i/inconsistent/inconsistent_quotes_fstring_py312.rc
tests/functional/i/inconsistent/inconsistent_quotes_fstring_py312.txt
tests/functional/i/inconsistent/inconsistent_quotes_fstring_py312_311.py
tests/functional/i/inconsistent/inconsistent_quotes_fstring_py312_311.rc

When running pre-3.12 interpeter, f-strings are opaque and are represented as a STRING token (like 'f\'{dictionary["0"]}\' for the test case in the ticket). So they are not used in analysis.
With 3.12 PEG interpreter, f-string is a proper Python expression, even if we target pre-3.12. So this PR enables ``inconsistent-quotes`` checks for string literals only if a target version is 3.12 or later. 
Closes #9113

Respect py-version for ``inconsistent-quotes`` inside f-strings

---

doc/whatsnew/fragments/7874.bugfix
pylint/extensions/magic_value.py
tests/functional/ext/magic_value_comparison/magic_value_comparison.py
tests/functional/ext/magic_value_comparison/magic_value_comparison.txt

I skimmed through all the `args` usage in messages and tested a few suspicious strings. Everything looks good and uses `as_string()` call. The only thing to fix is a `magic-value-comparison` from the referenced ticket.
Closes #7874

Escape special symbols and newlines in messages.

---

doc/whatsnew/fragments/8914.bugfix
pylint/checkers/similar.py
tests/checkers/unittest_similar.py
tests/regrtest_data/duplicate_code/ignore_conditional_imports/file_one.py
tests/regrtest_data/duplicate_code/ignore_conditional_imports/file_two.py
tests/test_similar.py

Improves detection of imports under conditionals. ~Limited checks by constant conditions such as `True`/`typing.TYPE_CHECKING`.~
Closes #8914

Fixes duplicate-code check with ignore-imports

---

pylint/checkers/design_analysis.py

fix: exempt `TypedDict` from `typing_extensions`

---

doc/whatsnew/fragments/9193.false_positive
pylint/checkers/variables.py
tests/functional/u/undefined/undefined_variable_py312.py
tests/functional/u/undefined/undefined_variable_py312.rc

Fix `undefined-variable` etc for Python 3.12 generic type syntax

---

doc/whatsnew/fragments/9148.false_positive
pylint/checkers/base/basic_checker.py
tests/functional/u/unnecessary/unnecessary_lambda.py

I might have missed something because I don't understand why `call_site.keyword_arguments` has been used here instead of simply comparing `node.args.kwarg` with `call.keywords`. Maybe this is not the right way to fix the issue.
```python
if call.keywords:
lambda_kwargs = {keyword.name for keyword in node.args.defaults}
if len(lambda_kwargs) != len(call_site.keyword_arguments):
return
if set(call_site.keyword_arguments).difference(lambda_kwargs):
return
```
As far as I can tell, `lambda_kwargs` here is always empty because of [this condition](https://github.com/pylint-dev/pylint/blob/main/pylint/checkers/base/basic_checker.py#L528) at the beginning of the check
```python
if node.args.defaults:
return
```
Also, `call_site.keyword_arguments` is empty in the case of the example I added to the …

Fix false positive for ``unnecessary-lambda`` with kwargs in the call but not the lambda

---

pylint/checkers/similar.py
pylint/checkers/variables.py
pylint/config/callback_actions.py
pylint/config/config_initialization.py
pylint/testutils/functional/test_file.py
pylint/utils/utils.py
tests/test_check_parallel.py

Follow up to 3.0 release, we did not clean some TODOs and most importantly a warning (that's why I'm backporting).

[todos] Fix the todos version and the warnings' text

---

doc/development_guide/contributor_guide/governance.rst

This is up for discussion: do we give pylint's maintenance right for plugin maintainers that want to migrate their plugin to pylint-dev ? Previously we invited Carl Crowder for pylint-django, when he wanted to migrate his plugin to pylint-dev but he was a PyCQA member, and already pretty invested in pylint so already had maintainer's rights. How about a master student that did their plugin in isolation and the plugin is not yet widely adopted ?
We can also create separate rights' groups in the org (admin / member / plugin owner).

[governance] Upgrade governance for pylint plugin maintainers

---

doc/user_guide/usage/run.rst
doc/whatsnew/fragments/9228.feature
pylint/config/find_default_config_files.py
tests/config/test_find_default_config_files.py

Support for resolving external toml files

---

doc/data/messages/i/implicit-str-concat/details.rst
doc/whatsnew/fragments/8808.bugfix
pylint/checkers/imports.py
pylint/constants.py
tests/functional/w/wrong_import_order.py
tests/functional/w/wrong_import_order.txt

Adds clarification in the message for the wrong-import-order check.
The original message was confusing, especially when multiple imports were on a single line, because the entire import statement is listed twice in the message (`"import X, Y, Z" should be placed before "import X, Y, Z"`).
Changes were made to extract the "current" import name and the "out of order" import names, and separate them by "isort order", so the user is able to clearly see what changes need to be made to address the problem.  For example, `standard import "X" should be placed before third order import "Y" and first order import "Z"`.
No functional tests were added, but the output for the wrong-import-order test was …

Correct/clarify message for wrong-import-order

---

tests/functional/i/iterable_context.py

While investigating #9253, I found that the regression test for suppressing `not-an-iterable` for Uninferable instances was not testing what it intended. Inference had improved over eight years, and we were testing an `Instance` instead, not `Uninferable`.
Refs #9253

[not-an-iterable] Add regression test for uninferable instances

---

doc/whatsnew/fragments/9210.bugfix
pylint/lint/expand_modules.py
tests/lint/unittest_expand_modules.py

When working as `pylint --recursive=y ./` or `pylint --recursive=y .` on a directory with a `__init__.py` file, pylilnt will not be able to walk through other files due to an empty input for `modutils.get_module_files` because `os.path.dirname("__init__.py") == ""`. This PR tries to fix this behavior.
Closes #9210

[bugfix] Find files with ./ as input with a __init__.py file

---

doc/data/messages/p/pointless-string-statement/related.rst
doc/whatsnew/fragments/9268.false_positive
pylint/checkers/base/basic_checker.py
tests/functional/s/statement_without_effect_py312.py
tests/functional/s/statement_without_effect_py312.rc

[pointless-string-statement] Ignore docstrings on py3.12 type aliases

---

doc/whatsnew/fragments/9288.false_positive
pylint/checkers/exceptions.py
tests/functional/w/wrong_exception_operation.py
tests/functional/w/wrong_exception_operation.txt

[wrong-exception-operation] Fix FP for tuple concatenation of exception types

---

pyproject.toml

Refs #9270
`isort` 5.13.0 pulls in many dev dependencies as runtime dependencies, some of which cause behavior differences in astroid. See [logs](https://github.com/pylint-dev/astroid/actions/runs/7159322816/job/19492440429).
Refs https://github.com/PyCQA/isort/issues/2206

Disallow isort 5.13.0

---

pyproject.toml
requirements_test_min.txt

Should reduce primer noise. Let's not backport until there's more of a reason.

Bump astroid to 3.0.2

---

doc/data/messages/t/too-many-positional/details.rst
doc/data/messages/t/too-many-positional/related.rst
doc/user_guide/checkers/features.rst
doc/user_guide/messages/messages_overview.rst
pylint/checkers/design_analysis.py

See https://github.com/astral-sh/ruff/issues/8946
Refs #9099

Reserve 'too-many-positional' / 'R0917' for later use

---

.github/workflows/primer_run_main.yaml
.github/workflows/primer_run_pr.yaml
.github/workflows/tests.yaml

Will need a second PR to fix downloading artifacts, but just want to fix one thing at a time.
Refs https://github.com/actions/upload-artifact/blob/main/docs/MIGRATION.md#multiple-uploads-to-the-same-named-artifact

Fix uploading artifacts in primer

---

.github/workflows/primer_run_main.yaml

Enables other jobs to lookup by "3.12" instead of "3.12.1" etc

[primer] Use short python version on main output steps

---

.github/workflows/primer_comment.yaml
.github/workflows/primer_run_pr.yaml

Following changes in #9324 due to actions/upload-artifact v4 (which no longer allows multiple jobs to upload to the same .zip artifact), these changes allow the primer workflows to download the individual artifacts before the primer compare command compares them.

Add compatibility with actions/download-artifact v4

---

.github/workflows/primer_comment.yaml

Follow-up to 4329e05.
The last PR too eagerly monkeyed with this order of terms in the file name when all it needed to do was get the python version from the correct place. The zip files and txt files aren't created with the same names.
Here's an `ls` command dumping out the result:
```sh
output_3.12_main_batch0.txt
output_3.12_main_batch1.txt
output_3.12_main_batch2.txt
output_3.12_main_batch3.txt
output_3.12_pr_batch0.txt
output_3.12_pr_batch1.txt
output_3.12_pr_batch2.txt
output_3.12_pr_batch3.txt
pr_number.txt
pr_number.zip
primer_output_main_3.12_batch0.zip
primer_output_main_3.12_batch1.zip
primer_output_main_3.12_batch2.zip
primer_output_main_3.12_batch3.zip
primer_output_pr_3.12_batch0.zip
primer_output_pr_3.12_batch1.zip
primer_output_pr_3.12_batch2.zip …
```

Fix primer compare step (again)

---

doc/whatsnew/fragments/9307.false_positive
pylint/checkers/nested_min_max.py
tests/functional/n/nested_min_max.py
tests/functional/n/nested_min_max.txt

Nesting is useful for finding the maximum in a matrix.
Therefore, pylint now allows nesting of the form:
```
max(max([[1, 2, 3], [4, 5, 6]]))
```
Closes #9307

Fixed false positive nested-min-max for nested lists

---

doc/whatsnew/fragments/9246.false_positive
pylint/checkers/typecheck.py
tests/functional/n/no/no_member_decorator.py

Fix FP for `no-member`: function attributes from decorator

---

doc/whatsnew/fragments/6804.false_positive
pylint/checkers/variables.py
tests/functional/u/used/used_before_assignment_else_continue.py
tests/functional/u/used/used_before_assignment_else_continue.txt

[used-before-assignment] Fix FP for try/else/continue

---

doc/faq.rst

Added a missing message that duplicates behavior in `pycodestyle` to the FAQ.
Refs #3512, #746
Closes #9383

feat(FAQ): Update duplicated messages in pycodestyle

---

pylint/checkers/variables.py

add compatibility with https://github.com/pylint-dev/astroid/pull/2345
some of the unrelated changes here are just for the sake of passing pylint too-many-statements, etc

Catch ParentMissingError in variables checker

---

doc/exts/pylint_messages.py

Closes #9372 
See https://pylint--9400.org.readthedocs.build/en/9400/user_guide/messages/refactor/no-self-use.html

Fix the whitespacing in the optional checker note

---

pylint/checkers/typecheck.py
pylint/checkers/utils.py
pylint/checkers/variables.py

Similar to https://github.com/pylint-dev/astroid/pull/2366
`Statement` was moved to `astroid.nodes._base_nodes`.

Fix astroid base_nodes imports

---

.github/workflows/primer_comment.yaml

If five days elapse without a commit on main, the artifacts created by the last primer / main job are still around, and can be used by the compare job, but the compare job will fail because the venv it needs will likely have been evicted in the meantime because we cache so much and are constantly running low on space.
The solve here is to just let the compare job recreate the venv. I tested by rerunning the primer / main job, and without even waiting for it to finish, I could [rerun this failing primer / comment job](https://github.com/pylint-dev/pylint/actions/runs/7855219897/job/21437376819), and it succeeded.
Refs https://github.com/pylint-dev/pylint/pull/9419#issuecomment-1937019507

[primer] Allow primer comment job to recreate venv

---

pylint/checkers/variables.py

The primer messages for sentry are pretty noisy, which is usually a symptom of some headache in the inference cache. They all seem to be in `no-name-from-module`. I couldn't reproduce locally, but I'm hoping avoiding some unnecessary inference here will help.
See https://github.com/pylint-dev/pylint/pull/9419#issuecomment-1937023350

Avoid some inference in `no-name-from-module`

---

doc/data/messages/u/use-yield-from/bad.py
doc/data/messages/u/use-yield-from/details.rst
doc/data/messages/u/use-yield-from/good.py
doc/data/messages/u/use-yield-from/related.rst
doc/user_guide/checkers/features.rst
doc/user_guide/messages/messages_overview.rst
doc/whatsnew/fragments/9229.feature
pylint/checkers/refactoring/refactoring_checker.py
tests/functional/b/bad_reversed_sequence.py
tests/functional/c/consider/consider_using_enumerate.py
tests/functional/ext/docparams/return/missing_return_doc_Sphinx.py
tests/functional/i/iterable_context_py36.py
tests/functional/n/non/non_iterator_returned.py
tests/functional/s/stop_iteration_inside_generator.py
tests/functional/u/undefined/undefined_variable.py
tests/functional/u/unpacking/unpacking_non_sequence.py
tests/functional/u/use/use_implicit_booleaness_not_len.py
tests/functional/u/use/use_yield_from.py
tests/functional/u/use/use_yield_from.txt
tests/functional/y/yield_assign.py

A new message has been added to suggest refactoring when yielding from a for loop can be replaced by 'yield from'. This message is only emitted when there are no other statements in the containing for loop.
Closes #9229.

New message `use-yield-from`

---

.pyenchant_pylint_custom_dict.txt
doc/whatsnew/fragments/9138.bugfix
pylint/__init__.py

Overwrite `sys.unraisablehook` to catch `ValueError` - `"generator already executing"` messages for Python 3.12.0 - 3.12.2 only. This is fixed upstream in both `3.12.3` and `3.13a2+`.
Closes #9138

Catch ValueError - generator already executing

---

doc/whatsnew/3/3.0/index.rst
doc/whatsnew/fragments/6804.false_positive
doc/whatsnew/fragments/9138.bugfix
doc/whatsnew/fragments/9246.false_positive
doc/whatsnew/fragments/9307.false_positive
doc/whatsnew/fragments/9451.false_positive
pylint/__pkginfo__.py
tbump.toml
towncrier.toml

What's new in Pylint 3.0.4?
Release date: 2024-02-23
- ``used-before-assignment`` is no longer emitted when using a name in a loop and
depending on an earlier name assignment in an ``except`` block paired with
``else: continue``.
Closes #6804
- Avoid false positives for ``no-member`` involving function
attributes supplied by decorators.
Closes #9246 
- Fixed false positive nested-min-max for nested lists.
Closes #9307 
- Fix false positive for ``used-before-assignment`` in a ``finally`` block
when assignments took place in both the ``try`` block and each exception handler.
Closes #9451 
- Catch incorrect ValueError ``"generator already executing"`` for Python 3.12.0 - 3.12.2.
This is …

Bump pylint to 3.0.4, update changelog

---

CONTRIBUTORS.txt
doc/development_guide/contributor_guide/release.rst
doc/whatsnew/3/3.1/index.rst
doc/whatsnew/3/3.2/index.rst
doc/whatsnew/3/index.rst
doc/whatsnew/fragments/8701.feature
doc/whatsnew/fragments/8808.bugfix
doc/whatsnew/fragments/8827.false_negative
doc/whatsnew/fragments/8855.new_check
doc/whatsnew/fragments/8935.other
doc/whatsnew/fragments/8947.false_negative
doc/whatsnew/fragments/9097.feature
doc/whatsnew/fragments/9100.other
doc/whatsnew/fragments/9106.false_positive
doc/whatsnew/fragments/9167.false_positive
doc/whatsnew/fragments/9196.feature
doc/whatsnew/fragments/9228.feature
doc/whatsnew/fragments/9229.feature
doc/whatsnew/fragments/9334.feature
doc/whatsnew/fragments/9457.internal
examples/pylintrc
examples/pyproject.toml
pylint/__pkginfo__.py
tbump.toml
towncrier.toml

What's new in Pylint 3.1.0?
Release date: 2024-02-25
New Features
------------
- Skip ``consider-using-join`` check for non-empty separators if an ``suggest-join-with-non-empty-separator`` option is set to ``no``.
Closes #8701 
- Discover ``.pyi`` files when linting.
These can be ignored with the ``ignore-patterns`` setting.
Closes #9097 
- Check ``TypeAlias`` and ``TypeVar`` (PEP 695) nodes for ``invalid-name``.
Refs #9196 
- Support for resolving external toml files named pylintrc.toml and .pylintrc.toml.
Closes #9228 
- Check for `.clear`, `.discard`, `.pop` and `remove` methods being called on a set while it is being iterated over.
Closes #9334 
New Checks
----------
- New message `use-yield-from` added to the refactoring checker. This message is emitted …

Release branch 3.1.0

---

tests/primer/packages_to_prime.json

Thousands of messages are going in/out of the baseline on every PR, adding noise and friction to the contribution experience, and hiding other legitimate feedback due to comment length limitations. Make a start toward reducing this.

[primer] Only prime pandas.core

---

.pre-commit-config.yaml
doc/whatsnew/fragments/9443.feature
pylint/reporters/text.py
tests/test_self.py

A new `github` reporter has been added. This reporter automatically annotates code on GitHub's UI with the messages found during linting.
Closes #9443.

Add GitHub reporter

---

doc/whatsnew/fragments/9449.false_negative
pylint/checkers/imports.py
pylint/checkers/refactoring/refactoring_checker.py
tests/functional/i/inconsistent/inconsistent_returns.py
tests/functional/u/used/used_before_assignment_else_return.py
tests/functional/u/useless/useless_return.py
tests/functional/u/useless/useless_return.txt

Returns inside try or if/else conditions were not being detected as useless. Said nodes are now checked for return statements to ensure their last component is not a useless return as well.
Closes #9449.

Fix useless-return false negatives

---

doc/whatsnew/3/3.1/index.rst
doc/whatsnew/3/3.2/index.rst

These are lacking a whitespace so the RST parser doesn't recognize them as fields.

📝 Fix release RST fields @ 3.1/3.2 changelogs

---

doc/whatsnew/3/3.1/index.rst

Missing whitespaces confuse RST parsers and they fail to recognize that em dashes don't need to remain double hyphens.

📝 Fix RST mdash typos @ 3.1 changelog summary

---

doc/whatsnew/1/1.5.rst
doc/whatsnew/2/2.11/full.rst
doc/whatsnew/2/2.11/summary.rst
pylint/config/arguments_manager.py
tests/functional/a/access/access_attr_before_def_false_positive.py
tests/functional/e/.#emacs_file_lock.py

This just fixes a handful of typos in comments or documentation.

Fix various typos

---

doc/whatsnew/fragments/9584.false_negative
pylint/checkers/classes/class_checker.py
tests/functional/p/property_with_parameters.py
tests/functional/p/property_with_parameters.txt

Fix false negative for ``property-with-parameters`` in the case of parameters which are ``positional-only``, ``keyword-only``, ``variadic positional`` or ``variadic keyword``.
Closes #9584

Fix false negative for ``property-with-parameters``

---

doc/whatsnew/fragments/9345.false_positive
pylint/checkers/design_analysis.py
tests/functional/t/too/too_few_public_methods_37.py

Beginning with attrs 21.1.0, the recommended way to use attrs is through `import attrs` and using `attrs.define`/`attrs.frozen`, not `import attr` and `attr.s` or `attr.attrs`. Pylint does understand `attr.attrs` (#2988), but new-style uses of attrs are not understood to be data class decorators.
Modify `_is_exempt_from_public_methods` to recognize `attrs.define` and `attrs.frozen` in a similar way as is currently done with `dataclasses.dataclass`.
Closes #9345

Recognize new-style attrs decorators in too-few-public-methods check

---

doc/whatsnew/fragments/9554.false_positive
pylint/checkers/refactoring/recommendation_checker.py
tests/functional/c/consider/consider_using_dict_items.py
tests/functional/c/consider/consider_using_dict_items.txt

Fix a false positive for ``consider-using-dict-items`` when iterating ``os.environ`` using the ``os.environ.keys()`` operation and then deleting an item using the key as a lookup.
Closes #9554

Fix a false positive for ``consider-using-dict-items``

---

doc/whatsnew/fragments/9310.performance
pylint/checkers/imports.py

If possible it is desirable to look for modules with no context file as it results in no search paths being given to astroid's find_spec(). This makes calls to it more uniform and opens up the possibility of effective caching.
Refs #9310.

Avoid search paths for ImportChecker when possible

---

pylint/config/config_initialization.py
pyproject.toml
script/create_contributor_list.py

There's some cleanup to do, but we can wait for ruff to autofix most of it. (We need to be careful when performance is a convern i.e. in loops). In the meantime this will make sure that we don't regress on what's already clean.

[ruff] Add 'flake8-pathlib' disable the messages that need fixing later

---

doc/whatsnew/fragments/9606.internal
pyproject.toml
requirements_test_min.txt
tests/functional/r/regression_02/regression_4660.py
tests/functional/r/regression_02/regression_4660.txt

https://github.com/pylint-dev/astroid/releases/tag/v3.2.0
Test change shows improvement anticipated in https://github.com/pylint-dev/pylint/issues/5273#issuecomment-2094363721.

Bump astroid to 3.2.0

---

.pyenchant_pylint_custom_dict.txt
doc/user_guide/configuration/all-options.rst
doc/whatsnew/fragments/9442.other
examples/pylintrc
examples/pyproject.toml
pylint/lint/base_options.py
pylint/lint/pylinter.py
pylintrc
tests/lint/test_pylinter.py
tests/test_functional.py

Adds ignored modules to the Astroid deny list so they may be truly ignored as they will now not be imported at all.
Depends on Astroid change pylint-dev/astroid#2399
Closes #9442

Add ignored modules to Astroid module deny list

---

doc/whatsnew/3/3.1/index.rst
doc/whatsnew/fragments/9345.false_positive
doc/whatsnew/fragments/9531.false_positive
doc/whatsnew/fragments/9554.false_positive
pylint/__pkginfo__.py
tbump.toml
towncrier.toml

What's new in Pylint 3.1.1?
Release date: 2024-05-13
- Treat `attrs.define` and `attrs.frozen` as dataclass decorators in
`too-few-public-methods` check.
Closes #9345
- Fix a false positive with ``singledispatchmethod-function`` when a method is decorated with both ``functools.singledispatchmethod`` and ``staticmethod``.
Closes #9531
- Fix a false positive for ``consider-using-dict-items`` when iterating using ``keys()`` and then deleting an item using the key as a lookup.
Closes #9554

Bump pylint to 3.1.1, update changelog

---

doc/data/messages/t/trailing-comma-tuple/details.rst
doc/whatsnew/fragments/9608.performance
pylint/checkers/refactoring/refactoring_checker.py

Performance analysis by @correctmost. Follow up to fix the known limitation will be in #9609 
Refs #8606 (follow-up)
Closes #9608

[performance] Check that 'trailing-comma-tuple' is enabled only once

---

doc/whatsnew/fragments/9273.false_negative
pylint/lint/expand_modules.py
tests/regrtest_data/ignore_pattern/.hidden/module.py
tests/regrtest_data/ignore_pattern/module.py
tests/test_self.py

Fix a false negative for ``--ignore-patterns`` when the directory to be linted is specified using a dot(``.``) and all files are ignored instead of only the files whose name begin with a dot.
Closes #9273

Fix a false negative for ``--ignore-patterns``

---

doc/whatsnew/fragments/9638.false_positive
pylint/checkers/base/name_checker/checker.py
tests/functional/t/type/typevar_naming_style_py312.py
tests/functional/t/type/typevar_naming_style_py312.txt

Don't emit ``typevar-name-incorrect-variance`` warnings for PEP 695 style TypeVars.
The variance is inferred automatically by the type checker.
Adding ``_co`` or ``_contra`` suffix can help to reason about TypeVar.

Don't emit incorrect-variance for type parameters (PEP 695)

---

doc/whatsnew/fragments/9643.false_positive
pylint/checkers/variables.py
pylint/constants.py
tests/functional/u/used/used_before_assignment_py311.py
tests/functional/u/used/used_before_assignment_py311.rc

Closes #9643
Thanks @efroemling for the report and test case.

Fix FP for `possibly-used-before-assignment` with `assert_never()`

---

doc/whatsnew/3/3.2/index.rst
doc/whatsnew/fragments/9139.internal
doc/whatsnew/fragments/9145.bugfix
doc/whatsnew/fragments/9273.false_negative
doc/whatsnew/fragments/9608.bugfix
doc/whatsnew/fragments/9626.bugfix
doc/whatsnew/fragments/9627.false_positive
doc/whatsnew/fragments/9638.false_positive
doc/whatsnew/fragments/9643.false_positive
pylint/__pkginfo__.py
tbump.toml
towncrier.toml

What's new in Pylint 3.2.1?
Release date: 2024-05-18
- Exclude if/else branches containing terminating functions (e.g. `sys.exit()`)
from `possibly-used-before-assignment` checks.
Closes #9627
- Don't emit ``typevar-name-incorrect-variance`` warnings for PEP 695 style TypeVars.
The variance is inferred automatically by the type checker.
Adding ``_co`` or ``_contra`` suffix can help to reason about TypeVar.
Refs #9638
- Fix a false positive for `possibly-used-before-assignment` when using
`typing.assert_never()` (3.11+) to indicate exhaustiveness.
Closes #9643
- Fix a false negative for ``--ignore-patterns`` when the directory to be linted is specified using a dot(``.``) and all files …

Bump pylint to 3.2.1, update changelog

---

.pre-commit-config.yaml
doc/development_guide/contributor_guide/release.rst
doc/faq.rst
doc/user_guide/installation/pre-commit-integration.rst
doc/user_guide/usage/run.rst

Closes #9341 
Closes #9465 
Also fix the release doc for something that bit me during 3.1.0 release.

Details about known caveats of using multiple processes in pre-commit

---

doc/whatsnew/fragments/9406.false_positive
pyproject.toml
requirements_test_min.txt
tests/functional/g/generic_class_syntax.py
tests/functional/g/generic_class_syntax_py312.py
tests/functional/g/generic_class_syntax_py312.rc
tests/functional/g/generic_class_syntax_py312.txt

Update astroid to `3.2.2` to fix multiple false positives with generic class syntax added in Python 3.12 (PEP 695).
This included
- useless-parent-delegation
- attribute-defined-outside-init
- access-member-before-definition
- non-parent-init-called
- unsubscriptable-object
It does `not` address the `undefined-variable` issue.
- #9335
--
https://github.com/pylint-dev/astroid/releases/tag/v3.2.2
Closes #9406

Update astroid to 3.2.2

---

doc/whatsnew/fragments/9653.false_negative
pylint/checkers/typecheck.py
tests/functional/a/await_outside_async.py
tests/functional/a/await_outside_async.txt

Also check Lambda for await-outside-async.

Also check Lambda for await-outside-async

---

doc/data/messages/c/contextmanager-generator-missing-cleanup/bad.py
doc/data/messages/c/contextmanager-generator-missing-cleanup/details.rst
doc/data/messages/c/contextmanager-generator-missing-cleanup/good.py
doc/whatsnew/fragments/9625.false_positive
pylint/checkers/base/function_checker.py
tests/functional/c/contextmanager_generator_missing_cleanup.py
tests/functional/c/contextmanager_generator_missing_cleanup.txt

An attempt at fixing the false-positives with the `contextmanager-generator-missing-cleanup` check where no cleanup happens after a singular yield.
Closes #9625

Fix false-positive with contextmanager missing cleanup

---

doc/whatsnew/3/3.2/index.rst
doc/whatsnew/fragments/9406.false_positive
doc/whatsnew/fragments/9625.false_positive
pylint/__pkginfo__.py
tbump.toml
towncrier.toml

What's new in Pylint 3.2.2?
Release date: 2024-05-20
- Fix multiple false positives for generic class syntax added in Python 3.12 (PEP 695).
Closes #9406
- Exclude context manager without cleanup from
``contextmanager-generator-missing-cleanup`` checks.
Closes #9625

Bump pylint to 3.2.2, update changelog

---

pylint/checkers/__init__.py
pylint/checkers/refactoring/implicit_booleaness_checker.py
pylint/checkers/similar.py
pylint/checkers/typecheck.py
pylint/testutils/_primer/primer.py
pylintrc
tests/message/unittest_message.py
tests/test_check_parallel.py

Original: #9644
Enables `possibly-used-before-assignment` for the pylint codebase, fixes the errors in two files, and locally disables the rest.
The disabled errors can probably be fixed but would need extra code coverage.
Refs #9637

Enable `possibly-used-before-assignment` and fix a few of them

---

doc/user_guide/checkers/features.rst
doc/whatsnew/fragments/9669.false_negative
pylint/checkers/base/basic_error_checker.py
tests/functional/a/async_functions.txt
tests/functional/d/duplicate/duplicate_argument_name.py
tests/functional/d/duplicate/duplicate_argument_name.txt
tests/functional/d/duplicate/duplicate_argument_name_py3.py
tests/functional/d/duplicate/duplicate_argument_name_py3.txt

Fix a false negative for ``duplicate-argument-name`` by including ``positional-only``, ``*args`` and ``**kwargs`` arguments in the check.
Closes #9669

Fix a false negative for ``duplicate-argument-name``

---

doc/whatsnew/fragments/9671.false_positive
pylint/checkers/variables.py
tests/conftest.py
tests/functional/r/redefined/redefined_except_handler.py

Fix a false positive for ``redefined-outer-name`` when there is a name defined in an exception-handling block which shares the same name as a local variable that has been defined in a function body.
Closes #9671

Fix a false positive for ``redefined-outer-name``

---

doc/whatsnew/fragments/9696.false_positive
pylint/checkers/refactoring/refactoring_checker.py
tests/functional/u/use/use_yield_from.py

If the return value from `yield` is inspected inline, such as by (augmented) assignment, changing the looped `yield` to `yield from` is very likely to change the semantics of the generator, since there is an implicit use of `generator.send`.
The type-hint component of #9696 feels (to me) like it would be suitable to suppress with a local lint suppression rather than complex type inference within pylint; it's a pretty unusual construction.
Closes #9696

Fix false positive in `use-yield-from` when using `yield` return

---

doc/whatsnew/3/3.2/index.rst
doc/whatsnew/fragments/9398.false_positive
doc/whatsnew/fragments/9671.false_positive
doc/whatsnew/fragments/9696.false_positive
examples/pylintrc
examples/pyproject.toml
pylint/__pkginfo__.py
tbump.toml
towncrier.toml

What's new in Pylint 3.2.3?
Release date: 2024-06-06
- Classes with only an Ellipsis (``...``) in their body do not trigger 'multiple-statements'
anymore if they are inlined (in accordance with black's 2024 style).
Closes #9398 
- Fix a false positive for ``redefined-outer-name`` when there is a name defined in an exception-handling block which shares the same name as a local variable that has been defined in a function body.
Closes #9671 
- Fix a false positive for ``use-yield-from`` when using the return value from the ``yield`` atom.
Closes #9696

Release branch 3.2.3

---

doc/whatsnew/fragments/8866.bugfix
pylint/checkers/variables.py
tests/functional/u/undefined/undefined_variable.py
tests/functional/u/undefined/undefined_variable.txt

[undefined-variable] Fix a crash for undefined lineno in annotations

---

doc/whatsnew/fragments/9078.bugfix
pylint/checkers/refactoring/refactoring_checker.py
tests/functional/u/unnecessary/unnecessary_list_index_lookup.py

[unnecessary-list-index-lookup] Fix crashes for uninferrable 'start' value in 'enumerate'

---

doc/whatsnew/fragments/9680.bugfix
pylint/config/argument.py
tests/config/functional/toml/issue_9680/bad_regex_in_ignore_paths.32.out
tests/config/functional/toml/issue_9680/bad_regex_in_ignore_paths.toml
tests/config/test_functional_config_loading.py

Fix 'ignore-paths' from #9680, in particular, but other using this function too.
Closes #9680

Gracefully handle invalid paths csv regex in conf/args

---

doc/data/messages/p/possibly-used-before-assignment/details.rst

Closes #9715 
Document using `assert_never` for declaring exhaustiveness to avoid `possibly-used-before-assignment`.
Clarify "exact same test" exception.

[possibly-used-before-assignment] Model using assert_never

---

doc/symilar.rst
doc/whatsnew/fragments/9734.internal
pylint/__init__.py
pylint/checkers/symilar.py
tests/checkers/unittest_symilar.py
tests/test_similar.py

Correct ``similar`` to ``symilar`` when talking about the standalone script

---

doc/data/messages/i/invalid-name/details.rst

Documentation - Update `class-const` definition to:
`Enum constants and class variables annotated with Final`
Closes https://github.com/pylint-dev/pylint/issues/9724

Documentation - Update `class-const` definition.

---

doc/whatsnew/fragments/9727.bugfix
pylint/config/find_default_config_files.py
tests/config/test_find_default_config_files.py

Fix a bug where a ``tox.ini`` file with pylint configuration was ignored and it exists in the current directory.
Closes #9727

Add `tox.ini` to the default discovered config files (right after setup.cfg)

---

doc/data/messages/p/possibly-used-before-assignment/details.rst
doc/whatsnew/fragments/9674.false_positive
pylint/checkers/utils.py
pylint/checkers/variables.py
tests/functional/u/used/used_before_assignment.py
tests/functional/u/used/used_before_assignment.txt

Closes #9674 for the general case, but not necessarily for pytest.skip due to the following:
```py
from astroid import extract_node
n = extract_node("""
... import pytest
... pytest.skip('foo')""")
>>> n.func.inferred()
[Uninferable]
```

[possibly-used-before-assignment] Avoid FP for typing.NoReturn

---

doc/data/messages/p/possibly-used-before-assignment/details.rst
doc/whatsnew/fragments/9674.false_positive
pylint/checkers/utils.py
pylint/checkers/variables.py
tests/functional/u/used/used_before_assignment.py
tests/functional/u/used/used_before_assignment.txt

Manual backport of #9714 after a cherry-pick conflict.

Backport [possibly-used-before-assignment] Avoid FP for typing.NoReturn & Never

---

doc/whatsnew/3/3.2/index.rst
doc/whatsnew/fragments/8866.bugfix
doc/whatsnew/fragments/9078.bugfix
doc/whatsnew/fragments/9343.bugfix
doc/whatsnew/fragments/9674.false_positive
pylint/__pkginfo__.py
tbump.toml
towncrier.toml

What's new in Pylint 3.2.4?
Release date: 2024-06-25
- Prevent emitting ``possibly-used-before-assignment`` when relying on names
only potentially not defined in conditional blocks guarded by functions
annotated with ``typing.Never`` or ``typing.NoReturn``.
Closes #9674 
- Fixed a crash when the lineno of a variable used as an annotation wasn't available for ``undefined-variable``.
Closes #8866
- Fixed a crash when the ``start`` value in an ``enumerate`` was non-constant and impossible to infer
(like in``enumerate(apples, start=int(random_apple_index)``) for ``unnecessary-list-index-lookup``.
Closes #9078
- Fixed a crash in ``symilar`` when the ``-d`` or ``-i`` short option were not …

Bump pylint to 3.2.4, update changelog

---

doc/whatsnew/fragments/9751.bugfix
pylint/checkers/utils.py
tests/functional/r/regression_02/regression_9751.py
tests/functional/u/used/used_before_assignment.py
tests/functional/u/used/used_before_assignment_py38.py
tests/functional/u/used/used_before_assignment_py38.rc

Closes #9751 regression introduced in #9714 by https://github.com/pylint-dev/pylint/commit/c41c35a8e0dd71ba96944613e6a2ced830407670

False positive ``unreachable-code`` when using ``typing.Any`` as return in python 3.8

---

doc/whatsnew/3/3.2/index.rst
doc/whatsnew/fragments/9751.bugfix
pylint/__pkginfo__.py
tbump.toml
towncrier.toml

What's new in Pylint 3.2.5?
Release date: 2024-06-28
- Fixed a false positive ``unreachable-code`` when using ``typing.Any`` as return type in python
3.8, the ``typing.NoReturn`` are not taken into account anymore for python 3.8 however.
Closes #9751

Bump pylint to 3.2.5, update changelog

---

doc/user_guide/usage/run.rst
doc/whatsnew/fragments/9764.bugfix
pylint/lint/expand_modules.py
tests/lint/unittest_expand_modules.py

Improve file discovery for directories that are not packages

---

doc/whatsnew/fragments/9765.false_positive
pylint/checkers/base/name_checker/checker.py
tests/functional/i/invalid/invalid_name.py
tests/functional/i/invalid/invalid_name.rc
tests/functional/i/invalid/invalid_name.txt

Fix `invalid-name` regression for class attributes in subclasses

---

doc/development_guide/contributor_guide/tests/writing_test.rst
doc/whatsnew/fragments/9774.other
pylint/testutils/functional/test_file.py
pylint/testutils/lint_module_test.py
pylint/testutils/output_line.py
tests/testutils/test_output_line.py

This reverts commit 4b45192113654c9403c288824bff1ff01c29e061 and 833762fd6f3326d61b897ffa2dab6086b8c8edc4..
See https://github.com/pylint-dev/pylint/pull/9774#discussion_r1671215907.

Revert "Remove `--min_pyver_end_position`"

---

doc/whatsnew/fragments/9214.bugfix
pyproject.toml
requirements_test_min.txt

Bump astroid to 3.2.3

---

doc/whatsnew/fragments/9780.false_positive
pylint/checkers/variables.py
tests/functional/u/used/used_before_assignment_py311.py
tests/functional/u/used/used_before_assignment_py311.rc

(cherry picked from commit a48cd4c6a872b6565bc58030b74585812f327f36)

Handle assert_never() when imported from typing_extensions (#9782)

---

doc/whatsnew/fragments/9739.false_positive
pylint/extensions/docparams.py
tests/functional/ext/docparams/missing_param_doc.py
tests/functional/ext/docparams/missing_param_doc.txt

Fix a false positive for ``missing-param-doc`` where a method which is decorated with ``typing.overload`` was expected to have a docstring specifying its parameters.
Closes #9739

Fix a false positive for ``missing-param-doc``

---

.github/workflows/checks.yaml
doc/data/messages/a/anomalous-backslash-in-string/bad.py
doc/data/messages/a/anomalous-backslash-in-string/details.rst
doc/data/messages/a/anomalous-unicode-escape-in-string/bad.py
doc/data/messages/u/using-exception-groups-in-unsupported-version/bad.py
doc/data/messages/u/using-exception-groups-in-unsupported-version/details.rst
doc/data/messages/u/using-exception-groups-in-unsupported-version/good.py
doc/data/messages/u/using-exception-groups-in-unsupported-version/pylintrc
doc/data/messages/u/using-generic-type-syntax-in-unsupported-version/bad.py
doc/data/messages/u/using-generic-type-syntax-in-unsupported-version/details.rst
doc/data/messages/u/using-generic-type-syntax-in-unsupported-version/good.py
doc/data/messages/u/using-generic-type-syntax-in-unsupported-version/pylintrc
doc/user_guide/checkers/features.rst
doc/user_guide/messages/messages_overview.rst
doc/whatsnew/fragments/9791.new_check
pylint/checkers/unsupported_version.py
tests/functional/u/unsupported/unsupported_version_for_exception_group.py
tests/functional/u/unsupported/unsupported_version_for_exception_group.rc
tests/functional/u/unsupported/unsupported_version_for_exception_group.txt
tests/functional/u/unsupported/unsupported_version_for_generic_type_syntax.py
tests/functional/u/unsupported/unsupported_version_for_generic_type_syntax.rc
tests/functional/u/unsupported/unsupported_version_for_generic_type_syntax.txt

Add unsupported version checks for major 3.11 and 3.12 features

---

doc/whatsnew/fragments/9814.bugfix
pylint/checkers/classes/class_checker.py
tests/functional/s/slots_checks.py

Fix a crash when a subclass extends `__slots__`

---

pyproject.toml
requirements_test_min.txt
tests/functional/r/recursion/recursion_error_3159.py

Update setuptools version used for tests and build.
Fixes https://github.com/pylint-dev/pylint/security/dependabot/2
https://setuptools.pypa.io/en/latest/history.html#v71-0-4

Update setuptools to >=71.0.4

---

pyproject.toml
requirements_test_min.txt

(cherry picked from commit c9c768e2fb56b9af3b0a5a25f0515bfd8cd0938b)

[Backport maintenance/3.2.x] Bump astroid to 3.2.4 (#9816)

---

doc/whatsnew/fragments/9814.bugfix
pylint/checkers/classes/class_checker.py
tests/functional/s/slots_checks.py

(cherry picked from commit 8e18fc012a5fcbd6cfe2b719e35ecd995da9f4bf)

[Backport maintenance/3.2.x] Fix a crash when a subclass extends `__slots__` (#9817)

---

.pre-commit-config.yaml

Prevents this error on Python 3.13:
```py
ExtensionError: Could not import extension sphinx.builders.epub3 (exception: No 
module named 'imghdr')
```
We were already pinning Sphinx in docs/requirements.txt:
https://github.com/pylint-dev/pylint/blob/60bd2307c220210b6dd6b739c382c6b3c45d75c4/doc/requirements.txt#L1

Sync Sphinx version in pre-commit config

---

doc/whatsnew/3/3.2/index.rst
doc/whatsnew/fragments/9214.bugfix
doc/whatsnew/fragments/9672.false_positive
doc/whatsnew/fragments/9739.false_positive
doc/whatsnew/fragments/9765.false_positive
doc/whatsnew/fragments/9780.false_positive
doc/whatsnew/fragments/9800.false_negative
doc/whatsnew/fragments/9814.bugfix
pylint/__pkginfo__.py
tbump.toml
towncrier.toml

What's new in Pylint 3.2.6?
Release date: 2024-07-21
- Quiet false positives for `unexpected-keyword-arg` when pylint cannot
determine which of two or more dynamically defined classes is being instantiated.
Closes #9672
- Fix a false positive for ``missing-param-doc`` where a method which is decorated with ``typing.overload`` was expected to have a docstring specifying its parameters.
Closes #9739
- Fix a regression that raised ``invalid-name`` on class attributes merely
overriding invalid names from an ancestor.
Closes #9765
- Treat `assert_never()` the same way when imported from `typing_extensions`.
Closes #9780
- Fix a false positive for `consider-using-min-max-builtin` when the assignment target is an attribute. …

Bump pylint to 3.2.6, update changelog

---

README.rst

The existing link resolves to an archived repository. The new repository is blessed by the old one to publish to `pylint-sonarjson` on PyPI.

Update repo for pylint-sonarjson

---

README.rst
pyproject.toml
requirements_test_min.txt
tests/functional/i/inconsistent/inconsistent_quotes_fstring.py
tests/functional/i/inconsistent/inconsistent_quotes_fstring_py312.py
tests/functional/i/inconsistent/inconsistent_quotes_fstring_py312_311.py

Bump astroid to 3.3.1

---

doc/whatsnew/fragments/9865.bugfix
pylint/checkers/refactoring/refactoring_checker.py
tests/functional/r/regression/regression_9865_calling_bound_lambda.py

Fixes:
```
File "sources/pylint/pylint/checkers/refactoring/refactoring_checker.py", line 2094, in _is_function_def_never_returning
and node.returns
^^^^^^^^^^^^
File "sources/pylint/.venv/lib/python3.11/site-packages/astroid/bases.py", line 138, in __getattr__
return getattr(self._proxied, name)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Lambda' object has no attribute 'returns'
```
Crash is reproducible if you have something like this:
```python
class C:
eq = lambda self, y: self == y
```
As a workaround, use a normal function instead of a lambda.
Closes #9865

Fix crash in refactoring checker when calling bound lambda

---

doc/whatsnew/fragments/9865.bugfix
pylint/checkers/refactoring/refactoring_checker.py
tests/functional/r/regression/regression_9865_calling_bound_lambda.py

Manual backport of b78deb6140799549ae5f2afc9cb5bc8c1afda5cc from #9866

[Backport maintenance/3.2.x] Fix crash in refactoring checker when calling bound lambda

---

doc/whatsnew/fragments/9875.bugfix
pylint/checkers/variables.py
tests/functional/r/regression/regression_9875_enumerate.py
tests/functional/r/regression/regression_9875_enumerate.txt

Regression in #7132
Closes #9875

Fix a crash in `undefined-loop-variable` with `enumerate()`

---

doc/data/messages/t/too-few-function-args/bad.py
doc/data/messages/t/too-few-function-args/details.rst
doc/data/messages/t/too-few-function-args/good.py
doc/user_guide/checkers/features.rst
doc/user_guide/messages/messages_overview.rst
doc/whatsnew/fragments/9847.false_negative
doc/whatsnew/fragments/9847.new_check
doc/whatsnew/fragments/9881.bugfix
pylint/checkers/typecheck.py
tests/functional/a/arguments.py
tests/functional/a/arguments.txt
tests/functional/c/consider/consider_merging_isinstance.py
tests/functional/c/consider/consider_merging_isinstance.txt
tests/functional/t/too/too_few_function_args.py
tests/functional/t/too/too_few_function_args.txt

The addition of a new message, `too-few-function-args`, in #9847, overlaps (fully) with an existing message `no-value-for-parameter`. Because the `too-few-function-args` was only implemented for `isinstance`, this PR only seeks to transfer those messages over to the existing message `no-value-for-parameter` with hard-coded argument names for `isinstance` because it's a built-in function.
Closes #9881

`too-few-function-args` redundant with `no-value-for-parameter`

---

doc/user_guide/checkers/features.rst
pylint/checkers/classes/class_checker.py

Fixed typo in the description of message W0212: "access" -> "accessed".

Fixed typo in W0212

---

doc/whatsnew/fragments/9731.user_action
pylint/checkers/symilar.py
tests/checkers/unittest_symilar.py

Follow-up to #9709, had to open a new PR because it's impossible to change the target branch in #9710 to reopen.

[symilar] Migrate from getopt to argparse

---

doc/development_guide/contributor_guide/index.rst
doc/development_guide/contributor_guide/oss_fuzz.rst

Add documentation for the OSS-Fuzz integration.
Refs https://github.com/pylint-dev/astroid/issues/2511
(This documentation is based on documentation I previously wrote for librsvg: https://gitlab.gnome.org/GNOME/librsvg/-/merge_requests/983.)

Add docs for OSS-Fuzz integration

---

doc/whatsnew/3/3.2/index.rst
doc/whatsnew/fragments/9840.false_positive
doc/whatsnew/fragments/9865.bugfix
doc/whatsnew/fragments/9875.bugfix
doc/whatsnew/fragments/9883.bugfix
pylint/__pkginfo__.py
tbump.toml
towncrier.toml

What's new in Pylint 3.2.7?
Release date: 2024-08-31
- Fixed a false positive `unreachable` for `NoReturn` coroutine functions.
Closes #9840
- Fix crash in refactoring checker when calling a lambda bound as a method.
Closes #9865
- Fix a crash in ``undefined-loop-variable`` when providing the ``iterable`` argument to ``enumerate()``.
Closes #9875
- Fix to address indeterminacy of error message in case a module name is same as another in a separate namespace.
Refs #9883

Bump pylint to 3.2.7, update changelog

---

examples/pylintrc
examples/pyproject.toml

The comment for `min-public-methods` got accidentally reused.

Fix max-positional-arguments comments in example config files

---

pylint/utils/ast_walker.py

`ASTWalker.walk` was calling `get` ~1.42 million times when linting yt-dlp.  This is a small speed-up that also helps unclutter profiler output.
```
$ python -m timeit -s 'from collections import defaultdict; visit_events = defaultdict(list)' -n 1000000 'x=visit_events.get("x", ())'
1000000 loops, best of 5: 50.7 nsec per loop
$ python -m timeit -s 'from collections import defaultdict; visit_events = defaultdict(list)' -n 1000000 'x=visit_events["x"]'
1000000 loops, best of 5: 29.4 nsec per loop
```
```
ncalls  tottime  percall  cumtime  percall filename:lineno(function)
2123486    0.529    0.000    0.529    0.000 {method 'get' of 'dict' objects}
```
| Command | Mean [s] | Min [s] | Max [s] …

Don't use .get() with defaultdicts

---

doc/whatsnew/fragments/9759.false_negative
pylint/checkers/format.py
tests/functional/m/multiple_statements.py
tests/functional/m/multiple_statements.txt

I took a look at 5bdc2218ef9891e9047823c26625c62d68f2dc52 and noticed that some inference logic got removed in `format.py` while refactoring to use the updated `Try` node. The purpose of this PR is to reintroduce the inference of `else` and `finally` line numbers to check for multiple statements on `else/finally` lines in a try statement.
This check is a little explicit because of how `else` and `finally` is represented in the AST, without a tree node to represent an `else` or `finally` line. However, it should work for general cases, except for unusual cases like:
```
try:
pass
except:
pass …
```

Fix false negative for `multiple-statements` on try... else/finally lines

---

.pre-commit-config.yaml
doc/data/ruff.toml
pyproject.toml

This makes it easier to run `ruff check` outside of the pre-commit hooks.

Move most ruff exclusions out of .pre-commit-config.yaml

---

pylint/checkers/imports.py
pylint/checkers/stdlib.py

See:
https://docs.python.org/3.13/whatsnew/3.13.html#new-deprecations

Add additional stdlib deprecations (mostly 3.13)

---

.github/workflows/primer_run_main.yaml
.github/workflows/primer_run_pr.yaml

On the theory that we might see primer indeterminacy due to incompletely created virtual environments being cached when jobs are interrupted (due to `cancel-in-progress: true`), exercise some control by running separate `actions/restore` and `actions/save` actions.
Refs https://github.com/pylint-dev/pylint/pull/9925#issuecomment-2358249852
cc/ @akamat10

Explicitly save cache in primer jobs

---

doc/data/messages/c/c-extension-no-member/details.rst
doc/data/messages/t/typevar-name-incorrect-variance/details.rst

Add details.rst for c-extension-no-member

---

doc/data/messages/u/unrecognize-option/details.rst
doc/data/messages/u/unrecognized-option/details.rst
doc/exts/pylint_messages.py

Following #9933 that closed #5953, we're now able to check that we have a good example and a bad example. Some message need to be permitted to not have examples. This permitted to catch a typo in the doc (unrecognize-option) but we could check that no directory that shouldn't exists do, too.

[doc framework] Assert that the good and bad example exists in the doc

---

doc/data/messages/u/unnecessary-default-type-args/bad.py
doc/data/messages/u/unnecessary-default-type-args/details.rst
doc/data/messages/u/unnecessary-default-type-args/good.py
doc/data/messages/u/unnecessary-default-type-args/pylintrc
doc/data/messages/u/unnecessary-default-type-args/related.rst
doc/user_guide/checkers/extensions.rst
doc/user_guide/messages/messages_overview.rst
doc/whatsnew/fragments/9938.new_check
pylint/checkers/exceptions.py
pylint/checkers/symilar.py
pylint/checkers/variables.py
pylint/extensions/typing.py
pylint/pyreverse/diadefslib.py
pylint/testutils/checker_test_case.py
pylint/testutils/utils.py
pylint/utils/pragma_parser.py
tests/functional/ext/typing/unnecessary_default_type_args.py
tests/functional/ext/typing/unnecessary_default_type_args.rc
tests/functional/ext/typing/unnecessary_default_type_args.txt
tests/functional/ext/typing/unnecessary_default_type_args_py313.py
tests/functional/ext/typing/unnecessary_default_type_args_py313.rc
tests/functional/ext/typing/unnecessary_default_type_args_py313.txt
tests/pyreverse/test_inspector.py

Starting with Python 3.13, `typing.Generator` and `typing.AsyncGenerator` have default type argument. E.g. it's no longer necessary to specify `None, None` for the send and return type.
```py
a1: Generator[int, None, None]
a1: Generator[int]
```
This check is similar to the one in ruff but extends on it to also cover the collections.abc` variants which can also be used with older Python versions.
https://docs.astral.sh/ruff/rules/unnecessary-default-type-args/
https://github.com/asottile/pyupgrade?tab=readme-ov-file#pep-696-typevar-defaults

Add check for `unnecessary-default-type-args`

---

CONTRIBUTORS.txt
doc/whatsnew/3/3.3/index.rst
doc/whatsnew/3/3.4/index.rst
doc/whatsnew/3/index.rst
doc/whatsnew/fragments/7565.false_negative
doc/whatsnew/fragments/9099.new_check
doc/whatsnew/fragments/9403.bugfix
doc/whatsnew/fragments/9499.feature
doc/whatsnew/fragments/9653.false_negative
doc/whatsnew/fragments/9669.false_negative
doc/whatsnew/fragments/9680.bugfix
doc/whatsnew/fragments/9727.bugfix
doc/whatsnew/fragments/9731.user_action
doc/whatsnew/fragments/9734.internal
doc/whatsnew/fragments/9759.false_negative
doc/whatsnew/fragments/9764.bugfix
doc/whatsnew/fragments/9774.other
doc/whatsnew/fragments/9791.new_check
doc/whatsnew/fragments/9820.new_check
doc/whatsnew/fragments/9823.new_check
doc/whatsnew/fragments/9847.false_negative
doc/whatsnew/fragments/9852.other
doc/whatsnew/fragments/9925.internal
doc/whatsnew/fragments/9938.new_check
pylint/__pkginfo__.py
script/.contributors_aliases.json
tbump.toml
towncrier.toml

What's new in Pylint 3.3.0?
Release date: 2024-09-20
Changes requiring user actions
------------------------------
- We migrated ``symilar`` to argparse, from getopt, so the error and help output changed
(for the better). We exit with 2 instead of sometime 1, sometime 2. The error output
is not captured by the runner anymore. It's not possible to use a value for the
boolean options anymore (``--ignore-comments 1`` should become ``--ignore-comments``).
Refs #9731
New Features
------------
- Add new `declare-non-slot` error which reports when a class has a `__slots__` member and a type hint on the class is not present in `__slots__`.
Refs #9499
New Checks
----------
- Added `too-many-positional-arguments` to allow distinguishing the configuration for too many …

Release branch 3.3.0

---

tests/checkers/unittest_imports.py

This PR addresses an issue with two tests (`test_wildcard_import_init` and `test_wildcard_import_non_init`) in [tests/checkers/unittest_imports.py](https://github.com/pylint-dev/pylint/blob/main/tests/checkers/unittest_imports.py) that I discovered while attempting to fix #9883.
The issue with the tests is that the tests are invalid and only work due to modified `sys.path` in https://github.com/pylint-dev/pylint/blob/main/tests/pyreverse/conftest.py#L70. This can be reproduced by running the test on only the file:
```
tox -e py312 -- tests/checkers/unittest_imports.py
```
the above command fails and I see the following:
```
FAILED tests/checkers/unittest_imports.py::TestImportsChecker::test_w …
```

Fix two incorrect/broken tests in `tests/checkers/unittest_imports.py`

---

doc/development_guide/contributor_guide/oss_fuzz.rst

The issue tracker is migrating: https://github.com/google/oss-fuzz/issues/12508

Update OSS-Fuzz issue tracker links in contributor docs

---

doc/whatsnew/fragments/9947.false_positive
pyproject.toml
requirements_test_min.txt

Bump astroid to 3.3.4

---

doc/whatsnew/3/3.3/index.rst
doc/whatsnew/fragments/9947.false_positive
pylint/__pkginfo__.py
tbump.toml
towncrier.toml

What's new in Pylint 3.3.1?
Release date: 2024-09-24
- Fix regression causing some f-strings to not be inferred as strings.
Closes #9947

Bump pylint to 3.3.1, update changelog

---

doc/data/messages/t/too-many-positional-arguments/bad.py
doc/data/messages/t/too-many-positional-arguments/good.py
doc/data/messages/t/too-many-positional-arguments/pylintrc

Permits to see the option you have to change when reading the doc (probably the next frontier in our doc, is documenting the option that affect each message). Also made the example more concrete, added the effect on the API, and removed the class construct.

[too-many-positional-arguments doc] Add the main option to use, real example

---

doc/faq.rst

This document is in RST, but the link was mistakenly formatted using Markdown.
$sbj.

Fix the VS Code extension link syntax @ FAQ

---

pylint/checkers/variables.py

The `ScopeConsumer` class is only used by the `NamesConsumer`. It adds an extra level of indirection, but without providing any clear benefit. Cut it and incorporate its fields directly into `NamesConsumer`.

Cut ScopeConsumer

---

doc/whatsnew/fragments/9255.breaking

Refs #9255 
Previous PR https://github.com/pylint-dev/pylint/pull/9744 did not include a whatsnew fragment for the breaking changes

Add breaking fragment for fixme docstring support

---

doc/user_guide/checkers/features.rst
pylint/checkers/refactoring/refactoring_checker.py

Clarify no-else-raise and no-else-return also apply to try/except
Closes #9901

Clarify no-else-raise and no-else-return also apply to try/except

---

doc/data/messages/m/missing-format-argument-key/related.rst
doc/data/messages/t/too-few-format-args/related.rst
doc/data/messages/t/too-many-format-args/related.rst
pyproject.toml

The "second minor update" of astroid is 4.0.0-dev0, not 3.4 (there will not be a 3.4 of pylint or astroid 🤞)

Bump astroid ceiling

---

pylint/checkers/classes/class_checker.py
tests/functional/p/protected_access.py
tests/functional/p/protected_access.txt

1. it was incorrect when the property wasn't inside a class and the enclosing class didn't have an explicit metaclass
2. The conjugated test is full with errors and I can't understand the intention. (the errors: `MC` doesn't inherit `type`; `_nargs` isn't defined; `obj` isn't defined, etc). What is the pointed of testing protected access on an undefined variable?..
The PR is intentionally extreme (removing the whole test), and I wouldn't be surprised if I missed something and my change is incorrect. I'd be happy to adapt based on the feedback.
The primary reason for this PR is marked as `1.` in the commit description (or above).
One situation where this happens is the following. In new astroid "function-call" style properties don't have the enclosing class as the parent. The reason is …

remove metaclass check for protected access in properties

---

doc/whatsnew/fragments/10026.bugfix
pylint/lint/expand_modules.py
tests/pyreverse/test_main.py

Closes #10026
This PR fixes a bug in the `discover_package_path` function in pylint/pyreverse. The function was incorrectly handling cases where the source root is a child of the module directory, causing issues when using pyreverse with certain project structures, particularly those with a `src` layout.
The fix modifies the condition for identifying the correct source root, allowing it to handle both cases where the source root is a parent or a child of the module directory.
Changes made:
- Updated the condition in `discover_package_path` function to correctly identify the source root:
```python …
```

Fix source root not recognized

---

doc/development_guide/contributor_guide/contribute.rst
doc/make.bat

While working on [this follow-up PR](https://github.com/pylint-dev/pylint/pull/10063), I noticed that make.bat was not fully aligned with the Makefile. This PR brings make.bat up to date with the Makefile and updates the according documentation sections.

Update building docs

---

doc/whatsnew/fragments/10028.false_negative
pylint/checkers/variables.py
tests/functional/u/used/used_before_assignment_nonlocal.py
tests/functional/u/used/used_before_assignment_nonlocal.txt
tests/functional/u/used/used_before_assignment_typing.py
tests/functional/u/used/used_before_assignment_typing.txt

Raise `used-before-assignment` when a function is defined under `TYPE_CHECKING` and used later.
Also extending the nonlocal handling to resolve the following false positive that was discovered by the [primer tests](https://github.com/pylint-dev/pylint/pull/9990#issuecomment-2411463617), where a variable usage references a nonlocal binding from an outer, enclosing frame.
These changes mainly include a search for nonlocal declarations in all enclosing frames of the variable usage. The idea is to rely on existing nonlocal checks and to only check outer frames if all nodes are filtered out by the …

Resolve `used-before-assignment` false negative when a function is defined under `TYPE_CHECKING` 

---

pylint/checkers/variables.py
tests/functional/u/used/used_before_assignment_nonlocal.py
tests/functional/u/used/used_before_assignment_nonlocal.txt

A continuation of #10034. This PR addresses the case where a nonlocal declaration exists outside the immediate enclosing frame for both the usage and definition.
Changes primarily extend the check for nonlocal declarations so that it stops once it reaches the first enclosing frame, ensuring that it does not go beyond the initial enclosing frame.
Closes #10069

Fix `used-before-assignment` false negative for nonlocals

---

README.rst
doc/conf.py

Just a quick fix of the README

Fix RTD links to additional tools in the README

---

doc/whatsnew/fragments/10076.false_positive
pylint/checkers/variables.py
tests/functional/p/potential_index_error.py
tests/functional/p/potential_index_error.txt

The current implementation calculates the length of an indexed iterable by using its literal length. However, this approach fails when the iterable contains a starred element that unpacks into multiple elements.
For example:
```
lst = [1, 2, 3]
print([*lst][1])  # error reported as checker assumes indexed iterable has 1 element instead of 3.
```
This PR addresses the issue by extending the check to account for the inferred length of starred nodes within the indexed iterable.
Closes #10076

Fix `potential-index-error` false positive when iterable contains starred element

---

doc/whatsnew/3/3.3/index.rst
doc/whatsnew/fragments/10026.bugfix
doc/whatsnew/fragments/10076.false_positive
examples/pylintrc
examples/pyproject.toml
pylint/__pkginfo__.py
tbump.toml
towncrier.toml

- Fix a false positive for `potential-index-error` when an indexed iterable
contains a starred element that evaluates to more than one item.
Closes #10076
- Fixes the issue with --source-root option not working when the source files are in a subdirectory of the source root (e.g. when using a /src layout).
Closes #10026

Bump pylint to 3.3.2, update changelog

---

doc/whatsnew/fragments/10100.false_positive
pylint/checkers/refactoring/implicit_booleaness_checker.py
tests/functional/u/use/use_implicit_booleaness_not_len.py
tests/functional/u/use/use_implicit_booleaness_not_len.txt

(bugfix) Issue 10100: [C1802] should not be emitted for generators.

---

.pre-commit-config.yaml
requirements_test.txt

[mypy] Use type-setuptools instead of types-pkg-resources

---

doc/whatsnew/fragments/9335.false_positive
pylint/checkers/variables.py
tests/functional/g/generic_class_syntax_py312.py
tests/functional/g/generic_class_syntax_py312.txt
tests/functional/u/undefined/undefined_variable_py312.py

Fix `undefined-variable` for Python 3.12 generic type syntax

---

doc/whatsnew/fragments/10112.bugfix
pyproject.toml
requirements_test_min.txt
tests/functional/n/no/no_member_imports.py
tests/functional/n/no/no_member_imports.rc

(cherry picked from commit 31e7674ad44c9cbd3120e7e42497bf8af911df79)

[Backport maintenance/3.3.x] Bump astroid from 3.3.5 to 3.3.8 (#10125)

---

doc/whatsnew/3/3.3/index.rst
doc/whatsnew/fragments/10100.false_positive
doc/whatsnew/fragments/10112.bugfix
doc/whatsnew/fragments/9335.false_positive
pylint/__pkginfo__.py
tbump.toml
towncrier.toml

What's new in Pylint 3.3.3?
Release date: 2024-12-23
- Fix false positives for ``undefined-variable`` for classes using Python 3.12
generic type syntax.
Closes #9335
- Fix a false positive for `use-implicit-booleaness-not-len`. No lint should be emitted for
generators (`len` is not defined for generators).
Refs #10100
- Fix ``Unable to import 'collections.abc' (import-error)`` on Python 3.13.1.
Closes #10112

Bump pylint to 3.3.3, update changelog

---

doc/data/messages/r/redefined-builtin/details.rst
tests/functional/r/redefined/redefined_builtin_allowed.py
tests/functional/r/redefined/redefined_builtin_allowed.rc
tests/functional/r/redefined/redefined_builtin_allowed.txt

Closes https://github.com/pylint-dev/pylint/issues/10160
The `redefined-builtin` check has an option - `allowed-redefined-builtins` that allows users to specify names that are allowed to shadow built-ins. However, there are exceptions where this option does not apply, which might lead to confusion. Users may reasonably expect the option to be effective in all cases.
The option is not effective when:
- the shadowing occurs at module level
- the shadowing occurs at local scope, but the `global` keyword is applied to the name
The justification for these exceptions was discussed in #3643. Therefore, …

Extend documentation for `redefined-builtin`

---

doc/whatsnew/fragments/10073.bugfix
pylint/lint/expand_modules.py
pylint/lint/pylinter.py
pylint/typing.py
pylint/utils/linterstats.py
tests/lint/unittest_expand_modules.py
tests/test_self.py

Closes https://github.com/pylint-dev/pylint/issues/10073. This bug has existed ever since the logic was introduced in https://github.com/pylint-dev/pylint/pull/9122. [This](https://github.com/pylint-dev/pylint/issues/8935) was 
the initial issue that inspired that PR, so we can see that the "skipped" count should obviously
have nothing to do with modules without docstrings.
Also enables more reports/output about skipped files in the future, which has been asked for.
I haven't implemented that since it would probably be a larger discussion as to how verbose 
`--verbose` should be.
Fleshed out the test that was written when this was introduced that didn't actually test anything.
Ran this with …

fix "skipped files" count calculation

---

doc/data/messages/u/unused-import/details.rst
doc/data/messages/u/unused-import/related.rst

- Explained why __init__.py files may have unused imports by design.
- Linked to the config option that overrides this behavior
Closes #10162

Mention that unused-import skips __init__.py files

---

doc/whatsnew/fragments/10203.bugfix
pyproject.toml

It's arguable it's not a bug fix, but I don't want to have to release pylint 4.0 for this (it's definitely not ready). 
Closes #10203

[isort] Permit to use isort 6

---

.pre-commit-config.yaml
CONTRIBUTORS.txt
doc/whatsnew/3/3.3/index.rst
doc/whatsnew/fragments/10073.bugfix
doc/whatsnew/fragments/10103.bugfix
doc/whatsnew/fragments/10203.bugfix
examples/pylintrc
examples/pyproject.toml
pylint/__pkginfo__.py
pyproject.toml
tbump.toml
towncrier.toml

- Fixes "skipped files" count calculation; the previous method was displaying an arbitrary number.
Closes #10073
- Fixes a crash that occurred when pylint was run in a container on a host with cgroupsv2 and restrictions on CPU usage.
Closes #10103 
- Relaxed the requirements for isort so pylint can benefit from isort 6.
Closes #10203

Release branch 3.3.4

---

doc/whatsnew/fragments/10208.false_positive
pylint/checkers/classes/special_methods_checker.py
tests/functional/i/invalid/invalid_getnewargs/invalid_getnewargs_ex_returned.py
tests/functional/i/invalid/invalid_getnewargs/invalid_getnewargs_ex_returned.txt

Fix a false positive for ``invalid-getnewargs-ex-returned`` when the tuple or dict has been assigned to a name.
Closes #10208

Fix a false positive for ``invalid-getnewargs-ex-returned``

---

doc/whatsnew/fragments/10211.false_positive
doc/whatsnew/fragments/10213.false_positive
pylint/checkers/imports.py

Upstream undeprecated it in December (https://github.com/python/cpython/pull/126227)
Closes #10211

Undeprecate getopt

---

doc/whatsnew/fragments/10211.false_positive
pylint/checkers/imports.py
tests/functional/d/deprecated/deprecated_module_py3.py
tests/functional/d/deprecated/deprecated_module_py3.txt
tests/functional/d/deprecated/deprecated_module_py36.py
tests/functional/d/deprecated/deprecated_module_py36.txt
tests/functional/d/deprecated/deprecated_relative_import/dot_relative_import.py
tests/functional/d/deprecated/deprecated_relative_import/dot_relative_import.txt
tests/functional/d/deprecated/deprecated_relative_import/subpackage/dot_dot_relative_import.py
tests/functional/d/deprecated/deprecated_relative_import/subpackage/dot_dot_relative_import.txt
tests/functional/n/no/no_member_imports.py
tests/functional/n/no/no_member_imports.txt

Upstream also undeprecated it in December (python/cpython#126227). Feels a bit weird, and sorry for not noticing this earlier. Hopefully I got the news fragment thing right. I wonder if we should mention that these modules were undeprecated?
Refs #10211

Also undeprecate optparse

---

.pre-commit-config.yaml
examples/pyproject.toml
pyproject.toml

This also make the examples easier to read.

Add pyproject.fmt to the pre-commit tooling

---

doc/whatsnew/fragments/10106.bugfix
pylint/checkers/exceptions.py
tests/functional/i/invalid/invalid_exceptions/invalid_exceptions_caught.py
tests/functional/i/invalid/invalid_exceptions/invalid_exceptions_caught.txt

Fix crash in `catching-non-exception` when something besides a class in `except`

---

pylint/lint/expand_modules.py
pylint/testutils/lint_module_test.py
pyproject.toml
requirements_test_min.txt
tests/checkers/unittest_variables.py
tests/functional/i/invalid/invalid_all/invalid_all_format_list_confusion.py
tests/functional/i/invalid/invalid_all/invalid_all_format_list_confusion.txt
tests/functional/i/invalid/invalid_all/invalid_all_format_tuple_confusion.py
tests/functional/i/invalid/invalid_all/invalid_all_format_tuple_confusion.txt
tests/functional/i/invalid/invalid_all/invalid_all_format_valid_3.py
tests/functional/i/invalid/invalid_all/invalid_all_format_valid_4.py
tests/lint/unittest_expand_modules.py

I've added some tests that test regressions in the tests.
I've also made the message to include the number of times a certain
message is missing or extra. Without it, I had a very confusing
experience, when I seemed to have the message and yet the
test-suite reported that I don't. Turned out, I had to add four
more of the same!
I'd be surprised if it passes the tests right now. This will need a new version of astroid to pass, specifically, https://github.com/pylint-dev/astroid/pull/2602

fix several tests related to constants

---

doc/whatsnew/fragments/10081.bugfix
pylint/checkers/variables.py
tests/functional/u/used/used_before_assignment.py

(cherry picked from commit 7b28cf474796ecfb875c3c812e30865222623e41)

[Backport maintenance/3.3.x] Fixed conditional import x.y causing possibly-used-before-assignment (#10240)

---

doc/whatsnew/fragments/10065.false_positive
pylint/checkers/refactoring/implicit_booleaness_checker.py
tests/functional/u/use/use_implicit_booleaness_not_comparison.py
tests/functional/u/use/use_implicit_booleaness_not_comparison.txt
tests/functional/u/use/use_implicit_booleaness_not_comparison_to_string.py
tests/functional/u/use/use_implicit_booleaness_not_comparison_to_zero.py

Currently, the `use-implicit-booleaness-not-comparison` check is applied to expressions with chained comparison. The emitted message and suggested code correction seem inaccurate, and I can't seem to find existing functional tests indicating that this behavior is intended. Therefore, these changes will skip the check when chained comparison nodes are visited.
Take for example:
```
foo, bar = [1], []
assert foo != bar == []  # "foo == []" can be simplified to "not foo", if it is strictly a sequence, as an empty list is falsey
```
`foo != bar == []` is equivalent to `foo != bar and bar == []`, which …

Fix false positives for `use-implicit-booleaness-not-comparison` checks

---

.github/workflows/checks.yaml

Fix the caching following upgrade of the github action

---

.github/workflows/release.yml
doc/whatsnew/fragments/10256.other

Update release workflow to use Trusted Publishing

---

doc/whatsnew/3/3.3/index.rst
doc/whatsnew/fragments/10065.false_positive
doc/whatsnew/fragments/10081.bugfix
doc/whatsnew/fragments/10106.bugfix
doc/whatsnew/fragments/10189.bugfix
doc/whatsnew/fragments/10208.false_positive
doc/whatsnew/fragments/10211.false_positive
doc/whatsnew/fragments/10256.other
pylint/__pkginfo__.py
tbump.toml

What's new in Pylint 3.3.5?
Release date: 2025-03-09
- Fix false positives for `use-implicit-booleaness-not-comparison`, `use-implicit-booleaness-not-comparison-to-string`
and `use-implicit-booleaness-not-comparison-to-zero` when chained comparisons are checked.
Closes #10065 
- Fix a false positive for ``invalid-getnewargs-ex-returned`` when the tuple or dict has been assigned to a name.
Closes #10208 
- Remove `getopt` and `optparse` from the list of deprecated modules.
Closes #10211 
- Fixed conditional import x.y causing false positive possibly-used-before-assignment.
Closes #10081 
- Fix a crash when something besides a class is found in an except handler.
Closes #10106 
- Fixed …

Bump pylint to 3.3.5, update changelog

---

.github/workflows/release.yml

Minor improvements to release workflow

---

.github/workflows/backport.yml

Backporting the release workflow improvements failed. E.g. #10267
```
/usr/bin/git push --set-upstream origin backport-10267-to-maintenance/3.3.x
To https://github.com/pylint-dev/pylint.git
! [remote rejected]     backport-10267-to-maintenance/3.3.x -> backport-10267-to-maintenance/3.3.x (refusing to allow a GitHub App to create or update workflow `.github/workflows/release.yml` without `workflows` permission)
error: failed to push some refs to 'https://github.com/pylint-dev/pylint.git'
```
https://github.com/pylint-dev/pylint/actions/runs/13748264125/job/38445990683#step:2:32
Judging by the error message, the action needs additional permissions to update workflow files.

Add additional permissions for backport workflow

---

doc/user_guide/configuration/all-options.rst
doc/user_guide/usage/output.rst
pylint/lint/base_options.py

Ref #10260 -- Add documentation for the github output format

---

doc/whatsnew/fragments/9391.false_positive
pylint/checkers/variables.py
tests/functional/u/used/used_before_assignment_typing.py

[used-before-assignment] Fix FP for inner function return type

---

.pre-commit-config.yaml
pyproject.toml
setup.cfg

When using the latest packaging==24.2, this no longer installs due to https://github.com/pypa/setuptools/pull/4837
and I get the expected error:
```
setuptools.errors.InvalidConfigError: 'project.license-files' is defined already. Remove 'tool.setuptools.license-files'.
```
Refs #XXXX
Closes #10290
Refs #10292

Move deprecated 'tool.setuptools.license-files', remove license classifier

---

.github/workflows/changelog.yml
.github/workflows/checks.yaml
.github/workflows/primer-test.yaml
.github/workflows/primer_run_main.yaml
.github/workflows/primer_run_pr.yaml
.github/workflows/tests.yaml

`pip install --help` shows six different `--u*` options so when writing commands that others will read, explicitly use the self-documenting `--upgrade` instead of `-U`.
* --user
* --upgrade
* --upgrade-strategy <upgrade_strategy>
* --use-pep517
* --use-feature <feature>
* --use-deprecated <feature>

GitHub Actions: Make pip commands more self-documenting

---

.pre-commit-config.yaml
examples/pyproject.toml
pyproject.toml
requirements_test.txt
setup.cfg

Backport Move deprecated 'tool.setuptools.license-files', remove license class

---

.github/workflows/tests.yaml

Use `matrix.os` and `matrix.include` to consolidate the GitHub Actions jobs `tests-linux`, `tests-macos`, and `tests-pypy` into a single `tests` job.
Removes 80+ lines of duplicate configuration.
Refs #10288
Closes #XXXX

GitHub Actions: Simplify tests using matrix.os

---

doc/whatsnew/fragments/10282.bugfix
pylint/checkers/refactoring/recommendation_checker.py
tests/functional/c/consider/consider_using_f_string.py

This PR addresses a crash in the `consider-using-f-string` check that occurs when `.format` is used with keyword arguments and the format string is malformed. The `utils.parse_format_method_string` raises an uncaught `IncompleteFormatString` exception, leading to the unexpected crash.
Another observation is `consider-using-f-string` is raised when `.format` is used with positional arguments:
```
print("{".format(1))  # [consider-using-f-string], [bad-format-string]
```
In such cases, it seems more appropriate to suppress `consider-using-f-string`, since the `bad-format-string` message already …

Fix crash caused by invalid format strings in `.format` context

---

doc/tutorial.rst

added black's github link in tutorial

---

.readthedocs.yaml
doc/readthedoc_requirements.txt
doc/requirements.txt

If a package is installed twice it makes pip fail now

[ci] Remove the ediatable install from the doc requirements

---

doc/whatsnew/fragments/10277.other
pylint/checkers/typecheck.py
tests/checkers/unittest_typecheck.py

Previously, edit distances were calculated for strings that had length differences greater than the maximum suggestion threshold.
Related PR:
- https://github.com/pylint-dev/pylint/pull/9962
I profiled yt-dlp (commit bd0a6681) with the following `.pylintrc` file:
```
[MAIN]
jobs=1
[MESSAGES CONTROL]
disable=all
enable=no-member
[REPORTS]
reports=no
score=no
```
| Command | Mean [s] | Min [s] | Max [s] | Relative |
|:---|---:|---:|---:|---:|
| `pylint --recursive=y .` | 39.161 ± 0.175 | 38.929 | 39.548 | 1.00 |
```
ncalls  tottime  percall  cumtime  percall filename:lineno(function)
103292    3.706    0.000    5.653    0.000 pylint/checkers/typecheck.py:153(_string_distance)
19623350    1.938 …
```

Speed up the generation of no-member suggestions

---

examples/pylintrc
examples/pyproject.toml
pylint/checkers/typecheck.py
pylintrc

The `missing-member-hint-distance` value is the upper limit rather than the lower limit:
https://github.com/pylint-dev/pylint/blob/9a6168d3041b1f155b4021fdfe79f1729d9f8ee6/pylint/checkers/typecheck.py#L203-L204

Fix typo in missing-member-hint-distance documentation

---

doc/development_guide/contributor_guide/oss_fuzz.rst

uv seems easier to use than pyenv for temporary virtual environments with older Python versions.

Update OSS-Fuzz docs to use uv instead of pyenv

---

tests/functional/r/regression_02/regression_dynamic_getitiem.py
tests/functional/r/regression_02/regression_dynamic_getitiem.txt
tests/functional/r/regression_02/regression_lambda_inference_not_callable.py
tests/functional/r/regression_02/regression_lambda_inference_not_callable.txt

Add regression tests for inference bug repros

---

.github/FUNDING.yml
.pre-commit-config.yaml

@Pierre-Sassoulas I was wondering why me and @yushao2 do not show up on the homepage of the repository.
I think this is because you can't actually have these be multi-line.
See:
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository
In fact, I think for this to work we actually need to prune this list to 4 contributors 😅 
Should we do so? Or should we just remove this list as it is broken and only rely on tidelift?

Fix `FUNDING.yml`

---

doc/data/messages/e/exec-used/bad.py
doc/data/messages/e/exec-used/details.rst
doc/data/messages/e/exec-used/good.py
doc/data/messages/e/exec-used/related.rst

I wanted to make the example's formatting better in details, ended up trying to reproduce it, but it seems the ``allow_globals`` parameters is smarter than we thought when originally documenting it. I get this error when uncommenting `` # allowed_globals``:
```
File "/home/pierre/pylint/a.py", line 4, in <module>
exec(
File "<string>", line 2, in <module>
SystemError: ../Objects/dictobject.c:1490: bad argument to internal function
```
```python
import textwrap
allowed_globals = {"__builtins__": None}
exec(
textwrap.dedent("""
import textwrap
with open("nefarious.py", "w") as f:
f.write(textwrap.dedent('''
def connive():
print("Here's some code as nefarious …
```

[doc] exec-used, add a full example writing in an intermediary file

---

doc/whatsnew/fragments/9353.feature
pylint/checkers/refactoring/implicit_booleaness_checker.py
tests/functional/u/use/use_implicit_booleaness_not_comparison.py
tests/functional/u/use/use_implicit_booleaness_not_comparison.txt
tests/functional/u/use/use_implicit_booleaness_not_comparison_to_string.py
tests/functional/u/use/use_implicit_booleaness_not_comparison_to_string.txt
tests/functional/u/use/use_implicit_booleaness_not_comparison_to_zero.py
tests/functional/u/use/use_implicit_booleaness_not_comparison_to_zero.txt

The `use-implicit-booleaness-not-comparison` check currently suggests replacing comparisons like `x != []` with `x` in all cases. However, this is incorrect when the comparison is not used in a boolean context, such as when it is assigned to a variable, passed as a function argument, used as a return value, etc.
To improve the accuracy of this suggestion, this PR extends the check to detect whether a comparison is used in a boolean context. If so, the expression can safely be refactored to `x`. Otherwise, it is now suggested to use an explicit boolean cast: `bool(x)`. This ensures that the …

Improve code suggestion for `use-implicit-booleaness-not-x` checks

---

.github/workflows/checks.yaml
pyproject.toml

Follow up to #10288. Introducing dependency groups in` pyproject.toml` and cleaning up the file a little bit. Once pip fully supports PEP735, we should update the documentation and remove all the `requirement.txt` files.
With this change you are able to install dependencies like this:
```bash
uv pip install -e . --group docs # installs docs requirements
uv pip install -e .[spelling] --group docs --group dev # installs pre-commit and docs requirements + spelling extras
```
One thing I am currently unsure is how the dependencies in `.readthedocs.yaml` would be handled, when the requirement files in the doc folder are removed?

Add dependency groups to pyproject.toml file

---

pyproject.toml

Reverts pylint-dev/pylint#10332

Revert "Add dependency groups to pyproject.toml file"

---

doc/whatsnew/fragments/10105.bugfix
pylint/checkers/variables.py
tests/functional/r/regression_02/regression_10105.py

[fix] Fix a crash for class decorators mistaken for class attributes

---

doc/whatsnew/3/3.3/index.rst
doc/whatsnew/fragments/10105.bugfix
doc/whatsnew/fragments/10161.false_positive
doc/whatsnew/fragments/10277.other
doc/whatsnew/fragments/10282.bugfix
doc/whatsnew/fragments/10334.bugfix
examples/pylintrc
examples/pyproject.toml
pylint/__pkginfo__.py
tbump.toml
towncrier.toml

What's new in Pylint 3.3.7?
Release date: 2025-05-04
- Comparisons between two calls to `type()` won't raise an ``unidiomatic-typecheck`` warning anymore, consistent with the behavior applied only for ``==`` previously.
Closes #10161
- Fixed a crash when importing a class decorator that did not exist with the same name than a class attribute after the class definition.
Closes #10105
- Fix a crash caused by malformed format strings when using `.format` with keyword arguments.
Closes #10282 
- Using a slice as a class decorator now raise a 'not-callable' message instead of crashing pylint. A lot of checks that dealt with decorators (too many to list) are now shortcut if the decorator …

Bump pylint to 3.3.7, update changelog

---

.pre-commit-config.yaml
requirements_test.txt

AFAICT `types-setuptools` isn't needed anymore. In the past it was used for `pkg_resources` (see #10119), however since then the module includes a `py.typed` file. Furthermore, I couldn't find any active uses for `pkg_resources` in our codebase.

Remove types-setuptools test dependency

---

pylint/checkers/base/name_checker/checker.py
pylint/extensions/typing.py
tests/functional/g/generic_alias/generic_alias_collections.py
tests/functional/g/generic_alias/generic_alias_collections.txt
tests/functional/g/generic_alias/generic_alias_typing.py
tests/functional/g/generic_alias/generic_alias_typing.txt

Start fixing some Python 3.14 errors. Tested against 3.14.0b1 locally. Mainly
- Adjust checkers to handle the "new" Union inference result. I.e. it's now a `ClassDef` instead of a `FunctionDef` and the builtins type is `Union` instead of `UnionType`.
- Remove `typing.ByteString` and `collections.abc.ByteString` as these have been removed in `3.14`. It's probably not worth it to add separate test cases just for them.
- Also remove `typing.re.Pattern` and `typing.re.Match` which have been removed back in `3.13`. pylint doesn't emit `no-member` warnings for these since the typing module has a `__getattr__` function.

Initial fixes for Python 3.14

---

pylint/graph.py
tests/pyreverse/test_writer.py

`codecs.open` has been superseded by `open` and will raise a DeprecationWarning in Python 3.14.
https://docs.python.org/3.14/library/codecs.html#codecs.open

Replace codecs.open with open

---

pylint/constants.py
tests/config/pylint_config/test_pylint_config_help.py

The output for `pylint-config generate -h` changed for 3.14. Adjust the test case accordingly.
**Python 3.13**
```
usage: pylint-config [options] generate [-h] [--interactive]
options:
-h, --help     show this help message and exit
--interactive
```
**Python 3.14**
```
usage: pylint-config generate [-h] [--interactive]
options:
-h, --help     show this help message and exit
--interactive
```

Fix pylint-config help output test for Python 3.14

---

.github/workflows/checks.yaml
.github/workflows/primer-test.yaml
.github/workflows/primer_run_main.yaml
.github/workflows/primer_run_pr.yaml
.github/workflows/tests.yaml

Fix failing spelling tests: https://github.com/pylint-dev/pylint/actions/runs/15076143743/job/42383895655
Prevent using an old cached version of `pylint` for tests by reinstalling it from source before every pytest run in CI.
Furthermore adding `--no-deps` since we only care about `pylint` itself. For everything else, like an updated dependency, the cache is invalidated anyway.

[ci] Install pylint before every test

---

.github/workflows/backport.yml

Followup to #10269
Noticed recently with #10388 that the backport to `.github/workflows` files still fails with the same error. After investigation and testing on my fork I found a solution that would work. For the backport to work we need the `workflows` permission. However that one isn't available for CI workflows. Instead we'd need to create a personal access token with the following permissions:
- `contents: write` -> push new branches to Github
- `pull-requests: write` -> create PR or add comment for manual backport
- `workflows: write` -> modify files in .github/workflows
_The `actions: write` permission I added in #10388 isn't necessary after all._
A side effect would be that we won't need to close / reopen PRs anymore before the workflow would run. By scoping the secret to an …

Improve backport job permissions

---

.github/workflows/backport.yml

Backport 222ab2005b4cd2cbd0c5ed245d2fe5d66c878f55 from #10390.

[Backport maintenance/3.3.x] Improve backport job permissions

---

doc/whatsnew/fragments/9668.false_positive
pylint/checkers/variables.py
tests/functional/u/used/used_before_assignment_py310.py
tests/functional/u/used/used_before_assignment_py310.txt

(cherry picked from commit ad14b5bf9f2eaaf9b69a0daef09d1d944e1b11cf)

[Backport maintenance/3.3.x] Resolve possibly-used-before-assignment false positives from `match` block assignments (#10393)

---

.github/workflows/tests.yaml

The `tests` job uses the `python-version` output from `actions/setup-python` as part of the cache key. That works well for cpython, however is broken for PyPy which doesn't include the Python version itself. Thus the workflow currently restores the first cached venv, e.g. `pypy-3.11` on `pypy-3.10`, and thus no packages are actually available.
The current key prefix for PyPy (3.10 and 3.11): `Linux-pypy7.3.19-venv-...`. Better would be `Linux-pypy3.10.16-7.3.19-venv-...` / `Linux-pypy3.11.11-7.3.19-venv-...`.
_This isn't an issue on our backport branch since PyPy 3.9 was dropped recently and so the PyPy versions are actually different. Nevertheless it might be good to backport it as well._
IMO this is really an issue with the `setup-python` action. Opened an issue and PR upstream. …

[ci] Fix PyPy venv caching issue

---

.github/workflows/backport.yml

Followup to #10390
For organizations it's recommended to use custom Github Apps over PAT from bot accounts.
Created https://github.com/apps/pylint-backport-bot for it.
https://github.com/actions/create-github-app-token

Use custom Github App to authenticate backport job

---

.github/workflows/checks.yaml
.github/workflows/primer-test.yaml
.github/workflows/tests.yaml

I don't see any downside of doing this. We're never checking the benchmark result either, but we need to add a comment like the primer if we really want to use the result from the benchmark job. (I don't know why the default is not 'no benchmark' each pytest call is taking longer because of this locally).

[ci] Disable the benchmarks everywhere except the benchmark job

---

doc/development_guide/how_tos/custom_checkers.rst

Move information from
https://github.com/pylint-dev/pylint/blob/13743cdd035765292d5f5f58274a21fb9aaafcf3/pylint/checkers/__init__.py#L5-L41
to
https://github.com/pylint-dev/pylint/blob/13743cdd035765292d5f5f58274a21fb9aaafcf3/doc/development_guide/how_tos/custom_checkers.rst?plain=1#L267-L273
as described [here](https://github.com/pylint-dev/pylint/issues/10341#issuecomment-2798947513).
Closes #10341.

[doc]Update custom_checkers.rst to specify the safe range that a custom checker may use

---

doc/whatsnew/fragments/10104.false_positive
pylint/extensions/docparams.py
tests/functional/ext/docparams/raise/missing_raises_doc_required_min_length.py
tests/functional/ext/docparams/raise/missing_raises_doc_required_min_length.rc
tests/functional/ext/docparams/yield/missing_yield_doc_required_min_length.py
tests/functional/ext/docparams/yield/missing_yield_doc_required_min_length.rc

Even though visit_functiondef is checking for docstring-min-length, it is not enough. This commit fixes the issue by adding the same check to visit_raise and visit_yield
If there is a better way of implementing this, please go forward. I am just providing a working fix to this problem.
Refs #XXXX
Closes #XXXX

Respect docstring-min-length in docparams extension

---

CONTRIBUTORS.txt
doc/whatsnew/fragments/10453.false_negative
pylint/checkers/deprecated.py
script/.contributors_aliases.json
tests/functional/d/deprecated/deprecated_module__import__.py
tests/functional/d/deprecated/deprecated_module__import__.rc
tests/functional/d/deprecated/deprecated_module__import__.txt

Using the following python code style
```python
__import__("deprecated_module")
```
The deprecated-module is ignored since that it expects
```python
import deprecated_module
```
This change adds the posibility to process these kind of style too
This style is used from popular auto-code snippets:
- https://github.com/honza/vim-snippets/blob/f0a3184/snippets/python.snippets#L209
|   X | :sparkles: New feature |
|  X  | :hammer: Refactoring   |
| X   | :scroll: Docs          |
Closes #10453

Fix false negative for `deprecated-module` when a `__import__` method is used instead of `import` sentence

---

doc/whatsnew/fragments/10149.feature
pylint/checkers/typecheck.py
pylint/checkers/variables.py
pylint/extensions/typing.py
tests/functional/p/postponed/postponed_evaluation_not_activated.py
tests/functional/u/undefined/undefined_variable.314.txt
tests/functional/u/undefined/undefined_variable.py
tests/functional/u/undefined/undefined_variable_py30.314.txt
tests/functional/u/undefined/undefined_variable_py30.py
tests/functional/u/used/used_before_assignment_nonlocal.314.txt
tests/functional/u/used/used_before_assignment_nonlocal.py
tests/functional/u/used/used_before_assignment_typing.314.txt
tests/functional/u/used/used_before_assignment_typing.py

Handle deferred evaluation of annotations in Python 3.14

---

doc/whatsnew/fragments/10426.false_positive
pylint/checkers/variables.py
tests/functional/u/unused/unused_global_variable2.py
tests/functional/u/unused/unused_variable.py
tests/functional/u/unused/unused_variable.txt

Somewhat related to #4791. When investigating the issue, I noticed that the false positive is only emitted when checking for global unused variables. It is fine when the try block is nested within a function like:
```
def foo():
try:
pass
except TypeError as exc:
print(exc)
except ValueError as exc:
print(exc)
```
There seems to be existing logic handling this as a special case, so I extracted it into a function and reused it for the global unused variable check.
Closes #10426

Fix `unused-variable` false positive when using same name for multiple exceptions 

---

doc/whatsnew/fragments/10482.false_negative
pylint/checkers/variables.py

`used-before-assignment` errors should still be emitted for function arg defaults even with postponed evaluation of type annotations enabled.
```py
from __future__ import annotations
def func(var = A):  # should emit 'used-before-assignment'
...
class A: ...
```
Didn't add a test case for it since the test suite already includes examples for it. These will be tested with Python 3.14 where the deferred evaluation of type annotations will be the default.
https://github.com/pylint-dev/pylint/blob/9e72867c1ac46cb0a2f88abf6f596530c2fa1708/tests/functional/u/undefined/undefined_variable.py#L91-L96
https://github.com/pylint-dev/pylint/blob/9e72867c1ac46cb0a2f88abf6f596530c2fa1708/tests/functional/u/undefined/undefined_variable.py#L142-L147
--
This does address some of the issues in #10467. In …

Fix false-negative for used-before-assignment with postponed evaluation in function defs

---

doc/whatsnew/3/3.3/index.rst
doc/whatsnew/fragments/10104.false_positive
doc/whatsnew/fragments/10373.bugfix
doc/whatsnew/fragments/10402.bugfix
doc/whatsnew/fragments/10426.false_positive
doc/whatsnew/fragments/10482.false_negative
doc/whatsnew/fragments/9668.false_positive
pylint/__pkginfo__.py
script/.contributors_aliases.json
tbump.toml
towncrier.toml

What's new in Pylint 3.3.8?
Release date: 2025-08-09
This patch release includes an exceptional fix for a false negative issue. For details, see: https://github.com/pylint-dev/pylint/pull/10482#issuecomment-3164514082
- Fix false positives for `possibly-used-before-assignment` when variables are exhaustively
assigned within a `match` block.
Closes #9668 
- Fix false positive for `missing-raises-doc` and `missing-yield-doc` when the method length is less than docstring-min-length.
Refs #10104 
- Fix a false positive for ``unused-variable`` when multiple except handlers bind the same name under a try block.
Closes #10426 
False Negatives Fixed
- Fix false-negative for ``used-before-assignment`` …

Bump pylint to 3.3.8, update changelog

---

doc/whatsnew/fragments/9815.false_positive
pylint/checkers/utils.py
pylint/checkers/variables.py
pylint/testutils/functional/find_functional_tests.py
tests/functional/u/used/used_before_assignment_py312.py
tests/functional/u/used/used_before_assignment_py312.txt
tests/functional/u/used_02/used_before_assignment_py313.py
tests/functional/u/used_02/used_before_assignment_py313.rc
tests/functional/u/used_02/used_before_assignment_py313.txt

Fix used-before-assignment for PEP 695 type aliases + parameters

---

doc/whatsnew/fragments/9815.false_positive
pylint/checkers/utils.py
pylint/checkers/variables.py
pylint/testutils/functional/find_functional_tests.py
tests/functional/u/used/used_before_assignment_py312.py
tests/functional/u/used/used_before_assignment_py312.txt
tests/functional/u/used_02/used_before_assignment_py313.py
tests/functional/u/used_02/used_before_assignment_py313.rc
tests/functional/u/used_02/used_before_assignment_py313.txt

Backport https://github.com/pylint-dev/pylint/commit/bbfcb381342c10693bfb8cb38b28e1f91998ea00 from https://github.com/pylint-dev/pylint/pull/10488.

[Backport maintenance/3.3.x] Fix used-before-assignment for PEP 695 type aliases + parameters

---

.github/workflows/tests.yaml

Followup to https://github.com/pylint-dev/pylint/pull/10392
The upstream PR https://github.com/actions/setup-python/pull/1110 was merged a few weeks ago. Unfortunately there hasn't been a new release in some time now. Guess we could switch back to a sha version for now. Hopefully dependabot will update it as well, otherwise we'll need to remember to do so.

Switch back to upstream setup-python with PyPy fix [ci]

---

.pre-commit-config.yaml
tests/test_check_parallel.py

The `rstcheck` pre-commit job requires pydantic which fails on Python 3.14 currently. The first compatible version will be `3.12.0`(not released yet). Make sure we can install the alpha release for 3.14.
Also update an import to fix pylint on 3.14.

Fix pre-commit checks on Python 3.14

---

doc/whatsnew/fragments/10510.bugfix
pylint/checkers/refactoring/refactoring_checker.py
tests/functional/u/unnecessary/unnecessary_list_index_lookup.py

Better approach in 'unnecessary-list-index-lookup' to avoid crashes

---

pyproject.toml

Followup to #10523
The dependency versions changed since the initial PR was committed. Make sure versions in `pyproject.toml` match those in the requirement files.

Sync requirements

---

.pre-commit-config.yaml
tests/test_self.py

Mypy itself has a rather slow release cadences. A while ago I created [mypy-dev](https://github.com/cdce8p/mypy-dev). A repository setup to create development releases of mypy available on PyPI. Initially it was only really intended for use during the Home Assistant development. Today, I also setup a pre-commit mirror at [mypy-dev-pre-commit](https://github.com/cdce8p/mypy-dev-pre-commit) so we could also use it here in pylint.
It wouldn't be worth it here usually, but I recently fixed a few mypy issues with the match statement which would be useful here. Once the next version is released, we could switch back again.
- https://github.com/python/mypy/pull/19708
- https://github.com/python/mypy/pull/19709
- https://github.com/python/mypy/pull/19742
> [!NOTE]
> Due to the increased release …

Switch to mypy-dev 1.18.0a6

---

.github/workflows/primer_comment.yaml
tests/testutils/_primer/fixtures/new_message/expected.txt
tests/testutils/_primer/fixtures/new_message/main.json
tests/testutils/_primer/fixtures/new_message/pr.json
tests/testutils/_primer/fixtures/removed_message/expected.txt
tests/testutils/_primer/fixtures/removed_message/main.json
tests/testutils/_primer/fixtures/removed_message/pr.json
tests/testutils/_primer/test_primer.py

Added some test cases with similar looking messages mimicking what we actually have when we upgrade messages later on.

[primer]  Mimick what we actually have when we upgrade messages in test cases

---

pylint/checkers/async_checker.py
pylint/checkers/exceptions.py
pylint/checkers/format.py
pylint/checkers/imports.py
pylint/checkers/lambda_expressions.py
pylint/checkers/logging.py
pylint/checkers/modified_iterating_checker.py
pylint/checkers/non_ascii_names.py
pylint/checkers/stdlib.py
pylint/checkers/strings.py
pylint/checkers/typecheck.py
pylint/checkers/utils.py
pylint/checkers/variables.py
tests/functional/u/unnecessary/unnecessary_lambda_assignment.py
tests/functional/u/unnecessary/unnecessary_lambda_assignment.txt

_To review I'd suggest to use `Hide whitespace`._

Use match statement in checkers (2)

---

doc/whatsnew/fragments/10542.false_negative
pylint/checkers/design_analysis.py
pylint/checkers/format.py
tests/functional/t/too/too_many_branches.py

Followup to https://github.com/pylint-dev/pylint/pull/10528#discussion_r2328337004

Count match cases for too-many-branches

---

pylint/checkers/base/basic_checker.py
pylint/checkers/base/basic_error_checker.py
pylint/checkers/base/docstring_checker.py
pylint/checkers/base/name_checker/checker.py
pylint/checkers/classes/class_checker.py
pylint/checkers/classes/special_methods_checker.py
pylint/checkers/refactoring/implicit_booleaness_checker.py
pylint/checkers/refactoring/refactoring_checker.py

_To review I'd suggest to use `Hide whitespace`._

Use match statement in checkers (3)

---

doc/user_guide/checkers/extensions.rst
doc/user_guide/checkers/features.rst
pylint/checkers/base_checker.py

The message sort order on the `Pylint features` page is quite confusing. I believe it makes sense to sort by message-id here. E.g. https://pylint.readthedocs.io/en/stable/user_guide/checkers/features.html#basic-checker-messages
We do also have the message overview which is sorted alphabetically.
https://pylint.readthedocs.io/en/stable/user_guide/messages/messages_overview.html

[docs] Update the message sort order

---

doc/whatsnew/3/3.3/index.rst

Let's see if it works.
Refs #10563

Add sphinx reference for whatsnew 3.3

---

.github/workflows/tests.yaml

~Also, use `python-version: 3.x` to always test on the latest stable version of Python.~
~Automated testing should tell us if things are broken on the latest stable version of Python before users do.~
~* https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md#using-the-python-version-input~
> ~[x-ranges](https://github.com/npm/node-semver#x-ranges-12x-1x-12-) to specify the latest stable version of Python (for the specified major version):~
Refs #XXXX
Closes #XXXX

[ci] Allow Python prerelease versions

---

.github/workflows/changelog.yml
.github/workflows/checks.yaml
.github/workflows/primer-test.yaml
.github/workflows/primer_run_main.yaml
.github/workflows/primer_run_pr.yaml
.github/workflows/tests.yaml

Github added support for YAML anchors in workflow files. They don't support key-merge / overrides but it's at least a start.
- https://github.blog/changelog/2025-09-18-actions-yaml-anchors-and-non-public-workflow-templates/ 
- https://docs.github.com/en/actions/reference/workflows-and-actions/reusing-workflow-configurations#yaml-anchors-and-aliases
- Good overview over the yaml anchors syntax: https://support.atlassian.com/bitbucket-cloud/docs/yaml-anchors/

Use yaml anchors for workflows

---

tests/functional/ext/mccabe/mccabe.py
tests/functional/ext/mccabe/mccabe.txt
tests/functional/ext/mccabe/not_too_complex.py
tests/functional/ext/mccabe/not_too_complex.rc
tests/functional/ext/mccabe/not_too_complex.txt

[mccabe] Add more functional tests to allow for easier refactor

---

pylint/checkers/async_checker.py
pylint/checkers/base/basic_checker.py
pylint/checkers/base/name_checker/checker.py
pylint/checkers/classes/class_checker.py
pylint/checkers/imports.py
pylint/checkers/nested_min_max.py
pylint/checkers/refactoring/refactoring_checker.py
pylint/checkers/strings.py
pylint/checkers/typecheck.py
pylint/checkers/utils.py
pylint/checkers/variables.py
pylint/extensions/docparams.py
pylint/extensions/typing.py
pylint/lint/pylinter.py
pylint/pyreverse/diagrams.py
pylint/pyreverse/inspector.py

Update additional astroid imports

---

pylint/checkers/symilar.py
pylint/message/message_id_store.py

This PR replaces some of the `.sort()` calls to `sorted(...)`, in places where it _makes sense_, which allows to _save few lines_. It also updates the implementation of `_raise_duplicate_symbol` and `_raise_duplicate_msgid` to make them more uniform.

Use `sorted()` instead of in-place sorting

---

doc/whatsnew/fragments/6052.breaking
pylint/lint/pylinter.py
pylint/lint/run.py

Deprecate PyLinter pylintrc argument
