pylint-dev/pylint

ChangeLog, pylint/checkers/base.py, pylint/test/functional/unneeded_not.py
=> Allow unneeded-not in __ne__

elisp/pylint.el
This is a convenience command to insert a comment like `# pylint: disable=msg1,msg2,...`.  It gathers messages from `pylint --list-msgs`, then runs in a loop inserting messages using completion.  I use it with ido-completion (via ido-ubiquitous); it might be better to use ido-completion by default.
=> Add pylint-insert-ignore-comment to pylint.el

pylint/checkers/base.py
extract and reuse a function checking for astroid.Const or astroid.Name.
=> Don't stringify nodes to check if they are None

pylint/checkers/base.py, pylint/test/functional/unneeded_not.py
=> Don't apply unneeded-not rule on sets

pylint/checkers/base.py, pylint/test/functional/simplifiable_if_statement.txt
=> Improve R0102 error messaging.

CONTRIBUTORS.txt
I add a very little contribution [PR#277](https://bitbucket.org/logilab/pylint/pull-requests/277/fix-362-show-deprecated-module-even-if-the/diff)
But the follow comment motivate me to create this PR:
` * ... Many other people have contributed by their feedback or even patches, if I've forgotten you, send me a note !`
=> [REF] CONTRIBUTORS.txt: Add Moisés López contribution

doc/run.rst, man/pyreverse.1, pylint/pyreverse/main.py
* pylint's run.rst is out of sync with [current help message](https://github.com/PyCQA/pylint/blob/master/pylint/lint.py#L271),
* pyreverse has bad docs for multi-ignore.
=> Update docs for --ignore option

.coveragerc, .gitignore, .travis.yml, README.rst, tox.ini
- Enable github statuses for coveralls
- Enable coverage report in log ouput of travis
=> [ADD] coverage: Enable coveralls and coverage report

README.rst
=> [REF] README: Add pypi badge

pylint/extensions/_check_docs_utils.py, pylint/extensions/check_docs.py, pylint/test/extensions/test_check_return_docs.py
=> check_docs warns for redundant return docstring

pylint/__pkginfo__.py
=> Don't pin mccabe version

pylint/checkers/imports.py, pylint/test/functional/deprecated_module_py4.py, pylint/test/functional/deprecated_module_py4.rc, pylint/test/functional/deprecated_module_py4.txt
- Fix https://github.com/PyCQA/pylint/issues/953
=> [FIX] deprecated-module: Detected with -d all -e deprecated-module

pylint/checkers/imports.py, pylint/test/functional/wrong_import_position15.py
- Fix https://github.com/PyCQA/pylint/issues/965
=> [FIX] wrong-import-position: Support pep-0008#module-level-dunder-names

doc/run.rst
=> add: documentation of exit codes

elisp/pylint.el
- 
add variable pylint-alternate-pylint-command, default pylint2
add prefix arg to pylint command, so that it uses the alternate command
=> add alternate pylint command

pylint/checkers/imports.py
- 
Sort the dependent files so that the order is predictable. Humans can more easily find names in an alphabetically ordered list. Also makes diff happy because the output is always going to be the same unless there is a new dependent file.
=> Sorted output of dependent files

ChangeLog, doc/whatsnew/2.0.rst, pylint/config.py, pylint/test/test_self.py, pylint/utils.py
=> [REF] config: Sort options

doc/development_guide/documentation.rst, doc/development_guide/index.rst
- Now no one else have to go through the problems i had to get the docs built, see issue #1093 for reference
=> Add how to build the docs to the development guide

CONTRIBUTORS.txt
=> Fix a typo in CONTRIBUTORS

pylint/lint.py
=> Fix spelling

pylint/extensions/overlapping_exceptions.py
Replaced for-loop with equivalent
=> Simplified

pylint/checkers/design_analysis.py
Minor fix, more idiomatic check for item count where condition is met.
=> design_analysis: simplify getting count of ignored arguments

pylint/test/extensions/test_overlapping_exceptions.py
- Also removes pytest warning that cannot detect tests in TestReporter.
=> Remove unittest dependancy of test_overlapping_exceptions

pylint/checkers/refactoring.py, pylint/checkers/utils.py, pylint/test/functional/nested_blocks_issue1088.py, pylint/test/functional/nested_blocks_issue1088.txt
Fix too-many-nested-blocks, where last nested block in function was
excluded from analysis.
Closes #1088
=> Fix too-many-nested-blocks

pylint/test/functional/used_before_assignment_issue853.py
=> Issue 853: add tests to show issue does not occur

ChangeLog, doc/whatsnew/2.0.rst, pylint/checkers/logging.py, pylint/test/functional/logging_format_interpolation.py, pylint/test/functional/logging_format_interpolation.txt
=> Fix too agressive logging-format-interpolation

pylint/checkers/variables.py, pylint/test/functional/used_before_assignment_issue1081.py
I am starting to realise why this code is that complicated…
=> Fix not-used-before-assignment false positive

.travis.yml, tox.ini
Hopefully improve coverage by actually running spellchecking-related tests.
=> Add pyenchant to dependencies

pylint/extensions/_check_docs_utils.py, pylint/test/extensions/test_check_docs.py
=> Can detect multiple types in docstring type fields

ChangeLog, doc/whatsnew/2.0.rst, pylint/checkers/format.py, pylint/test/unittest_checker_format.py
=> Add single-line-class-stmt

ChangeLog, pylint/checkers/classes.py, pylint/test/functional/access_to_protected_members.py, pylint/test/functional/access_to_protected_members.txt
=> Do not emit warning on type(self)._private_attribute access

ChangeLog, doc/whatsnew/2.0.rst, pylint/checkers/imports.py, pylint/test/functional/wildcard_import_allowed.py, pylint/test/functional/wildcard_import_allowed.rc, pylint/test/functional/wildcard_import_allowed.txt
=> Add flag to allow wildcard imports if module defines __all__

pylint/test/functional/class_members_py27.py, pylint/test/functional/class_members_py30.py
=> Add tests to confirm named tuple inference in astroid is improved

pylint/checkers/refactoring.py, pylint/test/functional/len_checks.py, pylint/test/functional/len_checks.txt
Closes #1325 and #1331.
I think adding a changelog for fixes in unreleased feature is not really needed, but if @PCManticore disagree, I’ll add relevant entries
=> len-as-cond: fix case where invalid calls wasn't used in .test leaf

pylint/test/unittest_checker_typecheck.py
=> Issue 1295: Fix false positives for typing module

ChangeLog, doc/whatsnew/1.7.rst, doc/whatsnew/2.0.rst, pylint/checkers/imports.py, pylint/test/input/func_w0401_disabled.py, pylint/test/messages/func_w0401_disabled.txt
=> Make cyclic import checker respect local disable clauses

pylint/test/functional/disable_msg_github_issue_1389.py, pylint/test/functional/disable_msg_github_issue_1389.rc
=> Add tests to prove that exception is no raised after astroid fixes

pylint/checkers/typecheck.py, pylint/test/functional/test_compile.py
- Fix crash on checking attributes of Unknown object.
- Closes #1365.
=> Fix crash on checking attributes of Unknown object.

ChangeLog, doc/whatsnew/1.7.rst, pylint/checkers/base.py, pylint/test/unittest_checker_base.py
New checker for assigning to new keyword.
Closes #1351.
=> assign-to-new-keyword

ChangeLog, doc/whatsnew/1.8.rst, pylint/exceptions.py, pylint/lint.py, pylint/test/unittest_lint.py
First attempt at solving #1388.
Any input is appreciated, since I really have no clear idea on what would be a "correct" way to solve it.
=> Raise meaningful exception for invalid reporter class being selected

ChangeLog, pylint/config.py
=> Log config file name to stderr in non-quiet mode

ChangeLog, doc/whatsnew/1.8.rst, pylint/checkers/spelling.py, pylint/test/unittest_checker_spelling.py
I intended to fix broken test, but while I was around this code I removed one TODO comment :)
=> spelling checker: parametrize count of suggestions, fix tests

pylint/checkers/imports.py
=> ImportsChecker: check all messages in leave_module

ChangeLog
A PR (#1337) was merged that introduced a changelog entry in a previous release.
This PR places the entry in the correct (upcoming) release section.
@PCManticore Please Take a Look.
=> Correct the location of a Changelog entry.

pylint/checkers/typecheck.py
=> Fix TypeError in c-extension-no-member msg

ChangeLog, pylint/lint.py, pylint/test/regrtest_data/py3k-disabled.rc, pylint/test/regrtest_data/py3k_errors_and_warnings.py, pylint/test/test_self.py
- Respect disable=... in config file when running with --py3k.
=> Respect disable=... in config with --py3k

pylint/checkers/stdlib.py
This TODO was resolved in: https://github.com/PyCQA/pylint/pull/1733#pullrequestreview-75930778
Resolves: #1301
=> Remove forgotten TODO

ChangeLog, doc/whatsnew/1.8.rst, pylint/checkers/refactoring.py, pylint/test/functional/inconsistent_returns.py, pylint/test/functional/inconsistent_returns.txt
Making a PR just to ensure CI is ok.
=> Backport of PR #1775

ChangeLog, doc/whatsnew/1.8.rst, pylint/checkers/refactoring.py, pylint/test/functional/inconsistent_returns.py, pylint/test/functional/inconsistent_returns.txt
=> Backport of PR #1806

ChangeLog, doc/whatsnew/1.8.rst, pylint/checkers/variables.py, pylint/test/functional/unused_argument.py
=> Backport of PR #1757

ChangeLog, doc/whatsnew/1.8.rst, pylint/checkers/refactoring.py, pylint/test/functional/inconsistent_returns.py, pylint/test/functional/inconsistent_returns.rc, pylint/test/functional/inconsistent_returns.txt
=> Backport of PR #1777

CONTRIBUTORS.txt, ChangeLog, pylint/checkers/utils.py, pylint/test/unittest_checker_exceptions.py
Parallel to #1836 for the 1.8 branch.
=> Fix error on 'raise from function' for 1.8.

CONTRIBUTORS.txt, ChangeLog, pylint/checkers/stdlib.py, pylint/test/functional/bad_thread_instantiation.py, pylint/test/functional/bad_thread_instantiation.txt
=> Fix bad thread instantiation check

pylint/checkers/typecheck.py
Require `no-context-manager`check to infer paths before walking the paths tree.
Fixes #1874
=> Fix no-context-manager test breakage in due to astroid changes

CONTRIBUTORS.txt, ChangeLog, pylint/test/test_import_graph.py, pylint/test/test_regr.py, pylint/test/test_self.py, pylint/test/unittest_lint.py, pylint/utils.py
- Fixes #1120 
Only replace `path_strip_prefix` for the first encountered instance.
=> fix 1120 incorrect file path

ChangeLog, doc/whatsnew/2.0.rst, pylint/checkers/variables.py, pylint/test/unittest_checker_variables.py
=> Fix false positive undefined-variable for lambda arguments in classes

ChangeLog, doc/whatsnew/1.8.rst, pylint/checkers/utils.py, pylint/checkers/variables.py, pylint/test/unittest_checker_variables.py
Fixes generated list comprehension variables in function defaults for python 2.7 
Close #1897
=> Fix comprehension in func defaults

doc/user_guide/run.rst, pylint/epylint.py
=> user-guide: Change pylint call from python example

pylint/exceptions.py, pylint/lint.py, pylint/test/unittest_lint.py
PluginRegistry.register_checker raises custom exception
InvalidCheckerError instead of ValueError as per #1893.
=> Add InvalidCheckerError

CONTRIBUTORS.txt, ChangeLog, doc/whatsnew/2.0.rst, pylint/checkers/refactoring.py, pylint/test/functional/consider_swap_variables.py, pylint/test/functional/consider_swap_variables.txt
I am not yet completely happy with the naming of this check, so if anyone has a better idea, feel free to comment.
=> add swapping variables with tuples check (#1922)

ChangeLog, doc/whatsnew/2.0.rst, pylint/checkers/refactoring.py, pylint/test/functional/consider_join.py, pylint/test/functional/consider_join.txt
=> Add new checker "consider-using-join" (closes #1952)

doc/faq.rst
add some doc for py3k option.
ref: <https://github.com/PyCQA/pylint/issues/1969>
=> add doc for --py3k option.

ChangeLog, doc/whatsnew/2.0.rst, pylint/checkers/variables.py, pylint/test/functional/globals.py, pylint/test/functional/globals.txt, pylint/test/unittest_checker_variables.py
- Check if global is set for import, if so do not error
I added one unit test, please let me know if there are other tests you would like me to add, happy to (and any other changes of course)!
Credit for pointing me to the .txt for the functional tests to @benhgreen
=>  Check if global is set for import, closes #1453

pylint/lint.py, pylint/utils.py
- PluginRegistry handles global message configuration
=> Reduce Mixin usage

CONTRIBUTORS.txt, ChangeLog, doc/whatsnew/2.0.rst, pylint/checkers/typecheck.py, pylint/test/functional/unhashable_dict_key.py, pylint/test/functional/unhashable_dict_key.txt
- Adds `unhashable-dict-keys` check
=> add check for unhashable dict keys (fixes #586)

ChangeLog, doc/whatsnew/2.0.rst, pylint/checkers/variables.py, pylint/test/functional/self_cls_assignment.py, pylint/test/functional/self_cls_assignment.txt
- New warning if the first argument of an instance/ class method gets assigned
=> Warn if the first argument of an instance/ class method gets assigned, closes #977

pylint/checkers/python3.py, pylint/test/unittest_checker_python3.py
=> min() and max() accept iterators

ChangeLog, doc/whatsnew/2.0.rst, pylint/checkers/refactoring.py, pylint/test/functional/consider_using_get.py, pylint/test/functional/consider_using_get.txt
=> Implement "consider-using-get"-checker (close #2076)

pylint/config.py, pylint/epylint.py, pylint/extensions/redefined_variable_type.py, pylint/lint.py, pylint/pyreverse/diadefslib.py, pylint/reporters/__init__.py, pylint/reporters/text.py, pylint/reporters/ureports/__init__.py, pylint/reporters/ureports/nodes.py, pylint/test/test_self.py, pylint/test/unittest_checker_similar.py, pylint/test/unittest_lint.py, pylint/test/unittest_pyreverse_diadefs.py, pylint/test/unittest_reporters_json.py, pylint/test/unittest_reporting.py, pylint/testutils.py, pylint/utils.py
six dependencies will be removed gradually, file by file.
- #1895
=> remove six package usages.

doc/exts/pylint_extensions.py, pylint/__pkginfo__.py, pylint/checkers/python3.py, pylint/checkers/spelling.py, pylint/config.py, pylint/epylint.py, pylint/extensions/redefined_variable_type.py, pylint/lint.py, pylint/pyreverse/diadefslib.py, pylint/reporters/__init__.py, pylint/reporters/text.py, pylint/reporters/ureports/__init__.py, pylint/reporters/ureports/nodes.py, pylint/test/test_self.py, pylint/test/unittest_checker_similar.py, pylint/test/unittest_lint.py, pylint/test/unittest_pyreverse_diadefs.py, pylint/test/unittest_reporters_json.py, pylint/test/unittest_reporting.py, pylint/testutils.py, pylint/utils.py
=> Remove six package from install_requires

ChangeLog, doc/whatsnew/2.0.rst, pylint/test/functional/line_too_long_end_of_module.py, pylint/utils.py
This PR is a variation around PR #2004. The preceding PR had a bug which was a wrong evaluation of the line number of the last line of the module.
Hope this one is ok now.
=> Bug 1950 new

Makefile, doc/conf.py, tox.ini
Closes https://github.com/PyCQA/pylint/issues/2167
=> Use python-docs-theme

man/pylint.1, pylint/lint.py
- Doc improvements related to the jobs option
=> Jobs documentation improvements

doc/Makefile, examples/pylintrc, man/pylint.1, pylint/config.py
- Improvements to man page and example rcfile generation
- Regenerated man page and example rcfile
=> Man page and example rcfile generation improvements

.gitignore, pylint/checkers/strings.py
Update `.gitignore`, cut Python 2 node reference
=> Minor updates

CONTRIBUTORS.txt, ChangeLog, doc/whatsnew/2.0.rst, pylint/checkers/refactoring.py, pylint/test/functional/simplify_chained_comparison.py, pylint/test/functional/simplify_chained_comparison.txt, pylint/test/functional/too_many_boolean_expressions.py
- #2032
A new checker chained-comparison.
=> Checker for simplifying chained comparison. 

pylint/checkers/refactoring.py
See https://github.com/pheanex/pylint/blob/6b6a88e613570f8f6395c0f812f9111bd5cc7b84/pylint/checkers/refactoring.py#L758 for reference
=> fix logic error in comment

.travis.yml
=> add build stages in travis.yml

ChangeLog, doc/whatsnew/2.0.rst, pylint/checkers/variables.py, pylint/test/unittest_checker_variables.py
=> Expand ignored-argument-names include starred arguments and keyword arguments

pylint/checkers/base.py
Add docstrings for SnakeCaseStyle, CamelCaseStyle, PascalCaseStyle, and UpperCaseStyle
=> Add docstrings for naming style classes

pylint/checkers/base.py
Fixes a pylint warning for wrong continued indentation (bad-continuation)
=> Fix wrong continued indentation (bad-continuation)

pylint/checkers/utils.py
isinstance can take multiple tuples
=> Refactor duplicate code in is_defined_before

pylint/checkers/base.py, pylint/checkers/typecheck.py
I haven't done rigorous measuring, but these seem to take a few seconds off of running over larger directories.
=> Add some early returns

.gitignore
=> add mypy_cache in gitignore

pylint/checkers/misc.py
- Add column offset to fixme messages.
=> Add column offset to fixmes

.travis.yml
=> move rstlint job under prechecks stage

pylint/utils.py
=> fix typos in docstring

ChangeLog, pylint/checkers/base.py, pylint/test/functional/misplaced_format_function.py, pylint/test/functional/misplaced_format_function.txt
=> fix pylint crash due to misplaced-format-function

pylint/config.py, pylint/lint.py, pylint/utils.py
- Added a way of specifying positional arguments to CLIParser (Closes #1889)
- Started using ConfigurationStore (Closes #2357). This class has become almost a dict so I may end up removing it.
=> Can have per directory configurations!

ChangeLog, pylint/checkers/classes.py, pylint/test/unittest_checker_classes.py
Skip Uninferable values from getattr
=> Stop protected-access exception for missing class attributes

doc/whatsnew/2.1.rst, doc/whatsnew/2.2.rst, doc/whatsnew/index.rst
=> add whatsnew/2.2.rst

ChangeLog, doc/whatsnew/2.2.rst, pylint/checkers/utils.py, pylint/test/functional/undefined_variable.py, pylint/test/functional/used_before_assignment_nonlocal.py
fix false positive ``undefined-variable`` and ``used-before-assignment`` with nonlocal keyword usage.
- #2049
=> fix false positive E0601 and E0602 with nonlocal keyword.

CONTRIBUTORS.txt, doc/user_guide/ide-integration.rst
Added documentation on how to use the [pylint-PyCharm-plugin](https://github.com/leinardi/pylint-PyCharm-plugin), as requested in #2433.
|   | Type |
Closes #2433
=> Added pylint-PyCharm-plugin to the ide integration docs

doc/user_guide/ide-integration.rst
I have basically rewritten the entire Pylint PyCharm plugin and this PR updates the documentation to reflect the plugin's changes.
This new version of the plugin offers both real-time and on-demand scanning:
It is also possible to easily scan the current file, the current module, the entire project or just the current changes:
and filter by message type:
I have also applied for publishing the plugin inside the official JetBrains repository (but is still pending): https://plugins.jetbrains.com/plugin/11084-pylint
@PCManticore what do you think is the best way to reach devs that use both Pylint and PyCharm? I would like to promote this plugin and also find some testers but I am not sure from where should I start.
|   | Type |
=> Updated pylint-pycharm plugin documentation

CONTRIBUTORS.txt, ChangeLog, pylint/checkers/refactoring.py, pylint/test/functional/boolean_datetime.py, pylint/test/functional/simplifiable_if_expression.py, pylint/test/functional/simplifiable_if_expression.txt
Similar to simplifiable-if-statement, it finds trivial ternary
statements and suggested replacing them.
Paired-with: Richard Goodman <richardg@brandwatch.com>
|   | Type |
Closes #2487
=> Added check simplifiable-if-expression

CONTRIBUTORS.txt, ChangeLog, pylint/checkers/refactoring.py, pylint/test/functional/consider_using_enumerate.py, pylint/test/functional/consider_using_enumerate.txt
Fixes #2477 by ignoring the `enumerate` suggestion when defining `__iter__` and using `range(len(self))`.
|   | Type |
Closes #2477
=> No enumerate check in __iter__

doc/tutorial.rst
Update tutorial docs to reflect current behaviour. Change example program to Python 3.
|   | Type |
#2118
=> Update tutorial docs

ChangeLog, doc/whatsnew/2.2.rst, pylint/checkers/utils.py, pylint/test/functional/try_except_raise.py
handles multilevel inheritance hierarchy for exceptions in utils.is_subclass_of
|   | Type |
=> fix utils.is_subclass_of for try-except-raise

doc/intro.rst, doc/tutorial.rst, doc/user_guide/installation.rst, doc/user_guide/run.rst
Makes some minor revisions & grammatical corrections to the docs.  Some
notable items:
- tries to make references to PEP 8 consistent (rather than PEP-8, PEP 8,
PEP-08, etc)
- general typos
|   | Type |
N/A
=> Make some minor revisions/corrections to the docs

CONTRIBUTORS.txt, pylint/checkers/variables.py
This is a trivial typo/grammar fix for the E0601 checker description, correcting it to use "its" instead of "it's".
I didn't add a ChangeLog entry to for such a trivial documentation change.
|   | Type |
n/a
=> Fix typo in msg description

CONTRIBUTORS.txt, ChangeLog, doc/how_tos/transform_plugins.rst
Fix how tos docs using `astroid<2.x`
|   | Type |
=> Fix docs to work with astroide>2.x

README.rst
use a decent python version as tox cmd line example.
|   | Type |
=> Update the README's testing section

CONTRIBUTORS.txt, pylint/checkers/python3.py
The documentation states that a range returns an iterator in Python 3 (W1638)
Which is False, I updated the message to "returns a range in Python 3". If this is not the best statement, any ideas are welcome. (Maybe `does not return a list in Python 3`?)
|   | Type |
=> Modify w1638 message

pylint/checkers/typecheck.py
=> Add missing closing parenthesis in option help

CONTRIBUTORS.txt, ChangeLog, doc/whatsnew/2.4.rst, pylint/checkers/stdlib.py, pylint/test/functional/subprocess_run_check35.py, pylint/test/functional/subprocess_run_check35.rc, pylint/test/functional/subprocess_run_check35.txt
- [✓] Add yourself to CONTRIBUTORS if you are a new contributor.
- [✓] Add a ChangeLog entry describing what your PR does.
- [✓] If it's a new feature or an important bug fix, add a What's New entry in `doc/whatsnew/<current release.rst>`.
- [✓] Write a good description on what the PR does.
New checker for `check` arg in subprocess.run for better and explicit exception handling
|   | Type |
Closes #2848
=> Added subprocess.run explicit set `check` argument set checker. Closes #2848

CONTRIBUTORS.txt, ChangeLog, pylint/checkers/spelling.py, pylint/test/unittest_checker_spelling.py
Reduce the line checked to a segment generated from the current word initial position, so, the before checked instances of the same word will be avoided in the check.
|   | Type |
|      | :sparkles: New feature |
|      | :hammer: Refactoring  |
|      | :scroll: Docs |
https://github.com/PyCQA/pylint/issues/2895
=> Fixed #2895 - Correct word pointed in spelling check

CONTRIBUTORS.txt, ChangeLog, doc/conf.py, pylint/checkers/imports.py
Fix typo in documentation
|   | Type |
=> Chore - fix misspellings in documentation

CONTRIBUTORS.txt, ChangeLog, pylint/checkers/base.py, pylint/test/functional/namePresetCamelCase.txt, pylint/test/functional/name_preset_snake_case.txt, pylint/test/functional/name_styles.py, pylint/test/functional/name_styles.txt, pylint/test/test_self.py, pylintrc
Backporting fix for snake-case false positives from https://github.com/PyCQA/pylint/issues/2047
|   | Type |
=> #2047 backport

CONTRIBUTORS.txt, doc/tutorial.rst, pylint/checkers/base.py
This fixes one spacing issue (space after full stop), one grammatical issue ("doesn't" -> "don't" for plural), and one typo ("necessary" -> "necessarily"). The output of this code is also referenced in the tutorial so it is updated there too.
|   | Type |
None
=> Grammar Fixes

CONTRIBUTORS.txt, ChangeLog, examples/pylintrc, man/pylint.1, pylint/checkers/spelling.py, pylint/lint.py
Cleans up a handful of grammar issues and confusing help for a few options.
|   | Type |
n/a
=> Improve help for options

pylint/checkers/base.py
That's what `pylint` teaches us to do according to its own styleguide.
None applies.
|   | Type |
None
=> Refactors `and ... or` expression to ternary

.pre-commit-hooks.yaml
This PR enables `pre-commit` to be pointed directly to this repo instead of the [mirrors](https://github.com/pre-commit/mirrors-pylint) one.
|   | Type |
Closes #2692
=> Start hosting `.pre-commit-hooks.yaml`. Refs #2692

ChangeLog, doc/whatsnew/2.4.rst, pylint/checkers/base.py, tests/functional/redeclared_assigned_name.py, tests/functional/redeclared_assigned_name.txt
|   | Type |
Closes https://github.com/PyCQA/pylint/issues/2898
=> Reassign name check

pylint/checkers/utils.py
Fix a small lint problem apart from a big merge request to not clutter it.
|   | Type |
=> [checkers.utils] Incompatible return value type (expected List[Any])

pylint/__pkginfo__.py
2.4.0 produces various errors when trying to run it with astroid 2.2.x, so bump the dependency.
|   | Type |
=> Require astroid >= 2.3

CONTRIBUTORS.txt, pylint/utils/utils.py
This is small refactoring, will remove duplicate of usage of 'normalize_text`
Refactoring
=> Removed duplicates of code, changed default to common default value

ChangeLog, pylint/testutils.py, tests/test_functional.py, tox.ini
as proposed in
https://github.com/PyCQA/pylint-django/pull/252#issuecomment-547931027
|   | Type |
=> Move classes to testutils to help 3rd party plugin tests

.travis.yml, CONTRIBUTORS.txt, ChangeLog
Update python interpreters versions used in travis configuration
=> [travis] Cleanup travis config using up to date interpreters

.pre-commit-config.yaml, ChangeLog, pylint/checkers/exceptions.py, pylint/checkers/logging.py, pylint/checkers/strings.py, pylint/checkers/utils.py, pylint/checkers/variables.py, tox.ini
Use last version of black : 19.10b0
|   | Type |
=> [formating] Bump black and isort

pylint/checkers/stdlib.py
Just a typo fix in a link.
|   | Type |
=> FIX: Typo.

ChangeLog, pylint/checkers/base.py, tests/functional/n/namePresetCamelCase.txt, tests/functional/n/name_good_bad_names_regex.txt, tests/functional/n/name_preset_snake_case.txt, tests/unittest_checker_base.py
Simplify naming regexps, fix a bug (see changelog and test case).
|   | Type |
=> Naming regexp improvements

pylint/checkers/base.py, pylint/checkers/classes.py, pylint/checkers/format.py, pylint/checkers/python3.py, pylint/checkers/typecheck.py, pylint/checkers/variables.py, pylint/lint.py, pylintrc
After all, if we don't use this, why should anybody else?
=> Enable else-if-used extension

pylint/checkers/base.py, tests/functional/a/assert_on_string_literal.py, tests/functional/a/assert_on_string_literal.txt
=> Adjust assert-on-string-literal to take in consideration empty strings

tests/test_pylint_runners.py
This is designed to simply ensure that the runners exist and haven't
been broken or changed in unexpected ways by refactors (as I did).
Whilst linting may catch changes, having a test that ensures the current
beahviour is captured ensures any changes are more liely to be intentional.
|   | Type |
=> cov| Puts runners under test - simply invokes

tox.ini
Allows generation of html coverage reports if coverage data exists.
Part of the reason for this is coveralls not show deltas in file-coverage.
|   | Type |
=> Generate coverage html reports in tox

pylint/lint/check_parallel.py, pylint/lint/report_functions.py, pylint/lint/run.py, pylint/lint/utils.py
Fix a problem added during #3516 
|   | Type |
=> Add back License not handled by a script

tests/extensions/test_broad_try_clause.py, tests/extensions/test_comparetozero.py
=> Remove unittest.main() not required with pytest

pylint/__pkginfo__.py, setup.py
Background info at https://github.com/pypa/warehouse/pull/7882
|   | Type |
=> Add What's New project URL

ChangeLog, pylint/checkers/classes.py, tests/functional/p/property_with_parameters.py, tests/functional/p/property_with_parameters.txt
=> `property-with-parameters` properly handles abstract properties

ChangeLog, pylint/checkers/variables.py, tests/functional/c/cellvar_escaping_loop.py, tests/functional/c/cellvar_escaping_loop.txt
=> Protect against `AttributeError` when checking `cell-var-from-loop`

examples/pylintrc
=> remove invalid fstr setting

doc/tutorial.rst
I know that this isn't the most important thing in the world, but as
a Latin teacher, it is (literally) my job to notice this sort of thing.
Thanks for pylint.
=> Fix spelling of Caesar

pylint/checkers/refactoring.py
typo fix, identitiy -> identity
|   | Type |
=> Minor typo fix in R1721 help string

CONTRIBUTORS.txt, ChangeLog, pylint/config/option.py, pylint/lint/pylinter.py, tests/test_self.py
Makes it possible to use floats in `fail-under`
|   | Type |
Closes #3626
=> Float fail-under

doc/faq.rst
Following #3817, documentation in the FAQ seems warranted.
|   | Type |
#3817
=> Add documentation for isort compatibility

doc/whatsnew/2.7.rst, doc/whatsnew/index.rst
Permit to document changes that will be in 2.7 now that 2.6 is out.
|   | Type |
#3816
=> Add 2.7.rst to document new changes in v2.7.0

README.rst, doc/exts/pylint_extensions.py, doc/whatsnew/2.6.rst, pylint/checkers/base.py, pylint/checkers/classes.py, pylint/checkers/format.py, pylint/checkers/imports.py, pylint/checkers/refactoring/refactoring_checker.py, pylint/checkers/strings.py, pylint/checkers/variables.py, tests/checkers/unittest_python3.py, tests/functional/l/line_too_long.py, tests/functional/s/stop_iteration_inside_generator.py, tests/functional/u/ungrouped_imports.py, tests/functional/u/using_constant_test.py, tox.ini
=> Remove unsecable whitespace in the whole codebase

.pre-commit-config.yaml, doc/exts/pylint_features.py, pylint/__init__.py, pylint/checkers/__init__.py, pylint/config/__init__.py, pylint/lint/__init__.py, pylint/utils/__init__.py
Add autoflake pre commit hook, autoflake has been around since 2012 and supports more features (also removes unused variables, removes useless pass statements)
|   | Type |
alternative PR to https://github.com/PyCQA/pylint/pull/3840
=> Add autoflake pre commit hook

CONTRIBUTORS.txt, ChangeLog, pylint/checkers/refactoring/refactoring_checker.py, tests/functional/s/super_with_arguments.py
=> Fix AttributeError in checkers/refactoring.py (rebased)

CONTRIBUTORS.txt, ChangeLog, doc/development_guide/contribute.rst
Minor fix for the command in`functional tests` section. I think that my corrected command is what the original writer intended to write. The`pylint` directory does not have a sub-directory named test, so needs to be omitted, also the name of the sub-dir is 'test**s**' and not 'test'.  
|   | Type |
|  | :bug: Bug fix  |
|  | :hammer: Refactoring  |
None
=> Minor doc correction in contribute.rst

CONTRIBUTORS.txt, ChangeLog, doc/how_tos/custom_checkers.rst, doc/user_guide/options.rst
Just cleaning up a few things I noticed when perusing the docs.
- Spurious `^` at the end of a line of `~`
- Checker's `message-id` was documented as being 5 numbers with a leading character, when it is actually 4
|   | Type |
N/A
=> Fix minor doc issues

CONTRIBUTORS.txt, ChangeLog, pylint/checkers/spelling.py, tests/checkers/unittest_spelling.py
=> Updated "Improve sphinx directives spelling filter" stuck PR 

doc/tutorial.rst
#Hacktoberfest (please [add label hacktoberfest-accepted](https://hacktoberfest.digitalocean.com/details#maintainers) to this PR)
Update the tutorial to show output from pylint 1.6.0, and use examples that are picked up by the same version. Removed messages that are no longer displayed (eg. bad-whitespace)
|   | Type |
#2118 (already closed)
=> Update tutorial to include pylint 1.6.0 output

tox.ini
With this change PR submitters can see what needs
to be changed instead of just knowing that
black needs to be run on the code. I think this
is a good kind of feedback
=> Modify tox to show diff of formatting changes with black

pylint/testutils/lint_module_test.py, pylint/testutils/output_line.py, tests/functional/m/missing_self_argument.txt, tests/functional/s/statement_without_effect.txt
This permit to create new functional tests without creating a .txt file with the expected output if there isn't any output.
|   | Type |
=> Make txt file with output optional in functional tests without output

ChangeLog, pylint/checkers/variables.py, tests/functional/u/undefined_variable_crash_on_attribute.py
=> Fix a crash in `undefined-variable` check when encountering chained attributes

.travis.yml, ChangeLog, appveyor.yml, doc/faq.rst, pylint/__pkginfo__.py, pylint/testutils/output_line.py, setup.py, tox.ini
Fix test issues with master branch.
**`__hash__`**
Return `none` is implied if `__eq__` is overwritten but not `__hash__`.
**Drop Python 3.5**
#4074 introduced variable annotations to fix some mypy issues. However those require at least **Python 3.6** (PEP 526).
We could either revert the PR or just move to 3.6.
|   | Type |
=> Fix test issues with master branch

.pre-commit-config.yaml
Update the hooks in pre-commit and fix the bug that found it's way to master because astroid master is broken right now.
|   | Type |
=> Update hooks in pre commit

.flake8, .pre-commit-config.yaml, pylint/__main__.py, pylint/checkers/base.py, pylint/checkers/classes.py, pylint/checkers/spelling.py, pylint/checkers/variables.py, pylint/config/man_help_formatter.py, pylint/pyreverse/inspector.py, pylint/pyreverse/utils.py, setup.py, tests/test_func.py, tests/test_import_graph.py
This add flake8 checks in pre-commit and fix the existing problems.
|   | Type |
=> Add flake8 to pre commit

CONTRIBUTORS.txt, ChangeLog, pylint/checkers/typecheck.py, tests/functional/g/generated_members.py, tests/functional/g/generated_members.rc, tests/functional/g/generated_members.txt
Rebase of #4038 (that is itself a take over of #3634)
=> Graingert add generated members match against the qualified name

.github/workflows/ci.yaml, .pre-commit-config.yaml, .travis.yml, ChangeLog, appveyor.yml, requirements_docs.txt, requirements_test.txt, requirements_test_pre_commit.txt, requirements_test_pypy.txt, tox.ini
#4088 rebased on latest master and from a branch in the official pylint repository so github actions work in the MR already see https://github.com/PyCQA/pylint/pull/4088#issuecomment-780180472
|   | Type |
=> Add GitHub actions (from the inside)

examples/deprecation_checker.py, tests/checkers/unittest_deprecated.py
Cosmetic fixes after #4051
|   | Type |
#4051
=> DeprecatedMixin: Fix typos and order of base classes in test

ChangeLog, doc/release.md, doc/whatsnew/2.8.rst, doc/whatsnew/index.rst, pylint/__pkginfo__.py
Following the release of 2.7.0.
|   | Type |
=> Add 2.8.0 in the Changelog and WhatsNew

.github/ISSUE_TEMPLATE/1_Bug_report.md, .github/ISSUE_TEMPLATE/2_Feature_request.md
Would probably permit to have the version more often and
to have something to do a functional test with more often
too.
|   | Type |
=> Guide the user more in the bug report

.pre-commit-config.yaml, ChangeLog, doc/whatsnew/1.7.rst, doc/whatsnew/1.8.rst, doc/whatsnew/1.9.rst, doc/whatsnew/2.0.rst, doc/whatsnew/2.1.rst, doc/whatsnew/2.2.rst, doc/whatsnew/2.4.rst, doc/whatsnew/2.5.rst, doc/whatsnew/2.6.rst, doc/whatsnew/2.7.rst, script/fix_documentation.py
I noticed that often only single back quotes (**\`**) are used inside the `ChangeLog` and `whatsnew` entries. Intended are almost always double back quotes (\`\`). This MR adds a custom pre-commit hook to address this issue. Additionally it updates the current files.
http://pylint.pycqa.org/en/latest/whatsnew/changelog.html#pylint-s-changelog
|   | Type |
=> Fix documentation

.pre-commit-config.yaml, script/fix_documentation.py, tests/checkers/unittest_spelling.py
Prevent ``# fmt: off`` to make black mandatory.
|   | Type |
=> Remove all fmt off from the codebase and add a check

CONTRIBUTORS.txt, ChangeLog, pylint/pyreverse/main.py, pylint/pyreverse/writer.py, tests/unittest_pyreverse_writer.py
=> pyreverse: Add output directory command-line option

script/fix_documentation.py
Some improvements to the internal `fix-documentation` pre-commit script. Added some more customization options.
|   | Type |
--
=> Improve fix-documentation pre-commit hook

.pre-commit-config.yaml, requirements_test_pre_commit.txt
We need to upgrade pre-commit too.
|   | Type |
=> Upgrade flake8 to 3.9.0 from 3.8.4

pylint/checkers/python3.py, pylint/checkers/spelling.py, pylintrc
See https://lgtm.com/projects/g/PyCQA/pylint/alerts/?mode=list&severity=error
|   | Type |
=> Fix LGTM errors

doc/how_tos/transform_plugins.rst, pylint/checkers/async.py, pylint/checkers/base.py, pylint/checkers/base_checker.py, pylint/checkers/classes.py, pylint/checkers/design_analysis.py, pylint/checkers/exceptions.py, pylint/checkers/imports.py, pylint/checkers/python3.py, pylint/checkers/raw_metrics.py, pylint/checkers/refactoring/len_checker.py, pylint/checkers/refactoring/refactoring_checker.py, pylint/checkers/similar.py, pylint/checkers/stdlib.py, pylint/checkers/strings.py, pylint/checkers/typecheck.py, pylint/checkers/utils.py, pylint/checkers/variables.py, pylint/constants.py, pylint/lint/pylinter.py, pylint/utils/utils.py, tests/unittest_pyreverse_inspector.py
This PR fix the warning signaled by LGTM. See https://lgtm.com/projects/g/PyCQA/pylint/alerts/?mode=list&severity=warning
|   | Type |
=> Fix some LGTM warning

tests/test_self.py
Follow up to #4258
Hopefully the last one 🤞🏻 
|   | Type |
=> Fix regession with sys.path filter (2)

ChangeLog, pylint/__init__.py, pylint/__pkginfo__.py, pylint/checkers/base.py, pylint/checkers/classes.py, pylint/checkers/design_analysis.py, pylint/checkers/imports.py, pylint/checkers/misc.py, pylint/checkers/python3.py, pylint/checkers/typecheck.py, pylint/checkers/variables.py, pylint/extensions/bad_builtin.py, pylint/graph.py, pylint/pyreverse/main.py, pylint/pyreverse/writer.py, pylint/utils/__init__.py, tests/checkers/unittest_classes.py, tests/test_functional.py, tests/test_import_graph.py, tests/unittest_pyreverse_writer.py, tests/utils/unittest_utils.py
We wanted to avoid introducing new problems by separating feature and bug fix in 2.7.x. Right now we have 4/5 rebase conflicts to handle in order to do that. I'd argue more problem will happen because of 5 conflict resolution than with 3 new features. 
|   | Type |
=> Change version for 2.7.3 release, modify release process

ChangeLog, doc/release.md, pylint/__pkginfo__.py
Doing things the old way before doing a PR to discuss what I'd like to change in the release process.
|   | Type |
=> Upgrade project for 2.7.4, and 2.8.0

ChangeLog, doc/release.md, pylint/__pkginfo__.py
Chores following 2.7.4, add an alpha release possibility.
|   | Type |
=> Upgrade the version for development following 2.7.4 release

pylint/checkers/base.py, pylint/checkers/base_checker.py, pylint/checkers/exceptions.py, pylint/checkers/format.py, pylint/checkers/misc.py, pylint/checkers/raw_metrics.py, pylint/checkers/strings.py, pylint/checkers/utils.py, pylint/config/options_provider_mixin.py, pylint/epylint.py, pylint/graph.py, pylint/message/message_handler_mix_in.py, pylint/pyreverse/inspector.py, pylint/utils/pragma_parser.py, setup.py
See https://lgtm.com/projects/g/PyCQA/pylint/alerts/?mode=list
|   | Type |
=> Fix LGTM warnings

tests/functional/l/logging_format_interpolation.py, tests/functional/s/string/string_formatting.py, tests/functional/s/string/string_formatting.txt
Some more tests for a feature that already exists.
Closes #4273
=> Add more functional tests for too few args in logging

pylint/checkers/base.py, pylint/checkers/classes.py, pylint/checkers/format.py, pylint/checkers/misc.py, pylint/checkers/typecheck.py, pylint/checkers/utils.py, pylintrc
While checking #4272 I noticed that the `pylintrc` file used outdated syntax and the `bad_builtin` extension wasn't loaded although `bad-functions` where defined.
|   | Type |
|  | :hammer: Refactoring  |
--
=> Fix pylintrc file

tox.ini
Doc creation failed because the necessary dependencies where not
installed.
|   | Type |
Closes #4290
=> #4290: remove skip_install in testenv docs

tests/test_epylint.py
Apparently epylint was not tested. 
|   | Type |
#4286
=> Add a test for epylint for issue 4286

.pre-commit-config.yaml, pylint/checkers/design_analysis.py, pylint/checkers/format.py, pylint/checkers/spelling.py, pylint/config/option_manager_mixin.py, pylint/lint/run.py, pylintrc, requirements_test_pre_commit.txt, tests/unittest_reporting.py
Upgrade pre-commit configuration and remove some implicit str concat when everything can hold on a single line for black.
|   | Type |
=> Remove some implicit str concat when everything can hold on a single line for black

.github/workflows/ci.yaml, ChangeLog
=> Add continuous integration with read the doc

.readthedocs.yaml, doc/requirements.txt, requirements_docs.txt, tox.ini
Read the doc is not set up for master.
|   | Type |
Follow up to #3850  and https://github.com/PyCQA/pylint/pull/4298#issuecomment-813386731
=> Better build for read the doc

pylint/checkers/classes.py, pylint/lint/expand_modules.py
Fix two LGMT errors, unreachable-statement.
https://lgtm.com/projects/g/PyCQA/pylint/?mode=list
|   | Type |
https://github.com/PyCQA/pylint/pull/4304#pullrequestreview-629771013
=> Fix some LGMT errors

.github/workflows/ci.yaml, requirements_test_min.txt
=> Add editable install in requirements_test_min.txt

.github/CONTRIBUTING.md, .github/ISSUE_TEMPLATE/1_Bug_report.md, .github/ISSUE_TEMPLATE/2_Feature_request.md, .github/ISSUE_TEMPLATE/3_Question.md, .github/PULL_REQUEST_TEMPLATE.md, .github/workflows/ci.yaml, .pre-commit-config.yaml, .pre-commit-hooks.yaml, .readthedocs.yaml, .travis.yml, appveyor.yml, doc/release.md
Also apply prettier
|   | Type |
=> Add prettier to the pre-commit configuration

ChangeLog, pylint/lint/run.py, tests/regrtest_data/fail_under_minus10.py, tests/regrtest_data/fail_under_plus6.py, tests/regrtest_data/fail_under_plus7_5.py, tests/test_self.py
Checks whether score of a run is larger or equals `config.fail_under`. This not only semantically makes sense but also allows for setting `fail_under` to `10.0` and still pass on a perfect score.
|   | Type |
=> Pass if score equals fail_under

ChangeLog, doc/whatsnew/2.8.rst, requirements_test_min.txt, setup.cfg, tests/functional/n/name/name_styles.py, tests/functional/t/typing_generic.py, tests/functional/t/typing_generic.rc
Update ``astroid`` to 2.5.3 and add test case for #2822.
Closes #2822
Closes #4206
Closes #4284
=> Update ``astroid`` to 2.5.3

pylint/extensions/comparetozero.py
FIx inaccurate docstring.
Closes #4274
=> fix inaccurate docstring; closes #4274

tests/functional/d/dataclass_with_default_factory.py, tests/functional/d/dataclass_with_default_factory.rc
=> Add a regression test for #2605

pylint/checkers/utils.py, tests/functional/p/postponed_evaluation_pep585.py, tests/functional/p/postponed_evaluation_pep585_error.py, tests/functional/p/postponed_evaluation_pep585_error.txt, tests/functional/p/postponed_evaluation_pep585_py39.py
Unfortunately, I missed force pushing my last changes yesterday which included an important bugfix. This is a quick follow up.
/CC: @Pierre-Sassoulas 
Follow up to #4340
=> Fix - Improve check for invalid PEP 585 syntax

tests/functional/r/redefine_loop.py, tests/functional/r/redefine_loop.txt
Added test case for issue #4163 
A warning is already thrown in these scenarios and this test case targets that.
Working with @haasea 
Test Case
Closes #4163
=> Added test case for issue #4163

ChangeLog, doc/whatsnew/2.8.rst, requirements_test_min.txt, setup.cfg
Update astroid to latest version. Required for #4382
/CC: @Pierre-Sassoulas
=> Update astroid to 2.5.4

.copyrite_aliases, ChangeLog, doc/whatsnew/2.8.rst, pylint/__init__.py, pylint/__pkginfo__.py, pylint/checkers/__init__.py, pylint/checkers/base.py, pylint/checkers/classes.py, pylint/checkers/format.py, pylint/checkers/misc.py, pylint/checkers/raw_metrics.py, pylint/checkers/similar.py, pylint/checkers/spelling.py, pylint/checkers/stdlib.py, pylint/checkers/variables.py, pylint/epylint.py, pylint/extensions/comparetozero.py, pylint/extensions/confusing_elif.py, pylint/graph.py, pylint/pyreverse/writer.py, pylint/utils/__init__.py, tests/checkers/unittest_format.py, tests/checkers/unittest_similar.py, tests/checkers/unittest_spelling.py, tests/extensions/test_confusing_elif.py, tests/test_self.py
=> Prepare for 2.8.0 release

README.rst
Replace relative URIs with absolute ones. The relative ones don't work for `pypi`: https://pypi.org/project/pylint/
=> Use absolute URIs in readme

.pre-commit-config.yaml, pylint/checkers/__init__.py, pylint/checkers/base.py, pylint/checkers/classes.py, pylint/checkers/design_analysis.py, pylint/checkers/format.py, pylint/checkers/imports.py, pylint/checkers/mapreduce_checker.py, pylint/checkers/newstyle.py, pylint/checkers/python3.py, pylint/checkers/raw_metrics.py, pylint/checkers/similar.py, pylint/checkers/spelling.py, pylint/checkers/stdlib.py, pylint/checkers/strings.py, pylint/checkers/typecheck.py, pylint/checkers/utils.py, pylint/checkers/variables.py, pylint/config/option_manager_mixin.py, pylint/extensions/empty_comment.py, pylint/lint/parallel.py, pylint/message/message_definition_store.py, pylint/reporters/__init__.py, pylint/testutils/reporter_for_tests.py, requirements_test_pre_commit.txt, tests/benchmark/test_baseline_benchmarks.py, tests/checkers/unittest_variables.py, tests/message/unittest_message_definition_store.py, tests/profile/test_profile_against_externals.py, tests/test_self.py
Changelog: https://github.com/psf/black/blob/master/CHANGES.md#214b0
=> Update black to 21.4b0

.github/workflows/ci.yaml, README.rst
This permit to autofix pull request.
=> Add pre-commit CI in continuous integration

pylint/checkers/stdlib.py
Added deprecated methods, arguments and classes to stdlib checker.
=> Add deprecated methods, classes and arguments to stdlib checker

CONTRIBUTORS.txt, ChangeLog, doc/whatsnew/2.9.rst, pylint/checkers/similar.py, tests/checkers/unittest_similar.py, tests/input/similar5, tests/input/similar6
Adds a ignore_signature parameter to duplicate code checker that'll help in cases like similarities caused by multi-line function definitions 
=> Add ignore_signatures to similarity checker

.github/SECURITY.md
=> Add security.md for Tidelift coordinated disclosure plan

pylint/checkers/classes.py, tests/functional/u/unused/unused_private_member.py
Fixed the false positive described in #4504 
#4504
=> Fixed false-positive on ``unused-private-member``

doc/release.md
=> Upgrade release.md following the decision to pin astroid

pylint/message/message.py, pylint/message/message_definition.py, pylint/message/message_definition_store.py, pylint/message/message_id_store.py, tests/message/unittest_message_id_store.py
Only the one that are not creating circular imports.
See #4530
=> Add typing in pylint.messages

.pre-commit-config.yaml
https://github.com/asottile/pyupgrade/compare/v2.19.0...v2.19.1
**Main change**
Revert rewriting of `str.join` with generator expressions as list generators are slightly more efficient.
Details: https://github.com/asottile/pyupgrade/issues/456
=> Bump pyupgrade to v2.19.1

requirements_test_min.txt, requirements_test_pre_commit.txt, setup.cfg
=> Upgrade to astroid 2.5.8

ChangeLog, doc/whatsnew/2.9.rst, pylint/checkers/typecheck.py, tests/functional/a/await_outside_async.py, tests/functional/a/await_outside_async.rc, tests/functional/a/await_outside_async.txt
Implemented new checker ``await-outside-async``, which checks to ensure that ``await`` keyword is used within a scope of an ``AsyncFunctionDef``
#654 , point 5
=> Implemented new checker ``await-outside-async``

pylint/checkers/base.py, tests/functional/i/invalid/invalid_name.py, tests/functional/i/invalid/invalid_name.txt
(So the issue is closed if it get fixed.)
=> Add test case from issue #119 for easier resolution

requirements_test_min.txt, setup.cfg
This will permit to handle all the MR that require an astroid upgrade while we wait for the pickle issue.
=> Upgrade astroid to 2.6.0-dev0

tests/functional/r/regression/regression_2306_enum_value.py
Add regression test from #2306
=> Add regression test from #2306

tests/functional/t/too/too_many_statements.py, tests/functional/t/too/too_many_statements.rc, tests/functional/t/too/too_many_statements.txt
See https://stackoverflow.com/questions/67883103/, the configuration value was not tested.
=> Add a test for ``max-statement`` option of ``too-many-statements`` check

.github/workflows/codeql-analysis.yml
Add some tools provided by github in ``settings/Security & Analysis``.
=> Add code analysis provided by GitHub

tests/functional/r/regression/regression_2913.py, tests/functional/r/regression/regression_2913.txt
=> Rebase of issue/2913-unicode-defs

.github/workflows/ci.yaml, requirements_test_min.txt, setup.cfg, tests/functional/t/typedDict.py
Add a regression test following issue #4610
--
Closes #4610
=> Add a regression test following issue #4610

.copyrite_aliases, ChangeLog, doc/release.md, pylint/__pkginfo__.py, pylint/checkers/base.py, pylint/checkers/utils.py, pylint/checkers/variables.py, pylint/extensions/_check_docs_utils.py, pylint/extensions/confusing_elif.py, pylint/pyreverse/diagrams.py, pylint/pyreverse/inspector.py, pylint/pyreverse/main.py, pylint/pyreverse/utils.py, pylint/pyreverse/writer.py, script/bump_changelog.py, setup.cfg, tbump.toml, tests/checkers/unittest_variables.py, tests/unittest_pyreverse_writer.py
This prepare for 2.9.0 release and check that the problem with windows 3.10 is linked to astroid 2.6.1 or not
=> Prepare release of 2.9.0

doc/whatsnew/2.10.rst, doc/whatsnew/2.9.rst, pylint/__pkginfo__.py, tbump.toml
=> Move back to a dev version and upgrade documentation

requirements_test_min.txt, setup.cfg, tests/functional/r/regression/regression_issue_4633.py
Add a regression test for #4633 
Closes #4633
=> Add a regression test for issue #4633

ChangeLog, pylint/__pkginfo__.py, pylint/extensions/confusing_elif.py, tbump.toml
=> Bump pylint to 2.9.1, update changelog

pylint/checkers/base.py, pylint/checkers/exceptions.py, pylint/checkers/refactoring/not_checker.py, pylint/checkers/strings.py, pylint/checkers/typecheck.py, pylint/checkers/utils.py, pylint/constants.py, pylint/extensions/redefined_variable_type.py, pylint/pyreverse/diadefslib.py
This create a builtins constant in pylint, like in astroid : https://github.com/PyCQA/astroid/pull/1070
=> Create a constant for builtins name

CONTRIBUTORS.txt, doc/user_guide/ide-integration.rst
Documents how to run pylint on a Jupyter Notebook, as per the question in https://github.com/PyCQA/pylint/issues/986
disclaimer: I'm the author of nbQA
=> document Jupyter integration

requirements_test_min.txt, setup.cfg, tests/functional/u/undefined/undefined_variable.py
Regression tests for #3711
Require https://github.com/PyCQA/astroid/pull/1102 to be merged.
=> Add a regression test for undefined-loop-variable false positive

ChangeLog, requirements_test_min.txt, setup.cfg, tests/functional/r/regression/regression_4723.py, tests/functional/r/regression/regression_4723.txt
=> Add a regression test for generator raised StopIteration

ChangeLog, pylint/__pkginfo__.py, pylint/checkers/classes.py, pylint/checkers/imports.py, pylint/checkers/mapreduce_checker.py, pylint/checkers/similar.py, pylint/checkers/stdlib.py, pylint/checkers/typecheck.py, pylint/checkers/utils.py, pylint/exceptions.py, pylint/extensions/_check_docs_utils.py, pylint/extensions/broad_try_clause.py, pylint/extensions/check_docs.py, pylint/extensions/confusing_elif.py, pylint/reporters/ureports/nodes.py, tbump.toml, tests/checkers/unittest_similar.py, tests/extensions/test_confusing_elif.py, tests/test_self.py
=> Bump pylint to 2.9.4, update changelog

ChangeLog, tests/functional/i/inference_crash_4692.py, tests/functional/i/inference_crash_4692.txt
Add a regression test for inference crash #4692 
Closes #4692
=> Add a regression test for inference crash

ChangeLog, pylint/__pkginfo__.py, pylint/checkers/variables.py, tbump.toml
=> 2.9.6 release branch

ChangeLog, doc/release.md, doc/whatsnew/2.10.rst, doc/whatsnew/index.rst
Fix style issue in `changelog` and `whatsnew/2.10.rst`. Additionally add `2.10.rst` to `doc/whatsnew/index.rst`.
=> Fix style issues Changelog + What's New

pylint/__init__.py, pylint/pyreverse/main.py
=> Small typing fix in PyReverse

doc/user_guide/message-control.rst
=> Add documentation for useless-suppression

doc/faq.rst
=> Documentation for what blocks are and FAQ clean up

doc/development_guide/contribute.rst
=> Fix the link to the discord server in the doc

tests/functional/c/class_attributes.py
A regression tests to check that #4823 is working properly on all interpreters and Windows/Linux.
=> Add a regression test for #4823

pylint/lint/pylinter.py
Following review see https://github.com/PyCQA/pylint/pull/4810\#discussion_r688049548
#4810
=> Simplification in error handling inside Pylinter

tests/functional/u/unused/unused_private_member.py, tests/functional/u/unused/unused_private_member.txt
It was already fixed in master, we need to release 2.10.0.
Closes #4837
=> Add a regression test for #4837

pylint/checkers/exceptions.py, pylint/checkers/imports.py, pylint/checkers/logging.py, pylint/checkers/newstyle.py, pylint/checkers/python3.py, pylint/checkers/similar.py, pylint/checkers/stdlib.py, pylint/checkers/strings.py, pylint/checkers/typecheck.py
=> Use alias for astroid.nodes 02

pylint/pyreverse/utils.py, tests/data/suppliermodule_test.py, tests/pyreverse/data/classes_No_Name.dot, tests/pyreverse/data/classes_No_Name.puml, tests/pyreverse/data/classes_No_Name.vcg, tests/pyreverse/data/classes_colorized.dot, tests/pyreverse/data/classes_colorized.puml, tests/pyreverse/test_utils.py
=> pyreverse - Handle a regression with typehints of type astroid.Subscript

pylint/lint/utils.py
=> Prevent crashing when it's impossible to create the issue template

pylint/checkers/refactoring/len_checker.py, pylint/checkers/refactoring/not_checker.py, pylint/checkers/refactoring/recommendation_checker.py, pylint/checkers/utils.py, pylint/checkers/variables.py, pylint/extensions/_check_docs_utils.py
=> Use alias for astroid.nodes 03

tests/functional/n/no/no_member_subclassed_dataclasses.py, tests/functional/n/no/no_member_subclassed_dataclasses.rc
=> Add a test for false positive no-member in subclassed dataclasses

.github/FUNDING.yml
Add main maintainers to funding.yml.
=> Add main maintainers to funding.yml

CONTRIBUTORS.txt, pylint/checkers/design_analysis.py
Hiyaa, I skipped adding this to the `ChangeLog` since the typical developer using `pylint` probably is not interested in reading this. 
Regardless, if you want me to add this, I can add a new entry. 
Thanks for the great project :smile: :+1: 
Closes #4925
=> Upgrade ignored-parents help description

tests/functional/u/unpacking_non_sequence_py37.py, tests/functional/u/unpacking_non_sequence_py37.rc
=> Add regression test for false positive on collections.abc

tests/functional/a/assign/assignment_from_no_return.py, tests/functional/n/no/no_member.py
| ✓   | 📝 Added regression tests |
Regression tests for the fixes in https://github.com/PyCQA/astroid/pull/1151.
=> Add regression tests for PyCQA/astroid#1151

tests/functional/s/super/superfluous_parens.py
Additional test based on a suggestion in #4907
=> Add test to ``superfluous-parens``

doc/user_guide/message-control.rst
Fixes typos in useless-suppression topic.
=> Fix typos in useless-suppression topic

pylint/lint/pylinter.py
=> py-version-check help fixes

doc/whatsnew/2.11.rst
As discussed here: https://github.com/PyCQA/astroid/pull/1180#issuecomment-921737038
=> Add ``flynt`` to 2.11 changelog

pylint/testutils/lint_module_test.py
Almost done with breaking up #4954
=> Add typing to `lint_module_test`

pylint/utils/file_state.py
=> Add typing to `FileState`

pylint/testutils/pyreverse.py
Ref #2079 
This allows ticking of `pylint/testutils/pyreverse.py` from the list.
=> Add basic typing to ``pylint/testutils/pyreverse``

CONTRIBUTORS.txt, ChangeLog, doc/whatsnew/2.12.rst, pylint/checkers/classes.py, pylint/checkers/utils.py, tests/functional/a/access/access_to_protected_members.py, tests/functional/a/access/access_to_protected_members.txt
This supersedes #3300
This closes #3066
=> Fix ``protected-access`` for attributes and methods of nested classes 

pylint/extensions/_check_docs_utils.py
=> Remove accidental print statement

CONTRIBUTORS.txt, ChangeLog, doc/whatsnew/2.12.rst, pylint/pyreverse/main.py
the Install graphviz error is showed even for plantuml message, but for this format no graphiz is needed
=> Nographviz fix

doc/development_guide/contribute.rst, pylint/extensions/__init__.py, script/get_unused_message_id_category.py
Closes #5247 
What about this? @Pierre-Sassoulas
=> Add script to generate new message category id

requirements_test.txt
Should allow #5239 to be merged. Update was released last night!
=> Update ``coveralls`` requirement to ~=3.3

ChangeLog, doc/whatsnew/2.12.rst, pylint/checkers/classes.py, tests/functional/u/unused/unused_private_member.py
=> Fix crash on checking private members on ``__class__``

pylint/config/option_manager_mixin.py
=> Simplify toml handling by removing else after try

doc/tutorial.rst, doc/user_guide/index.rst, doc/user_guide/pre-commit-integration.rst
**WIP**. 
`readthedocs` doesn't automatically run on forks, so using this PR to see how current iteration renders. I'll convert to finished when ready for review :)
Closes #5291
=> Add documentation for adding ``pylint`` to ``pre-commit``

ChangeLog, doc/whatsnew/2.12.rst, tests/functional/a/assign/assignment_expression.py
This adds tests for the problems solved in https://github.com/PyCQA/astroid/pull/1233
This closes #5178
=> Add tests for crash on assignment expressions in if statemenpytts

ChangeLog, doc/whatsnew/2.12.rst, pylint/checkers/classes.py, tests/functional/r/regression_02/regression_protected_access.py, tests/functional/r/regression_02/regression_protected_access.txt
Found in #5173 
Did not create an issue, could still do so if desired
=> Fix crash for ``protected-access`` on (outer)-class traversal

pylint/checkers/base.py, pylint/checkers/similar.py, pylint/checkers/spelling.py, pylint/checkers/utils.py, pylint/config/option.py, pylint/config/option_manager_mixin.py, pylint/extensions/__init__.py, pylint/lint/parallel.py, pylint/lint/pylinter.py, pylint/lint/run.py, pylint/reporters/__init__.py, pylint/reporters/reports_handler_mix_in.py, pylint/testutils/output_line.py, setup.cfg, tests/lint/test_pylinter.py, tests/test_func.py, tests/test_pylint_runners.py, tests/test_self.py
=> Add error codes to all ``type: ignore``

ChangeLog, tests/functional/i/inherit_non_class.py, tests/functional/i/inherit_non_class.txt
Tests for https://github.com/PyCQA/astroid/pull/1266
=> Add tests `inherit-non-class` with subscriptable class

tests/testutils/test_output_line.py
Some additional tests and some docstrings to other tests.
=> Add additional tests for ``OutputLine``

pylint/checkers/base.py, pylint/checkers/classes.py, pylint/checkers/format.py, pylint/checkers/imports.py, pylint/checkers/refactoring/implicit_booleaness_checker.py, pylint/checkers/refactoring/recommendation_checker.py, pylint/checkers/refactoring/refactoring_checker.py, pylint/checkers/similar.py, pylint/checkers/stdlib.py, pylint/checkers/strings.py, pylint/checkers/typecheck.py, pylint/checkers/utils.py, pylint/checkers/variables.py, pylint/config/option.py, pylint/config/options_provider_mixin.py, pylint/extensions/typing.py, pylint/graph.py, pylint/lint/pylinter.py, pylint/utils/pragma_parser.py, pylintrc
Activate use set for membership in pylint, for a small performance gain.
=> Activate and fix existing use-set-for-membership checks

doc/development_guide/testing.rst
See https://github.com/PyCQA/pylint/pull/5386#discussion_r756987807.
=> Update documentation of ``max_pyver`` test option

tests/checkers/unittest_format.py, tests/functional/m/multiple_statements.py, tests/functional/m/multiple_statements.txt, tests/functional/m/multiple_statements_single_line.py, tests/functional/m/multiple_statements_single_line.rc, tests/functional/m/multiple_statements_single_line.txt
=> Move ``TestMultiStatementLine`` to functional tests

tests/checkers/unittest_strings.py, tests/functional/b/bad_string_format_type.py, tests/functional/b/bad_string_format_type.txt
To ease the process of reviewing your PR, do make sure to complete the following boxes.
=> Move ``TestStringChecker`` to functional tests

tests/checkers/unittest_stdlib.py, tests/functional/s/shallow_copy_environ.py, tests/functional/s/shallow_copy_environ.txt
Another one in my lunch break! 5 classes left for `pytest -k unittest` 😄
=> Move most tests of ``TestStdlibChecker`` to functional tests

tests/checkers/unittest_imports.py, tests/functional/i/import_error.py, tests/functional/i/import_error.rc, tests/functional/i/import_error.txt, tests/functional/i/import_outside_toplevel.py, tests/functional/i/import_outside_toplevel.rc, tests/functional/i/import_outside_toplevel.txt
Left some tests that need data. Those location attributes will need to be added by hand.
=> Move most tests out of ``TestImportsChecker``

tests/functional/ext/docparams/raise/missing_raises_doc_Google.py, tests/functional/ext/docparams/raise/missing_raises_doc_Numpy.py, tests/functional/ext/docparams/raise/missing_raises_doc_Sphinx.py
=> Add type of docstring to ``missing_raises_doc`` functional tests

tests/extensions/test_check_docs.py, tests/functional/ext/docparams/parameter/missing_param_doc_required_Google.py, tests/functional/ext/docparams/parameter/missing_param_doc_required_Google.rc, tests/functional/ext/docparams/parameter/missing_param_doc_required_Google.txt, tests/functional/ext/docparams/raise/missing_raises_doc_Google.py, tests/functional/ext/docparams/raise/missing_raises_doc_Google.txt, tests/functional/ext/docparams/return/missing_return_doc_Google.py, tests/functional/ext/docparams/return/missing_return_doc_Google.txt, tests/functional/ext/docparams/return/missing_return_doc_required_Google.py, tests/functional/ext/docparams/return/missing_return_doc_required_Google.txt
=> Move tests for Google docstrings from ``TestParamDocChecker`` to functional tests

tests/checkers/unittest_base.py, tests/functional/n/nan_comparison_check.py, tests/functional/n/nan_comparison_check.txt, tests/functional/s/singleton_comparison.py, tests/functional/s/singleton_comparison.txt
I think this should be the final moving PR 😄
=> Move tests from ``TestComparison`` to functional tests

.pre-commit-config.yaml, pylint/extensions/__init__.py, pylint/reporters/__init__.py, requirements_test_pre_commit.txt, tests/config/unittest_config.py
http://mypy-lang.blogspot.com/2021/12/mypy-0920-released.html
=> Upgrade mypy to 0.920

tests/functional/r/regression_02/regression_node_statement_two.py
Suggestion by @jacobtylerwalls in #5382.
=> Add regression test for issue #5382

pylint/checkers/typecheck.py
This typing is a bit more useful than what Pylance/VS Code came up with itself... Makes it easier to contribute to `visit_call` in this checker.
I added some `TODO`'s as to not lose information I already looked up. Let me know if you want to keep that in or if I should remove them..
=> Add typing to ``_determine_callable``

examples/custom.py, pylint/checkers/classes/special_methods_checker.py, pylint/checkers/refactoring/implicit_booleaness_checker.py, pylint/extensions/broad_try_clause.py, pylint/extensions/docparams.py, pylint/interfaces.py, tests/test_check_parallel.py
Some small unrelated change before #5558
=> Typo and small fixes before 5558

pylint/testutils/configuration_test.py, pylint/testutils/functional/test_file.py, pylint/testutils/get_test_info.py
Small changes, trying to get `testutils` to pass with `--strict`.
=> Add typing to some functions in ``testutils``

pylint/lint/pylinter.py
=> Add typing to file visiting attributes of ``PyLinter``

tests/lint/unittest_lint.py
Based on comment here: https://github.com/PyCQA/pylint/pull/5580#discussion_r773286938
=> Rename ``init_linter`` fixture to ``initialized_linter``, add filename

pylint/config/man_help_formatter.py
It's better if abstractness is explicit and enforced by an error at instanciation.
=> Make an implicitely abtract class explicitely abstract and remove disable

pylint/lint/pylinter.py
Should be only 1/2 PRs after this one to get the `__init__` (and therefore all attributes) of `PyLinter` typed 😄
=> Add types to option attributes of ``PyLinter`` and reorganize ``init``

CODE_OF_CONDUCT.md
The template makes this really easy and I think this will bring benefits.
=> Add a code of conduct from template

.pre-commit-config.yaml, pylint/checkers/utils.py, requirements_test_pre_commit.txt
http://mypy-lang.blogspot.com/2021/12/mypy-0930-released.html
=> Upgrade mypy to 0.930

pylint/lint/parallel.py, tests/test_check_parallel.py
Follow up to #5609.
Not sure why this was not done in the original PR, but this can be a `with` statement.
=> Use ``with`` statement in ``parallel.py``

pylint/__init__.py, tests/test_pylint_runners.py
See @cdce8p's review here: https://github.com/PyCQA/pylint/pull/5613#discussion_r776900943
=> Rename ``arguments`` to ``argv`` in entry point functions

tests/message/unittest_message_id_store.py
Closes #5255 
This is a very quick and dirty approach, but I guess it works? Too bad that I see some recent additions in here that could have been avoided if this test had been in place earlier 😢
=> Add test for exclusivity of id names

pylint/checkers/variables.py
Tagging @jacobtylerwalls again as the expert.
Instead of doing an assert I updated the typing and used an ignore. `mypy` is dumb here and doesn't recognise that `action is VariableVisitConsumerAction.CONSUME` says something about the second value of the tuple. `pylance` does recognise this. Hopefully `mypy` will start to recognise this and we'll get a useless ignore warning here.
=> Add typing to ``get_next_to_consume`` and ``_check_consumer``

tests/checkers/unittest_unicode/unittest_bad_chars.py, tests/checkers/unittest_unicode/unittest_bidirectional_unicode.py, tests/checkers/unittest_unicode/unittest_invalid_encoding.py, tests/conftest.py
We're getting some `pytest` warnings on `main`. This fixes that as well using the standard pattern for test files.
=> Follow-up to some test changes

ChangeLog, doc/whatsnew/2.13.rst, pylint/checkers/classes/class_checker.py, tests/functional/r/redefined_slots.py, tests/functional/r/redefined_slots.txt
=> Add checker `redefined-slots-in-subclass`

ChangeLog, doc/whatsnew/2.13.rst, pylint/checkers/classes/class_checker.py, tests/functional/i/init_not_called.txt, tests/functional/n/non/non_init_parent_called.txt, tests/functional/s/super/super_init_not_called.py, tests/functional/s/super/super_init_not_called.txt, tests/functional/s/super/super_init_not_called_extensions.py, tests/functional/s/super/super_init_not_called_extensions.rc, tests/functional/s/super/super_init_not_called_extensions.txt, tests/functional/s/super/super_init_not_called_extensions_py310.py, tests/functional/s/super/super_init_not_called_extensions_py310.rc, tests/functional/s/super/super_init_not_called_extensions_py310.txt, tests/functional/s/super/super_init_not_called_py38.py, tests/functional/s/super/super_init_not_called_py38.rc
Closes #4790.
Added typing and `confidence` as well.
=> Fix ``super-init-not-called`` if parent or ``self`` is a ``Protocol``

ChangeLog, doc/whatsnew/2.13.rst, pylint/checkers/classes/class_checker.py, pylint/checkers/imports.py, pylint/checkers/stdlib.py, tests/functional/s/super/super_init_not_called.py, tests/functional/s/super/super_init_not_called.txt
=> Fix false positive ``super-init-not-called`` for inherited ``init``

.copyrite_aliases, CONTRIBUTORS.txt
|   | :bug: Bug fix          |
Add Or Bahari (myself) to aliases new format
This was added ass a separate MR because of the request made in this [comment](https://github.com/PyCQA/pylint/pull/5628#issuecomment-1020583885) .
=> add Or Bahari copyrite aliases

ChangeLog, doc/whatsnew/2.13.rst, pylint/checkers/stdlib.py, tests/functional/u/unspecified_encoding_py38.py, tests/functional/u/unspecified_encoding_py38.txt
=> Fix crash when providing None to mode arg of open()

pylint/checkers/similar.py, pylint/lint/parallel.py, pylint/lint/pylinter.py, tests/lint/unittest_lint.py, tests/test_check_parallel.py
Turned out to be quite easy.
@Pierre-Sassoulas I wonder if this breaks anything. I don't think it shouldn't, but I'm hesitant about it...
=> Add ``DeprecationWarning`` for non-string ``current_name`` & ``file``

tests/functional/n/no/no_else_break.py, tests/functional/n/no/no_else_continue.py, tests/functional/n/no/no_else_raise.py
=> Fix typos in unit test docstrings

ChangeLog, doc/whatsnew/2.13.rst, pylint/lint/pylinter.py, tests/lint/test_utils.py
Closes #5668.
Was unsure about the exception to raise, but I think this makes sense. Also added typing 😄
=> Emit the crash issue template for more exceptions and crashes

ChangeLog, doc/whatsnew/2.13.rst, pylint/checkers/base.py, pylint/checkers/refactoring/refactoring_checker.py, pylint/extensions/check_elif.py, tests/functional/ext/check_elif/check_elif.txt, tests/functional/n/no/no_else_break.txt, tests/functional/n/no/no_else_continue.txt, tests/functional/n/no/no_else_raise.txt, tests/functional/n/no/no_else_return.txt, tests/functional/u/useless/useless_else_on_loop.txt
See https://github.com/PyCQA/pylint/pull/5614#issuecomment-1023614434 for rationale.
Closes #5598
=> Clearer error message for useless-else-x type messages

pylint/checkers/variables.py
See discussion in https://github.com/PyCQA/pylint/pull/5727#discussion_r795078071. Wait for #5727, then rebase and open for review.
=> Remove VariableVisitConsumerAction.CONSUME

doc/development_guide/testing.rst
Follow-up to #5753. With this #5474 can be closed as it has been superseded.
=> Update Testing docs to reflect enforced folder structure

CONTRIBUTORS.txt, README.rst
|   | :bug: Bug fix          |
- Add note on how to share badge for pylint
Closes #5819
=> Add note on how to share the badge for pylint

doc/user_guide/output.rst, doc/user_guide/run.rst
=> Add title in running pylint's documentation

ChangeLog, doc/whatsnew/2.13.rst, requirements_test_min.txt, setup.cfg
=> Add a ``testutil`` extra-require and add ``gitpython`` to it

.pre-commit-config.yaml, ChangeLog, doc/whatsnew/2.13.rst, pylint/config/find_default_config_files.py, pylint/config/option_manager_mixin.py, requirements_test.txt, setup.cfg, tests/config/functional/toml/issue_3181/toml_decode_error.1.out
=> Use the ``tomli`` package instead of ``toml`` to parse ``.toml``

pylint/checkers/imports.py, pylint/reporters/text.py
Typo fix and type annotation fix. Two independent commits (could be a "rebase and merge").
=> Fix type annotation and typo

.pre-commit-config.yaml, pylint/testutils/functional/test_file.py, pylint/testutils/primer.py, requirements_test_pre_commit.txt, setup.cfg
Can't merge yet as the ``pre-commit`` mypy mirror hasn't been updated yet, see: https://github.com/pre-commit/mirrors-mypy
=> Upgrade mypy to 0.940

pylint/checkers/classes/class_checker.py, pylint/checkers/design_analysis.py, pylint/checkers/refactoring/refactoring_checker.py, pylint/checkers/typecheck.py, pylint/checkers/variables.py
Based on @cdce8p's comment [here](https://github.com/PyCQA/pylint/pull/5907#discussion_r825493666).
=> Simplify ``cached_property`` import guards

.pre-commit-config.yaml
Fixed an issue with the pre-commit hook configuration. No longer necessary to pass `-w` ourselves.
=> Update ``pydocstringformatter`` to ``0.5.3``

doc/how_tos/custom_checkers.rst
I just created my first AST checker in #5938 following the docs and wanted to make a few small tweaks to help improve them further for future contributors 😄
=> Update "How to Write a Checker" docs

script/.contributors_aliases.json
First step toward #5877. Done independently so we can see what really changed in the configuration later.
=> Migrate copyrite configuration

ChangeLog, doc/release.md, doc/whatsnew/2.13.rst, doc/whatsnew/2.14.rst, doc/whatsnew/index.rst, pylint/__pkginfo__.py, tbump.toml
=> Release branch 2.13.0

pylint/checkers/__init__.py, pylint/utils/utils.py
=> Add basic typing to ``pylint/utils.py``

pylint/reporters/multi_reporter.py, pylint/reporters/reports_handler_mix_in.py
=> Add basic typing to ``pylint/reporters``

pylint/reporters/ureports/base_writer.py, pylint/reporters/ureports/nodes.py, pylint/reporters/ureports/text_writer.py
Together with #5978 this should finish the `reporters` directory.
=> Final typing for ``pylint/reporters/ureports``

doc/data/messages/a/assigning-non-slot/bad.py, doc/data/messages/a/assigning-non-slot/good.py
=> Added message doc for assigning-non-slot

doc/data/messages/a/attribute-defined-outside-init/bad.py, doc/data/messages/a/attribute-defined-outside-init/good.py
=> Added example for attribute-defined-outside-init

doc/data/messages/b/bad-builtin/bad.py, doc/data/messages/b/bad-builtin/good.py
=> Added example for bad-builtin

doc/data/messages/b/bad-indentation/bad.py, doc/data/messages/b/bad-indentation/details.rst, doc/data/messages/b/bad-indentation/good.py
=> Added example for bad-indentation

ChangeLog, pylint/checkers/base/name_checker/checker.py, tests/functional/u/unbalanced_tuple_unpacking.py, tests/functional/u/unbalanced_tuple_unpacking.txt
=> Fix crash on unbalanced tuple unpacking

doc/data/messages/b/bare-except/bad.py, doc/data/messages/b/bare-except/good.py
=> Added example of bare-except

README.rst
|  🚀   | Type                   |
| ✔   | :scroll: Docs          |
There was a sus defect in the readme where it had a broken link.
=> fix workflow badge in readme

pylint/config/config_initialization.py, pylint/config/option_manager_mixin.py
=> Move setting of the current module to a better place in config init

pylint/config/__init__.py, pylint/config/environment_variable.py, pylint/constants.py
Remove what I believe is dead code. There's more to do in ``pylint.config.__init__``  but I'm taking it slow as it's untested and hard to test right now. The refactor aims to make this more testable.
=> Cleanup of the USER_HOME variable in ``pylint.config``

README.rst
=> Fix Tidelift logo in README.rst

doc/exts/pylint_messages.py
=> Docs: Generate note about extensions module in message documentation

pylint/checkers/base/name_checker/naming_style.py
Small performance improvement. 
Regex compilation takes up quite a bit of time in our start-up. I couldn't find other places to improve immediately, but every little bit helps.
=> Re-use regex pattern in naming style

doc/data/messages/r/redefined-slots-in-subclass/bad.py, doc/data/messages/r/redefined-slots-in-subclass/good.py
=> Add ``redefined-slots-in-subclass`` documentation examples

doc/data/messages/b/bad-option-value/bad.py, doc/data/messages/b/bad-option-value/good.py
-->
Add example for ``bad-option-value``.
Ref: #5953
=> Documentation examples for ``bad-option-value``

doc/data/messages/b/bad-str-strip-call/bad.py, doc/data/messages/b/bad-str-strip-call/good.py
So it's easier to understand what strip does without reading the documentation
=> [doc] Add example to bad strip call

ChangeLog, doc/data/messages/d/duplicate-argument-name/bad.py, doc/data/messages/d/duplicate-argument-name/good.py, pylint/checkers/base/basic_error_checker.py, script/.contributors_aliases.json, tests/functional/a/async_functions.py, tests/functional/a/async_functions.txt, tests/functional/d/duplicate_argument_name.py, tests/functional/d/duplicate_argument_name.txt, tests/functional/d/duplicate_argument_name_py3.py, tests/functional/d/duplicate_argument_name_py3.txt
add code example for `duplicate-argument-name`
Ref #5953
=> Add example for `duplicate-argument-name` message documentation

doc/data/messages/a/arguments-differ/bad.py, doc/data/messages/a/arguments-differ/details.rst, doc/data/messages/a/arguments-differ/good.py, doc/data/messages/a/arguments-differ/related.rst, doc/data/messages/a/arguments-out-of-order/bad.py, doc/data/messages/a/arguments-out-of-order/good.py, doc/data/messages/a/arguments-renamed/bad.py, doc/data/messages/a/arguments-renamed/good.py, doc/data/messages/s/super-with-arguments/bad.py, doc/data/messages/s/super-with-arguments/good.py, doc/data/messages/t/too-many-arguments/bad.py, doc/data/messages/t/too-many-arguments/good.py
Code examples based on [pylint-errors](https://github.com/vald-phoenix/pylint-errors) and my own work.
Ref. #5953.
=> Add documentation for messages with arguments in their name

pylint/config/argument.py
I moved some code from #6055 to make it more reviewable.
=> Use transformers instead of validators for ``Argument``

doc/data/messages/b/broad-except/bad.py, doc/data/messages/b/broad-except/good.py
=> Added broad-except message example

doc/data/messages/c/catching-non-exception/bad.py, doc/data/messages/c/catching-non-exception/good.py
=> Add catching-non-exception message example

pylint/checkers/base/docstring_checker.py, pylint/config/argument.py
If all of these are this easy...
=> Use the ``argparse`` config handler in ``docstring_checker.py``

ChangeLog, doc/whatsnew/2.14.rst, pylint/checkers/dunder_methods.py, tests/functional/u/unnecessary/unnecessary_dunder_call.py, tests/functional/u/unnecessary/unnecessary_dunder_call.txt
Closes #6074. Allows dunder method calls on super()
=> Exclude dunder calls on super() from raising ``unnecessary-dunder-call``

pylint/checkers/imports.py, pylint/config/argument.py, pylint/testutils/unittest_linter.py, pylint/utils/utils.py, tests/test_import_graph.py
=> Use the ``argparse`` config handler in ``imports.py``

pylint/checkers/refactoring/refactoring_checker.py, pylintrc, tests/pyreverse/test_utils.py
Part of #6078 that we can add already.
=> Use for v in *.values() instead of _, v in *.items()

pylint/checkers/exceptions.py, pylint/checkers/format.py, pylint/config/argument.py
=> Use ``argparse`` config handler in ``imports.py`` & ``exceptions.py``

pylint/checkers/design_analysis.py, pylint/config/argument.py
=> Use ``argparse`` config handler in ``design_analysis.py``

pylint/checkers/strings.py, pylint/checkers/typecheck.py, pylint/config/arguments_manager.py
=> Use ``argparse`` config handler on two checkers

pylint/config/config_initialization.py
Let's see what this does to the coverage.
=> Do ``argparse`` parsing of config file first

pylint/checkers/misc.py, pylint/config/config_file_parser.py, pylint/testutils/decorator.py
=> Use ``argparse`` config handler in ``misc.py``

pylint/config/config_file_parser.py, pylint/config/utils.py, pylint/testutils/decorator.py
Removes the need to instantiate another `_ConfigurationFileParser` 😄
=> Move ``_parse_rich_type_value`` to ``utils``

pylint/extensions/bad_builtin.py, pylint/extensions/broad_try_clause.py, pylint/extensions/code_style.py, pylint/extensions/docparams.py, pylint/extensions/mccabe.py, pylint/extensions/typing.py
=> Use ``argparse`` config handler in all extensions

doc/conf.py
- clean up commented config from `python-docs-theme`
- add notes about use of default `furo` theme config
=> Clean up docs `conf.py`

pylint/checkers/base_checker.py, pylint/checkers/similar.py, tests/checkers/unittest_similar.py
=> Use ``argparse`` config handler in ``similar.py``

doc/data/messages/w/wildcard-import/bad.py, doc/data/messages/w/wildcard-import/good.py
Co-authored-by: Vladyslav Krylasov vladyslav.krylasov@gmail.com
Related to #5953
=> Add `wildcard-import` doc example

pylint/config/argument.py
See:
https://github.com/PyCQA/pylint/blob/5e1926e77fb5956f3776f7a75b18e809bce56a62/pylint/config/option.py#L99-L114
@Pierre-Sassoulas  Turning on `argparse` for the `PyLinter` class is a mammoth task so I'm splitting some of the jobs into separate PRs that can be merged separately. They will have low coverage, but they are needed for the final `PyLinter` PR to be somewhat reviewable.
=> Add last missing transformers

pylint/config/argument.py, pylint/config/arguments_manager.py, pylint/config/config_initialization.py, pylint/config/option.py, pylint/config/utils.py, pylint/interfaces.py, pylint/lint/pylinter.py, pylintrc
Changes are all over the place. Best viewed in commit view. Trying to get `PyLinter` to work...
=> Small changes to ``argparse`` implementation

doc/data/messages/u/unreachable/bad.py, doc/data/messages/u/unreachable/good.py
- add example code for `unreachable`
Related: #5953
=> add example for `unreachable` message documentation

doc/data/messages/u/undefined-variable/bad.py, doc/data/messages/u/undefined-variable/good.py
- add example for add example for `undefined-variable`
Ref #5953
=> add example for `undefined-variable` message documentation

doc/data/messages/b/broken-collections-callable/bad.py, doc/data/messages/b/broken-collections-callable/good.py, doc/data/messages/b/broken-collections-callable/pylintrc, doc/data/messages/b/broken-collections-callable/related.rst
=> Add example for ``broken-collections-callable``

doc/data/messages/s/singleton-comparison/bad.py, doc/data/messages/s/singleton-comparison/good.py, doc/data/messages/s/singleton-comparison/related.rst
=> Added singleton-comparison message example

pylint/config/__init__.py, pylint/config/argument.py, pylint/config/arguments_manager.py, pylint/config/utils.py, pylint/lint/pylinter.py, pylint/testutils/unittest_linter.py
Blocked by #6143.
Now that I have done all options I now which `Arguments` we support. The last two commits in this PR fix up their inheritance cycle.
=> Refactor all ``_Argument`` classes

pylint/config/callback_actions.py, pylint/config/exceptions.py, pylint/config/utils.py, pylint/lint/__init__.py, pylint/lint/run.py, pylint/lint/utils.py, tests/lint/unittest_lint.py, tests/test_self.py
Think this might be the final refactor of `Run` for now.
Cleans up the remaining bits and pieces of the options handling here.
=> Move preprocessing of arguments into ``config`` directory

ChangeLog, doc/data/messages/t/typevar-name-mismatch/bad.py, doc/data/messages/t/typevar-name-mismatch/good.py, doc/whatsnew/2.14.rst, pylint/checkers/base/name_checker/checker.py, tests/functional/t/typevar_name_mismatch.py, tests/functional/t/typevar_name_mismatch.txt
Catches when typevar name doesn't match the assigned variable name.
Follows on from work in #6015.
Closes #5224
=> New check: TypeVar name mismatch

doc/data/messages/c/comparison-with-callable/bad.py, doc/data/messages/c/comparison-with-callable/good.py
=> Added comparison-with-callable message example

pylint/config/arguments_manager.py, pylint/config/config_initialization.py, pylint/config/deprecation_actions.py, tests/config/test_argparse_config.py
=> Finalize ``_parse_command_line_configuration``

pylint/lint/pylinter.py, pylint/lint/run.py, pylint/testutils/checker_test_case.py, tests/benchmark/test_baseline_benchmarks.py, tests/config/test_config.py, tests/lint/unittest_lint.py, tests/test_check_parallel.py
These are the easy options without complicated test that need updating.
=> Partially use ``namespace`` in ``PyLinter``

doc/test_messages_documentation.py, pylint/lint/pylinter.py, pylint/reporters/text.py, pylint/testutils/global_test_linter.py, pylint/testutils/lint_module_test.py, tests/lint/unittest_lint.py, tests/unittest_reporters_json.py, tests/unittest_reporting.py
=> Use namespace in PyLinter and tests

.github/workflows/tests.yaml
Simple solution to a time consuming debug.
=> Increase the cache version to fix pypy 3.7

doc/data/messages/f/function-redefined/bad.py, doc/data/messages/f/function-redefined/good.py
- add code example for `function-redefined`
Related #5953
=> add example for `function-redefined` message documentation

pylint/checkers/base_checker.py, pylint/checkers/similar.py, pylint/config/options_provider_mixin.py, pylint/lint/pylinter.py, pylint/pyreverse/main.py, pylint/typing.py
=> Add ``Options`` and ``OptionsDict`` to typing utils

pylint/config/arguments_manager.py, pylint/config/config_file_parser.py, pylint/config/config_initialization.py
Two commits that should improve the performance somewhat. Instead of iterating in `_load_default_argument_values` we not iterate when we already go over all options.
=> Performance improvements to ``argparse`` config parsing

pylint/config/arguments_manager.py, pylint/config/arguments_provider.py, pylint/lint/pylinter.py, tests/test_self.py
Extracting some of the changes in #6199 as well as fixing one easy `TODO`.
=> Another round of small refactors in ``argparse``

doc/data/messages/c/cell-var-from-loop/related.rst, doc/data/messages/d/duplicate-key/related.rst, doc/data/messages/g/global-at-module-level/related.rst, doc/data/messages/l/literal-comparison/related.rst, doc/data/messages/m/missing-format-argument-key/related.rst, doc/data/messages/s/self-assigning-variable/related.rst, doc/data/messages/s/singleton-comparison/related.rst, doc/data/messages/t/too-few-format-args/related.rst, doc/data/messages/t/too-many-format-args/related.rst, doc/data/messages/u/unbalanced-tuple-unpacking/related.rst, doc/data/messages/u/undefined-all-variable/related.rst, doc/data/messages/u/unidiomatic-typecheck/related.rst, doc/data/messages/u/useless-import-alias/related.rst, doc/test_messages_documentation.py
=> Assert that links in related.rst are a list

pylint/config/arguments_manager.py, pylint/lint/pylinter.py
=> Deprecate ``register_options_provider``

pylint/config/arguments_manager.py
=> Deprecate ``add_option_group``

pylint/config/arguments_manager.py
=> Deprecate ``add_optik_option`` and ``optik_option``

pylint/config/arguments_manager.py, pylint/config/callback_actions.py, pylint/utils/utils.py
=> Deprecate ``generate_config``

pylint/config/arguments_manager.py, pylint/config/config_initialization.py, pylint/lint/pylinter.py
=> Deprecate ``load_provider_defaults`` and ``read_config_file``

doc/data/messages/u/use-list-literal/bad.py, doc/data/messages/u/use-list-literal/good.py
=> Added example for use-list-literal message

doc/data/messages/i/import-outside-toplevel/bad.py, doc/data/messages/i/import-outside-toplevel/good.py
=> Added import-outside-toplevel message example

doc/data/messages/w/wrong-import-position/bad.py, doc/data/messages/w/wrong-import-position/good.py
=> Added wrong-import-position message example

.pre-commit-config.yaml, doc/data/messages/m/misplaced-future/bad.py, doc/data/messages/m/misplaced-future/good.py
=> Added misplaced-future message example

doc/data/messages/u/use-dict-literal/bad.py, doc/data/messages/u/use-dict-literal/good.py
=> Added example of use-dict-literal message

doc/data/messages/m/missing-module-docstring/bad.py, doc/data/messages/m/missing-module-docstring/good.py
=> Added missing-module-docstring message example

doc/data/messages/m/missing-function-docstring/bad.py, doc/data/messages/m/missing-function-docstring/good.py
=> Added missing-function-docstring message example

doc/data/messages/u/useless-return/bad.py, doc/data/messages/u/useless-return/good.py
=> Added useless-return message example

pylint/config/utils.py, tests/config/test_deprecations.py, tests/config/unittest_config.py, tests/lint/unittest_expand_modules.py, tests/regrtest_data/dummy_plugin/dummy_plugin.py
=> Handle missing keys in option dictionaries

pylint/checkers/async.py, pylint/checkers/base/docstring_checker.py, pylint/checkers/base_checker.py, pylint/checkers/classes/class_checker.py, pylint/checkers/design_analysis.py, pylint/checkers/exceptions.py, pylint/checkers/format.py, pylint/checkers/imports.py, pylint/checkers/logging.py, pylint/checkers/misc.py, pylint/checkers/raw_metrics.py, pylint/checkers/refactoring/refactoring_checker.py, pylint/checkers/similar.py, pylint/checkers/spelling.py, pylint/checkers/strings.py, pylint/checkers/typecheck.py, pylint/config/exceptions.py, pylint/extensions/bad_builtin.py, pylint/extensions/broad_try_clause.py, pylint/extensions/code_style.py, pylint/extensions/docparams.py, pylint/extensions/mccabe.py, pylint/extensions/typing.py, pylint/lint/pylinter.py
=> Remove the ``future_option_parsing`` keyword

pylint/checkers/base_checker.py, pylint/config/arguments_provider.py, tests/test_regr.py
@Pierre-Sassoulas I know this method is not perfect, but it worked quite well with `ArgumentsManager` so I'd like to do it like this again :)
=> Copy all ``OptionsProvideMixIn`` methods to ``ArgumentsProvider``

.pre-commit-config.yaml, tests/config/unittest_config.py, tests/test_self.py
=> Set ``pyupgrade`` to ``--py37-plus``

doc/data/messages/n/no-else-raise/bad.py, doc/data/messages/n/no-else-raise/good.py
=> Added no-else-raise message example

doc/data/messages/n/no-else-return/bad.py, doc/data/messages/n/no-else-return/good.py
=> Added no-else-return message example

pylint/checkers/base/name_checker/checker.py, pylint/checkers/variables.py, pylint/config/utils.py
=> Use ``namespace`` in two more checkers

pylint/checkers/base_checker.py, pylint/config/arguments_manager.py, pylint/config/arguments_provider.py, tests/test_regr.py
=> Remove ``OptionsProviderMixIn`` from ``BaseChecker``

pylint/config/arguments_manager.py, pylint/config/config_initialization.py, pylint/lint/pylinter.py, pylint/typing.py
=> Number of small refactors in ``argparse`` code

pylint/config/callback_actions.py, pylint/config/config_file_parser.py, pylint/config/utils.py
=> Add ``_DisableAction`` and ``_EnableAction``

pylint/lint/pylinter.py, tests/lint/unittest_lint.py, tests/regrtest_data/dummy_plugin/dummy_conf_plugin.py
=> Use ``namespace`` for ``ignore`` and ``ignore_patterns``

doc/data/messages/n/no-else-break/bad.py, doc/data/messages/n/no-else-break/good.py
=> Added no-else-break message example

pylint/config/arguments_provider.py
=> Do not use ``config`` in ``option_value``

pylint/testutils/unittest_linter.py
=> Let ``UnittestLinter`` subclass ``PyLinter``

pylint/testutils/decorator.py
=> Remove the ``optparse`` section from ``set_config``

pylint/checkers/base/name_checker/naming_style.py
Followup to #6072
Instead of chained assignments, use separate lines to help with readability.
=> Update formatting for NamingStyles

pylint/config/arguments_provider.py, pylint/config/config_initialization.py, tests/config/test_deprecations.py
Drafting as I want to see the coverage impact.
=> Remove use of deprecated methods in ``_ArgumentsProvider`` and ``_config_initialization``

pylint/lint/expand_modules.py, pylint/lint/parallel.py, pylint/lint/pylinter.py, pylint/lint/report_functions.py, pylint/lint/run.py
=> Use ``python-typing-update`` on ``pylint/lint`` directory

pylint/config/arguments_manager.py, pylint/config/arguments_provider.py, pylint/lint/pylinter.py, tests/test_regr.py
=> Set ``Namespace`` on ``config`` instead of ``namespace``

pylint/config/arguments_manager.py, pylint/lint/run.py, tests/config/test_deprecations.py
=> Several refactors related to ``argparse``

ChangeLog, doc/whatsnew/2.14.rst, pylint/checkers/base_checker.py, pylint/config/arguments_manager.py, pylint/config/arguments_provider.py, pylint/config/option_manager_mixin.py, pylint/lint/pylinter.py, pylint/testutils/decorator.py, tests/config/test_deprecations.py, tests/config/test_find_default_config_files.py, tests/test_import_graph.py, tests/unittest_reporting.py
=> Number of argparse refactors

.coveragerc, pylint/config/arguments_manager.py, pylint/config/arguments_provider.py, pylint/config/callback_actions.py
Files left to fix coverage in:
`pylint/config/__init__.py`
`pylint/config/argument.py`
`pylint/config/arguments_manager.py`
`pylint/config/config_file_parser.py`
`pylint/config/utils.py`
`pylint/config/find_default_config_files.py`
=> Exclude deprecated methods and files from coverage

pylint/config/arguments_manager.py, pylint/pyreverse/main.py, pylint/pyreverse/utils.py, pylint/pyreverse/writer.py
Small refactors in preparation for a larger PR that transitions to ``argparse``.
=> Add typing and small refactors to pyreverse

tests/config/functional/toml/toml_without_pylint.toml, tests/config/test_config.py, tests/config/test_find_default_config_files.py
=> Improve coverage of ``argparse``

ChangeLog, doc/whatsnew/2.14.rst, pylint/checkers/async.py, pylint/checkers/base/basic_checker.py, pylint/checkers/base/basic_error_checker.py, pylint/checkers/classes/class_checker.py, pylint/checkers/design_analysis.py, pylint/checkers/imports.py, pylint/checkers/refactoring/recommendation_checker.py, pylint/checkers/refactoring/refactoring_checker.py, pylint/checkers/typecheck.py, pylint/checkers/unsupported_version.py, pylint/checkers/variables.py, pylint/extensions/code_style.py, pylint/extensions/docparams.py, pylint/extensions/typing.py, pylint/lint/pylinter.py, pylint/utils/utils.py, tests/checkers/unittest_design.py, tests/config/test_deprecations.py, tests/config/unittest_config.py, tests/lint/unittest_expand_modules.py
=> Deprecate ``get_global_option``

ChangeLog, doc/whatsnew/2.14.rst, pylint/checkers/similar.py, pylint/config/arguments_manager.py, pylint/config/utils.py, pylint/lint/pylinter.py
=> Several ``argparse`` related refactors

pylint/config/arguments_manager.py, pylint/pyreverse/main.py, pylint/pyreverse/writer.py, pylint/testutils/pyreverse.py, tests/pyreverse/test_main.py
=> Transition ``pyreverse`` from ``optparse`` to ``argparse``

pylint/__pkginfo__.py
As discussed in this comment:
https://github.com/PyCQA/pylint/pull/6348#discussion_r851600653
=> Improve type annotation of version tuple

pylint/checkers/base_checker.py, tests/checkers/unittest_base_checker.py
=> Improve the ``__gt__`` method of Checkers

pylint/checkers/similar.py, tests/regrtest_data/duplicate_code/ignore_imports/file_one.py, tests/regrtest_data/duplicate_code/ignore_imports/file_two.py, tests/test_similar.py
Didn't add a changelog as it is unreleased.
Closes #6350.
=> Fix regression with ``ignore-imports``

tests/functional/c/cell_var_from_loop_enabled_regression.py, tests/functional/c/cell_var_from_loop_enabled_regression.rc, tests/functional/c/cell_var_from_loop_enabled_regression.txt
=> Add regression tests for cell var from loop (#4574)

pylint/config/option_manager_mixin.py, pylint/utils/utils.py
=> Add remaining typing to ``pylint/utils``

pylint/config/callback_actions.py, pylint/config/utils.py, pylint/lint/expand_modules.py, pylint/lint/run.py, pylint/lint/utils.py, pylint/message/message_definition_store.py
=> Add some typing to ``pylint/lint``
