pylint-dev/pylint

doc/ide-integration.rst
Here are the instructions for integrating with PyCharm.  Figured it'd be better to bring them in than simply update the link to point to another blog that might disappear.
fixes #755
=> Add PyCharm integration instructions

pylint/checkers/classes.py
…f the ClassChecker
Those methods are actually not only emitting the listed messages but also updating
some internal state that is used from other, unrestricted, messages. We should
work on separating responsabilities if we want to restrict method entries upon
messages restriction.
Closes issue #789
=> remove @check_message decorator from [visit|leave]_classdef methods of the ClassChecker

pylint/checkers/misc.py, pylint/test/unittest_checker_misc.py
Hi, I changed the regex : 
https://github.com/PyCQA/pylint/blob/master/pylint/checkers/misc.py#L88.
I did several tests. At the project root, run :
~~~bash
cd pylint/test/
python -m unittest discover -p "unittest_checker_misc.py"
~~~
If you can review that ? I don't know where put this patch. I chose master. 
But if it is available for the new version of pylint 1.6.0, or also for pylint 1.5.4.x, it will be great.
**Required** 
pylint 1.6.0, 
astroid 1.5.0
Python 3.4.3 (default, Oct 14 2015, 20:28:29) 
[GCC 4.8.4]
=> Fix #793 [MISCELLANEOUS] code tag without message doesn't track

pylint/utils.py
Tuples of length 4+ will match the preceding case.
=> Remove pointless slicing in build_message_def

pylint/checkers/typecheck.py, pylint/test/unittest_checker_typecheck.py, pylintrc
This makes it possible to configure pylint to recognize backports of contextlib or other decorators similar to `@contextmanager` without the need for an explicit `#pylint disable=not-context-manager`.
Tested with a backport of contextlib from Python 3 onto Python 2 imported under a different name.
cc @dbaum who suggested making this configurable upstream.
=> Make list of contextmanager decorators configurable.

pylint/checkers/utils.py
__div__ is used in python2 decimal and numbers packages as well as 3rd
party modules so treat it like the other special methods.
This should fix issue #807 and should also be backported to the 1.5.0 branch.
=> Add __div__ to special methods

pylint/testutils.py
I find that passing the line parameter of `is_message_enabled` by keyword makes the code more readable, and this seems to be done both [in Pylint code](https://github.com/PyCQA/pylint/blob/master/pylint/test/unittest_lint.py#L261) and in external content like @nedbat's [edx_lint](https://github.com/edx/edx-lint/blob/master/edx_lint/pylint/getattr_check.py#L63), but currently `UnittestLinter.is_message_enabled` doesn't allow keyword arguments, which is annoying when trying to test such lints.
This PR fixes that issue by just allowing and ignoring keyword arguments.
=> UnittestLinter.is_message_enabled blows up when passed keyword arguments

bin/epylint.bat, bin/pylint-gui.bat, bin/pylint.bat, bin/pyreverse.bat, bin/symilar.bat
When deploying to Windows, the Python script files (ie: those with no file extensions) that would typically be deployed to Linux platforms are automatically converted to native executables. Those executables are then accompanied by batch files which were meant to act as a redirect on Windows to allow the system shell to run the extension-less files using the current Python interpreter. Unfortunately these scripts never took into account this conversion process that happens during deployment.
As such I've reworked the batch files so they simply redirect their calls to the native executable files that still share the same name as their batch file counterparts.
=> Fixed Windows startup scripts so they redirect to the executable files generated by setuptools.

pylint/checkers/classes.py, pylint/test/functional/invalid_length_returned.py, pylint/test/functional/invalid_length_returned.txt
=> New check: invalid-length-returned

CONTRIBUTORS.txt, README.rst, pylint/__pkginfo__.py, pylint/checkers/imports.py, pylint/test/functional/import_error.py, pylint/test/functional/reimported.py, pylint/test/functional/super_checks.py, pylint/test/input/func_w0404.py, tox.ini
=>  [REF] import-checkers: Use of isort

pylint/extensions/check_docs.py, pylint/test/extensions/test_check_docs.py
This pull request adds support for looking for constructor parameter documentation in either the class or `__init__` docstring. See #886 for the motivation behind this.
This also adds a new warning (W9005) to indicate when constructor parameters are documented
in both the class docstring and `__init__` docstring.
This does not implement checking whether the parameters are consistently documented in either the class or `__init__` docstring.
Fixes #886
=> [ADD] check_docs can find constructor parameters in __init__

pylint/checkers/imports.py, pylint/test/functional/wrong_import_order.py, pylint/test/functional/wrong_import_order.txt, pylint/test/functional/wrong_import_order2.py, pylint/test/input/func_w0233.py
The value node.modname for `from . import package`
or `from .package import Class`
returns `package`
But `isort` needs `.package` to detect a local import.
=> [FIX] wrong-import-order: Fix detect local imports

pylint/lint.py
Currently 'pylint -E' disables all no-error messages. Instead,
it should disable messages types which severity is lower than
error.
=> Show fatal messages when disabling no-error messages

elisp/pylint.el
Prefix arg wasn't working as intended, now it's fixed.
=> fix bug in pylint-insert-ignore-comment and add it to the commentary

CONTRIBUTORS.txt, pylint/__pkginfo__.py, pylint/extensions/check_mccabe.py, pylint/test/extensions/data/mccabe.py, pylint/test/extensions/test_check_mccabe.py, tox.ini
Integrate a new check to verify the [cyclomatic complexity](https://en.wikipedia.org/wiki/Cyclomatic_complexity) of a code with mccabe 
Other python Checker QA [flake8](https://flake8.readthedocs.org/en/latest/#quickstart) have this check.
```bash
flake8 offers an extra option: 
–max-complexity, which will emit a warning 
if the McCabe complexity of a function is higher than the value. 
By default it’s deactivated
$ flake8 --max-complexity 12 coolproject
coolproject/mod.py:939:1: C901 'Checker.check_all' is too complex (12)
coolproject/mod.py:1204:1: C901 'selftest' is too complex (14)
```
=> [ADD] mccabe: Add check for mccabe complexity cyclomatic threshold

doc/options.rst
There is inconsistency in documentations regarding default regexp (between manpage and shinx-based rst file).
=> Update of documentation's part describing regexp default values for symbol names

.github/CONTRIBUTING.md, .github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md
- Auto fill a template format for issues and pull request of github
- Add a contributing link in issues.
Example:
=> [ADD] .github: Add standard folder .github to add github templates

man/pylint.1, pylint/__pkginfo__.py
As per RFC 6068, there should be no slashes after `mailto:`.
=> Fix mailto URIs

pylint/extensions/_check_docs_utils.py, pylint/extensions/check_docs.py, pylint/test/extensions/test_check_return_docs.py
This adds checking that a docstring documents information about what is returned in the method when the method returns a statement.
If no docstring exists then a warning will be raised. The user has the option to turn this off with the `accept_no_return_doc` option.
=> Added return docstring checking to check_docs

pylint/extensions/_check_docs_utils.py, pylint/extensions/check_docs.py, pylint/test/extensions/test_check_docs.py
This fixes a couple of bugs in check_docs.
Linting docstrings with args and kwargs failed because we were still using list operations on variables that were converted to sets. There are now tests for linting the docstring of methods that are args or kwargs.
Google docstrings allow asterisks at the start of args and kwargs in docstrings. We weren't taking this into account. So it would try to match "*args" against "args" and "**kwargs" against "kwargs" and fail. There are now tests for this as well.
=> Check docs improvements

pylint/extensions/_check_docs_utils.py
The common section parsing code has been merged into a single method.
Fixed matching of complex types (eg mymodule.MyClass), references (eg :class:`AClass`), and container types (eg list(:class:`AClass`) or tuple(str, int)).
Fixed numpy docs not requiring descriptions.
=> Improved docstring matching in check_docs

CONTRIBUTORS.txt, ChangeLog, pylint/checkers/base.py, pylint/test/unittest_checker_base.py, pylintrc
This makes it possible to configure pylint to accept custom decorators
similar to @property without the need to explicitly add a pylint
directive #pylint disable=invalid-name
=> Made list of property-like decorators configurable.

examples/pylintrc, man/pylint.1, pylint/checkers/typecheck.py, pylintrc
- Added "threading.local" to ignored classes default list (as "thread._local" and "_thread._local")
Note that the implementation names for Python 2/3 are used (threading.local is an alias). Also changed related places for consistency.
=> Added threading.local to ignored classes default list

CONTRIBUTORS.txt, ChangeLog, doc/extensions.rst
- As reported in #735, the documentation for the check_docs extension incorrectly instructs the user to set `accept-no-param-doc=yes` to enable additional checking, but in actuality these checks are enabled by `accept-no-param-doc=no`.
=> Fixed check_docs doc error (#735)

pylint/lint.py, pylint/utils.py
The PyLinter object is still very dependent on having certain operation performed on it in order. Hence why the parallel code is often calling methods on `self.linter`. As we move towards a linter object being used for a single file, it would be good to eliminate these.
Implements #936
=> Moved parallel execution code outside of PyLinter

ChangeLog, doc/whatsnew/2.0.rst, pylint/extensions/docparams.py, pylint/test/extensions/test_check_docs.py
- Fix a false positive of 'missing-param-doc' and 'missing-type-doc' that occurred when a class docstring uses the 'For the parameters, see' magic string but the class __init__ docstring does not, or vice versa.
```python
"Foo and Bar"
class Foo(object):
"""Foo.
For the parameters, see AnotherClass.
"""
def __init__(self, x):
"""Foo the bar.
"""
self.x = x
class Bar(object):
"""Bar.
"""
def __init__(self, x):
"""Bar the foo.
For the parameters, see AnotherClass.
"""
self.x = x
```
Before:
```
$ pylint --load-plugins=pylint.extensions.docparams --accept-no-param-doc=n for_the_parameters.py
************* Module for_the_parameters
W:  8, 4: "x" missing or differing in parameter documentation (missing-param-doc)
W:  8, 4: "x" missing or differing in parameter type documentation …
```
=> Fix false positive for missing-[type,param]-doc

doc/contribute.rst
During development, it's helpful to run only a subset of tests
to have faster feedback, this adds instructions on how to do it.
It took me more time to figure this out than to make the changes
needed for #1016, so it will be nice to have it in the docs.
=> Document how to run a subset of tests during development

ChangeLog, doc/whatsnew/2.0.rst, pylint/checkers/base.py, pylint/checkers/imports.py, pylint/checkers/raw_metrics.py, pylint/exceptions.py, pylint/lint.py, pylint/test/unittest_lint.py, pylint/test/unittest_utils.py, pylint/utils.py
-  Add missing validation of message ``old_names`` in ``MessagesStore.register_messages()`` to prevent a newly registered message from overwriting values previously registered by another message.
- Add `InvalidMessageError` to raise in these and similar cases instead of using `assert`.
- Move `EmptyReport` and `UnknownMessage` exceptions (and `InvalidMessageError`) to `pylint.exceptions` submodule.
- Rename `EmptyReport` to `EmptyReportError` and `UnknownMessage` to `UnknownMessageError`
=> Prevent data overwrite by old_names in register_messages

doc/installation.rst
- should be `pip install pylint`, I think ?
=> update instruction to install pylint

pylint/checkers/classes.py
Otherwise we get this from astroid:
```
.../pylint/pylint/checkers/classes.py:1112: PendingDeprecationWarning:
ClassDef.instanciate_class() is deprecated and slated for removal in
astroid 2.0, use ClassDef.instantiate_class() instead.
instance = cls.instanciate_class()
```
=> Use ClassDef.instantiate_class()

elisp/pylint.el
Emacs guesses the indent of a python file and stores it in a buffer-local variable.  This patch allows pylint.el to set `--indent-string` based on the guessed indent.  
I worked at a place with the weird policy of 3 space indent.  Emacs guessed this correctly, but pylint would complain about the indentation.  I didn't want to set it to 3 for everything because my personal scripts and other projects use the normal 4 space indent.  So this does the Right Thing on a per-file basis.
=> elisp: allow guessed indent string to be passed to pylint

pylint/checkers/variables.py, pylint/test/functional/unused_variable.py
- https://github.com/PyCQA/pylint/issues/1058
- Additional check in `pylint/test/functional/unused_variable.py`
In `pylint/test/functional/unused_argument.py`, the following line should fail; The test is, actually, incorrect.
__unused_argument.py:__
```
def test_unused(first, second, _not_used): # [unused-argument, unused-argument]
pass
```
However. First of all, I don't know the Pylint codebase well enough know why this is either being skipped or it is marked as a pass; It shouldn't. I want to point a finger to the `pylintrc` file, but I won't be so brash. Running pylint without any arguments,  `pylint pylint/test/functional/unused_argument.py`, appears to confirm my point.
```
I:  1, 0: Locally disabling missing-docstring (C0111) (locally-disabled)
I:  1, 0: Locally disabling …
```
=> Allow underscores in unused-variables. (#1058)

ChangeLog, doc/whatsnew/2.0.rst, pylint/config.py, pylint/test/regrtest_data/dummy_plugin.rc, pylint/test/regrtest_data/dummy_plugin/dummy_plugin.py, pylint/test/test_self.py
If you create a plugin and you want just one section for all checkers but you need many class to split logic, then you will need repeat the `name` value of the attribute of the classes to have the same section in the configuration file.
Reverting the core change and running the same tests the resut was:
```bash
======================================================================
ERROR: test_pylintrc_plugin_duplicate_options (test_self.RunTC)
----------------------------------------------------------------------
File "/root/vauxoo-dev/pylint/.tox/py33/lib/python3.3/site-packages/pylint/test/test_self.py", line 351, in test_pylintrc_plugin_duplicate_options
expected_output=expected)
File "/root/vauxoo-dev/pylint/.tox/py33/lib/python3.3/site-packages/pylin …
```
=> [REF] config.py: Support multiple classes with same 'name' value

CONTRIBUTORS.txt, ChangeLog, doc/whatsnew/2.0.rst, pylint/checkers/newstyle.py, pylint/test/functional/super_checks.py, pylint/test/functional/super_checks.txt
Now detects `super(type(self), self)` and `super(self.__class__, self)` which can lead to recursion loop in derived classes. For more info on the topic see:
http://stackoverflow.com/questions/18208683/when-calling-super-in-a-derived-class-can-i-pass-in-self-class
**NOTE**:  currently there is also a regression wrt *Bad first argument 'type' given to super()* being detected. I have an older version (pylint-1.3.1-1.el7.noarch) which emits this error but the code in master doesn't. I think commit 2943e24 broke this but I'm not certain. In case you'd like to debug the regression first I'm posting the entire diff between my local version and master.
```
$ diff -u /usr/lib/python2.7/site-packages/pylint/checkers/newstyle.py pylint/checkers/newstyle.py
--- …
```
=> Add new error conditions for 'bad-super-call'

.travis.yml, pylint/__pkginfo__.py
- Environment markers can be used only in recent versions of
setuptools. Instead of relying on extras_require, we are falling back to
install_requires when we detect an incompatibility between the installed
setuptools version and what pylint expects.
Steps to reproduce a error before of this change:
```bash
virtualenv pylint_old_setuptools
source pylint_old_setuptools/bin/activate
pip install setuptools==1.1.6
pip install --no-deps git+https://github.com/PyCQA/pylint@master
Collecting git+https://github.com/PyCQA/pylint@master
Cloning https://github.com/PyCQA/pylint (to master) to /var/folders/zc/1m37yppx4z5596yfyzg385140000gn/T/pip-l78WRL-build
Complete output from command python setup.py egg_info:
error in pylint setup command: Invalid environment marker: python_version<"3.4"
```
Using …
=> Add compatibility with old versions of setuptools

CONTRIBUTORS.txt, doc/whatsnew/2.0.rst, pylint/checkers/python3.py, pylint/test/unittest_checker_python3.py
I've been exploring transitioning our codebase to Python 3, and I've been using the immensely helpful `-3` flag when running tests as described here:
https://docs.python.org/3/howto/pyporting.html#prevent-compatibility-regressions
Unfortunately, one of the most common issues I'm finding is around classes implementing `__eq__` but not `__hash__`.  The behavior around this changed in Python 3.  See below:
```python
class JustEq(object):
def __init__(self, x):
self.x = x
def __eq__(self, other):
return self.x == other.x
class Neither(object):
def __init__(self, x):
self.x = x
class HashAndEq(object):
def __init__(self, x):
self.x = x
def __eq__(self, other):
return self.x == other.x
def __hash__(self):
return hash(self.x)
{Neither(1), Neither(2)}  # OK
{HashAndEq(1), HashAndEq(2)}  # OK …
```
=> Add a Python 3 warning for implementing `__eq__` without also implentnting `__hash__`

ChangeLog, doc/whatsnew/2.0.rst, pylint/checkers/python3.py, pylint/test/unittest_checker_python3.py
These methods are removed in Python 3 in favor of `__truediv__`.
=> Add a warning when declaring `__div__` or `__idiv__` in Python 2.

pylint/checkers/logging.py
These two descriptions were reversed, and missing a full stop.
=> Fix descriptions for E1205 & E1206.

ChangeLog, doc/whatsnew/2.0.rst, pylint/checkers/python3.py, pylint/test/unittest_checker_python3.py
Unfortunately I forgot about this in https://github.com/PyCQA/pylint/pull/1121
=> Issue a warning on methods implementing `__rdiv__` as well.

examples/custom_raw.py
- 
Fix following error when using this plugin
```
with module.stream() as stream:
NameError: global name 'module' is not defined
```
=> Fix err "global name 'module' is not defined"

CONTRIBUTORS.txt, doc/whatsnew/2.0.rst, pylint/checkers/python3.py, pylint/test/functional/exception_message.py, pylint/test/functional/exception_message.rc, pylint/test/functional/exception_message.txt, pylint/test/unittest_checker_python3.py
**Fixes / new features**
Exception.message has been removed in Python 3.  This checker should be able to find most instances of it's use.
=> Add a checker for accessing `Exception.message` in Python 2.

CONTRIBUTORS.txt, ChangeLog, doc/whatsnew/2.0.rst, pylint/checkers/python3.py, pylint/test/unittest_checker_python3.py
These codecs were removed from the type restricted convenience methods on
`str`, `bytes`, and `bytearray` in Python 3.4 and produce inconsistent output
with their counterparts in `codecs`
=> Add a Python 3 checker for calls to `encode` or `decode` with non-text codecs.

CONTRIBUTORS.txt, ChangeLog, pylint/checkers/classes.py, pylint/test/functional/slots_checks.py, pylint/test/functional/slots_checks.txt
- Addresses issue 1166: [detect \_\_slots\_\_ = "single_attr" as being bad](https://github.com/PyCQA/pylint/issues/1166)
=> Report when __slots__ is a simple string and not a non-string container

CONTRIBUTORS.txt, ChangeLog, doc/whatsnew/2.0.rst, pylint/checkers/classes.py, pylint/checkers/refactoring.py, pylint/checkers/spelling.py, pylint/checkers/typecheck.py, pylint/config.py, pylint/test/functional/len_checks.py, pylint/test/functional/len_checks.txt
This new checker implements the following statement from PEP8:
```
For sequences, (strings, lists, tuples), use the fact that empty sequences are false.
Yes: if not seq:
if seq:
No: if len(seq):
if not len(seq):
```
This is still a work in progress mainly around lines 76-79 when we have a Compare statement. ATM I'm not handling statements like `0 < len(S) < 5` or `0 != len(S)`, etc. Advice is welcome on how to handle this and what sort of error conditions to consider valid.
Background: Recently I've been working with a code base which has lots of `if len(something) > 0` or `if len(something) != 0` and figured I'll write this patch.
=> Add new checker len-as-condition

CONTRIBUTORS.txt, ChangeLog, doc/whatsnew/2.0.rst, pylint/checkers/python3.py, pylint/test/unittest_checker_python3.py
This also triggered a "Rule of 3" refactoring for me to generalize warning about
accessing a given attribute on a module.
=> Add Python 3 checker for accessing deprecated functions on the `string` module.

doc/whatsnew/2.0.rst, pylint/checkers/python3.py, pylint/test/unittest_checker_python3.py
This checker could possibly have some false positives, but after checking our codebase
and several other large codebases using this implementation, I did not find any false
positives.
=> Add a Python 3 checker for finding deprecated calls to `str.translate`.

pylint/checkers/python3.py, pylint/test/unittest_checker_python3.py
Without this change there could be a false-positive with the following code:
```python
import six.moves.configparser
configparser.ConfigParser()
```
=> Only check system modules during imports.

pylint/checkers/misc.py, pylint/test/functional/fixme_bad_formatting_1139.py, pylint/test/functional/fixme_bad_formatting_1139.rc, pylint/test/functional/fixme_bad_formatting_1139.txt
When file has CRLF line separators, CR was kept in msg. This CR made
CLI output behave unexpectedly.
Solves #1139
=> Fix CLI output for fixme messages

CONTRIBUTORS.txt, ChangeLog, doc/whatsnew/2.0.rst, pylint/checkers/variables.py, pylint/test/functional/unused_global_variable1.py, pylint/test/functional/unused_global_variable2.py, pylint/test/functional/unused_global_variable2.rc, pylint/test/functional/unused_global_variable2.txt, pylint/test/functional/unused_global_variable3.py, pylint/test/functional/unused_global_variable4.py, pylint/test/functional/unused_global_variable4.rc, pylint/test/functional/unused_global_variable4.txt
- yield warnings for unused global variables (disabled by default)
Obviously it's not ready for merge, but I'll leave it here in case anyone want to leave a feedback (which is appreciated).
Closes #919
=> allow-global-unused-variables

ChangeLog, pylint/checkers/variables.py, pylint/test/unittest_checker_variables.py
- Now ignores modules imported as _ when checking for unused modules.
- Closes #1190
=> 'import ... as _' skips unused-import check.

Makefile
- Fixes #1220 by upgrading tox to version 2.x which is compatible with py35
=> Upgrade tox to v2.x for py35 compatability (#1220)

ChangeLog, pylint/checkers/variables.py, pylint/test/functional/bugfix_local_scope_metaclass_1177.py, pylint/test/functional/bugfix_local_scope_metaclass_1177.rc
TODO:
Current fail is triggered, when metaclass is imported in non local (enclosing) scope. I’m not quite sure yet how pushing and popping from `_to_consume` stack should work, but second element of pushed tuple seems to be never populated.
Any input is appreciated.
Closes #1177
=> Improve metaclass detection in nested scopes in Python 3

ChangeLog, doc/whatsnew/2.0.rst, pylint/checkers/base.py, pylint/checkers/python3.py, pylint/checkers/refactoring.py, pylint/checkers/variables.py, pylint/extensions/docstyle.py, pylint/test/functional/boolean_datetime.py, pylint/test/functional/ternary.py, pylint/test/functional/ternary.txt, pylint/utils.py
Fixes #1204.
It's a rough draft, which still needs additional tests and refactoring.
Basic assumptions was:
- low (zero) error rate - do not emit message unless multiple conditions are supported. That's why complex boolean operations in `cond and true or false` are ignored and only literal ordered sequences are checked in `(false, true)[cond]` case.
- Reasonable user experience - correct form should be emitted in message
I'll do some additional work on it, but maybe there will be some valuable feedback.
=> New refactoring checker: consider-using-ternary

pylint/utils.py
Remove code duplication by extracting private method for enabling/disabling messages.
Note that code is not equivalent:
- `msgs_store._alternative_names` is looked up on both enable and disable path (was: only on disable path)
- config object is synced for both `enable` and `disable` attributes after each enable/disable (was: one of two depending on performed action)
=> MessagesHandlerMixIn: extract common private method

CONTRIBUTORS.txt, pylint/checkers/refactoring.py, pylint/test/functional/ternary.py
Using a sentence like as: `my_var = True and True and True or True`
Avoid show the following traceback:
```bash
File "pylint/checkers/refactoring.py", line 400, in visit_assign
cond, truth_value, false_value = self._get_and_or_ternary_arguments(node.value)
File "pylint/checkers/refactoring.py", line 427, in _get_and_or_ternary_arguments
condition, true_value = node.values[0].values
ValueError: too many values to unpack
```
NOTE: I didn't changed ChangeLog because is a fix of a new check from 2.0.0 version (unreleased).
=> [FIX] consider-using-ternary: Fix case: 'True and True and True or True'

pylint/checkers/format.py, pylint/test/unittest_checker_format.py
Code such as:
```python
"""
test
"""
from typing import Dict
def my_function(my_attr: Dict = None):
"""
foo
"""
print(my_attr)
```
caused convention warnings because of the spaces around kwarg assignment. Yet, this syntax is correct when type hints are used.
- Require spaces around kwarg assignment if type hint used
=> Omit convention warnings on assignment with type hints

CONTRIBUTORS.txt, ChangeLog, doc/whatsnew/2.0.rst, pylint/extensions/emptystring.py, pylint/test/extensions/data/empty_string_comparison.py, pylint/test/extensions/test_emptystring.py
Detects things like
```
if X == '':
pass
```
Note that in some cases this is what the author needs but my experience tells me most of the times empty string value doesn't have a special meaning. 
Note2: this probably belongs to the ComparisonChecker in base.py. This checker however only supports binary comparisons so I will have to fix his limitation first. Let me know how would you like to proceed about that.
=> New checker: comparison to empty string constant

pylint/checkers/spelling.py
* Skips spelling on shebang lines
* Skips spelling on coding lines
* Skips spelling on pylint enable/disable comments
=> Ignore shebang's, coding lines and pylint comments

pylint/test/functional/arguments_differ_py3.txt
- fix failing tests in pylint/test/functional/arguments_differ_py3.py
=> Fix errors introduced by change to arguments-differ

CONTRIBUTORS.txt, ChangeLog, doc/whatsnew/2.0.rst, pylint/extensions/comparetozero.py, pylint/test/extensions/data/compare_to_zero.py, pylint/test/extensions/test_comparetozero.py
Similar to #1183 but for comparisons to zero. Again made it as an extension because this may not be what you need. I've used this to refactor a great deal of projects I've been working on though where such comparisons are not needed and expand the size of mutation test matrix in the order of 1000s of additional cases.
Please review and comment, thanks.
=> Add new extension for detecting integer comparisons against zero

pylint/test/conftest.py, pylint/test/extensions/test_bad_builtin.py, pylint/test/extensions/test_check_mccabe.py, pylint/test/extensions/test_docstyle.py, pylint/test/extensions/test_elseif_used.py, pylint/test/extensions/test_emptystring.py, pylint/test/extensions/test_overlapping_exceptions.py, pylint/test/extensions/test_redefined.py, pylint/test/test_regr.py, pylint/test/unittest_lint.py, pylint/test/unittest_reporting.py
- Refactor pytest fixtures to centralize definition of linter used in unit tests.
=> Refactor pytest fixtures.

pylint/checkers/python3.py, pylint/test/functional/print_always_warns.py, pylint/test/functional/print_always_warns.rc, pylint/test/functional/print_always_warns.txt, pylint/test/unittest_checker_python3.py
Frequently 2and3 code will gate some Python 3 specific code with something like:
```python
if six.PY2:
```
This PR will respect those branches.
One thing I wasn't able to do was handle `else` branches here.  e.g.:
```python
if six.PY3:
else:
```
I'd love some feedback on how I can accomplish this, but AFAICT there is no `else` node
in `astroid`.
=> Respect checks for Python 2

pylint/checkers/variables.py, pylint/test/functional/used_before_assignment_issue1081.py, pylint/test/functional/used_before_assignment_issue1081.txt
=> used-before-assignment: ignore global lookup when there's assign statement in checked scope

.travis.yml, tox.ini
This reverts commit 796b1690bebfee1fc637fcfce5d398646958435b.
Last change introduced regression with sending data to coveralls.
=> Revert "Use pytest-xdist for parallel execution of tests in travis (#1246)"

pylint/checkers/spelling.py, pylint/test/unittest_checker_spelling.py
This pull request let's pyenchant do it's thing.
- Previous skips still work(but pyenchant takes care of them)
- Skips email addresses
- Skips URLs
However, invalid characters on docstrings are also stripped by enchant thus we loose the ability to raise `invalid-characters-in-docstring`. I'll need guidance on how to proceed here.
I also would like some examples where the python literals trigger spelling errors since there's no current tests for that. My guess is that pyenchant already takes care of those for us.
=> Spelling Improvements

ChangeLog, pylint/epylint.py
The way this object is defined won't let the user modify the message
template when pylint is called from a python script. Rearranging the
order of variables on its definition prevents this behavior.
Fixes #1269
Signed-off-by: Daniela Plascencia <daniela.plascencia@linux.intel.com>
- Fixes #1269
=> epylint: corrects msg-template object

CONTRIBUTORS.txt, ChangeLog, doc/whatsnew/1.7.rst, pylint/extensions/docparams.py, pylint/test/extensions/test_check_docs.py
Add 2 different error codes for different params defined
Split param name checking in two functions, one for missing checks
and another for different names checks
Check for missing params and then check for differing params
Minor fix in type of found_argument_names [list --> set]
- Fixes #1342
=> Split missing+differing docstring param checks

pylint/reporters/__init__.py
This PR fixes an issue for users of macOS, where by default LC_CTYPE
is set to an invalid locale. See https://bugs.python.org/issue18378
further discussion on this issue.
=> Replace getdefaultlocale with getpreferredencoding

pylint/checkers/async.py, pylint/test/functional/yield_inside_async_function.rc, pylint/test/functional/yield_inside_async_function_py36.py, pylint/test/functional/yield_inside_async_function_py36.rc, pylint/test/functional/yield_inside_async_function_py36.txt
- Allow yield in async function for python3.6.
- Closes #1372.
=> Allow yield in async function for python3.6.

pylint/extensions/_check_docs_utils.py, pylint/test/extensions/test_check_docs.py
Fixes #1383
- Adding ", optional" to the end of the type of a parameter in a numpy docstring no longer makes docparams throw a missing-type-doc warning.
=> docparams now ignores "optional" specifier on parameter docs

ChangeLog, doc/development_guide/contribute.rst, doc/faq.rst
- Use correct capitalisation of PyCQA organisation in Github links
- Use current version number (1.7) in ChangeLog file
- Use readhedocs URL instead of outdated docs.pylint.org
- Avoid _here_ in links in favor of actual info on link we're pointing to (http://ux.stackexchange.com/questions/12100/why-shouldnt-we-use-words-such-as-here-and-this-in-textlinks)
=> Docs refinement

doc/faq.rst
=> FAQ: clarify that Pylint 1.7 is required when Py3.6 features are used

pylint/checkers/python3.py, pylint/checkers/typecheck.py, pylint/config.py, pylint/test/test_self.py, pylint/test/unittest_config.py, pylint/test/unittest_lint.py
https://docs.python.org/3/whatsnew/3.6.html#deprecated-python-behavior
=> Python 3.6 invalid escape sequence deprecation fixes

pylint/checkers/format.py, pylint/test/unittest_checker_format.py
Fixes #1429 
- Additional test and fix for bad-whitespace when type hint has a dot in it
=> bad-whitespace checking around dotted type hint

pylint/checkers/refactoring.py, pylint/test/functional/consider_using_enumerate.py, pylint/test/functional/consider_using_enumerate.txt
- Catch a new case in 'consider-using-enumerate': `range(0, len(iterable))`
- Includes test to this new case
Closes https://github.com/PyCQA/pylint/issues/1319
=> consider-using-enumerate: New case added

doc/user_guide/run.rst, pylint/lint.py
- Improves the help description, to indicate that multiple modules or packages are allowed.
=> Make the help accurate: multiple modules are allowed

pylint/checkers/misc.py, pylint/checkers/similar.py, pylint/checkers/spelling.py, pylint/test/functional/invalid_encoding_py27.py, pylint/test/functional/invalid_encoding_py27.rc, pylint/test/functional/invalid_encoding_py27.txt, pylint/utils.py
Resolve #1442 
* Create method for safe_decode in pylint/utils
* Write test for this test_case 'invalid_encoding2.7'
* Refactor all decode methods to safe_decode
* Add specific 'syntax-error' for this bug in checkers/misc
- Fix crash if coding with bad encoding goes after docstring
=> Fix crash if coding with bad encoding goes after docstring fix

ChangeLog, doc/whatsnew/1.8.rst, pylint/checkers/python3.py, pylint/test/unittest_checker_python3.py
In Python 2 implementing a no argument instance method `next` would implement the Iterator protocol, allowing the class to be used
with `next()` or a `for` loop.  In Python 3 this is now `__next__`.
=> Implement a Python3 warning for declaring a method `next` method that would implement the Iterator protocol in Python 2 but not in Python 3.

pylint/checkers/base.py, pylint/test/unittest_checker_base.py
Now it also emits warn on nodes:
FunctionDef, AsyncFunctionDef, ClassDef
=> Improve assign-to-new-keyword checker

pylint/checkers/stdlib.py
The inspect.getfullargspec() command was un-deprecated in Python 3.6, so it should be removed from the deprecated list.
https://docs.python.org/3/library/inspect.html#inspect.getfullargspec
- Remove getfullargspec from the 'deprecated' list
=> Un-deprecate inspect.getfullargspec

pylint/test/functional/iterable_context_py2.rc, pylint/test/functional/mapping_context_py2.py, pylint/test/functional/mapping_context_py2.rc
max_pyver=2.7 caused tests to be not run on Python 2.7.x
=> Unskip two functional tests skipped by mistake

doc/whatsnew/1.8.rst, pylint/extensions/_check_docs_utils.py, pylint/extensions/docparams.py, pylint/test/extensions/test_check_docs.py
- Properties can use the new property type syntax.
- Property setters without a docstring can use the relevant property docstring to search for missing raises documentation.
Fixes #1125
=> More intelligent property docstring checking

pylint/checkers/imports.py, pylint/test/functional/import_error.rc
=> import-error now is correctly emitted for import nodes when lower level messages are disabled

pylint/checkers/python3.py
A previous document I based this list off of was incorrect.
=> Allow importing `stat` in Python 3, Disallow `sets`

.travis.yml, pylint/test/functional/invalid_encoding_py27.rc
As I have to develop on Ubuntu Trusty occasionally, I would appreciate tests not failing there by default as they currently do. To achieve this I'd skip one test for extremely old Python versions, and add Python 2.7.6 to the Travis build matrix.
See https://travis-ci.org/gagern/pylint/jobs/253033100 for a failing Travis run using that version.
This PR is a bug report and bug fix in one. So here is the bug report part.
Run functional test suite using Python 2.7.6 as shipped by Ubuntu Trusty
Functional test `invalid_encoding_py27` fails because error is reported in line 1 not 2.
No tests failing by default, to help development. Perhaps skip that test for old versions of Python.
pylint 1.8.0, 
astroid 1.5.3
Python 2.7.6 (default, Oct 26 2016, 20:30:19) 
[GCC 4.8.4]
=> Run tests on Python 2.7.6

ChangeLog, pylint/checkers/imports.py, pylint/test/functional/disable_ungrouped_imports.py, pylint/test/functional/disable_ungrouped_imports.txt, pylint/test/functional/disable_wrong_import_order.py, pylint/test/functional/disable_wrong_import_order.txt, pylint/test/functional/disable_wrong_import_position.py
Fixes https://github.com/PyCQA/pylint/issues/1336 on `master`.
=> Optimize effect of disabling import warnings

CONTRIBUTORS.txt, ChangeLog, doc/whatsnew/1.8.rst, pylint/checkers/exceptions.py, pylint/test/functional/raising_format_tuple.py, pylint/test/functional/raising_format_tuple.txt
Bad (now causing a new warning):
*  `raise SomeError('message about %s', foo)`
*  `raise SomeError('message about {}', foo)`
Good (likely intended):
*  `raise SomeError('message about %s' % foo)`
*  `raise SomeError('message about {}'.format(foo))`
People used to `printf` in C might accidentally write a comma to separate a
message format containing `%` placeholders from the arguments to substitute,
instead of the `%` sign required to actually do the formatting and build the
error message as a single string.  But even when using `{…}` as a placeholder,
some libraries will prefer deferred evaluation for e.g. logging calls, so a
user might have a habit of using commas instead of a `str.format()` call for
those, too.  This warning points out such use cases.  It can be ignored on
projects …
=> Warn when raising an exception with a format string and some arguments

pylint/test/acceptance/test_stdlib.py, pytest.ini
It's a follow-up on discussion in #1072 comments.
One failing case on Py 3.6 found. One failing case on PyPy found.
Obviously these tests shouldn't run per check-in, but having them in source code and easily runnable may be beneficial.
Just an idea, we can think about it a little bit more.
=> Add acceptance tests

pylint/lint.py
- 
pylint always starts all jobs even when analyzing a single file #1613
=> pylint always starts all jobs even when analyzing a single file #1613

pylint/checkers/imports.py, pylint/test/input/func_w0401_disabled_in_func.py, pylint/test/messages/func_w0401_disabled.txt, pylint/test/messages/func_w0401_disabled_in_func.txt, pylint/test/messages/func_w0401_package.txt, pylint/test/test_func.py
Since commit 7df8caaa3e1995018417ac2fd87afd89be6945ba,
the "# pylint: disable=cyclic-import" statment is
respected.
One case which was not covered is the disabling of the
check for an import from inside a method/function.
Example:
File test1.py
> class B(object):
>     pass
>
> def function():
>     from . import test2  # pylint: disable=cyclic-import
>     pass
File test2.py
> from . import test1
>
> class A(object):
>     pass
Pylint wrongly reports:
Cyclic import (testfolder.test1 -> testfolder.test2) (cyclic-import)
This is due to the fact that the self._excluded_edges
dict was not filled with the imports that need to be
excluded. Passing the line number to the
self.linter.is_message_enabled() check allows to not
prematurely return due to the line number being None.
=> Do not warn for locally disabled cyclic import checks

pylint/checkers/spelling.py
`tox -e pylint` failed on my machine due to those warnings.
=> Disable no-init and old-style-class for enchant helper mocks

pylint/test/test_self.py, pylint/utils.py
makes list-like output in the 'MESSAGES CONTROL' section more
readable (one item per line).
With this PR the output of the 'disable' option looks as follows
```ini
disable=invalid-name,
missing-docstring,
too-many-lines,
import-error,
no-member,
print-statement,
parameter-unpacking,
....
```
I've restricted this improvement to the 'MESSAGES CONTROL' section, since the regular expressions in the 'BASIC' section shall not be changed.
=> more readable --generate-rcfile output

pylint/extensions/_check_docs_utils.py, pylint/test/extensions/test_check_docs.py
Currently xref is allowed only for a container type, but not for a basic type.
This pull requests extends the basic type with xref as well.
=> Allow simple xrefs for types in docstrings

ChangeLog, doc/whatsnew/1.8.rst, pylint/checkers/base.py, pylint/checkers/format.py, pylint/test/unittest_checker_format.py
Closes #574
I honestly have no idea why this extra condition was introduced in first place. A the end of the day we have no regressions and correct no-emit for reported case.
=> Fix superfluous-parens false positive for logical statements involving `in` operator

pylint/checkers/similar.py, pylint/test/unittest_utils.py, pylint/utils.py
This is part of a patch from https://github.com/asottile/future-fstrings/issues/7#issuecomment-329305973
I think this is the less controversial half of that patch, I'd be willing to write tests if this seems like a _good_ idea (don't really want to invest time otherwise!).
The tl;dr rationale is I've written a terrible hacky encoding that does some (really cool?) source rewriting -- the source it produces *is* valid and the codec produces correct results for `full_file_contents.decode(...)` and properly decodes in a simulated linewise fashion by the implemented `codecs.StreamReader`.
The codec interface requires an implementation of `StreamReader`, the `StreamReader` is designed to wrap a binary stream and give you file-like operations (`readline`, `readlines`, etc.), this makes pylint …
=> Use codecs.getreader.

ChangeLog, doc/whatsnew/1.8.rst, pylint/checkers/classes.py, pylint/checkers/format.py, pylint/checkers/imports.py, pylint/checkers/python3.py, pylint/checkers/refactoring.py, pylint/checkers/typecheck.py, pylint/checkers/utils.py, pylint/checkers/variables.py, pylint/epylint.py, pylint/extensions/_check_docs_utils.py, pylint/extensions/mccabe.py, pylint/lint.py, pylint/pyreverse/utils.py, pylint/test/functional/inconsistent_returns.py, pylint/test/functional/inconsistent_returns.txt, pylint/test/functional/lost_exception.py, pylint/test/functional/nested_blocks_issue1088.py, pylint/test/functional/nested_blocks_issue1088.txt, pylint/test/functional/no_else_return.py, pylint/test/functional/too_many_nested_blocks.py, pylint/test/functional/too_many_nested_blocks.txt, pylint/test/functional/unpacking_non_sequence.py, pylint/test/functional/useless_else_on_loop.py, pylint/test/functional/useless_else_on_loop.txt, pylint/test/functional/using_constant_test.py, pylint/test/input/func_return_yield_mix_py_33.py, pylint/utils.py
The code is quite simple. I'followed the recommendations of @AWhetter. However the most difficult part
was to determine if a function has an implicit return statement. This is done inside the recursive ``_is_node_return_ended`` function. I'm not sure it can handle all encountered cases but the associated unit test is quite extensive...
Close #1267
=> Adding a check for ``inconsistent-return-statements`` inside function or methods.

pylint/checkers/exceptions.py, pylint/test/functional/raising_format_tuple.py, pylint/test/functional/raising_format_tuple.txt
First part of #1677
Cannot reproduce another issue on current master branch.
=> Fix unhandled exception when node without a name is used as exception class

pylint/checkers/format.py, pylint/test/unittest_checker_format.py
- #1525
- #1543
Many issues and pull requests have been opened. And this is one of them.
With type hints becoming more and more popular, and 1.8 not released yet, more and more people are hitting upon the issue of bad-whitespace checking around dotted type hint.
Past issues:
pull #1229 Omit convention warnings on assignment with type hints
issue #1430 Incorrect checking of whitespace with dotted type hint
pull #1429 bad-whitespace checking around dotted type hint
Currently open issues:
issue #1525 Pylint not allowing whitespace after type hint
issue #1543 False positive "No space allowed around keyword argument assignment" when using non-trivial annotations
This PR doesn't include any new code, it simply cherry-picks a commit 2561f53 that's on master since April, into 1.7 branch.
I'm sure …
=> bad-whitespace checking around dotted type hint in pylint 1.7 (#1525, #1543)

pylint/config.py, pylint/exceptions.py, pylint/lint.py, pylint/utils.py, tox.ini
This is part of the per directory config work (#618) so this is being merged into `per_dir_config` and not master. It also isn't 100% production ready.
Fixing #972 and moving the command line parsing out of the PyLinter class is a huge change. So I'm splitting it up into smaller chunks. Although, this has still ended up being pretty big so I'll explain some of the changes here. Don't feel as though you can't make statements about the overall design, and feel free to be picky even though this is a big change.
This first chunk of work removes optparse in favour of argparse. I've also added the start of some classes that we'll eventually start using once we fully move the config parsing out of PyLinter:
* `Configuration`: This is an `argparse.Namespace` like object that will store all of the …
=> Fix 972 argparse

doc/user_guide/output.rst
Adds basic documentation for adjusting the evaluation output.
This option is important because it explains how to suppress all
output when the code is free of errors and warnings.
=> Document score section and option in output.rst

pylint/test/test_self.py
This test was failing on my local machine due to my ~/.pylintrc
=> Fix test from failing when user has ~/.pylintrc

CONTRIBUTORS.txt, ChangeLog, pylint/checkers/refactoring.py, pylint/test/functional/trailing_comma_tuple.py, pylint/test/functional/trailing_comma_tuple.txt
The prevous implementation was too conservative with looking for
previous tokens associated with assignment: It looked only
at the immediately previous token, causing 'a = (5),' to not be
caught.
Now The current implementation backtracks to the start of the line
to find an assignment substring.
Fixes issue #1713
=> Extend trailing-comma-tuple check to more complex assignments

CONTRIBUTORS.txt, ChangeLog, pylint/checkers/python3.py, pylint/test/unittest_checker_python3.py
- Do not display no-absolute-import warning multiple times per file.
=> Do not warn no-absolute-import multiple times

CONTRIBUTORS.txt, ChangeLog, doc/whatsnew/1.8.rst, pylint/checkers/stdlib.py, pylint/test/unittest_checker_stdlib.py
Shallow copy of os.environ doesn't work as people may expect. os.environ
is not a dict object but rather a proxy object, so any changes made
on the copy may have unexpected effects on os.environ
Instead of copy.copy(os.environ) method os.environ.copy() should be
used.
Message-id is: `shallow-copy-environ`
See https://bugs.python.org/issue15373 for details.
Resolves: #1301
=> WIP: New warning: shallow copy of os.environ

ChangeLog
Change log entry added in #1733 was accidentally removed in commit
996b3fb51597379ad6170056ce445f9f52da52e6 in PR #1726
Adding changelog entry back.
Fixes: #1301
=> Add back accidentally removed changelog entry

doc/exts/pylint_extensions.py, pylint/utils.py
Whilst working on the Reproducible Builds effort [0], we noticed
that pylint could not be built reproducibly.
This is due to the documentation generator iterating over the filesystem
in a nondeterminstic order and then iterating over an internal,
nondeterminstic, data structure.
This was originally filed in Debian as #883913.
[0] https://reproducible-builds.org/
[1] https://bugs.debian.org/883913
Signed-off-by: Chris Lamb <chris@chris-lamb.co.uk>
=> Make the documentation build reproducibly.

pylint/checkers/spelling.py, pylint/test/unittest_checker_spelling.py
- This is a more permissive regex which also allows digits.
=> Fix `camelCase` spelling regex.

ChangeLog, doc/whatsnew/1.8.rst, pylint/config.py, pylint/test/test_self.py
@thish has shown (#1747) that pylint takes the default rcfile even if the rcfile specified on the command line doesn't exist. It may be problematic.
This PR is a proposal to fix this.
If the rcfile specified on the command line does't exist then an IOError exception is raised.
We only check the existence of the rcfile and not is type (file or directory) because it is already taken into account in `read_config_file` method in `config.py`.
=> Pylint doesn't take anymore the default rcfile if the rcfile specified on the command line doesn't exist

doc/whatsnew/1.8.rst
The documentation specify that os.environ is a mapping object, so we should
not assume the undocumented copy() method. The recommended and simple
way to copy the os.environ is with a dict.
=> The right way was wrong, os.environ is not a dict

CONTRIBUTORS.txt, pylint/checkers/base.py, pylint/test/functional/function_redefined.py, pylint/test/functional/function_redefined.txt
- Fixed #1774 
- Adds more regression tests to make redefined testing more robust.
Maybe this can be backported to 1.8 branch as well?
=> Bug 1774: fix redefining functions that were imported

pylint/test/functional/deprecated_module_py36.py
tkinter can be unavailable in python distributions compiled without it.
Without this ignore, `pytest pylint/test/test_functional.py::test_functional` gives:
```
E           Failed: Wrong results for file "deprecated_module_py36":
E           
E           Unexpected in testdata:
E              5: import-error
```
=> Ignore import-error in deprecated_module_py36.py test

ChangeLog, doc/whatsnew/2.0.rst, pylint/checkers/refactoring.py, pylint/test/functional/inconsistent_returns.py, pylint/test/functional/inconsistent_returns.txt
In the ``_is_node_return_ended`` method (in `refactoring.py`), if the node is a ``While`` then we consider the node as return ended.
I added two unit tests, one is directly the one of @jabdoa2 in bug #1772 and the other is a slight variation where the while loop is inside an if statement.
=> While loop are considered return ended for check of ``inconsistent-return-statements`` message

ChangeLog, pylint/checkers/__init__.py, pylint/checkers/format.py, pylint/testutils.py, pylint/utils.py
Fixes #1649 
I needed to modify add_message to accommodate column offsets that do not have nodes (since bad-whitespace uses tokens).
=> Fix "Incorrect column number for whitespace conventions"

pylint/checkers/classes.py, pylint/checkers/typecheck.py, pylint/config.py, pylint/lint.py, pylint/reporters/text.py, pylint/reporters/ureports/nodes.py, pylint/utils.py, pylintrc
Ironically, Pylint's own `pylintrc` has many checks disabled. This PR enables most them. Enabling the checks globally was offset by liberalizing configurable variables (`max-lines` et al) and disabling locally.
The commits are small and independent, so it should be easy to remove them if some of the changes aren't welcome. They can be squashed later.
=> Enable pylint checks

pylint/checkers/python3.py
=> fixes zip-builtin-not-iterating false positive when used as reversed function argument

ChangeLog, pylint/checkers/refactoring.py, pylint/test/functional/stop_iteration_inside_generator.py
Fix stop-iteration-return false positive when next builtin has a default
value in a generator.
Fixes #1830
=> Fix stop-iteration-return false positive

CONTRIBUTORS.txt, ChangeLog, pylint/checkers/utils.py, pylint/test/unittest_checker_exceptions.py
Currently when pylint checks if a function is an exception, it causes an error:
```python
File "/project/.tox/py36/bin/pylint", line 11, in <module>
sys.exit(run_pylint())
File "/project/.tox/py36/lib/python3.6/site-packages/pylint/__init__.py", line 16, in run_pylint
Run(sys.argv[1:])
File "/project/.tox/py36/lib/python3.6/site-packages/pylint/lint.py", line 1347, in __init__
linter.check(args)
File "/project/.tox/py36/lib/python3.6/site-packages/pylint/lint.py", line 768, in check
self._do_check(files_or_modules)
File "/project/.tox/py36/lib/python3.6/site-packages/pylint/lint.py", line 901, in _do_check
self.check_astroid_module(ast_node, walker, rawcheckers, tokencheckers)
File "/project/.tox/py36/lib/python3.6/site-packages/pylint/lint.py", line …
```
=> Fix error on 'raise from function'.

ChangeLog, pylint/checkers/format.py, pylint/test/unittest_checker_format.py
=> Stop newlines in function parameters from raising a false positive bad-whitespace from annotations

CONTRIBUTORS.txt, ChangeLog, doc/whatsnew/2.0.rst, pylint/checkers/refactoring.py, pylint/test/functional/assigning_non_slot.py, pylint/test/functional/assigning_non_slot.txt, pylint/test/functional/inconsistent_returns.py, pylint/test/functional/return_in_init.py, pylint/test/functional/stop_iteration_inside_generator.py, pylint/test/functional/stop_iteration_inside_generator.txt, pylint/test/functional/undefined_variable_py30.py, pylint/test/functional/useless_return.py, pylint/test/functional/useless_return.txt, pylint/test/input/func_noerror_yield_return_mix.py, pylint/test/input/func_typecheck_callfunc_assigment.py
Another take on #1821 only producing messages if there is ony 1 return statement at the end of the function.
=> Add new checker useless-return

pylint/__init__.py, pylint/checkers/__init__.py, pylint/config.py, pylint/lint.py, pylint/test/test_functional.py, pylint/test/test_self.py, pylint/test/unittest_config.py, pylint/test/unittest_lint.py, pylint/test/unittest_reporters_json.py, pylint/test/unittest_reporting.py, pylint/testutils.py, pylint/utils.py
This removed the OptionsManagerMixin and OptionsProvider classes, meaning that the ConfigParser classes now handle the option parsing and the Runner organises these parsers.
New Tasks to do:
- Fix all tests (The API may keep changing so I haven't fixed anything for now.
- Figure out what API we want to give the PluginRegistry. Currently it's using a linter to pass attribute requests onto but ideally we would have a proper API on the registry which gets given to checkers and reporters. The PluginRegistry would then not need a linter instance.
- Possibly split (parts of) the message handler mixin and reports handler mixin from the linter. As I've dug into how these classes work I've realised that they all rely on each other. It's probably not required for per directory configurations, but …
=> [per_dir_config] Moved option parsing outside of linter

CONTRIBUTORS.txt, doc/development_guide/contribute.rst
- Update documents for development guide and contributing. Paths to the test folder did not include the parent folder "pylint"
=> Update contribute documentation with correct test path

pylint/lint.py, pylint/reporters/text.py, pylint/utils.py
Setting a reporter is something that's global. With PyLinters being created per file/directory in the future, it makes sense for the reporting to move elsewhere.
New tasks:
- Split up the ReportsHandlerMixin methods. The PluginRegistry needs to handle the registering of reporters, and the Runner should handle setting the runner and doing the reporting.
Closes #1899
=> [per_dir_config] Moved reporting from PyLinter

ChangeLog, doc/whatsnew/2.0.rst, pylint/checkers/typecheck.py, pylint/test/unittest_checker_typecheck.py
This is a holdover until astroid can be fixed. Astroid needs to
understand descriptors or at least raise Uninferable instead
of allowing the descriptor instance through
Close #1699
=> Suppress false-positive not-callable messages from class descriptors

pylint/lint.py, pylint/test/unittest_lint.py, pylint/testutils.py
Skipping register with no error based on type as per #1892.
=> Add check to not register same linter type twice

pylint/epylint.py
=> Fix shlex parsing error on Windows in epylint

CONTRIBUTORS.txt, ChangeLog, doc/whatsnew/2.0.rst, pylint/checkers/exceptions.py, pylint/test/functional/inconsistent_returns.py, pylint/test/functional/misplaced_bare_raise.py, pylint/test/functional/stop_iteration_inside_generator.py, pylint/test/functional/try_except_raise.py, pylint/test/functional/try_except_raise.txt
reports on except handlers where raise is the first operator in the handler body.
There are some failures from existing code which need to be examined. I'm not sure how do we want to handle some scenarios. 
The motivation behind this checker comes from a legacy code base which has a lot of
```
try:
do_something
except:
raise
```
which obviously doesn't do anything useful. 
There's also the use case where `raise` is followed by some other nodes which is also detected by unreachable. 
Then there's the scenario where we `raise ExcType()` and the edge case where we raise the same exception type as the one that has been caught in the except clause. 
Let me know how do you like this PR to evolve.
=> New error condition try-except-raise

pylint/checkers/base.py
Whilst working on the Reproducible Builds effort [0], we noticed that pylint could not be built reproducibly.
This is due to iterating over a set in a non-determinstic manner and using that in the documentation output.
This was originally filed in Debian as #894607 [1].
[0] https://reproducible-builds.org/
[1] https://bugs.debian.org/894607
Signed-off-by: Chris Lamb <lamby@debian.org>
-
=> Make the build reproducible

pylint/epylint.py
epylint overrides my pylintrc settings with it's own hardcoded values. There is no way to override them without specifying additional command line options, so I have just removed them. Now when I invoke epylint, without any arguments, my pylintrc file is honored, and the output is now identical to regular pylint.
=> Fixes erroneous default arguments to epylint

ChangeLog, doc/whatsnew/2.0.rst, pylint/test/functional/line_too_long_end_of_module.py, pylint/utils.py
This seems to break the message control from the configuration file. That's the reason the linting suddenly started to fail.
CC @hippo91 Didn't have time to check why this is happening, if you can take a look when you get a chance, that would be great.
Reverts PyCQA/pylint#2004
=> Revert "Proposal of a fix for bug #1950"

pylint/extensions/_check_docs_utils.py, pylint/test/extensions/test_check_docs.py
Fixes #1844 
- Adding ", optional" to the end of the type of a parameter in a google docstring no longer makes docparams throw a missing-type-doc warning.
=> Ignore 'optional' type specifier for google docstring

pylint/checkers/variables.py
Just like unused-argument, redefined-outer-name now also uses ignored-argument-names.
Technically this is a new feature but it should be easy to backport to 1.8 anyway.
- Fixes #1535
=> Can ignore arguments that cause redefined-outer-name

ChangeLog, doc/whatsnew/2.0.rst, pylint/checkers/design_analysis.py, pylint/checkers/utils.py, pylint/test/functional/too_few_public_methods.py, pylint/test/functional/too_few_public_methods.txt
- Enum classes do not trigger too-few-methods
- Special methods are counted as part of the public API when counting methods for too-few-methods. They are not counted towards the number of methods for too-many-methods though.
Needs backporting to 1.8
Fixes #605
=> Enum classes no longer trigger too-few-methods

ChangeLog, doc/whatsnew/2.0.rst, pylint/extensions/docparams.py, pylint/test/extensions/test_check_docs.py
Abstract methods are allowed to document returns documentation even
if the default implementation does not return something.
This is so that an abstract method can document what an implementation
should return.
Abstract methods also do not need to document that they raise a
NotImplementedError. This is because a docstring author may choose to
indicate that the method is abstract in the docstring description,
which is something that we cannot detect.
Needs backporting to 1.8
- Closes #2044
=> Relaxed docstring checks for abstract methods

CONTRIBUTORS.txt, ChangeLog, pylint/checkers/python3.py, pylint/test/unittest_checker_python3.py
Add new check py3k invalid-unicode-literal for below strings.
a = ur'foobar'
- Close #1938
=> Add new check py3k invalid-unicode-literal.

pylint/test/unittest_lint.py, pylint/test/unittest_utils.py, pylint/utils.py
I've refactored quite a lot during the implementation of #2036, this seem to be independant of the functional change required. This pull request add readability changes and better error messages for duplicated or non existing message, following the review by @AWhetter  and @PCManticore.
=> Refactor of MessagesStore

pylint/checkers/format.py, pylint/test/unittest_lint.py, pylint/utils.py
=> Refactor - MessagesStore.check_message_id(msgid)

CONTRIBUTORS.txt, ChangeLog, doc/whatsnew/2.0.rst, pylint/checkers/imports.py, pylint/test/regrtest_data/awesome_module.py, pylint/test/regrtest_data/init_wildcard/__init__.py, pylint/test/unittest_checker_imports.py
-  Skip wildcard check for `__init__.py`, since it is one of the best ways to populate packages in `__init__.py`
=>  Skip wildcard check if __init__.py, solves #2026

CONTRIBUTORS.txt, doc/whatsnew/2.0.rst, pylint/checkers/stdlib.py, pylint/test/functional/subprocess_popen_preexec_fn.py, pylint/test/functional/subprocess_popen_preexec_fn.txt, pylint/test/unittest_checker_stdlib.py
- Adds a warning when using the preexc_fn keyword argument with the subprocess.Popen constructor.
=> Warn when using subprocess.Popen preexec_fn kwarg - resolves: #1195

doc/development_guide/contribute.rst
Current markup looks a little strange...
see screenshot
This should fix it.
=> Fix weird indentation in contributing guide

doc/intro.rst, pylint/checkers/format.py
This PR does the following:
* Updates the style guide's URL, as the old link no longer works
* Changes `too-many-lines`'s message from `too much lines` to `too many lines`
* Changes a couple of `http`s to `https`es, and
* Adjusts `format.py`'s whitespace for PEP-8 (removing spaces before colons, etc.).
=> Miscellaneous copy edits

CONTRIBUTORS.txt, ChangeLog, doc/user_guide/output.rst, pylint/reporters/text.py, pylint/test/test_self.py
The default report format in `mypy`, `pydocstyle`, and other tools includes the file path so that the user of certain terminals (e.g. iTerm) can click on each warning to open that line in their editor.
For example, here is what the default `mypy` output looks like:
> framework/views/billing.py:92: error: Incompatible return value type (got "View", expected "DashboardTab")
With this new format, `pylint`output looks like:
> framework/views/dashboards.py:21:8: W0612: Unused variable 'x' (unused-variable)
Note that some editors (e.g. Sublime Text) index columns from 1, so this will place the cursor one column to the left of the warning.
cc @PCManticore
=> Includes file paths in the default report format

CONTRIBUTORS.txt, ChangeLog, pylint/checkers/logging.py, pylint/test/functional/logging_format_interpolation_py36.py, pylint/test/functional/logging_format_interpolation_py36.txt, pylint/test/functional/logging_fstring_interpolation_py36.py, pylint/test/functional/logging_fstring_interpolation_py36.rc, pylint/test/functional/logging_fstring_interpolation_py36.txt
A new check `logging-fstring-interpolation` is added.
It emits a warning when f-string is used within logging
function calls.
Closes https://github.com/PyCQA/pylint/issues/1998
=> Add a new check: `logging-fstring-interpolation`.

ChangeLog, doc/whatsnew/2.0.rst, pylint/config.py, pylint/lint.py
- Expose quiet mode to command line options with --quiet flag
- closes #1863
The quiet option is parsed in Run.preprocess_options. This was necessary due to the call order in the Run class constructor. I also moved the quiet keyword argument from OptionsManagerMixIn.__init__() to OptionsManagerMixin.read_config_file() because it wasn't used anywhere else in the class. Currently, quiet mode only manipulates the display of the config file path ("Using config file <path>").
=> Exposequietmode

CONTRIBUTORS.txt, ChangeLog, pylint/lint.py, pylint/test/test_self.py
Add a new command-line option for the use of continuous integration scripts which abort if a command returns a non-zero status code.  If the option is specified, and Pylint runs successfully, it will exit with 0 regardless of the number of lint issues detected.
Configuration errors, parse errors, and calling Pylint with invalid command-line options all still return a non-zero error code, even if `--exit-zero` is specified.
Thanks for hosting a sprint at PyCon 2018!
Resolves #2042 Provide ability to disable exit code for lint errors
=> Add `--exit-zero` option

CONTRIBUTORS.txt, ChangeLog, doc/whatsnew/2.0.rst, pylint/extensions/docparams.py, pylint/test/extensions/test_check_docs.py, pylint/test/extensions/test_check_return_docs.py
If type annotations exists on the function signature for a parameter and/or
return type then don't raise missing-type-doc and/or missing-return-type-doc.
- #2083
=> check for annotation in missing-type-doc and missing-return-type-doc

pylint/checkers/python3.py, pylint/test/unittest_checker_python3.py
=> Use last previous assignment for comprehension-escape

doc/user_guide/ide-integration.rst
- Fixed strings that were broken down in order to fit in table cells in rst and were not concatenated when rendered to HTML.
=> Fix message categories table rendering glitch

pylint/lint.py, pylint/reporters/__init__.py, pylint/reporters/json.py, pylint/reporters/text.py, pylint/utils.py
This change removes the idea of a global linter object and instead the runner now creates the pylinter only when doing the checking. The next step is to be able to make a new linter object and a new set of checkers either for each file that is run, or each time a config changes in a directory.
Closes #973
=> Runner coordination

CONTRIBUTORS.txt, ChangeLog, pylint/checkers/refactoring.py, pylint/test/functional/len_checks.py, pylint/test/functional/len_checks.txt
This patch adds lints for two more cases:
1) `if len(X) < 1:`
2) `if len(X) <= 0:`
Meaning of the both is same as `if not X`.
Signed-off-by: Matej Marusak <mmarusak@redhat.com>
-
=> `len-as-condition` recognize more cases

README.rst
I saw on Twitter that http://pylint.pycqa.org/ is the preferred url over pylint.org.
=> Update links in readme.rst to http://pylint.pycqa.org/

CONTRIBUTORS.txt, ChangeLog, doc/whatsnew/2.0.rst, pylint/checkers/base.py, pylint/test/functional/comparison_with_callable.py, pylint/test/functional/comparison_with_callable.txt
This check warn for comparison with bare callable, without calling it.
- #2082
=> Add new check 'comparison-with-callable'

pylint/checkers/base.py, pylint/checkers/design_analysis.py, pylint/checkers/exceptions.py, pylint/checkers/format.py, pylint/checkers/imports.py, pylint/checkers/logging.py, pylint/checkers/spelling.py, pylint/checkers/typecheck.py, pylint/checkers/variables.py, pylint/lint.py
A number of help strings are inconsistent in trailing periods, or
spaces after them in the middle of text, or add a large amount of
whitespace by using \ to continue the string.  Standardize a lot
of these so all help messages end in a period and there is normal
whitespace in the middle.
The tests don't show any regressions, and pylint is clean.
I think I'm supposed to regenerate the pylintrc & man pages, but
I haven't been able to figure out how to do that.
=> standardize help strings a bit

ChangeLog, pylint/checkers/refactoring.py, pylint/test/functional/consider_using_dict_comprehension.py, pylint/test/functional/consider_using_dict_comprehension.txt
As discussed in #2194 this adds the new checker for using old style dict initializations with list comprehensions instead of dict-comprehensions.
How is this for a first version?
I think it could use some more tests, but could not think of any more at the moment :smile: 
Anyone see any edge-cases?
=> enhancement: add new checker 'consider-using-dict-comprehension'

ChangeLog, doc/whatsnew/2.0.rst, pylint/checkers/format.py, pylint/test/unittest_checker_format.py
Prevents false-positive bad-whitespace message
Close #1992
=> Acknowledge that ellipses are allowed in typing annotations

pylint/lint.py, pylint/test/unittest_lint.py
Each ChildLinter receives a file path and instantiates a linter to check
that file. As such, all files are arguments to child linters in parallel
mode. Therefore, the check for should_analyze_file must happen in the
parent linter, where knowledge of the original arguments is available.
Expand the custom should_analyze_file test to exercise parallel mode.
Close #1885
=> Filter with should_analyze_file in parallel mode

ChangeLog, doc/whatsnew/2.0.rst, pylint/checkers/utils.py, pylint/checkers/variables.py, pylint/test/functional/cellvar_escaping_loop.py, pylint/test/functional/cellvar_escaping_loop.txt
The NameConsumer to_consume frame needed to be backed out by one so that
for lambda bound default argument variables (closure) could consume the
name in a higher scope (just like function default arguments)
Close #1921
Close #1552
Close #1099
Close #210
=> Fix false positive unused-variable in lambda default arguments

CONTRIBUTORS.txt, ChangeLog, pylint/checkers/base.py, pylint/test/functional/namePresetCamelCase.txt, pylint/test/functional/name_preset_snake_case.txt, pylint/test/functional/name_styles.py, pylint/test/functional/name_styles.txt, pylintrc
- Fixed false positive check for invalid name "doesn't conform to snake_case naming style" for class methods and attributes. 
Removed max length in regex for class method and attribute. Tests and docs updated according to [this PR](https://github.com/PyCQA/pylint/pull/2149)
See [#2047](https://github.com/PyCQA/pylint/issues/2047)
=> False positive snake case waring

ChangeLog, pylint/checkers/format.py, pylint/test/unittest_checker_format.py
The format checker was ignoring block opener tokens on the first line
because the encoding token is the always the first value of the first line.
Close #2281
=> Fix format checker inconsistency for start of first line

CONTRIBUTORS.txt, ChangeLog, pylint/checkers/exceptions.py
This changes the `try-accept-raise` message from `E0705` to `W0706` to be more in line with the way the rest of the messages are organized.
Fixes #2323
=> Demote 'try-except-raise' from an error to a warning

.travis.yml
Tests fail, but I don't think it's the fault of this PR, but just maybe a real issue this change has revealed with 3.7.0.
=> Use final 3.7 in Travis

ChangeLog, pylint/extensions/_check_docs_utils.py, pylint/extensions/docparams.py
Close #1169
I'll backport this to 1.9 as well.
=> Can specify a default docstring type for when the check cannot guess the type

pylint/lint.py, pylint/test/test_self.py
- `--list-msgs` works again with 0 arguments.
=> Fix --list-msgs

doc/faq.rst
- Corrects a sentence in the FAQ which seemed to imply that Pylint works with any version of Python 2.7 or greater.  With Pylint 2.0+ being 3.4+ only, this was misleading & confusing.
=> Correct sentence in FAQ around Python version support

pylint/checkers/misc.py, pylint/test/functional/fixme.py
- Simplify fixme regex
- Require word boundary after fixme notes
- Escape regex metachars in configured fixme note tags
=> Fixme improvements

pylint/checkers/refactoring.py
Calling nodes_of_class without a skip_klass and then filtering
afterwards is slightly inefficient, but more importantly it's an
unusual use of the function (this is the only example in Pylint where
Return nodes are extracted without skipping FunctionDef).
=> Change refactoring nodes_of_class call to use skip_klass

pylint/lint.py, pylint/utils.py
As the title says, PyLinter objects are now created on a per file basis. There's possibly some optimisation to be done here. Really linters need to be created only once per directory because a configuration file will affect a directory and not individual files.
=> Linters are created per file

doc/user_guide/ide-integration.rst
Does just what it says on the tin; the links to both the Spyder IDE site and docs are many years out of date, so as part of spyder-ide/spyder-docs#39 this updates them as well as adding a brief line about how to actually access Pylint (as the other IDEs have). I made this off ``master`` like most other PRs, but if there's any chance this could get backported to at least the 2.0.1 docs if not older that would be great since the links are so out of date (but if not, I understand).
As a minor note, the relevant sentence is a pretty clear comma splice as is, but I didn't fix that here (i.e. by changing ``,`` to ``;``) for consistancy's sake with the other list entries that also all have the same problem.
I didn't create an issue or changelog entry since this was such a trivial and ephemeral …
=> Update Spyder links and short description in IDE integration doc

pylint/checkers/exceptions.py, pylint/test/functional/try_except_raise.py, pylint/test/functional/try_except_raise.txt
pylint crashes due to safe_infer, in case of bare except.
- #2352
=> consider bare except also for try-except-raise

doc/intro.rst
If PyChecker is the only one in the list that is defuct, this clarifies that. Otherwise it looks like you're listing all of them as defunct.
-
=> intro.rst, pychecker the only one defunct?

CONTRIBUTORS.txt, examples/pylintrc, man/pylint.1, pylint/checkers/format.py
- Removed a double space that was generated in "Number of spaces of indent required inside a hanging  or continued line" and updated man page and pylintrc example accordingly.
This bothered me unreasonably much.
( Not sure if this really warrants a contributor entry but the guidelines told me to, so. :) )
=> No extra space

ChangeLog, doc/whatsnew/2.1.rst, pylint/checkers/base.py, pylint/checkers/utils.py, pylint/test/extensions/data/docstring.py, pylint/test/functional/docstrings.py, pylint/test/functional/function_redefined.py, pylint/test/functional/init_not_called.py, pylint/test/functional/invalid_sequence_index.py, pylint/test/functional/invalid_slice_index.py, pylint/test/functional/keyword_arg_before_vararg.py, pylint/test/functional/line_too_long.py, pylint/test/functional/name_styles.py, pylint/test/functional/names_in__all__.py, pylint/test/functional/try_except_raise.py, pylint/test/functional/unnecessary_pass.py, pylint/test/functional/unnecessary_pass.txt, pylint/test/input/func_bug113231.py, pylint/test/input/func_noerror_inner_classes.py, pylint/test/input/func_w0623_py30.py, pylint/test/messages/func_w0623_py30.txt
`unnecessary-pass` is now also emitted when a function or class contains
only docstring and pass statement, in which case, docstring is enough for
empty definition.
- #2208
=> add new case for `unnecessary-pass`

ChangeLog, doc/whatsnew/2.2.rst, pylint/checkers/imports.py, pylint/test/functional/useless-import-alias.py, pylint/test/functional/useless-import-alias.txt
=> Ignore import x.y.z as z cases for checker `useless-import-alias`

.travis.yml, pylint/__pkginfo__.py, pylint/checkers/__init__.py, pylint/checkers/base.py, pylint/checkers/python3.py, pylint/checkers/raw_metrics.py, pylint/checkers/similar.py, pylint/checkers/spelling.py, pylint/checkers/utils.py, pylint/checkers/variables.py, pylint/config.py, pylint/lint.py, pylint/pyreverse/main.py, pylint/utils.py, tox.ini
=> annotations changes on new branch.

ChangeLog, doc/whatsnew/2.2.rst, pylint/checkers/variables.py, pylint/test/functional/unused_variable.py, pylint/test/functional/unused_variable.txt, pylint/test/messages/func_w0612.txt
- [ x ] Add yourself to CONTRIBUTORS if you are a new contributor.
- [ x ] Add a ChangeLog entry describing what your PR does.
- [ x ] If it's a new feature or an important bug fix, add a What's New entry in `doc/whatsnew/<current release.rst>`.
- [ x ] Write a good description on what the PR does.
``pylint`` used to emit a ``unused-variable`` error if unused import was found in the function. Now instead of
``unused-variable``, ``unused-import`` is emitted.
|   | Type |
=> emit unused-import instead of unused-variable if the import in is function

doc/user_guide/output.rst
Added missing `info` type to the output documentation.
|   | Type |
Closes #2466
=> Added missin Info type to doc

CONTRIBUTORS.txt, ChangeLog, doc/whatsnew/2.2.rst, pylint/checkers/logging.py, pylint/checkers/strings.py, pylint/checkers/utils.py, pylint/test/unittest_checker_strings.py
This commit detects situations when string format specifier does not match argument type as e.g. in
```
"%d" % '1'
```
I've been personally bitten by this several times so decided that this check deserves some attention.
I'll be happy to update/fix the patch if needed.
|   | Type |
=> Added checker for format string type mismatches.

CONTRIBUTORS.txt, ChangeLog, examples/pylintrc, pylint/checkers/variables.py, pylintrc
Fix grammar errors in pylintrc files and CONTRIBUTORS.txt.
|   | Type |
NONE
=> Grammar fixes to docs

CONTRIBUTORS.txt, ChangeLog, pylint/checkers/format.py
https://github.com/python/cpython/commit/c4ef4896eac86a6759901c8546e26de4695a1389
(not yet in any released version, but it's been backported to all
versions of Python in git, even 2.7!) changed the behaviour in the
stdlib's tokenize module to emit a synthetic NEWLINE token even if the
file does not end with a newline. This was causing a spurious
"mixed-line-endings" warning to be emitted, but luckily the synthetic
token is easy to test for (the token text is "").
|   | Type |
=> fix compatibility with unreleased changes to stdlib tokenizer

CONTRIBUTORS.txt, ChangeLog, doc/whatsnew/2.2.rst, pylint/checkers/base.py, pylint/checkers/classes.py, pylint/checkers/design_analysis.py, pylint/checkers/exceptions.py, pylint/checkers/format.py, pylint/checkers/imports.py, pylint/checkers/misc.py, pylint/checkers/newstyle.py, pylint/checkers/python3.py, pylint/checkers/refactoring.py, pylint/checkers/stdlib.py, pylint/checkers/strings.py, pylint/checkers/typecheck.py, pylint/checkers/variables.py, pylint/lint.py, pylint/test/functional/bad_continuation.py, pylint/test/functional/implicit_str_concat_in_sequence.py, pylint/test/functional/implicit_str_concat_in_sequence.txt, pylint/test/unittest_checker_strings.py
- Adds a new warning. Example of code that would raise it:
```
TEST_LIST = ('a', 'b' 'c')
```
Message:
```
String literals are implicitly concatenated in a comma-separated list : maybe a comma is missing ?
```
=> Adding implicit-str-concat-in-sequence check

CONTRIBUTORS.txt, ChangeLog, pylint/checkers/base.py, pylint/test/functional/literal_comparison.py, pylint/test/functional/literal_comparison.txt
Fixed literal-comparison for the case of 0 and 1
Prior to this commit literal-comparison did not fire for the following
comparisons
x is 0
x is 1
due to a subtle bug in the checker implementation. The skip condition
in the ``ComparisonChecker._check_literal_comparison`` was
literal.value in (True, False, None)
which holds for True/False/None _as well as_ 0 and 1, since 0 == False
and 1 == True.
|   | Type |
|  | :scroll: Docs |
N/A
=> Fixed literal-comparison for the case of 0 and 1

ChangeLog, pylint/checkers/utils.py, pylint/test/unittest_checker_variables.py
Remove unnecessary break in checker utils for lambdas causing parent lambdas to be ignored.
Close #760
Bugfix backport
|   | Type |
Backport of #760 fix, issue reported as #2595
=> Fix false-postive undefined-variable in nested lambda. (#2274)

CONTRIBUTORS.txt, pylint/checkers/python3.py, pylint/test/unittest_checker_python3.py
Currently pylint gets false-positive error (zip-builtin-not-iterating) on a line containing `OrderedDict(zip(...))`, even though OrderedDict is in `collections` and accepts iterator passed to it. This is very similar to following resolved issue https://github.com/PyCQA/pylint/issues/1803 with `reversed`, so the fix is the same, add `OrderedDict` to `_ACCEPTS_ITERATOR`
|   | Type |
=> Fix zip-builtin-not-iterating false positive with OrderedDict

CONTRIBUTORS.txt, pylint/checkers/typecheck.py, pylint/test/functional/iterable_context_py36.py
This PR fixes #2637 by adding a missing a `check_async` parameter when checking async comprehensions. It also adds a new test for all the async comprehensions.
|   | Type |
Closes #2637
=> Fix false positive Non-iterable value with async comprehensions

ChangeLog, pylint/checkers/refactoring.py, pylint/config.py, pylint/test/functional/no_else_raise.py, pylint/test/functional/no_else_raise.txt
Add ``no-else-raise`` warning for else statements that are unnecessary due to a raise statement within the previous if statement.  Added as R1720.
Fixed up ChangeLog comments from previous submit; that submit was for 'return', not 'raise'.
|   | Type |
Closes #2558
=> Add ``no-else-raise`` warning (R1720)

pylint/checkers/format.py, pylint/lint.py, pylint/test/unittest_lint.py, pylint/test/unittest_utils.py, pylint/utils.py
Work in progress of the refactor for #2036 
In order to see what still need to be done.
=> Refactor of MessageStore for multiple old message

CONTRIBUTORS.txt, ChangeLog, doc/how_tos/plugins.rst, pylint/lint.py, pylint/test/regrtest_data/dummy_plugin/dummy_conf_plugin.py, pylint/test/unittest_lint.py
- [✓] Add yourself to CONTRIBUTORS if you are a new contributor.
- [✓] Add a ChangeLog entry describing what your PR does.
- [✓] If it's a new feature or an important bug fix, add a What's New entry in `doc/whatsnew/<current release.rst>`.
- [✓] Write a good description on what the PR does.
Added ``load_configuration()`` hook for plugins.
New optional hook for plugins is added: ``load_configuration()``. This hook is called by pylint after configuration is loaded to prevent against overwriting plugin specific configuration via user-based configuration. Plugins are supposed to adjust configuration e.g. by extending ``good_names`` or extending ``black_list``, etc...
|   | Type |
| ✓ | :bug: Bug fix  |
| ✓ | :sparkles: New feature |
|    | :hammer: …
=> Load plugin configuration hook

ChangeLog, pylint/extensions/_check_docs_utils.py, pylint/extensions/docparams.py, pylint/test/extensions/test_check_raise_docs.py
Updated checking of missing Raises to check exceptions that have
absolute paths.
Close #1502
This PR checks that the 'Raises' docstring matches the actual exceptions raised.  As suggested in #1502, it does a string-based comparison on the class name only since there's no straightforward mechanism to get an astroid NODE for the text in the 'Raises' clause.
If this PR is accepted then there should be (at least) two other issues opened:
1. missing-raise-doc warnings don't correctly check the fully qualified class names.
2. The syntax for what's allowed as the exception name in the Raises portion of the docstring should be updated to reflect usage; at minimum '~' should be allowed.
|   | Type |
Closes #1502
=> Fix missing-raises-doc false positive (W9006)

pylint/checkers/__init__.py
Hi,
I was using `BaseTokenChecker` when my IDE complained it wasn't in the `__init__`'s `__all__` variable. Any reason for not having it there? Learned about `BaseTokenChecker` after finding it in [another checker that uses it too](https://github.com/PyCQA/pylint/blob/master/pylint/extensions/check_elif.py).
Cheers
Bruno
|   | Type |
=> Expose/export BaseTokenChecker in __all__ as well?

CONTRIBUTORS.txt, ChangeLog, pylint/lint.py
Avoid popping __main__ when using multiple jobs.
|   | Type |
Closes #2689
=> avoid popping __main__

ChangeLog, pylint/checkers/strings.py, pylint/test/functional/implicit_str_concat_in_sequence_multiline.py, pylint/test/functional/implicit_str_concat_in_sequence_multiline.rc, pylint/test/functional/implicit_str_concat_in_sequence_multiline.txt
Adding the option discussed in https://github.com/PyCQA/pylint/pull/1655
=> Add a new option 'check-str-concat-over-line-jumps' to check 'implicit-str-concat-in-sequence'

CONTRIBUTORS.txt, ChangeLog, pylint/checkers/classes.py, pylint/checkers/typecheck.py, pylint/checkers/utils.py, pylint/test/functional/no_self_argument_py37.py, pylint/test/functional/no_self_argument_py37.rc, pylint/test/functional/no_self_argument_py37.txt, pylint/test/functional/unsubscriptable_value_py37.py, pylint/test/functional/unsubscriptable_value_py37.rc, pylint/test/functional/unsubscriptable_value_py37.txt
Take into account `__class_getitem__` from [PEP 560](https://www.python.org/dev/peps/pep-0560/) and fixes some false positives for `no-self-argument` and `unsubscriptable-object`.
|   | Type |
Closes #2416
=> Take into account __class_getitem__ from PEP 560

CONTRIBUTORS.txt, ChangeLog, pylint/checkers/logging.py, pylint/checkers/utils.py, pylint/test/unittest_checker_logging.py
The number of arguments was not handled properly, leading to an always successful check. See new tests for specific cases this fixes.
|   | Type |
=> Fixes for linting of new style logging format.

CONTRIBUTORS.txt, ChangeLog, pylint/checkers/typecheck.py, pylint/test/unittest_checker_typecheck.py
When the return type for a property is uninferable, it should not emit `not-callable`.
|   | Type |
=> Fix not-callable false positive on uninferable property

CONTRIBUTORS.txt, ChangeLog, pylint/checkers/base.py, pylint/test/functional/useless_else_on_loop.py, pylint/test/functional/useless_else_on_loop.txt
When break is deep in the else of an inner loop, W0120 was raised by mistake:
```python
for i in range(10):
while False:
pass
else:
if i > 2:
break
else:
print('else')
```
```
test.py:7:0: W0120: Else clause on loop without a break statement (useless-else-on-loop)
```
This PR fixed this issue.
|   | Type |
N/A
=> Fix bug in W0120 with break deep in else of inner loop

pylint/__pkginfo__.py
Pylint currently specifies unbounded versions of its dependencies. Assuming semver-compliant dependencies, this is dangerous because from one day to the next, your users can end up transitively picking up a breaking version of your dependencies. (This just happened to me [via astroid](PyCQA/astroid#651).\*)
This pins your dependencies within non-breaking version ranges to hopefully protect your users from breaking this way.
\* The fact that astroid's minor version bump was a breaking change goes to show this isn't foolproof, but it's strictly an improvement over the status quo of having no bound whatsoever.
=> Pin dependencies to non-breaking version ranges

doc/whatsnew/2.3.rst
"upports" -> "supports"
|   | Type |
=> Fix trivial typo in 2.3.rst

CONTRIBUTORS.txt, ChangeLog, pylint/pyreverse/writer.py, pylint/test/data/classes_No_Name.dot
When generating a dot file with pyreverse, the method arguments are not utilized.
This pull request will fix this issue.
|   | Type |
Closes #2139
=> Added method arguments to the pyreverse dot file writer

CONTRIBUTORS.txt, ChangeLog, doc/whatsnew/2.3.rst, pylint/exceptions.py, pylint/lint.py, pylint/test/test_self.py
First of all thx @cpitclaudel for starting with the first draft (#1189) of the Read-from-stdin feature.
This PR is based on the inital PR by @cpitclaudel and tries to incorporate the comment by @PCManticore  from #1189. I would like to know from @PCManticore if this PR now goes into the right direction.
I tested this PR by using the following command:
```
cat examples/custom_raw.py | ./bin/pylint --from-stdin custom_raw.py 
```
Closes: #1187
|   | Type |
=> Add support for reading from stdin

pylint/__pkginfo__.py
Make sure the master branch is tagged as a development version (`2.4.0-dev0` in this case) so that it is not mistaken for an official release.
Also modify the version string logic to avoid misinterpreting development version 0 as an official release (since 0 == False) by enforcing `dev_version = None` for non-development versions.
|   | Type |
=> Set version to 2.4.0-dev0

pylint/checkers/variables.py, pylint/test/functional/unused_import.py, pylint/test/functional/unused_import.txt
This PR fixes a minor bug whereby importing multiple packages in the same `import` statement resulted in an incorrect warning regarding unused imports.  
Given the following input:
```
import re, os.path
print(os.path.exists("/"))
```
pylint output was:
```
eg.py:1:0: C0410: Multiple imports on one line (re, os.path) (multiple-imports)
eg.py:1:0: W0611: Unused import re (unused-import)
eg.py:1:0: W0611: Unused import os.path (unused-import)
```
The third line above regarding unused os.path is incorrect; this PR fixes that incorrect attribution.
|   | Type |
=> Fix misattribution of `unused import`

CONTRIBUTORS.txt, ChangeLog, doc/whatsnew/2.4.rst, pylint/checkers/refactoring.py, pylint/test/functional/len_checks.py, pylint/test/functional/len_checks.txt
This PR reduce the scope of len-as-condition to only care when a `len(SEQUENCE)` call is made without an explicit comparison. As stated in PEP8:
```
For sequences, (strings, lists, tuples), use the fact that empty sequences are false.
```
It also changes the checker's message and description to:
```
Do not use `len(SEQUENCE)` without comparison to determine if a sequence is empty
```
```
Used when Pylint detects that len(sequence) is being used without explicit comparison inside a condition to determine if a sequence is empty. Instead of coercing the length to a boolean, either rely on the fact that empty sequences are false or compare the length to a scalar.
```
|   | Type |
Closes #2684
=> Make ``len-as-condition`` only fire when a ``len(x)`` call is made without an explicit comparison

CONTRIBUTORS.txt, ChangeLog, doc/whatsnew/2.4.rst, pylint/checkers/imports.py, pylint/test/functional/disable_ungrouped_imports.py, pylint/test/functional/disable_wrong_import_order.py, pylint/test/functional/ungrouped_imports.py, pylint/test/functional/ungrouped_imports_isort_compatible.py
C0412 and isort are incompatible when there is a mix of from x import y and import x.  See #2806 for details.
|   | Type |
Closes #2806
=> Feat - Makes C0412 (ungrouped-imports) compatible with isort

doc/conf.py
The "last updated" date was displaying as "None", which we can fix
by uncommenting `html_last_updated_fmt` in the sphinx configuration.
Current (taken from ReadTheDocs):
Proposed (generated locally):
|   | Type |
=> Fix last updated date in sphinx documentation

CONTRIBUTORS.txt, ChangeLog, pylint/checkers/similar.py, pylint/test/input/similar1, pylint/test/input/similar2, pylint/test/unittest_checker_similar.py
Raw docstrings are not ignored inside Similarities checker even when docstrings are ignored. This PR addresses this issue:
- raw docstring was added to the condition inside `pylint.checkers.similar.stripped_lines` for ignoring docstrings
- existing tests were modified to check for raw docstrings
|   | Type |
Closes #2829
=> Ignore raw docstrings in Similarities check with `ignore-docstring=yes`

CONTRIBUTORS.txt, ChangeLog, doc/whatsnew/2.4.rst, pylint/extensions/_check_docs_utils.py, pylint/test/extensions/test_check_return_docs.py
This PR fixes a minor bug, which causes a docstring which should pass to fail. This new test is captured in `/pylint/test/extensions/test_check_return_docs.py::test_find_numpy_returns_with_of`.
A docstring of the following form should pass (see https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_numpy.html, search for ':obj:`list` of :obj:`str`')
```python
def my_func(self):
"""This is a docstring.
Returns
-------
:obj:`list` of :obj:`str`
List of strings
"""
return ["hi", "bye"] #@
```
But currently fails on master with 'W9011: Missing return documentation (missing-return-doc)' error.
|   | Type |
=> Add 'of' to GoogleDocstring multiple type

CONTRIBUTORS.txt, ChangeLog, pylint/extensions/broad_try_clause.py, pylint/test/extensions/data/broad_try_clause.py, pylint/test/extensions/test_broad_try_clause.py
Add an extension checker (``pylint.extensions.broad_try_clause``) that enforces a configurable maximum number of statements inside of a ``try`` clause. This facilitates enforcing PEP 8's guidelines about try/except statements and the amount of code in the try clause: "Additionally, for all try/except clauses, limit the try clause to the absolute minimum amount of code necessary. Again, this avoids masking bugs."
|   | Type |
Closes #2877
=> Add broad try clause extension.

.pre-commit-config.yaml, pylint/checkers/python3.py, pylint/test/unittest_checker_python3.py
`old-division` will now only fire for:
- `int / int`
- `unknown / int`
- `int / unknown`
- `unknown / unknown`
|   | Type |
Resolves #2887
=> fix old-division check for int(...)

CONTRIBUTORS.txt, ChangeLog, pylint/checkers/typecheck.py, pylint/test/unittest_checker_typecheck.py
When you run pylint against this file
```python
def get_num(n):
return 2 * n
get_num(10)()
```
you will get a crash:
```
$ pylint minimal.py
File "XXX/code/pylint/.venv/bin/pylint", line 7, in <module>
exec(compile(f.read(), __file__, 'exec'))
File "XXX/code/pylint/bin/pylint", line 4, in <module>
run_pylint()
File "XXX/code/pylint/pylint/__init__.py", line 20, in run_pylint
Run(sys.argv[1:])
File "XXX/code/pylint/pylint/lint.py", line 1684, in __init__
linter.check(args)
File "XXX/code/pylint/pylint/lint.py", line 969, in check
self._do_check(files_or_modules)
File "XXX/code/pylint/pylint/lint.py", line 1131, in _do_check
self.check_astroid_module(ast_node, walker, rawcheckers, tokencheckers)
File "XXX/code/pylint/pylint/lint.py", line 1214, in …
```
=> Fix crash in callable check

ChangeLog, pylint/checkers/variables.py, pylint/test/functional/nested_func_defined_in_loop.py
This fixes the case described in the original issue where `undefined-loop-variable` was raised when a function defined in a loop uses a variable defined by the same loop.
|   | Type |
Closes #202
=> Fixed false positive for `undefined-loop-variable`

ChangeLog, pylint/lint.py, pylint/test/functional/pragma_after_backslash.py
As described in the original issue, pragmas on their own line after a backslash were getting ignored. This fixes that so that a pragma comment affects the whole logical line, and not just the physical line.
|   | Type |
Closes #199
=> Fixed pragmas on their own line after a backlash being ignored

ChangeLog, doc/whatsnew/2.4.rst, pylint/checkers/typecheck.py, pylint/test/functional/arguments.py, pylint/test/functional/arguments.rc
This adds a new option `function_mutators` that allows `too-many-function-args`, `unexpected-keyword-arg`, and `no-value-for-parameter` to not get raised for functions that are decorated with a decorator mentioned in `function_mutators`.
I figured it would be too difficult to try and infer what a decorator was doing so this seemed like the best solution, even though it means that there will be cases where a function is called with incorrect arguments will be missed by pylint when the function is decorated with a mutator decorator.
|   | Type |
Close #259
=> Can choose decorators that mutate a function's signature

ChangeLog, pylint/checkers/base.py, pylint/checkers/utils.py, pylint/checkers/variables.py, pylint/test/functional/typing_use.py, pylint/test/functional/typing_use.rc, pylint/test/functional/typing_use.txt
This change fixes `unused-argument` and `function-redefined` getting raised for functions decorated with `typing.overload`.
`unused-argument` ignores these functions altogether. `function-redefined` does not treat them as actual definitions, both when checking the node itself and when looking for duplicate definition nodes.
|   | Type |
Close #1581
=> Fixed false positives for function stubs

pylint/config.py
Fixes new errors emitted by mypy 0.710:
```
pylint/checkers/similar.py:295: error: Incompatible types in assignment (expression has type "Tuple[Tuple[str, Dict[str, object]], Tuple[str, Dict[str, object]], Tuple[str, Dict[str, object]], Tuple[str, Dict[str, object]]]", base class "OptionsProviderMixIn" defined the type as "Tuple[]")
pylint/checkers/strings.py:577: error: Incompatible types in assignment (expression has type "Tuple[Tuple[str, Dict[str, object]]]", base class "OptionsProviderMixIn" defined the type as "Tuple[]")
pylint/checkers/spelling.py:178: error: Incompatible types in assignment (expression has type "Tuple[Tuple[str, Dict[str, Sequence[str]]], Tuple[str, Dict[str, str]], Tuple[str, Dict[str, str]], Tuple[str, Dict[str, str]], Tuple[str, Dict[str, object]]]", base class …
```
=> Fix mypy 0.710 errors

CONTRIBUTORS.txt, ChangeLog, examples/pylintrc, pylint/checkers/classes.py, pylintrc, tests/functional/attribute_defined_outside_init.py
Currently ``astroid`` seems to not support dataclass in a way that would allow to still raise the ``attribute-defined-outside-init`` if attribute is defined in ``__post_init__`` in a class that is not dataclass. I think it is reasonable to add ``__post_init__`` into ``defining-attr-methods``, especially that the ``setUp`` method is already there and pylint doesn't check if it is ``TestCase`` class.
|   | Type |
Closes #2581
=> Fix - do not raise `attribute-defined-outside-init` for `__post_init__`

tests/test_self.py
Trying to see if this fixes AppVeyor.
=> Escape the clean path before normalizing to slashes

ChangeLog, doc/whatsnew/2.4.rst, pylint/checkers/refactoring.py, tests/functional/cellvar_escaping_loop.py, tests/functional/consider_iterating_dictionary.py, tests/functional/consider_using_set_comprehension.py, tests/functional/defined_and_used_on_same_line.py, tests/functional/iterable_context.py, tests/functional/iterable_context_py36.py, tests/functional/name_styles.py, tests/functional/star_needs_assignment_target_py35.py, tests/functional/statement_without_effect.py, tests/functional/unnecessary_comprehension.py, tests/functional/unnecessary_comprehension.txt, tests/functional/unsubscriptable_value.py, tests/functional/unsupported_assignment_operation.py, tests/functional/unsupported_delete_operation.py, tests/functional/using_constant_test.py
Add a new checker "unnecessary-comprehension" (See #2905)
|   | Type |
Closes #2905
=> Add new checker (unnecessary-comprehension) (close #2905)

.isort.cfg, ChangeLog, doc/whatsnew/2.4.rst, pylint/checkers/base.py, tests/functional/self_assigning_variable.py, tests/functional/self_assigning_variable.txt, tests/functional/unused_import.py
Added a new check, ``self-assigning-variable``
This check is emitted when we detect that a variable is assigned to itself, which might indicate a potential bug in the code application.
|   | Type |
Closes https://github.com/PyCQA/pylint/issues/2930
=> Add a new check for self assigning variable

.isort.cfg, .pre-commit-config.yaml, doc/conf.py, tests/extensions/test_bad_builtin.py, tests/extensions/test_check_docs.py, tests/extensions/test_check_docs_utils.py, tests/extensions/test_check_mccabe.py, tests/extensions/test_check_raise_docs.py, tests/extensions/test_check_return_docs.py, tests/extensions/test_check_yields_docs.py, tests/extensions/test_comparetozero.py, tests/extensions/test_docstyle.py, tests/extensions/test_elseif_used.py, tests/extensions/test_emptystring.py, tests/extensions/test_overlapping_exceptions.py, tests/test_functional.py
This change the exclusion filter in the `pre-commit` configuration and the `isort` configuration, so that code tests files are formatted automatically but not fixtures and data file used in tests. Also, format code files without other any modifications to them. This bug affected pylint developpers and was probably caused by [the commit where we moved tests](https://github.com/PyCQA/pylint/commit/33b8185a455c1686d038258697bb93005f2441c2)
|   | Type |
I opened #3017 initially (I'm just modifying `test_functional.py`), but looking at the excludes, there was a little more to do than I initially thought.
=> Fix black and isort excludes in pre-commit then apply black

CONTRIBUTORS.txt, ChangeLog, pylint/lint.py, tests/unittest_lint.py
Fix the "statement" values in the PyLinter's stats reports by module.
Before, the PyLinter class initialized the stats['by_module'][modname]["statement"] attribute to 0 (initialized in the **PyLinter.set_current_module** method). But it was never updated after each module was checked. This pull request fix that issue. 
Having the number of statements by module, in addition to the number of other warnings, may be used for example to compute an evaluation note for each module during a post-processing of the output.
|   | Type |
=> Fix number of statements in by_module stats

pylint/lint.py, pylint/message/__init__.py, pylint/message/message_definition.py, pylint/message/message_handler_mix_in.py, pylint/message/message_store.py, tests/message/unittest_message_definition.py, tests/message/unittest_message_store.py
This fixes some minor naming problem and add unit tests for MessageDefinition to achieve better coverage without functional test. Adding unit tests also permitted to realise that add_message was not used anywhere but in tests.
|   | Type |
Smaller merge request to make #2992 easier to review.
=> Add unittests for MessageDefinition

pylint/message/message_handler_mix_in.py, pylint/utils/__init__.py, pylint/utils/utils.py
`category_id()` in pylint.utils is used only once in pylint.message, so without it pylint is simpler to understand. (less imports and code in pylint.utils and the possibility to see what is done directly in pylint.message without going elsewhere).
|   | Type |
=> Refactor `pylint.utils.category_id()` that is used one time only

CONTRIBUTORS.txt, ChangeLog, pylint/checkers/base.py, tests/functional/assert_on_tuple.txt
Change the description of W0199 to refer to _2-item-tuple_ instead of _2-uple_.
This makes it more-clear what the problem is and I think is easier to understand for non-native-speakers as it does not rely on the pronounciation of _two_.
|   | Type |
=> W0199: Change description to use the term 2-item-tuple

pylint/lint.py, pylint/message/__init__.py, pylint/message/message_definition_store.py, pylint/message/message_handler_mix_in.py, tests/message/unittest_message.py, tests/message/unittest_message_definition_store.py
It rename `MessageStore` to `MessageDefinitionStore` because we anticipate to have a `MessageIdStore` later. A lot of commits are impossible to isolate if this file is not renamed on the master branch.
|   | Type |
Next step in order to make #2992 easier to review.
=> Rename MessageStore to MessageDefinitionStore

CONTRIBUTORS.txt, ChangeLog, pylint/extensions/_check_docs_utils.py, tests/extensions/test_check_raise_docs.py
For context see https://github.com/PyCQA/pylint/issues/1502#issuecomment-448535694
In this issue it was agreed that `re.error`, `~re.error` and `!re.error` would all be accepted. However, it's also common in Sphinx to use a `.` prefix for local references.
|   | Type |
=> Allow a `.` as a prefix for Sphinx name resolution.

pylint/message/message_definition.py, pylint/message/message_definition_store.py, pylint/message/message_handler_mix_in.py
Remove a mechanism that was handling symbol equal to None. It does not happens in the current tests and we want to have a 1-1 link between symbol and msgid anyway.
|   | Type |
Permit to make #2992 easier to review.
=> Remove legacy null symbol handling

pylint/checkers/classes.py, tests/functional/init_not_called.py
Fix false positive (super-init-not-called) for `__init__` methods decorated with `typing.overload`.
Close #3020
=> Don't require super call from `typing.overload`ed __init__

ChangeLog, doc/whatsnew/2.4.rst, pylint/checkers/typecheck.py, tests/functional/arguments.py, tests/functional/arguments.txt, tests/functional/arguments_out_of_order.py, tests/functional/arguments_out_of_order.txt, tests/functional/simplifiable_if_statement.py, tests/functional/useless_super_delegation.py
Adds a new check: `arguments-out-of-order`, which warns if there are positional arguments being passed in to a function in the wrong order in the case where the arguments are named in the same way as in the function signature. 
|   | Type |
Closes #2975
=> New check 2975 arguments out of order

README.rst
One of the major pain point of developing pylint
for me was the 30s to launch even a single test
with tox and then not have coverage, so I think
this doc will be helpful for future contributors.
|   | Type |
=> [Readme] Add information on how to launch tests fast

ChangeLog, pylint/checkers/base.py, pylint/checkers/base_checker.py, pylint/checkers/classes.py, pylint/checkers/imports.py, pylint/checkers/python3.py, pylint/checkers/refactoring.py, pylint/checkers/typecheck.py, pylint/checkers/variables.py, pylint/extensions/docparams.py, pylint/message/__init__.py, pylint/message/message_definition.py, pylint/message/message_definition_store.py, pylint/message/message_handler_mix_in.py, pylint/message/message_id_store.py, tests/message/generic_fixtures.py, tests/message/unittest_message.py, tests/message/unittest_message_definition.py, tests/message/unittest_message_definition_store.py, tests/message/unittest_message_id_store.py, tests/unittest_checker_base.py
At the cost of forcing to rename the old symbol when you create an old_name. Making the couple msgid/symbol a 1-1 relation removes legacy functions and complexity in order to ease implementation and optimize performance in the MessageStore. It will also permit to have multiple messages with the same old name for #1164. 
|   | Type |
=> Make the relation between msgid and symbol 1:1instead of 1:N

CONTRIBUTORS.txt, ChangeLog, pylint/utils/file_state.py
This simply tweaks iter_spurious_suppression_messages() to ignore any 'R0401' warnings it comes across (cyclic-import). The cyclic-import checker seems to have incomplete context at the point when this runs so is always flagged as a useless suppression.
Please holler if this is not the best place to add the ignore; happy to revise the PR if needed.
|   | Type |
Closes #3064
=> useless-suppression detection now ignores cyclic-import

CONTRIBUTORS.txt, ChangeLog, pylint/message/message_definition_store.py, pylint/message/message_handler_mix_in.py, pylint/message/message_id_store.py, tests/message/unittest_message_definition_store.py, tests/message/unittest_message_id_store.py, tests/test_functional.py
Permit to have multiple messages with the same old name. There are optimisations done that make Pylint a little faster.
|   | Type |
This is it, after this PR the real review for #1164 can start.
=> Multiple messages with the same old name

CONTRIBUTORS.txt, ChangeLog, pylint/checkers/base.py, tests/functional/d/docstrings.py, tests/functional/d/docstrings.txt, tests/functional/m/messages_managed_by_id.py, tests/functional/m/messages_managed_by_id.txt, tests/functional/m/missing_docstring.py, tests/functional/m/missing_docstring.txt, tests/functional/m/missing_docstring_new_style.py, tests/functional/m/missing_docstring_new_style.txt, tests/functional/m/missing_module_docstring_disabled.py, tests/test_self.py, tests/unittest_checker_base.py
This is an incomplete pull request in order to see more easily what needs to be changed in order to implement #1164 after a long period of inactivity.
=> Breaking down C0111(Missing Docstring) into multiple "Convention" messages

ChangeLog, doc/whatsnew/2.4.rst, pylint/checkers/imports.py, pylint/graph.py, pylint/reporters/text.py, tests/functional/g/globals.py, tests/functional/i/invalid_exceptions_raised.py, tests/functional/i/invalid_name.py, tests/functional/import_outside_toplevel.py, tests/functional/import_outside_toplevel.txt, tests/functional/m/member_checks.py, tests/functional/r/raising_format_tuple.py, tests/functional/u/undefined_variable.py, tests/functional/u/unused_variable.py, tests/functional/w/wrong_import_position4.py, tests/input/func_w0404.py, tests/input/func_w0405.py, tests/input/func_w0612.py, tests/unittest_checker_imports.py
- [x ] Add yourself to CONTRIBUTORS if you are a new contributor.
- [ x] Add a ChangeLog entry describing what your PR does.
- [ x] If it's a new feature or an important bug fix, add a What's New entry in `doc/whatsnew/<current release.rst>`.
- [ x] Write a good description on what the PR does.
This check warns when modules are imported from places other than a
module toplevel, e.g. inside a function or a class.
|   | Type |
=> New check: import-outside-toplevel (close #3067)

pylint/checkers/design_analysis.py, tests/functional/too/too_few_public_methods_37.py
- [] Add a ChangeLog entry describing what your PR does.
- [] If it's a new feature or an important bug fix, add a What's New entry in `doc/whatsnew/<current release.rst>`.
- [X ] Write a good description on what the PR does.
We were disabling `too-few-public-methods` for dataclasses, but only when the `dataclass` decorator was present in the root scope. Unfortunately that's not the case when using the fully qualified name e.g. `dataclasses.dataclass` which will result in the dataclass check to fail.
Also refactored the three checks for exempted classes into a single one for performance reasons.
|   | Type |
Close #3025
=> Disable too-few-public-methods for dataclasses

pylint/checkers/refactoring.py
This moves the cheap filters first before doing any inference.
=> Simplify and improve the logic of consider-iterating-dictionary

ChangeLog, doc/user_guide/run.rst, doc/whatsnew/2.5.rst, doc/whatsnew/index.rst, pylint/__pkginfo__.py, pylint/config.py, pylint/lint.py, tests/test_config.py
- [*] Add yourself to CONTRIBUTORS if you are a new contributor.
- [*] Add a ChangeLog entry describing what your PR does.
- [*] If it's a new feature or an important bug fix, add a What's New entry in `doc/whatsnew/<current release.rst>`.
- [*] Write a good description on what the PR does.
Configuration can be read from a setup.cfg or pyproject.toml file. See the documentation for exactly how.
|   | Type |
Closes #617
=> Can read setup.cfg and pyproject.toml files

CONTRIBUTORS.txt, ChangeLog, pylint/checkers/stdlib.py
inspect.getargvalues was inadvertently marked as deprecated in Python 3.5, and was deprecated in Python 3.6. See https://bugs.python.org/issue28814 for details.
`inspect.getargvalues` and `inspect.formatargvalues` were inadvertently marked as deprecated in Python 3.5, and was deprecated in Python 3.6. See https://bugs.python.org/issue28814 for details.
|   | Type |
=> Move inspect.getargvalues and inspect.formatargvalues out of deprecated functions

CONTRIBUTORS.txt, ChangeLog, pylint/checkers/python3.py, tests/unittest_checker_python3.py
As reported on #3128, there is a bug when the handler bound object is being used inside a generator causing a false positive. I identified that this was due to the way we were identifying if the object was "inside" its handler or not. In the previous implementation we would visit the node parents until we reached the object scope (in the generator case, the scope of the node is the generator, not the handler), my change continues to go up the parent stack until it reaches its parent handler, or, if it's not inside its handler, it reaches the module's parent (`None`). 
Object is considered inside its handler if it reaches it by going up in the parent chain. It's considered outside its handler if it reaches `None`.
|   | Type | …
=> Fixes "exception-escape" false positive with generators (#3128)

ChangeLog, doc/whatsnew/2.5.rst, pylint/checkers/base.py, tests/functional/d/dangerous_default_value_py30.py, tests/functional/d/dangerous_default_value_py30.txt
See #3183.
|   | Type |
Closes #3183
=> Flag various collections as dangerous defaults (#3183)

ChangeLog, pylint/extensions/docparams.py, tests/extensions/test_check_return_docs.py, tests/extensions/test_check_yields_docs.py
- [*] Add yourself to CONTRIBUTORS if you are a new contributor.
- [*] Add a ChangeLog entry describing what your PR does.
- [*] If it's a new feature or an important bug fix, add a What's New entry in `doc/whatsnew/<current release.rst>`.
- [*] Write a good description on what the PR does.
This fixes ``missing-yield-type-doc`` getting raised on a generator that has a type annotation and does not document a yield type. Returns documentation already caters for this case and so do parameters. Yields were missed out.
I've also removed a duplicate test.
|   | Type |
Closes #3185
=> Fixed ``missing-yield-type-doc`` ignoring type annotation

CONTRIBUTORS.txt, ChangeLog, pylint/checkers/classes.py, pylint/config.py, pylint/lint.py, pylint/message/message_definition.py, tests/message/unittest_message_definition.py, tests/unittest_lint.py
The PyLinter.check and related methods are refactored to remove copy-paste code and to allow simpler parallel linting implementation.
PyLinter is made pickleable so that the configured linter can be passed to worker processes (even when not using _fork_ method) so custom PyLinter objects can be used when linting parallel. For example, Prospector, will benefit from this. See https://github.com/PyCQA/prospector/issues/320
|   | Type |
=> Refactor file checking to allow parallel linting in Prospector

ChangeLog, pylint/checkers/classes.py, tests/functional/m/method_hidden.py, tests/functional/m/method_hidden.txt
- [*] Add yourself to CONTRIBUTORS if you are a new contributor.
- [*] Add a ChangeLog entry describing what your PR does.
- [*] If it's a new feature or an important bug fix, add a What's New entry in `doc/whatsnew/<current release.rst>`.
- [*] Write a good description on what the PR does.
`method-hidden` is not raised when a subclass defines the method. In this case the subclass is at fault and the parent class is trying to override the method that already exists.
|   | Type |
Closes #414
=> Fixed method-hidden when subclass defines the method

CONTRIBUTORS.txt, doc/whatsnew/2.4.rst, doc/whatsnew/2.5.rst, pylint/checkers/base.py, tests/functional/n/name_good_bad_names_regex.py, tests/functional/n/name_good_bad_names_regex.rc, tests/functional/n/name_good_bad_names_regex.txt
Adds two new config options: bad-names-rgxs and good-names-rgxs, to enable easier white/blacklisting of names. 
Closes #3086
=> Add regexs for bad- and good-names to enable better white- or blacklisting

CONTRIBUTORS.txt, ChangeLog, setup.py
The primary goal of this change was to remove an explicit requirement on pytest-runner for building/installing pylint*, as it is only required when running tests. This change is similar to what was done in the McCabe project, starting with [PyCQA/mccabe@cf1c36f84](https://github.com/PyCQA/mccabe/commit/cf1c36f842e252b8efd9e8fe853584ce69020b7f).
While here, fix a variety of pylint warnings with `setup.py` that were being omitted with the latest copy of pylint.
Finally, do some book keeping items around adding myself to CONTRIBUTORS and an entry to the ChangeLog for the change.
Signed-off-by: Enji Cooper <yaneurabeya@gmail.com>
|   | Type |
This is …
=> Make pytest-runner a requirement with test only targets

ChangeLog, pylint/lint.py, tests/test_self.py
Exceptions raised in ``_ast_from_string`` were not properly handled in
``Pylint.check``. Therefore, the output of `echo "for" | pylint --disable=all
--enable=syntax-error --from-stdin module.py` contained a traceback.
This issue is fixed by integrating the code from ``_ast_from_string into
Pylint.get_ast``.
|   | Type |
=> Fix problem with syntaxerrors in file from stdin

tests/test_self.py
``py.path.as_cwd`` _(return context manager which changes to current dir during the managed "with" context. On __enter__ it returns the old dir.)_ is a nice ctx manager, that can be used in one test
instead of a try/finally block.
|   | Type |
=> Cleanup tmpdir related code in test

pylint/lint.py
This code is not needed, since get_ast with `data` != None is only
needed for the --from-stdin feature, where get_ast is only called
once. Therefore, a cache is not needed.
|   | Type |
=> Remove dead code

CONTRIBUTORS.txt, ChangeLog, doc/whatsnew/2.5.rst, pylint/checkers/typecheck.py, tests/functional/n/non_str_assignment_to_dunder_name.py, tests/functional/n/non_str_assignment_to_dunder_name.txt
This adds a new check to make sure that only strings are assigned to `__name__` attributes.
|   | Type |
Closes #583
=> Add check to make sure only strings are assigned to __name__

CONTRIBUTORS.txt, ChangeLog, doc/whatsnew/2.5.rst, examples/pylintrc, pylint/checkers/strings.py, tests/functional/i/inconsistent_quotes.py, tests/functional/i/inconsistent_quotes.rc, tests/functional/i/inconsistent_quotes.txt, tests/functional/i/inconsistent_quotes2.py, tests/functional/i/inconsistent_quotes2.rc, tests/functional/i/inconsistent_quotes2.txt
This change implements a check for a recommendation in PEP-8.  It is emitted when quotes delimiters (" and ') are not used consistently throughout a module.  It makes allowances for avoiding unnecessary escaping, allowing, for example, ``"Don't error"`` in a module in which single-quotes otherwise delimit strings so that the single quote in ``Don't`` doesn't need to be escaped.
Quoting PEP-8:
> In Python, single-quoted strings and double-quoted strings are the same. This PEP does not make a recommendation for this. Pick a rule and stick to it. When a string contains single or double quote characters, however, use the other one to avoid backslashes in the string. It improves readability.
Features:
* Accounts for strings where the delimiter is swapped so an internal quote doesn't need to be …
=> Adds a new check 'inconsistent-quotes'.

CONTRIBUTORS.txt, ChangeLog, pylint/checkers/python3.py, tests/unittest_checker_python3.py
While dict-keys-not-iterating does not generate false positives for the
'in' containment test, the check does generate false positives for the
inverse counterpart of the containment test, 'not in'. This patch
changes the check behavior to also consider the 'not in' operator as an
iterating context.
|   | Type |
Relates to  #2186
=> Fix false positive for inverse containment tests

.pre-commit-hooks.yaml
- no need to quote `types`
- the other keys are optional and were their defaults
=> Simplify pre-commit configuration

CONTRIBUTORS.txt, pylint/checkers/base.py
This PR fixes a typo in the `visit_with` method of `BasicChecker` (`pylint/checkers/base.py`).
The typo fix: coresponds  --> corresponds
I did not add this change to the changelog. Please let me know if this is needed.
|   | Type |
=> BasicChecker: fix typo in 'visit_with' method

ChangeLog, doc/whatsnew/2.5.rst, pylint/checkers/base.py, tests/functional/a/assert_on_string_literal.py, tests/functional/a/assert_on_string_literal.txt
This PR adds a warning for assert statements that have string literals as their first argument.
Such assert statements will never fail.
|   | Type |
Fixes #3284
=> Add a check for asserts on string literals

examples/pylintrc
update examples/pylintrc with new logging-format-style help added in #3095
|   | Type |
=> update examples/pylintrc with new logging-format-style help

CONTRIBUTORS.txt, ChangeLog, pylint/checkers/strings.py
Remove import of Counter from types. It's unused and it also prevents use in python 3.5.3 or lower.
|   | Type |
Closes #3379
=> Remove import of Counter from types (unneeded and prevents use in python 3.5.3 or lower)

CONTRIBUTORS.txt, ChangeLog, examples/pylintrc, pylint/graph.py
While playing around with the 'import-graph' setting, I noticed that attempting to write a graph to a relative path did not work as I would have expected.
For example, 'import-graph=docs/graph.dot' would attempt to add 'graph.dot' to '/LOCAL/PATH/docs/docs/'.
This was because the 'dot_sourcepath' in this scenario would be set to the combination of the 'storedir' ('/LOCAL/PATH/docs') and the 'outputfile' ('docs/graph.dot'). I am requesting that it be changed to just be 'outputfile' in this scenario.
Also, I have removed the instantiation of the 'dotfile' variable because it now has no use.
|   | Type |
=> Fixed writing graphs to relative paths

ChangeLog, pylint/checkers/utils.py, tests/functional/u/unused_argument_py3.py, tests/functional/u/unused_argument_py3.txt
The original intention of `pylint.checkers.utils.is_error()` was to verify that a function only raises an error similar to being an abstract method by raising `NotImplementedError`. Unfortunately the implementation only inspected the body of the function to find at least a `raise` node, which means it was checking more than it should have in the first place.
|   | Type |
Close #3246
=> Emit ``unused-argument`` for functions that partially uses their argument list before raising an exception.

CONTRIBUTORS.txt, ChangeLog, pylint/checkers/base.py, tests/functional/r/redeclared_assigned_name.py, tests/functional/r/redeclared_assigned_name.rc, tests/functional/r/redeclared_assigned_name.txt
Added a check for the 'dummy-variables-rgx' option to '_check_redeclared_assign_name' as suggested in [#3341 ](https://github.com/PyCQA/pylint/issues/3341). 
This results in a non failed check if a reassigned variable matches with the regex.
Not sure if this counts as bugfix or feature.
|   | Type |
|  ✓ | :bug: Bug fix  |
| ✓ | :sparkles: New feature |
=> Allow dummy variables for 'redeclared-assigned-name'

pylint/checkers/logging.py, tests/unittest_checker_logging.py
The intention for `logging-too-many-args` and `logging-too-few-args` is to be emitted
when the logging string matches the expected format interpolation.
Otherwise `logging-too-many-args` will always be emitted when the logging string
does not match the expected format interpolation, especially since the arguments
have more bearing for the old style interpolation format, using modulo.
|   | Type |
Close #3362
=> Do not emit `logging-too-many-args` when `logging-format-interpolation` is emitted

ChangeLog, pylint/__init__.py, pylint/__main__.py
``python -m pylint ...`` adds the current working directory as the first element
of ``sys.path``. This opens up a potential security hole where ``pylint`` will import
user level code as long as that code resides in modules having the same name as stdlib
or pylint's own modules.
CPython issue: https://bugs.python.org/issue33053
|   | Type |
Close #3386
=> Do not allow ``python -m pylint ...`` to import user code

pylint/checkers/typecheck.py, tests/functional/i/isinstance_second_argument.py, tests/functional/i/isinstance_second_argument.txt
astroid can either infer a tuple call as a `Tuple()` node on successful
inference or it can infer the call as an `Instance` of the builtin tuple
object, on unsuccessful inference.
Should address the false positives from `astroid`: https://travis-ci.org/PyCQA/astroid/jobs/653410221?utm_medium=notification&utm_source=github_status
=> Allow instances of tuple of the isinstance() type check

pylint/pyreverse/writer.py
=> Skip methods without arguments when generating the dot format. 

ChangeLog, pylint/checkers/base.py
=> ``typing.overload`` functions are exempted from docstring checks

ChangeLog, pylint/checkers/base.py, tests/functional/d/dangerous_default_value_py30.py, tests/functional/d/dangerous_default_value_py30.txt
It looks like the rule wasn't accounting for kwargs defaults, I also had to add a None check to the for loop, because in cases like
```
def f(*, foo):
pass
```
The `node.args.kw_defaults` will be `[None]`
Please, let me know if there's anything missing
|   | Type |
#3373
=> dangerous-default-value accounts for kwargs defaults. Close #3373

CONTRIBUTORS.txt, ChangeLog, appveyor.yml, doc/whatsnew/2.5.rst, pylint/checkers/base.py, pylint/pyreverse/utils.py, tests/functional/n/namePresetCamelCase.txt, tests/functional/n/name_good_bad_names_regex.txt, tests/functional/n/name_preset_snake_case.txt, tests/functional/n/non_ascii_name.py, tests/functional/n/non_ascii_name.txt, tests/test_functional.py, tests/unittest_checker_base.py
This PR attempts to allow non-ASCII characters in identifiers in the `invalid-name` rule.
|   | Type |
This PR is in reference to issue #2725 but I have not closed it in the commit message yet because I have not yet implemented the second [part](https://github.com/PyCQA/pylint/issues/2725#issuecomment-522041148) and there are likely more changes required to this PR as well.
=> allow non-ASCII characters in identifiers in the invalid-name rule and add non-ascii-name

pylint/checkers/imports.py, pylint/lint.py, pylint/utils/utils.py, tests/test_self.py, tests/unittest_lint.py
---
**Do not add the current directory to `sys.path` any longer** (ac2c4986)
Adding the current directory to `sys.path` can also mean that we're
going to load modules having the same name as stdlib modules or
astroid modules, which can break pylint.
We were doing this since 4becf6f9e596b45401680c4947e2d92c953d5e08,
but there was indication on why we were doing that.
---
**Add test for checking that files are not imported from local directory** (c8dc18eb)
Close #959
Close #2952
---
**Replace individual member imports with `os` in utils file** (50621cd5)
---
**Move _get_python_path in utils to be accessible by that file as well** (04d69fee)
---
**Pass an additional search path to modutils.modpath_from_file and friends** (814774b9)
---
**Continue adding the current working directory to …
=> Avoid importing files from the local directory when running pylint

CONTRIBUTORS.txt, ChangeLog, pylint/checkers/classes.py, tests/functional/a/arguments_differ.py, tests/functional/a/arguments_differ.txt, tests/functional/a/arguments_differ_py3.py, tests/functional/a/arguments_differ_py3.txt
This PR suppresses the `arguments-differ` message if the overriding function provides positional or keyword variadics in its signature that can feasibly accept and pass on all parameters given by the overridden function.
|   | Type |
Closes #1482
Closes #1553
=> Fix overzealous `arguments-differ` for variadics

tox.ini
- [N/A] Add yourself to CONTRIBUTORS if you are a new contributor.
- [N/A] Add a ChangeLog entry describing what your PR does.
- [N/A] If it's a new feature or an important bug fix, add a What's New entry in `doc/whatsnew/<current release.rst>`.
Tox wasn't running locally without this, so we switch to using the coverage module invocation
instead of calling the site-package directly.
It's not clear why the site-package was being used directly, and if it passes on all platforms it might be worth applying.
|   | Type |
=> tox| Uses -m coverage instead of path to site-packages

ChangeLog, pylint/reporters/json_reporter.py, tests/test_self.py
The JSON module already escapes special characters as needed, so no need to HTML-escape them.  The only thing that this could break would be code that directly interpolates error messages into HTML code.  This would be a bug of that code, arguably.
This was already reported in #2769 and partially addressed by
6b1adc668727ebfbd84763b14b65676cc11febec, but that commit still quotes angle
brackets ('<' and '>').
|   | Type |
Closes #2769.
=> Don't HTML-escape JSON messages

CONTRIBUTORS.txt, pylint/checkers/refactoring.py, tests/functional/t/trailing_comma_tuple.py, tests/functional/t/trailing_comma_tuple.txt
This change addresses #2007.
The current logic for detecting trailing-comma-tuple violations fails to detect positive cases that span multiple lines because its look-back mechanism stops at the last NL or NEWLINE token when it should in fact stop at the last NEWLINE token only.
|   | Type |
Closes #2007
=> Fix false-negative cases for trailing-comma-tuple

tests/test_import_graph.py
We skip these tests if/when we run benchmarking only
Simply ignore a failure to delete a test-fixture file if it wasn't found on delete - it's likely the cause is the fact the test was skipped.
NB: we should run pylint on these test files. There is a lot of shadowed variables in this file.
|   | Type |
=> Handles failing file-delete when skipping import_graph tests

.isort.cfg, tests/.test_pylintrc, tests/extensions/test_check_docs.py, tests/extensions/test_check_raise_docs.py, tests/message/unittest_message_definition.py, tests/message/unittest_message_definition_store.py, tests/message/unittest_message_id_store.py, tests/test_config.py, tests/test_functional.py, tests/test_pragma_parser.py, tests/test_self.py, tests/unittest_checker_format.py, tests/unittest_lint.py, tests/unittest_pyreverse_diadefs.py, tests/unittest_reporting.py, tox.ini
Permit to lint pylint's own test, and fix some of the old problem found. It was not done previousely or at least not enforced in CI. There is a lot of work to get up to speed by removing old issue. In order to not have to do everything at once we created a new pylintrc file specific for tests so this can be done progressively. 
|   | Type |
Discussed in #3479 with @doublethefish . There is a lot of `redefined-outer-name` in the tests.
=> Enforce linting and auto-formatting in pylint's own tests

CONTRIBUTORS.txt, ChangeLog, pylint/checkers/variables.py, tests/functional/c/class_scope.py, tests/functional/c/class_scope.txt, tests/unittest_checker_variables.py
The  `_ignore_class_scope` method within the variable checker determines whether to search attributes in the class scope. This in turn uses `_defined_in_function_definition` to distinguish function arguments and annotations from the contents of the function (which form their own scope). However, `_defined_in_function_definition` was previously missing checks to search decorators (#511) and return type annotations (#1976), leading to false positives. These two checks were an easy fix.
While implementing the solution, it became apparent that Pylint wasn't checking whether variables inside list/set/dict comprehensions and generator expressions could actually access class scope. This led to false negatives where Python would raise a `NameError`, but Pylint wasn't providing any warning …
=> Fix class scope issues in undefined-variable checker #511 #1976 #3494

tox.ini
Fairly straight-forward change enabling the creation heatgraphs for test-runs, when and as needed.
We can use `tox -epy38 -- --profile-svg` to enable this functionality now that we have the pytest-profiling dependency added to tox.
Partly addresses #1954. Split out from the original PR for #3473.
|   | Type |
=> profile| Adds (opt-inable) profile-heatmap generation output to tox test-runs

ChangeLog, doc/whatsnew/2.5.rst, pylint/checkers/logging.py, tests/functional/l/logging_format_interpolation.txt, tests/functional/l/logging_format_interpolation_py36.py, tests/functional/l/logging_format_interpolation_py36.txt, tests/functional/l/logging_fstring_interpolation_py36.py, tests/functional/l/logging_fstring_interpolation_py36.txt, tests/functional/l/logging_not_lazy.txt, tests/messages/func_bug113231.txt, tests/messages/func_logging_not_lazy_with_logger.txt, tests/unittest_checker_logging.py
The brings back the logging-fstring-interpolation message so that multiple types of log formatting can be used at once. To address the original issue (#2395) we need to disable `logging-fstring-interpolation` by default so that f-string formatting is allowed by default, but this currently isn't possible.
In #3361 I also noted that we should add a `logging-old-style-interpolation` message but `logging-not-lazy` takes care of that case already.
When I first implemented fstring formatting in logging functions I misunderstood what the `logging-format-style` option was for. It's actually for controlling whether you can pass a new or old style format string directly to the logging message (eg `log.info("{}", "blah")` or `log.info("%s", "blah")`), not what type of logging is valid overall. So …
=> Brought back logging-fstring-interpolation

ChangeLog, pylint/checkers/classes.py, tests/functional/m/method_hidden.py
The patch replaces `mro()` with `ancestors()` as the former is not
fully capable of generating the complete linearization when
dealing with ambiguous inferences.
Close #3527
=> Fix a crash in `method-hidden` lookup for unknown base classes

ChangeLog, pylint/lint/run.py, tests/benchmark/test_baseline_benchmarks.py, tests/lint/unittest_lint.py, tox.ini
---
**Fix a crash in `method-hidden` lookup for unknown base classes** (90d42153)
The patch replaces `mro()` with `ancestors()` as the former is not
fully capable of generating the complete linearization when
dealing with ambiguous inferences.
Close #3527
---
**Revert pylint.Run's `exit` parameter to ``do_exit``** (a02b1892)
This has been inadvertently changed several releases ago to ``do_exit``.
---
**Lint pylint from toxinidir, not the installed one** (357922e9)
|   | Type |
Close #3533
=> Rename pylint.Run do_exit parameter to exit 

ChangeLog, pylint/checkers/typecheck.py, tests/functional/r/regression_no_value_for_parameter.py
The problem was caused by the exemption of variadics for `no-value-for-parameter` not being smart enough when deciding if a statement should be included or not. Previously only return statements or expressions were taking in consideration, but right hand side of assignments should also be exempted when dealing with variadics.
|   | Type |
Close #3563
=> `no-value-for-parameter` variadic detection has improved for assign statements

ChangeLog, pylint/utils/utils.py, tests/test_self.py
`modutils.modpath_from_file_with_callback` can use an additional path to search other than `sys.path`. While we were passing this flag for `modutils.file_info_from_modpath` in the `expand_modules` function, we were not doing it for `modpath_from_file_with_callback` as well, which is used to grab the file paths from the current package to be linted.
|   | Type |
Close #3524
=> Allow package files to be properly discovered with multiple jobs

ChangeLog, pylint/utils/utils.py, tests/test_self.py
This was a regression in 2.5 caused by https://github.com/PyCQA/pylint/commit/a6d7ffc4679b0ad2258cf6c31c6dfbeeb2b331ef. 
Close #3528
|   | Type |
=> Allow linting directories without `__init__.py`

ChangeLog, doc/whatsnew/2.6.rst, pylint/checkers/python3.py, tests/checkers/unittest_python3.py, tests/functional/s/super_style.py, tests/functional/s/super_style.rc, tests/functional/s/super_style.txt
Adds a check that flags instances of super with the default arguments, which are no longer needed in Python 3.
|   | Type |
Closes #3541
=> Add new old-style-super check to flag instances of super with default arguments

ChangeLog, doc/whatsnew/2.6.rst, pylint/checkers/python3.py, pylint/checkers/refactoring.py, tests/checkers/unittest_python3.py, tests/functional/a/access_to_protected_members.py, tests/functional/a/arguments_differ.py, tests/functional/a/assigning_non_slot.py, tests/functional/d/deprecated_methods_py3.py, tests/functional/d/deprecated_methods_py38.py, tests/functional/i/init_not_called.py, tests/functional/m/member_checks.py, tests/functional/m/member_checks_hints.py, tests/functional/m/member_checks_no_hints.py, tests/functional/m/method_hidden.py, tests/functional/n/name_styles.py, tests/functional/r/regression_property_no_member_844.py, tests/functional/s/super_checks.py, tests/functional/s/super_style.txt, tests/functional/s/super_with_arguments.py, tests/functional/s/super_with_arguments.rc, tests/functional/s/super_with_arguments.txt, tests/functional/u/useless_super_delegation.py, tests/functional/u/useless_super_delegation_py3.py, tests/functional/u/useless_super_delegation_py35.py
---
**Rename the new old-style super with super-with-arguments** (0c54e7e9)
Also move it from the Python 3 checker to the refactoring one, as it's a
better fit for it.
---
**Address the super violations in the codebase** (f2197e5f)
|   | Type |
=> Rename old-style-super and move it to refactoring out of the Python 3 porting checker

ChangeLog, pylint/lint/run.py
We need to allow various third party libraries that depend on `pylint` to still use `do_exit` until they can move over to use `exit`. For now the `do_exit` parameter is marked as deprecated and will be removed in a future version.
Close #3590
=> ``pylint.Run`` accepts ``do_exit`` as a deprecated parameter

pylint/__pkginfo__.py, pylint/config/option_manager_mixin.py, pylint/config/option_parser.py, pylint/constants.py, pylint/lint/pylinter.py, pylint/lint/run.py
This fix #3576 albeit in a hacky way (?) I refactored a little the version that was stored in every checker apparently. What could be the reason to do that? Also, I wonder why the BaseChecker inherit from OptionProviderMixin? Couldn't we parse the option once and give each checker it's own options so we can instantiate a checker without using sys args and optparse?
|   | Type |
Closes #3576
=> Fix crash when the user ask for --version and pylintrc is malformed

ChangeLog, pylint/checkers/base.py, tests/functional/c/continue_in_finally.rc
=> `continue-in-finally` no longer emitted on Python 3.8 where it's now valid

CONTRIBUTORS.txt, ChangeLog, pylint/config/option_manager_mixin.py, tests/test_config.py
Before that, we had to use strings in a TOML configuration file, like
this:
```toml
enable = "use-symbolic-message-instead,useless-suppression"
jobs = "10"
suggestion-mode = "no"
```
TOML supports rich types like list, integer and boolean. They make for
a more readable and less error-prone file. We can now express the same
configuration like this:
```toml
enable = [
"use-symbolic-message-instead",
"useless-suppression",
]
jobs = 10
suggestion-mode = false
```
|   | Type |
Closes #3538 
Previous tests were not quite right because they used `MagicMock`, which happily says yes to, well, whatever you throw at it, including `magic_mocked_thing.called_with("anything", "really")`. ;)
I aimed for the least invasive change, but I think that …
=> config: Handle rich (non-string) types in TOML file

ChangeLog, pylint/lint/check_parallel.py, tests/test_self.py
The linter depends on `FileState.base_name` to be set for emitting
the reports. This has been removed inadvertently in
21dc87531296256c3bccda660229b0c60a7bb129 during refactoring of
the multiprocessing implementation.
Close #3547
|   | Type |
=> Fix a regression where the score was not reported with multiple jobs

CONTRIBUTORS.txt, ChangeLog, doc/faq.rst
Add an FAQ detailing which messages to disable to avoid duplicates when using other popular linters alongside pylint.  Includes pycodestyle, pyflakes, mccabe, pep8-naming, and flake8-import-order.
|   | Type |
Related: #3512, #3517 
This does not resolve them in any way.  It only adds instructions in the faq on how to configure pylint manually while using other linters
=>  Add an faq detailing which messages to disable to avoid duplicates w/ other popular linters

CONTRIBUTORS.txt, ChangeLog, pylint/utils/pragma_parser.py, tests/test_pragma_parser.py
This fixes https://github.com/PyCQA/pylint/issues/3666.
- [N/A] If it's a new feature or an important bug fix, add a What's New entry in `doc/whatsnew/<current release.rst>`.
Pylint used to allow just about anything in a checker name, but with https://github.com/PyCQA/pylint/commit/9bdae8b82fcc5b0592135cbf6bead7df360a6672, it got a lot stricter about naming (I believe unintentionally). This expands the `MESSAGE_STRING` regular expression to allow for numbers in checker names.
|   | Type |
Closes https://github.com/PyCQA/pylint/issues/3666
=> Allow numbers in checker names.

pylint/checkers/similar.py
#2830 ignores all lines in a module after the start of a raw docstring i.e. `r"""` or `r'''`. This PR fixes this and just ignores the raw docstring.
To reproduce the bug, create two identical modules `package/similar1.py` and `package/similar2.py` with the content:
```
r"""A raw docstring.
"""
def look_busy():
xxxx = 1
yyyy = 2
zzzz = 3
wwww = 4
vvvv = xxxx + yyyy + zzzz + wwww
return vvvv
```
Run `pylint --disable W9011,W9012 package`.
Duplicate code in function `look_busy` is flagged.
No duplicate code warning raised.
|   | Type |
=> Fix #2830. Ignore just the raw docstring, no more.

ChangeLog, pylint/checkers/typecheck.py, tests/functional/m/missing_kwoa_py3.py, tests/functional/m/missing_kwoa_py3.txt
=> ``missing-kwoa`` is no longer emitted when dealing with overload functions

pylint/checkers/base.py, pylint/checkers/typecheck.py, pylint/checkers/utils.py, pylint/config/option.py, pylint/lint/pylinter.py, pylint/pyreverse/vcgutils.py
I recently went over [Matplotlib](https://github.com/matplotlib/matplotlib/pull/16706), [Pandas](https://github.com/pandas-dev/pandas/pull/32322) and [NumPy](https://github.com/numpy/numpy/pull/15731), fixing a small mistake in the way that Python 3's exception chaining is used. If you're interested, I can do it here too. I've done it on just one file right now. 
The mistake is this: In some parts of the code, an exception is being caught and replaced with a more user-friendly error. In these cases the syntax `raise new_error from old_error` needs to be used.
Python 3's exception chaining means it shows not only the traceback of the current exception, but that of the original exception (and possibly more.) This is regardless of `raise from`. The usage of `raise from` tells Python to put a …
=> Fix exception causes all over the codebase

.pre-commit-hooks.yaml, CONTRIBUTORS.txt, ChangeLog
The default pre-commit behaviour might lead to falsely succeeding lint-runs.
E.g. due to duplicate lines of code spread across multiple files -- if affected
files get spread across multiple runs, duplicates can not be detected.
|   | Type |
=> Set default pre-commit hook config: single process

ChangeLog, doc/whatsnew/2.6.rst, pylint/checkers/format.py, tests/checkers/unittest_format.py
Skip over superfluous-parens checks for parenthesis wrapping the walrus operator since parenthesis can change the meaning of this operator
|   | Type |
Closes #3383
=> Fix false positive superfluous-parens for the walrus operator

ChangeLog, pylint/checkers/base.py, tests/functional/r/regression_infer_call_result_3690.py
`infer_call_result` can raise `InferenceError` and should be handler in all call sites. This was not happening with this particular check.
|   | Type |
Close #3690
=> Fix a crash caused by not guarding against `InferenceError` when calling `infer_call_result`

ChangeLog, pylint/lint/check_parallel.py, tests/test_self.py
This has been like this since the parallel refactoring done in https://github.com/PyCQA/pylint/commit/8babeffde54a696e7ba84d69f8fc1f871e432950
|   | Type |
Close #3564
=> Fix a crash in parallel mode when the module's filepath is not set

CONTRIBUTORS.txt, ChangeLog, doc/whatsnew/2.6.rst, pylint/checkers/exceptions.py, pylint/checkers/utils.py, tests/functional/m/misplaced_bare_raise.py, tests/functional/n/no_else_raise.py, tests/functional/n/no_else_return.py, tests/functional/r/raise_missing_from.py, tests/functional/r/raise_missing_from.txt, tests/functional/r/regression_3416_unused_argument_raise.py, tests/functional/r/regression_3416_unused_argument_raise.txt, tests/functional/s/stop_iteration_inside_generator.py, tests/functional/t/try_except_raise.py
=> Add rule raise-missing-from

setup.py
The test suite certainly exits with failure when running ``python setup.py test`` without this.
Mentioned in #3702 but does not close the issue
Or we can skip the benchmark tests if the plugin is not installed. What do you think?
Sample error:
```
file /home/user/code/pylint/tests/benchmark/test_baseline_benchmarks.py, line 208
def test_baseline_lots_of_files_j10_empty_checker(self, benchmark):
E       fixture 'benchmark' not found
>       available fixtures: cache, capfd, capfdbinary, caplog, capsys, capsysbinary, checker, disable, doctest_namespace, enable, linter, monkeypatch, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, register, reporter, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory
>       use 'pytest --fixtures [testpath]' for help …
```
=> Add missing test dependency pytest-benchmark to setup.py

.travis.yml
Not having this option is creating an error:
````
SystemError: Parent module 'setuptools' not loaded,
cannot perform relative import
````
See https://travis-ci.org/github/PyCQA/pylint/jobs/722843170:
It isn't clear what a permanent fix could be. See
https://github.com/pypa/setuptools/issues/2232 and
https://github.com/pypa/setuptools/blob/17cb9d6bf249cefe653d3bdb712582409035a7db/CHANGES.rst#v5000
for details.
|   | Type |
=> Temporary fix build for setuptools 50.0.0

CONTRIBUTORS.txt, ChangeLog, pylint/lint/run.py, tests/test_self.py
Previously, pylint would crash if called with a nonexistent config file, such as `pylint --rcfile=does_not_exist`. This change catches the exception raised by `OptionsManagerMixIn.read_config_file()` and reports it properly, exiting with the code 32.
I also changed a test case which only checked if the crash occurred.
|   | Type |
Downstream bug report: https://bugzilla.redhat.com/show_bug.cgi?id=1831554
=> Fix crash when specified config file doesn't exist

CONTRIBUTORS.txt, ChangeLog, setup.py
`>=3.5.*` can make some packaging tools confused.
|   | Type |
=> Fix the ambiguous python version specifier

doc/whatsnew/2.7.rst, pylint/lint/check_parallel.py, pylint/reporters/collecting_reporter.py, tests/lint/unittest_lint.py
Fixed an issue in `check_parallel` that re-emits all messages a process has seen before for each file. Added a `reset` method to the `CollectingReporter` and call it after each file a process analyses.
|   | Type |
Closes #3584
=> Fix duplicate messages created by jobs>1.

CONTRIBUTORS.txt, ChangeLog, pylint/checkers/similar.py, tests/checkers/unittest_similar.py, tests/input/similar3, tests/input/similar4
Enhanced the similarity checker to ignore lines that only have symbols on them (e.g. comma, bracket, parentheses, etc.).  The tool `black` can often create such lines when reformatting whitespace, which leads to false positives for code similarity.
|   | Type |
Closes #3726
=> fixed issue 3726: enhanced similarity checker

ChangeLog, pylint/checkers/base.py, pylint/checkers/refactoring/len_checker.py, pylint/checkers/refactoring/refactoring_checker.py, pylint/checkers/utils.py, tests/checkers/unittest_base.py, tests/functional/s/singleton_comparison.py, tests/functional/s/singleton_comparison.txt
Singleton-comparison will now suggest `is` for boolean constants, as well as a message for truthiness/falsiness in case the user intended this, whereas the message would only suggest checking truthiness/falsiness before. The message will now also display the actual code in question, instead of an `expr` stand-in.
|   | Type |
|      | :sparkles: New feature |
|      | :hammer: Refactoring  |
|      | :scroll: Docs |
=> Improve `singleton-comparison` suggestion message

CONTRIBUTORS.txt, ChangeLog, pylint/checkers/spelling.py, tests/checkers/unittest_spelling.py
Fix spell-checker crash on indented docstring lines that look like `# comments`. See #3786 for more info.
|   | Type |
Closes #3786
=> Docstr comment

ChangeLog, doc/whatsnew/2.7.rst, pylint/extensions/empty_comment.py, tests/extensions/data/empty_comment.py, tests/extensions/test_empty_comment.py
* Empty comments in your code can be confusing in large scale programs, especially when developers are replaced frequently. If a developer who didn't write the code see an empty comment s/he can think there is a missing a comment. I know that some developers put empty comments when they want to bookmark somewhere in the code, and this is a bad practice that should be avoided.
* This checker recognizes lines with empty comments, but also accurate enough not to raise False Positives (or else people would stop using this tool).
* Since a message is raised only with empty comments, I could not add a test at `tests/test_functional.py` folder, so I wrote a unittest instead.
IsDone | Type
------------ | -------------
|| 🐛 Bug fix
✓|✨ New feature
||🔨  Refactoring
||📜  Docs
None
=> Add checker for empty comments

CONTRIBUTORS.txt, ChangeLog, pylint/checkers/utils.py, tests/functional/p/postponed_evaluation_activated_with_alias.py, tests/functional/p/postponed_evaluation_activated_with_alias.rc
Fix a bug that causes an unrelated warning when renaming "annotations" from "__future__" with the `as` clause.
|   | Type |
Closes #3798
=> bugfix: accepts aliases for __future__ annotations

ChangeLog, doc/whatsnew/2.6.rst, pylint/checkers/classes.py, tests/checkers/unittest_classes.py
This PR adds an option to the `ClassChecker` that allows the user to activate/deactivate the emission of `protected-access` message for single underscore prefixed attribute access in special methods.
|   | Type |
Closes #3120
=> Bug pylint 3120

CONTRIBUTORS.txt, ChangeLog, doc/whatsnew/2.7.rst, pylint/extensions/docparams.py, tests/extensions/test_check_docs.py
Adds support to ignored arguments from the `ignored-argument-names` config such as "_", for instance.
To avoid breaking changes it also accepts ignored argument names to be documented.
|   | Type |
Closes #3800
=> Adds support to `ignored-argument-names` in DocstringParameterChecker

pylint/checkers/refactoring/refactoring_checker.py, tests/functional/i/inconsistent_returns.py, tests/functional/i/inconsistent_returns.txt
This PR is a fix for #3873 and should allow `astroid` CI to be free from linting errors.
A try/except node is now considered as return ended if at least one of its non-except-handling children is return ended and if all the except-handling children are return ended.
3 unit tests have been added.
|   | Type |
Closes #3873
=> Bug pylint 3873

pylint/__pkginfo__.py
The long description now comes from `Readme.rst`, see `setup.py` line 66 to 72
|   | Type |
=> Remove deprecated long description in __pkginfo__.py

CONTRIBUTORS.txt, ChangeLog, doc/whatsnew/2.6.rst, pylint/lint/parallel.py
Shutdown multiprocessing pool properly (base on pytest-cov recommandation [here](https://pytest-cov.readthedocs.io/en/latest/subprocess-support.html#if-you-use-multiprocessing-pool));fixing the triggered warnings from parallel runs of pytest plugins (pytest-cov and pytest-pylint in this case (see issue #3779))
|   | Type |
Closes #3779
=> lint multiprocessing pool shutdown

CONTRIBUTORS.txt, ChangeLog, pylint/checkers/format.py
Before this change, we would check a line for `pylint: disable`-style
pragmas to determine whether to check the line length. The regex
check itself is very costly (~5% of pylint's total runtime in one
codebase), and is much more costly than the check itself.
This refactors the pylint check to instead do an approximate line
length check on everything, before using the regex to handle
exceptional, false negative cases like pragmas being the cause for the line length
overflow.
This change, in one sample codebase, lowered the `check_lines`
runtime from 5% of the total runtime to 0.35% of the total runtime.
**EDIT**: the control flow on this is a bit weird to avoid iterating over content twice in the common "passing" case, but I think here it's worth it 
|   | Type |
| ------------- | …
=> Avoid doing a regex search for line lengths unless necessary

CONTRIBUTORS.txt, ChangeLog, doc/development_guide/contribute.rst, pylint/checkers/typecheck.py, tests/checkers/unittest_typecheck.py
I'm trying myself at fixing #3882, by handling the specific case where a decorator is a class. I bet this could be handled elsewere to be made more generic, but as a first contribution I'm starting slow.
|   | Type |
Closes #3882
=> Handle class decorators during typing checks.

tests/profile/test_profile_against_externals.py, tox.ini
- [-] Add yourself to CONTRIBUTORS if you are a new contributor.
- [-] Add a ChangeLog entry describing what your PR does.
- [-] If it's a new feature or an important bug fix, add a What's New entry in `doc/whatsnew/<current release.rst>`.
Runs pylint against numpy and supports adding other external repos for testing.
Will generate a .svg in the .tox/prof. Here's an example:
https://pylint.s3.amazonaws.com/doublethefish/pylint/output.svg
Other considerations:
* Use https gitub uri so we do not need credentials
* Shallow clone so we don't pull more data than we need
* Ensure we skip external profiling unless explicitly wanted
|   | Type |
=> profile| Runs pylint against external code, generating profile-heatmaps

pylint/testutils/__init__.py, pylint/testutils/checker_test_case.py, pylint/testutils/constants.py, pylint/testutils/decorator.py, pylint/testutils/functional_test_file.py, pylint/testutils/get_test_info.py, pylint/testutils/global_test_linter.py, pylint/testutils/lint_module_test.py, pylint/testutils/output_line.py, pylint/testutils/tokenize_str.py, pylint/testutils/unittest_linter.py, pylint/testutils/utils.py, tests/test_func.py
In order to be able to make better test utility we  first start to make the testutils package more manageable. This permit to not have too much noise in #3918 .
|   | Type |
#3918
=> Burst testutils/utils into files with semantic names

ChangeLog, pylint/checkers/base.py, tests/functional/b/bad_reversed_sequence.py, tests/functional/b/bad_reversed_sequence.txt, tests/functional/b/bad_reversed_sequence_py37.py, tests/functional/b/bad_reversed_sequence_py37.rc, tests/functional/b/bad_reversed_sequence_py37.txt, tests/functional/b/bad_reversed_sequence_py38.py, tests/functional/b/bad_reversed_sequence_py38.rc
Only emit `bad-reversed-sequence` on dictionaries if below py3.8
|   | Type |
Closes #3940
=> Only emit `bad-reversed-sequence` on dictionaries if below py3.8 (#3940)

.pre-commit-config.yaml, tox.ini
Permit to use `pre-commit run --all-files` as exec
during interactive rebasing.
Also fix a bug with appveyor that appeared on the master branch.
|   | Type |
=> Add proper exclusion in pre-commit configuration

CONTRIBUTORS.txt, ChangeLog, pylint/checkers/stdlib.py
Fixes regression introduced by
https://github.com/PyCQA/pylint/commit/9d4f2c082e4f17fb5165deb0c9e4a0fd329d5cbd which incorrectly added
getfullargspec as deprecated, which in fact was never deprecated, not even in the latest [3.9.0](https://docs.python.org/3/library/inspect.html#inspect.getfullargspec)
|   | Type |
Related: https://github.com/PyCQA/pylint/commit/9d4f2c082e4f17fb5165deb0c9e4a0fd329d5cbd
=> Fix regression about getfullargspec deprecation

.pre-commit-config.yaml, bin/pylint, setup.py, tox.ini
This put all the formatting in pre-commit so we can't have change in tox that make pre-commit not work anymore and inversely.
|   | Type |
=> Factorize code formatting in one place

ChangeLog, pylint/checkers/async.py, tests/functional/n/not_async_context_manager_py37.py
=> Fix false positive for `not-async-context-manager` when `contextlib.asynccontextmanager` is used

CONTRIBUTORS.txt, ChangeLog, pylint/checkers/utils.py
=> Make postponed annotations enabled by default for 3.10+

ChangeLog, pylint/checkers/refactoring/recommendation_checker.py, tests/functional/c/consider_using_enumerate.py
=> Fix a crash in `consider-using-enumerate` when encountering `range()` without arguments

CONTRIBUTORS.txt, ChangeLog, pylint/checkers/classes.py, tests/functional/s/signature_differs.py
We make sure to only raise signature-differs warnings for functions that do not have variadic arguments.
|   | Type |
Closes #3737
=> Fix false positive for signature-differs

pylint/testutils/lint_module_test.py, tests/functional/b/bad_reversed_sequence.txt, tests/functional/c/comparison_with_callable.txt, tests/functional/i/init_not_called.txt, tests/functional/i/invalid_exceptions_raised.txt, tests/functional/i/invalid_sequence_index.txt, tests/functional/m/messages_managed_by_id.txt, tests/functional/n/namedtuple_member_inference.txt, tests/functional/s/super_checks.txt, tests/functional/u/unbalanced_tuple_unpacking.txt, tests/functional/u/unidiomatic_typecheck.txt, tests/functional/u/useless-import-alias.txt, tests/test_functional.py
Use sets here to show full diffs in functional tests
Co-authored-by: Ethan Leba <ethanleba5@gmail.com>
This change was hidden in #3821 and was not related to the MR that is taking some time because I must handle function and it's hard to do it properly. This was detrimental because tjhe error message was modified again in #3906 although a clearer error message already existed.
|   | Type |
=> Better assert message when dealing with functional tests messages

CONTRIBUTORS.txt, ChangeLog, doc/whatsnew/2.6.rst, pylint/checkers/refactoring/len_checker.py, tests/checkers/unittest_refactoring.py, tests/functional/l/len_checks.py, tests/functional/l/len_checks.txt
`len-as-conditions` is now triggered only for classes that are inheriting directly from list, dict, or set and not implementing the `__bool__` function, or from generators like range or list/dict/set comprehension. This should reduce the false positive for other classes, like pandas's DataFrame or numpy's Array. See discussion in related issue.
|   | Type |
#1879
=> Less false positives for len-as-conditions (pandas's DataFrame, numpy's Array)

pylint/testutils/__init__.py, pylint/testutils/constants.py, tests/test_func.py, tests/test_functional.py
This fix the problem we had with the command supposed to update functional tests. It uniformize it between legacy and current functional tests, document it for legacy tests and fix it for current functional tests.
|   | Type |
=> Unify, document and fix functional tests internal updating process

CONTRIBUTORS.txt, ChangeLog, doc/whatsnew/2.6.rst, pylint/checkers/__init__.py, pylint/checkers/mapreduce_checker.py, pylint/checkers/similar.py, pylint/lint/parallel.py, tests/checkers/unittest_similar.py, tests/input/similar_lines_a.py, tests/input/similar_lines_b.py, tests/test_check_parallel.py, tests/test_self.py
This is #3458 rebased because it's mergeable but stuck as the original one is not directly editable by maintainers. Had to fix some conflict and move the changelog from 2.5 to 2.6.1.
=> Rebased Doublethefish's bug/3314 duplicate code error only shows up with pylint jobs 1

ChangeLog, pylint/extensions/empty_comment.py, tests/extensions/test_empty_comment.py
Fixed empty-comment wrong line number in its message. Was 1 line behind the actual line number.
Fixed implementation and unittest.
|   | Type |
#4009
=> empty-comment line number bug fix

CONTRIBUTORS.txt, ChangeLog, pylint/checkers/strings.py, tests/functional/a/anomalous_backslash_escape.py, tests/functional/a/anomalous_backslash_escape.txt, tests/functional/e/excess_escapes.py, tests/functional/e/excess_escapes.txt
The existing logic does not account for the start-of-line to start-of-string offset in the column and does not adjust the line to reflect where the actual backslash occurs.
|   | Type |
=> Fix location metadata on backslash/unicode escape lints

README.rst
This add information about pytest-benchmark necessary for local test that was added some time ago.
|   | Type |
=> Add pytest-benchmark info in the readme

.pre-commit-config.yaml, pylint/extensions/_check_docs_utils.py, pylint/testutils/checker_test_case.py, pylint/testutils/lint_module_test.py, pylint/testutils/output_line.py, setup.py, tests/checkers/unittest_base.py, tests/lint/unittest_lint.py, tests/test_regr.py, tox.ini
This  MR make the tox mypy test be applied on the whole code, use pre-commit to do it so it's done automatically on commit and fix all issues encountered with mypy in the existing code.
|   | Type |
=> Extends mypy check, add pre-commit configuration and fix legacy fail

ChangeLog, pylint/checkers/variables.py, tests/functional/a/assignment_expression.py, tests/functional/a/assignment_expression.rc, tests/functional/a/assignment_expression.txt
Fix multiple false positive that occurred together with assignment expressions. Addressed issues:
```py
x = b if (b := True) else False  # b
assert (n := 2) == 1, f"Expected 1, but got {n}"  # n
dict({1: (o := 2)}, data=o)  # o
if (c := lambda: 2) and c():  # c
print("ok")
values = (
e := 1,
f := e,  # e
)
function = lambda: (
h := 1,
i := h,  # h
)
```
|   | Type |
Closes: #3347
Closes: #3953
Closes: #3865
Closes: #3275
=> Fix multiple false positives with assignment expressions

ChangeLog, pylint/checkers/classes.py, tests/functional/t/typedDict.py, tests/functional/t/typedDict.rc
In Python 3.9 `typing.TypedDict` changed from a class to function with some metaclass magic.
This caused a `inherit-non-class` error for valid code.
**Source code**
[Python 3.8 - typing.py](https://github.com/python/cpython/blob/c370596a23167749b8127d1d2e20e039865aa695/Lib/typing.py#L1760-L1763)
[Python 3.9 - typing.py](https://github.com/python/cpython/blob/48d16b4b0fb0d0558bdbc1aee850650a671ecc77/Lib/typing.py#L1940-L1998)
**Documentation**
https://docs.python.org/3/library/typing.html#typing.TypedDict
|   | Type |
Closes #1927
=> Fix TypedDict inherit-non-class false-positive Python 3.9+

.gitignore
Permit to avoid having to repeat that the gitignore global exists like in #4058 
|   | Type |
=> Add a warning in the .gitignore

ChangeLog, doc/whatsnew/2.6.rst, doc/whatsnew/2.7.rst, doc/whatsnew/index.rst
Remove everything that was in 2.6 changelog when it should be in 2.7 following the decision taken in #3831 
This can be checked with
```
git remote add pyorigin git@github.com:PyCQA/pylint.git
git diff pyorigin/2.6 doc/whatsnew/
git diff pyorigin/2.6 ChangeLog
```
The idea is that nothing should be added between 2.6 and now in a 2.6 portion everything done between now and 2.6 should be in 2.7.
|   | Type |
=> Fix the changelog and whatsnew retroactively

CONTRIBUTORS.txt, ChangeLog, doc/whatsnew/2.7.rst, pylint/checkers/python3.py, tests/checkers/unittest_python3.py
Since ``map()`` supports iterables, it should not issue ``builtin-not-iterating`` for iterable arguments.
|   | Type |
Closes #4078
=> Fix false positive when map() receives iterable

ChangeLog, doc/how_tos/custom_checkers.rst, examples/deprecation_checker.py, pylint/checkers/__init__.py, pylint/checkers/deprecated.py, pylint/checkers/stdlib.py, tests/checkers/unittest_deprecated.py
This PR is moving deprecated check logic to separate mixin class `DeprecatedMixin`. This enables plugins to implement their own deprecation checks. The most visible use case can be pylint-django. Here is the example of simple plugin:
```python
"""
Simple DeprecatedChecker marking test.deprecated_func as deprecated.
"""
import astroid
from pylint.checkers import BaseChecker, DeprecatedMixin, utils
from pylint.interfaces import IAstroidChecker
class DeprecatedChecker(BaseChecker, DeprecatedMixin):
__implements__ = (IAstroidChecker,)
name = "deprecated"
msgs = {
"W1505": (
"Using deprecated method %s()",
"deprecated-method",
"The method is marked as deprecated and will be removed in "
"a future version of Python. Consider looking for an "
"alternative in the documentation.",
)
} …
```
=> Implement reusable Method Deprecation checker.

CONTRIBUTORS.txt, pylint/testutils/__init__.py
In the project I am working on we just upgraded to 2.7 and got hit by a [missing import](https://github.com/rotki/rotki/pull/2417/checks?check_run_id=1946892832) for `UnitTestLinter`. We have some custom pylint plugins. I see that there was a refactor in testutils for 2.7 and I assume exposing this class from __init__.py was missed. So I am going ahead and adding it with this PR. Hope it's fine.
|   | Type |
=> Expose UnittestLinter in testutils after 2.7

.github/workflows/ci.yaml, ChangeLog, pylint/utils/utils.py
This MR fixes the currently broken benchmark test and adds a CI job to run the benchmark every time.
The fix doesn't require any changes in astroid. The `register_plugins` didn't filter `.`-foldernames (eg. `.github`) and thus `modutils.load_module_from_file` was called. Astroid uses `importlib.import_module` which interprets the `.` as a relative import. I believe it's highly unlikely that some project would define their plugins in a hidden directory which is why I added a simply filter for it.
|   | Type |
Closes #4119
--
cc: @Pierre-Sassoulas, @hippo91
=> Fix benchmark test

.github/workflows/ci.yaml
I noticed that the CI checks where not run after a commit to a release branch (`2.7`). This small MR adds that.
https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestbranchestags
|   | Type |
=> Run CI checks on every release branch

ChangeLog
Put both 2.7.2 and 2.8.0 in the changelog so cherry-picking is easier (also add the changelog created in 2.7 branch).
|   | Type |
=> Retcon the changelog after 2.7.1 release

.github/ISSUE_TEMPLATE/1_Bug_report.md, .github/ISSUE_TEMPLATE/2_Feature_request.md, .github/workflows/ci.yaml, ChangeLog, pylint/checkers/typecheck.py, pylint/utils/utils.py, tests/functional/m/member_checks.py
Fix #4123 issue about "False positive on `Enum.__members__.items()`". I add a conditional at `_emit_no_member` function in typecheck.py.
I am curious if there are any other cases similar to this one.
|   | Type |
Closes #4123
=> Fix False positive on Enum.__members__.items()

CONTRIBUTORS.txt, ChangeLog, pylint/__main__.py, tests/test_self.py
Hello @PCManticore, can you please review this since you wrote the initial implementation of the `sys.path` fix?
51c646bf70a6e0a86492bfd2ddd1885671d64d67 only stripped the first dangerous `sys.path` entry, causing problems when `PYTHONPATH` starts or ends with a colon.
This commit ensures all bad entries are removed. I consider this harmless but I might be wrong, please let me know if I am missing something.
I have added a new block to `test_do_not_import_files_from_local_directory` in order to make sure that pylint does not fail when `PYTHONPATH` ends with a colon. This test would always fail without the change to `pylint/__main__.py `
|   | Type |
=> Properly strip dangerous sys.path entries (not just the first one)

.github/dependabot.yml, .github/workflows/ci.yaml, .pre-commit-config.yaml, ChangeLog, README.rst, pylint/__pkginfo__.py, requirements_docs.txt, requirements_test.txt, requirements_test_min.txt, requirements_test_pre_commit.txt, requirements_test_pypy.txt, tests/test_self.py, tox.ini
Replaces: #4111
It started with just some CI improvements, but got a bit bigger in the end.
Since almost all changes are workflow related it should be possible to later include the MR in the `2.7.1` release.
**Changes**
* CI: Improve usage of pinned astroid version
* CI: Add caching for Windows job (whole suite now takes 4:30 - 5:00, instead of 7:00min)
* Fixed some tests that occurred during the Windows CI run
* CI: Use specific versions for Github Actions
* Update requirements
* Pin all `test` requirements to current versions
* Rename `requirements _test_pypy.txt` to `requirements_test_min.txt`
* Moved some dependencies from `min` to `test`
* Updated `coverage` dependency to `==5.4.0`, instead of `<5.0`
* Use `pytest-cov` as wrapper for `coverage`
* Pin `docs` requirements to current …
=> Workflow and packaging improvements

pylint/__pkginfo__.py, pylint/checkers/classes.py, requirements_test_min.txt, tests/functional/t/try_except_raise_crash.py, tests/functional/t/try_except_raise_crash.rc, tests/functional/t/try_except_raise_crash.txt
- Update astroid version (Replaces #4130)
- Fix pylint tests
- Remove `TypedDict` hotfix. Not necessary anymore since now included in astroid.
|   | Type |
Closes: #4154
=> Modify tests for astroid update

ChangeLog, pylint/checkers/base.py, tests/functional/n/name_preset_snake_case.py, tests/functional/n/name_preset_snake_case.txt
Fixes an issue where Enum constants would be name checked as `class_attributes` and thus the name preset didn't apply correctly. The Enum check was introduced with #3896
This could be included in a `2.7.3` release if that is planned.
cc: @iFreilicht
|   | Type |
Closes: #4149
=> Fix Enum invalid name with snake_case preset

CONTRIBUTORS.txt, ChangeLog, doc/whatsnew/2.7.rst, pylint/checkers/variables.py, tests/functional/r/redefined_builtin_allowed.py, tests/functional/r/redefined_builtin_allowed.rc, tests/functional/r/redefined_builtin_allowed.txt
Some builtins have little-to-no use in application code while being
convenient as variables names (e.g. id, dir). New option allows
to configure allowed to override names for redefined-builtin checker.
|   | Type |
Closes #3263
=> Add allow-redefined-builtins option to variable checker

ChangeLog, pylint/__init__.py, pylint/__main__.py, tests/test_self.py
This MR changes how `sys.path` is stripped of dangerous paths. #4153 removed all mentions of `os.getcwd()` even if pylint was installed in editable mode. See #4161
It will now strip all **consecutive** entries from the beginning of `sys.path` and thus abort after it finds one path that should be kept.
@sbraz Would that work in your case? The tests are passing.
--
cc: @Pierre-Sassoulas 
|   | Type |
Closes #4161
=> Fix sys.path bug

ChangeLog, pylint/checkers/design_analysis.py, tests/functional/t/typedDict.py
Don't check `too-few-public-methods` for `typing.TypedDict`.
|   | Type |
Closes #4180
=> Exempt TypedDict from too-few-public-methods check

ChangeLog, pylint/checkers/typecheck.py, pylint/checkers/utils.py, tests/functional/m/member_checks_typed_annotations.py, tests/functional/m/member_checks_typed_annotations.txt
Fix false-positive `no-member` for typed annotations without default value.
```py
class A:
myfield: int
class B(A):
pass
a = A()
print(a.myfield)
b = B()
print(b.myfield)  # No longer emits `no-member` warning 
```
|   | Type |
Closes #3167
=> Fix false-positive no-member for typed annotations without default value

tests/input/no_absolute_import.py, tests/test_self.py
Just merging some good code @doublethefish is too shy to request to merge himself :)
|   | Type |
#2674
=> Add tests for disables being ignored with multiple jobs

requirements_test.txt, requirements_test_min.txt
Github dependabot is opening a PR for every single release of a lib otherwise. And we don't need to fix the test dependencies that accurately.
|   | Type |
=> Relax test's dependencies so we're not spammed by dependabot

ChangeLog, doc/whatsnew/2.8.rst, examples/deprecation_checker.py, pylint/checkers/deprecated.py, tests/checkers/unittest_deprecated.py
This PR :
* introduces mechanics of checking deprecated argument. In order to check arguments, the `DeprecatedMixin` class is extended and new callback is introduced: `deprecated_arguments()`. 
* The `DeprecatedMixin` implements `visit_call()` callback for even simpler usage.
* The `DeprecatedMixin` is not abstract class anymore to support overriding just subset of callbacks.
|   | Type |
This PR is first PR fixing #4050. Next PR will extend stdlib checker to support attribute checking.
=> Introduced deprecated attributes

.pre-commit-config.yaml, examples/deprecation_checker.py, pylint/checkers/deprecated.py, tox.ini
The ``pre-commit run pylint`` command was not exactly the same than ``tox -e pylint``
|   | Type |
Closes #4201
=> Fix tox -e pylint and pre commit

ChangeLog, doc/whatsnew/3.0.rst, doc/whatsnew/index.rst, pylint/lint/pylinter.py, pylint/reporters/json_reporter.py, tests/test_self.py, tests/unittest_reporters_json.py
This fix #3504, but I wonder... It looks like the fabled bug that will break countless integration by being fixed. `--score=y` is the default setting, and JSON is probably a prime candidate for automation. Is it reasonable to fix it and ask everyone to change their option to `-s n`? I'm pretty sure no one read the pylint's changelog and even if they do we can't know how many poeple have a working continuous integration that iwll be broken by this.
|   | Type |
Closes #3504
=> Fix score option for JSON export

.pre-commit-config.yaml, examples/deprecation_checker.py, pylint/checkers/deprecated.py, tox.ini
Followup to #4202. I noticed that the `pylint.extensions.mccabe` extension isn't loaded during the `pre-commit` check. There shouldn't be space between the extensions in the list. This was also an issue with the `tox` command. Enabling the extension results in multiple style warnings which is why I chose to disable it for now.
Furthermore, I added the `-sn` argument to hide the score during the pre-commit run and did some small typing changes.
cc: @Pierre-Sassoulas 
|   | Type |
#4201
=> Typing changes + disable unused pylint plugin for pre-commit

tox.ini
Change tox to run formatting instead of pylint by default, to get
flake8, mypy, and other checks. Formatting runs first because some of
the pre-commit hooks may modify files.
|   | Type |
Followup to https://github.com/PyCQA/pylint/issues/4201#issuecomment-792338107
=> tox: run formatting by default

ChangeLog, pylint/checkers/refactoring/len_checker.py, tests/functional/l/len_checks.py, tests/functional/l/len_checks.txt
Wrap `node.infer()` in `try ... except` to catch `astroid.InferenceError` if variable is undefined.
The error seems to be a result of https://github.com/PyCQA/pylint/commit/e50d7331e85a45cab09180cd4321bc91f3bde562
--
This could be included in `2.7.3`
|   | Type |
Closes #4215
=> Fix astroid.Inference error for undefined-variables with len()

ChangeLog, pylint/checkers/typecheck.py
Pylint 2.7.2 has a left over print call in `_emit_no_member` this breaks the expected output using formats such as Junit from junit_pylint etc. It would be really nice if this fix was cherry-picked into pylint 2.7.3 as the output generated by 2.7.2 is currently invalid. 
|   | Type |
=> remove print call from _emit_no_member method

ChangeLog
Fixing the changelog following a mistake while reviewing #4230 
|   | Type |
#4230
=> Fix changelog: print removal need to be in '2.7.3'

doc/release.md
It's hard to tell that a release is official programmatically if the tag is not part of the main branch of the project.
|   | Type |
Closes #4245
=> Update the release documentation for pre-commit autoupdate to works

pylint/testutils/lint_module_test.py, tests/test_functional.py
Only print the verbose error log with the actual output if pytest is executed with `-v`.
--
CC: @Pierre-Sassoulas 
|   | Type |
https://github.com/PyCQA/pylint/pull/4240#issuecomment-808474047
=> Only print verbose logs if pytest -v

ChangeLog, pylint/checkers/variables.py, pylint/constants.py, tests/functional/a/assignment_expression.py, tests/functional/a/assignment_expression.txt
Fixed some small issues with assignment expressions.
**Multiline strings**
```py
l1 = f'The number {(count1 := 4)} ' \
f'is equal to {count1}'
```
This caused a `used-before-assignment` error in Python **3.8**. The root cause is in the builtin `ast` module. Until **3.9**, all nodes where parsed as being on the same line. I added some special case handling for it.
**However this might cause some errors to remain unnoticed!**
**Assignment expression with `Expr`**
```py
foo if (foo := 3 - 2) > 0 else 0
```
**Assignment expression with `AnnAssign` and `AugAssign`**
```py
x2: bool = b2 if (b2 := True) else False
x3 = 0
x3 += b3 if (b3 := 4) else 6
```
--
I believe this could be included with `2.7.3`
|   | Type |
Closes #3763
Closes …
=> Improve handling of assignment expressions

ChangeLog, pylint/checkers/typecheck.py, pylint/checkers/utils.py, tests/functional/p/postponed_evaluation_pep585.py, tests/functional/p/postponed_evaluation_pep585.txt, tests/functional/p/postponed_evaluation_pep585_py39.py, tests/functional/p/postponed_evaluation_pep585_py39.txt
- Use `value.qname()` instead of `value.name` for subscriptable check PEP 585. Only exempt `ClassDefs` that are truly subscriptable.
- Cleanup and refactoring of the PEP 604 check. This should make it much easier to understand it.
I would appreciate if we could include this in `2.7.3` as well.
|   | Type |
Follow up to #4094
=> Improvements to PEP 585 and 604 checks

ChangeLog, pylint/__pkginfo__.py, pylint/checkers/variables.py, requirements_test_min.txt, tests/functional/u/unused/unused_import_class_def_keyword.py
Fix a false-positive the occurs after https://github.com/PyCQA/astroid/pull/919 is merged.
```py
from const import DOMAIN_2  # would be (falsely) flagged as unused-import
class Child:
def __init_subclass__(cls, **kwargs):
pass
class Parent_2(Child, domain=DOMAIN_2):
DOMAIN_2 = DOMAIN_2
```
Furthermore, I added some test cases for #3202.
This MR depends on https://github.com/PyCQA/astroid/pull/919
|   | Type |
Closes #3202
=> Fix false-positive for unused-import on class keyword arguments

ChangeLog, pylint/__init__.py, tests/test_self.py
This MR fixes the regression with `sys.path` filter by checking `PYTHONPATH` **before** removing any additional entries.
This should fix the new issue (#4252) without undoing the previous one.
This should ideally be included in `2.7.3`
|   | Type |
Closes #4252
Followup to
#4153
#4164
--
CC: @sbraz, @Pierre-Sassoulas
=> Fix regression with sys.path filter

CONTRIBUTORS.txt, ChangeLog, pylint/checkers/imports.py, pylint/graph.py, tests/test_import_graph.py
The pre-existing code looks extremely dodgy, but I've tried to avoid making any backwards-incompatible changes while fixing some problems that made it very difficult to work out how to use this option.
Changes:
- Raise error if graphvis is not installed (instead of mistakenly reporting success)
- Fix tempfile creation bug when outputfile includes directories
- Fix bug when using file extension that isn't 3 characters long
- Fix confusing help text
- Rename deprecated .dot extension to .gv
- Default to .png if no extension is specified
|   | Type |
=> Fix various problems with --import-graph filename parsing

ChangeLog, pylint/checkers/utils.py, tests/functional/n/name/name_styles.py, tests/functional/n/name/name_styles.txt
This MR fixes an issue introduced with #4185. The error occurs if a class var with an annotation subscript, that is an attribute, is parsed. See example below
```py
import typing
from typing import List
import custom_path
class Custom:
var: List[int]
var2: typing.List[int]  # error
var3: custom_path.MyOtherClass  # works
```
A workaround, until a new version is released, would be to not use attribute access for class variable annotations with subscript. Instead import the name directly, eg. `from typing import List`.
|   | Type |
Closes #4264
=> Fix issue with annotated class constants

ChangeLog, pylint/__pkginfo__.py, pylint/message/message_handler_mix_in.py, tests/functional/d/disabled_msgid_in_pylintrc.py, tests/functional/d/disabled_msgid_in_pylintrc.rc
Regression in ``2.7.3``
|   | Type |
#4265
=> Fix disabled warning not ignored

tests/test_import_graph.py
Two tests are failing if graphviz is installed. They do not fail in CI because graphviz is not installed. Graphviz might not be super well tested...
|   | Type |
=> Skip test_missing_graphviz if graphviz is installed

ChangeLog, pylint/checkers/utils.py
Fix an issue introduced with the last refactoring of the PEP 585 syntax. `collections.abc.Set` wouldn't be identified correctly, since the `qname()` string contained a comment that should have been deleted.
/CC: @Pierre-Sassoulas, @hippo91 
|   | Type |
--
=> Fix PEP 585 - collections.abc.Set

ChangeLog, pylint/checkers/base.py, pylint/checkers/utils.py, tests/functional/n/name/name_final.py, tests/functional/n/name/name_final.rc, tests/functional/n/name/name_final.txt, tests/functional/n/name/name_final_snake_case.py, tests/functional/n/name/name_final_snake_case.rc, tests/functional/n/name/name_final_snake_case.txt, tests/functional/n/name/name_styles.py, tests/functional/n/name/name_styles.txt
`typing.ClassVar` should not be identified as a class constant for the naming style `class-const`. Instead `typing.Final` should be.
This should probably be included in `2.7.5`
--
`typing.Final` could probably be used to identify module constants as well, but that should be another MR.
|   | Type |
Closes #4277
=> Fix class-const naming style

CONTRIBUTORS.txt, ChangeLog, doc/whatsnew/2.7.rst, pylint/checkers/classes.py, tests/functional/a/access/access_to_protected_members.py, tests/functional/a/access/access_to_protected_members.txt
This is a pretty basic change to allow accessing protected member inside class methods. It performs three checks:
1. Are we in a class method
2. Is the inferred value of the access expression an instance of the class
3. Is the attribute name being accessed an instance or class member of the class
If all three check out, then we allow access to protected members.
I've added tests for the new behaviour, as well as some (potentially redundant) tests to make sure I wasn't picking up attributes of other classes.
I wasn't 100% sure about how to structure the change log entries, but I've added what I thought was correct. If they need to be amended I can certainly do that.
|   | Type |
Closes #1159
=> Allow protected-access in class methods

CONTRIBUTORS.txt, doc/user_guide/output.rst, doc/user_guide/run.rst
https://github.com/PyCQA/pylint/issues/4282:
Explain connection between ``--output-format`` and ``--msg-template``.
Document which command line options are implicitly set through
``epylint.py_run()``
|   | Type |
Closes #4282
=> Extend documentation for issue #4282

ChangeLog, pylint/checkers/base.py, tests/functional/n/name/name_final.py, tests/functional/n/name/name_final.txt, tests/functional/n/name/name_final_snake_case.py, tests/functional/n/name/name_final_snake_case.rc, tests/functional/n/name/name_final_snake_case.txt
This depends on #4279 and should be rebased once it's merged.
Apply the `const-naming-style` to module constants if they are annotated with with `typing.Final`.
|   | Type |
=> Apply const-naming-style to module const annotated with Final

ChangeLog, pylint/checkers/refactoring/refactoring_checker.py, tests/functional/i/inconsistent/inconsistent_returns.py, tests/functional/i/inconsistent/inconsistent_returns.txt
This PR allows declaring a `never-returning-function` by just specifying `NoReturn` as a return type hint.
Thus the emission of `inconsistent-return-statements` message won't be triggered if such functions are used.
|   | Type |
Closes #4122
Closes #4188
=> Bug pylint 4122

ChangeLog, pylint/checkers/variables.py, tests/functional/a/assignment_expression.py, tests/functional/a/assignment_expression.txt
This MR addresses a false-positive that occurred for assignment expressions in function returns.
The following is valid and should not raise an `used-before-assignment` error.
```py
def func():
return f'The number {(count := 4)} ' \
f'is equal to {count}'
```
This is a followup to #4253
|   | Type |
Closes #4301
=> Fix false-positive ``used-before-assignment`` in function returns

ChangeLog, pylint/checkers/refactoring/refactoring_checker.py, tests/functional/i/inconsistent/inconsistent_returns.py, tests/functional/i/inconsistent/inconsistent_returns.txt
During detection of `inconsistent-return-statements`, consider that an `assert False` statement is equivalent to a return node.
|   | Type |
Closes #4019
=> Bug pylint 4019

ChangeLog, pylint/checkers/typecheck.py, tests/functional/d/duplicate_bases.py
Previously an attribute access to a class which has duplicate bases would result in an `astroid.DuplicateBasesError`.
Note: The error for `duplicate-bases` was / is still printed.
**Without MR**
```bash
************* Module functional.d.duplicate_bases
tests/functional/d/duplicate_bases.py:5:0: E0241: Duplicate bases for class 'Duplicates' (duplicate-bases)
File "/Users/.../pylint/venv-39_link/bin/pylint", line 33, in <module>
sys.exit(load_entry_point('pylint', 'console_scripts', 'pylint')())
File "/Users/.../pylint/pylint/__init__.py", line 24, in run_pylint
PylintRun(sys.argv[1:])
File "/Users/.../pylint/pylint/lint/run.py", line 358, in __init__
linter.check(args)
File "/Users/.../pylint/pylint/lint/pylinter.py", …
```
=> Don't show ``astroid.DuplicateBasesError`` for attribute access

.flake8, pylint/config/option_manager_mixin.py, pylint/lint/pylinter.py, pylint/message/message_handler_mix_in.py, pylint/message/message_id_store.py, tests/message/unittest_message_id_store.py
Before working on the unknown message in pylintrc disable/enable, some fix came to mind.
Inspired by #4265
=> Small refactor before adding ``unknown-message-in-pylintrc`` warning

pylint/checkers/utils.py
Small performance improvement for PEP 585 check.
Fail early if `value.qname() not in SUBSCRIPTABLE_CLASSES_PEP585` and only then check for parent in while loop.
--
=> Small performance improvement (PEP 585 check)

CONTRIBUTORS.txt, ChangeLog, elisp/pylint.el
The function `tramp-dissect-file-name` now returns a `tramp-file-name` structure instead of an array. Therefore, the function `aref` can no longer be used to extract the `filename` from a tramp file. This fix correctly extracts the `filename` from the `tramp-file-name` structure by using the emacs built-in function `cl-struct-slot-value`.
=> fix emacs pylint error when running with tramp

ChangeLog, pylint/checkers/utils.py, tests/functional/p/postponed_evaluation_pep585.py, tests/functional/p/postponed_evaluation_pep585.txt, tests/functional/p/postponed_evaluation_pep585_error.py, tests/functional/p/postponed_evaluation_pep585_error.txt, tests/functional/p/postponed_evaluation_pep585_py39.py
This MR fixes a false-negative for invalid PEP 585 syntax inside functions if postponed evaluation is enabled.
```py
from __future__ import annotations
import typing
def func3():
AliasInvalid2 = list[int]  # [unsubscriptable-object]
cast_variable2 = [1, 2, 3]
cast_variable2 = typing.cast(list[int], cast_variable2)  # [unsubscriptable-object]
var19: list[int]
func3()
```
After `func3()` is called, python raises a runtime exception.
Previously both `unsubscriptable-object` errors would remain undetected.
--
**Update**: Found another bug
```py
from __future__ import annotations
import typing
def func4(arg=list[int]):  # [unsubscriptable-object]
pass
func4()
```
This was also undetected previously.
| --- | …
=> Improve check for invalid PEP 585 syntax inside functions

doc/user_guide/run.rst
A directory containing a __init__.py file is called a package, as per https://docs.python.org/3/tutorial/modules.html#packages
Use Python official terminology to not confuse people
=> Use Python official doc's terminology

pylint/utils/ast_walker.py
Improve exception / crash debugging by printing the node and file on which the exception occurred.
Example  output:
```
Exception on node <If l.19 at 0x7f81f0290430> in file '/../pylint/test2.py'
File "/../pylint/venv-39_link/bin/pylint", line 33, in <module>
sys.exit(load_entry_point('pylint', 'console_scripts', 'pylint')())
File "/../pylint/pylint/__init__.py", line 24, in run_pylint
PylintRun(sys.argv[1:])
File "/../pylint/pylint/lint/run.py", line 358, in __init__
linter.check(args)
File "/../pylint/pylint/lint/pylinter.py", line 873, in check
self._check_files(
File "/../pylint/pylint/lint/pylinter.py", line 907, in _check_files
self._check_file(get_ast, check_astroid_module, name, filepath, modname)
File …
```
=> Improve exception debugging

pylint/checkers/refactoring/refactoring_checker.py, tests/functional/c/consider/consider_using_min_max_builtin.py
Fix crash for
```py
var = 1
if var == -1:
var = None
```
Since this checker hasn't been released yet, I don't think it's necessary to write a changelog entry.
Closes: #4379
/CC: @Pierre-Sassoulas, @Qwiddle13, @manderj
=> Fix crash min-max refactoring checker

ChangeLog, pylint/checkers/utils.py
PEP 563, postponed evaluation of type annotations, will be delayed, at least until Python 3.11
Since it's not yet clear when exactly it will become the default, I propose to remove the check for now and add it back once we know more.
https://mail.python.org/archives/list/python-dev@python.org/thread/CLVXXPQ2T2LQ5MP2Y53VVQFCXYWQJHKZ/
--
=> Don't auto-enable postponed evaluation of type annotations with PY310

ChangeLog, doc/user_guide/run.rst, doc/whatsnew/2.8.rst, pylint/lint/run.py, tests/test_self.py
This PR is a proposal for closing #1070.
It adds a new option ``--output-file`` which can be optionally specified.
If set, all messages and reports will be saved to the specified file instead of being printed to stdout.
It can be combined with all of the existing reporters/output formats.
Closes #1070
=> Enhancement 1070 file output

ChangeLog, doc/whatsnew/2.8.rst, pylint/__init__.py, pylint/__pkginfo__.py
There was a problem in the code given in the changelog, and we needed it in a more visible section in What's new
Closes #4399
=> Remove 2.8.0 breaking changes in ``__pkginfo__``

README.rst
Unfortunately the image is still broken on PyPI: https://pypi.org/project/pylint/
I should have used the link to `raw.githubusercontent.com` instead: https://stackoverflow.com/a/46875147
Before we do another MR after that, should we use links to a fixed version? At the moment, all links to Github are to the `master` branch. What do you think?
#4397
=> Fix image link in readme

ChangeLog, pylint/__pkginfo__.py
After 2.8.1 `__pkginfo__.numversion` was now a list which broke pylint-django. See #4405 
This avoids breaking pylint-django like described here https://github.com/PyCQA/pylint-django/issues/323
Not sure if it would make sense to fix here or downstream
Closes #4405
=> Keep __pkginfo__.numversion a tuple

ChangeLog, doc/release.md, doc/whatsnew/2.9.rst, pylint/__pkginfo__.py, setup.cfg, setup.py
Move to scm_setuptools for easier release. Update the release doc.
#4399 #4400
=> Use scm setuptools for auto-versionning

tests/lint/unittest_expand_modules.py
`expand_modules` doesn't guarantee the order of yielded entries.
Closes: #4417
=> tests: Sort for comparison in test_expand_modules

ChangeLog, doc/whatsnew/2.9.rst, pylint/checkers/design_analysis.py, tests/functional/t/too/too_many_ancestors.py, tests/functional/t/too/too_many_ancestors.txt
Fix false-positive `too-many-ancestors` by ignoring pre-defined builtin classes when calculating the number of ancestors. The list isn't complete but should cover most cases.
Closes #4166
Closes #4415
=> Fix too-many-ancestors

.pre-commit-config.yaml, CONTRIBUTORS.txt, ChangeLog, doc/whatsnew/2.8.rst, pylint/checkers/deprecated.py, pylint/checkers/stdlib.py, tests/functional/d/deprecated/deprecated_class_py33.py, tests/functional/d/deprecated/deprecated_class_py33.rc, tests/functional/d/deprecated/deprecated_class_py33.txt
According to Python documentation of module `collections`[1], classes in `_collections_abc`[2] will be moved from `collections` to `collections.abc`. And now Pylint hasn't checked it.
This PR add ``deprecated-class`` to check deprecated class that be imported or called, and could check the deprecation above.
**Unsupport scenario**
I haven't found a proper method that could detect the code below. Maybe it could be implemented in future.
```
import collections
isinstance(None, collections.Iterable)
```
[1]https://docs.python.org/3/library/collections.html
[2]https://github.com/python/cpython/blob/3.9/Lib/_collections_abc.py#L18
Closes #4388
=> Add new warning ``deprecated-class`` #4388

pylint/checkers/deprecated.py, pylint/checkers/stdlib.py, tests/checkers/unittest_deprecated.py
This PR adds support for checking deprecated class arguments. Hence, we can check deprecated arguments of `functools.partialmethod` even it is defined as a class.
=> Add support for checking deprecated class arguments.

CONTRIBUTORS.txt, ChangeLog, doc/whatsnew/2.9.rst, pylint/lint/pylinter.py, pylint/lint/run.py, tests/test_self.py
The current `--fail-under` option actually is more of a "do not fail over", whereby if the score is higher, the return code is zero, regardless of any types of errors.
This means that you cannot e.g. fail on
- score less than 7.0 OR
- any error-category messages
which for obvious reasons really restricts the utility of `--fail-under`.
The new `--fail-on` specifies messages/categories to enable that, if detected, will not return non-zero error code, regardless of what `--fail-under` is set to. For example to catch the above case, we can do:
```
$ pylint --fail-under=7.0 --fail-on=E myfile.py
```
If a category is specified, it will use already-enabled checks only (it will not enable every message/check in that category). …
=> Add --fail-on option (#4227)

tests/test_self.py
The last python updates (`3.8.10` and `3.9.5`) seem to have broken a test. Unfortunately, I wasn't able to determine the exact issue. The best I got is that it's probably some kind of global state. It occurred when `test_parallel_execution_missing_arguments` and `test_can_list_directories_without_dunder_init` where executed after one another.
https://github.com/PyCQA/pylint/blob/7167442a294bd9dac498724557f0d737bfad9b58/tests/test_self.py#L303-L304
https://github.com/PyCQA/pylint/blob/7167442a294bd9dac498724557f0d737bfad9b58/tests/test_self.py#L1080-L1093
Anyway, this change should fix the test.
=> Fix broken tests

ChangeLog
=> Fix changelog

ChangeLog, pylint/checkers/imports.py, pylint/checkers/stdlib.py, pylint/config/man_help_formatter.py, pylint/config/option.py, pylint/config/option_manager_mixin.py, pylint/config/option_parser.py, pylint/config/options_provider_mixin.py
This PR moves checking of stdlib deprecated modules to stdlib checker. This is more natural place for having checks of deprecated modules and also now python version is taken into account during the checks. Imports check still has `--deprecated-modules` switch but now the default value is empty list. Moreover, multiple new deprecated modules are added.
=> Moved stdlib module deprecation from imports checker to stdlib checker

.github/dependabot.yml
Prevent `dependabot` from rebasing MRs after the branch was updated (e.g., because another MR was merged).
https://docs.github.com/en/code-security/supply-chain-security/configuration-options-for-dependency-updates#rebase-strategy
=> Change rebase-strategy dependabot

tox.ini
Update the `pre-commit` version used for `tox`. The `requirements_text.txt` file is already up to date.
https://github.com/PyCQA/pylint/blob/6b3c49895f5e1750e2cc6c4e0c4e0c5460056cd2/requirements_test.txt#L5
=> Tox - update pre-commit version

.github/workflows/ci.yaml, pylint/checkers/typecheck.py, pylint/testutils/get_test_info.py, tests/functional/m/member/member_checks_py37.py, tests/test_func.py, tests/test_self.py, tox.ini
In order to be ready when python 3.10 goes out. For python 3.9 we were a little late and we had to do everything almost at the time when it became the default python in the new debian. See #3959 
|   | Type |
=> Add python 3.10 dev in the CI

ChangeLog, doc/whatsnew/2.9.rst, pylint/checkers/strings.py, requirements_test.txt, requirements_test_pre_commit.txt, tests/functional/i/inconsistent/inconsistent_returns.py, tests/functional/i/inconsistent/inconsistent_returns.txt, tests/functional/i/inconsistent/inconsistent_returns_noreturn.py, tests/functional/i/inconsistent/inconsistent_returns_noreturn.rc, tests/functional/i/inconsistent/inconsistent_returns_noreturn.txt
This PR fixes compatibility with Python 3.6.0, mainly due to `typing`:
- `typing.Counter` is added in Python 3.6.1, so make the import conditional on TYPE_CHECKING.
- `typing.NoReturn` is added in Python 3.6.2, split the inconsistent_returns tests that need this to it's own file.
- `black`, `pre-commit` and `pyupgrade` require Python 3.6.1 (or later), add `python_full_version` markers so `tox -e py36` works
Closes #4412
=> Fix issues with Python 3.6.0

pylint/checkers/refactoring/recommendation_checker.py
Small logic update and docstring reformatting. -- ``if`` attribute of (List/Dict)Comp nodes are included when using ``.get_children()``
=> Removed redundant logic from ``consider-using-dict-items``

CONTRIBUTORS.txt, ChangeLog, doc/user_guide/message-control.rst
There were two errors in the User Guide example for block disables. The code comments didn't agree with the disable commands. In one case, the disable command was wrong; in the other, the comment was wrong.
=> [Docs] Fix errors in block disables paragraph in User Guide

ChangeLog, doc/whatsnew/2.9.rst, pylint/checkers/imports.py, tests/extensions/test_empty_comment.py, tests/functional/i/import_aliasing.py, tests/functional/i/import_aliasing.txt, tests/functional/u/useless/useless-import-alias.txt
Implemented this new check to check for instances where
```python
import x.y.z as z
```
could be refactored to 
```python
from x.y import z
```
Also refactored some doc/ code to use typehints
Closes #2309
#2402
#2423 -> should I name it instead to ``consider-use-from-import`` as some styleguides might suggest otherwise?
=> Implemented new check ``consider-using-from-import``

CONTRIBUTORS.txt, ChangeLog, doc/user_guide/output.rst, doc/whatsnew/2.9.rst, pylint/lint/pylinter.py, pylint/reporters/__init__.py, pylint/reporters/multi_reporter.py, tests/unittest_reporting.py
This PR allows users to specify more than one output format by passing a comma-separated list `output-format` like this:
```sh
--output-format=text,json
```
You can also set the output file for each output format by specifying it after a colon like this:
```sh
--output-format=text:path/to/pylint-report.txt,json:different/path/to/pylint-report.json
```
Without the `:path` part, the default is to output to `stdout`.
Closes #1798
=> Multiple `output-format` support

ChangeLog, pylint/checkers/refactoring/refactoring_checker.py, tests/functional/u/unnecessary/unnecessary_comprehension.py, tests/functional/u/unnecessary/unnecessary_comprehension.txt
Improved help text for ``unnecessary-comprehension`` -- now provides suggestion of what could be used instead.
E.g:
```python
a_dict = dict()
[(k, v) for k, v in a_dict.items()]  # [unnecessary-comprehension]
```
Help text:
```
unnecessary-comprehension:17:0::Unnecessary use of a comprehension, use list(a_dict.items()) instead.
```
| ✓   | :memo:  Documentation   |
Closes #4499
=> Added suggestion in helptext for ``unnecessary-comprehension`` checker

doc/whatsnew/2.9.rst
A small formatting oversight for my previous PRs made for the ``unused-private-member`` checker -- sorry about that :sweat: 
=> Fixed minor doc formatting in doc/whatsnew/2.9.rst

MANIFEST.in, setup.cfg
`setuptools_scm` auto-includes all files managed by git in the source distribution except for excludes specified in `MANIFEST.in`. https://github.com/pypa/setuptools_scm#file-finders-hook-makes-most-of-manifestin-unnecessary
`wheel` still adheres to the `options.packages.find` section config in `setup.cfg` for the build distribution.
=> Improve build config

ChangeLog, pylint/checkers/design_analysis.py, pylint/checkers/refactoring/recommendation_checker.py, pylint/config/option_manager_mixin.py, tests/functional/c/consider/consider_using_enumerate.py, tests/functional/c/consider/consider_using_enumerate.txt
Fixed false negative of ``consider-using-enumerate`` not emitting when iterating over an attribute.
Also, included test scenario described in #3657 
Closes #3657
=> Fixed false negative of ``consider-using-enumerate`` on attributes

CONTRIBUTORS.txt, ChangeLog, doc/whatsnew/2.9.rst, pylint/config/option_manager_mixin.py
Cast floats to string so ``ConfigParser`` can handle them, just like ints.
Closes #4518
=> Handle floats when parsing pyproject.toml (#4518)

ChangeLog, requirements_test_min.txt, setup.cfg, tests/functional/i/invalid/l/invalid_length_returned.py, tests/functional/i/invalid/l/invalid_length_returned.txt, tests/functional/l/logging_format_interpolation.py, tests/functional/l/logging_format_interpolation.txt, tests/functional/n/no/no_self_use.py
Upgrade astroid so we get the latest fixes.
https://github.com/PyCQA/pylint/pull/4471
https://github.com/PyCQA/pylint/pull/4473
https://github.com/PyCQA/pylint/pull/4428
https://github.com/PyCQA/pylint/pull/4348
https://github.com/PyCQA/pylint/pull/4325
=> Require astroid 2.5.7

ChangeLog, tests/functional/t/typing_generic.py
Add regression test. This is fixed with the current `astroid` master branch.
```py
from abc import ABC
from typing import Generic, TypeVar
Anything = TypeVar("Anything")
MoreSpecific = TypeVar("MoreSpecific", str, int)
class A(ABC, Generic[Anything]):
def a_method(self) -> None:
print("hello")
class B(A[MoreSpecific]):
pass
class C(B[str]):
pass
c = C()
c.a_method()  # should NOT emit no-member error
```
Closes https://github.com/PyCQA/astroid/issues/942
=> Add regression test for no-member with generic base class

ChangeLog, pylint/checkers/classes.py, tests/functional/a/assign/assigning_non_slot_4509.py, tests/functional/a/assign/assigning_non_slot_4509.rc, tests/functional/a/assign/assigning_non_slot_4509.txt
Fix a false-positive for `assigning-non-slot` with base that inherits from `typing.Generic`.
```py
from typing import Generic, TypeVar
T = TypeVar("T")
class Base(Generic[T]):
__slots__ = ()
class Foo(Base[T]):
__slots__ = ['_value']
def __init__(self, value: T):
self._value = value
```
The reason for the issue is that `slots()` is evaluated and cached before any inference tips from astroid are applied.
For classes that directly inherit from `Generic` this is fixed by `astroid`, everything else needs to be handled by `pylint` at least for now. -> [astroid fix](https://github.com/PyCQA/astroid/pull/931/files#diff-bad42d2444679b996b2e5e6d3d1f157ecdd286279465d0cda99d3bd772862f82R169-R173) …
=> Fix false-positive assigning-non-slot with typing.Generic base

ChangeLog, doc/whatsnew/2.9.rst, pylint/checkers/classes.py, pylint/checkers/design_analysis.py, pylint/checkers/exceptions.py, pylint/checkers/logging.py, pylint/checkers/refactoring/refactoring_checker.py, pylint/checkers/strings.py, tests/functional/c/consider/consider_using_namedtuple.py, tests/functional/c/consider/consider_using_namedtuple.txt
Add a new checker to suggest the use of `namedtuples` for constant dictionary values, instead of sub-dicts or lists.
Module level dicts are most often used as mappings and thus don't change. Namedtuples provide some (minor) performance benefits but most importantly will make code more readable in most cases.
Some requirements:
- All dict values must either be dicts or lists. They must all be of the same type
- If the dict values are dicts itself, all dict values must have at least one common key and the current keys of the `sub-dict` must be strings (e.g., ints are no valid fieldnames for namedtuples).
- If all dict values are lists, they must all have the same number of elements > 0 and any dict value can't contain only dicts.
I added the requirements to prevent most false-positives, but …
=> Add new checker ``consider-using-namedtuple``

ChangeLog, doc/whatsnew/2.9.rst, pylint/checkers/variables.py, tests/functional/i/invalid/invalid_all_format.py, tests/functional/i/invalid/invalid_all_format.txt, tests/functional/i/invalid/invalid_all_format_valid_1.py, tests/functional/i/invalid/invalid_all_format_valid_2.py
New checker to catch a common beginner mistake when writing `__all__` as a tuple: missing the trailing comma.
```py
__all__ = ("CONST")  # this is evaluated as a string, not a tuple
__all__ = ("CONST", )
CONST = 42
```
=> Add new checker `invalid-all-format`

ChangeLog, tests/functional/u/unused/unused_variable.py, tests/functional/u/unused/unused_variable.txt
This pull request adds some test cases to the `unused-variable` message related to nested exceptions. 
The current errors emitted for these cases are not complete and that is due to the bug of #4391.
#4391
=> Add test cases to unused-variable message

ChangeLog, doc/whatsnew/2.9.rst, pylint/checkers/classes.py, pylint/checkers/design_analysis.py, pylint/checkers/exceptions.py, pylint/checkers/logging.py, pylint/checkers/refactoring/refactoring_checker.py, pylint/checkers/strings.py, tests/functional/c/consider/consider_using_namedtuple.txt, tests/functional/c/consider/consider_using_namedtuple_or_dataclass.py, tests/functional/c/consider/consider_using_namedtuple_or_dataclass.txt
Followup to #4517
I realized while working on the `MsgDef` change that often `dataclasses` are also a good option instead of `dicts` or `lists`. Since we haven't release `2.9.0` yet, this wouldn't even be a breaking change.
I'm just not sure if `consider-using-namedtuple-or-dataclass` is the best name as it's pretty long. Open to suggestions if we find something better.
=> Update name checker `consider-using-namedtuple` to include `dataclass`

pylint/testutils/lint_module_test.py, tests/test_functional.py
Use `__tracebackhide__ = True` to hide functions from pytest traceback. This is especially useful for the functional test output. https://docs.pytest.org/en/latest/example/simple.html?highlight=tracebackhide
Unfortunately, it isn't possible to hide it for all functions in the call stack. Therefore I've added a helper to keep it at least as short as possible.
**Before**
```
======================================================== FAILURES ========================================================
______________________________________ test_functional[typing_consider_using_alias] ______________________________________
test_file = FunctionalTest:typing_consider_using_alias, recwarn = WarningsRecorder(record=True)
pytestconfig = <_pytest.config.Config object at 0x109b6ab00> …
```
=> Improve traceback for pytest runs

ChangeLog, tests/functional/p/pattern_matching.py, tests/functional/p/pattern_matching.rc
Add basic regression test for Pattern Matching to catch `unused-variable` and `undefined-variable` errors.
Requires: https://github.com/PyCQA/astroid/pull/1010
=> Add regression test for Pattern Matching 3.10

ChangeLog, pylint/extensions/typing.py
Clarify documentation for `typing` extension.
Closes #4545
=> Clarify documentation for `typing` extension

pylint/extensions/typing.rst
Didn't know that the checker class docstring wasn't used for the documenation.
=> Add additional documenation for typing extension

.coveragerc
Add `exclude_lines` setting to `coveragerc` file. Some lines will never be executed. We shouldn't use them to calculate coverage.
https://coverage.readthedocs.io/en/coverage-4.3.3/excluding.html#advanced-exclusion
Example Home-Assistant: [.coveragerc](https://github.com/home-assistant/core/blob/c242e56b8c9eb2b4de51aac24406e638cfa843de/.coveragerc#L1249)
--
Similar to https://github.com/PyCQA/astroid/pull/1022
=> Add exclude_lines coverage

ChangeLog, pylint/checkers/typecheck.py, tests/functional/u/unhashable_dict_key.py, tests/functional/u/unhashable_dict_key.txt
Fix `AttributeError` that occurred when trying to use slice as subscript for dict with Python < 3.9
Instead emit `unhashable-dict-key` error.
```py
{}[1:2]
```
```
...
File "/.../pylint/pylint/checkers/typecheck.py", line 1780, in visit_subscript
inferred = safe_infer(node.slice.value)
AttributeError: 'Slice' object has no attribute 'value'
```
=> Fix error with slice as subscript for dict

pylint/interfaces.py, pylint/reporters/base_reporter.py, pylint/reporters/collecting_reporter.py, pylint/reporters/json_reporter.py, pylint/reporters/multi_reporter.py, pylint/reporters/text.py, pylint/testutils/output_line.py, pylint/testutils/reporter_for_tests.py, tests/extensions/test_broad_try_clause.py, tests/extensions/test_comparetozero.py, tests/test_self.py, tests/testutils/test_output_line.py
We lacked coverage on this and this prevented proper typing.
=> Add ``OutputLine`` tests and typing on ``handle_message``

ChangeLog, MANIFEST.in, appveyor.yml
Appveyor is not used anymore and can be removed.
=> Remove appveyor.yml replaced by github actions

pylint/checkers/base.py, pylint/checkers/format.py
Remove all references to the `astroid.Ellipsis` node.
https://github.com/PyCQA/astroid/pull/1025
=> Remove deprecated `astroid.Ellipsis` node

pylint/checkers/refactoring/recommendation_checker.py, pylint/checkers/refactoring/refactoring_checker.py, pylint/checkers/typecheck.py, pylint/checkers/utils.py
Remove all references of `astroid.Index` and `astroid.ExtSlice` nodes.
https://github.com/PyCQA/astroid/pull/1026
=> Remove deprecated `astroid.Index` and `astroid.ExtSlice` nodes

ChangeLog, tests/functional/e/enum_subclasses.py
`doc/whatsnew/<current release.rst>`.~
Captures the regression tests specified in #1932 and #2062 and fixed by PyCQA/astroid#1020.
Closes #1932. Closes #2062. Depends on PyCQA/astroid#1020.
=> Add regression tests for Enum.name and .value inference

ChangeLog, pylint/lint/pylinter.py, pylint/message/message_handler_mix_in.py, pylint/reporters/text.py, tests/functional/p/plugin_does_not_exists.py, tests/functional/p/plugin_does_not_exists.rc, tests/functional/p/plugin_does_not_exists.txt, tests/test_functional.py
This fix a crash when the configuration is wrong, also it fixe the update process of functional test when the expected output do not exists, it can now be created.
Closes #4555
=> Run the checks anyway when a plugin does not exists in the configuration

ChangeLog, pylint/checkers/utils.py, tests/functional/c/cached_property.py, tests/functional/c/cached_property.rc, tests/functional/c/cached_property.txt
Supersedes #4144 originally authored by @tiagohonorato
Overriding a `property` with `cached_property` currently results in an `invalid-overridden-method` error as the definition for property is too narrow. @hippo91 suggested to use `astroid.bases._is_property` which seems to work well: https://github.com/PyCQA/pylint/issues/4023#issuecomment-770197615
https://docs.python.org/3/library/functools.html#functools.cached_property
Closes #4023
=> Better recognize property decorators

ChangeLog, pylint/checkers/utils.py, tests/functional/r/regression/regression_4612_crash_pytest_fixture.py
And astroid can't infer the name of the decorator when using ``open`` without ``with`` inside the function.
Closes #4612
=> Fix a crash when a test function is decorated with ``@pytest.fixture``

ChangeLog, doc/whatsnew/2.9.rst, pylint/extensions/_check_docs_utils.py, pylint/extensions/docparams.py, tests/extensions/test_check_docs.py, tests/functional/u/useless/useless_type_doc.py, tests/functional/u/useless/useless_type_doc.rc, tests/functional/u/useless/useless_type_doc.txt
Fix false positive ``useless-type-doc`` on ignored argument using ``pylint.extensions.docparams``
when a function was typed using pep484 but not inside the docstring.
Closes #4117
Closes #4593
=> Fix false positive useless type annotation for pep484 typing

CONTRIBUTORS.txt, ChangeLog, pylint/checkers/variables.py, pylint/constants.py, tests/checkers/unittest_variables.py
Prior to this commit `VariableChecker` did not recurse into attribute lookups in type comments. This lead to false positive `unused-import messages` in e.g.
import collections
d = ...  # type: collections.OrderedDict
Fixes #4603.
=> VariableChecker now accounts for attribute lookups in type comments

ChangeLog, doc/user_guide/options.rst, examples/pylintrc, pylint/extensions/confusing_elif.py
A few minor documentation fixes:
- Fix regular expression for camelCase naming style example (#3747)
- Add ``ignore-paths`` to example pylintrc
- Change verbatim name of ``ConfusingConsecutiveElifChecker`` to ``confusing_elif`` so that it does not appear as "Confusing Elif Checker Checker" anymore
- Fix some improperly indented bullet points in ``ChangeLog`` so building the docs works again.
Closes #3747
Closes #4541
=> Documentation fixes

pylint/checkers/stdlib.py
Fixes several issues in #4620:
* Remove duplicates
* Remove SSLSocket methods - the methods cannot be inferred when created by factory SSLContext.wrap_socket
* `ssl.RAND_pseudo_bytes`  -> `_ssl.RAND_pseudo_bytes`
=> Fix deprecated methods from #4620

tests/functional/r/regression/regression_issue_4631.py, tests/functional/r/regression/regression_issue_4631.rc, tests/functional/r/regression/regression_issue_4631.txt
Fux an issue with StopIteration when using ``limit-inference-results=0``
Closes #4631 
Closes https://github.com/PyCQA/astroid/issues/1080
=> Fix a crash with ``StopIteration`` when using ``limit-inference-results=0``

ChangeLog, pylint/checkers/classes.py, tests/functional/u/unused/unused_private_member.py
We can have something else than node with expr.name attribute in this context.
Closes #4638
=> Handle the 'call' use case of unused_private_member

.github/CONTRIBUTING.md, .github/ISSUE_TEMPLATE/2_Feature_request.md, .github/PULL_REQUEST_TEMPLATE.md, .github/workflows/ci.yaml, .github/workflows/codeql-analysis.yml, README.rst, doc/how_tos/custom_checkers.rst, doc/how_tos/transform_plugins.rst, doc/release.md
Rename references from `master` branch to `main`. Should only be applied **after** the branch has been renamed.
https://github.com/PyCQA/astroid/pull/1079
=> Rename refs from `master` to `main`

ChangeLog, pylint/checkers/classes.py, tests/functional/u/unused/unused_private_member.py
The self was forgotten. Also made some small refactor around it following comment made in #4642 
Closes #4644
=> Fix false positive ``unused-private-member`` if class member is accessed via ``self``

ChangeLog, pylint/checkers/similar.py, tests/checkers/unittest_similar.py, tests/input/similar5, tests/input/similar6
Fix a crash caused by the newly introduced ignore-signatures option for similarities checker fails for functions with an empty body with docstring only. Also include some refactor necessary so pre-commit works (trailing whitespace added in report).
Closes #4648
=> Fix ``similarity`` checker fails with ``ignore-signatures`` option enabled on function with docstring-only body

ChangeLog, pylint/checkers/classes.py, tests/functional/u/unused/unused_private_member.py, tests/functional/u/unused/unused_private_member.txt
Handle case where private class attributes are assigned/mutated with: `cls.attrib = ...`
This was forgotten during the initial implementation.
Closes #4657
=> Fix false positive `unused-private-member` if class member is assigned/mutated with `cls`

ChangeLog, doc/whatsnew/2.10.rst, doc/whatsnew/2.9.rst, pylint/checkers/refactoring/refactoring_checker.py, tests/functional/c/consider/consider_using_with.py
The ``contextlib.ExitStack`` class provides a method to automatically call ``__exit__`` on context managers added to its stack when leaving a ``with contextlib.ExitStack() as stack`` block.
If a callable that could be used in a ``with`` block was added to the stack, no R1732 ``consider-using-with`` message should be triggered:
```python
with contextlib.ExitStack() as stack:
_ = stack.enter_context(
open("/sys/firmware/devicetree/base/hwid,location", "r")
)  # must not trigger
```
While ``contextlib.AsyncExitStack`` should theoretically also be covered (as it can be used with synchronous context managers as well), it is currently not possible to implement this, as trying to infer the ``stack.enter_context`` returns ``Uninferable`` in this case...
I …
=> Fix false-positive ``consider-using-with`` when using ``contextlib.ExitStack``

CONTRIBUTORS.txt, ChangeLog, pylint/checkers/similar.py, tests/checkers/unittest_similar.py, tests/input/similar_empty_func_1.py, tests/input/similar_empty_func_2.py
Similarities checker with "ignore-signatures" option enabled ignores functions with empty bodies.
This PR fixes this bug.
|       | Type                   |
| --- | --------------- |
| ✓   | :bug: Bug fix     |
Closes #4652
=> [duplicate-code] Fix ignored empty functions by similarities checker with ignore-signatures option enabled

pylint/testutils/lint_module_test.py, pylint/testutils/reporter_for_tests.py, tests/functional/r/regression/regression_issue_4631.txt
There was a problem when there was no output from pylint but an expected output in the functional tests.
=> [test utils] No output with an expected output now fail properly

ChangeLog, pylint/checkers/deprecated.py, pylint/checkers/imports.py, pylint/checkers/utils.py, tests/checkers/unittest_deprecated.py, tests/functional/d/deprecated/deprecated_relative_import/dot_relative_import.py, tests/functional/d/deprecated/deprecated_relative_import/dot_relative_import.rc, tests/functional/d/deprecated/deprecated_relative_import/dot_relative_import.txt, tests/functional/d/deprecated/deprecated_relative_import/subpackage/dot_dot_relative_import.py, tests/functional/d/deprecated/deprecated_relative_import/subpackage/dot_dot_relative_import.rc, tests/functional/d/deprecated/deprecated_relative_import/subpackage/dot_dot_relative_import.txt
This PR adjust deprecated module check of from imports to use absolute import name. It helps avoid detecting deprecated
modules in relative imports.
Closes #4629
=> Use absolute import qualified module name for deprecated module check

ChangeLog, doc/whatsnew/2.9.rst, pylint/checkers/refactoring/refactoring_checker.py, tests/functional/c/consider/consider_using_with_open.py
For details see #4676 - things like ``open`` calls inside ternary conditionals used in a ``with`` were incorrectly flagged with the ``consider-using-with``, because the check if this call happens inside the items of a ``with`` only looked at the first parent node.
This is now expanded to check all parents until we reach the enclosing frame.
I also ran ``pylint`` over a few other codebases (black, requests, pip, twine) and (luckily 😁) found no new edge cases.
But I somehow have a feeling that this won't stay the last fix of false-positives for ``consider-using-with``... 
Closes #4676
=> Fix false-positive ``consider-using-with`` for ternary conditionals in ``with`` items

CONTRIBUTORS.txt, ChangeLog, pylint/checkers/typecheck.py, tests/functional/r/regression/regression_4688_duplicated_bases_member_hints.py, tests/functional/r/regression/regression_4688_duplicated_bases_member_hints.txt
This fixes #4687.
Missing type hints won't fail hard anymore when applied to an instance with an MRO with duplicated names.
Closes #4687
=> Catch MRO error when applying missing hints feature.

pylint/checkers/variables.py, tests/functional/r/regression/regression_4680.py, tests/functional/r/regression/regression_4680.txt
I have a feeling there could be an easier way to get the name of the metaclass node but for now we'll just fix the crash.
Closes #4680
=> [undefined-variable] Fix crash when metaclass was parsed as an attribute

CONTRIBUTORS.txt, ChangeLog, pylint/checkers/imports.py
The `consider-using-from-import` checker only works on submodule imports, not member imports because, e.g., `import pandas.DataFrame` is not valid syntax (`import <member>`). This PR removes "member" from the documentation and changes the example to a submodule import.
By the way, I could not find a justification for this checker in the documentation or in the PR that created it. Is it that the `from ... import` syntax uses less characters? (Personally, I prefer `import a.b as b` to `from a import b` to avoid problems with someone later defining `b` as a member in `a.py` and that taking precedence over the submodule import but I didn't know if I was missing another advantage to the `from` syntax).
| ✓   | :scroll: Docs …
=> Clarify documentation for consider-using-from-import

ChangeLog, pylint/checkers/base.py, tests/functional/u/unreachable.py, tests/functional/u/unreachable.txt
The `unreachable` code warning should not be emitted for empty generator functions.
```py
def func():
return
yield
```
Closes #4698
=> Don't emit `unreachable` warning for empty generator functions

doc/release.md
Documenting the release process. @cdce8p would you like to release the next version so you can have an opinion on how to make this better ? I'm not really satisfied with the way we have to launch tbump two times and interrupt it the second time. We could also unprotect the main branch like in astroid so we can push directly on it as maintainers (?).
=> Document the release process

ChangeLog, pylint/checkers/utils.py, tests/functional/i/invalid/invalid_overridden_method.py, tests/functional/i/invalid/invalid_overridden_method.txt
``invalid-overridden-method`` should not be raised if decorator has a nested property function.
```py
def my_property(func):
@property
def _wrapper(self):
pass
return _wrapper
class A:
@property
def foo(self):
return True
class B(A):
@my_property
def foo(self):
return False
```
Closes #4368
=> Fix invalid-overridden-method with nested property

CONTRIBUTORS.txt, ChangeLog, pylint/lint/pylinter.py, pylint/lint/run.py, tests/regrtest_data/fail_on.py, tests/regrtest_data/fail_on_info_only.py, tests/test_self.py
This fixes a bug in which pylint can still return a zero exit code when using --fail-on even if the specified issue occurs when the issues matched are all of info type.
Without this patch, running: `pylint --fail-on=useless-suppression a.py` when `a.py` contains:
```
"""Test file to trigger an useless-suppression error msg"""
pass
```
returns exit code 0 despite matching the useless-suppression (info) issue.
This is related to Issue #4296 and #3363. However although it will provides some other options for these issues, I don't think it will fully resolve them.
=> Ensure --fail-on always returns a non-zero exit code when issue is matched

ChangeLog, pylint/checkers/classes.py, tests/functional/u/unused/unused_private_member.py
Fix false positive when using ``__new__`` in a class, this is done by performing the following:
1. If the current method is ``__new__``, get all returned object names by the method
2. Check and do not emit when the current expression of the attribute is in this list of object names, and a ``self.attribute`` of the same attribute was consumed in other methods of the same class
Closes #4668
=> [unused-private-member] add logic to check for obj attributes when using ``__new__``

ChangeLog, pylint/checkers/imports.py, pylint/checkers/utils.py, pylint/checkers/variables.py, tests/functional/i/import_error.py, tests/functional/i/import_error.txt, tests/functional/u/ungrouped_imports.py
Ignore the following error messages if import is in guarded if block (`sys.version_info` or `typing.TYPE_CHECKING`):
* `import-error`
* `no-name-in-module`
* `ungrouped-imports`
Although just ignoring them isn't ideal, that seems to be the best we can do here. Besides, a fix seems to be highly requested.
Closes #3285
Closes #3382
=> Ignore import errors if in guarded import block

ChangeLog, tests/functional/t/typedDict.py
Depends on https://github.com/PyCQA/astroid/pull/1101
Closes #4715
=> Add regression test TypedDict not-callable

CONTRIBUTORS.txt, ChangeLog, doc/whatsnew/2.10.rst, pylint/checkers/stdlib.py
It was deprecated in 3.3 and removed in 3.8.
=> Added `time.clock` to deprecated functions/methods for python 3.3.

ChangeLog, doc/whatsnew/2.9.rst, pylint/checkers/refactoring/refactoring_checker.py, tests/functional/c/consider/consider_using_with.py, tests/functional/c/consider/consider_using_with.txt
#4721 introduced a crash if a context manager was not assigned to a variable or attribute, but instead to something like a list or dictionary item.
``_append_context_managers_to_stack()`` now ignores assignments where the left hand side is not assigned to something with a name. This will lead to ``consider-using-with`` to be triggered when ``visit_call()`` is called.
Note that this would have been the same behaviour as before #4721, so this is not a step back. 
Of course it would be desirable if it is possible to properly detect if the list/dict item is extracted later on and used in a ``with`` block, like so:
```python
import subprocess
job_dict = {}
job_dict["new"] = subprocess.Popen("ls")  # will currently emit consider-using-with
for name, job in …
```
=> Fix crash if a callable returning a context manager was assigned to a list or dict item

ChangeLog, requirements_test_min.txt, setup.cfg, tests/functional/r/regression/regression_4439.py, tests/functional/r/regression/regression_4439.txt
Add a regression test for AttributeError for Subscript object (#4439)
Closes #4439
=> Add a regression test for AttributeError for Subscript object

CONTRIBUTORS.txt, pylint/checkers/variables.py, tests/functional/u/undefined/undefined_variable.py, tests/functional/u/undefined/undefined_variable.txt
This is a proposed fix for an issue where defining a function decorated with a list comprehension that shares argument name, and the argument is used twice in the list comprehension, it shows an undefined-variable error.
To put it in code:
```python3
def decorator(seq):
return lambda f: f
@decorator(x * x for x in "123")
def func(x):
pass
```
This wrongfully shows an `undefined-variable` error since version at least 2.7.
```python3
def decorator(seq):
return lambda f: f
@decorator(x for x in "123")
def func(x):
pass
```
This is rightfully OK on the current `main`.
This probably will need changes, but I am not familiar enough with the codebase to go better about it.
| ✓   | :bug: Bug fix …
=> [#3791] propose a fix

.github/ISSUE_TEMPLATE/BUG-REPORT.yml, .github/ISSUE_TEMPLATE/FEATURE-REQUEST.yml, .github/ISSUE_TEMPLATE/QUESTION.yml, .github/ISSUE_TEMPLATE/config.yml
Follow up to #4742
* Some improvements to the current issue forms
* Allow black issues. Especially useful in cases where the default templates don't match.
=> Improve Issue forms

tests/test_pylint_runners.py
This makes test_pylint_runners use a tmpdir for any output files.
As a result the classes.dot file created during testing will now be
removed after testing has finished.
This closes #4762
Does this need a mention in the changelog? Does not seem relevant for end-users.
=> Remove classes.dot after testing #4762

ChangeLog, doc/whatsnew/2.10.rst, pylint/checkers/typecheck.py, tests/functional/n/no/no_member_if_statements.py, tests/functional/n/no/no_member_if_statements.txt
Omit `no-member` errors if attribute / method access is guarded behind if statement.
This change doesn't implement `control-flow` logic. Instead I chose to check for an `IF` / `IFExp` node in the node parents and evaluate it. That doesn't solve all issue, especially not those with `assert` #4693, but I would never the less consider it an improvement.
As this is a larger change, I would like to target `2.10` for it.
```py
from datetime import datetime
value = "Hello World"
value.isoformat()  # [no-member]
if isinstance(value, datetime):
value.isoformat()  # This is now fixed and doesn't emit 'no-member' anymore
```
--
Ref #1162 (not closed, but issue would be addressed)
Closes #1990
Closes …
=> Omit no-member error if guarded behind if stmt

ChangeLog, pylint/lint/parallel.py, tests/test_check_parallel.py
It closes #4118 by passing the option to the merger instance (the `recombined.min_lines = self.min_lines` part).
While working on it @doublethefish spotted the score was wrong: errors raised during the merge were not accounted for, it is now (the `linter.stats = _merge_stats([linter.stats] + all_stats)` part).
I tried to implement a test to avoid regression, I'm not fluent with pylint internals yet, reviews welcome ♥
|   | Type |
Closes #4118
=> Similar check: Passe min_lines to recombined.

ChangeLog, doc/whatsnew/2.10.rst, pylint/checkers/classes.py, pylint/checkers/python3.py, pylint/checkers/refactoring/refactoring_checker.py, pylint/checkers/stdlib.py, pylint/checkers/typecheck.py, pylint/extensions/code_style.py, pylint/lint/pylinter.py, script/bump_changelog.py, tests/functional/ext/code_style/code_style_consider_using_tuple.py, tests/functional/ext/code_style/code_style_consider_using_tuple.txt
Extend `consider-using-tuple` check from the `CodeStyleChecker` extension to recognize lists / sets in `in` comparisons.
**Some examples**
```py
x in [1, 2, 3]  # [consider-using-tuple]
if x in [1, 2, 3]:  # [consider-using-tuple]
pass
assert x in {1, 2, 3}  # [consider-using-tuple]
```
Previously the check was only used inside `For` looks and `Comprehensions`.
=> Extended `consider-using-tuple` check to cover `in` comparisons

CONTRIBUTORS.txt, tests/lint/unittest_lint.py
pylintd is a directory, so os.remove throws IsADirectoryError
Do I have to add myself CONTRIBUTORS for a small change like this? Should I add the fix to the changelog?
Closes #4780
=> Fix IsADirectoryError in tests/lint/unittest_lint

ChangeLog, pylint/checkers/classes.py, tests/functional/u/unused/unused_private_member.py, tests/functional/u/unused/unused_private_member.txt
Add logic for checking (private) nested functions in a class which was causing a false-negative as reported in 
#4673 
also, improve error message for nested functions
Closes #4673
=> [unused-private-member] add logic for checking nested functions

ChangeLog, pylint/checkers/classes.py, tests/functional/u/unused/unused_private_member.py, tests/functional/u/unused/unused_private_member.txt
Simple fix to avoid false-positive to check for private attributes and do not emit if it was called with the Class's name.
Done by using a boolean condition and comparing it to the node's (classdef) name
Also, added a pylint ignore as more boolean expressions are needed here
Closes #4681
=> Fix false-positive of `unused-private-member` with class name

ChangeLog, pylint/checkers/classes.py, tests/functional/u/unused/unused_private_member.py, tests/functional/u/unused/unused_private_member.txt
| ✓   | :page_facing_up:  Documentation          |
Added logic to prevent checking attributes of attributes, and only check for the first level of attributes.
Closes #4755
=> Fix crash for `unused-private-member` when there are nested attributes

ChangeLog, doc/whatsnew/2.10.rst, pylint/lint/pylinter.py, pylint/lint/run.py, pylint/message/message_definition_store.py
Both options now show which messages can't be emitted with the current interpreter. This makes function more like their name implies. Code clearly shows in which order/format the messages are emitted.
This closes #4778
=> Refactor ``--list-msgs`` & ``--list-msgs-enabled``

tests/functional/r/regression/regression_4439.rc
This is a hot fix, the real fix escape me right now.
=> Hot-fix master following release of python 3.10-rc's new version

ChangeLog, doc/whatsnew/2.10.rst, pylint/checkers/strings.py, pylint/config/__init__.py, tests/functional/s/string/string_formatting.py, tests/functional/s/string/string_formatting.txt, tests/functional/s/string/string_formatting_error.py, tests/functional/s/string/string_formatting_error.txt
This adds a checker that checks strings with '%' or format() applied to them.
If no variables to be replaced are found the warning is emitted.
Closes #4042
=> Add ``format-string-without-interpolation`` checker

pylint/pyreverse/dot_printer.py, pylint/pyreverse/main.py, pylint/pyreverse/printer.py, pylint/pyreverse/vcg_printer.py, pylint/pyreverse/writer.py, tests/unittest_pyreverse_writer.py
Currently the logic to create diagrams is split between the ``Printer`` classes and the ``DiagramWriter`` classes.
In my opinion the responsibilities should be:
- ``DiagramWriter`` defines WHAT elements should be included in the diagram
- ``Printer`` handles HOW this needs to be translated into a format the desired tool (``dot``/Graphviz or ``vcg``, later on also PlantUML) understands
With the current implementation the ``DiagramWriter`` subclasses also hold a lot of logic how to construct the ``label`` of individual nodes (i.e. to include attributes and methods of the classes). However, how this label needs to be constructed is an implementation detail of the backend and thus should reside in the ``Printer`` classes.
This MR moves the logic inside the ``Printer`` classes.
Please note …
=> ``pyreverse``: Move creation of label from ``DiagramWriter`` to ``Printer`` 

ChangeLog, pylint/checkers/variables.py, tests/functional/a/assign/assignment_expression.py
```py
def foo() -> str:
return bar if (bar := "") else ""
```
Closes #4828
=> Fix false-positive used-before-assignment with := in Return node

ChangeLog, doc/whatsnew/2.10.rst, pylint/checkers/classes.py, pylint/checkers/python3.py, pylint/checkers/refactoring/refactoring_checker.py, pylint/checkers/stdlib.py, pylint/checkers/typecheck.py, pylint/extensions/code_style.py, pylint/lint/pylinter.py, script/bump_changelog.py, tests/functional/ext/code_style/code_style_consider_using_tuple.py, tests/functional/ext/code_style/code_style_consider_using_tuple.txt
Revert changes made in #4768 after discussion #4776.
=> Revert "Extended consider-using-tuple check to cover 'in' comparisons (#4768)"

ChangeLog, doc/tutorial.rst, doc/whatsnew/2.10.rst, pylint/lint/pylinter.py, pylint/lint/utils.py, pylint/utils/ast_walker.py, tests/lint/test_pylinter.py, tests/lint/test_utils.py, tests/lint/unittest_expand_modules.py
Permit to lint to the end in case of crash on a file and add a pre-filled issue template so it's easier to open an issue.
Will permit to keep using pylint when there is a crash on a code base. Also easier issue and probably more report.
Related to all the issue with a crash that are opened and completely prevent pylint from being run on a code base. I've done that prior to #4775
=> Permit to lint to the end in case of crash on a file

ChangeLog, doc/whatsnew/2.10.rst, pylint/checkers/refactoring/recommendation_checker.py, tests/functional/ext/code_style/code_style_consider_using_tuple.py, tests/functional/ext/code_style/code_style_consider_using_tuple.txt, tests/functional/u/undefined/undefined_loop_variable.py, tests/functional/u/use/use_sequence_for_iteration.py, tests/functional/u/use/use_sequence_for_iteration.txt
Part of https://github.com/PyCQA/pylint/issues/4776#issuecomment-890496656
It is more efficient to iterate over sequence types than sets.
```py
for x in {1, 2, 3}:  # [use-sequence-for-iteration]
pass
```
```py
for x in (1, 2, 3):
pass
```
=> Add `use-sequence-for-iteration` checker

ChangeLog, doc/whatsnew/2.10.rst, pylint/extensions/code_style.py, tests/functional/ext/code_style/code_style_consider_using_tuple.py, tests/functional/ext/code_style/code_style_consider_using_tuple.txt
Followup to https://github.com/PyCQA/pylint/pull/4835#issuecomment-898052028
* Add additional typing to `CodeStyleChecker`
* Limit `consider-using-tuple` to in-place defined lists to prevent double warnings.
* Emit `consider-using-tuple` even for starred expressions as they can be replaced as well.
```py
var = (1, 2, 3)
[*var]
(*var,)  # trailing comma is important
```
=> Improvements `consider-using-tuple`

CONTRIBUTORS.txt, ChangeLog, pylint/checkers/similar.py, tests/checkers/unittest_similar.py, tests/input/similar5
Ignore function decorators during similarities check if ignore signatures flag enabled.
Closes #4839
=> [duplicate-code] Ignore decorators lines by similarities checker when ignore signatures flag enabled

pylintrc
#4842 enabled the `Typing` plugin for pylint. At least for the moment it isn't of any help for us. This will change once support for Python 3.6 is removed.
This PR adds the necessary config for the extension.
--
Updating the `py-version` can probably be added as task in #4683.
=> Add pylintrc config for typing extension

ChangeLog, pylint/config/option.py
Pylint does support rich types in `.toml` config files. However when copying a `true` / `false` option back to a `pylintrc` file, it is an error.
This is how the conversion is done for `.toml` files:
https://github.com/PyCQA/pylint/blob/09ffc07fcb9ac2ac99d56b1d2c818ce93e509426/pylint/config/option_manager_mixin.py#L280-L284
```toml
reports = true
```
```ini
reports = yes
reports = true
```
=> Allow true / false in pylintrc

ChangeLog, doc/whatsnew/2.10.rst, pylint/pyreverse/dot_printer.py, pylint/pyreverse/main.py, pylint/pyreverse/plantuml_printer.py, pylint/pyreverse/printer.py, pylint/pyreverse/vcg_printer.py, pylint/pyreverse/writer.py, tests/pyreverse/conftest.py, tests/pyreverse/data/classes_No_Name.puml, tests/pyreverse/data/classes_colorized.dot, tests/pyreverse/data/classes_colorized.puml, tests/pyreverse/data/packages_colorized.dot, tests/pyreverse/data/packages_colorized.puml, tests/pyreverse/test_printer.py, tests/pyreverse/test_writer.py
This MR adds two command line options to ``pyreverse``:
* ``--colorized``: Use colored output. Classes/modules of the same package get the same color.
* ``--max-color-depth``: Use separate colors up to package depth of <depth>
This feature is usable with ``DotPrinter`` and ``PlantUmlPrinter``. 
``VCGPrinter`` will simply ignore the color passed to it. 
Closes #4488
=> ``pyreverse``: Add option for colored output

ChangeLog, doc/whatsnew/2.10.rst, pylint/checkers/refactoring/refactoring_checker.py, tests/functional/c/consider/consider_using_with_open.py
As discussed in #4748 the ``consider-using-with`` check should be suppressed on ``return`` statements.
The new proposal for ``consider-using-context-manager`` is not included in this MR. I think we should discuss the use cases where this message should - and especially should not - trigger before starting the implementation. 
Closes #4748
=> Suppress ``consider-using-with`` on return statements

ChangeLog, pylint/checkers/utils.py, tests/functional/i/import_aliasing.py, tests/functional/i/import_aliasing.txt
=> Fix crash on relative import beyond top-level package

CONTRIBUTORS.txt, ChangeLog, doc/whatsnew/2.10.rst, pylint/checkers/similar.py, tests/checkers/unittest_similar.py, tests/input/similar_cls_a.py, tests/input/similar_cls_b.py
Ignore class methods' and nested functions' signatures the same way as functions' with similarities "ignore-signatures" option enabled.
Closes #4653
=> [duplicate-code] Parse functions and class methods recursively when gathering signature lines

examples/custom.py, pylint/checkers/async.py, pylint/checkers/base.py, pylint/checkers/classes.py, pylint/checkers/deprecated.py
Followup to #4656
Use `an` alias for `astroid.nodes`.
=> Use alias for astroid.nodes 01

pylint/checkers/refactoring/refactoring_checker.py, pylint/extensions/bad_builtin.py, pylint/extensions/check_elif.py, pylint/extensions/code_style.py, pylint/extensions/confusing_elif.py, pylint/extensions/emptystring.py, pylint/extensions/redefined_variable_type.py, pylint/extensions/typing.py, pylint/pyreverse/diadefslib.py, pylint/pyreverse/diagrams.py, pylint/pyreverse/dot_printer.py, pylint/pyreverse/inspector.py, pylint/pyreverse/printer.py, pylint/pyreverse/utils.py, pylint/pyreverse/writer.py, tests/checkers/unittest_stdlib.py, tests/extensions/test_check_docs.py, tests/pyreverse/test_diadefs.py, tests/pyreverse/test_inspector.py, tests/pyreverse/test_utils.py
Followup to #4656
--
This should be the last PR. There might be a few places left that haven't been updated (especially regarding the functions from `astroid.nodes` -> we might still what to import them just from `astroid` ??? ). In the end though, it's probably best to deal with them once the old way is removed in astroid.
=> Use alias for astroid.nodes 04

pylint/checkers/base.py, pylint/checkers/classes.py, pylint/checkers/python3.py, pylint/checkers/refactoring/not_checker.py, pylint/checkers/strings.py, pylint/checkers/typecheck.py, pylint/checkers/utils.py, pylint/constants.py, pylint/extensions/redefined_variable_type.py, pylint/pyreverse/diadefslib.py
Replace the constant BUILTINS by the string 'builtins'
This make for clearer and also slightly faster code (means time
seems to decrease by 0.68% with this change alone (astroid/pylint)
in the pylint tests benchmarks). Done originally because we were using an
import from astroid from astroid.bases for one of those, which is
kinda messy.
=> ``astroid.const.BUILTINS`` use removed for clarity and so astroid can also removes it later

pylint/extensions/code_style.py
Small refactoring in the `CodeStyle` extension.
Commit was originally part of #4853.
=> Refactor existing code - code_style extension

ChangeLog, pylint/checkers/base.py, pylint/checkers/deprecated.py, pylint/checkers/logging.py, pylint/checkers/stdlib.py, pylint/checkers/utils.py
While looking at the pylint call graph https://github.com/PyCQA/astroid/issues/1115#issuecomment-890961827, I noticed that some parts aren't properly utilizing caching. This seems to be especially the case for `Call` nodes, which often use
```py
try:
for inferred in node.func.infer():
...
except astroid.InferenceError:
pass
```
We can't use `safe_infer` for that as it will only return one value. Thus I've created a new helper function for it, that will also be cached.
--
Difficult to say if that will significantly improve performance, but it might be worth a try.
@robin-wayve Would you be able to test these changes?
=> Add cached infer_all helper function

ChangeLog, pylint/checkers/typecheck.py, tests/checkers/unittest_typecheck.py
Ref https://github.com/PyCQA/pylint/pull/4870#discussion_r691830356
Previously, the `invalid-metaclass` message prints out the full class text when given an `Instance` of a `ClassDef`. I added a check so that their repr (`Instance of ...`) would be displayed instead.
As a comment, because `bases.Instance` has some subclasses like `nodes.Const` and `nodes.Dict` where we *do* want to call `as_string`, I used an unidiomatic type check to pull out `Instance` objects directly. Not amazing, but I left a comment explaining why. I feel like astroid should support a separate subclass of `Instance` for "instance of a class with an unknown value" to differentiate it from `Const`/`Dict`/etc.
=> Improve invalid-metaclass error message for Instances

ChangeLog, doc/whatsnew/2.10.rst, pylint/checkers/base.py, pylint/checkers/imports.py, pylint/checkers/misc.py, pylint/checkers/typecheck.py, pylint/config/option_manager_mixin.py, pylint/epylint.py, pylint/extensions/bad_builtin.py, pylint/extensions/consider_ternary_expression.py, pylint/lint/report_functions.py, pylint/pyreverse/dot_printer.py, tests/functional/ext/consider_ternary_expression.py, tests/functional/ext/consider_ternary_expression.rc, tests/functional/ext/consider_ternary_expression.txt
=> Add consider-if-expression extension

ChangeLog, pylint/config/__init__.py
=> pylint does not crash when PYLINT_HOME does not exist

ChangeLog, pylint/config/__init__.py, setup.cfg, tests/lint/unittest_lint.py
Black already did the migration, the import time also got faster see https://github.com/psf/black/pull/2375. A worthy import time goal for astroid 😄 
Closes #4886
=> Migrate from ``appdirs`` to ``platformdirs``

setup.cfg
Update `platformdirs` requirement to `>=2.2.0`.
Version `2.1.0` added typing support: https://github.com/platformdirs/platformdirs/releases/tag/2.1.0
Version `2.2.0` added a fallback if the `XDG` environment variable is empty: https://github.com/platformdirs/platformdirs/releases/tag/2.2.0
No changelog entry require as no pylint version with `platformdirs` has been released yet.
=> Require platformdirs 2.2.0

.github/workflows/ci.yaml, .pre-commit-config.yaml, setup.cfg
https://github.com/PyCQA/pylint/pull/4887#discussion_r693329085 mentioned that `platformdirs` is now fully typed.
To be able to remove the import ignore from `setup.cfg`, we would need to add `platformdirs` as an additional dependency in `.pre-commit-config.yaml`. Long term it might be better to just run mypy in the local environment instead.
If the PR is accepted, I'll update `astroid` as well.
=> Updated mypy checks

ChangeLog, pylint/checkers/stdlib.py, tests/functional/r/regression/regression_4891.py
=> Fix a crash from astroid.InferenceError raised on copy.copy

.readthedocs.yaml, ChangeLog, doc/user_guide/message-control.rst, setup.cfg
https is now prefered in the documentation and http://pylint.pycqa.org correctly redirect to https://pylint.pycqa.org
Closes #3802
=> Better read the doc configuration

ChangeLog, doc/whatsnew/2.11.rst, pylint/checkers/base.py, tests/functional/f/function_redefined.py, tests/functional/f/function_redefined.txt
Fix false positive for `function-redefined` for simple type annotations.
Closes #4936
=> Fix false positive for `function-redefined` for simple type annotations

ChangeLog, doc/whatsnew/2.10.rst, doc/whatsnew/2.11.rst, pylint/checkers/classes.py, tests/functional/a/access/access_to_protected_members_typing.py, tests/functional/a/access/access_to_protected_members_typing.rc
Fix false positive protected-access in typing
Class functions can return protected members which can then be passed as arguments to other functions.
When using type hints in function definitions these raised a message which they shouldn't do.
I did not create an issue for this so no issue is assigned, if needed I can still do this
I also saw some discrepancies between the `Changelog` and the `2.10` & `2.11` files. I fixed these and added the customary styling of the `whatsnew` documents to the `2.11`. I thought this might be helpful, but let me know if I should remove or change that commit!
=> Fix false positive ``protected-access`` in typing 

ChangeLog, doc/whatsnew/2.11.rst, pylint/checkers/typecheck.py, tests/functional/d/dict_iter_missing_items.py, tests/functional/d/dict_iter_missing_items.txt
This fixes a false positive emitted for dictionaries that contain only
tuples as keys. This makes unpacking the dictionary without calling `.items()` valid.
This closes #3283
=> Fix false pos. `dict-iter-missing-items` for tuple keys

pylint/checkers/base.py
In Python 3 `exec` is just a normal `Call` node. `exec-used` is still checked.
=> Remove dead visit_exec method

ChangeLog, pylint/checkers/exceptions.py, tests/functional/i/invalid/e/invalid_exceptions_raised.py, tests/functional/i/invalid/e/invalid_exceptions_raised.txt
Apparently this use case was supposed to be handled by the py3K checker but as it was disabled all the time the issue has'nt been handled at all for a long time.
=> Fix the ``raising-bad-type`` warning for string

ChangeLog, doc/whatsnew/2.11.rst, pylint/checkers/format.py, tests/checkers/unittest_format.py, tests/functional/s/super/superfluous_parens.py, tests/functional/s/super/superfluous_parens.txt
Tuples can be created with inner tuples. This creates double parenthesis which we flagged incorrectly.
This closes #4907
=> Fix false positive ``superfluous-parens`` for tuples

requirements_test_min.txt, tests/lint/test_pylinter.py
`pylint` already uses `typing-extensions`. There is no need to add `mypy-extensions` as well. Ref #4950
https://docs.python.org/3/library/typing.html#typing.NoReturn
=> Remove test dependency mypy-extensions

ChangeLog, doc/whatsnew/2.11.rst, pylint/checkers/refactoring/refactoring_checker.py, tests/functional/c/consider/consider_using_in.py, tests/functional/c/consider/consider_using_in.txt
`consider-using-in` doesn't need to be limited to `Name` nodes. `Attribute` once work too.
```py
class A:
def __init__(self):
self.a = 2
def func(self):
var = self.a
if var == 2 or var == 3:
print()
if self.a == 2 or self.a == 3:  # new
print()
=> Extend consider-using-in for attribute access

tests/functional/ext/code_style/code_style_consider_using_assignment_expr.py
Small test case to make sure pylint doesn't emit `consider-using-assignment-expr` for attribute access. Assignment expressions only work for `Name`.
=> Add additional test case - consider-using-assignment-expr

ChangeLog, doc/whatsnew/2.11.rst, pylint/checkers/similar.py, tests/checkers/unittest_similar.py
This makes it so that setting ``min-similarity-lines`` to zero exits the
similarity code checker with a successful exit.
This closes #4901
=> Make ``min-similarity-lines == 0`` stop similarity check

pylint/extensions/code_style.py, pylint/extensions/typing.py, pylint/utils/utils.py
The next step in splitting #4954 in more manageable PR's.
I opted to go for `overload` as it allows us to immediately tell what ``get_global_option`` will return or throw an error if it is unspecified.
The globals added to `pylint/utils/utils.py` could go in `pylint/typing` but since they won't be used outside of this file I thought it would be best to add them here.
Sorry for making a second PR. The fix turned out to be much easier than anticipated.
=> Use ``overload`` to type ``get_global_option``

ChangeLog, doc/whatsnew/2.11.rst, pylint/config/__init__.py
By changing the function used to create the cache from ``os.mkdir`` to ``os.makedirs`` we now handle non-existing parent directories correctly.
This closes #4900
This was one of the final open issues on the `2.11.0` milestone! 😄
=> Fix bug with cache's parent directory not existing

ChangeLog, doc/whatsnew/2.11.rst, pylint/checkers/utils.py, pylint/checkers/variables.py, tests/functional/g/globals.py, tests/functional/g/globals.txt, tests/functional/u/unused/unused_variable.py, tests/functional/u/unused/unused_variable.txt
This checker now checks whether the names after the global keyword are reassigned in the local scope.
I created a small `utils` function that checks whether the name appears in any of the `AssignName` nodes in the scope.
The updated test only throws an error for 2 of the 4 variables. Not quite sure what that is about and we might want to make another issue/PR to fix that. However, since the change did not break any of the tests the file is designed for I guessed it was okay for now. This PR does fix the original issue.
This closes #1375
This closes #330
=> Make ``global-variable-not-assigned`` check local scope

examples/custom_raw.py, pylint/checkers/format.py, pylint/checkers/misc.py, pylint/checkers/similar.py, pylint/checkers/strings.py, pylint/config/man_help_formatter.py, pylint/config/option_manager_mixin.py, pylint/extensions/empty_comment.py, pylint/interfaces.py, pylint/lint/pylinter.py, pylint/message/message_handler_mix_in.py, pylint/reporters/ureports/__init__.py, pylint/testutils/lint_module_test.py, pylint/utils/utils.py, tests/benchmark/test_baseline_benchmarks.py, tests/test_check_parallel.py
The next instalment of breaking up #4954 into more manageable PR's. 
This PR is based on two related commits which I felt should be part of the same PR as they deal with a similar topic.
The first is annotation of all implementations of `process_module`. This is fairly straightforward and covers adding `nodes.Module` to the typing of the parameter and changing `module`, `astroid` and other parameter names to the new standard of `node`. As `process_module` calls `node.stream()` often this seemed like a good first step to this PR.
The second commit covers annotation of (most) functions with a reference to `stream`, `filestream` or a similar parameter. There are two important comments about …
=> Add typing to references of ``stream`` and ``stream()``

ChangeLog, pylint/message/message_id_store.py, tests/functional/u/use/use_symbolic_message_instead.py, tests/functional/u/use/use_symbolic_message_instead.txt
=> Fix false negative for use-symbolic-message

ChangeLog, doc/whatsnew/2.11.rst, pylint/checkers/classes.py, tests/functional/u/unused/unused_private_member.py, tests/functional/u/unused/unused_private_member.txt
Fix false positive for ``unused-private-member`` when accessing attribs in class using ``cls`` by extending logic
Closes #4681
=> Fix false positive ``unused-private-member`` for accessing attributes in a class using ``cls``

tests/checkers/unittest_stdlib.py
Following the deprecations in astroid a test was raising deprecation warning.
=> Fix deprecation warning for AssignAttr in tests

CONTRIBUTORS.txt, tests/functional/n/no/no_member_nested_namedtuple.py, tests/functional/n/no/no_member_nested_namedtuple.rc
This PR adds a functional test that's demonstrating #4370. The test should become green once PyCQA/astroid#1166 is merged and astroid is released.
(Oh, and i took the liberty to update my last name in contributors list.)
Closes #4370.
=> Fix #4370: false-positive no-member in class based on typing.NamedTuple

pylint/checkers/base.py, pylint/checkers/raw_metrics.py, pylint/lint/report_functions.py
/CC @cdce8p 
This changes some occurrences of `lines` to become lists
=> Change `lines` to lists

setup.cfg, tests/pyreverse/test_diadefs.py, tests/pyreverse/test_writer.py
Fix an import error due to pytest adding all file to the pythonpath before launching tests.
=> Fix PyreverseConfig imports in pyreverse's tests

pylint/testutils/pyreverse.py, tests/pyreverse/conftest.py, tests/pyreverse/test_diadefs.py, tests/pyreverse/test_writer.py
See : https://github.com/PyCQA/pylint/pull/5010#issuecomment-920291278
=> Move PyreverseConfig to pylint.testutil

pylint/checkers/imports.py, pylint/reporters/ureports/nodes.py
Quick and easy change as suggested by myself in https://github.com/PyCQA/pylint/pull/5004#discussion_r708532947
/CC @Pierre-Sassoulas
=> Move methods to `BaseLayout`

pylint/checkers/__init__.py, pylint/checkers/imports.py, pylint/interfaces.py, pylint/lint/report_functions.py, pylint/reporters/__init__.py, pylint/reporters/collecting_reporter.py, pylint/reporters/multi_reporter.py, pylint/reporters/reports_handler_mix_in.py, pylint/reporters/ureports/base_writer.py, pylint/reporters/ureports/nodes.py, pylint/reporters/ureports/text_writer.py
This add typing in ``pylint.reporters`` in order to add typing little by little in the code base. Necessary for easier evolution of json output for 3.0.
=> Add typing in ``pylint.reporters``

ChangeLog, pylint/checkers/stdlib.py, tests/functional/u/unspecified_encoding_py38.py, tests/functional/u/unspecified_encoding_py38.txt
=> Fix ``unspecified-encoding`` for `Path()`
